### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by darbaoui** [vuejs/vuepress#100]
How i can add logo to nav bar.
any suggestion.

**Comment by dyhpoon** [comment]
you can define a `logo` property in your theme config

For example
```
themeConfig: {
    logo: '/logo.png',
}
```

**Comment by darbaoui** [comment]
thanks @dyhpoon , but **title** text still appear with logo, how i can display only logo, if  i remove the title from `module.exports ` the logo appear only but no title in head pages

**Comment by dyhpoon** [comment]
I dont think you can do it with the default theme. Perhaps you need to create your own theme.

**Comment by yyx990803** [comment]
Yeah, we don't want to make everything config based for the default theme. You can eject and tweak it yourself though.

**Comment by chrtz** [comment]
I added the **pageClass** to the root **README.md**'s YAML.
And defined a _custom CSS_ rule in the **override.styl** afterwards to hide the span.

Actually there seem to be an autohide in **default-theme navbar component** (https://github.com/vuejs/vuepress/blob/master/lib/default-theme/Navbar.vue)
if a logo is defined, but this didn't work for me, too.

**Comment by leaanthony** [comment]
I did this by setting the title to a single space:
```
heroText: " "
```

**Comment by jazzandrock** [comment]
I did this by 

```styl
.site-name.can-hide
    display: none
```
