### ISSUE TITLE
Error reporting while using nprogress build(document is not defined)

### ISSUE THREAD

**Issue by songStar0904** [vuejs/vuepress#1000]
hi, when i used `npm run docs:build`, error
![image](https://user-images.githubusercontent.com/21984603/48469498-07af4e80-e82a-11e8-9003-ccaacbdc4052.png)

```md
    return !!document.getElementById('nprogress');
    ^

ReferenceError: document is not defined
    at Object.NProgress.isRendered (server-bundle.js:5597:5)
    at Object.NProgress.render (server-bundle.js:5550:19)
```
but when i used `npm run docs:dev`, it was normal.
```
version:
"vuepress": "^0.14.4"
 "nprogress": "^0.2.0"
```

**Comment by ulivz** [comment]
[Browser API Access Restrictions](https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions)
