### ISSUE TITLE
Extra markdown plugins in extendMarkdown-config aren't working

### ISSUE THREAD

**Issue by mariovde** [vuejs/vuepress#1001]
- [x] I confirm that this is a issue rather than a question.

## Bug report

Documentation stated that you can use custom markdown-it-xxx plugins. 
Wanted to register a new custom container name, but didn't work.

#### Version
vuepress 0.14.5

#### Steps to reproduce

1) open config.js in .vuepress
2) add the following block to your config 
markdown: {
    anchor: { permalink: false },
    toc: { includeLevel: [1, 2] },
    extendMarkdown: md => {
      md.use(require("markdown-it-container"), "card");
    }
  }
3) restart your vuepress server

#### What is expected?
I expect - when I use the following code in my *.md files - it gets renderd into a div with class "card"
::: card
this is the content for the card
:::

#### What is actually happening?
A p-tag is rendered with ::: card this is the content for the card ::: in it

#### Other relevant information

- Your OS: Mac os 10.12.6 (16G1510)
- Node.js version: v8.11.1
- Browser version: Chrome  70.0.3538.77
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
`extendMarkdown` are only available in 1.x, in 0.x you should use `markdown.config`.

See [Migration from 0.x > markdown.config](https://vuepress.vuejs.org/miscellaneous/migration-guide.html#markdown-config).

**Comment by mariovde** [comment]
That's because markdown-it-container' is a custom module I've written. 
If you don't have custom modules, just remove the line: 

      md.use(require('markdown-it-container'),

**Comment by davision** [comment]
I don't think so `markdown-it-container` is a custom module. It's markdown-it plugin which I want to extend.

**Comment by vSanjo** [comment]
@davision, did you find a fix for this?

**Comment by AGachet** [comment]
Same issue at my side with the current version of vuePress (1.0.2). 

I'm working following this [documentation](https://vuepress.vuejs.org/guide/markdown.html#advanced-configuration) and this [library to extend snippets](https://www.npmjs.com/package/markdown-it-vuepress-code-snippet-enhanced) but the syntax explain on plugin documentation ins not interpreted. 

@[code](@/docs/code.js) works as a link :/

**Comment by AGachet** [comment]
ok, solve... it's a...documentation problem XD

The solution is [here](https://v1.vuepress.vuejs.org/guide/markdown.html#advanced-configuration), it's easy to think that the link above is for the latest version of vuePress (I think it should be good to add v0.X on the title as for the new version.
