### ISSUE TITLE
Q: dynamic extension of `config.themeConfig.nav`

### ISSUE THREAD

**Issue by CrossEye** [vuejs/vuepress#1002]
First, an apology.  This is a question, not an issue.  I simply could not find any reference to a place for discussions.  If you want to point me to one, I'll close this and ask there.

----------

Can I extend `config.themeConfig.nav` with information gathered from `$site.pages`?

I'm starting to build an in-house documentation site for my day job.  My favorite option so far has been VuePress.  I really don't know Vue itself, so my question may be naive.

It's not clear how to do something I'd like, nor even whether it's possible.  I want to have a dynamic top menu derived from some site metadata.  I'm using the default theme.  I've added tags, based on [Roy Greenfeld's technique][rg] but would also like to add a navbar menu that lists the top ten tags plus a link to the full list of tags.  The navbar configuration is in `.vuepress/config.js`.  So again is there a way to extend `config.themeConfig.nav` dynamically with information from `this.$site.pages`?  Or is there some other way to accomplish this dynamic menu?

  [rg]: https://code.roygreenfeld.com/cookbook/adding-tags-to-vuepress.html

**Comment by bretterer** [comment]
I would suggest asking this question in StackOverflow as it will give you some more visibility

**Comment by mariovde** [comment]
Can't you just create a custom component 'customMenu" and pass it the this.$site.pages as a property.

that way you have full control over how the navigation is structured, rendered...

**Comment by CrossEye** [comment]
@bretterer: I will ask there.  Thanks.

@mariovde: Perhaps.  This was meant to be one menu entry of several on the navbar, so I thought it had to use the theme configuration, but I'm just learning my way through the model.  I may have to learn a bit more about both Vue and VuePress.  Can more than one component be placed in a single slot?

**Comment by CrossEye** [comment]
@bretterer: Thank.  Just looking at other StackOverflow questions seems to have set me down the right path.
