### ISSUE TITLE
@vuepress/plugin-last-updated crashes on GitLab Pages

### ISSUE THREAD

**Issue by Ambyjkl** [vuejs/vuepress#1007]
- [x] I confirm that this is a issue rather than a question.

## Bug report
@vuepress/plugin-last-updated uses the `git` command's `stdout` output to determine when a particular file was updated. But the issue is, for some reason on GitLab, `spawn.sync.stdout` is `null`, which causes the function to throw an error "Cannot read property toString of null".
#### Version
The latest version as of now 1.0.0-alpha.22
#### Steps to reproduce
1. Create a vuepress project on gitlab
2. Trigger `vuepress build` on the Gitlab CI environment.

Here's my repo for reference, with the failing build:

https://gitlab.com/Ambyjkl/strange-dreams/-/jobs/120764389
#### What is expected?
The build succeeds
#### What is actually happening?
The build fails with aforementioned error.
#### Other relevant information
I think it's due to some funny business in the communication from a process inside a docker container to a one outside (I'm not quite sure how that happens, I'm still in the process of figuring it out)
- Your OS: Alpine Linux (CI environment)
- Node.js version: 10.12.0 (node:alpine)
- Browser version: Doesn't matter in this case
- Is this a global or local install? Local
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
I just made sure the build passes in 2a4e37f, but last-updated will not be available in your build context because there is no `git` in your build context.

To solve this, please ensure that you are using `git clone` to pull your source code.
