### ISSUE TITLE
Markdown in Frontmatter

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#101]
Hey there!

What would you do, if you wanted to highlight a few words in the features of the homepage with markdown? 
Markdown in frontmatter is not parsed and also cannot reliably, possibly. Because some values are turned into the appropriate format. e.g. false -> boolean, or 2018-03-20 is a Date object.
I wonder if I should write custom components and then use them instead of frontmatter, so I can work around the limits like so:

``` html
<Feature>
    <template slot="description">
        **special** features to describe here.
    </template>
</Feature>
```

But then, I could also almost just start writing plain HTML.

I want the flexibility of layouts and metadata attached to articles, but still define and re-use some common components.
Maybe I could also abuse custom containers for this- but they also just define two properties: title and text body. But at least I could leverage markdown for the task.

**Comment by yyx990803** [comment]
Thought a bit about this and I don't think we'll extend the home page functionality any further, because you can just use plain HTML after the frontmatter:

```
---
home: true
---

<div class="features">
  <div class="feature">
    <h2>A feature</h2>
     <p>some <strong>text</strong></p>
  </div>
</div>
```

While being able to write markdown for this is easier, it involves a lot more complexity in the implementation so it's not worth the effort IMO.

**Comment by MartinMuzatko** [comment]
Thanks for the reply @yyx990803, The features were just an example. I agree on not further expanding the homepage.

I use front matter as a mechanism to use the content in different areas of the page. E.g. a description/teaser-text part of the header, and then continue with the usual content.

I was also thinking about implementing this with multiple `<Content />` outlets, like Vues slot mechanism. Maybe that is too complex as a feature. What do you think?
