### ISSUE TITLE
Prev/Next Links not appearing on Page.vue

### ISSUE THREAD

**Issue by eunjae-lee** [vuejs/vuepress#1010]
- [x] I confirm that this is a issue rather than a question.

#### Version

Reproduced in the following versions:
* 0.14.5
* 1.0.0-alpha.18
* 1.0.0-alpha.22

#### Steps to reproduce

1. Clone this repo: https://github.com/eunjae-lee/vuepress-bug-reproduction
2. `npm run dev`
3. Visit `http://localhost:8080/Second%20Document.html`

#### What is expected?

On every page I should see Prev/Next Links (if exists)

#### What is actually happening?

On a page which contains white space in its filename, I don't see any Prev/Next Links at the bottom.

#### Other relevant information

- Your OS: macOS 10.12.6
- Node.js version: 8.11.1
- Browser version: Google Chrome 70.0.3538.102
- Is this a global or local install? local install
- Which package manager did you use for the install? npm

Here's what I've found so far. It seems VuePress tries to match current page from `sidebarItems` and get corresponding prev/next pages.

![screen shot 2018-11-16 at 7 24 41 pm](https://user-images.githubusercontent.com/499898/48619482-a0cf9800-e9d7-11e8-918a-798814a67c98.png)

Here you can see the path of current `$page` is `/Second%20Document.html`. The whitespace is encoded there, which seems okay.

![screen shot 2018-11-16 at 7 24 31 pm](https://user-images.githubusercontent.com/499898/48619484-a7f6a600-e9d7-11e8-8d6c-633bc12975de.png)

Here you can see the path from `sidebarItems` and there the whitespace is not encoded. So VuePress cannot match current page.

**Comment by ulivz** [comment]
Thanks for the report, fixed it at e8d728f for 1.x.

**Comment by eunjae-lee** [comment]
@ulivz Thanks!
After filing this issue, I realised I didn't have to put whitespace in the filename but like this:

second-document.md
```
# Second Document
```

I saw that still behaved as I expected.
