### ISSUE TITLE
Header anchor link clicks don't change current URL

### ISSUE THREAD

**Issue by dcastil** [vuejs/vuepress#1011]
- [x] I confirm that this is a issue rather than a question.

## Bug report

When I click on the `#` in the header anchor of any heading, the page scrolls to the heading but the anchor doesn't appear in the URL.

#### Version

v1.0.0-alpha.22

#### Steps to reproduce

```bash
# Clone vuepress repo
git clone git@github.com:vuejs/vuepress.git && cd vuepress

# Remove '@vuepress/active-header-links' from plugins in theme-default
sed -i '21d' ./packages/@vuepress/theme-default/index.js

# Start docs
yarn && yarn dev
```

#### What is expected?

After visiting `http://localhost:8080/guide/` and clicking `#` next to the heading `How It Works`, the current URL is `http://localhost:8080/guide/#how-it-works`.

#### What is actually happening?

Current URL remains `http://localhost:8080/guide/`.

#### Other relevant information

- Your OS: Mac OS Mojave v10.14.1 
- Node.js version: v10.13.0
- Browser version: Chrome v70.0.3538.102 and Safari 12.0.1
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
Why removing '@vuepress/active-header-links' from plugins in theme-default?

**Comment by dcastil** [comment]
@ulivz As the plugin automatically inputs the last trespassed anchor into the URL, it‘s not possible to show that the anchors don‘t work when the plugin is active.

In my private project I use vuepress with a custom ejected theme and don‘t want to use the plugin. But the anchors are broken because of that.
