### ISSUE TITLE
Palette link in docs broken

### ISSUE THREAD

**Issue by matjaeck** [vuejs/vuepress#1019]
- [x] I confirm that this is an issue rather than a question.

`[palette](../config/README.md#palette)` in https://github.com/vuejs/vuepress/blame/master/packages/docs/docs/theme/writing-a-theme.md#L32 should be `[palette](../config/README.md#palette-styl)`

One would expect that the link to the not existing anchor tag took you to the top of the page but instead it scrolls down a bit. There is probably something else going wrong (maybe related to #1016).

**Comment by ulivz** [comment]
Thanks, updated at 2b40e7e
