### ISSUE TITLE
"Using a theme" link in docs broken

### ISSUE THREAD

**Issue by matjaeck** [vuejs/vuepress#1020]
`[Using a theme](../theme/README.md#using-a-theme)` in https://github.com/vuejs/vuepress/blame/master/packages/docs/docs/config/README.md#L171` should be `[Using a theme](../theme/using-a-theme.md)`

- [x] I confirm that this is an issue rather than a question.

**Comment by ulivz** [comment]
Thanks, updated at b123e18
