### ISSUE TITLE
Rename "README.md" files to "index.md"

### ISSUE THREAD

**Issue by matjaeck** [vuejs/vuepress#1021]
## Feature request

`README.md` is too specific for generic root content files and can be misleading. #23 allows to use `index.md`.

#### What problem does this feature solve?
`README` is the established name for contextual documentation files. Using this name can be misleading for newcomers and `index.md` makes it easier to understand what the purpose of the file is. 

I understand that everyone is free to use either `README` or `index` but note that many people will follow your example here, check out how it's done in your `docs` and at least for me it was not obvious while reading the documentation that README files are treated as index files or that the naming is meaningful at all.

https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Page.vue#L127 probably needs to be changed, too.

**Comment by ulivz** [comment]
Both of them are supported, using index.md or README.md is up to you. See https://github.com/vuejs/vuepress/pull/23.

**Comment by matjaeck** [comment]
In this case it should be explained in the docs. You probably missed the edit I submitted just when you closed this.

**Comment by matjaeck** [comment]
Also, please check if 

> https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Page.vue#L127 probably needs to be changed, too.

If I understand it correctly, index.md breaks the edit links.

**Comment by matjaeck** [comment]
> Our original intention is that writing two programs in the document at the same time may make the novice fear: which solution should I choose?

My suggestion here is to use index.md as the only standard for root content files. README is as described not a good name and can cause conflicts in github environments. Replace README with index, then add a paragraph in the docs that explains the purpose and usage of index.md files. I'm willing to contribute to the docs once I've learned more about it, for now I can only help with reporting issues.

> To avoid problems, it is recommended that you use the README for now.

Alright, good to know.

**Comment by viktorsmari** [comment]
This is a top hit on Google, but how do you use README.md as a 'normal readme' and not as a website?
I wanted to use the README.md as a guide how to set up the project.

So, I want to disable what VuePress does out of the box (converting a README.md to an index.html) 
and simply use a index.md instead.

Is this easily possible? (And why on earth is it not the default behaviour)

**Comment by veidenberg** [comment]
> This is a top hit on Google, but how do you use `README.md` as a 'normal readme' and not as a website?

After some digging, I found that fortunately the default filename selection is slightly different for VuePress and Github. To target readmes for both, rename the GitHub readme as `README.markdown` and Vuepress file as `index.md` or `readme.md`.

**Comment by rickalex21** [comment]
Thanks to #23 I figured out that I don't want to make changes because this may conflict with future plugins? Coming from hugo using 'index.md' is a page and '_index.md' is a list page. In vuepress by the looks of it you have to render a component on Page.vue to make it list page. I'm sure there's a way to use frontmatter instead ```kind:list``` instead of using this in my markdown. 

```html
<Posts page="code" />
```

**Comment by fPkX6F1nGTX** [comment]
I just asked a question over here but if anyone on this thread can answer, please do so:
https://github.com/vuejs/vuepress/pull/23#issuecomment-2271567925

**Comment by fPkX6F1nGTX** [comment]
> I just asked a question over here but if anyone on this thread can answer, please do so: [#23 (comment)](https://github.com/vuejs/vuepress/pull/23#issuecomment-2271567925)

Also please contribute to discussion here which implies index.md would NOT be allowed (as of late 2021):
https://stackoverflow.com/a/69190614/12763497
