### ISSUE TITLE
Single page output

### ISSUE THREAD

**Issue by benmccann** [vuejs/vuepress#1023]
## Feature request

I would like the ability to have the output all concatenated together into a single page

#### What problem does this feature solve?

The user could then use either version: the version with numerous pages that can be navigated to via the sidebar or the single page version with everything in a single page.

Sometimes I prefer the single page view so that I can use Ctrl+F, print everything out or save it as pdf, etc.

#### What does the proposed API look like?

`themeConfig.sidebar` could be used to control the order in which to concatenate the pages so as to not make the user specify the order of pages in two places. These could also be included as a table of contents in the single page version which could take the user to the appropriate place via anchor tags

#### How should this be implemented in your opinion?

I'm not familiar with the vuepress codebase to know what the major design decisions would need to be

#### Are you willing to work on this yourself?**

No, unfortunately, I would not have time

**Comment by ulivz** [comment]
Also, I guess this feature is related to PDF output.

**Comment by ulivz** [comment]
Well, you can try [vuepress-plugin-export](https://github.com/ulivz/vuepress-plugin-export).
