### ISSUE TITLE
The packaged product is too large

### ISSUE THREAD

**Issue by youxfans** [vuejs/vuepress#1031]
- [ x ] I confirm that this is a issue rather than a question.

## Bug report

The packaged product is too large, I use Lighthouse to analyze performance, the indicators are not good.

#### Version

"vuepress": "^1.0.0-alpha.13"

#### Steps to reproduce

https://developers.uc.cn/

#### What is expected?

Within the [lighthouse](https://developers.google.com/web/tools/lighthouse/) standard.

#### What is actually happening?

Lighthouse indicators are not good.

#### Other relevant information

- Your OS: mac
- Node.js version: 8.11
- Browser version:  chrome 70
- Is this a global or local install?  local
- Which package manager did you use for the install? tnpm

**Comment by ulivz** [comment]
Besides, the lighthouse  performance test result of vuepress's website.

![image](https://user-images.githubusercontent.com/23133919/48911868-037cd400-eeaf-11e8-9a30-5454291e4bc8.png)
