### ISSUE TITLE
Sidebar Issues

### ISSUE THREAD

**Issue by sharanraj124** [vuejs/vuepress#1033]
![screen shot 2018-11-21 at 6 23 59 pm](https://user-images.githubusercontent.com/41563058/48842702-ed8de700-edba-11e8-8766-d11657665d99.png)

I want to this type of sidebar. I try to many ways but not working. how to create ?????

**Comment by HerrBertling** [comment]
@sharanraj124 If you have solved this, it might be helpful to share some code or a link to a repo/file for people running into similar problems :)
