### ISSUE TITLE
nested sidebar issue?

### ISSUE THREAD

**Issue by sharanraj124** [vuejs/vuepress#1034]
I try to add nested sidebar for my vuepress docs. I use default vuepress theme. I have added sample code below. but its not working.       
```
 {
            title: 'Test',
            collapsable: true,
            children: [
            ['/test/san', 'SAN'],
                {
                    title: 'sample',
                    collapsable: true,
                    children: [
                    ['/test/sample/can', 'CAN'],
                        {
                            title: 'foo',
                            collapsable: true,
                            children: [
                              ['/test/sample/foo/vel', 'VEL'],
                            ]
                        }
                    ]
                },
            ]

**Comment by sharanraj124** [comment]
sorry. I need how to add nested sidebar in vuepress docs.

**Comment by matjaeck** [comment]
Github is not a support forum and tagging maintainers to get help with individual problems not very nice. I suggest you check out the default theme and how it is done there, check the docs directory in this repo and then move on from there.

**Comment by ulivz** [comment]
Advise you to be kind and able to **provide a reproduction repo** instead of letting me try to imagine and create your context.

Also, if you expect others to help you, please DON'T delete the issue template
