### ISSUE TITLE
cannot resolve modules 

### ISSUE THREAD

**Issue by Genuifx** [vuejs/vuepress#1036]
- [x] I confirm that this is a issue rather than a question.

## Bug report
cannot resolve 'register-service-worker' in @vuepress/pluign-pwa
cannot resolve 'vue-toasted' in @vuepress/plugin-notification

#### Version
"vuepress": "^1.0.0-alpha.23",
"@vuepress/plugin-notification": "^1.0.0-alpha.23",
"@vuepress/plugin-pwa": "^1.0.0-alpha.23",

#### Steps to reproduce

1. install vuepress globally
2. install @vuepress plugin in repo.
3. run `vuepress dev`

#### What is expected?
could be resolved.

#### What is actually happening?
show Error.

#### Other relevant information

- Your OS: MacOS
- Node.js version: node10
- Browser version: N/A
- Is this a global or local install? global
- Which package manager did you use for the install? npm

the path to fix:
-. install vuepress in the repo and run `npx vuepress dev`
-. install all plugin globally.  (not good at all.)

**Comment by ulivz** [comment]
`npx vuepress dev` with a globally installed vuepress? 

Sorry but I cannot reproduce, feel free to continue if you can provide a valid repro.
