### ISSUE TITLE
TypeError: Cannot read property 'toString' of null at exports.getGitLastUpdatedTimeStamp

### ISSUE THREAD

**Issue by jaipradeesh** [vuejs/vuepress#1037]
- [x] I confirm that this is a issue rather than a question.

## Bug report

```
WAIT Extracting site metadata... TypeError: Cannot read property 'toString' of null at exports.getGitLastUpdatedTimeStamp (/usr/lib/node_modules/vuepress/lib/prepare/util.js:79:84) at Promise.all.pageFiles.map (/usr/lib/node_modules/vuepress/lib/prepare/resolveOptions.js:137:26) at Array.map (<anonymous>) at resolveOptions (/usr/lib/node_modules/vuepress/lib/prepare/resolveOptions.js:128:49) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7) The command '/bin/sh -c vuepress build docs -d public/docs' returned a non-zero code: 1
```
#### Version
0.14.5

#### Steps to reproduce
`/bin/sh -c vuepress build docs -d public/docs`

#### What is expected?

Expected to build

#### What is actually happening?

Build failed

#### Other relevant information

- Your OS: Linux/amd64 // docker // alpine-3.8
- Node.js version: 10.13.0
- Browser version:
- Is this a global or local install? Both
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Could you provide a reproduction repo?

**Comment by ulivz** [comment]
Thanks for the report, try `0.14.6` or `1.x`
