### ISSUE TITLE
Favicon Support

### ISSUE THREAD

**Issue by sambeevors** [vuejs/vuepress#1038]
#### What problem does this feature solve?
Currently no way (to my knowledge) to add a favicon to a VuePress site without "getting hacky". This fixes that in a way that promotes PWA best practises.

#### What does the proposed API look like?
You could simply add it as an option to the `config.js`
```js
module.exports = {
  favicon: 'logo.png'
}
```
and then add the referenced icon in your `dist` folder, everything else will be handled automatically. Logo could be PNG, JPG or SVG. Ideally square and 260x260 (or above) but would work with any image.

#### How should this be implemented in your opinion?
Use [Real Favicon Generator](https://realfavicongenerator.net/) or something similar to generate a well rounded collection of different favicons (inc `manifest.json`) and automatically inject the relevant code into the `<head>` of each page.

example output:
```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
<link rel="manifest" href="/site.webmanifest"/>
<meta name="msapplication-TileColor" content="#ffffff"/>
<meta name="theme-color" content="#ffffff"/>
```
`msapplication-TileColor` and `theme-color` could match the `$accentColor` stylus variable.
#### Are you willing to work on this yourself?**
I'd sure be willing to give it a go!

**Comment by ulivz** [comment]
Thank you for your interest in VuePress, but you can use [head](https://vuepress.vuejs.org/config/#head) option to get what you want.

- Refs:

   - [Site Config of VuePres itself](https://github.com/vuejs/vuepress/blob/master/packages/docs/docs/.vuepress/config.js#L19)
