### ISSUE TITLE
Algolia Doc Search

### ISSUE THREAD

**Issue by FadySamirSadek** [vuejs/vuepress#104]
I was working on integrating vuepress Doc search using Algolia's Doc Search but there are a couple of things that I need to know and they will help me to figure the right way to do it:

1-since Algolia already has a suggestions box should we delete the suggestions box that is already in the SearchBox component or we should add it as a general setting like google analytics. This totally depends on the direction of the project and the goal behind it. In the readme file the project is defined as "Minimalistic docs generator with Vue component based layout system" and if it is all about generating docs then making Algolia's Doc search integrated the same way google analytics is integrated as a general component that is configured using the configuration file would make sense. But if the target of VuePress is to be a"powered Static Site Generator" as the website says and it will be a generic static site generator that can be used for multiple purposes other than DOCS then Algolia's Doc Search should be limited to our docs not the entire API

2-There is currently a way for developers to add a elements to the head of a page using the head parameter in the config file which I used to add css file for Algolia's Docs while there is no way to inject something at the end of the body without creating a component

**Comment by yyx990803** [comment]
This is something that the default theme plans to support as a built-in feature. We will have a separate `<AlgoliaSearchBox/>` component which contains only the input box and inits algolia's docsearch library in `mounted`. Then we decide which search box component to render based on whether the user has provided an algolia config or not.

**Comment by FadySamirSadek** [comment]
@yyx990803 this is what I similar to what I asking about in #62 why should we make the choice for the user and add the <AlgoliaSearchBox /> component and users choose between it and normal search while we can create a guideline for the community to build other vue components ('this is what I meanr by plugins') that the user can install on his own to integrate a certain feature he/she wants

**Comment by ulivz** [comment]
Closing in favor of the PR #201 . Let's continue discussion there.
