### ISSUE TITLE
Linkify option does not seem to work

### ISSUE THREAD

**Issue by octref** [vuejs/vuepress#1040]
- [x] I confirm that this is a issue rather than a question.

## Bug report

`markdown.linkify` do not linkify.

#### Version

- 0.14.7
- 1.0.0-alpha.24

#### Steps to reproduce

```bash
git clone git@github.com:vuejs/vetur.
git checkout linkify
vuepress dev docs
# Nagivate to http://localhost:8080/vetur/formatting and observe multiple pure links are not linkified
```

#### What is expected?

Links are linkified.

#### What is actually happening?

They aren't.

#### Other relevant information

- Your OS: macOS High Sierra
- Node.js version: v8.11.4
- Browser version: Chrome latest
- Is this a global or local install? Global
- Which package manager did you use for the install? npm

**Comment by octref** [comment]
Commit here: https://github.com/vuejs/vetur/commit/401daa7e4300018bb47bd367028a7818bfe78a69

Related: https://github.com/vuejs/vetur/issues/981

**Comment by ulivz** [comment]
Thanks for the report! this looks like an issue but actually a necessary feature but we forgot in the past.

- For 0.x, fixed at https://github.com/vuejs/vuepress/commit/838332965c2747a5b1481f681611ef749182174b at released at [0.14.8](https://github.com/vuejs/vuepress/blob/0.x/CHANGELOG.md#0148-2018-11-26) ✨ 

- For 1.x, will support this feature later.

**Comment by ulivz** [comment]
BTW, I found some HTML tag in your `docs/CHANGELOG.md`:

e.g. `<template-component>` and `<version>`, it's better to use use ` to wrap them.

**Comment by octref** [comment]
I see, that's why vuepress gives back scary warnings 😅 Thanks for the quick fix 👍
