### ISSUE TITLE
How do i create static html pages

### ISSUE THREAD

**Issue by srikanthreddy919** [vuejs/vuepress#1042]
## Feature request

How do i create static html pages instead of md files, I want to create a static main website with the documentation. Is it possible to create static web pages in html with custom layouts and default layout for the documentation. Please help me on this. My website https://razorops.com/

**Comment by dacsang97** [comment]
You can read [Custom Theme](https://vuepress.vuejs.org/guide/custom-themes.html) section in official docs of Vue Press
Alternative, you can use `html`, `Vue component` in your `.md` file, md file only defined your permalink (in v1.x alpha, you can custom permalink), but page content depends on you.

**Comment by ulivz** [comment]
`VuePress build` will help you to transpile your markdown files to static HTML files according to your site config. If you want to to know more, you can check out our docs:

- For 1.x (**Alpha**): https://vuepress.vuejs.org/
- For 0.x (**Stable**): https://v0.vuepress.vuejs.org/

If you met any issues or had any good features idea, welcome back to here to inform us.
