### ISSUE TITLE
Tabulations inside ClientOnly

### ISSUE THREAD

**Issue by Deraw-** [vuejs/vuepress#1043]
- [x ] I confirm that this is a issue rather than a question.

#### Steps to reproduce

Create a custom component and use it in `ClientOnly` component with one tabulation, like this:

```
<ClientOnly>
	<Timeline
		:items="[]"
	/>
</ClientOnly>
```

#### What is expected?

I'm expecting that the component inside `ClientOnly` will be rendered normally.

#### What is actually happening?

The code inside `ClientOnly` is rendered as a code-block, to fix the issue you need to have no tabulation, like this:

```
<ClientOnly>
<Timeline
	:items="[]"
/>
</ClientOnly>
```

I'm not sure if this is wanted, but it as made me struggling a lot!

I haven't tested with spaces.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
Thanks for your report, to save our time and avoid suspicion, could you create an reproduction repo for that?

**Comment by Deraw-** [comment]
@ulivz Sure! Here it is https://github.com/Deraw-/vuepress-issue-1043

**Comment by meteorlxy** [comment]
Just tried your repo.

Markdown treat lines start with `tab` as code block, see https://www.markdownguide.org/basic-syntax/#code-blocks-1.

So do not use `tab` nor `four spaces`. `Two spaces` is prefered.

**Comment by Deraw-** [comment]
@meteorlxy Oh that's true! I didn't think about the fact that this is still Markdown!

**So this isn't an issue, closing it right now, thanks!**
