### ISSUE TITLE
Sidebar navigation to header within page does not work on Firefox 63.0

### ISSUE THREAD

**Issue by drewtownchi** [vuejs/vuepress#1044]
- [ x] I confirm that this is a issue rather than a question.

## Bug report
The sidebar sublinks within a page do not work in Firefox 63.0 on Windows.  For example, if you are on a sidebar .md page and click on Examples it does not go to the sample header.  This does work on Chrome.

#### Version
1.0.0-alpha.24

#### Steps to reproduce
1. Create a page that is long with multiple headers
2. In the sidebar, click the #link to one of the headers that is below the current viewport.

#### What is expected?
It should navigate to the header.

#### What is actually happening?
The address bar is updated but the page navigation does not work.
#### Other relevant information

- Your OS: Windows 10
- Node.js version: 
- Browser version: Firefox 63.0
- Is this a global or local install? Local 
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Thanks for your report, could you create an reproduction repo?

**Comment by drewtownchi** [comment]
https://github.com/drewtownchi/VuePressNoScroll I also experience this on the main VuePress docs as well
 https://vuepress.vuejs.org/guide/basic-config.html

Whenever I run npm run docs:dev and I click between "Section Section" and "First Section" the page does not move at all. I don't see any issues on Edge or Chrome.  Just Firefox 63 seems to be having this issue?

**Comment by drewtownchi** [comment]
Duplicate of #1107 and fixed by #1108
