### ISSUE TITLE
Extending @vuepress/theme-default Layout.vue causes the Sidebar to disappear

### ISSUE THREAD

**Issue by spiltcoffee** [vuejs/vuepress#1045]
- [x] I confirm that this is a issue rather than a question.

#### Version
vuepress 1.0.0-alpha.24

#### Steps to reproduce

1. Create a Layout that extends `@vuepress/theme-default/layouts/Layout.vue`

`CustomLayout.vue`
```html
<script>
import Layout from "@vuepress/theme-default/layouts/Layout.vue";

export default {
  extends: Layout
}
</script>
```

2. Use Layout

`index.md`
```markdown
---
layout: CustomLayout
---
```

#### What is expected?

Default layout to appear as expected

#### What is actually happening?

The sidebar is always hidden.

I believe this is to do with the following function:
https://github.com/vuejs/vuepress/blob/ace3aec3dbcfd43d269edb5701aabcc653cae1a2/packages/%40vuepress/theme-default/layouts/Layout.vue#L93-L101

Checking for `!frontmatter.layout` causes the sidebar to always be hidden if you inherit the default Layout.vue in this way.

It's possible to get around the issue by redefining `shouldShowSidebar()` in the inherited component, but I'm wondering whether there should even be a check for `!frontmatter.layout` anyway, seeing as LayoutDistributor.vue will replace the whole component if `frontmatter.layout` is defined.

#### Other relevant information

- Your OS: Windows 10
- Node.js version: 10.6.0
- Browser version: Chrome 70
- Is this a global or local install? local
- Which package manager did you use for the install? npm 6.4.0

**Comment by ulivz** [comment]
Fixed at 8dd418e
