### ISSUE TITLE
Customizable .vuepress Directory Location

### ISSUE THREAD

**Issue by gaomd** [vuejs/vuepress#105]
Currently, while running `npx vuepress build docs` in the project root, VuePress will ONLY look for `docs/.vuepress/config.js` file, which resulting in a nested project structue:

    /docs/README.md
    /docs/.vuepress/config.js
    /docs/.vuepress/dist/*

Ideally, we could specify the `.vuepress` path via command line option, so the `.vuepress` directory and the generated files won't mess up with the `docs` directory, for example:

    npx vuepress build --vuepress-dir=.vuepress docs

Results in:

    /docs/README.md
    /.vuepress/config.js
    /.vuepress/dist/*

I know there's a `--dest` option for specifying the `dist` directory, but the ability to specify the entire `.vuepress` directory would be great!

**Comment by yyx990803** [comment]
I don't see practical value in this except for personal preference, so probably not.

**Comment by nkconnor** [comment]
Practical value: dot files are excluded by default for _many_ development tools. Using a hidden directory requires specialized development set-up. What's the advantage to this?

**Comment by zolero** [comment]
Funny that @yyx990803 his view on this is getting quite some thumbs down which ironically shows that people would like to have this feature... Same as me.

**Comment by jmatospob** [comment]
not really sure if same thing as I'm new to vuepress, but another use case conflict

github pages uses `docs/` folder for serving content so I'can have vuepress, source documents and generated html in same branch. 

well technically I can, but it will be a mess of source and target files.
