### ISSUE TITLE
How should I use the medium-zoom plugin

### ISSUE THREAD

**Issue by sharanraj124** [vuejs/vuepress#1052]
hi, when I am reading official tutorials, I read the docs 'https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html#install' of  and update my site's code as follows: in docs/.vuepress/config.js' I add:

```
    plugins: {
    '@vuepress/plugin-medium-zoom': true,
    },
```
add in `pakage.json` file

```
  "devDependencies": {
    "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.24",
    "node-sass": "^4.10.0",
    "vuepress": "^1.0.0-alpha.23"
  },
```
but unlucky, there is no effect on my site, for I want the `Zoom image` as an official site, what should I do?

**Comment by EliazTray** [comment]
The default selector of 'plugin-medium-zoom' is '.content img'.
Maybe your img tag isn't wrapped in className '.content' .
If you want change selector  by tagName such as 'img'.

```js
 plugins: {
    '@vuepress/plugin-medium-zoom': {
           selector: 'img'
       },
    },
```

then it will effect. :)

**Comment by sharanraj124** [comment]
Thanks for our suggestion @EliazTray . but this is not working. I think plugin is not loaded. my img tag is wrapped in className '.content'. 
![screen shot 2018-11-29 at 8 09 54 am](https://user-images.githubusercontent.com/41563058/49195772-6b9b5080-f3ae-11e8-93a6-0f97b2346877.png)

there is no effect on my docs, for I want the Zoom image as an official, what should I do?

**Comment by ulivz** [comment]
@sharanraj124 Could you Create a reproduction repo instead of pasting code here, thanks.

**Comment by sharanraj124** [comment]
this is my repo `https://github.com/sharanraj124/sample-docs` I only added sample image. could you help for zoom images.

**Comment by ulivz** [comment]
Thanks for providing the reproduction repo, it's the best and quickest way for us to help you to find out the solution.

After bootstraping your repo, I just find out you need to update the version of `@vuepress/plugin-medium-zoom`.

```diff
 -   "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.24",
 +   "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.24",
```

FYI: for now the plugin are also tagged `next`, so you also need to install the latest version via:

```bash
npm install @vuepress/plugin-medium-zoom@next -D
# or yarn add @vuepress/plugin-medium-zoom@next -D
```

**Comment by sharanraj124** [comment]
I Tried this one `@vuepress/plugin-medium-zoom": "^1.0.0-alpha.24` but I am not to zoom my image in mouse click.  i don't know how to fix this problem. could you help for me.

**Comment by ulivz** [comment]
I was truly working just now, just removing your node_modules and re-install.

**Comment by sharanraj124** [comment]
ok I will try

**Comment by sharanraj124** [comment]
thank you so much @ulivz this is working. but one more doubt how to `disable` in markdown files for in this plugin.

**Comment by ulivz** [comment]
You can use selector option to select these elements you want

**Comment by sharanraj124** [comment]
thank you this is working fine

**Comment by 7neves** [comment]
I also have problems with the plugin that are not in effect. The settings are set according to [Official Description] (https://vuepress.vuejs.org/en/plugin/official/plugin-medium-zoom.html). But it still can't take effect. Finally, it is found that the plugins option is set. It is not set according to the official designation. Instead, the plugin name is completed, and it finally takes effect. I don't know if it is a personal operation problem. I hope to encounter this. People with problems can also see it.
```js
 plugins: {
    '@vuepress/plugin-medium-zoom': {
      selector: 'img.zoom-custom-imgs',
      // medium-zoom options here
      // See: https://github.com/francoischalifour/medium-zoom#options
      options: {
        margin: 16
      }
    }
  },
```
