### ISSUE TITLE
Bug: Google Analytics plugin not working on Zeit Now

### ISSUE THREAD

**Issue by johnleider** [vuejs/vuepress#1055]
- [x] I confirm that this is a issue rather than a question.

## Bug report
@vuepress/google-analytics is not working when deploying on Zeit Now.

[google plugin docs](https://vuepress.vuejs.org/plugin/official/plugin-google-analytics.html)
[reference implementation](https://github.com/vuejs/vuepress/blob/master/packages/docs/docs/.vuepress/config.js#L76)
[my implementation](https://github.com/vuetifyjs/vuex/blob/master/packages/cognito-module/docs/.vuepress/config.js#L9)
[now deployment docs](https://vuepress.vuejs.org/guide/deploy.html#now)
[deployed site](https://cognito.vuetifyjs.com/)

#### Version
vuepress@^0.14.8
@vuepress/plugin-google-analytics@^1.0.0-alpha.0

#### Steps to reproduce
```
git clone git@github.com:vuetifyjs/vuex.git
cd vuex && yarn && now
```

#### What is expected?
Google Analytics to work

#### What is actually happening?
It is not 🤕

#### Other relevant information
- Your OS: Ubuntu 18.04
- Node.js version: 8.11.3
- Browser version: Any
- Is this a global or local install? local w/ lerna + yarn workspaces
- Which package manager did you use for the install? yarn

**Comment by johnleider** [comment]
This was due to using the incorrect documentation.

**Comment by ulivz** [comment]
😂
