### ISSUE TITLE
Unable to create the vuepress docs inside reactjs folder

### ISSUE THREAD

**Issue by 10-seconds** [vuejs/vuepress#1058]
I have developed project in reactjs and i have need to create the documentation purpose , i am choosing the vuepress and it was located in reactjs folder inside docs folder. If even i am starting the reactjs service start, vue press is not working. Anyone help how to handled the above mentioned issue?

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
