### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by zubairhasrat** [vuejs/vuepress#106]
How can I access store in themeConfig.js so that make Nav dynamic

**Comment by ulivz** [comment]
VuePress doesn't use Vuex now. You can custom your nav links via `themeConfig.nav` see: https://vuepress.vuejs.org/default-theme-config/#navbar-links

**Comment by zubairhasrat** [comment]
my question is how can i create dynamic nav after getting from database or some API but you have suggested create static hard coded nav??

**Comment by yyx990803** [comment]
You can't. VuePress is not designed to use a database as data source. All content has to be static markdown in your project.

**Comment by yyx990803** [comment]
Alternatively, you can fetch data from your database and write it into a JSON file before you run `vuepress`, and then require that JSON file in your config.js.
