### ISSUE TITLE
Fail to run "vuepress dev" on Pixelbook / Debian

### ISSUE THREAD

**Issue by traderd65** [vuejs/vuepress#1066]
- [ x] I confirm that this is a issue rather than a question.

## Bug report
Running "Vuepress Dev" per installation instructions in Vuepress "Getting Started" tutorial

#### Version
vuepress/1.0.0-alpha.25 linux-x64 node-v11.2.0

#### Steps to reproduce
npm install -g vuepress
echo '# Hello VuePress' > README.md
vuepress dev

... the script runs for a while then crashes with:

[210:0x25e1fc0]   620422 ms: Mark-sweep 1379.4 (1450.8) -> 1370.6 (1454.8) MB, 1149.2 / 8.0 ms  (average mu = 0.158, current mu = 0.049) allocation failure scavenge might not succeed
[210:0x25e1fc0]   622059 ms: Mark-sweep 1382.8 (1454.8) -> 1373.9 (1457.3) MB, 1577.9 / 6.7 ms  (average mu = 0.091, current mu = 0.036) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1e06f5acfb5d]
    1: StubFrame [pc: 0x1e06f5a8dd5a]
Security context: 0x321fedf9d9f1 <JSObject>
    2: join [0x1c882dc7ea31] [path.js:~1146] [pc=0x1e06f5b54b20](this=0x1c882dc022b1 <Object map = 0x25b57b8b4071>)
    3: arguments adaptor frame: 2->0
    4: /* anonymous */(aka /* anonymous */) [0x27ac1a0533c9] [/home/doronsherman/npm-global/lib/node_modules/vuepress/node_modules/readdirp/readdirp.js:~172] [pc=0x1e06f...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x944930 node::Abort() [node]
 2: 0x9457dc node::OnFatalError(char const*, char const*) [node]
 3: 0xb0d02e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb0d264 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf09832  [node]
 6: 0xf09938 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf16058 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf16b6b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf198a1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xee3ad4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x11994be v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x1e06f5acfb5d 
Aborted
...
There are also multiple messages "Language does not exist sh" during the script run. The failure occurs while compiling vue-eslint-parser... eslint-scope...

#### What is expected?
Advise how to get vuepress setup on the Pixelbook Debian container.

#### What is actually happening?
Crash (reported above)

#### Other relevant information

- Your OS: Chrome OS
- Node.js version: 11.2.0
- Browser version: Chrome
- Is this a global or local install? global install under npm-global folder in home directory
- Which package manager did you use for the install? npm

**Comment by spiltcoffee** [comment]
Seeing a few lines saying "out of memory" in the dump there. How much memory does the container have access to? Are you able to increase that?

Also, if you're trying to run `vuepress dev` on nodejs >=v10, bump the version to 1.0.0-alpha.27 to make sure https://github.com/vuejs/vuepress/issues/1063 isn't affecting you.

**Comment by traderd65** [comment]
myname@penguin:~$ free --mega
                    total        used        free      shared  buff/cache   available
Mem:           5074         138        3922          32        1014        4410
Swap:             0           0           0

**Comment by ulivz** [comment]
Could you increase your memory via `--max-old-space-size` and try again?

**Comment by traderd65** [comment]
Do you mean I should run:

vuepress dev --max-old-space-size=4096

?

**Comment by spiltcoffee** [comment]
I think the flag needs to be passed to nodejs itself, so maybe try `NODE_OPTIONS="--max-old-space-size=8192" vuepress dev`

**Comment by traderd65** [comment]
vuepress dev NODE_OPTIONS="--max-old-space-size=4096"

worked!

vuepress build NODE_OPTIONS="--max-old-space-size=4096"

also worked but placed the .vuepress folder under a top folder named "NODE_OPTIONS="--max-old-space-size=4096""

**Comment by spiltcoffee** [comment]
Make sure to either put it first or even run the `NODE_OPTIONS` as a separate command first so you don't pass the environment variable in as an argument to vuepress accidentally.

**Comment by traderd65** [comment]
When setting NODE_OPTIONS="--max-old-space-size=8192" then running vuepress dev, the same JavaScript heap out of memory error occur.
