### ISSUE TITLE
Multiple docs/products, versions and locales

### ISSUE THREAD

**Issue by maziarz** [vuejs/vuepress#1067]
## Feature request

I am currently maintaining multiple documentations, versions and localizations across different repositories. My eyes were caught by Vuepress, but before i can use it completely i am wondering if i can implement a solution which can handle multiple documentations (products), versions and locales.

#### What problem does this feature solve?

Lets assume we have 3 products: Windows, macOS, Linux.
Each product has multiple versions and multiple locales. We would like to host all these from the same point of entry: docs.operativesystems.com

#### How should this be implemented in your opinion?

The end result i would want to achieve for this solution would be something in this direction:

##### Landing page
docs.operativesystems.com/

##### Windows
docs.operativesystems.com/windows
docs.operativesystems.com/windows/xp
docs.operativesystems.com/windows/xp/en-US
docs.operativesystems.com/windows/xp/zh-CN

##### macOS
docs.operativesystems.com/macos
docs.operativesystems.com/macos/10.13
docs.operativesystems.com/macos/10.13/en-US

etc.

#### Are you willing to work on this yourself?**

Yes indeed!

**Comment by ulivz** [comment]
Thanks for your interest in VuePress

- For `i18n`, see: https://vuepress.vuejs.org/guide/i18n.html
- For `version control`, let's move https://github.com/vuejs/vuepress/issues/1018 to continue
