### ISSUE TITLE
Why can't use <script> in markdown-it-container?

### ISSUE THREAD

**Issue by bailnl** [vuejs/vuepress#107]
I try to write a custom container demo base markdown-it-container, but <script> and <style> cannot compiled.

I tried to see the source code to solve the problem but did not find it

https://vuepress.vuejs.org/guide/using-vue.html#script-style-hoisting

According to the documentation instructions should be feasible.

sorry,  I am working hard on my English.

**Comment by bailnl** [comment]
I want to know how it works?
Use markdown-it and its plugins to convert markdown to html code, then pick out the <script> <style> in html and generate the vue component.

*.md => html => vue ?

if so, it should be work.

**Comment by yyx990803** [comment]
Sorry but this is out of scope for issues.

**Comment by bailnl** [comment]
sorry, My description may have problems.

This is my “demo” container.
but <script> and <style> cannot compiled.

![image](https://user-images.githubusercontent.com/2436993/38904651-2d288cb8-42de-11e8-98c9-3063ceb5f3e6.png)

@yyx990803

**Comment by BuptStEve** [comment]
大兄弟试试这个？https://buptsteve.github.io/vuepress-plugin-demo-code/
不过目前刚发现似乎不管用不用这个插件，打包后 `<style>` 标签没了，开发时是有的...
试了 0.x 和 1.x  都有这个问题，我看看源码是哪儿出了问题...
