### ISSUE TITLE
Layout name can not be 'home'

### ISSUE THREAD

**Issue by distance295** [vuejs/vuepress#1072]
- [ ] I confirm that this is a issue rather than a question.

## Bug report

if you want to paint a page with you own component.Layout name can not be 'home'.
Please note this rule clearly.

#### Version
all Version
#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
Why cannot the name of component be home?

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
