### ISSUE TITLE
Blog-plugin: wrong rendering for the router '/tag/' and '/category/'

### ISSUE THREAD

**Issue by EliazTray** [vuejs/vuepress#1073]
- [x] I confirm that this is a issue rather than a question.

#### Version
@vuepress 1.0.0-alpha.27

#### Steps to reproduce

1. Create  `Layout.vue`, `Page.vue`, `Post.vue`, `Tag.vue`, `Tags.vue`, `Category.vue`, `Categories.vue` under the 'layouts' directory. 

2. npm run dev

3. visit `/tag/`. 

![image](https://user-images.githubusercontent.com/16015431/49557473-b7b43b00-f942-11e8-8da8-5db0499df503.png)

#### What is expected?
It will use `Cateogries.vue` layout to render.
#### What is actually happening?
it used `Page.vue` layout to render.
#### Other relevant information

- Your OS: macOs
- Node.js version:  v8.11.3
- Browser version: Chrome 70.0.3538.110
- Is this a global or local install? local
- Which package manager did you use for the install? 
v1.0.0.alpha.27

**Comment by tohutohu** [comment]
I also encountered a similar problem.

The part of adding the page of the plugin is working properly. 
However, that information is not properly passed to Layout.vue.

I added debug print.

build.js 
https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/build.js#L128-L132
```javascript
  async function renderPage (page) {
    const pagePath = page.path
    readline.clearLine(process.stdout, 0)
    readline.cursorTo(process.stdout, 0)
    process.stdout.write(`Rendering page: ${pagePath}\n`)
    console.log('path: ', page.path) // add
    console.log('frontmatter: ', page.frontmatter) // add
```

LayoutDistoributor.vue
https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/app/components/LayoutDistributor.vue
```javascript
export default {
  computed: {
    layout () {
      console.log('path: ', this.$page.path) // add
      console.log('frontmatter: ', this.$page.frontmatter) // add
      if (this.$page.path) {
        return this.$page.frontmatter.layout || 'Layout'
      }
      return 'NotFound'
    }
  }
}
```

I got the following output.
```
Rendering page: /2018/12/04/index/
{ title: 'test article',
  date: 2018-12-04T00:00:00.000Z,
  layout: 'Post',
  permalink: '/:year/:month/:day/:slug' }
path:  /2018/12/04/index/
{ title: 'test article',
  date: '2018-12-04T00:00:00.000Z',
  layout: 'Post',
  permalink: '/:year/:month/:day/:slug' }
Rendering page: /tag/
{ title: 'Tags', layout: 'Tags' }
path:
{}
Rendering page: /category/
{ title: 'Categories', layout: 'Categories' }
path:
{}
Rendering page: /404.html
undefined
path:
{}
```

**Comment by EliazTray** [comment]
@tohutohu 
i found the problem in [https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-blog/index.js#L67](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-blog/index.js#L67).

'/tag/' & '/category/' match the first condition of [enhancers](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-blog/index.js#L19)

when `Page` layout exists, [it](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-blog/index.js#L68) used the layout which exists....

**Comment by Mrminfive** [comment]
The new page of the blog plugin cannot be used because the getSiteData method has been executed before the plugin ready.

**Comment by ulivz** [comment]
Thanks for @Mrminfive , there has been a [PR](https://github.com/vuejs/vuepress/pull/1095) for this issue
