### ISSUE TITLE
Search plugin load fail when base option set on build mode

### ISSUE THREAD

**Issue by huang-x-h** [vuejs/vuepress#1076]
- [ ] I confirm that this is a issue rather than a question.

## Bug report

When `base` option set `/guide/`, then `yarn docs:build` build the dist directory, put on the nginx, can not access search plugin img and js

#### Version

```
"vuepress": "^0.14.8"
```

#### Steps to reproduce

project directory

![image](https://user-images.githubusercontent.com/381860/49567832-dd086f80-f969-11e8-8ba8-23384ef6affc.png)

1. config.js
```js
module.exports = {
  base: '/code_guide/'
}
```

2. yarn docs:dev

access the url `http://localhost:8080/code_guide/`

![image](https://user-images.githubusercontent.com/381860/49568004-86e7fc00-f96a-11e8-8fff-37164fcc9d21.png)

`assets` files are not in `code_guide` directory

so when `yarn docs:build` build the dist, put on the nginx, access url

![image](https://user-images.githubusercontent.com/381860/49568033-9e26e980-f96a-11e8-89b8-203fb48d04da.png)

![image](https://user-images.githubusercontent.com/381860/49567971-66b83d00-f96a-11e8-92d1-88077d39faee.png)

can not access the search plugin assets files

#### Other relevant information

- Your OS: 

macOS Sierra 10.12.6 

- Node.js version: 

v8.11.2

- Browser version: 

Chrome 70.0.3538.110

- Is this a global or local install? 

local install

- Which package manager did you use for the install?

yarn

**Comment by ulivz** [comment]
I ensure that the search plugin works with base option. or the website of VuePress will never work.

Since you are putting it in `nginx`, so please check your own nginx config by yourself. If it truly turns out to be a bug, open a issue and provide a valid repro.
