### ISSUE TITLE
Blog plugin affects SFC layout definition

### ISSUE THREAD

**Issue by leopiccionia** [vuejs/vuepress#1079]
- [X] I confirm that this is a issue rather than a question.

#### Version

* vuepress@1.0.0-alpha.26+
* @vuepress/plugin-blog@1.0.0-alpha.0

#### Steps to reproduce

A minimal repro: https://github.com/leopiccionia/vuepress-sfc-blog-bug

Remove the blog plugin to solve the issue.

#### What is expected?

As noted in changelog, a SFC (in this case, outside of `options.postDir`) should be its own layout.

#### What is actually happening?

SFC is wrapped inside default layout.

**Comment by ulivz** [comment]
Thanks for your report, let's see your deps:

```
    "@vuepress/plugin-blog": "^1.0.0-alpha.0",
    "vuepress": "^1.0.0-alpha.27"
```

You installed the outdate blog plugin. please update to the same version of vuepress. feel free to continue discussion if it turns out to be a bug.
