### ISSUE TITLE
Double curly braces causing error

### ISSUE THREAD

**Issue by jisi724** [vuejs/vuepress#108]
Hey @yyx990803,

Thanks a bunch for making this nice tool that I am seeking for a long time.

However, I found the double curly braces `{{...}}` in *.md file would cause compiling error as vue uses Mustache style syntax to interpolate text. Is there any way to escape that? 

Thanks in advance for you help.

**Comment by mdaffin** [comment]
Use a `::: v-pre` block. [See this part of the documentation](https://vuepress.vuejs.org/guide/using-vue.html#escaping).

**Comment by Rowdster** [comment]
This doesn't solve the problem if you need {{ inline in your text and don't want to change font/layout format

**Comment by abea** [comment]
Is there a solution to the inline case @Rowdster brought up?
ex:
> 2. Add `({{ arr.count }})` inside of the `p` tag in `index.html`.
