### ISSUE TITLE
configureWebpack method breaks webpack 2.0 spec

### ISSUE THREAD

**Issue by GrayedFox** [vuejs/vuepress#1083]
- [x] I confirm that this is a issue rather than a question.

## Bug report
The `configureWebpack` method of the Vuepress 0.x branch attempts to mutate the webpack object directly, which is not allowed as of Webpack 2.0 and above. Since this branch is built on Webpack 2.0, the method documentation and logic of the configureWebpack method is now bugged (it should of been fixed at the same time the underlying Webpack version was bumped).

#### Version
0.14.2

#### Steps to reproduce
Inside your config.js file add this: 

```
  configureWebpack: (config) => {
    config.env = { development: 'balls' }
  }
```

#### What is expected?
Webpack can be configured

#### What is actually happening?
Build fails with:

> WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration has an unknown property 'env'.

#### Other relevant information
I would suggest we try and fix this in a backwards compatible way by changing the internal logic of the configureWebpack method to define a plugin the way webpack expects: https://webpack.js.org/plugins/define-plugin/

- Your OS: Ubuntu 18.04
- Node.js version: v8.11.4
- Browser version: Version 71.0.3578.80 (Official Build) (64-bit)
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
1. VuePress was based on webpack 4.x
2. `env` wasn't a option of webpack 4.x

**Comment by GrayedFox** [comment]
Sigh... took me a while but finally got it to work. I assumed that I needed access to the webpack instance VuePress was using, but this was erroneous. Requiring webpack at the top of the file works just fine. Need coffee... for anyone wondering how to expose Node env vars:

```
// .vuepress/config.js
require('dotenv').config()
const webpack = require('webpack')

module.exports = {
  configureWebpack: (config) => {
    return { plugins: [
      new webpack.EnvironmentPlugin({ ...process.env })
    ]}
  }
}
```

Cheers.

**Comment by ulivz** [comment]
Why not：

```
module.exports = {
  alias: {
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.DEBUG': process.env.DEBUG
  }
}
```

directly? 😅
