### ISSUE TITLE
Teamplate variable may get a wrong type?

### ISSUE THREAD

**Issue by intijk** [vuejs/vuepress#1094]
I am trying to understand the code here. 
https://github.com/vuejs/vuepress/blob/a56c3b4b139121389550ce9a9e14203a8fbc23e0/packages/%40vuepress/shared-utils/src/tryChain.ts#L1-L11

In line 7, `resolver` is an element of `resolvers`, it might be an array or a boolean. If it is a boolean, it will construct `resolver=[boolean, true]` at line 9. And on line 11, `provider` will become a boolean. Is it intend to be designed this way?

**Comment by ulivz** [comment]
Thanks for your report, but it's actually a typo, a resolver could be a plain function which will be executed every time, or a array with resolving function as the 1st pos and condition as the 2nd pos which is for optional execution.
