### ISSUE TITLE
Default viewport settings affect UX badly

### ISSUE THREAD

**Issue by pepelsbey** [vuejs/vuepress#110]
By default there’s a viewport configuration that considered an antipattern:
```html
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
```
The `maximum-scale=1` and `user-scalable=no` are locking viewport scaling which affects UX and accessibility badly. See [Anti-Pattern: Disabling Pinch-to-Zoom](https://ebay.gitbooks.io/mindpatterns/content/antipatterns/disabling_pinch-to-zoom.html) by eBay for details.

I’m ready to send PR removing those viewport options, but I decided to check if you’d agree.

**Comment by yyx990803** [comment]
Yeah we can remove them for accessibility.
