### ISSUE TITLE
Change to 404 quikly when i open the index.html with chrome after build

### ISSUE THREAD

**Issue by ltstriker** [vuejs/vuepress#1103]
I build a page just like the guide.It works well when using dev. But after build, it change to 404 quickly when i open the index.html with chrome.I refresh it.It can be seen that the right page will be made but I do not know why it change to 404.

follow is my configure.json

module.exports = {
    base: '/retryvpress/.vuepress/dist/',
    title: ' asd ',
    description: 'asd blog',
  }

// the base seems must be that, or the js file cannot be found

- Your OS: win10
- Node.js version: v8.12.0
- Browser version: chrome 版本 69.0.3497.100
- Is this a global or local install?  global
- Which package manager did you use for the install?
I have tried both npm and yarn.

**Comment by ulivz** [comment]
To report an issue that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. [vuepress-issue-example](https://github.com/ocavue/vuepress-issue-example)), otherwise I don't know where you are going wrong.

**Comment by ltstriker** [comment]
Here is the repo https://github.com/ltstriker/retryvpress  .

**Comment by ulivz** [comment]
Hmmm... so which version did you use?

**Comment by ltstriker** [comment]
0.14.8
Thanks.

**Comment by ltstriker** [comment]
So sorry.I made a mistake about the repo.
I refresh the repo.the old one is the version the js file not found..The new one is what i am asking about.
just the base change
// my repo is in E:/retryvpress/
base: '/retryvpress/docs/.vuepress/dist/',

**Comment by ulivz** [comment]
> the base seems must be that, or the js file cannot be found?

Are you sure? Hmmm... don't know what to say.

**Comment by ulivz** [comment]
The usage of your repro is very normal and it should work and it really works for me. so it should be caused by the damn windows.

Let's move to #913 to continue if you could provide an invalid repro so that other windows users could help you.
