### ISSUE TITLE
Deploying to Netlify

### ISSUE THREAD

**Issue by pjolson** [vuejs/vuepress#1104]
My continuous deploy worked great yesterday.
I tried to add a second blog post page today and made some minor updates and now it is failing.

The big change I made today was I added a post with a bunch of images. It looks like this might be the issue. Something about not being able to resolve an alias.

Any help is appreciated.

This is my packages.json

{
  "name": "MySuite",
  "version": "1.0.0",
  "description": "---\r title: MySuite\r ---",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docs:build": "vuepress build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/pjolson/MySuiteBlog.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/pjolson/MySuiteBlog/issues"
  },
  "homepage": "https://github.com/pjolson/MySuiteBlog#readme",
  "dependencies": {
    "vuepress": "^0.14.8"
}
}

This is my deploy log.

10:39:29 AM: Build ready to start
10:39:30 AM: build-image version: 12783d4d177a66bec5a23ad1097ea7bd02931128
10:39:31 AM: buildbot version: 5a64b5cb0ce1ed3ba485935522483a4d39e15107
10:39:31 AM: Fetching cached dependencies
10:39:31 AM: Starting to download cache of 69.0MB
10:39:31 AM: Finished downloading cache in 808.999924ms
10:39:32 AM: Starting to extract cache
10:39:34 AM: Finished extracting cache in 2.675509253s
10:39:34 AM: Finished fetching cache in 3.605817526s
10:39:34 AM: Starting to prepare the repo for build
10:39:35 AM: Preparing Git Reference refs/heads/master
10:39:35 AM: Starting build script
10:39:35 AM: Installing dependencies
10:39:36 AM: Started restoring cached node version
10:39:38 AM: Finished restoring cached node version
10:39:39 AM: v8.14.0 is already installed.
10:39:39 AM: Now using node v8.14.0 (npm v6.4.1)
10:39:40 AM: Attempting ruby version 2.3.6, read from environment
10:39:41 AM: Using ruby version 2.3.6
10:39:41 AM: Using PHP version 5.6
10:39:41 AM: Started restoring cached node modules
10:39:41 AM: Finished restoring cached node modules
10:39:41 AM: Installing NPM modules using NPM version 6.4.1
10:39:54 AM: npm
10:39:55 AM: notice created a lockfile as package-lock.json. You should commit this file.
10:39:55 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
10:39:55 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:39:55 AM: audited 11927 packages in 12.201s
10:39:55 AM: found 0 vulnerabilities
10:39:55 AM: NPM modules installed
10:39:55 AM: Started restoring cached go cache
10:39:55 AM: Finished restoring cached go cache
10:39:55 AM: unset GOOS;
10:39:55 AM: unset GOARCH;
10:39:55 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
10:39:55 AM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
10:39:55 AM: go version >&2;
10:39:55 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
10:39:55 AM: go version go1.10 linux/amd64
10:39:55 AM: Installing missing commands
10:39:55 AM: Verify run directory
10:39:55 AM: Executing user command: npm run docs:build
10:39:55 AM: > MySuite@1.0.0 docs:build /opt/build/repo
10:39:55 AM: > vuepress build
10:39:56 AM:  WAIT  Extracting site metadata...
10:39:56 AM: <a href="https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/" target="_blank"><img src="../img/profile.jpg" title="Patrick Olson - LinkedIn Profile" alt="Patrick Olson - LinkedIn Profile" width=40% height="auto" style="border-radius: 50%; display: block; margin-left: auto; margin-right: auto"><br></a>
10:39:56 AM: <a href="https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/" target="_blank"><img src="../img/profile.jpg" title="Patrick Olson - LinkedIn Profile" alt="Patrick Olson - LinkedIn Profile" width=8% height="auto" style="border-radius: 50%;"></a>**By:** [Patrick Olson](https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/)
10:39:56 AM: <a href="https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/" target="_blank"><img src="../img/profile.jpg" title="Patrick Olson - LinkedIn Profile" alt="Patrick Olson - LinkedIn Profile" width=8% height="auto" style="border-radius: 50%;"></a>**By:** [Patrick Olson](https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/)
10:39:59 AM: [16:39:59] Compiling Client
10:39:59 AM: [16:39:59] Compiling Server
10:40:01 AM: <a href="https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/" target="_blank"><img src="../img/profile.jpg" title="Patrick Olson - LinkedIn Profile" alt="Patrick Olson - LinkedIn Profile" width=40% height="auto" style="border-radius: 50%; display: block; margin-left: auto; margin-right: auto"><br></a>
10:40:01 AM: <a href="https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/" target="_blank"><img src="../img/profile.jpg" title="Patrick Olson - LinkedIn Profile" alt="Patrick Olson - LinkedIn Profile" width=8% height="auto" style="border-radius: 50%;"></a>**By:** [Patrick Olson](https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/)
10:40:01 AM: <a href="https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/" target="_blank"><img src="../img/profile.jpg" title="Patrick Olson - LinkedIn Profile" alt="Patrick Olson - LinkedIn Profile" width=8% height="auto" style="border-radius: 50%;"></a>**By:** [Patrick Olson](https://www.linkedin.com/in/patrick-olson-pmp-csm-137a9435/)
10:40:05 AM: [16:40:05] Compiled Server in 6s
10:40:12 AM: [16:40:12] Compiled Client in 13s
10:40:12 AM: (undefined) ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"4495a569-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&)
10:40:12 AM: Module not found: Error: Can't resolve '../img/postimgs/post2/criteria.png' in '/opt/build/repo/blog'
10:40:12 AM: resolve '../img/postimgs/post2/criteria.png' in '/opt/build/repo/blog'
10:40:12 AM:   using description file: /opt/build/repo/package.json (relative path: ./blog)
10:40:12 AM:     Field 'browser' doesn't contain a valid alias configuration
10:40:12 AM:     using description file: /opt/build/repo/package.json (relative path: ./img/postimgs/post2/criteria.png)
10:40:12 AM:       no extension
10:40:12 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:12 AM:         /opt/build/repo/img/postimgs/post2/criteria.png doesn't exist
10:40:12 AM:       .js
10:40:12 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:12 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.js doesn't exist
10:40:12 AM:       .jsx
10:40:13 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:13 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.jsx doesn't exist
10:40:13 AM:       .vue
10:40:13 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:13 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.vue doesn't exist
10:40:13 AM:       .json
10:40:13 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:13 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.json doesn't exist
10:40:13 AM:       .styl
10:40:13 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:13 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.styl doesn't exist
10:40:13 AM:       as directory
10:40:13 AM:         /opt/build/repo/img/postimgs/post2/criteria.png doesn't exist
10:40:13 AM: [/opt/build/repo/img/postimgs/post2/criteria.png]
10:40:13 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.js]
10:40:13 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.jsx]
10:40:13 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.vue]
10:40:13 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.json]
10:40:13 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.styl]
10:40:13 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"4495a569-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&) 1:922-967
10:40:13 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42&
10:40:14 AM:  @ ./blog/post2.md
10:40:14 AM:  @ ./node_modules/vuepress/lib/app/.temp/routes.js
10:40:14 AM:  @ ./node_modules/vuepress/lib/app/app.js
10:40:14 AM:  @ ./node_modules/vuepress/lib/app/clientEntry.js
10:40:14 AM:  @ multi ./node_modules/vuepress/lib/app/clientEntry.js
10:40:14 AM: (undefined) ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"4495a569-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&)
10:40:14 AM: Module not found: Error: Can't resolve '../img/postimgs/post2/results.png' in '/opt/build/repo/blog'
10:40:14 AM: resolve '../img/postimgs/post2/results.png' in '/opt/build/repo/blog'
10:40:14 AM:   using description file: /opt/build/repo/package.json (relative path: ./blog)
10:40:14 AM:     Field 'browser' doesn't contain a valid alias configuration
10:40:14 AM:     using description file: /opt/build/repo/package.json (relative path: ./img/postimgs/post2/results.png)
10:40:14 AM:       no extension
10:40:14 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:14 AM:         /opt/build/repo/img/postimgs/post2/results.png doesn't exist
10:40:14 AM:       .js
10:40:14 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:14 AM:         /opt/build/repo/img/postimgs/post2/results.png.js doesn't exist
10:40:14 AM:       .jsx
10:40:14 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:14 AM:         /opt/build/repo/img/postimgs/post2/results.png.jsx doesn't exist
10:40:14 AM:       .vue
10:40:14 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:14 AM:         /opt/build/repo/img/postimgs/post2/results.png.vue doesn't exist
10:40:14 AM:       .json
10:40:14 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:14 AM:         /opt/build/repo/img/postimgs/post2/results.png.json doesn't exist
10:40:15 AM:       .styl
10:40:15 AM:         Field 'browser' doesn't contain a valid alias configuration
10:40:15 AM:         /opt/build/repo/img/postimgs/post2/results.png.styl doesn't exist
10:40:15 AM:       as directory
10:40:15 AM:         /opt/build/repo/img/postimgs/post2/results.png doesn't exist
10:40:15 AM: [/opt/build/repo/img/postimgs/post2/results.png]
10:40:15 AM: [/opt/build/repo/img/postimgs/post2/results.png.js]
10:40:15 AM: [/opt/build/repo/img/postimgs/post2/results.png.jsx]
10:40:15 AM: [/opt/build/repo/img/postimgs/post2/results.png.vue]
10:40:15 AM: [/opt/build/repo/img/postimgs/post2/results.png.json]
10:40:15 AM: [/opt/build/repo/img/postimgs/post2/results.png.styl]
10:40:15 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"4495a569-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&) 1:1128-1172
10:40:15 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42&
10:40:15 AM:  @ ./blog/post2.md
10:40:15 AM:  @ ./node_modules/vuepress/lib/app/.temp/routes.js
10:40:15 AM:  @ ./node_modules/vuepress/lib/app/app.js
10:40:15 AM:  @ ./node_modules/vuepress/lib/app/clientEntry.js
10:40:15 AM:  @ multi ./node_modules/vuepress/lib/app/clientEntry.js
10:40:15 AM: (undefined) ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"2dafc7e0-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&)
10:40:15 AM: Module not found: Error: Can't resolve '../img/postimgs/post2/criteria.png' in '/opt/build/repo/blog'
10:40:15 AM: resolve '../img/postimgs/post2/criteria.png' in '/opt/build/repo/blog'
10:40:15 AM:   using description file: /opt/build/repo/package.json (relative path: ./blog)
10:40:15 AM:     using description file: /opt/build/repo/package.json (relative path: ./img/postimgs/post2/criteria.png)
10:40:15 AM:       no extension
10:40:15 AM:         /opt/build/repo/img/postimgs/post2/criteria.png doesn't exist
10:40:16 AM:       .js
10:40:16 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.js doesn't exist
10:40:16 AM:       .jsx
10:40:16 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.jsx doesn't exist
10:40:16 AM:       .vue
10:40:16 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.vue doesn't exist
10:40:16 AM:       .json
10:40:16 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.json doesn't exist
10:40:16 AM:       .styl
10:40:16 AM:         /opt/build/repo/img/postimgs/post2/criteria.png.styl doesn't exist
10:40:16 AM:       as directory
10:40:16 AM:         /opt/build/repo/img/postimgs/post2/criteria.png doesn't exist
10:40:16 AM: [/opt/build/repo/img/postimgs/post2/criteria.png]
10:40:16 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.js]
10:40:16 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.jsx]
10:40:16 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.vue]
10:40:16 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.json]
10:40:16 AM: [/opt/build/repo/img/postimgs/post2/criteria.png.styl]
10:40:16 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"2dafc7e0-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&) 1:1593-1638
10:40:16 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42&
10:40:16 AM:  @ ./blog/post2.md
10:40:16 AM:  @ ./node_modules/vuepress/lib/app/.temp/routes.js
10:40:16 AM:  @ ./node_modules/vuepress/lib/app/app.js
10:40:16 AM:  @ ./node_modules/vuepress/lib/app/serverEntry.js
10:40:16 AM:  @ multi ./node_modules/vuepress/lib/app/serverEntry.js
10:40:16 AM: (undefined) ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"2dafc7e0-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&)
10:40:16 AM: Module not found: Error: Can't resolve '../img/postimgs/post2/results.png' in '/opt/build/repo/blog'
10:40:17 AM: resolve '../img/postimgs/post2/results.png' in '/opt/build/repo/blog'
10:40:17 AM:   using description file: /opt/build/repo/package.json (relative path: ./blog)
10:40:17 AM:     using description file: /opt/build/repo/package.json (relative path: ./img/postimgs/post2/results.png)
10:40:17 AM:       no extension
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png doesn't exist
10:40:17 AM:       .js
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png.js doesn't exist
10:40:17 AM:       .jsx
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png.jsx doesn't exist
10:40:17 AM:       .vue
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png.vue doesn't exist
10:40:17 AM:       .json
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png.json doesn't exist
10:40:17 AM:       .styl
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png.styl doesn't exist
10:40:17 AM:       as directory
10:40:17 AM:         /opt/build/repo/img/postimgs/post2/results.png doesn't exist
10:40:17 AM: [/opt/build/repo/img/postimgs/post2/results.png]
10:40:17 AM: [/opt/build/repo/img/postimgs/post2/results.png.js]
10:40:17 AM: [/opt/build/repo/img/postimgs/post2/results.png.jsx]
10:40:17 AM: [/opt/build/repo/img/postimgs/post2/results.png.vue]
10:40:17 AM: [/opt/build/repo/img/postimgs/post2/results.png.json]
10:40:17 AM: [/opt/build/repo/img/postimgs/post2/results.png.styl]
10:40:17 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"2dafc7e0-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/vuepress/lib/webpack/markdownLoader.js??ref--1-2!./blog/post2.md?vue&type=template&id=4e51ff42&) 1:1751-1795
10:40:17 AM:  @ ./blog/post2.md?vue&type=template&id=4e51ff42&
10:40:17 AM:  @ ./blog/post2.md
10:40:17 AM:  @ ./node_modules/vuepress/lib/app/.temp/routes.js
10:40:17 AM:  @ ./node_modules/vuepress/lib/app/app.js
10:40:18 AM:  @ ./node_modules/vuepress/lib/app/serverEntry.js
10:40:18 AM:  @ multi ./node_modules/vuepress/lib/app/serverEntry.js
10:40:18 AM: Error: Failed to compile with errors.
10:40:18 AM:     at webpack (/opt/build/repo/node_modules/vuepress/lib/build.js:113:18)
10:40:18 AM:     at finalCallback (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:247:12)
10:40:18 AM:     at runWithDependencies.err (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:270:6)
10:40:18 AM:     at done (/opt/build/repo/node_modules/neo-async/async.js:2928:13)
10:40:18 AM:     at runCompilers (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:174:48)
10:40:18 AM:     at err (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:181:7)
10:40:18 AM:     at compiler.run (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:263:7)
10:40:18 AM:     at finalCallback (/opt/build/repo/node_modules/webpack/lib/Compiler.js:210:39)
10:40:18 AM:     at hooks.done.callAsync.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:226:13)
10:40:18 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
10:40:18 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
10:40:18 AM:     at onCompiled (/opt/build/repo/node_modules/webpack/lib/Compiler.js:224:21)
10:40:18 AM:     at hooks.afterCompile.callAsync.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:552:14)
10:40:18 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
10:40:18 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
10:40:18 AM:     at compilation.seal.err (/opt/build/repo/node_modules/webpack/lib/Compiler.js:549:30)
10:40:18 AM: npm ERR! code ELIFECYCLE
10:40:18 AM: npm ERR! errno 1
10:40:18 AM: npm ERR! MySuite@1.0.0 docs:build: `vuepress build`
10:40:18 AM: npm ERR! Exit status 1
10:40:18 AM: npm ERR!
10:40:18 AM: npm ERR! Failed at the MySuite@1.0.0 docs:build script.
10:40:18 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10:40:18 AM: npm ERR! A complete log of this run can be found in:
10:40:19 AM: npm ERR!     /opt/buildhome/.npm/_logs/2018-12-13T16_40_12_184Z-debug.log
10:40:19 AM: Caching artifacts
10:40:19 AM: Started saving node modules
10:40:19 AM: Finished saving node modules
10:40:19 AM: Started saving pip cache
10:40:19 AM: Finished saving pip cache
10:40:19 AM: Started saving emacs cask dependencies
10:40:19 AM: Finished saving emacs cask dependencies
10:40:19 AM: Started saving maven dependencies
10:40:19 AM: Finished saving maven dependencies
10:40:19 AM: Started saving boot dependencies
10:40:19 AM: Finished saving boot dependencies
10:40:19 AM: Started saving go dependencies
10:40:19 AM: Finished saving go dependencies
10:40:19 AM: Error running command: Build script returned non-zero exit code: 1
10:40:19 AM: Failing build: Failed to build site
10:40:19 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:40:19 AM: Finished processing build request in 48.835672091s

**Comment by ulivz** [comment]
Please do not paste useless log and create an invalid issue.

**Comment by pjolson** [comment]
Excuse me. This is my first vuepress site. Welcome to the community, I guess. Thanks for your help!



Sent from Mail for Windows 10
