### ISSUE TITLE
Typo in Content-Outlet

### ISSUE THREAD

**Issue by nknapp** [vuejs/vuepress#1105]
- [x ] I confirm that this is a issue rather than a question.

## Bug report

This [line in the Content component](https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/core/lib/app/components/Content.vue#L8) looks liks a typo to me. It should probably be `content`, not `conent`.

#### Version

The master branch of this repo.

**Comment by ulivz** [comment]
Thank for the report, updated at ed10110
