### ISSUE TITLE
Anchor link not jump

### ISSUE THREAD

**Issue by intijk** [vuejs/vuepress#1107]
- [x] I confirm that this is a issue rather than a question.

#### Version
1.0.0-alpha.29

#### Steps to reproduce

Open any link for example https://vuepress.vuejs.org/zh/plugin/option-api.html
Click left side sub level anchor link.

#### What is expected?
Page should jump scroll to target section. 

![](https://raw.githubusercontent.com/intijk/refimage/master/vuepress_anchor_bug.png)

#### What is actually happening?
Jump not happen

#### Other relevant information

- Your OS: 
Ubuntu 18.04
- Node.js version: 
- Browser version: 
Firefox 64.0
- Is this a global or local install? 
Both in online doc and local `yarn dev` 
- Which package manager did you use for the install?
yarn

**Comment by intijk** [comment]
Also reproduced in Chrome.

**Comment by dimitrieh** [comment]
I would like to add that certain plugins are no longer functioning which is I think related.

In the following example you see me refresh a cached page:

![2018-12-16 23 40 10](https://user-images.githubusercontent.com/429659/50059820-0c01bb00-018c-11e9-8a78-4e0d64ed0eb8.gif)

**Comment by dimitrieh** [comment]
@ulivz as this is closed, did you  have a look at  https://github.com/vuejs/vuepress/issues/1107#issuecomment-447683444 ? I  can  create a new  issue if that is  appreciated 😉

**Comment by ulivz** [comment]
@dimitrieh Feel free to open a new issue.

**Comment by dimitrieh** [comment]
@ulivz see #1113
