### ISSUE TITLE
Has anyone gotten mermaid working?

### ISSUE THREAD

**Issue by CrossEye** [vuejs/vuepress#111]
How would I get **[mermaid][mm]** diagrams formatted in vuepress?

I tried this with a correct NPM install:

```js
module.exports = {
  markdown: {
    config: md => {
      md.use(require('markdown-it-mermaid'))
      md.use(require('markdown-it-footnote'))
    }
  }
}
```
... and I tried the same with all five markdown-it plugins [found in an NPM search][np].  Most of them generated errors of some sort, and the one that didn't simply did nothing, showing this block

    ```mermaid
    graph TD
        A[Christmas] -->|Get money| B(Go shopping)
        B --> C{Let me think}
        C -->|One| D[Laptop]
        C -->|Two| E[iPhone]
        C -->|Three| F[Car]
    ```
as an fenced block of unknown type.

This is not the overall `markdown-it` plugin process, since I tested it with `markdown-it-footnote`, and it worked fine.

I've been looking for a tool to replace an awful Confluence implementation, and I like what I see so far of vuepress.  I would love to be able to integrate mermaid as well.  Has anyone done this successfully?  Any suggestions for another plugin or a better way to integrate this?

  [mm]: https://github.com/knsv/mermaid
  [np]: https://www.npmjs.com/search?q=markdown-it%20mermaid

**Comment by CrossEye** [comment]
@inosik:

Thank you for your help.  This is not yet a top priority for me.  But mermaid is one of the factors I'm considering as I compare some tools.

**Comment by vedmalex** [comment]
Hi! the same issue for me.

1. vuepress eject
2. go to .vuepress/theme/Layout.vue
```
import mermaid from "mermaid";

mermaid.initialize({
  startOnLoad: true
});
```
3. then in .md file 
<pre>
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
</pre>

it will generate the code like this:
```html
<div class="mermaid">graph TD;
    A--&gt;B;
    A--&gt;C;
    B--&gt;D;
    C--&gt;D;</div>
```
but it won't works for me...

**Comment by vedmalex** [comment]
@inosik can you share somehow the project?

**Comment by inosik** [comment]
Sure, I here's a Gist with the modified file: https://gist.github.com/inosik/b896edeeea99f661c49d7b39644b9bdf

[Line 19](https://gist.github.com/inosik/b896edeeea99f661c49d7b39644b9bdf#file-layout-vue-L19) and [Line 110](https://gist.github.com/inosik/b896edeeea99f661c49d7b39644b9bdf#file-layout-vue-L110) are the only changes I added.

**Comment by vedmalex** [comment]
Thanks @inosik I've found out 
i've just use `import mermaid from "mermaid/dist/mermaid";`
and it working now!

**Comment by vedmalex** [comment]
https://gist.github.com/vedmalex/88830bdf64a45b745e142eef9e5c805d
```vue

<template>
</template>

<script>
export default {
  mounted() {
    import("mermaid/dist/mermaid").then(m => {
      m.initialize({
        startOnLoad: true,
      });
    });
  }
};
</script>
```

and then include it in markdown

<pre>
# sample mermaid project

&lt;mermaid/&gt;

```mermaid
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[Car]
```
</pre>

**Comment by CrossEye** [comment]
This is great!  Thanks everyone who looked into this!

**Comment by dyyce** [comment]
Thx for the instructions!!! 😄 
I got mermaid to run and it works at first.

But after switching pages it is not rendering anymore.

e.g.

* go to page with mermaid graph -> render **ok**
* go to next page (or a different page)
* go back to page with mermaid graph -> render **not ok**
* it just shows the graph syntax, but does not render

Anyone else got this behaviour?

**Comment by vedmalex** [comment]
https://gist.github.com/vedmalex/60cc85b419da134032b70969ca10b426
i've update it:
```vue
<template>
</template>

<script>
export default {
  mounted() {
    import("mermaid/dist/mermaid").then(m => {
      m.initialize({
        startOnLoad: true
      });
      m.init();
    });
  }
};
</script>
```

**Comment by dyyce** [comment]
@vedmalex thx for the quick response! 😀 

unfortunately it does not change anything for me 🤔 
do I have to create a `mermaid.vue` file and import it? I have put your code inside the `mounted()` function of `Layout.vue`

Cheers

**Comment by vedmalex** [comment]
@dyyce I use it as component

**Comment by dyyce** [comment]
@vedmalex thx again, unfortunately it didn't worked out. Might have missed something.

But I found a workaround for me.
I just added `mermaid.init()` to the `updateMetaTags` function in the `Layout.vue` file. Seems to be fine for now :)

Cheers!

**Comment by vedmalex** [comment]
@dyyce may be we need to make PR for support mermaid by default?

**Comment by superpikar** [comment]
@dyyce have you solve `wndow is not defined` problem? I got the same issue when building my project.

**Comment by avishnyakov** [comment]
Wouldn't it be great to support mermaid diagrams out of the box considering that VuePress comes with default tech documentation ready theme?

**Comment by devCrossNet** [comment]
@CrossEye can you reopen the issue or create a feature request?

I am at a point where I would love to have diagrams in my documentation :-)

**Comment by CrossEye** [comment]
Reopened.  The project I was using this for has been put aside for a while, but I expect it to be back on soon.  And it looks as though most of the answers here are to some extent hacks.  It would be great if this feature could be added to the default theme or the core.

**Comment by MurWhite** [comment]
Same with @dyyce and @superpikar . `window is not defined` occured when run `vuepress build docs` but not when run `vuepress dev docs`. Should someone open a new bug issue?

**Comment by dyyce** [comment]
@MurWhite I think it is because in production build there is no browser active and for that reason also no window object. But mermaid requires the window object to render the graphs. It isn’t really a bug, but I am also not sure how to fix it.

**Comment by rufuspollock** [comment]
Anyone have any updates or thoughts here? We really want this for our handbook https://gitlab.com/datopian/handbook/issues/5

**Comment by neumayr** [comment]
This is working for me – Crosspost from [gist](https://gist.github.com/vedmalex/88830bdf64a45b745e142eef9e5c805d#gistcomment-2619745)

---

This is how I got it working on `mermaid` `v8.0.0` and `vuepress` `v0.10.1`

```js
// .vuepress/components/mermaid.vue

<template>
  <div class="mermaid">
    <slot></slot>
  </div>
</template>

<script>
export default {
  mounted() {
    import("mermaid/dist/mermaid").then(m => {
      m.initialize({
        startOnLoad: true
      });
      m.init();
    });
  }
};
</script>
```

And my `README.md` looks like:

```md
### mermaid

<mermaid>
graph TD
  A[Silvester] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[Car]
   
  C -->|Four| F[Mac]
</mermaid>
```

**Notice** Blank lines are making trouble, my workaround is adding a `&nbsp;` after the blank line indentation `   ` (`<Space><Space><&nbsp;>` or `<Space><Space><!-- // -->`)

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by neumayr** [comment]
This is how I got it working on `mermaid` `v8.0.0` and `vuepress` `v0.10.1`

```js
// .vuepress/components/mermaid.vue

<template>
  <div class="mermaid">
    <slot></slot>
  </div>
</template>

<script>
export default {
  mounted() {
    import("mermaid/dist/mermaid").then(m => {
      m.initialize({
        startOnLoad: true
      });
      m.init();
    });
  }
};
</script>
```

And my `README.md` looks like:

```md
### mermaid

<mermaid>
graph TD
  A[Silvester] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[Car]
   
  C -->|Four| F[Mac]
</mermaid>
```

**⚠️ Notice** Blank lines are making trouble, my workaround is adding a `&nbsp;` after the blank line indentation `   ` (`<Space><Space><&nbsp;>`)

x-post: https://gist.github.com/vedmalex/88830bdf64a45b745e142eef9e5c805d#gistcomment-2619745

**Comment by rufuspollock** [comment]
@ulviz the basic issue is unresolved and i'm regularly checking in here to see if there is a solution. I'd vote for re-opening as this is an active issue in using vuepress and a blocker for greater adoption at my end.

**Comment by ulivz** [comment]
@rufuspollock 

If it turns out to be a bug, could you help to create a reproduction repo?

you can use this boilerplate to create a proper reproduction repo quickly: https://github.com/ulivz/template-vuepress

**Comment by rufuspollock** [comment]
@ulivz thanks for suggesting that. I don't think i'll have time immediately for this - but when i come back and do an update i'll let you know (i'm tracking the issue myself in my gitlab repo https://gitlab.com/datopian/handbook/issues/5

**Comment by rufuspollock** [comment]
@neumayr to clarify are you using the markdown-it mermaid stuff or are you installing mermaid directly? Can you add your package.json and mermaid config.js for clarity? Much appreciated :smile:

**Comment by RichardMatsen** [comment]
@neumayr thanks your code sample works well for me. Initially I still had mermaid imported in Layout.vue and that caused the build error mentioned above (window not defined), but after removing those references it builds ok.

**Comment by CrossEye** [comment]
I'm back on a project related to the one that spurred this issue.  I will check out the solution from @neumayr.  I'm curious if anyone has managed to get mermaid working against syntax like this?:

    ```mermaid
    graph TD
      A[Silvester] -->|Get money| B(Go shopping)
      B --> C{Let me think}
      C -->|One| D[Laptop]
      C -->|Two| E[iPhone]
      C -->|Three| F[Car]
       
      C -->|Four| F[Mac]
    ```

That is, I would love to have the mermaid diagram syntax simply look like code if viewed without mermaid enabled (say in GitHub's viewer).  Has anyone managed to do this?

**Comment by maartenvanderhoef** [comment]
Currently using vuepress-1.0.0-alpha.25 with mermaid like this, would love to know how this can be done better.
```html
<mermaid/>
<div class="mermaid">
graph LR
    A --- B
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner);
</div>
```

**Comment by blurab** [comment]
get ride of it as follow , in Page.vue
``` javascript
export default {
  props: ['sidebarItems'],
    mounted() {
   
      import("mermaid/dist/mermaid").then(m => {
        m.initialize({
          startOnLoad: true
        });
        m.init();
      });
    },
   updated () {
      
      import("mermaid/dist/mermaid").then(m => {
        m.initialize({
          startOnLoad: true
        });
        m.init();
      });
    },
```
and in my .md:
 
<div class="mermaid">
graph TD
  A[Silvester] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[Car]
  C -->|Four| F[Mac]
</div>

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by rufuspollock** [comment]
For anyone searching through https://gist.github.com/vedmalex/88830bdf64a45b745e142eef9e5c805d#gistcomment-2619745 is the current best-state of things.

I would still like to know if anyone has, got mermaid working with ...

* [ ] backticks ``` rather than `<mermaid>` blocks (atm this means constantly doing find and replace on backticks in vuepress markdown
* [ ] support for blank lines etc

Question: why do no solutions use markdown-it-mermaid https://www.npmjs.com/package/markdown-it-mermaid? Does that not help at all?

@ulivz i would vote this is still not fully resolved. There is a working "hack" for this but it does not seem very clean or easy to implement.

**Comment by PeppeL-G** [comment]
@rufuspollock I can be wrong, but I've assumed `markdown-it-mermaid` doesn't work in VuePress because VuePress do Server-Side Rendering, and here mermaid will fail because it makes use of client-side only functionalities. Therefor we must make use of a Vue component to make sure that the client-side only functionalities only are used on the client by using the `mounted()` callback.

**Comment by andymed-jlp** [comment]
Hi @CrossEye & @rufuspollock - I've got it working with the backtick formatting. It's a little hacky but works for me. Please let me know how you get on with it. :-)

```<template>
  <div class="mermaid">
    <slot></slot>
  </div>
</template>

<style>
div.language-mermaid {
  background-color: inherit
}
</style>

<script>
export default {
  beforeMount() {
    import("mermaid/dist/mermaid").then(m => {
      m.initialize({
        startOnLoad: true
      });
      m.init('div.language-mermaid>pre>code');
    });
  }
};
</script>```

**Comment by CrossEye** [comment]
Thank you @andymed-jlp!

I expect to be starting a new vuepress site soon and I will definitely check it out.

I don't recall the vuepress model well, but would it work to put that `<mermaid/>` tag inside some common include (header/footer/whatever?)

**Comment by andymed-jlp** [comment]
You're very welcome - if you hit any problems when you start the new site, just ping me. Thanks for the idea of a header/footer - that sounds like that would work!

**Comment by rufuspollock** [comment]
@andymed-jlp thanks and reporting that this worked!

**Comment by noelmace** [comment]
Go check [vuepress-plugin-mermaidjs](https://github.com/eFrane/vuepress-plugin-mermaidjs) by @eFrane. I just started to use it and so far, it's perfect.
