### ISSUE TITLE
SFC page compile error

### ISSUE THREAD

**Issue by psi-4ward** [vuejs/vuepress#1110]
- [x] I confirm that this is a issue rather than a question.

## Bug report

As far as I've seen SFCs are supported along md-Files for pages.

If I add any my-page.vue I'll get

```
TypeError: Cannot read property 'parseComponent' of undefined
    at Object.parse (node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at parse (node_modules/@vuepress/shared-utils/lib/parseVueFrontmatter.js:17:47)
    at Page.process (node_modules/@vuepress/core/lib/prepare/Page.js:125:30)
```

This is cause `@vuepress/shared-utils/lib/parseVueFrontmatter.js` gets transpiled to

```js
    const output = component_compiler_utils_1.parse({
        source: src,
        compiler: vue_template_compiler_1.default,
        needMap: false
    });
```

see the wrong `.default` at `compiler` prop.
If I remove this it works as expected.  
Another typescript gotcha?

#### Version

1.0.0-alpha.29

**Comment by ulivz** [comment]
To report an issue that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. [vuepress-issue-example](https://github.com/ocavue/vuepress-issue-example)), otherwise I don't know where you are going wrong.

**Comment by tonyxu-io** [comment]
I have the same issue, removing `default` solved the problem.
