### ISSUE TITLE
Last update didn't refresh new value

### ISSUE THREAD

**Issue by kamontat** [vuejs/vuepress#1112]
- [x] I confirm that this is a issue rather than a question.

#### Version
alpha.29

#### Steps to reproduce

1. Include last update plugin
2. create page with
```js
transformer: (timestamp, lang) => {
        moment.locale(lang || 'en')
        const time = moment(timestamp)
        return `${time.calendar()} (${time.fromNow()})`
}
```
3. the result become only static text which not update when time is pass on.

Configuration: https://github.com/kamontat/Portfolio/blob/master/gh-pages/.vuepress/config.js#L132-L138
Result: https://docs.kcnt.info/development/#notes

#### What is expected?
Update last update time format by `now` time.

#### What is actually happening?
Static text

#### Other relevant information

- Your OS: MacOS
- Node.js version: 10
- Browser version: Chrome
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, but actually it's an invalid issue.

If you are familiar with the details of the build and runtime stage, you will know that last updated will not follow the current moment. It's only updated every time you triggered build.
