### ISSUE TITLE
Plugins bottom of page do not seem to be working (noticable on https://vuepress.vuejs.org)

### ISSUE THREAD

**Issue by dimitrieh** [vuejs/vuepress#1113]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I would like to add that certain plugins are no longer functioning. In the following example you see me refresh a cached page:

![2018-12-16 23 40 10](https://user-images.githubusercontent.com/429659/50059820-0c01bb00-018c-11e9-8a78-4e0d64ed0eb8.gif)

#### Version

`v1.0.0-alpha.29`

#### Steps to reproduce

This is noticeable on https://vuepress.vuejs.org

#### What is expected?

The plugins that take care of `next page` and `edit in GH`  etc should be visible

#### What is actually happening?

PLugin outputs at the bottom of page disappear

#### Other relevant information

- Your OS: macos
- Node.js version: v11.3.0
- Browser version: chrome Version 71.0.3578.80 
- Is this a global or local install? `local`
- Which package manager did you use for the install? `yarn`

**Comment by dimitrieh** [comment]
cc: @ulivz

**Comment by ulivz** [comment]
Try `1.0.0-alpha.30`.
