### ISSUE TITLE
Wrong editLink in default-theme with index.md

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#1115]
- [x] I confirm that this is a issue rather than a question.

#### Version

v1.0.0-alpha.29

#### Steps to reproduce

https://github.com/vuejs/vuepress/blob/1c2aa08ed528fc084044184fe44afc854f119769/packages/%40vuepress/theme-default/components/Page.vue#L125

#### What is expected?

Both `index.md` and `README.md` are supported. 

#### What is actually happening?

Wrong path if using `index.md` instead of `README.md` as the index filename.

#### Possible solution

Add an extra config field like `indexFileName`, which is set to `README.md` by default.

**Comment by ulivz** [comment]
Truly an issue and first reported at https://github.com/vuejs/vuepress/issues/1021
