### ISSUE TITLE
Unknown custom element: <NotFound>

### ISSUE THREAD

**Issue by zhangyuhan2016** [vuejs/vuepress#1124]
## Bug report
[Vue warn]: Unknown custom element: <NotFound> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

<LayoutDistributor> at node_modules/@vuepress/core/lib/app/components/LayoutDistributor.vue

#### Version
vuepress:  1.0.0-alpha.30

#### Steps to reproduce

Hi,I created a new project and used the following directory structure:

-- docs
----guide
------README.md
--package.json

It doesn't work properly

I tried this solution [vue-loader@latest](https://github.com/vuejs/vuepress/issues/69), but it didn't work

#### Other relevant information

- Your OS:  win10
- Node.js version:  v8.12.0
- Npm version:  6.4.1
- Is this a global or local install?  
 global & local
 global : 1.0.0-alpha.27
 local:    1.0.0-alpha.30

**Comment by zhangyuhan2016** [comment]
😂 I'm sorry, I tried using yarn installation and now it is running fine , you can turn off the problem

**Comment by rafi** [comment]
@zhangyuhan2016 I'm experiencing the same error. How did you solve it? I'm using `yarn run dev` which runs `vuepress dev`..

**Comment by ulivz** [comment]
@rafi You can open a separate issue with invalid reproduction repo to describe your context, or no one would help you.

**Comment by eugeneotto** [comment]
The fix for me was to move `.vuepress` from the project root to the docs root (e.g. `docs/`).

**Comment by ciarans** [comment]
I had to stop and restart dev to get my component to show
