### ISSUE TITLE
NotFound component doesn't work

### ISSUE THREAD

**Issue by dcastil** [vuejs/vuepress#1130]
- [x] I confirm that this is a issue rather than a question.

#### Version

`vuepress@1.0.0-alpha.30`

#### Steps to reproduce

```bash
$ git clone git@github.com:vuejs/vuepress.git
$ cd vuepress
$ yarn
$ yarn dev
```

Then navigate to `localhost:8080/not-existent` in any browser.

#### What is expected?

Seeing the standard 404 page.

#### What is actually happening?

A blank page is rendered and I get an error about an unknown custom element `<NotFound>` as shown in the screenshot below.

<img width="888" alt="screenshot 2018-12-23 at 23 10 01" src="https://user-images.githubusercontent.com/31006608/50387906-e2a2db00-0707-11e9-8c76-1721cd7dac20.png">

#### Other relevant information

- Your OS: Mac OS Mojave 10.14.2
- Node.js version: v10.14.2
- Browser version: Chrome v71.0.3578.98
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

Relates to https://github.com/vuejs/vuepress/issues/1124

**Comment by DerZade** [comment]
Same Problem for me.

**Comment by zhangyuhan2016** [comment]
@dcastil @htakao @duncan 
Hi~
I don't know the standard solution, but you can use the following : 

Refer to this directory structure [directory-structure](https://vuepress.vuejs.org/guide/directory-structure.html)

Create a new **NotFound.vue** in the **components** folder.

Rerun and you'll get the results you want.

**Comment by nunibaranes** [comment]
Same problem for me,
OS: Mac OS Mojave 10.14.2
Node: v10.14.2
Browser: Chrome v71 and Firefox 64

**Comment by ulivz** [comment]
@nunibaranes It has been fixed but not released yet.

**Comment by nunibaranes** [comment]
> @nunibaranes It has been fixed but not released yet.

Can you tell me if it could be until next week?
