### ISSUE TITLE
Special character ~ in the build files wont support on Google App Engine

### ISSUE THREAD

**Issue by websiddu** [vuejs/vuepress#1132]
Vuepress by default bundles search and after the build it creates a file vendors~docsearch.[hash].js file. 

This works with most of the hosting options, but not with Google App Engine. Google App Engine won't allow to upload static files with names that contains a special character. 

Reference 
https://stackoverflow.com/questions/24893204/app-engine-static-files-with-special-characters-causes-404-file-not-found
https://b.corp.google.com/issues/35885974

Not sure whats the benefit in using ~ vs a simple dot.

**Comment by ulivz** [comment]
> Please don't delete this template or we'll close your issue

Hope you have seen it before opening an issue.
