### ISSUE TITLE
Blog permalinks only working on default language

### ISSUE THREAD

**Issue by Robjam** [vuejs/vuepress#1135]
- [x] I confirm that this is a issue rather than a question.

## Bug report
Blog-plugin permalink with multiple locales are ignored.

#### Version
1.0.0-alpha.30

#### Steps to reproduce

- clone sample [repo](https://github.com/Robjam/vuepressLocaleBlogRepro)

- install dependecies `yarn`

- run locally `yarn dev:blog`

- navigate to localhost:8080/jp/2018/12/26/first-article.html (404)
- (confirmation) navigate to localhost:8080/jp/_posts/FirstArticle.html

#### What is expected?
localhost:8080/jp/2018/12/26/first-article.html should load the page

#### What is actually happening?
localhost:8080/jp/_posts/firstarticle.html loads the page

#### Other relevant information

- Your OS: 
MacOS Mojave 10.14.1

- Node.js version: 
10.14.2
	
- Browser version:
Firefox 64

- Is this a global or local install?
local

- Which package manager did you use for the install?
yarn

I can make a PR if interested.

**Comment by seifertm** [comment]
I am running into the same issue. Have you found a workaround until this is addressed?

**Comment by ulivz** [comment]
We have reimplemented the blog plugin. (See: https://github.com/vuejs/vuepress/issues/36#issuecomment-498633025)

Could you help check if this issue exists at the [new blog plugin](https://github.com/ulivz/vuepress-plugin-blog)? If yes, please create issue at there.
