### ISSUE TITLE
How to automatically jump to the page？

### ISSUE THREAD

**Issue by LL-LAILAI** [vuejs/vuepress#1137]
When I input  https://vuepress.vuejs.org/zh, press Enter to automatically jump to https://vuepress.vuejs.org/zh/ instead of returning 404.

**Comment by ulivz** [comment]
Yes, https://vuepress.vuejs.org/zh will be redirected to https://vuepress.vuejs.org/zh/

**Comment by LL-LAILAI** [comment]
but,it will not be redirected to in my project,Where can I set it up?
