### ISSUE TITLE
Integrated dark mode

### ISSUE THREAD

**Issue by slice** [vuejs/vuepress#114]
Feature suggestion — an included, toggleable dark mode would be nice. Not sure how to approach this from a UI perspective, though. Perhaps a button in the sidebar or nav bar?

**Comment by yyx990803** [comment]
We want to keep the default theme minimal and won't be adding features that can be done in custom themes.

**Comment by jrappen** [comment]
@yyx990803, @ulivz in case you reconsider:

Leaving a link here about how Safari will be able to be queried for possible current dark mode:

https://www.macstories.net/news/safari-technology-preview-allows-websites-to-switch-themes-based-on-mojaves-dark-mode/

Couldn't find anything about how to do it on Windows (in the future).

**Comment by polyzen** [comment]
IMO [`prefers-color-scheme`](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme) is something all websites should support someday.
