### ISSUE TITLE
refresh page report a error

### ISSUE THREAD

**Issue by LL-LAILAI** [vuejs/vuepress#1141]
Why throw an error after refreshing, but not when open it for the first time?
![image](https://user-images.githubusercontent.com/30370215/50536103-edd48b80-0b8b-11e9-90f6-4de4807d187d.png)

**Comment by ulivz** [comment]
Please don't delete issue template or we'll close your issue. (This sentence should be visible when you created the issue.)

**Comment by agrass-GitHub** [comment]
I also have this problem, how to solve it
