### ISSUE TITLE
ENOSPC: no space left on device, write error on Gitlab CI/CD Pipeline

### ISSUE THREAD

**Issue by jpvajda** [vuejs/vuepress#1145]
### issue 

When making updates to VuePress and running the CI / CD Pipeline job in Gitlab I get the following error. It's not clear to me what is causing this issue, any help would be appreciated. I thought i may be relating to the DB package `"caniuse-db": "^1.0.30000925"` so I added that to my dependencies in package.json, with `yarn add caniuse-db`  but I'm still getting the same error.

### expected results

pipeline job completes and passes without failures. 

### error message 
```
$ yarn install
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/caniuse-db/-/caniuse-db-1.0.30000847.tgz: ENOSPC: no space left on device, write".
info If you think this is a bug, please open a bug report with the information provided in "/builds/xxxx/docs/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Job failed: exit code 1
```

**Comment by jpvajda** [comment]
reopening as this is occurring again.

**Comment by ulivz** [comment]
You should report this issue in [yarn](https://github.com/yarnpkg/yarn/issues)
