### ISSUE TITLE
refresh will result in 404

### ISSUE THREAD

**Issue by recoluan** [vuejs/vuepress#1149]
- [ ] I confirm that this is a issue rather than a question.

## Bug report
I'm develop a theme named vuepress-theme-reco, its my web site(https://recoluan.gitlab.io). I added some routes to create new page, it can be accessed normally after deployment, but a refresh will result in 404. But it's ok in the local, I knew vuepress use mode-history，but why it's ok in the local，and how can I resolve my problem?Thanks!

This happens in tabs page and categories page
#### Version

vuepress 0.14.8

#### Steps to reproduce

- Your OS: mac
- Node.js version: 11.4.0
- Browser version: chrome
- Is this a global or local install? online
- Which package manager did you use for the install?npm

**Comment by ulivz** [comment]
Thank for your interest in VuePress, but I cannot reproduce it after refreshing your site. could you provide more details?

**Comment by recoluan** [comment]
1. I plan to add routes in `enhancedApp.js` with `addRoutes` to realize the page of category and tag wall.

2. SSR makes it impossible for me to develop themes at will because of various restrictions.

3. My problem can be closed. I think there is no solution at present. It is hoped that the post-optimization of `vuepress` will be more beneficial to developers.Thank you.

**Comment by recoluan** [comment]
1. I plan to add routes in enhancedApp.js with addRoutes to realize the page of category and tag wall.

2. SSR makes it impossible for me to develop themes at will because of various restrictions.

3. My problem can be closed. I think there is no solution at present. It is hoped that the post-optimization of vuepress will be more beneficial to developers.Thank you.
