### ISSUE TITLE
When I import code Snippets,It doesn't work as expected and show "Not Found: E"

### ISSUE THREAD

**Issue by jiaming743** [vuejs/vuepress#1151]
- [x] I confirm that this is a issue rather than a question.

## Bug report
When I import code Snippets,It doesn't work as expected and show "Not Found: E"

I tried to clone your project and run it, it still doesn't show up as expected.

git clone https://github.com/vuejs/vuepress.git
cd vuepress
yarn
yarn dev

http://localhost:8080/guide/markdown.html#import-code-snippets

# Import Code Snippets

Input
```
<<< @/test/markdown/fragments/snippet.js{2}
```

Output
```
Not Found: E
```

#### Version
global (vuepress@0.14.8) and local (vuepress@0.14.8)

#### What is expected?
show code snippets

#### What is actually happening?
Not Found:  E

#### Other relevant information

- Your OS: Windows 10
- Node.js version: 10.13.0
- Browser version: Chrome 70.0.3538.102
- Is this a global or local install? global (vuepress@0.14.8) and local (vuepress@0.14.8)
- Which package manager did you use for the install? yarn

**Comment by Shigma** [comment]
https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/markdown/lib/snippet.js#L27

It seems that vuepress delete all characters after `:`, which results in this problem.

**Comment by jiaming743** [comment]
> It seems that vuepress delete all characters after `:`, which results in this problem.

Thanks

**Comment by jiaming743** [comment]
> https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/markdown/lib/snippet.js#L27
> 
> It seems that vuepress delete all characters after `:`, which results in this problem.

I removed ":" but it still shows `Not found: E`

**myProject/node_modules/vuepress/lib/markdown/snippet.js#27**
`const filename = rawPath.split(/[{\s]/).shift()`

What's more

I tried **console.log(content)** and the contents of the file can be read normally.
