### ISSUE TITLE
feat: Use semantic HTML in default theme

### ISSUE THREAD

**Issue by HerrBertling** [vuejs/vuepress#1154]
## Feature request

I'd like to improve the default theme by using some semantic HTML tags in favor of `div`s throughout the default theme.

#### What problem does this feature solve?

This would make the default vuepress theme (and thus quite some documentation pages) a bit more accessible.

#### What does the proposed API look like?

It's not really an API, I just found some places in the theme that could use `main`, `aside` or `footer` instead of a simple `div`. For example:

* [`footer` here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Page.vue#L7)
* [`main` here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Home.vue#L2)
* [`aside` here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Sidebar.vue#L2)
* [`role="search"` here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/AlgoliaSearchBox.vue#L2)
* [`section` here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/SidebarGroup.vue#L2)
* [`header` here](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Home.vue#L3)

I'm not sure whether I'd touch the navbar navigation parts. I'd prefer `li`s instead of a `div` per `.nav-item`, but I'm aware that this change would require way more cross-device/env testing than the "simple quick wins" by exchanging some tags.

#### How should this be implemented in your opinion?

I'd open a pull request if this is something of interest?

#### Are you willing to work on this yourself?**

See above :)

By the way: I thought about this some time ago and [this article](https://benrobertson.io/accessibility/designing-layouts-for-screen-readers) reminded me of that, so I figured I'd ask :)

**Comment by yyx990803** [comment]
Sounds good for a PR!

**Comment by HerrBertling** [comment]
Pull request opened 😊
