### ISSUE TITLE
Unnecessary console.log during build and dev

### ISSUE THREAD

**Issue by bretterer** [vuejs/vuepress#1155]
- [x] I confirm that this is a issue rather than a question.

#### Version
1.0.0-alpha.30

#### Steps to reproduce
Create a markdown file with an `<a href=` tag.  run `yarn build`

#### What is expected?
Clean console output

#### What is actually happening?
It is `console.log`ing the link string

#### Other relevant information
It appears that there is a `console.log` being used at https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown/lib/component.js#L46  Removing this console.log cleans this up.  Is this here on purpose or can it be removed?

- Your OS:  Mac
- Node.js version: 11.6
- Browser version:  Chrome 71.0.3578.98
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Thanks for the report and contribution welcome!

**Comment by bretterer** [comment]
Wanted to make sure that was not necessary for some reason that was not clear to me.   PR on its way
