### ISSUE TITLE
plugin additionalPages frontmatter attribute ignored when combined with content

### ISSUE THREAD

**Issue by sullivanpt** [vuejs/vuepress#1157]
- [x ] I confirm that this is a issue rather than a question.

#### Version
vuepress@1.0.0-alpha.30

#### Steps to reproduce

make a vuepress plugin like the following

```
module.exports = {
  name: 'my-plugin',
  async additionalPages () {
    return [
      {
        path: '/mypath/',
        frontmatter: {
           key: 'value'
        },
        content: '## my custom\npage {{ $page }}'
      }
    ]
  }
}
```

build vuepress (e.g. "npm run docs:build"), open the generated file (e.g. /dist/mypath/index.html), observe the frontmatter is empty.

```
page {
            &quot;title&quot;: &quot;my custom&quot;,
            &quot;frontmatter&quot;: {  },
            &quot;regularPath&quot;: &quot;/changelog/&quot;,
```

#### What is expected?

frontmatter in additionalPages should be included in $page

#### What is actually happening?

$page.frontmatter is empty. I'm just guessing that it is being overridden by the "empty" frontmatter embedded in the content attribute; if so then I think these should be merged (up for debate I guess).

Note, not a blocker as one can work around this by defining the frontmatter in a plugin extendPageData. But it seems awkward. The following works as expected:
```
  async additionalPages () {
    return [
      {
        path: '/mypath/',
        content: '## my custom\npage {{ $page }}'
      }
    ],
  extendPageData ($page) {
    $page.frontmatter.key = 'value'
  }
```

#### Other relevant information

- Your OS:  Windows
- Node.js version: 8.12.0
- Browser version: N/A
- Is this a global or local install? local
- Which package manager did you use for the install? npm 6.4.1

**Comment by sullivanpt** [comment]
Awesome, thank you!  Is it OK if I follow in your footsteps and submit some similar PR, such as not overwriting 'title' if explicitly provided?

**Comment by ulivz** [comment]
@sullivanpt Welcome to submit PRs 👍
