### ISSUE TITLE
How to create dynamic meta tags?

### ISSUE THREAD

**Issue by ShailenNaidoo** [vuejs/vuepress#1165]
Hey folks, i might be not seeing something in the docs but if it is there do you mind pointing it out to me. 

I want to know if it is possible to generate dynamic meta tags per a `.md` file so that the documents can be compliant with the [Open Graph Protocol](http://ogp.me/)

Thanks in advance 😄

**Comment by ulivz** [comment]
https://vuepress.vuejs.org/guide/frontmatter.html#meta

**Comment by alsargent** [comment]
@ulivz Unfortunately https://vuepress.vuejs.org/guide/frontmatter.html gives a 404. I have the same question as @ShailenNaidoo ... how to incorporate Open Graph information into Vuepress articles.

**Comment by ulivz** [comment]
@alsargent See: https://v1.vuepress.vuejs.org/guide/frontmatter.html
