### ISSUE TITLE
Support for korean language

### ISSUE THREAD

**Issue by hg-pyun** [vuejs/vuepress#117]
Hello.

There are many Koreans who use vue So I want to support Korean version document.
I hope your project will be accessible to more Koreans.
Can I tell you the procedure for creating a Korean version?

Thank you.

**Comment by hg-pyun** [comment]
@YuyangGong Thank you for guide. I pending this.

**Comment by yyx990803** [comment]
We will have documentation for adding a new language soon, and PR is welcome.
