### ISSUE TITLE
List of All VuePress Themes

### ISSUE THREAD

**Issue by yonkov** [vuejs/vuepress#1171]
## Feature request

I am happy to have tried VuePress and it is great! I am using it for one of my projects (the default theme with some minor modifications). My suggestion is to make a themes' website with a list of all VuePress themes that were created by the community. The themes will be automatically added to the themes' site. Should be something like [this website](https://themes.gohugo.io/) but for VuePress.

#### What problem does this feature solve?

People will be able to easily find the theme that best suits their needs and more people will be attracted to use VuePress when they see they can choose from a broad list of nice-looking themes.  

Not all the users have the time or the necessity to make a custom theme themselves and currently there is no easy way to search / find any existing VuePress themes. 

Moreover, the developers will be more than happy to see their effort being listed on the theme's website, respectively more people will be able to find their products and more GitHub stars they will get.

#### What does the proposed API look like?

The process of adding the themes to the website should be automated. The developers should be able to upload their themes on the website.

#### How should this be implemented in your opinion?
Hugo Static site generator has accomplished that. Please check this [link](https://github.com/gohugoio/hugoThemes) to see how they did it. I am not sure how this can be implemented for VuePress though 

#### Are you willing to work on this yourself?**

I am not sure how to do it.

**Comment by meteorlxy** [comment]
For now you can check [Awesome Vuepress](https://github.com/meteorlxy/awesome-vuepress).

Of course a theme preview site is better.

**Comment by vicbergquist** [comment]
hi 👋 , I'm putting together a list of themes 😊 Just started making it so it's still missing things, but it's a start!
https://vuepress.gallery
https://github.com/vicbergquist/vuepress.gallery

**Comment by ulivz** [comment]
You can check out the official [Awesome VuePress](https://github.com/ulivz/awesome-vuepress).

We are planning to complete the design and development of the official website blog theme. If anyone is interested, please contact me.

**Comment by andreiTn** [comment]
@vicbergquist  the repository and website are not maintained anymore you should remove or update your comment

**Comment by avimehenwal** [comment]
Hey @yonkov , URL seems to be dormant, do you still own the domain? Since I am learning vue I can work on it in spare time :smile: let me know if you would like to proceed
