### ISSUE TITLE
Deploy to Github Enterprise?

### ISSUE THREAD

**Issue by SeaDude** [vuejs/vuepress#1192]
Hello,
In the [VuePress Deployment Docs](https://vuepress.vuejs.org/guide/deploy.html#github-pages), the URL options are:

* `https://<USERNAME>.github.io/`
* `https://<USERNAME>.github.io/<REPO>/`

Neither of these URL structures is what appears in my Github **Enterprise** Github Page settings:

* `https://github.<myCompany>.com/<internalUsername>/<repoName>`

* Is VuePress deployable on Enterprise?
* How do I translate the deployment instructions for Enterprise? 

Thank you!

**Comment by SeaDude** [comment]
To `config.js` I added:
`base: "/<internalUsername>/<repoName>/"`
Hopefully this will work.

**Comment by ulivz** [comment]
> Is VuePress deployable on Enterprise?

You can deploy it to anywhere as long as you want.

> How do I translate the deployment instructions for Enterprise?

You should provide an detailed example before asking a question.

---

This is a question and should be asked in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress).
