### ISSUE TITLE
No matching version found for @vue/component-compiler-utils@^2.4.0

### ISSUE THREAD

**Issue by fairyly** [vuejs/vuepress#1193]
- [ ] I confirm that this is a issue rather than a question.

## Bug report
```
>npm install -g vuepress
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Bro
wserslist >3.0 config used in other tools.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/component-compiler-utils@^2
.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'vue-loader'
npm ERR! notarget
```

#### Other relevant information

- Your OS:  win7
- Node.js version:  v8.11.2
- Browser version:  71.0.3578.98
- Is this a global or local install?  global 
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
I guess you installed vue-cli globally.

**Comment by fairyly** [comment]
@ulivz I  was installed vue-cli global.

**Comment by ulivz** [comment]
FYI, VuePress doesn't depend on `@vue/component-compiler-utils@^2.4.0`, please check your environment.

---

BTW, `was` should be removed, and `global` should be `globally`.
