### ISSUE TITLE
[PRISM-JS] plugin what do you think about it ?

### ISSUE THREAD

**Issue by f3ltron** [vuejs/vuepress#1198]
## Feature request

Hello i would like to present you my [vuepress-plugin-prismjs](https://f3ltron.github.io/vuepress-plugin-prismjs/)

#### What problem does this feature solve?

It solve some prismjs api we dont have access by default because vuepress using primjs from node

#### What does the proposed API look like?

go to the link url 👍 

#### How should this be implemented in your opinion?

Maybe added to core plugins

#### Are you willing to work on this yourself?**

I am actually working on it. But i need some return about what do you expect about a plugin and this plugin before expecting having it in core plugins.

It is in [WIP] so not considering using it in production for now. But some functionnalities working well

**Comment by ulivz** [comment]
Thanks for the great work, but we don't want to introduce it to the core, we even want to reduce to count of official plugins.

**Comment by f3ltron** [comment]
Ok i understand so do you plan to regroup vuepress plugins ?
