### ISSUE TITLE
need new verision for plugin pagination  and blog

### ISSUE THREAD

**Issue by yuicer** [vuejs/vuepress#1199]
## Feature request
can we publish the new version for the @vuepress/plugin-blog and @vuepress/plugin-blog?
it still be 1.0.0-alpha.0 , and a lot of problems.

**Comment by ulivz** [comment]
Thanks for the suggestion, for now all the plugins were tagged `@next`, so you need to install the latest development version via `yarn add @vuepress/plugin-blog@next`.

**Comment by yuicer** [comment]
@ulivz i did this, and installed `"@vuepress/plugin-blog": "^1.0.0-alpha.32"`
but there still has some problems, i got the err `[vuepress] cannot resolve plugin "@vuepress/blog"` when i add it in my theme config
```js
const path = require('path')
module.exports = (options, ctx) => ({
  alias() {
    const { themeConfig, siteConfig } = ctx
    // resolve algolia
    const isAlgoliaSearch =
      themeConfig.algolia ||
      Object.keys((siteConfig.locales && themeConfig.locales) || {}).some(
        base => themeConfig.locales[base].algolia
      )
    return {
      '@AlgoliaSearchBox': isAlgoliaSearch
        ? path.resolve(__dirname, 'components/AlgoliaSearchBox.vue')
        : path.resolve(__dirname, 'noopModule.js')
    }
  },

  plugins: [
    '@vuepress/blog',
    '@vuepress/active-header-links',
    '@vuepress/search',
    '@vuepress/nprogress'
    // '@vuepress/pagination'
  ]
})

```

**Comment by yuicer** [comment]
i guess there has some dependency problems and make the resolver crashed at the beginning

**Comment by ulivz** [comment]
Reproduction repo please and do not paste code.

**Comment by songololo** [comment]
Would probably be good to mention in the docs to install `@vuepress/plugin-blog@next` instead of `@vuepress/plugin-blog`

**Comment by ulivz** [comment]
> Would probably be good to mention in the docs to install `@vuepress/plugin-blog@next` instead of `@vuepress/plugin-blog`

Contribution welcome!
