### ISSUE TITLE
Insert image syntax does not work

### ISSUE THREAD

**Issue by mqhe2007** [vuejs/vuepress#12]
According to the tutorial in the "Asset Handling" section, I used the
 
```
![An image][./image.png]
```

statement to insert an image, but it did not work and was output to the page as it was.
![image](https://user-images.githubusercontent.com/13450661/38767483-c2e81c36-4014-11e8-9fd8-4f135a597ea5.png)
![image](https://user-images.githubusercontent.com/13450661/38767487-d32e586c-4014-11e8-8b50-a53a0ab479e0.png)

**Comment by egoist** [comment]
That might be a typo, should be `![]()`

**Comment by MrSunshyne** [comment]
@egoist that was it! thanks

**Comment by mqhe2007** [comment]
@egoist Thank you, you are right. In addition, using relative paths can work, but the alias mode does not work.

**Comment by yyx990803** [comment]
@mqhe2007 it's just an example - you need to configure the alias yourself.
