### ISSUE TITLE
Customize the navbar without ejecting the default theme

### ISSUE THREAD

**Issue by ghys** [vuejs/vuepress#120]
Is there a way to override only the Navbar component and avoid ejecting the default theme?
My case is, I don't want the site's title displayed on the top-left because I have a full-size logo:
https://github.com/vuejs/vuepress/blob/c4772f4f721fe640eba8105a120df619dbec98d6/lib/default-theme/Navbar.vue#L8-L12
...but I'd also like to keep it defined because it appears in `<title>`. Thanks!

**Comment by yyx990803** [comment]
You can do that with override.styl.
