### ISSUE TITLE
[Netlify Deploy] 404 error

### ISSUE THREAD

**Issue by matheusagnus** [vuejs/vuepress#1200]
- [x] I confirm that this is a issue rather than a question.

#### Other relevant information

- Your OS: Windows
- Node.js version: v10.10.0
- Browser version: Chrome 71.0.3578.98
- Is this a global or local install? Local
- Which package manager did you use for the install? npm

#### I already tried to do this too: https://github.com/vuejs/vuepress/issues/441

![vuepress](https://user-images.githubusercontent.com/28713867/51313043-c27ae900-1a33-11e9-821b-122f50f783e6.png)

**Comment by ulivz** [comment]
Could you provide your Netlify config?

**Comment by ansidev** [comment]
@matheusagnus The config is wrong.
```
"scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
},
```

And there is no folder named `docs` at the same level as the file `package.json`. For the homepage, you should have a file named `index.md` in folder `docs`.
And please never upload the folder `node_modules`, I think this is a basic best practice.

You should read the documentation carefully.

You can see my repository if you need an example: https://github.com/ansidev/awesome-nuxt
