### ISSUE TITLE
Question:how to move toc to right in content page

### ISSUE THREAD

**Issue by moyokoo** [vuejs/vuepress#1211]
like this  https://vuetifyjs.com/en/getting-started/quick-start

**Comment by BusyHe** [comment]
@moyokoo do you solved？

**Comment by moyokoo** [comment]
忘记怎么修改了 ,我记得是自己手动加一个toc在内容页上面了,当时改的时候有点麻烦,毕竟我不会前端
现在我已经不用这个了

**Comment by BusyHe** [comment]
好的，我要找一下。应该能解决，实在不行自己写一个
