### ISSUE TITLE
Add syntax highlighting to inline code @ markdown

### ISSUE THREAD

**Issue by Enteleform** [vuejs/vuepress#1212]
#### What problem does this feature solve?
Inline code snippets rendered by markdown don't have a way to apply syntax highlighting.

&nbsp;  
#### What does the proposed API look like?
```html
<code class="language-foo">
```

&nbsp;  
#### How should this be implemented in your opinion?
```markdown
Syntax:
`<text>`<language>

Example:
`console.log("foo")`javascript
```

&nbsp;  
#### Are you willing to work on this yourself?**
Potentially, if it's within my abilities. I can check out the code if someone knows the best place to start.

**Comment by ulivz** [comment]
Thanks for your issue, but we don't plan to create a new syntax outside of [markdown spec](https://spec.commonmark.org/0.28/#code-spans).
