### ISSUE TITLE
Lifecycle methods are not respected in prod build (edge case I guess)

### ISSUE THREAD

**Issue by lgraziani2712** [vuejs/vuepress#1214]
- [x] I confirm that this is a issue rather than a question.

## Bug report

There's something strange with I-don't-know-what-transitional-dep which, when compiling everything for production, the `mounted` (at least the one I tested) lifecycle doesn't work as expected: instead of being called first on the children and then on the parent, is being called first on the parent and then on the children.

This happens with the compiled views. If you start changing pages without refreshing the site, everything works as expected.

I don't know what version of what lib is making this, so I cannot make a minimal reproductible repo. But my project's OSS, so you can see the commits:

- Before the bug was introduced: https://github.com/lgraziani2712/validate-me/tree/6e7d51d7627c0e4d9c6f7d56b4a62b705f96326c
- The next commit, with the bug: https://github.com/lgraziani2712/validate-me/tree/dc9b4c93397d966b9c8ad8bce8f053b835c2ed77

In that last commit, wasn't the package.json change what introduced the bug, but the `yarn upgrade` command I ran after. I know that, because I tried resetting everything, and updating one package at a time until finding the what was making the bug. But no direct dependency broke anything. Then, I ran `yarn upgrade` again, and the bug appeared. 

In the following image you can see a warning about the `Tapable.plugin` deprecation. This warning appeared until the dep's upgrade, so perhaps it's related. I don't know nor I know how to verify it.

![image](https://user-images.githubusercontent.com/15050200/51449039-f93d5180-1d08-11e9-821e-4dc4e4bcccfe.png)

- In my github pages site, is running the last correct commit: https://lgraziani2712.github.io/validate-me/
- In my netlify site, is running the last bugged commit: https://5c44dd2705a4b700072ea2f2--validate-me.netlify.com/

#### Version

- vuepress, nor vue or related, aren't the problem here. But I replicated the error with vuepress 0.14.* and v1.0.0-alpha.32. Also I could "fix" it in both versions with rollbacking the `yarn upgrade`.

#### Steps to reproduce

I don't know how to reproduce it in an isolated repo, but you could clone my repo:

- `git clone https://github.com/lgraziani2712/validate-me`
- Access the last correct commit:
   1. `git branch -b not-bugged 6e7d51d7627c0e4d9c6f7d56b4a62b705f96326c`
   2. `yarn && yarn build:docs`
   3. `npx http-server ./docs/.vuepress/dist`
      The site opens in `/validate-me`
- Acces the first bad commit:
   1. `git branch -b not-bugged dc9b4c93397d966b9c8ad8bce8f053b835c2ed77`
   2. `yarn && yarn build:docs`
   3. `npx http-server ./docs/.vuepress/dist`
      The site opens in `/validate-me`

#### What is expected?

To have the `mounted` lifecycle method ran as expected when loading the page for the first time: first the children and then the parent.

#### What is actually happening?

When the page is loaded the first time, the `mounted` lifecycle method ran first in the parent (who has no children) and the in the children.

#### Other relevant information

- Your OS: Windows 10 (but also happens in netlify).
- Node.js version: 10.15.
- Browser version: Firefox 65 & Chrome 71.
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

**Comment by lgraziani2712** [comment]
Ok... (wow) I could fix it. I had to add the following code into the vuepress config:

```js
{
  // ...
  configureWebpack(config, isServer) {
    if (isServer) {
      return;
    }

    config.optimization.splitChunks.cacheGroups.vendor = {
      test: /node_modules/,
      chunks: 'initial',
      name: 'vendor',
      priority: 0,
      enforce: true,
    };
  },
}
```

Splitting the vendor code from the app code fix it.

I still don't know what triggers this bug.

**Comment by ulivz** [comment]
See: https://vuejs.org/v2/api/#mounted

![image](https://user-images.githubusercontent.com/23133919/54493294-30933d80-4909-11e9-9f03-21b23fe8c9a2.png)

**Comment by lgraziani2712** [comment]
Thank you @ulivz! I didn't knew that `mounted` didn't guarantee that all child components have also been mounted!

`this.$nextTick` did definitively resolve the issue! 👍
