### ISSUE TITLE
Is there any way to disable the theme style in Vue code?

### ISSUE THREAD

**Issue by LasyIsLazy** [vuejs/vuepress#1218]
## Feature request
Any way to disable the theme style in Vue code

#### What problem does this feature solve?
I have used `ElementUI` and it's style in `enhanceApp.js` and write some vue code in markdown.

But there is some styles applied to my vue code in default theme. Like 

```
tr:nth-child(2n) {
    background-color: #f6f8fa;
}
```
I have to overwrite it to make my vue code looked like what is should be, it's confused.

I don't know how many styles will affect my code. I can not overwrite all of them.

In addition, if I switch to another theme, I have to write code again to overwrite what that theme's style.
#### What does the proposed API look like?
Maybe surround code with a tag like `code` and provide an attribute `disableDefaultStyle`?
Or a config in config.js?

**Comment by Shigma** [comment]
I don't think it is a good idea. You can override them by yourself if you don't like default styles.

**Comment by LasyIsLazy** [comment]
> I don't think it is a good idea. You can override them by yourself if you don't like default styles.

It will take a lot of time to find out which style I should override when there are many styles in theme.
In addition, I must repeat these steps if I change the theme.

**Comment by Shigma** [comment]
I think since you don't need all the styles, it's better to write the theme of your own. Use `vuepress eject`, which will copy the default theme into your `.vuepress/theme` folder, and you can customize your styles by editing all the `.styl` files directly.
