### ISSUE TITLE
Code splitting with script and style hoisting in mind

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#122]
Hello there!

Is there a way to make webpack also take care about code splitting with styles and scripts imported through scripts that are within the markdown file?

I'm building a blog showcasing libraries and how to build something with them.
I want to avoid relying on third party iframes such as codepen, jsfiddle or plunkr.

Previously, I inline-required the resources via `<script src="">` but this is not allowed in Vue.
While normal script tags are allowed (only in the root of the markdown document), for scripts with `src` set, you get the following error:
> Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

Now I `import` the scripts - which is a lot more comfortable, but code splitting doesn't seem to take care about this - now I have to load all the JS of all my demos on every page entrance.

**Comment by yyx990803** [comment]
Each page component is already code-split into separate chunks. Anything you import inside `<script>` tags on that page will be included in that page's chunk only.
