### ISSUE TITLE
Language does not exist: caddyfile, sh, makefile, yml and dockerfile

### ISSUE THREAD

**Issue by mbana** [vuejs/vuepress#1221]
- [x] I confirm that this is a issue rather than a question.

#### Version
`1.0.0-alpha.31`
#### Steps to reproduce
```sh
$ (cd /tmp && \
    git clone git@github.com:banaio/www-bana-io-vue-js.git && \
    cd www-bana-io-vue-js && \
    yarn install && \
    yarn docs:build)
...
Language does not exist caddyfile
Language does not exist caddyfile
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist vuepress/public/examples/circleci-authorizing-the-google-cloud-sdk_examples/makefile
Language does not exist yml
Language does not exist caddyfile
Language does not exist dockerfile
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
Language does not exist sh
...
```

#### What is expected?
No errors saying `Language does not exist *`.

#### What is actually happening?
See the `Steps to reproduce` section.

#### Other relevant information

- Your OS: 
```sh
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```
- Node.js version: `v8.12.0`
- Browser version: `Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)`
- Is this a global or local install? `Local`
- Which package manager did you use for the install? `yarn 1.10.0`

**Comment by meteorlxy** [comment]
Temporarily use `bash` for `sh` and `yaml` for `yml`

**Comment by ulivz** [comment]
Just added shortcut for `sh` and `yml` at fc5dba8, you'll get it at next version.

`dockerfile` and `makefile`  should be supported for now:

````
```dockerfile
```
```makefile
```
````

Moreover, If you want to support `caddyfile`, please go to [prismjs](https://prismjs.com/#languages-list) to report a feature request.

**Comment by mbana** [comment]
@ulivz by next version do you mean `v1.0.0-alpha.33`?
Is it possible to use the `master` build of `vuepress` somehow?
