### ISSUE TITLE
Error: render function or template not defined in component

### ISSUE THREAD

**Issue by biggabba** [vuejs/vuepress#1223]
I am sorry if I did not find relevant answer to my problem. This is my issue. I get error on `vuepress build`. In `vupress dev` goes with warning (describe later), but in `vuepress dev` code generate error (describe later). Problem is that I try several methods and been thinking that problem is inside installed `npm i vue-awesome-swiper -D` but is not, because I getting this with every dependency I install to my project. What I am doing wrong?
this is my code
```
<template>
  <md-card>
    <md-card-media class="swiper-inner">
      <!-- swiper -->
      <swiper :options="swiperOption">
        <swiper-slide v-for="i in images"><img :src="i.url" :alt="i.alt"></swiper-slide>
        
        <div class="swiper-pagination" slot="pagination"></div>
      </swiper>
    </md-card-media>
  </md-card>
</template>

<script>
import "../public/css/swiper.css"
import { swiper, swiperSlide } from 'vue-awesome-swiper'
  export default {
    name: 'carrousel',
   data() {
      return {
         images: [
                { url: '/img/slides/1.jpg', alt: 'I love you nature' },
                { url: '/img/slides/2.jpg', alt: 'Now with dog - Rosé' },
                { url: '/img/slides/3.jpg', alt: 'Jeg er i Danmark' },
                { url: '/img/slides/4.jpg', alt: 'Badabimbadabum' },
                { url: '/img/slides/5.jpg', alt: 'Goodmorning el mundo' },
                { url: '/img/slides/6.jpg', alt: 'My white and rosé with paella' }
            ],
        swiperOption: {
          effect: 'coverflow',
          grabCursor: true,
          centeredSlides: true,
          slidesPerView: 'auto',
          loop: true,
          autoplay: {
            delay: 3500,
            disableOnInteraction: false
          },
          coverflowEffect: {
            rotate: 80,
            stretch: 0,
            depth: 100,
            modifier: 1,
            slideShadows : true
          },
          pagination: {
            el: '.swiper-pagination'
          }
        }
      }
    },
    computed: {
      swiper() {
        return this.$refs.mySwiper.swiper
      }
    },
    mounted() {
      this.swiper.slideTo(3, 1000, false)
    },
    components: {
      swiper,
      swiperSlide,
      importAll(r) {
      return r.keys().map(r);
      }
   }
  }
</script>
<style lang="scss" scoped>
  .swiper-inner {
    width: 100%;
    height: 400px;
    padding-top: 50px;
    padding-bottom: 50px;
  }
  .swiper-slide {
    background-position: center;
    background-size: cover;
    width: 600px;
    height: 500px;
    img {
       height: 100%;
       width: 100%;
    }
  }
  @media (max-width: 762px) {
     .swiper-slide {
         background-position: center;
         background-size: cover;
         width: 100%;
         height: 300px;
      }
  }
  @media (max-width: 992px) {
     .swiper-slide {
         background-position: center;
         background-size: cover;
         width: 300px;
         height: 300px;
      }
  }
  
</style>
```

this is the error on `vuepress buil`:

>  WAIT  Extracting site metadata...
>  TIP  override.styl has been split into 2 APIs, we recommend you upgrade to continue.
>       See: https://v0.vuepress.vuejs.org/default-theme-config/#simple-css-override
> [3:21:00 PM] Compiling Client
> [3:21:00 PM] Compiling Server
> [3:21:07 PM] Compiled Server in 7s
> [3:21:11 PM] Compiled Client in 10s
>  WAIT  Rendering static HTML...
> Rendering page: /flatroofs/ FAIL  Error rendering /flatroofs/:
> Error: render function or template not defined in component: Slider
>     at normalizeRender (/usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7392:13)
>     at renderComponentInner (/usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7516:3)
>     at renderComponent (/usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7487:5)
>     at resolve (/usr/lib/node_modules/vuepress/node_modules/vue-server-renderer/build.js:7548:9)

this is my config:

> module.exports = {
>     title: 'Custom title',
>     description: 'This is default description tag',
>     themeConfig: {
>         nav: [ 
>             {text: 'Home', link: '/'},
>             {text: 'Flat roofs', link: '/flatroofs/'}
>         ],
>         search: false,
>         searchMaxSuggestions: 20
>     }
> }

this is my warrning on vuepress dev:

```
WARNING in ./.vuepress/components/Slider.vue?vue&type=template&id=7c9d3a98&scoped=true& (/usr/lib/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"../../../../../usr/lib/node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"18759c20-vue-loader-template"}!/usr/lib/node_modules/vuepress/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!/usr/lib/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js??ref--0-0!/usr/lib/node_modules/vuepress/node_modules/vue-loader/lib??vue-loader-options!./.vuepress/components/Slider.vue?vue&type=template&id=7c9d3a98&scoped=true&)
Module Warning (from /usr/lib/node_modules/vuepress/node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) <swiper-slide v-for="i in images">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./.vuepress/components/Slider.vue?vue&type=template&id=7c9d3a98&scoped=true& 1:0-570 1:0-570
 @ ./.vuepress/components/Slider.vue
 @ /usr/lib/node_modules/vuepress/lib/app/.temp/routes.js
 @ /usr/lib/node_modules/vuepress/lib/app/app.js
 @ /usr/lib/node_modules/vuepress/lib/app/clientEntry.js
 @ multi /usr/lib/node_modules/vuepress/lib/app/clientEntry.js

```

and this is my files:

![screenshot from 2019-01-24 15-22-40](https://user-images.githubusercontent.com/41113924/51684394-da2e1080-1fe3-11e9-9f23-8af92385633d.png)

and my package.json:

> {
>   "name": "roof",
>   "version": "1.0.0",
>   "description": "--- title: This is home page home: true description: Hello this is my home page heroImage: /img/builder.svg heroText: Jan Gabriel tagline: Front end developer footer: Jan Gabriel | Front end developer | Wordpress, Vue, VuePress ---",
>   "main": "index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "devDependencies": {
>     "node-sass": "^4.11.0",
>     "sass-loader": "^7.1.0"
>   },
>   "dependencies": {
>     "vue-awesome-swiper": "^3.1.3"
>   }
> }

**Comment by meteorlxy** [comment]
1. So follow the warning message, see https://vuejs.org/guide/list.html#key for more info.

2. A reproduce repo would help.

3. Do not delete the issue template.

**Comment by biggabba** [comment]
I created repository on
https://github.com/biggabba/vueswiper

**Comment by ulivz** [comment]
@biggabba Please remove your node_modules first.

**Comment by biggabba** [comment]
where else to install npm dependencies ?

**Comment by ulivz** [comment]
@biggabba Hmmm... `node_modules` should be set in `.gitignore`, which is a base for a NPM developer. 🙂
