### ISSUE TITLE
[Bug report] page links failed in pages that use permalink

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#1227]
- [x] I confirm that this is a issue rather than a question.

#### Version

v1.0.0-alpha.34

#### Steps to reproduce

```sh
docs
├── with-permalink.md
└── target-page.md
```

One page uses permalink, in which there is a link to the other page.

The other page does not use permalink.

```md
// with-permalink.md
---
permalink: '/foo/bar'
---

[To target page](./target-page.md)
```

#### What is expected?

The link url is rendered as `'/target-page.html'`, which points to `target-page.md`.

#### What is actually happening?

The link url is rendered as `'/foo/bar/target-page.html'`, which does not exist.

**Comment by ulivz** [comment]
To a certain extent, I don't agree that this is an issue.

Once you set permalink `foo/bar`, it means that the file will eventually be generated under `foo/bar`, but you are using a `relative path`. so there is a workaround: once you used a permalink, you should use absolute paths first. maybe at this time, we need to mark this limit in the documentation.

It is more complicated to resolve the `relative path` during the build process, and it may also bring a breaking change.

**Comment by meteorlxy** [comment]
A common situation is in posts of blog. It might be annoying to link to other posts by absolute path.

**Comment by ulivz** [comment]
In the blog lovers I know, it seems that they all use absolute paths, e.g. @egoist. [ref](https://raw.githubusercontent.com/egoist/blog/master/source/_posts/2015-10-anime-review.md).

**Comment by meteorlxy** [comment]
Oh that makes me thinking about: Why Vuepress allow links end with `.md`?

I guess it's to be compatible with docs, as many projects just put their docs on github (like lerna).

I'm not so familiar with other tools, but they might not allow `*.md` link? So users have to write the url themselves.

(Vuepress makes me lazy lol 😅 )

**Comment by Shigma** [comment]
But we cannot get the frontmatter during build process, can we?

**Comment by Shigma** [comment]
@meteorlxy We can change the behavior of resolution of relative urls in pages that use permalink.
```
if (!to.startsWith('/')) {
  to = relPath
    ? url.resolve('/' + relPath, to) // resolve url with the relative path of the file by default
    : ensureBeginningDotSlash(to)    // add a `./` before the url otherwise (previous strategy)
}
```
