### ISSUE TITLE
@vuepress/plugin-pagination: documentation or lack thereof

### ISSUE THREAD

**Issue by mbana** [vuejs/vuepress#1230]
https://vuepress.vuejs.org/plugin/official/plugin-pagination.html

Aside from the installation instructions and a how-to-use guide there is hardly any information on this plugin.

* What does it do?
* Is there an example I can see of what it does?
* No example on how to set `postsFilter`,`postsSorter`, etc.

Don't take this negatively, but the page leaves one confused.

**Comment by ulivz** [comment]
Let's go https://github.com/vuejs/vuepress/issues/1091 to continue.
