### ISSUE TITLE
[plugin-blog] Spaces and special symbols in category title

### ISSUE THREAD

**Issue by Laruxo** [vuejs/vuepress#1234]
#### What problem does this feature solve?
Currently in posts you can provide category title via frontmatter. The problem appears when you try to use more than one word for the title. In most sites we usually slugify the title, to make urls more seo and user friendly. But that does not happen when blog-plugin is generating category permalinks.

E.g. if I use `category: Awesome Posts` - category permalink becomes `/category/Awesome%20Posts.html`.
If I use `category: awesome-posts` - page title becomes `awesome-posts | Category`

Same issues exists with tags.

#### What does the proposed API look like?
In post frontmatter provide category with spaces and special symbols as needed.

#### How should this be implemented in your opinion?
When generating category permalink slugify the title with simple regex based replace.

#### Are you willing to work on this yourself?**
Yes. I already wrote a small plugin for my own blog, but I think official blog-plugin could benefit from it.

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/issues/36#issuecomment-498633025
