### ISSUE TITLE
Image path contains Chinese.build failed

### ISSUE THREAD

**Issue by tanshion** [vuejs/vuepress#1237]
- [x] I confirm that this is a issue rather than a question.

#### Version
1.0.0-alpha.33
#### Steps to reproduce
Image path contains Chinese.build failed

For example.
`![image-20190128143347796](./idea插件.assets/image-20190128143347796.png)`

```
chentengxiangdeMacBook-Pro:docs chentx$ yarn build
yarn run v1.13.0
$ vuepress build docs --temp .temp
wait Extracting site metadata...
wait Extracting site metadata...
[{"text":"devops","items":[{"text":"docker","link":"/devops/docker/docker安装常用服务命令.md"},{"text":"linux","link":"/devops/linux/7z.md"}]},{"text":"devtool","link":"/devtool/http上传json文件自带header参数.md"},{"text":"git","link":"/git/git实战.md"},{"text":"java","items":[{"text":"微服务","link":"/java/微服务/sso.md"}]}]
{ '/devops/docker/': [ 'docker安装常用服务命令.md', 'docker安装配置.md' ],
  '/devops/linux/':
   [ '7z.md',
     'centos安装和环境配置.md',
     'debain安装kvm.md',
     'dokuwiki.md',
     'minio.md',
     'raid和lvm.md' ],
  '/devtool/': [ 'http上传json文件自带header参数.md', 'idea插件.md', 'maven.md' ],
  '/git/': [ 'git实战.md', 'git操作.md' ],
  '/java/%E5%BE%AE%E6%9C%8D%E5%8A%A1/': [ 'sso.md', '线程池、Lambda表达式.md' ] }
tip Apply theme @vuepress/theme-default
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vuepress/notification (i.e. "@vuepress/plugin-notification") ...
[下午2:37:29] Compiling Client
[下午2:37:29] Compiling Server
[下午2:37:35] Compiled Server in 6s
[下午2:37:38] Compiled Client in 9s
(undefined) ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"fc14df32-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&)
Module not found: Error: Can't resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
  using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx doesn't exist
      .vue
        Field 'browser' doesn't contain a valid alias configuration
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json doesn't exist
      .styl
        Field 'browser' doesn't contain a valid alias configuration
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl doesn't exist
      as directory
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl]
 @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"fc14df32-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&) 1:361-431
 @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876&
 @ ./docs/devtool/idea插件.md
 @ ./.temp/internal/page-components.js
 @ ./node_modules/@vuepress/core/lib/app/util.js
 @ ./node_modules/@vuepress/core/lib/app/components/Content.js
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/clientEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/clientEntry.js
(undefined) ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"727217d2-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&)
Module not found: Error: Can't resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
  using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool)
    using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png)
      no extension
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
      .js
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js doesn't exist
      .jsx
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx doesn't exist
      .vue
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue doesn't exist
      .json
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json doesn't exist
      .styl
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl doesn't exist
      as directory
        /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json]
[/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl]
 @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"727217d2-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&) 1:361-431
 @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876&
 @ ./docs/devtool/idea插件.md
 @ ./.temp/internal/page-components.js
 @ ./node_modules/@vuepress/core/lib/app/util.js
 @ ./node_modules/@vuepress/core/lib/app/components/Content.js
 @ ./node_modules/@vuepress/core/lib/app/app.js
 @ ./node_modules/@vuepress/core/lib/app/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/app/serverEntry.js
Error: Failed to compile with errors.
    at webpack (/Users/chentx/Desktop/docs/node_modules/@vuepress/core/lib/build.js:103:18)
    at finalCallback (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/Users/chentx/Desktop/docs/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:220:39)
    at hooks.done.callAsync.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:236:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chentx/Desktop/docs/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chentx/Desktop/docs/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:234:21)
    at hooks.afterCompile.callAsync.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chentx/Desktop/docs/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chentx/Desktop/docs/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:627:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
chentengxiangdeMacBook-Pro:docs chentx$

```

#### Other relevant information

- Your OS: MACOSX
- Node.js version: v10.9.0
- Browser version: chrome latest
- Is this a global or local install? local
- Which package manager did you use for the install?yarn

**Comment by ulivz** [comment]
Could you create a minimal reproduction repo?

**Comment by tanshion** [comment]
[docs2.zip](https://github.com/vuejs/vuepress/files/2808459/docs2.zip)

Please check. Thank you

**Comment by ulivz** [comment]
I truly reproduced it, but actually it's an issue from one of the VuePress's deps —— [markdown-it](https://github.com/markdown-it).

markdown-it will encode all URIs and [it doesn't decide to disable this behaviors](https://github.com/markdown-it/linkify-it/issues/71), it works for those assets at the condition of using absolute path(`/xxx.png`) of assets at`public`, but the relative URIs (e.g. `![image-20190129233632400](./idea插件.assets/image-20190129233632400.png)`) at markdown files will be resolved by webpack at build process, file system doesn't decode URIs like browser before resolving it, so you got these errors.

Sorry for VuePress cannot do anything for you, please using non-ASCII characters as name of directories for your case.

**Comment by nanyuantingfeng** [comment]
i wrote a markdown-it plugin to fix this issue. 
please check `markdown-it-disable-url-encode` in npm 
and  add 
```
  markdown: {
    extendMarkdown: md => {
      md.use(require("markdown-it-disable-url-encode"));
    }
  }
``` 
to ` config.js`

**Comment by wangrongding** [comment]
> * [x]  I confirm that this is a issue rather than a question.
> 
> ## Bug report
> #### Version
> 1.0.0-alpha.33
> 
> #### Steps to reproduce
> Image path contains Chinese.build failed
> 
> For example. `![image-20190128143347796](./idea插件.assets/image-20190128143347796.png)`
> 
> ```
> chentengxiangdeMacBook-Pro:docs chentx$ yarn build
> yarn run v1.13.0
> $ vuepress build docs --temp .temp
> wait Extracting site metadata...
> wait Extracting site metadata...
> [{"text":"devops","items":[{"text":"docker","link":"/devops/docker/docker安装常用服务命令.md"},{"text":"linux","link":"/devops/linux/7z.md"}]},{"text":"devtool","link":"/devtool/http上传json文件自带header参数.md"},{"text":"git","link":"/git/git实战.md"},{"text":"java","items":[{"text":"微服务","link":"/java/微服务/sso.md"}]}]
> { '/devops/docker/': [ 'docker安装常用服务命令.md', 'docker安装配置.md' ],
>   '/devops/linux/':
>    [ '7z.md',
>      'centos安装和环境配置.md',
>      'debain安装kvm.md',
>      'dokuwiki.md',
>      'minio.md',
>      'raid和lvm.md' ],
>   '/devtool/': [ 'http上传json文件自带header参数.md', 'idea插件.md', 'maven.md' ],
>   '/git/': [ 'git实战.md', 'git操作.md' ],
>   '/java/%E5%BE%AE%E6%9C%8D%E5%8A%A1/': [ 'sso.md', '线程池、Lambda表达式.md' ] }
> tip Apply theme @vuepress/theme-default
> tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
> tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
> tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
> tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
> tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
> tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
> tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
> tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
> tip Apply plugin @vuepress/notification (i.e. "@vuepress/plugin-notification") ...
> [下午2:37:29] Compiling Client
> [下午2:37:29] Compiling Server
> [下午2:37:35] Compiled Server in 6s
> [下午2:37:38] Compiled Client in 9s
> (undefined) ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"fc14df32-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&)
> Module not found: Error: Can't resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
> resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
>   using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool)
>     Field 'browser' doesn't contain a valid alias configuration
>     using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js doesn't exist
>       .jsx
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx doesn't exist
>       .vue
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue doesn't exist
>       .json
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json doesn't exist
>       .styl
>         Field 'browser' doesn't contain a valid alias configuration
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl doesn't exist
>       as directory
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl]
>  @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"fc14df32-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&) 1:361-431
>  @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876&
>  @ ./docs/devtool/idea插件.md
>  @ ./.temp/internal/page-components.js
>  @ ./node_modules/@vuepress/core/lib/app/util.js
>  @ ./node_modules/@vuepress/core/lib/app/components/Content.js
>  @ ./node_modules/@vuepress/core/lib/app/app.js
>  @ ./node_modules/@vuepress/core/lib/app/clientEntry.js
>  @ multi ./node_modules/@vuepress/core/lib/app/clientEntry.js
> (undefined) ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"727217d2-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&)
> Module not found: Error: Can't resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
> resolve './idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png' in '/Users/chentx/Desktop/docs/docs/devtool'
>   using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool)
>     using description file: /Users/chentx/Desktop/docs/package.json (relative path: ./docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png)
>       no extension
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
>       .js
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js doesn't exist
>       .jsx
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx doesn't exist
>       .vue
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue doesn't exist
>       .json
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json doesn't exist
>       .styl
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl doesn't exist
>       as directory
>         /Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png doesn't exist
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.js]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.jsx]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.vue]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.json]
> [/Users/chentx/Desktop/docs/docs/devtool/idea%E6%8F%92%E4%BB%B6.assets/image-20190128143347796.png.styl]
>  @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/@vuepress/core/node_modules/.cache/vuepress","cacheIdentifier":"727217d2-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??ref--1-1!./node_modules/@vuepress/markdown-loader??ref--1-2!./docs/devtool/idea插件.md?vue&type=template&id=f2029876&) 1:361-431
>  @ ./docs/devtool/idea插件.md?vue&type=template&id=f2029876&
>  @ ./docs/devtool/idea插件.md
>  @ ./.temp/internal/page-components.js
>  @ ./node_modules/@vuepress/core/lib/app/util.js
>  @ ./node_modules/@vuepress/core/lib/app/components/Content.js
>  @ ./node_modules/@vuepress/core/lib/app/app.js
>  @ ./node_modules/@vuepress/core/lib/app/serverEntry.js
>  @ multi ./node_modules/@vuepress/core/lib/app/serverEntry.js
> Error: Failed to compile with errors.
>     at webpack (/Users/chentx/Desktop/docs/node_modules/@vuepress/core/lib/build.js:103:18)
>     at finalCallback (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:247:12)
>     at runWithDependencies.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:270:6)
>     at done (/Users/chentx/Desktop/docs/node_modules/neo-async/async.js:2928:13)
>     at runCompilers (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:174:48)
>     at err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:181:7)
>     at compiler.run (/Users/chentx/Desktop/docs/node_modules/webpack/lib/MultiCompiler.js:263:7)
>     at finalCallback (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:220:39)
>     at hooks.done.callAsync.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:236:13)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chentx/Desktop/docs/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
>     at AsyncSeriesHook.lazyCompileHook (/Users/chentx/Desktop/docs/node_modules/tapable/lib/Hook.js:154:20)
>     at onCompiled (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:234:21)
>     at hooks.afterCompile.callAsync.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:630:14)
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chentx/Desktop/docs/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (/Users/chentx/Desktop/docs/node_modules/tapable/lib/Hook.js:154:20)
>     at compilation.seal.err (/Users/chentx/Desktop/docs/node_modules/webpack/lib/Compiler.js:627:30)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> chentengxiangdeMacBook-Pro:docs chentx$
> ```
> 
> #### What is expected?
> #### What is actually happening?
> #### Other relevant information
> * Your OS: MACOSX
> * Node.js version: v10.9.0
> * Browser version: chrome latest
> * Is this a global or local install? local
> * Which package manager did you use for the install?yarn




你可以用全中文的路径,在.md前面最好不要有英文符号!,(,),...等等

**Comment by wangrongding** [comment]
可以看到我的这个仓库中, 很多中文路径的文件,仍然可以打包成功

https://github.com/wangrongding/fedtop
