### ISSUE TITLE
bug: `app.js` is 404

### ISSUE THREAD

**Issue by BuptStEve** [vuejs/vuepress#1238]
- [x] I confirm that this is a issue rather than a question.

## Bug report
* `app.js` is 404
![image](https://user-images.githubusercontent.com/11501493/51820682-8d16ab00-2311-11e9-95a6-4cdd13b8ed0b.png)

* because of this
![image](https://user-images.githubusercontent.com/11501493/51820698-9bfd5d80-2311-11e9-9b50-0c508cd4b542.png)

* actually real path is `http://localhost:8080/tua-ui/assets/js/app.js`
![image](https://user-images.githubusercontent.com/11501493/51821088-e92dff00-2312-11e9-8f8d-dcb866227d08.png)

#### Version
1.0.0-alpha.33

#### Steps to reproduce

1. set base to some string, like `base: '/tua-ui/',`
2. run `vuepress dev docs`
3. throw error `app.js is 404`
4. if i set base to `/`, it works fine...

#### What is expected?
no error

**Comment by BuptStEve** [comment]
@ulivz 
if i change this to `.publicPath(publicPath)`, fix 404
https://github.com/vuejs/vuepress/blob/19c21aaa7e3bee2cb0311e5b91885b60f87d7954/packages/%40vuepress/core/lib/webpack/createBaseConfig.js#L42

however, assets in `.vuepress/public` are 404

![image](https://user-images.githubusercontent.com/11501493/51828194-0ae4b180-2326-11e9-9f13-0bd941e561f4.png)

because real paths are

* http://localhost:8080/standard.svg
* http://localhost:8080/logo.png

it's weried, `publicPath` not working...

**Comment by BuptStEve** [comment]
https://github.com/BuptStEve/vuepress-bug

`npm start`

**Comment by coder163** [comment]
期待官方解决
