### ISSUE TITLE
Link to html file in /public folder

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/vuepress#1241]
## Feature request
Hi,
It would be nice to be able to link to .html in /public
I have a email signature generator that i would like to like as an "external link" on my site (target="_blank" and external svg).
This works with alias when using image but not links

#### What problem does this feature solve?
Allow you tu use webpack alias in markdown link

#### What does the proposed API look like?
Same as webpack alias in markdown image

#### How should this be implemented in your opinion?
Same as webpack alias in markdown image

**Comment by mrleblanc101** [comment]
This works:
![An image](~@public/hero.png)
This does not:
[A link](~@public/signature.html)

**Comment by mrleblanc101** [comment]
You mean in ```.vuepress/``` or in ```docs/```.
HTML file in docs are treated like .md file, which mean they will be wrapped in the theme layout component, which i do not want as this is a email signature generator.

**Comment by meteorlxy** [comment]
I got your point. So your workaround that use `<a>` tag could be the only workaround for now, as it won't be converted be the markdown parser of vuepress.

**Comment by ulivz** [comment]
Except using `<a>` tag, you also has another workaround —— Writing a plugin via [clientRootMixin](https://vuepress.vuejs.org/plugin/option-api.html#clientrootmixin) and [define](https://vuepress.vuejs.org/plugin/option-api.html#define).

- plugin's entry:

```js
const path = require('path')

module.exports = {
  define() {
     // Collect HTMLs located at public directory or from plugin options.
     return {
         PUBLIC_HTML_FILES: [ ... ]
     }
  }
  clientRootMixin: path.resolve(__dirname, 'mixin.js')
}
```

- mixin.js:

```js
/* PUBLIC_HTML_FILES */

export default {
  mounted () {
    this.$router.beforeEach((to, from, next) => {
      if (PUBLIC_HTML_FILES.indexOf(to.path) !== -1) {
        location.href = location.origin + this.$router.options.base + to.path
      } else {
        next()
      }
    })
  }
}
```

Welcome to complete this plugin so that other users can benefit from that.

**Comment by mrleblanc101** [comment]
I'll look into this.
But the question is, why would we manage this behavior with a plugin ?
Image behave correctly.
1) I should be able to use webpack alias for link even if it's unusual
2) Every link to a a file outside the doc folder should be treated as a link tag (```<a>```) and not a <router-link>, no ?

**Comment by njzjz** [comment]
But how to use `<a>` in the navigation?
