### ISSUE TITLE
base路径

### ISSUE THREAD

**Issue by coder163** [vuejs/vuepress#1242]
我在设置了base属性值为/blog/之后，请求地址：http://localhost:8080/blog/

出现以下错误

- localhost/:10 GET http://localhost:8080/assets/js/app.js 404 (Not Found)

- touxiang.png:1 GET http://localhost:8080/blog/img/touxiang.png 404 (Not Found)

清除缓存问题依然存在，但是放在其他服务器下居然可以正常访问，我不确定是不是我的问题

目录结构如下：
```shell
|--docs/
   |--blog/
   |--index.md
   |--README.md

```

- 如果有知道的朋友麻烦指点

**Comment by BuptStEve** [comment]
和我的 #1238 重复了...临时解决可以先把 base 改成 `/`

ps 我提了个解决的 pr，https://github.com/vuejs/vuepress/pull/1239

**Comment by ulivz** [comment]
Fixed at #1239.

**Comment by chuxubank** [comment]
使用base路径后运行 `vuepress dev` 打开的页面为空白...部署之后倒是正常的
将base路径去除后正常...
