### ISSUE TITLE
themeConfig.sidebar = auto 。Global configuration invalid

### ISSUE THREAD

**Issue by zq99299** [vuejs/vuepress#1243]
- [x ] I confirm that this is a issue rather than a question.

#### Version 
1.0.0-alpha.32

#### Steps to reproduce

1. https://github.com/zq99299/java-tutorial
2.  yarn install
3.  yarn docs:dev
4.  /nav.html

.vuepress/config.js

```
 themeConfig: {
        sidebar: 'auto',   
```

themeConfig.sidebar = auto 。Global configuration invalid，The sidebar is not automatically generated （nav.md  is not configured in the themeConfig. Sidebar）

It needs to be configured in the specific md head

nav.md
```
---
sidebar: auto
---
```

#### What is expected?

Global configuration options take effect.Or am I misinterpreting this global configuration?

#### Other relevant information

- Your OS: windows 10
- Node.js version: v8.12.0
- Browser version: Google Chrome 版本 69.0.3497.81（正式版本） （64 位）
- Is this a global or local install?  local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Sorry but I still cannot get what is actually happening. 

FYI, Page-level configuration (frontmatter) has the higher priority than site-level's.

**Comment by zq99299** [comment]
@ulivz 

.vuepress/config.js

```
 themeConfig: {
        sidebar: 'auto',   
```
I mean this global configuration is not valid.Only in the specific md file configuration can have effect

```
---
sidebar: auto
---
```

**Comment by ulivz** [comment]
Maybe you should use Google Translate, it's easier to understand. 🙂

**Comment by zq99299** [comment]
The global setting is invalid and can only be set at the top of the .md file to have a sidebar effect. :sob:

**Comment by ulivz** [comment]
> at the top of the .md file

This is [frontmatter](https://vuepress.vuejs.org/guide/frontmatter.html), you can be more professional. 🙂

**Comment by ulivz** [comment]
Cannot you see that you configured 2 'sidebar' ?

![image](https://user-images.githubusercontent.com/23133919/52070545-06d1c180-25bc-11e9-8981-b79f246946d5.png)

![image](https://user-images.githubusercontent.com/23133919/52070550-0d603900-25bc-11e9-8ed1-8bf79f5afde4.png)

---


BTW, Remove `locales` if you don't use i18n:

```
    locales: {
        // 键名是该语言所属的子路径
        // 作为特例，默认语言可以使用 '/' 作为其路径。
        '/': {
            lang: 'zh-CN', // 将会被设置为 <html> 的 lang 属性
        }
    },
```

If you want to use i18n, you should place your config under
