### ISSUE TITLE
vue code scope in markdown file

### ISSUE THREAD

**Issue by LasyIsLazy** [vuejs/vuepress#1244]
## Feature request
Vue code with scope in .md file

#### What problem does this feature solve?

```Markdown
## some text
<template></template>
<script>
// code snippet 1
</script>
## some other text
<script>
// code snippet 2
</script>
```
code snippet 1 will affect code snippet 2.

There are two components here, But they influence each other.

#### What does the proposed API look like?

Maybe:
```Markdown
<scope>
<!-- code ->
</scope>
```

**Comment by ulivz** [comment]
In VuePress, each markdown file will be transpiled into a Vue SFC, and each *.vue file can contain at most one `<script>` block at a time.  You should split these HTMLs into 2 Vue SFC (`.vuepress/components`) first and using it in the markdown.

ref: https://vue-loader.vuejs.org/spec.html#script
