### ISSUE TITLE
Publish date

### ISSUE THREAD

**Issue by kaihendry** [vuejs/vuepress#1245]
## Feature request

https://forum.vuejs.org/t/how-to-override-last-updated-timestamp-on-a-page/54958

#### What problem does this feature solve?

A way to show the original published date of a document. [Most](https://gohugo.io/functions/format/) [other](https://jekyllrb.com/docs/front-matter/) static site generators have this feature. In Jekyll this overrides the Last updated date, though it is probably better to have two fields, like birth time (publish date) and modification (last updated) time.

Rationale: Documentation sources may be updated over time, but still refer to an old outdated topic, hence the need to clearly show the original publication date as well as last modification date.

This is especially needed on documents without time clearly formatted within the URL.

#### What does the proposed API look like?

```
{
    "publishDate": "2016-01-29T12:53:39.174Z"
}
```

#### How should this be implemented in your opinion?

Via the default theme

#### Are you willing to work on this yourself?**

No, though DerZade#6170 on Discord expressed interest.

**Comment by kaihendry** [comment]
Maybe something like:

```
git log --diff-filter=A --pretty=format:%ad --  blog/entry/Webconverger_and_WebKit.md
Sun Dec 9 11:41:51 2018 +0800
```
Would be a better idea for birth time. However in my case I renamed files to fit Vuepress's `.md` suffix and broke birth time. :(

```
[hendry@t480s webconverger-org.old]$ git log --diff-filter=A --pretty=format:%ad --  blog/entry/Webconverger_and_WebKit.mdwn
Tue Jun 24 23:24:39 2008 +0100
[hendry@t480s webconverger-org.old]$ git mv blog/entry/Webconverger_and_WebKit.mdwn blog/entry/Webconverger_and_WebKit.md
[hendry@t480s webconverger-org.old]$ git log --diff-filter=A --pretty=format:%ad --  blog/entry/Webconverger_and_WebKit.md
[hendry@t480s webconverger-org.old]$ git add blog/entry/Webconverger_and_WebKit.md
[hendry@t480s webconverger-org.old]$ git commit -m "mdwn to md"
[master b2228ee] mdwn to md
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename blog/entry/{Webconverger_and_WebKit.mdwn => Webconverger_and_WebKit.md} (100%)
[hendry@t480s webconverger-org.old]$ git log --diff-filter=A --pretty=format:%ad --  blog/entry/Webconverger_and_WebKit.md
Wed Jan 30 20:41:12 2019 +0800
```

**Comment by ulivz** [comment]
I found that it's better to write a plugin for it like [@vuepress/plugin-last-updated](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/plugin-last-updated) —— We hope the core to be as simple as possible and the Plugin API is for extension.

If you found that the Plugin API cannot resolve your problem, feel free to open a FR issue for that.

So please write a plugin to get it.
