### ISSUE TITLE
cache false的逻辑不正确。

### ISSUE THREAD

**Issue by intijk** [vuejs/vuepress#1258]
- [x] I confirm that this is a issue rather than a question.

## Bug report

在这部分的代码，看得出来是想做一个开关，让cache可以设置为true或者false，但是这个功能似乎并没有相应的作用，如果给在命令行给cache一个false，那么实际的效果是产生了一个叫做false的cache folder，这应该不是设计的目的吧。

https://github.com/vuejs/vuepress/blob/055d68013a955d1d531527e1c324cc29aa0d8fca/packages/%40vuepress/core/lib/prepare/CacheLoader.js#L22

#### Version
1.0.0-alpha.36

#### Steps to reproduce

vuepress/packages/docs$  vuepress/node_modules/.bin/vuepress --cache false

#### What is expected?

cache feature should be muted.

#### What is actually happening?

a cache folder called `false` generated

**Comment by ulivz** [comment]
The caching folders are bound to be generated. `yarn xxx -- no-cache `actually means that the cache is cleared before current build.

https://github.com/vuejs/vuepress/blob/8d0cc9eb69f2eddee442c1321ff4e337ba75f0ef/packages/%40vuepress/core/lib/webpack/createBaseConfig.js#L76

At present, this solution is relatively straightforward. Of course, the better solution is not to use cache loader when we met `--no-cache`, but this is too expensive.

---

缓存的目录是一定会生成的。`yarn xxx --no-cache` 实际的含义是在每次构建之前清除缓存。

目前这种方式比较直接。当然，更好的做法应该是在 `--no-cache` 时不应用 cache loader，但是这个成本太大。

---

BTW, next time I suggest you open an issue by English so anybody can answer, you will also benefit from this :)
