### ISSUE TITLE
Need help, custom highlight function for markdown-it

### ISSUE THREAD

**Issue by jeud** [vuejs/vuepress#1261]
Dear all.

I'm using `vuepress` 0.14.8.

I would like to have a custom highlight function for the `markdown-it`, I have tried 2 approaches below, but none of them seem working.

please guide.
Thanks

*.vuepress/config.js*

```js
const hljs = require('highlight.js')

const highlight = (str, lang) => {
    if (lang && hljs.getLanguage(lang)) {
        try {
            return '<foo></foo>'
        } catch (__) { }
    }

    return ''
}


// approach 1
module.exports = {
    chainMarkdown(config) {
        config
            .options
            .highlight(highlight)
    }
}

// approach 2
module.exports = {
    markdown: {
        config: md => {
            md.set({ highlight: highlight })
        }
    }
}
```

**Comment by jeud** [comment]
For `vuepress` 0.14.8., I solved this problem using approach 2, It was my own mistake not to force recompiling the markdown files.

**Comment by ulivz** [comment]
@jeud you're right the chainMarkdown was introduced by 1.x.
