### ISSUE TITLE
Is it possible to manipulate <meta> dynamically ?

### ISSUE THREAD

**Issue by jeud** [vuejs/vuepress#1263]
Dear all.

I'm using `vuepress` 0.14.8.

I would like to manipulate the `<meta>` tag dynamically so I have tried some coding at _.vuepress/enhanceApp.js_ but the result is quite inconsistent when using `vuepress build`, so it's **only SSR** problem.

```js
export default ({ siteData }) => {
    siteData.pages.forEach(page => {
        if (pattern.test(page.path)) {
            if (!page.frontmatter['meta'])
                page.frontmatter['meta'] = []

            // working
            page.frontmatter['meta'].push({ name: 'description', content: `${siteData.description} - ${page.frontmatter['title']}` })

            // not working
            page.frontmatter['meta'].push({ property: 'og:description', content: `${siteData.description} - ${page.frontmatter['title']}` })

            // not working
            if (page.frontmatter['meta']) {
                page.frontmatter['meta'].forEach(each => {
                    if (each['property'] === 'og:image')
                        each['content'] = 'xxx.png'
                })
            }
        }
    })
}
```

Please guide, how can I fix this

> Both of them are working on 'vuepress dev', there are <meta> elements on the browser, but may be it’s because that they were rendered as client JavaScript

**Comment by ulivz** [comment]
> **Only the modification of frontmatter was done at build process will both of the dev and build command respect it.**, the `enhanceApp.js` are client-only enhancement.

Let's start with conclusions, you cannot manipulate `<meta>` dynamically in 0.x. 

But's possible in 1.x.

- In site config(`.vuepress/config.js`)

```js
module.exports = ctx => ({
  // ...
  ready () {
    const { siteData } = ctx
    // changing frontmatter ...
  }
})
```

- In a plugin

```js
module.exports = (options, ctx) => ({
  // ...
  ready () {
    const { siteData } = ctx
    // changing frontmatter ...
  }
})
```

The only difference is that the sequence of passed-in `ctx` is different.
