### ISSUE TITLE
New Install Causing � Between Markdown

### ISSUE THREAD

**Issue by HUGODOS** [vuejs/vuepress#1267]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Launching Vuepress Dev from newly install Vuepress cause <?> embedded between characters on README.md File.

Example: 
echo '# Hello VuePress' > README.md

What is shown on webpage:
��#� �H�e�l�l�o� �V�u�e�P�r�e�s�s�

#### Version

Vuepress: cli.js/1.0.0-alpha.36 win32-x64 node-v9.11.1
Also tried 0.14.8
Yarn: 1.10.1

#### Steps to reproduce
Follow new install steps on website:
## install globally
yarn global add vuepress

## create a markdown file
echo '# Hello VuePress' > README.md

## start writing
vuepress dev

#### What is expected?
No � characters between letters.

#### What is actually happening?
��#� �H�e�l�l�o� �V�u�e�P�r�e�s�s� Being rendered instead of markdown header.

Inside webpack JS script on build looks like this: 

```
(window.webpackJsonp=window.webpackJsonp||[]).push([[3],{168:function(t,e,n){"use strict";n.r(e);var s=n(0),i=Object(s.a)({},function(){this.$createElement;this._self._c;return this._m(0)},[function(){var t=this.$createElement,e=this._self._c||t;return e("div",{staticClass:"content"},[e("p",[this._v("��#� �H�e�l�l�o� �V�u�e�P�r�e�s�s�")])])}],!1,null,null,null);e.default=i.exports}}]);
```
 
Exampel Render Below:
![issue](https://user-images.githubusercontent.com/23139695/52403731-5124d800-2abf-11e9-8ba1-f733afd323a2.png)

#### Other relevant information

- Your OS: Windows 10 x64
- Node.js version: v9.11.1
- Browser version: Firefox Nightly 63.0a1 (2018-09-03) (64-bit) and Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Is this a global or local install? Global
- Which package manager did you use for the install? Yarn

## Issue Resolution
Don't create the markdown file from CMD or PowerShell as it causes this issue, on windows create the file externally using windows explorer or code editor.

**Comment by SimonEast** [comment]
Yes, I'm also getting the same issue on both Vuepress 1.0.0-alpha.36 *and* latest stable 0.14.8. 

My Vuepress is also installed as a global via yarn as instructed in the docs.

**Comment by SimonEast** [comment]
I think it *may* have something to do with the Windows version of `echo` and the type of file it creates. I created a clean file inside Sublime text and it doesn't appear to show these issues, but haven't had time to test fully. Will try again later.

**Comment by HUGODOS** [comment]
Hi @SimonEast you are correct the echo on windows is causing rouge character between the creation of the MD file. I have created it from using VS code create the file and it works as intended might need to update docs to suggest not echo for windows.

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/issues/276#issuecomment-384930661
