### ISSUE TITLE
Clarification on generating dynamic pages

### ISSUE THREAD

**Issue by danquist** [vuejs/vuepress#1270]
First of all, thank you guys for this amazing project, everything about it is beautiful and I can't wait to see it mature.

I am looking for clarification if there is built-in support for handling dynamic page generation, or if this is something that I should implement via a custom plugin.

My use case is that I am trying to generate a documentation site for a python library, where each class gets it's own page generated at build-time from the source docstrings. I could of course create these files separately, but I would really like to avoid have the same documentation duplicated in multiple places.

Is this something that would best be handled as a plugin using one of the life cycle hooks? Has the life cycle API stabilized yet?

I saw #452, but that seemed to be referring to dynamic data files, not pages, so I wasn't sure that discussion applied here.

**Comment by ulivz** [comment]
Thanks for your interest in VuePress! 

For now you can only add dynamic pages via plugin api: [additionalPages](https://vuepress.vuejs.org/plugin/option-api.html#additionalpages), a tip is that all the plugin apis can also be used at site config(`.vuepress/config.js`), so you can test it at your docs first, if you found it can be reused by other people, you can separate it as a standalone plugin.

Oh, another thing, the plugin api was introduced by 1.x, so make sure that you are using the correct version, of course, latest version should be better!

**Comment by danquist** [comment]
Thanks!

**Comment by danquist** [comment]
Can `additionalPages` take a raw Vue component or does it only accept markdown content?

**Comment by shalu0317** [comment]
can i add a dynamic uri inside my additionalPages? I want to accept a value inside my additionalPages and pass it as my url. so that it is different for different users. Pls reply asap
