### ISSUE TITLE
代码块不识别语言名

### ISSUE THREAD

**Issue by wuyudi** [vuejs/vuepress#1274]
- [x] I confirm that this is a issue rather than a question.

#### Version
1.0.0-alpha.31
#### Steps to reproduce
我在markdown里输入
```
```mathematica
TableForm[pts = RandomReal[{-1, 1}, {5, 2}]]
row[{x_, y_}] := {1, x, y, x y, x^2, y^2}
Det@Prepend[row /@ pts, row[{x, y}]]
```
然后yarn install && yarn start

#### What is expected?
出来高亮的代码块
#### What is actually happening?
出现了提示：Language does not exist mathematica
C++也是同理

#### Other relevant information

- Your OS: Windows10
- Node.js version:  v8.12.0
- Browser version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Is this a global or local install? local
- Which package manager did you use for the install? yarn 1.12.3

**Comment by wuyudi** [comment]
```
```mathematica
TableForm[pts = RandomReal[{-1, 1}, {5, 2}]]
row[{x_, y_}] := {1, x, y, x y, x^2, y^2}
Det@Prepend[row /@ pts, row[{x, y}]]
```
```
代码长这样

**Comment by CrazyPandas** [comment]
因为并不支持mathematica语言，详见
[@vuepress/markdown/lib/highlight.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown/lib/highlight.js)
在这个文件里可以看到支持的语言有：

- vue
- html
- md（即markdown）
- ts（即typescript）
- py 
- sh
- yml

**Comment by ulivz** [comment]
All supported languages are here: https://prismjs.com/

**Comment by CrazyPandas** [comment]
> 
> 
> Here are all supported languages: https://prismjs.com/
> Full List
> 
> And here is related issue: [PrismJS/prism#1647](https://github.com/PrismJS/prism/issues/1647)
> 
> BTW, next time I suggest you open an issue by English so anybody can answer, you will also benefit from this :)

Thanks for your answer, I make a mistake.

**Comment by NineSwordsMonster** [comment]
Language does not exist c++

**Comment by ulivz** [comment]
@NineSwordsMonster You should use cpp instead of `c++`.
