### ISSUE TITLE
'@vuepress/plugin-medium-zoom' this plugin fails when routing updates

### ISSUE THREAD

**Issue by Ice-Hazymoon** [vuejs/vuepress#1276]
- [x] I confirm that this is a issue rather than a question.

## Bug report

'@vuepress/plugin-medium-zoom' works fine the first time the page is loaded, but no longer works after routing updates

![_ _20190211183647](https://user-images.githubusercontent.com/25239977/52558245-c03a5d80-2e2c-11e9-9b3d-7281b0d7dda9.gif)

#### Version

**vuepress**: 1.0.0-alpha.37
**@vuepress/plugin-medium-zoom**: 1.0.0-alpha.0

#### Steps to reproduce

After the route is updated

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v11.9.0
- Browser version: 70.0.3538.77
- Is this a global or local install? 
  Global installation
- Which package manager did you use for the install?
  Use yarn as the package manager

**Comment by ulivz** [comment]
Thanks has been fixed at https://github.com/vuejs/vuepress/pull/994, please use latest version of `@vuepress/plugin-medium-zoom`
