### ISSUE TITLE
Suggestion/Annoyance: Remove the `.` to the vuepress folder: `.vuepress`

### ISSUE THREAD

**Issue by staghouse** [vuejs/vuepress#1280]
## Feature request

On an OS level when saving files in to a vuepress project, the OS finder window (OSX for example) will not show you `.vuepress` - this is kind of annoying for adding assets and perhaps has other indexing implications for custom deployments.

#### What problem does this feature solve?

OS visibility to the project. Some OS's dont let you move, copy, etc files/dirs that start with `.`

#### What does the proposed API look like?

`.vuepress` -> `vuepress`
or
`.vuepress` -> `_vuepress`

#### How should this be implemented in your opinion?

Seems simple enough, though it is a breaking change that should have large lead time of awareness

#### Are you willing to work on this yourself?**

WIlling to if community believes its a valid problem

**Comment by ulivz** [comment]
Sorry but we don't plan to change it since it's a too big breaking change.
