### ISSUE TITLE
webpack  config  don't work, my vuetify-loader don't work,

### ISSUE THREAD

**Issue by zhhlwd** [vuejs/vuepress#1285]
```
"vuepress": "^1.0.0-alpha.37",
```

- [x] I confirm that this is a issue rather than a question.

#### What is expected?
I'm writing a theme,
 vuetify-loader will automatically import all the vuetify components you use.
https://vuetifyjs.com/zh-Hans/framework/a-la-carte#vuetify-loader
my config.js:
```
..... more
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')
chainWebpack: config => {
    config.plugin('vuetify').use(VuetifyLoaderPlugin);
  },
.....more
```
my enhanceApp.js
```
import Vuetify from 'vuetify/lib';
import 'vuetify/src/stylus/app.styl';

export default ({ Vue }) => {
  Vue.use(Vuetify);
};
```
#### What is actually happening?
don't work
![2019-02-13_025916](https://user-images.githubusercontent.com/35592403/52662471-40e97e80-2f3f-11e9-99ea-687041a35b17.png)

#### Other relevant information

- Your OS:  window 10
- Node.js version:  v10.13.0
- Browser version: chrome  70.0.3538.102
- Is this a global or local install? local 
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Thanks for your interest in VuePress.

But to report an issue that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. vuepress-issue-example), otherwise I don't know where you are going wrong.
