### ISSUE TITLE
Allow anchor linking in sidebar grouping children

### ISSUE THREAD

**Issue by staghouse** [vuejs/vuepress#1289]
#### What problem does this feature solve?

Vue generated anchor links do not show up in Sidebar for a markdown file. 

#### Use case:

In `example/README.md` I have a Vue component that renders out multiple tables and each table has a `h3` anchor heading to match VuePress' anchoring

#### What does the proposed API look like?

```js
sidebar: [
  '/',
  {
    title: 'Example',
    path: '/example/',
    collapsable: false,
    children: [
      '/example/#1',
      '/example/#2',
      '/example/#3',
    ]
  }
]
```

When doing the above, the sidebar will return an array of the proper count but render only the base route and its meta data, in this case, the children would all be the base Example route with no hash anchoring

**Comment by ulivz** [comment]
You can write like this:

```js
sidebar: [
  '/',
  {
    title: 'Example',
    path: '/example/',
    collapsable: false,
    children: []
  }
]
```

When a sidebar group doesn't

**Comment by staghouse** [comment]
This doesn't work. Not when Vue is rendering out anchors instead of the markdown.
