### ISSUE TITLE
document issue '@vuepress/last-updated'  

### ISSUE THREAD

**Issue by zhhlwd** [vuejs/vuepress#1291]
'@vuepress/last-updated' relies on git history, but the document doesn't mention this at all.
At first, I did not initialize git and commit, so the lastUpdated was not displayed. Finally, I had to look at the source code to solve the problem.
It wasted a lot of my time to debug, consumed a lot of my enthusiasm and goodwill,
Your documentation should clearly indicate that you are relying on git and that you must commit to detect new changes

**Comment by ulivz** [comment]
Thanks for the report, actually this restriction has been documented at [here](http://localhost:8080/theme/default-theme-config.html#last-updated), I just added some references to come here.
