### ISSUE TITLE
Choose build location at runtime

### ISSUE THREAD

**Issue by mortocks** [vuejs/vuepress#1292]
## Feature request

Add the output location to the build command `vuepress build docs MY_BUILD_FOLDER`

#### What problem does this feature solve?

When deploying versioned versions of the site for team documentation, we want to include all previous releases in subfolders or subdomains of the site in our deployment pipeline e.g.

- **dist** contains master branch build of the docs e.g version 2.0.0 of the docs
  - **generate_page_folder_1** site content
  - **generate_page_folder_2** site content
  - **1.5.0** contains the `release/1.5.0` version of the docs
    - **generate_page_folder_1** site content
    - **generate_page_folder_2** site content
  - **1.0.0** contains the `release/1.0.0` version of the docs
    - **generate_page_folder_1** site content
    - **generate_page_folder_2** site content

This would give the final urls of 

`https://mysite.com`
`https://mysite.com/generated_page_folder`
`https://mysite.com/...`
`https://mysite.com/1.0.0/generated_page_folder`
`https://mysite.com/1.0.0/...`
`https://mysite.com/1.5.0/generated_page_folder`
`https://mysite.com/1.5.0/...`

NOTE: folder structure doesn't necessarily need to be nested like this, having the different build folders at the same level and using server config to point to the correct directory is also fine. 

#### What does the proposed API look like?

`vuepress build docs MY_BUILD_FOLDER`. In the folder examples above this would be  `vuepress build docs; vuepress build docs dist/1.0.0`

#### How should this be implemented in your opinion?

keep the current config.json option as the default but if the build command has a directory provided then use that instead during build. 

#### Are you willing to work on this yourself?**

I am but don't know if I have the skills :-)

**Comment by ulivz** [comment]
You can get by using a custom ENV:

```
// .vuepress/config.js
module.exports = {
  dest: process.env.VUEPRESS_DEST
}
```

Then execute:

```bash
VUEPRESS_DEST=... vuepress build dev
```
