### ISSUE TITLE
Line numbers are misaligned in code blocks

### ISSUE THREAD

**Issue by glecetre** [vuejs/vuepress#1294]
- [x] I confirm that this is a issue rather than a question.

#### Version
```
> vuepress -V
0.14.8
```

#### Steps to reproduce
Just add a code block in any page, using the default template. You can use this markdown:

```
(escape)```ts{3,6-8}
import { STATE } from "@hpi_utils/state_machine"

import INITIAL_DISPLAY from "../display/initial_display"

export default class INITIAL_STATE extends STATE {
  prepare() {
    // Ignore the constructor parameter for now
    this.view_model = new INITIAL_DISPLAY({})
  }
}
(escape)```
```

#### What is expected?
Line numbers in code blocks should correctly be aligned to the lines they represent.

#### What is actually happening?
In code blocks, line numbers are misaligned:

![image](https://user-images.githubusercontent.com/43233602/52781718-8f853e80-304d-11e9-974b-455b4719af2b.png)

#### Other relevant information

- Your OS: Linux Mint Tara
- Node.js version: 10.15.1
- Browser version: Vivaldi 2.3.1440.41 (Stable channel) (64-bit)
- Is this a global or local install? Global
- Which package manager did you use for the install? Yarn

**Comment by Shigma** [comment]
Can you provide a reproduction repo?

**Comment by ulivz** [comment]
Obviously it's caused by your custom styles, so how to address this issue is up to you .

**Comment by ShailenNaidoo** [comment]
> Obviously it's caused by your custom styles, so how to address this issue is your business.

I have the exact some issue as @glecetre and I am not using any custom styles, here is a repo that is live https://github.com/Lumkani/vue-architecture-patterns and has the above mentioned issues

**Comment by JulioJu** [comment]
If you use default-theme, change padding at https://github.com/vuejs/vuepress/blob/3e1f5d844b16a3f829465a35e734a5f556c3dd22/packages/%40vuepress/theme-default/styles/code.styl#L79 

by 
```
      padding 1rem 0
```

**Comment by alexfornuto** [comment]
This is a real issue that should be re-opened. I am also encountering it with the default theme.

@ulivz this is not a user-created error.
