### ISSUE TITLE
Error in local theme index.js should not be ignored and reported as "cannot resolve plugin ..."

### ISSUE THREAD

**Issue by Shigma** [vuejs/vuepress#1296]
- [x] I confirm that this is a issue rather than a question.

#### Version

1.0.0-alpha.36 

#### Steps to reproduce

```
.vuepress
├─ config.js
├─ theme
   ├─ index.js
   ├─ and other files ...
```

Assuming that an error was encounted in `index.js`, vuepress will leave a message `cannot resolve plugin .../.vuepress/theme`. But this behavior is rather strange and may mislead user with an indication that the theme is **not found**. Also, I think errors in local theme index file should not be simply ignored.

#### What is expected?

- stop the process like an error was encounted in the `config.js`, or
- provide a better warning like `an error was encounted in ......`

#### What is actually happening?

`cannot resolve plugin .../.vuepress/theme`

#### Other relevant information

- Your OS: N/A
- Node.js version: N/A
- Browser version: N/A
- Is this a global or local install? N/A
- Which package manager did you use for the install? N/A

**Comment by ulivz** [comment]
The theme's configuration file [themeEntryFile](https://vuepress.vuejs.org/miscellaneous/glossary.html#themeentryfile) also supports all the plugin api so it'll be applied like a plugin, so this unfriendly log should also occur in the normal plugin.

We truly need to enhance the log, contribution welcome! and I trust your sense!
