### ISSUE TITLE
import code snippet fail（BUG #1151 The situation still exists）

### ISSUE THREAD

**Issue by jiaming743** [vuejs/vuepress#1297]
- [x] I confirm that this is a issue rather than a question.

## Bug report

**BUG #1151** 

According to @Shigma 's advice 

I removed ":"  

**myVuePressProject/node_modules/vuepress/lib/markdown/snippet.js#27**

### Before

`const filename = rawPath.split(/[{:\s]/).shift()`

### After

`const filename = rawPath.split(/[{\s]/).shift()`

**It still shows `Not found:  E`**

## What's more

I tried **console.log(content)** and the contents of the file can be read normally.

**myVuePressProject/node_modules/vuepress/lib/markdown/snippet.js#28**

`const content = fs.existsSync(filename) ? fs.readFileSync(filename).toString() : 'Not found: ' + filename`

#### Version

VuePress@0.14.8

#### What is expected?

show codes what I imported

#### What is actually happening?

show me `Not found: E`

#### Other relevant information

- Your OS:  Windows 10
- Node.js version: 10.13.0
- Browser version:   Chrome 70.0.3538.102
- Is this a global or local install? * (vuepress@0.14.8) and local (vuepress@0.14.8)
- Which package manager did you use for the install? yarn

**Comment by Shigma** [comment]
Really wield. After first running, any change to the file you mentioned will be of no effect, even if you replace line.28 with something like `const content = 'Hello World'`. But if you change the file before first usage, the code snippet will run as expected.

**I think it's a problem with cache system.**

If it is, don't be worried. Just wait for an update on `v0.x` branch and everything will be ok.

**Comment by Shigma** [comment]
@ulivz Do I also need to send a PR to `v0.x` branch, something like #1236 ?

**Comment by ulivz** [comment]
@Shigma Contribution welcome!

**Comment by Shigma** [comment]
@ulivz A release of 0.x may solve this issue, any plans?

**Comment by ulivz** [comment]
Released [0.14.9](https://github.com/vuejs/vuepress/blob/0.x/CHANGELOG.md#0149-2019-02-17), @jiaming743 could you try the latest version?

**Comment by jiaming743** [comment]
👍The problem has been solved. @ulivz @Shigma 

But I found an interesting situation: import test.js in test.md, then change the contents of test.js and press 'ctrl+s', the page has not changed after compile automatically. Then I switch to test.md and press 'ctrl+s', the page changed after compile automatically again.

**It seems that:** changes to the imported file will not trigger the recompilation of the code snippet, you need to re-save the 'test.md' to trigger the code snippet compilation.

### Steps to reproduce

**test.js**

```js
export default {
    // this is a test file.
}
```

**test.md**

```html
<<< @/dirpath/test.js
```

**current code snippet**

```js
export default {
    // this is a test file.
}
```

### setp1

**change test.js**

```js
export default {
    // test test test...
}
```

press 'ctrl+s' in test.js

compile automatically...

**current code snippet**

```js
export default {
    // this is a test file.
}
```

No change

### setp2

**switch to test.md(No edits)**

press 'ctrl+s' in test.md

compile automatically...(Slower.It seems that all the files have been recompiled.)

**current code snippet**

```js
export default {
    // test test test...
}
```

changed

**Comment by Shigma** [comment]
It's because imported codes are not treated as dependencies at present, so changes to those files will not trigger hmr......

It's a long story. You can open a new issue about that.
