### ISSUE TITLE
[Proposal] Enhance app hooks

### ISSUE THREAD

**Issue by Shigma** [vuejs/vuepress#1299]
#### What problem does this feature solve?

The execution of the enhance app files is before the initialization of vuepress client, so it is hard to get access to the vuepress api, such as router instance.

> An bad walkaround by my own
```js
let created = false
Vue.mixin({
  beforeMount() {
    if (created) return
    created = true
    myEnhanceClient(this.$vuepress, this.$router)
  },
})
```

#### What does the proposed API look like?

There are two ways:
1. Import the enhance app files after initialization of client. *(Which may leave some breaking changes.)*
2. Add a new option api, like `enhanceClientFiles`, whose files will export a function like this:
```js
// config.js
module.exports = {
  // some config
  enhanceClientFiles: ['path/to/myEnhanceClient.js']
}
```

```js
// myEnhanceClient.js
export default function myEnhanceClient(vuepress, router) {
  // some code
}
```

#### How should this be implemented in your opinion?

Add a new hook which will be called after client is initialized.

#### Are you willing to work on this yourself?**

Yes.

**Comment by ulivz** [comment]
Could [clientRootMixin](https://vuepress.vuejs.org/plugin/option-api.html#clientrootmixin) solve your requirement?

**Comment by Shigma** [comment]
> Could [clientRootMixin](https://vuepress.vuejs.org/plugin/option-api.html#clientrootmixin) solve your requirement?

Partially, but still I can't get access to `$router` during initializing easily.

**Comment by Shigma** [comment]
Sorry I didn't know enhancer can export a default function which has router as a parameter. The problem can be solved.
