### ISSUE TITLE
how to document complex tables

### ISSUE THREAD

**Issue by BenRoe** [vuejs/vuepress#1300]
I have to create a complex table. To maintain that with markdown is not very convenient.
I thought a json file would be better and use this [Vuetable-2](https://www.vuetable.com).
I am a vuepress noob and have no idea how to implement vuetable in vuepress.

Can someone help me to implement vuetable, or suggest an other idea?

**Comment by ulivz** [comment]
This is the scope of markdown syntax itself, or you can create a vuetable plugin by yourself.

**Comment by BenRoe** [comment]
Got it to work. Maybe this helps some other noobs. 

Install Vuetable with `npm install -D vuetable-2@next` or `yarn add -D vuetable-2@next`

Create a file `.vuepress/components/Vuetable.vue` in your root project folder.

```js
<template>
  <vuetable ref="vuetable"
    api-url="http://openlibrary.org/people/george08/lists.json"
    :fields="['name', {name: 'last_update', title: 'Last Update'}, 'edition_count']"
    data-path="entries"
    pagination-path=""
  ></vuetable>
</template>

<script>
import Vuetable from 'vuetable-2'

export default {
  components: {
    Vuetable
  }
}
</script>
```

Add `<Vuetable/>` to your .md file where the table should be displayed.

**Comment by shriaviator** [comment]
@ Ben vuetable-2 works in dev but does not work in deployment . Any suggestions ?
