### ISSUE TITLE
Publish source code for vuepress-html-webpack-plugin or unfork it

### ISSUE THREAD

**Issue by benmccann** [vuejs/vuepress#1303]
- [X] I confirm that this is a issue rather than a question.

## Bug report

vuepress uses a fork https://github.com/vuejs/vuepress/commit/4816bef of html-webpack-plugin. This package was published to npm, but the source code never made available. This means I can't understand what the issue was that was being worked around that made the fork required

#### Version

`master`

#### Steps to reproduce

1. Look for source code of `vuepress-html-webpack-plugin`
2. Fail to find it anywhere on the internet

#### What is expected?

It should be a repo under https://github.com/vuejs with a clear explanation as to why the package had to be forked and what was changed

Or even better, the dependency on this closed source package should be removed and the project should switch back to the upstream html-webpack-plugin unforking the code

#### What is actually happening?

The package was published to npm, but the source code was never made available

#### Other relevant information

- Your OS: any
- Node.js version: any
- Browser version: any
- Is this a global or local install? either
- Which package manager did you use for the install? any

**Comment by olizilla** [comment]
I suspect these are the sources you are looking for https://github.com/yyx990803/html-webpack-plugin

**Comment by benmccann** [comment]
Thanks for the answer
