### ISSUE TITLE
Cannot read property 'globalLayout' of null

### ISSUE THREAD

**Issue by epitole** [vuejs/vuepress#1304]
- [x] I confirm that this is a issue rather than a question.

## Bug report
Cannot read property 'globalLayout' of null

#### Version
vuepress 1.0.0-alpha.38

#### Steps to reproduce
1. Create new project
2. Run vuepress dev (or build)

#### What is expected?
Development server start

#### What is actually happening?
```
TypeError: Cannot read property 'globalLayout' of null
    at AppContext.getThemeConfigValue (/Users/tom/Desktop/test/node_modules/@vuepress/core/lib/prepare/AppContext.js:377:65)
    at AppContext.resolveCommonAgreementFilePath (/Users/tom/Desktop/test/node_modules/@vuepress/core/lib/prepare/AppContext.js:301:35)
    at AppContext.resolveGlobalLayout (/Users/tom/Desktop/test/node_modules/@vuepress/core/lib/prepare/AppContext.js:271:30)
    at AppContext.process (/Users/tom/Desktop/test/node_modules/@vuepress/core/lib/prepare/AppContext.js:99:10)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

#### Other relevant information

- Your OS: Mac OSX
- Node.js version: v11.7.0
- Browser version: any
- Is this a global or local install? any
- Which package manager did you use for the install? any

**Comment by TribeWeb** [comment]
Exact same issue both with existing and fresh 1.x projects

**Comment by manastalukdar** [comment]
Verified that this issue happens all the way back till alpha.32.

**Comment by BuptStEve** [comment]
Because of this commit: https://github.com/vuejs/vuepress/commit/c91f55a

**Comment by BuptStEve** [comment]
There are two errors:

https://github.com/vuejs/vuepress/blob/c91f55a2b2b930107574b4d5ae0bef84a624f9c7/packages/%40vuepress/core/lib/prepare/AppContext.js#L377

https://github.com/vuejs/vuepress/blob/c91f55a2b2b930107574b4d5ae0bef84a624f9c7/packages/%40vuepress/core/lib/prepare/AppContext.js#L385

A quick fix for me:

```js
 // ...

  getThemeConfigValue (key) {
    return this.themeEntryFile[key] || 
      (this.parentThemeEntryFile && this.parentThemeEntryFile[[key]) // <-- replace by this
  }

  getThemeAgreementFile (filepath) {
    const current = path.resolve(this.themePath, filepath)
    if (fs.existsSync(current)) {
      return current
    }
    if (!this.parentThemePath) return // <-- add this
    const parent = path.resolve(this.parentThemePath, filepath)
    if (fs.existsSync(parent)) {
      return parent
    }
  }

 // ...
```

**Comment by ulivz** [comment]
Thanks for the report, it would be better to create a repro repo (e.g. [vuepress-global-layout-repro](https://github.com/ulivz/vuepress-global-layout-repro)) at your next time to report issue.
