### ISSUE TITLE
Header Anchors trigger watchers?

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#1306]
- [x] I confirm that this is a issue rather than a question. (Ummmm.. Not so sure about that)

#### Version

1.0.0-alpha.39

#### Steps to reproduce

```md
<!-- Readme.md -->

## Anchor1

## Anchor2

## Anchor3

<script>
export default {
  computed: {
    someConfig () {
      return {
        lang: this.$lang
      }
    },
  },

  watch: {
    'someConfig': (val) => {
      console.log('someConfig:', val)
    },
  }
}
</script>
```

Click the different anchors, and check the console.

#### What is expected?

No watcher function is triggered.

#### What is actually happening?

The `someConfig` watcher is triggered

#### Other relevant information

- Your OS: Windows 10 x64
- Node.js version: v10.13.0
- Browser version: Chrome v70.0.3538.67 x64
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

I'm trying to config some third-party component with the `$lang` computed of Vuepress. The component will re-init if the config is changed (by watching the config).

However, when clicking the anchors in Vuepress, the component always re-inited. I found that clicking anchors will trigger the watcher as shown above.

It seems so strange and I'm not sure if this is a bug. Could anyone help to give some hints?

[__Reproduce Repo__](https://github.com/meteorlxy/vuepress-1306)

**Comment by Shigma** [comment]
Nothing wield to me. @meteorlxy 

`$lang` and `someConfig.lang` are primitives, so updates in dom will take no effect.

However `someConfig` is an object created by computed API, and obviously `{ lang: "en-US" } !== { lang: "en-US" }`, so the watcher will be triggered.

**Comment by meteorlxy** [comment]
Ummm what confused me it that, why "clicking the anchor" will trigger the computed API?

**Comment by Shigma** [comment]
The answer is a little complicated. As is well known, Vue will observe every computed attributes by their dependencies. Let we see what is behind the computation of `someConfig`:

- `someConfig` depends on `$lang`
- `$lang` depends on `$page.frontmatter.lang`
- `$page` depends on `$route.path`
- and finally `$route` will change by click anchor

**Comment by meteorlxy** [comment]
> * and finally `$route` will be changed by clicking anchor

I didn't realize that. Thanks a lot! 😄
