### ISSUE TITLE
Not rerender when code snippet file changes

### ISSUE THREAD

**Issue by Shigma** [vuejs/vuepress#1309]
- [x] I confirm that this is a issue rather than a question.

#### Version

1.0.0-alpha.39

#### Steps to reproduce

The issue is found by @jiaming743 in #1297. Thanks!

Suppose we have two files, *foo.js* and *foo.md*.

**foo.js**

```js
export default {
    // this is a test file
}
```

**foo.md**

```md
<<< @/foo.js
```

#### What is expected?

When updating *foo.js*, *foo.html* will automatically rerender.

#### What is actually happening?

After updating *foo.js*, *foo.html* does not changes.

#### Other relevant information

- Your OS: Windows
- Node.js version: v10.12.0
- Browser version: N/A
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

**Comment by Shigma** [comment]
The problem is we use cache in markdown-loader:

https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown-loader/index.js#L36

In that case, changes in code snippets will not be able to be detected even if we add them as dependencies.

**Comment by Shigma** [comment]
@ulivz What do you mean by:

https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown-loader/index.js#L30-L32

Can we only cache the markdown tokens and do the rendering repetitively?

**Comment by BuptStEve** [comment]
I hava a plan.

* markdown-loader `index.js`
```js
  // const cached = cache.get(key)
  // if (cached && (isProd || /\?vue/.test(this.resourceQuery))) {
  //   return cached
  // }

  ,,,

  // the render method has been augmented to allow plugins to
  // register data during render
  const {
    html,
    data: { hoistedTags, links, deps },
    dataBlockString
  } = markdown.render(content, {
    frontmatter: frontmatter.data,
    relPath: path.relative(sourceDir, file)
  })

  deps.forEach(this.addDependency) // <-- add deps for webpack
```

* markdown `lib/snippet.js`
```js
    md.$data = md.$data || {}
    md.$data.deps = md.$data.deps || []
    md.$data.deps.push(filename) // <-- add dep
```

* markdown `index.js`
```js
module.exports.dataReturnable = function dataReturnable (md) {
  // override render to allow custom plugins return data
  const render = md.render
  md.render = (...args) => {
    md.$data = md.$data || {} // <-- markdown-it plugins can pass deps via md.$data
    
    ...
  }
}
```

![deps](https://user-images.githubusercontent.com/11501493/52966970-9dd3b180-33e3-11e9-9f28-6f2009bbe013.gif)

@ulivz what do you think?

**Comment by Shigma** [comment]
@BuptStEve 
Working out a simple solution is not difficult, but actually we should make sure to take advantage of lru cache as far as possible.

**Comment by BuptStEve** [comment]
> @BuptStEve
> Working out a simple solution is not difficult, but actually we should make sure to take advantage of lru cache as far as possible. Your solution will increase the rendering time.

Yeah, it's just a simple and naive solution. Any better ideas?

**Comment by Shigma** [comment]
My idea is to separate [`md.render`](https://github.com/markdown-it/markdown-it/blob/master/lib/index.js#L540) into two parts: `md.parse` and `md.renderer.render`.

Every part will has cache with it, which will not only solve the problem but improve performance for general situations as well. I will open a pr later to clarify some technical details.
