### ISSUE TITLE
ServiceWorker doesn't work

### ISSUE THREAD

**Issue by mysticatea** [vuejs/vuepress#1311]
- [X] I confirm that this is a issue rather than a question.

#### Version

- vuepress 1.0.0-alpha.39
- @vuepress/plugin-pwa 1.0.0-alpha.39

#### Steps to reproduce

1. Open https://mysticatea.github.io/eslint-plugin-eslint-comments/
2. Open devtools
3. Go `Application` tab > `Service Workers`.
4. You can find a worker is in invalid URL.

![image](https://user-images.githubusercontent.com/1937871/52954706-2fd0bf80-33ce-11e9-94dc-495f2c26c62b.png)

- **Site:** https://mysticatea.github.io/eslint-plugin-eslint-comments/
- **Config:** https://github.com/mysticatea/eslint-plugin-eslint-comments/blob/master/docs/.vuepress/config.js
- **Repository:** https://github.com/mysticatea/eslint-plugin-eslint-comments
    - `npm run docs:build` is the command to build with vuepress.
- **Build job:** https://travis-ci.org/mysticatea/eslint-plugin-eslint-comments/jobs/494890548

#### What is expected?

- The service worker caches files.

#### What is actually happening?

- The service worker doesn't cache files.

#### Other relevant information

- Your OS: Travis CI's Linux container (Ubuntu 14.04.5 LTS)
- Node.js version: 10.15.1
- Browser version: Chrome 73.0.3683.27（Official Build）beta
- Is this a global or local install? : local
- Which package manager did you use for the install? : yarn

**Comment by ulivz** [comment]
Thanks for the report again, I just created a MR to [register-service-worker](https://github.com/yyx990803/register-service-worker/pull/26) to solve the issue from the root.
