### ISSUE TITLE
can vuepress not delete .git

### ISSUE THREAD

**Issue by zhhlwd** [vuejs/vuepress#1314]
Every time build vuepress deletes the.git folder in the dist directory and then I need to init it again so that my commit log only has one, can vuepress not delete it? I want my commit log to show what's been updated each time

**Comment by LinusBorg** [comment]
why do you have a git repository in your dist folder instead of your project root folder?

**Comment by zhhlwd** [comment]
> 为什么你的dist文件夹中有一个git存储库而不是你的项目根文件夹？

That will push my other files to github, such as config.js.md;
I just need HTML,js, CSS files to open github page
The documentation is also being init with git in the dist directory

https://vuepress.vuejs.org/zh/guide/deploy.html#github-pages

**Comment by ulivz** [comment]
Please read docs carefully, the question doesn't exist since the `git init` are only executed under `docs/.vuepress/dist` instead of your project root. so it will NEVER push your other files to github.
