### ISSUE TITLE
Bewildering 404

### ISSUE THREAD

**Issue by kaihendry** [vuejs/vuepress#1317]
- [X ] I confirm that this is a issue rather than a question.

## Bug report

yes, though I asked a question with [video](https://s.natalian.org/2019-02-19/vuepress.mp4) on discord already too 

#### Version

^1.0.0-alpha.39

#### Steps to reproduce

```
git clone -b vuepress git@github.com:Webconverger/wiki.git
npm run dev
open http://localhost:8080/blog/2014/webconverger_24_release
```

#### What is expected?

https://beta.webconverger.org/iso redirects to https://beta.webconverger.org/iso.html and renders
https://beta.webconverger.org/blog/2014/webconverger_24_release should render by the same logic

#### What is actually happening?

https://beta.webconverger.org/blog/2014/webconverger_24_release is a 404 after seemingly rendering

#### Other relevant information

https://beta.webconverger.org is on netlify

**Comment by ulivz** [comment]
That's a long story to talk about it, well, for the unroot markdown you shouldn't omit the `.html` for now.

> https://beta.webconverger.org/blog/2014/webconverger_24_release.html

**Comment by kaihendry** [comment]
Since the ikiwiki system I'm migrating from had URLs like: https://webconverger.org/blog/2014/Webconverger_24_release/ (by default) I guess I need to add frontmatter to all my .md files, to keep my permalinks (aka URLs) consistent?

Tbh I don't like the superfluous .html default.

**Comment by Shigma** [comment]
@kaihendry 

You may try *Webconverger_24_release/index.md*.

**Comment by Shigma** [comment]
> That's a long story to talk about it, well, for the non-index markdown you shouldn't omit the `.html`

Do you actually care about the links with relative path? Well after #1298 we do not need to worry about these. Perhaps we can add a new option and redirect all the `foo.html` to `foo/` if there is no ambiguity.

**Comment by kaihendry** [comment]
I don't think I use relative links in my markdown. I always link `[awesome content](/content/awesome)` in an absolute way (I think, need a linter).

I am NOT especially fond of the _Webconverger_24_release/index.md_ suggestion. I think the index.md creates at least to me, clutter. Furthermore now info that should be in the filename imo, is in the folder name. Perhaps I am missing some advantage? I don't keep any images (or other static content) alongside posts anymore, but if I did, I guess that is one advantage perhaps?

**Comment by Shigma** [comment]
https://github.com/vuejs/vuepress/blob/d206d448c9c19e5e707aad447073066e6e948fbe/packages/%40vuepress/core/lib/app/redirect.js#L1-L21

It seems that vuepress is able to hangle the redirect...... I don't know why it isn't. @ulivz Can you provide some explanation?

**Comment by Shigma** [comment]
@kaihendry 
- redirecting based on lower case in #1333 (which will fix 404)
- urls without `.html` suffix in #1060 (which will satisfy your need)

**Comment by kaihendry** [comment]
So I need not rename [files](https://github.com/Webconverger/wiki/tree/vuepress) IIUC? Just update?

Thank you,

**Comment by Shigma** [comment]
@kaihendry 

The PR has been merged but a version has not been released yet. You need to wait for vuepress v1.0.0-alpha.40. No need to rename any files. 😄

**Comment by Shigma** [comment]
@kaihendry 

Now you can use [plugin-clean-urls](https://v1.vuepress.vuejs.org/plugin/official/plugin-clean-urls.html) if you want your urls to be

`https://webconverger.org/blog/2014/Webconverger_24_release/`

or even

`https://webconverger.org/blog/2014/Webconverger_24_release`!

**Comment by kaihendry** [comment]
I think I like trailing slash since that's the default on most systems iirc.

**Comment by kaihendry** [comment]
Just deployed 40 on https://beta.webconverger.org/blog/2014/webconverger_24_release.html and now it's working. However the [Edit this page](https://github.com/webconverger/wiki/edit/master/blog/2014/Webconverger_24_release.md) link is not pointing to the branch "vuepress" that it originated from. New bug or am I missing something?

**Comment by Shigma** [comment]
@kaihendry That is because you use markdown with extension `.mkdn` instead of `.md`.

I think you can change your extensions or open a feature request of supporting more extensions.

**Comment by kaihendry** [comment]
I've already renamed them in the vuepress branch https://github.com/webconverger/wiki/edit/vuepress/blog/2014/Webconverger_24_release.md

The problem is, it's Edit page is pointing to wrong branch.

**Comment by Shigma** [comment]
> The problem is, it's Edit page is pointing to wrong branch.

We have a `config.docsBranch` option: https://v1.vuepress.vuejs.org/theme/default-theme-config.html#git-repo-and-edit-links.

**Comment by kaihendry** [comment]
Thanks @Shigma that works.. but not on pages like: https://beta.webconverger.org/maintenance/

Not where this **README.md** source comes from.

https://s.natalian.org/2019-02-28/READMEmd.mp4
