### ISSUE TITLE
Category page not found

### ISSUE THREAD

**Issue by destinytaoer** [vuejs/vuepress#1318]
- [ x] I confirm that this is a issue rather than a question.

## Bug report

I can't find category-pages in siteData pages property when i use string type category like: 
```
category: aaa
```
![default](https://user-images.githubusercontent.com/27852774/53031776-75fa5180-34a8-11e9-9680-fcfa621cb9f8.PNG)

But, it exists when i use Array type categories like:

```
categories:
- aaa
```
![2](https://user-images.githubusercontent.com/27852774/53031878-acd06780-34a8-11e9-81a5-a0c4e43dda13.PNG)

Why?

#### Version
vuepress: 1.0.0-alpha.37
@vuepress/plugin-blog: 1.0.0-alpha.0

#### What is expected?

i watch the source,it can work both.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by destinytaoer** [comment]
when i use the permalink in @vuepress/plugin-blog, it doesn't work too. it just use the default value.

**Comment by destinytaoer** [comment]
没有人确认一下吗

**Comment by destinytaoer** [comment]
发现问题了，这里的 blog 源码与我使用 yarn 下载的源码有差异。是我本地的 blog 插件源码有问题

**Comment by ulivz** [comment]
Please install @vuepress/plugin-blog: 1.0.0-alpha.37
