### ISSUE TITLE
--open doesn't work

### ISSUE THREAD

**Issue by tangruijia** [vuejs/vuepress#1320]
- [ ] I confirm that this is a issue rather than a question.

#### Version
1.0.0-alpha.39
#### What is expected?
Use vuepress dev docs --open,expect the browser will open
#### What is actually happening?
Browser won't open
#### Other relevant information

- Your OS: macOS
- Node.js version: v10.3.0
- Browser version: chrome72
- Is this a global or local install? global/local install
- Which package manager did you use for the install?npm/yarn

**Comment by Shigma** [comment]
pr created at #1329
