### ISSUE TITLE
1.x version self layout no use，but the 0.x normal

### ISSUE THREAD

**Issue by leach-chen** [vuejs/vuepress#1321]
#### Version
1.x-alpha

#### What is expected?
Custom Layout for Specific Pages
By default the content of each *.md file is rendered in a <div class="page"> container, along with the sidebar, auto-generated edit links and prev/next links. If you wish to use a completely custom component in place of the page (while only keeping the navbar), you can again specify the component to use using YAML front matter:

- - -
layout: SpecialLayout
- - -
This will render .vuepress/components/SpecialLayout.vue for the given page.

Follow the official tutorial to use a custom layout in the md file
#### What is actually happening?
1.x version self layout no use，but the 0.x normal
#### Other relevant information
* Your OS: windows
* Node.js version: v10.15.1
* Browser version: chrome72
* Is this a global or local install? local install
* Which package manager did you use for the install?yarn

**Comment by Shigma** [comment]
你的 SpecialLayout.vue 文件应该放入 .vuepress/theme/layouts 目录。

**Comment by leach-chen** [comment]
我找到原因了，跟1.x版本对比，是1.x版本移除了该功能

**Comment by ulivz** [comment]
是个 issue，要优化

**Comment by Shigma** [comment]
@leach-chen @ulivz 我这里 SpecialLayout.vue 貌似用的好好的啊（躺

**Comment by ulivz** [comment]
另外，请把这个 issue 翻译成英文，谢谢。

**Comment by destinytaoer** [comment]
In 0.x ，the default layout is undefined，but in 1.x，it changed to 'Layout'。if you haven't defined layout，it will be 'Layout'。we can change the Layout.vue like 0.x

```html
<div
      class="custom-layout"
      v-if="$page.frontmatter.layout !== 'Layout'"
    >
    <component :is="$page.frontmatter.layout"></component>
</div>
```
但是，每次路由被改变，layout 都会被重新赋值，即使是默认值，如果把 $page.frontmatter.layout 弄成计算属性，会造成堆栈溢出

**Comment by destinytaoer** [comment]
如果像 @Shigma 一样，放置在 layouts 目录，那么会替换掉整个页面，而不只是内容区域。

**Comment by destinytaoer** [comment]
查看源码的逻辑是，如果定义的 layout 存在，那么就使用这个 [layout].vue 作为整个页面的布局。如果不存在，那么仍然会使用默认的 Layout.vue。

那么仍然可以像我前面所用的使用 $page.frontmatter.layout 在 Layout.vue 中进行判断。

也可以自定义一个 frontmatter，来进行判断使用哪个组件

**Comment by leach-chen** [comment]
> 另外，请把这个 issue 翻译成英文，谢谢。

已修改

**Comment by leach-chen** [comment]
> 查看源码的逻辑是，如果定义的 layout 存在，那么就使用这个 [layout].vue 作为整个页面的布局。如果不存在，那么仍然会使用默认的 Layout.vue。
> 
> 那么仍然可以像我前面所用的使用 $page.frontmatter.layout 在 Layout.vue 中进行判断。
> 
> 也可以自定义一个 frontmatter，来进行判断使用哪个组件

不用

> 查看源码的逻辑是，如果定义的 layout 存在，那么就使用这个 [layout].vue 作为整个页面的布局。如果不存在，那么仍然会使用默认的 Layout.vue。
> 
> 那么仍然可以像我前面所用的使用 $page.frontmatter.layout 在 Layout.vue 中进行判断。
> 
> 也可以自定义一个 frontmatter，来进行判断使用哪个组件

1.x可以在nodel_module下把主题拷出来重命名为themem放到.vuepress目录下，然后加回那段代码，官方既然说了是个issue，那就会改过来吧

**Comment by destinytaoer** [comment]
@leach-chen 使用 `vuepress eject ./docs` 可以直接抛出主题文件。希望官方可以快一些呗，整个页面和局部的都应该支持。刚刚尝试了一下，其他插件也会有依赖到这个自定义组件，比如标签页等，确实很难修改。还有很多待优化的，期待 VuePress 1.x 的正式发布。

**Comment by xxholly32** [comment]
现在只能用<special-layout/>写法写

**Comment by ulivz** [comment]
Fixed at 0306574b1f852e3284a65c62d2c85a1e0fefe97a.

BTW, using components under components (i.e., global components) as layouts is really convenient, but in 1.x we still suggest you to place layout components at layout directory, which has better-defined duties.

**Comment by xxholly32** [comment]
`1.0.0-alpha.43` 👍 

it seems use `YAML front matter` and user `<special-layout/>` is different; Using `YAML front matter` , the navbar is disappear;

@ulivz

**Comment by ulivz** [comment]
@xxholly32 In 1.x, the layout system was implemented by the `core` instead of the `default theme`, so if you use a custom layout, all the page's content will be replaced.

If you want to set global header, footer or sidebar, you should custom your [globalLayout](https://v1.vuepress.vuejs.org/theme/option-api.html#globallayout)

**Comment by xxholly32** [comment]
@ulivz ok
