### ISSUE TITLE
vuepress build docs  Error

### ISSUE THREAD

**Issue by Pearyman** [vuejs/vuepress#1328]
- [ ] I confirm that this is a issue rather than a question.

#### Version
- 0.14.9
#### Steps to reproduce

```
vuepress build docs
```

#### What is actually happening?
![image](https://user-images.githubusercontent.com/6932025/53225031-a8c36600-36b1-11e9-9a5d-881dcfc0c59e.png)

#### Other relevant information

- Your OS:  Mac OS
- Node.js version:  v11.2.0
- Browser version:  chrome 72.0.3626.109
- Is this a global or local install? global install
- Which package manager did you use for the install? npm

Please help me with a look

**Comment by Shigma** [comment]
Have a look at [this documentation](https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions).

Your project has a dependency `particles.js`, which cannot run directly without a browser environment.

**Comment by Pearyman** [comment]
@Shigma  方便具体一点么？

我只是在enhanceApp.js 文件里面全局挂载了`Vue` ` vue-highlight.js` ` element-ui` 这几个组件

```
import Vue from 'vue'
import VueHighlightJS from 'vue-highlight.js'
import 'highlight.js/styles/atom-one-dark.css'
import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import '../.vuepress/public/css/index.css'

export default ({
  Vue, 
  options, 
  router, 
  siteData
}) => {
  Vue.use(VueHighlightJS)
  Vue.use(Element)
}

```

然后Build的时候 ，就爆出 ReferenceError: window is not defined。

**Comment by Shigma** [comment]
你的代码中使用到了库 vue-particles，这个库依赖于 particles.js，而后者的运行又依赖于浏览器环境。（不信的话你可以在 Node 环境中单独 require 一下那个库试试~）根据浏览器的 API 访问限制，这样的代码是无法 build 的。

**Comment by Pearyman** [comment]
@Shigma  从哪里看到我使用 `vue-particles` 的？ 没有使用啊

项目 node_modules 截图
![image](https://user-images.githubusercontent.com/6932025/53227699-f9d75800-36b9-11e9-94a2-666449623213.png)

**Comment by Shigma** [comment]
非常不好意思……我以为你说的是 #1129。
然而你说的 element-ui 貌似存在同样的问题。

**Comment by Pearyman** [comment]
Looks like I know what the problem is.

**Comment by Shigma** [comment]
Ummmm I think you might misunderstand me.

If a module cannot be "require"d directly from Node, it cannot be used in vuepress, unless it is imported in the mounted hook like this:

```js
export default {
  mounted() {
    import('element-ui').then(/* things to do next */)
  }
}
```

**Comment by 1Crazy** [comment]
@Pearyman 你的问题和我当时遇到的一样，当时我是想全局引入一个vueparticle的组件，你是想找vuepress的入口文件哇，想全局引入组件是吧，建议你使用vuepress1.x的文档，看这篇教程
https://vuepress.vuejs.org/zh/guide/custom-themes.html#%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE
```
import Vue from 'vue';
import AppTest from './components/AppTest';

export default (({
  Vue
}) => {
  Vue.use(AppTest)
});
```

**Comment by Pearyman** [comment]
@1Crazy  Emmmmm  我是写了一个组件库 然后想用Vuepress做个文档  发现全局引入我写的这个组件库 怎么都挂载不上

dev环境是可以的  build 是不行的

**Comment by 1Crazy** [comment]
@Pearyman 你和我遇到的问题是一样的，建议看这篇文档，1.x的文档，1.x的文档有一个主入口文件，你把这个文件命名为enhanceApp.js就好了，记住用1.x的文档，下面是连接：https://vuepress.vuejs.org/zh/guide/custom-themes.html#%E8%8E%B7%E5%8F%96%E6%B8%B2%E6%9F%93%E5%86%85%E5%AE%B9

**Comment by Pearyman** [comment]
```
import Vue from 'vue'
import VueHighlightJS from 'vue-highlight.js'
import 'highlight.js/styles/atom-one-dark.css'
import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import '../.vuepress/public/css/index.css'
import mymodule from 'mymodule'
export default ({
  Vue, 
  options, 
  router, 
  siteData
}) => {
  Vue.use(VueHighlightJS)
  Vue.use(Element)
  Vue.use(mymodule)
}

```

我用的是 0.14.x的版本 ，不清楚为啥 element-ui这么使用可以全局挂载上，而我自己的组件库就挂载不上。然后Build的时候 ，就爆出 ReferenceError: window is not defined。

**Comment by 1Crazy** [comment]
@Pearyman 这个建议你用1.x的版本，0.x版本我当时也不行，0.x估计应该是底层代码的问题

**Comment by Pearyman** [comment]
Having found another way ，it was solved. 

```
import Vue from 'vue'
import VueHighlightJS from 'vue-highlight.js'
import 'highlight.js/styles/atom-one-dark.css'
import Element from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import '../.vuepress/public/css/index.css'
import {MyComponent} from 'mymodule/packages/MyComponent'
export default ({
  Vue, 
  options, 
  router, 
  siteData
}) => {
  Vue.use(VueHighlightJS)
  Vue.use(Element)
  Vue.component('MyComponent',MyComponent)
}
```
it works for me when i run `vuepress build`

**Comment by 1Crazy** [comment]
666

**Comment by xxholly32** [comment]
element-ui里面有个代码是
```
var root = window
```
去掉就好了，不知道是不是window不能赋值

[popper.js](https://github.com/ElemeFE/element/blob/dev/src/utils/popper.js)

**Comment by 1Crazy** [comment]
666

**Comment by ulivz** [comment]
@xxholly32 I recommend that you create a PR to element-ui to fix it, obviously it's SSR unfriendly.

**Comment by leafiy** [comment]
如果在directive中使用了window，无法使用client-only解决

**Comment by grasilife** [comment]
> Having found another way ，it was solved.
> 
> ```
> import Vue from 'vue'
> import VueHighlightJS from 'vue-highlight.js'
> import 'highlight.js/styles/atom-one-dark.css'
> import Element from 'element-ui'
> import 'element-ui/lib/theme-chalk/index.css'
> import '../.vuepress/public/css/index.css'
> import {MyComponent} from 'mymodule/packages/MyComponent'
> export default ({
>   Vue, 
>   options, 
>   router, 
>   siteData
> }) => {
>   Vue.use(VueHighlightJS)
>   Vue.use(Element)
>   Vue.component('MyComponent',MyComponent)
> }
> ```
> 
> it works for me when i run `vuepress build`

这个你最终的解决方案是什么?

**Comment by zwf193071** [comment]
我遇到了同样的问题，上述方法无法解决
我自己编写了一个组件包sf-view-vue，该组件包内置了接口方法，如下面代码所示：
`// 获得小区 楼栋详情
export function getAoipoiDetailInfo(query) {
    if (window) {
        return globalApi.axios({
            url: `${globalApi.oldBaseUrl}/standardAddress/getAddrDetail`,
            method: 'get',
            params: query,
        })
    }
}`
在调用该组件包时，需将上面对应的全局参数传入
`
import { axios } from './utils/request';

window.globalApi = Object.freeze({
   axios,
   oldBaseUrl: "//10.82.232.213:8083"
});
`
在vuepress文档系统内，组件vue代码如下所示：
`<template>
  <div>
    <SearchBox v-if="searchComponentsEnable" address="百瑞景中央生活区3期" style="left:700px;top:2140px;"></SearchBox>
  </div>
</template>

<script>
import { SearchBox } from 'sf-view-vue';
import { mapGetters } from 'vuex';
import { axios } from './utils/request';

export default {
	computed: {
  		...mapGetters([
    		'searchComponentsEnable' // 控制搜索控件是否显示，状态已在组件包内定义完成
		  ])
	},
	components: {
		SearchBox
	},
	provide() {
		return {
			hasBussiness: false, // tab页签去掉商业
			city: '武汉',
		};
	},
	beforeCreate() {
		this.$store.commit('SET_ADCODE', 420100);
	},
	mounted() {
		window.globalApi = Object.freeze({
			axios,
			oldBaseUrl: "//10.82.232.213:8083"
		});
	}
}
</script>
<style lang="less">
	@import "~sf-view-vue/src/styles/index.less";

    @tips-bg:rgba(18,18,18,0.8); // 搜索提示的背景颜色
    @inner-bg:rgba(18,18,18,.9); // 深度信息的背景颜色
    @input-bg:rgba(68,68,68,0.8); // 搜索框的背景颜色

    @tabWidth:33.33%;
</style>`

enhanceApp.js的代码如下所示：
`import Vue from 'vue'
import Vuex from 'vuex';
import { SFViewGetters, SFViewModules } from 'sf-view-vue';

export default ({
    Vue
}) => {
    Vue.use(Vuex);
    const store = new Vuex.Store({
        modules: {...SFViewModules},
        getters: {...SFViewGetters}
    });
    Vue.prototype.$EventBus = new Vue();
    Vue.mixin({store: store})
};`

`vuepress dev`都是正常的，但一旦`vuepress build`便会抛出
`server-bundle.js:63963
    if (window) {
    ^

ReferenceError: window is not defined
    at searchAddressData (server-bundle.js:63963:5)
    at VueComponent.<anonymous> (server-bundle.js:64106:7)
    at Timeout.later [as _onTimeout] (server-bundle.js:63860:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
`
