### ISSUE TITLE
Custom Layout for Specific Pages - Not Functioning

### ISSUE THREAD

**Issue by Mbensler** [vuejs/vuepress#1332]
- [x] I confirm that this is a issue rather than a question.

#### Version
1.x-alpha

#### Steps to reproduce
- Setup directory structure as shown on the Vuepress site. 
- Specify the page layout in the wanted readme.md file:
`---`
`layout: SpecialLayout`
`---`
- Add SpecialLayout.vue to component folder in .vuepress (with a default layout)

#### What is expected?
The component should be used as the new page layout.

#### What is actually happening?
Nothing. The component isn't used at all, however if i were to use something like:
`---`
`home: true`
`---`

along with other meta data shown on the Vuepress guide, then that works just fine. It seems as if it doesn't recognize the component. 

#### Other relevant information
Components are working just fine using them normally: 
Using `<SpecialLayout/>` in a readme.md file works just fine. It's when I'm trying to use it as the page layout it doesn't work.

- Your OS: Arch Linux
- Node.js version: 11.10.0
- Browser version: Firefox latest. Chromium latest.
- Is this a global or local install? Global
- Which package manager did you use for the install? Npm

**Comment by Shigma** [comment]
Can you provide a reproduction repo? Also please make sure you use the latest version.

**Comment by Mbensler** [comment]
Using latest version.

Will this do?
https://github.com/Mbensler/CiNe

**Comment by Shigma** [comment]
You should put your layouts in `theme/layouts` directory instead of `theme/components`.

**Comment by Mbensler** [comment]
> You should put your layouts in `theme/layouts` directory instead of `theme/components`.

I do not have a theme/components.

Doing what you said will create a custom layout for every single .md page in my docs folder. I only wish to create a custom layout for my frontpage: https://vuepress.vuejs.org/default-theme-config/#custom-layout-for-specific-pages

According to this link i would do: 
`--- 
layout: SpecialLayout 
---`
in the .md file that I want to create a custom layout for, for a specific page only, and then put the SpecialLayout.vue component in the .vuepress/components folder.

Doing what you said: 
Creating the theme/layouts/layout.vue is to create a theme for all your .md files, which is not what I want. I only want it for a specific page.

**Comment by butameron** [comment]
I have the same issue.
according to document of default theme, custom layout file is should be placed  in `.vuepress/components`.
> This will render .vuepress/components/SpecialLayout.vue for the given page.
> https://vuepress.vuejs.org/default-theme-config/#custom-layout-for-specific-pages

however, this doesn't work.

therefore, I think  document is wrong or this is bug of default theme.

**Comment by ulivz** [comment]
@butameron You should create an issue with repro instead of only mentioning here, or no one would answer you.

**Comment by butameron** [comment]
@ulivz thank you. 
sorry, I had thought i should not to post duplicate issue. 

repro code is not exist because I already avoid to use `.vuepress/components` and I did yarn upgrade. 
for now, layout placed in `.vuepress/components` works propery.

so my issue might be bug of my brain or node_modules dir state.
