### ISSUE TITLE
node stuck when run vuepress dev

### ISSUE THREAD

**Issue by chuxubank** [vuejs/vuepress#1334]
- [x] I confirm that this is a issue rather than a question.

#### Version
vuepress/1.0.0-alpha.39 darwin-x64 node-v11.10.0
#### Steps to reproduce

[My repo](https://github.com/chuxubank/Learning-AI)

#### What is expected?

`vuepress dev`

#### What is actually happening?

```bash
Asuna:Learning-AI misaka$ vuepress dev
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin latex (i.e. "vuepress-plugin-latex") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...

Compiling

● Client █████████████████████████ building (24%) 121/143 modules 22 active
  ../../../.config/yarn/global/node_modules/core-js/modules/es6.promise.js
```
And then it just stuck and `node` take up 99.7% of my CPU and do not respond even if send `Ctrl-z`.

#### Other relevant information

I can successfully run `vuepress build`
The file are different in each `vuepress dev` stuck
I can successfully run `vuepress dev` in a new empty vuepress project
Maybe too much `latex` code cause the stuck

When running `yarn global upgrade` the warings shows up:
```bash
warning vuepress > @vuepress/core > autoprefixer > browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning vuepress > @vuepress/core > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning vuepress > @vuepress/core > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning vuepress > @vuepress/core > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
```

- Your OS: macOS 10.14.3
- Node.js version: v11.10.0
- Browser version: Safari 12.0.3
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

**Comment by Shigma** [comment]
After removing `vuepress-plugin-latex`, the blog went on smoothly. This is obviously not vuepress' problem.

You can open a issue in `vuepress-plugin-latex`, or try to use other plugins since `vuepress-plugin-latex` is no longer maintained. How about `vuepress-plugin-mathjax`?

**Comment by ulivz** [comment]
[vuepress-plugin-mathjax](https://github.com/Shigma/vuepress-plugin-mathjax) is created by the collaborator of VuePress, undoubtedly you can should use it first.

**Comment by chuxubank** [comment]
Thanks for replay!

I have tried `vuepress-plugin-mathjax` before but `mathjax` just not perform that well as `katex`, and `vuepress-plugin-mathjax` has some little bugs. [Inline bug](https://github.com/Shigma/vuepress-plugin-mathjax/issues/1#issue-413949350)

The `vuepress-plugin-latex` seemed directly use the `@iktakahiro/markdown-it-katex` and it still stuck when run `vuepress dev`

It still very strange that it just stuck in `dev` but succeed in `build` lol.
