### ISSUE TITLE
Custom Template Content not processing markdown correctly

### ISSUE THREAD

**Issue by davehlewis** [vuejs/vuepress#134]
Trying to create a custom template as per the docs. Layout.vue file has following:
```
<template>
  <div>
    <Content/>
  </div>
</template>
```
Simple Hello world markdown file:
`# Hello World`
Outputs following HTML
```
<h1>
  <a href="#hello-world" aria-hidden="true" class="header-anchor">#</a> Hello World
</h1
```
Correctly recognises H1, but keeps # for some reason.

**Comment by yyx990803** [comment]
The `#` is an anchor header which is hidden by CSS... please actually open the page to see what it looks like.

**Comment by mtobeiyf** [comment]
@davehlewis The default layout is loaded. You need to add a `override.styl` to override the default css.
Check the doc: https://vuepress.vuejs.org/default-theme-config/#simple-css-override

**Comment by davehlewis** [comment]
I feel like people either aren't understanding my message fully.

I am setting up a custom layout, a custom theme. The default is being overridden, so there are no styles to overrwrite. Please look at the docs under Custom Themes (https://vuepress.vuejs.org/guide/custom-themes.html).

My point is the docs at the moment for this do not list some of the custom styles you apparently need for it to work as normal. It's fine, and I have done that now, but there should be a mention of it perhaps is my only thought?

**Comment by pattrickrice** [comment]
These anchor tags can be hidden by placing the following in your .vue-press/theme/Layout.vue
```
<style>
.header-anchor {
  display: none;
}
</style>
```

**Comment by venimus** [comment]
you would need to set
```
module.exports = {
...
    markdown: {
        anchor: {
            permalink: false
        }
    },
...
}
```
in `.vuepress/theme/config.js`
