### ISSUE TITLE
@vuepress/theme-blog not found

### ISSUE THREAD

**Issue by songololo** [vuejs/vuepress#1340]
- [x] I confirm that this is a issue rather than a question.

## Bug report
Unable to install @vuepress/theme-blog

#### Version
`"vuepress": "^1.0.0-alpha.39"`

#### Steps to reproduce
Try to add `@vuepress/theme-blog` with `yarn`.

#### What is expected?
That the blog theme will be installed.

#### What is actually happening?
`yarn` returns an error when trying to install `@vuepress/theme-blog`: 

`error An unexpected error occurred: "https://registry.yarnpkg.com/@vuepress%2ftheme-blog: Not found".`

#### Other relevant information

- Your OS: Mac
- Node.js version: v11.9.0
- Browser version: Safari & Chrome latest
- Is this a global or local install? Local
- Which package manager did you use for the install? yarn

**Comment by Shigma** [comment]
Sorry, but our `@vuepress/theme-blog` is currently working in progress.

You can check this [roadmap](https://github.com/vuejs/vuepress/projects/1#card-17994124).
