### ISSUE TITLE
Mobile terminal icon

### ISSUE THREAD

**Issue by newbie-println** [vuejs/vuepress#1342]
I noticed that the icon in the upper left corner of the mobile terminal in version 0.14.9 was not displayed

But the **_1.0.0-alpha version_** does
[http://note.println.xyz/bug.png](http://note.println.xyz/bug.png)
![http://note.println.xyz/bug.png](http://note.println.xyz/bug.png)

**Comment by Shigma** [comment]
fixed？

**Comment by ulivz** [comment]
Fixed and out at `0.14.10`.
