### ISSUE TITLE
upgrading from 1.0.0-alpha.30 to 1.0.0-alpha.39 breaks and breaks rollback too!

### ISSUE THREAD

**Issue by ksnyde** [vuejs/vuepress#1344]
- [x] I confirm that this is a issue rather than a question.

#### Version

1.0.0-alpha.39

#### Steps to reproduce

**Steps:**
- Using `1.0.0-alpha.30`, upgrade to `1.0.0-alpha.39` via "yarn upgrade vuepress@next"
- When you run `yarn docs` it starts compilation but fails on client compilation at 0% with the error:
     > events.js:183
     > throw er; // Unhandled 'error' event

    then there is a few CR's and then error message:

     > Error: getaddrinfo ENOTFOUND localhost
     >     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

- I did notice a "tip" that "override.styl" has been deprecated in favor of "palette.styl" but changing to this new file structure made no difference in outcome
- I also tried a system reboot, repo 1 on `alpha.39` exhibits above error, repo 2 on `alpha.30` works fine.
- I also a "nuclear" clearout with `rimraf lib; rimraf node_modeles; yarn cache clean; rm yarn.lock; yarn`; no difference
- I then checked whether a production build with `yarn docs:build` would work; no issues, works fine

**Rollback Steps**
- I then tried to **rollback** with `yarn upgrade@1.0.0-alpha.30`
     > Note: I also rolled back the `palette.styl` to `override.styl`
- This now produces the following error (where there had been no error before):

    > module.js:550
    > throw err;

   the stack is:

    > Error: Cannot find module 'cac'
    >     at Function.Module._resolveFilename (module.js:548:15)
    >     at Function.Module._load (module.js:475:25)
    >     at Module.require (module.js:597:17)
    >     at require (internal/module.js:11:18)
    >     at Object.<anonymous> (/Users/ken/mine/forest-fire/firemodel/node_modules/vuepress/lib/util.js:8:13)
    >     at Module._compile (module.js:653:30)
    >     at Object.Module._extensions..js (module.js:664:10)
    >     at Module.load (module.js:566:32)
    >     at tryModuleLoad (module.js:506:12)
    >     at Function.Module._load (module.js:498:3)
    >     at Module.require (module.js:597:17)
    >     at require (internal/module.js:11:18)
    >     at Object.<anonymous> (/Users/ken/mine/forest-fire/firemodel/node_modules/vuepress/vuepress.js:4:17)
    >     at Module._compile (module.js:653:30)
    >     at Object.Module._extensions..js (module.js:664:10)
    >     at Module.load (module.js:566:32)
- to my surprise at this point I can't even run a production build as it generates the same error as above!

**Repos:**
I have reproduced this in two repos and using the steps described the behavior is identical. Only one of the two is a public repo: https://github.com/forest-fire/firemodel, to see it both states you refer to these commits off the `features/dynamic-dbPath` feature:

- [version 1.0.0-alpha.39](https://github.com/forest-fire/firemodel/commit/fc910a981c9cace51be560e44761a4f96d36eb09)
- [version 1.0.0-alpha.30](https://github.com/forest-fire/firemodel/commit/6ae8a405c2c4fea46e24aba35ba062a8ff1a6434)

#### What is expected?

`yarn docs` to start node server which gives me dev server for my docs

#### What is actually happening?

compilation crashes with above error(s); rolling back to prior version fails as well!

#### Other relevant information

- Your OS: macOs 10.14.3 
- Node.js version: 8.15.0, 10.15.1 (tried both)
- Browser version: Chome 72.0.3626.109
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn
- Does this issue occur when all plugins are disabled? I use pwa, back-to-top, last-updated, and -medium-zoom but even when removed from `config.js` the problem exists

**Comment by ksnyde** [comment]
Probably not relevant to this issue but when I run a production build with `1.0.0-alpha.39` I get the following.

![image](https://user-images.githubusercontent.com/980757/53303431-10e38a80-381f-11e9-9a5c-92be81189524.png)

**Comment by ksnyde** [comment]
Ugh. I have now upgraded to 1.0.0-alpha.40 as I was hoping all my troubles would go away. Nope. I have a new error instead and shockingly this one too does not go away when I rollback to `1.0.0-alpha.39`. Why roll back? Well with `.39` I could still produce production builds but now both dev and production are broken. :( 

> TypeError: Cannot read property 'multiple' of undefined
>     at PluginAPI.use (/Users/ken/mine/forest-fire/firemodel/node_modules/@vuepress/core/> lib/plugin-api/index.js:94:16)
>     at pluginsConfig.forEach (/Users/ken/mine/forest-fire/firemodel/node_modules/> @vuepress/core/lib/plugin-api/index.js:139:12)
>     at Array.forEach (<anonymous>)
>     at PluginAPI.useByPluginsConfig (/Users/ken/mine/forest-fire/firemodel/node_modules/> @vuepress/core/lib/plugin-api/index.js:138:19)
>     at PluginAPI.use (/Users/ken/mine/forest-fire/firemodel/node_modules/@vuepress/core/> lib/plugin-api/index.js:105:12)
>     at AppContext.applyUserPlugins (/Users/ken/mine/forest-fire/firemodel/node_modules/> @vuepress/core/lib/prepare/AppContext.js:176:8)
>     at AppContext.process (/Users/ken/mine/forest-fire/firemodel/node_modules/@vuepress/> core/lib/prepare/AppContext.js:102:10)
>     at prepare (/Users/ken/mine/forest-fire/firemodel/node_modules/@vuepress/core/lib/> prepare/index.js:17:20)
>     at prepareServer (/Users/ken/mine/forest-fire/firemodel/node_modules/@vuepress/core/> lib/dev.js:28:32)
>     at module.exports (/Users/ken/mine/forest-fire/firemodel/node_modules/@vuepress/> core/lib/dev.js:4:40)
>     at args (/Users/ken/mine/forest-fire/firemodel/node_modules/vuepress/lib/> util.js:35:12)
>     at CAC.cli.command.option.option.option.option.option.option.option.option.action (/> Users/ken/mine/forest-fire/firemodel/node_modules/vuepress/lib/> registerCoreCommands.js:34:23)
>     at CAC.runMatchedCommand (/Users/ken/mine/forest-fire/firemodel/node_modules/cac/> dist/index.js:787:38)
>     at CAC.parse (/Users/ken/mine/forest-fire/firemodel/node_modules/cac/dist/> index.js:707:18)
>     at CLI (/Users/ken/mine/forest-fire/firemodel/node_modules/vuepress/lib/> util.js:23:7)
>     at <anonymous>

**Comment by ulivz** [comment]
So at least you should provide a minimal reproduction repo instead of creating too many error logs here and no one can help you 🙂

**Comment by ksnyde** [comment]
That’s a bit unfair. I gave you a repo version which WAS the repoducible example. I spent a lot of putting this together and this reponse comes off as too disapproving and smug. It’s entirely unfair to ask for some additional detail but leaving a window of a few days for the person who raised it to response give the impression of caring rather than just trying to avoid.
