### ISSUE TITLE
IE 11 -- any chance

### ISSUE THREAD

**Issue by flacito** [vuejs/vuepress#135]
I ask this with all humility:  is there anyway we can get the build to work for IE 11?   We work at place that still runs Windows 7 and has IE 11 as its approved browser and we are trying to introduce DevOps to a lot of noobs who just have, argh, IE 11.

Thanks SO much for even considering.

--Brian

**Comment by flacito** [comment]
Wait, seeing the evergree option in the webpack config.  Is this the answer?

**Comment by yyx990803** [comment]
The build *should* already work in IE11 (note: the dev server does not). If it doesn't please file a bug report.
