### ISSUE TITLE
Missing sidebar button on a mobile homepage

### ISSUE THREAD

**Issue by Vladislav-Lyuminarskiy** [vuejs/vuepress#1355]
- [x] I confirm that this is a issue rather than a question.

#### Version

`0.14.9`.

#### Steps to reproduce

1. Add a navbar.
2. Open mobile homepage.

#### What is expected?

1. Navbar is hidden.
2. Sidebar button is visible.

#### What is actually happening?

1. Navbar is hidden.
2. Sidebar button is **also hidden**.

Demo: https://oop-course.github.io/en/

Homepage with a sidebar on an iPad:
![52947839-4d336880-3391-11e9-9605-f43bc82ef453](https://user-images.githubusercontent.com/16743037/53337592-47063480-391b-11e9-8400-17063f4dada1.png)

Same page on an iPhone (sidebar button is missing):
![52947845-502e5900-3391-11e9-9cb3-f3b7cc3b49a7](https://user-images.githubusercontent.com/16743037/53337608-4ff70600-391b-11e9-8f88-37028cb6f629.png)

#### Other relevant information

Sourse of the bug: #1159

- Your OS: Windows 10 `1809`
- Node.js version: `10.9.0`
- Browser version: Google Chrome `72.0.3626.109`
- Global install.
- NPM.
- VuePress v0 doesn't support plugins.

**Comment by ulivz** [comment]
Now it's out at `v0.14.10`.

**Comment by alcuadrado** [comment]
Hey @ulivz! Thanks for your update :)

Is `v0.14.10` already published? I can't find it [on npm](https://www.npmjs.com/package/vuepress).

**Comment by alcuadrado** [comment]
I was dealing with this same issue yesterday. I can confirm that `v.0.14.10` fixes it. Thank you!
