### ISSUE TITLE
[Bug report] 1.0.0-alpha.40 breaks #1204, #1206

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#1362]
- [x] I confirm that this is a issue rather than a question.

#### Version

1.0.0-alpha.40

#### Steps to reproduce

https://github.com/vuejs/vuepress/commit/d16d3d574ea30a3597e1919acedd77f6d1c770f2#diff-56a897e96a354a8b8ea86dc24074ad5bR61

```js
    const pkgPath = require.resolve(name)
    let packageRootDir = parse(pkgPath).dir
    // For those cases that "main" field was set to non-index file
    // e.g. `layouts/Layout.vue`
    while (!fs.existsSync(`${packageRootDir}/package.json`)) {
      packageRootDir = resolve(packageRootDir, '..')
    }
```

#### What is expected?

Allow "main" field to be set to something like `lib/index.js` (As explained in #1204 )

In such case, the `packageRootDir` should be `<pkgDir>/lib/`

#### What is actually happening?

The `packageRootDir` is `<pkgDir>` now.

**Comment by ulivz** [comment]
There is another more important case for now, a 0.x user would want to migrate his/her theme to 1.x and doesn't have `themeEntry`, so he need set the "main" field to `layouts/Layout.vue`. so we need to retrieve the correct theme path.

For your case you can try:

```js
module.exports = {
   theme: require.resolve('vuepres-theme-xxx/lib')
}
```

**Comment by meteorlxy** [comment]
@ulivz 

Emmm.. As I remembers, 0.x theme does not allow users to set set the "main" field to `layouts/Layout.vue`

https://github.com/vuejs/vuepress/blob/a30f6fa363a2f424d8c8494f34bfe4689bc6c03c/lib/prepare/resolveOptions.js#L61

![image](https://user-images.githubusercontent.com/18205362/53474559-5ff02080-3aa8-11e9-9418-1d35717f7f05.png)
