### ISSUE TITLE
Add browser compatibility meta tag for IE

### ISSUE THREAD

**Issue by flacito** [vuejs/vuepress#137]
[regarding](https://github.com/vuejs/vuepress/issues/135)

Our IT team displays intranet sites in Compatibility View in IE 11.  Although we can disable it if we know what we are doing, the vast majority of our users do not know how to do this and leave it enabled. The HTML, Javascript, and CSS that Vuepress generates does not work in IE Compatibility View.

Microsoft has provided a workaround that I think will fix things if we add `<meta http-equiv="XA-UA-Compatible" content="IE=edge">` as a meta tag in the page headers. It would have to be in every generated HTML file.

I took a look at the [Site and Page Metadata](https://vuepress.vuejs.org/guide/custom-themes.html#site-and-page-metadata) section of the docs, but it didn't explain the headers field.  Would I just literally put that meta tag in the headers array?

If not, can we add a feature to Vuepress to either put the meta tag in there all the time or provide a boolean in the config.js to turn it on?

Thanks! --Brian

**Comment by yyx990803** [comment]
https://vuepress.vuejs.org/config/#head

**Comment by flacito** [comment]
Amazing support sir.  Thank you so much. ❤️ Vue
