### ISSUE TITLE
Boilerplate production repo ulivz/template-vuepress gives 404

### ISSUE THREAD

**Issue by tedmiston** [vuejs/vuepress#1372]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Open <https://github.com/ulivz/template-vuepress> in browser.

#### What is expected?

It is expected that this URL leads to the "boilerplate to create a proper reproduction repo quickly" as mentioned in the GitHub issue template here.

https://github.com/vuejs/vuepress/blame/cbafe8f562df45f0e9399abf3298da80f5159c1a/.github/ISSUE_TEMPLATE/bug_report.md#L29

#### What is actually happening?

The page returns a 404.  A cursory shows that the repo does not seem to exist under ulivz or vuejs orgs.  Any chance it's been migrated or renamed?

#### Other relevant information

- Your OS: n/a
- Node.js version:  n/a
- Browser version:  n/a
- Is this a global or local install?  n/a
- Which package manager did you use for the install? n/a
- Does this issue occur when all plugins are disabled? n/a

**Comment by ulivz** [comment]
You can visit it now.
