### ISSUE TITLE
Front-matter defaults in config

### ISSUE THREAD

**Issue by bandantonio** [vuejs/vuepress#1377]
Hello everyone.
I'm trying to switch my documentation site from GitBook to Vuepress and got stuck with front-matter variables. In GitBook you just add variables in config and then use them anywhere on page as `{{ book.variable_name }}`. In Vuepress, at glance, things seem to be trickier.

I need to configure several variables that are used _across the whole site_, so adding them to each page would be a complete nightmare. The documentation tells nothing about how to configure front-matter variables but has a link to Jekyll site. On the Jekyll site, I found [this article](https://jekyllrb.com/docs/configuration/front-matter-defaults/) that is exactly what I want to achieve. The problem is that I have no idea how to use this info in config. 

Any help is highly appreciated.

**Comment by ulivz** [comment]
See: https://v1.vuepress.vuejs.org/guide/frontmatter.html

**Comment by bandantonio** [comment]
This section doesn't answer my question.
How do I add a variable to `config.js` so that variable will appear in all created pages? For example, `author`.
