### ISSUE TITLE
Chagne install vuepress to vuepress@next In Getting Start

### ISSUE THREAD

**Issue by g6ling** [vuejs/vuepress#1380]
## Bug report
https://github.com/vuejs/vuepress/blob/master/packages/docs/docs/guide/getting-started.md
In getting start page, use `yarn global add vuepress`. However, i think this have to be changed to `yarn global add vuepress@next`, because this page is for vuepress 1.x version.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?
- Does this issue occur when all plugins are disabled?

**Comment by Shigma** [comment]
Should title be `vuepress@next`?

**Comment by g6ling** [comment]
@Shigma sorry. i did mistake. i edited title :)

**Comment by Shigma** [comment]
I bet you are right. Contribution welcome!
