### ISSUE TITLE
[Bug report] `evergreen` disable babel totally

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#1386]
- [x] I confirm that this is an issue rather than a question.

#### Version

1.0.0-alpha.40

#### Steps to reproduce

https://github.com/vuejs/vuepress/blob/1850be7f343e54575c64d82c4f0cedc25a9aa91c/packages/%40vuepress/core/lib/webpack/createBaseConfig.js#L126-L162

#### What is expected?

We still need babel to make some things work, e.g. jsx

#### What is actually happening?

`evergreen` disable babel totally.

**Comment by ulivz** [comment]
You can add it by yourself since we don't decide to support `jsx` internally.
