### ISSUE TITLE
[Bug report] PascalCase layouts cannot be used camelCase nor hyphen-delimited

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#1391]
- [x] I confirm that this is an issue rather than a question.

#### Version

1.0.0-alpha.42

#### Steps to reproduce

1. Create a layout `Hello`:

```sh
+-- .vuepress
    +-- theme
        +-- layouts
            +-- Hello.vue
            +-- Layout.vue
```

2. Set `layout` in the frontmatter:

```md
---
layout: hello
---
```

#### What is expected?

Render layout `Hello.vue`.

#### What is actually happening?

Render layout `Layout.vue`.

#### Other relevant information

The expected behavior is how 0.x behaves. So this could be a breaking change if not fixed.

Some relevant information about this issue:

- 1.x does not register all the layout components autoly, but 0.x does. 1.x only register layout components in routes `beforeEnter` hook (see https://github.com/vuejs/vuepress/issues/1173#issuecomment-469011680).
- 1.x will check if the layout exists accoding to the exact layout name, i.e. `LayoutName` is only matched with `LayoutName` but not `layoutName` nor `layout-name`

**Comment by ulivz** [comment]
Available at `1.0.0-alpha.43`.
