### ISSUE TITLE
How to auto generate sidebar in vuepress component

### ISSUE THREAD

**Issue by xsmyqf** [vuejs/vuepress#1392]
##### this is my readme.md file
```
---
#blog_index: true
sidebar: auto
---

<IndexByCategory />
```
##### this is my IndexByCategory Component
```
<template>
    <div>
        <div v-for="(posts,postTag,index) in postsResult">
            <h2 :id="postTag"><a href="#" aria-hidden="true" class="header-anchor">#</a> {{postTag}}</h2>
            <div v-for="post in posts">
            <h3>
                <router-link :to="post.path">{{ post.frontmatter.title }}</router-link>
            </h3>
    
            <p>{{ post.frontmatter.description }}</p>
    
            <p>
                <router-link :to="post.path">Read more</router-link>
            </p>
            <hr>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        computed: {
            postsResult() {
                var tagSort = new Object();
                var filteredPages=this.$site.pages.filter(x => x.path.startsWith('/blog/'));
                //console.log(this.$site["pages"]);
                filteredPages.forEach(element => {
                    if(element["frontmatter"]["tags"]==undefined){
                        console.log(element["title"]+"  don't have tags in frontmatter!");
                    }
                    element["frontmatter"]["tags"].forEach(element2 => {
                        if (tagSort[element2] == undefined) {
                            tagSort[element2] = new Array();
                        }
                        tagSort[element2].push(element);
                    });
                });
                //console.log(tagSort);
                return tagSort;
            }
        }
    }
</script>
```
I want to generate a tag as a markdown head in component so that I can use sidebar:auto to generate a sidebar,but I don't know the fastest way to realize it.
#### What does the proposed API look like?
give a way to realize a sidebar anchor in vuepress component.maybe it is a component too.
#### How should this be implemented in your opinion?
use a vuepress component like makrdown header # ,## ,###
#### Are you willing to work on this yourself?**
no,I don't have much time to write it.

**Comment by ulivz** [comment]
https://v1.vuepress.vuejs.org/guide/using-vue.html#built-in-components

**Comment by PeppeL-G** [comment]
I'm having the same problem. When a markdown file contains a `<MyOwnVueComponenet />` that in turn contains headers like `<h1>`, these headers do not appear in the sidebar.

If I'm not mistaking, a workaround for this is using [a custom a container](https://vuepress.github.io/en/plugins/container/#usage) instead (at least it correctly register headers using the `::: warning :::` container), but at the moment I can't see how to do it in a convenient way. Using my own Vue component, I would simply write the following in my markdown file:

```html
<GradingGuidelines
	:guidelines='[{
		title: "Indentation Convention",
		description: "The convention used for indenting code (e.g. 4 spaces or a tab) and the optional usage of and placement of curly brackets. For more information, see https://en.wikipedia.org/wiki/Indentation_style",
		gradeU: "No indentation convention has been used or there exists too many places where the convention has not been followed.",
		grade3: "The same indentation convention is mostly used, but at a few places the convention has not been followed.",
		grade4: "The same indentation convention is consistently used in each file, although individual files (even of the same type) may use different indentation conventions.",
		grade5: "The same indentation convention is consistently used across all files of the same type." 
	}, {
		title: "Naming Convention",
		description: "The convention used when naming variables, constants, functions, classes, methods, functions, files, packages, etc. For more information, see https://en.wikipedia.org/wiki/Naming_convention_(programming).",
		gradeU: "No naming convention has been used or there exists too many places where the convention has not been followed.",
		grade3: "The same naming convention is mostly used, but at a few places the convention has not been followed.",
		grade4: "The same naming convention is consistently used in each file, although individual files (even of the same type) may use different naming conventions.",
		grade5: "The same naming convention is consistently used across all files of the same type." 
	}, {
		title: "Mnemonic names",
		description: "The names used (on variables, functions, classes, etc.) reflect what they represent. Optimal names should be short and very descriptive. For more information, see https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Python_for_Everybody_(Severance)/2%3A_Variables%2C_Expressions%2C_and_Statements/2.12%3A_Choosing_Mnemonic_Variable_Names",
		gradeU: "Many names are not mnemonic.",
		grade3: "Many names (~80%) are mnemonic.",
		grade4: "Almost all names (~90%) are mnemonic.",
		grade5: "All names (~100%) are mnemonic." 
	}, {
		title: "Correct usage of statements/expressions",
		description: "When a solution can be implemented in different ways, the most preferred implementation is used. If statements VS switches, arrays VS switches, for loops VS while loops VS do-while loops, iteration over indexes VS iteration over values etc.",
		gradeU: "Solutions have not been implemented at all.",
		grade3: "The solutions are often not implemented the preferred way.",
		grade4: "The solutions are often implemented the preferred way.",
		grade5: "The solutions are always implemented the preferred way." 
	}]'
/>
```
But if I should use a container instead, I don't see how I would be able to pass this information in a convenient way to the container. Pass it as a JSON string and then parse it in the custom container I create? Any input on this is appreciated.

**Comment by xsmyqf** [comment]
I have tried several times and gave up.I use a page to guide all.

**Comment by xsmyqf** [comment]
I have tried several times and gave up.I use a page to guide all.Hope to help you.






------------------ 原始邮件 ------------------
发件人: "Peter Larsson-Green"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 上午6:40
收件人: "vuejs/vuepress"<vuepress@noreply.github.com>;
抄送: "木叶清风-谢"<xsmyqf@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vuejs/vuepress] How to auto generate sidebar in vuepresscomponent (#1392)




I'm having the same problem. When a markdown file contains a <MyOwnVueComponenet /> that in turn contains headers like <h1>, these headers do not appear in the sidebar.
 
If I'm not mistaking, a workaround for this is using a custom a container instead (at least it correctly register headers using the ::: warning ::: container), but at the moment I can't see how to do it in a convenient way. Using my own Vue component, I would simply write the following in my markdown file:
 <GradingGuidelines 	:guidelines='[{ 		title: "Indentation Convention", 		description: "The convention used for indenting code (e.g. 4 spaces or a tab) and the optional usage of and placement of curly brackets. For more information, see https://en.wikipedia.org/wiki/Indentation_style", 		gradeU: "No indentation convention has been used or there exists too many places where the convention has not been followed.", 		grade3: "The same indentation convention is mostly used, but at a few places the convention has not been followed.", 		grade4: "The same indentation convention is consistently used in each file, although individual files (even of the same type) may use different indentation conventions.", 		grade5: "The same indentation convention is consistently used across all files of the same type."  	}, { 		title: "Naming Convention", 		description: "The convention used when naming variables, constants, functions, classes, methods, functions, files, packages, etc. For more information, see https://en.wikipedia.org/wiki/Naming_convention_(programming).", 		gradeU: "No naming convention has been used or there exists too many places where the convention has not been followed.", 		grade3: "The same naming convention is mostly used, but at a few places the convention has not been followed.", 		grade4: "The same naming convention is consistently used in each file, although individual files (even of the same type) may use different naming conventions.", 		grade5: "The same naming convention is consistently used across all files of the same type."  	}, { 		title: "Mnemonic names", 		description: "The names used (on variables, functions, classes, etc.) reflect what they represent. Optimal names should be short and very descriptive. For more information, see https://eng.libretexts.org/Bookshelves/Computer_Science/Book%3A_Python_for_Everybody_(Severance)/2%3A_Variables%2C_Expressions%2C_and_Statements/2.12%3A_Choosing_Mnemonic_Variable_Names", 		gradeU: "Many names are not mnemonic.", 		grade3: "Many names (~80%) are mnemonic.", 		grade4: "Almost all names (~90%) are mnemonic.", 		grade5: "All names (~100%) are mnemonic."  	}, { 		title: "Correct usage of statements/expressions", 		description: "When a solution can be implemented in different ways, the most preferred implementation is used. If statements VS switches, arrays VS switches, for loops VS while loops VS do-while loops, iteration over indexes VS iteration over values etc.", 		gradeU: "Solutions have not been implemented at all.", 		grade3: "The solutions are often not implemented the preferred way.", 		grade4: "The solutions are often implemented the preferred way.", 		grade5: "The solutions are always implemented the preferred way."  	}]' />
 
But if I should use a container instead, I don't see how I would be able to pass this information in a convenient way to the container. Pass it as a JSON string and then parse it in the custom container I create? Any input on this is appreciated.

**Comment by PeppeL-G** [comment]
@ulivz I don't think you've understood what we're trying to do here, or we simply don't understand how the link you wrote can help us. Could you clarify?

**Comment by PeppeL-G** [comment]
I have a solution now, although not a nice one (IMO).

In `config.js` create your own container with code like this:

```js
const container = require('markdown-it-container')

function createContainer(type) {
  return [container, type, {
    render(tokens, idx) {
      const token = tokens[idx]
      if (token.nesting === 1) {
        const guidelineAsJson = token.info.trim().slice(type.length).trim()
        tokens.guideline = JSON.parse(guidelineAsJson) // Remember the data in the tokens object, so we can access it the next time render() is called.
        return `
          <div class="container-grading-guideline">\n`
      } else {
        const guideline = tokens.guideline // Read out the data.
        return `
            <p>${guideline.description}</p>
            <table>
              <tbody>
                  <tr>
                    <td>
                      <b>Grade U</b><br>
                      ${guideline.gradeU}
                    </td>
                    <td>
                      <b>Grade 3</b><br>
                      ${guideline.grade3}
                    </td>
                    <td>
                      <b>Grade 4</b><br>
                      ${guideline.grade4}
                    </td>
                    <td>
                      <b>Grade 5</b><br>
                      ${guideline.grade5}
                    </td>
                  </tr>
              </tbody>
            </table>
          </div>\n
        `
      }
    }
  }]
}

module.exports = {
  // ...
  markdown: {
    extendMarkdown: md => {
      md.use(...createContainer('grading-guideline') )
    }
  }
}
```

And then I can use it like this in markdown files:

```markdown
::: grading-guideline {"description": "The convention used for indenting code (e.g. 4 spaces or a tab) and the optional usage of and placement of curly brackets. For more information, see https://en.wikipedia.org/wiki/Indentation_style", "gradeU": "No indentation convention has been used or there exists too many places where the convention has not been followed.", "grade3": "The same indentation convention is mostly used, but at a few places the convention has not been followed.", "grade4": "The same indentation convention is consistently used in each file, although individual files (even of the same type) may use different indentation conventions.", "grade5": "The same indentation convention is consistently used across all files of the same type."}
## Indentation Convention
:::
```

Now the `Indentation Convention` is found and put in the sidebar, but it does not feel like a clean way to do it. Suggestions on better ways to do it are very welcome.

**Comment by JStumpp** [comment]
Same problem here. We generate page content (including headers like h2, h3) from a json file, example here: https://docs.movisens.com/movisensXS/mobile_sensing/#features-library-version-version

Having no sidebar and no search for this content is a huge problem for us. @ulivz, do you have a suggestion? Thank you so much.

**Comment by m-mohr** [comment]
Same problem here...

**Comment by iamchriswick** [comment]
Why is this closed when there no solution for it?
