### ISSUE TITLE
Is it possible to specify that a sidebar group that is collapsible is expanded by default?

### ISSUE THREAD

**Issue by SimeonRoss** [vuejs/vuepress#1405]
Hi,

I've got some sidebar groups which are all collapsible however when you land on the page i'd like the first group to be expanded by default. Is this possible?

**Comment by DRD161** [comment]
It's possible using Bootstrap 4 or Javascript. Bootstrap 4 has a class that allows you to specify what container is expanded/collapsed depending on the viewport size.

**Comment by SimeonRoss** [comment]
How would you do either of these approaches? I'm using an out of the box VuePress setup

**Comment by ulivz** [comment]
You can set `collapsable: true` for each sidebar group.

**Comment by SimeonRoss** [comment]
@ulivz You have not understood my question. I know that i can do that to make them collapsable. However, the default behaviour is then to have them collapsed when you land on the page whereas i would like one of them to be expanded by default. How do I achieve that?

**Comment by fdabek1** [comment]
> You can set `collapsable: true` for each sidebar group.

@ulivz Can we reopen this as you mistakenly did not understand the question and this would be very helpful to add.

**Comment by MartinMuzatko** [comment]
Would also like to have

**Comment by timqian** [comment]
+1 for this

**Comment by timqian** [comment]
Whether a collapsible group is expanded or not seems random. I got about 20 groups with the same setting, some are expanded and some are collapsed.
It would be great if we can decide it

**Comment by rexwangcc** [comment]
Would it be possible to re-open the issue and have more discussion around this?
