### ISSUE TITLE
[Bug report] plugin-last-updated display 'en' time when default lang is 'zh-CN'

### ISSUE THREAD

**Issue by YunYouJun** [vuejs/vuepress#1410]
- [x] I confirm that this is an issue rather than a question.

## Bug report

plugin-last-updated display time format in `en` when my lang is `zh-CN`.

#### Version

v1.0.0-alpha.42

#### Steps to reproduce

Build in travis.

```sh
yarn docs:build
```

[Travis Build Log](https://travis-ci.com/YunYouJun/software-engineering-notes/jobs/182725236)

#### What is expected?

I expect `2019-3-6 16:12:33`

#### What is actually happening?

I get `3/6/2019, 8:12:33 AM`.

![image](https://user-images.githubusercontent.com/25154432/53884076-af5cc080-4055-11e9-88ee-e0baa466c2fc.png)

#### Other relevant information

And I `console.log(this.$lang)`:

![image](https://user-images.githubusercontent.com/25154432/53884350-5f322e00-4056-11e9-877d-ea984fc32026.png)

It only happened to Travis.

```sh
yarn docs:dev
```

I can see right format `2019-3-6 21:01:27` in my localhost.

- Your OS: Windows 10
- Node.js version: v11.9.0
- Browser version: Google Chrome 72.0.3626.119
- Is this a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled?

**Comment by ulivz** [comment]
Sorry but I cannot reproduce at my side (just like the official website also works.).

![image](https://user-images.githubusercontent.com/23133919/53979553-26bf4c80-4149-11e9-8368-acfe86e58dc0.png)

I guess it's the issue of `new Date` at windows. I suggested that you using a custom [transformer](https://v1.vuepress.vuejs.org/plugin/official/plugin-last-updated.html#transformer) to solve it.

**Comment by YunYouJun** [comment]
It works well in my computer. ( Windows 10, China )
But it shows 'en' format after Travis built it. ( I guess Linux & American )
So maybe it is relevant to timezone?

**Comment by sho918** [comment]
I had same issue.
In my case, install [`full-icu`](https://yarnpkg.com/en/package/full-icu) and running with `NODE_ICU_DATA` to solve this issue.

**Comment by YunYouJun** [comment]
@sho918 

Thanks for your suggestion.
I'm trying to review the source code to find the reason and a better way to solve it.

**Comment by juzi214032** [comment]
@YunYouJun  Did you find a solution?

**Comment by YunYouJun** [comment]
@juzi214032 

Use custom transformer like this:

```sh
yarn add -D dayjs
```

```js
// `docs/.vuepress/config.js`
const dayjs = require("dayjs");

module.exports = {
  plugins: {
    "@vuepress/last-updated": {
      transformer: (timestamp, lang) => {
        return dayjs(timestamp).format("YYYY-MM-DD HH:mm:ss");
      },
    },
  }
}
```

Then you will get `2020-02-07 02:18:57`.

**Comment by juzi214032** [comment]
ok thanks!
