### ISSUE TITLE
Build error with plugin

### ISSUE THREAD

**Issue by gluons** [vuejs/vuepress#1414]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Some of user [report error](https://github.com/gluons/vue-github-buttons/issues/14) from my component plugin for VuePress.  
I can't find solution to fix it. Maybe bug?

#### Version

`v1.0.0-alpha.42`

#### Steps to reproduce

Example repo: https://github.com/gluons/vuepress-issue-1414

#### What is expected?

Build complete without errors.

#### What is actually happening?

Get error from `vuepress build` but `vuepress dev` works perfectly.

![screenshot-vuepress-build](https://user-images.githubusercontent.com/4688092/53967351-ab996e80-4127-11e9-9b87-910dcf72f129.png)

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v10.15.1
- Browser version: -
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn 1.13.0
- Does this issue occur when all plugins are disabled? No

**Comment by YunYouJun** [comment]
Hello, I run the case.
```sh
yarn dev
```
But I get `Uncaught Error: Cannot find module 'vue-component-with-plugin'` in  console.

This plugin has been applied.
![image](https://user-images.githubusercontent.com/25154432/54007229-b2fa5f80-419b-11e9-8976-ef7ef8783072.png)

I guess something error in [vue-component-with-plugin/plugins/vuepress/index.js#L6](https://github.com/gluons/vuepress-issue-1414/blob/ad79ed559c4fc5f8dc6c58da95fc3913261ca84d/vue-component-with-plugin/plugins/vuepress/index.js#L6).

Maybe it doesn't know where to import from?

**Comment by gluons** [comment]
@YunYouJun Did you follow [Steps to repro](https://github.com/gluons/vuepress-issue-1414#steps-to-repro) in my repo?

```sh
cd vue-component-with-plugin
yarn
yarn build
cd ..
cd vuepress-project
yarn
yarn dev
```

It works without any error on my side.

![default](https://user-images.githubusercontent.com/4688092/54007529-e1287100-4194-11e9-8d3d-2e091919cd58.png)

**Comment by YunYouJun** [comment]
I delete it , then reproduce it. And it works. 😢 
I am sorry for my carelessness and helplessness.

**Comment by Shigma** [comment]
After many attempts, I found that using `require('../../vue-component-with-plugin/plugins/vuepress')` instead of `require('vue-component-with-plugin/plugins/vuepress')` may solve the problem.

However I still don't know what had caused the issue.

**Comment by Shigma** [comment]
Similar to #451. I believe it is a duplicate issue.

**Comment by Shigma** [comment]
@gluons You can use relative path to workaround this issue. Let's move to #451 to continue discussion.
