### ISSUE TITLE
Official Scaffolding Tool

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#1415]
It's time to kick off an official scaffolding tool called `create-vuepress` which helps us to generate following types of boilerplate:

- Docs 
- Plugin
- Blog
- Repro repo
- ...

**Comment by ulivz** [comment]
Consider starting development based on [kopy](https://github.com/saojs/kopy)?

//cc @egoist

**Comment by egoist** [comment]
Maybe you can use vue-cli for this?

**Comment by ulivz** [comment]
Sound good but `vue-cli` wasn't for pure scaffolding for now.

**Comment by kazupon** [comment]
You may consider nodepack. 😄
It’s still wip 😅
https://github.com/Akryum/nodepack
/cc @Akryum

**Comment by ulivz** [comment]
Just finished: https://github.com/ulivz/create-vuepress

You can use `yarn create vuepress` to launch a docs or blog website quickly.
