### ISSUE TITLE
feat: support json front matter

### ISSUE THREAD

**Issue by slathrop** [vuejs/vuepress#142]
## Similar to other SSGs ([Hugo](https://gohugo.io/content-management/front-matter/), etc.), add support in VuePress for JSON front matter (in addition to YAML and TOML [#141]).

- [ ] Select or write package equivalent to yaml-front-matter
  - Consider [`gray-matter`](https://www.npmjs.com/package/gray-matter)
- [ ] Add reference to /lib/prepare.js
- [ ] Complete Implementation
- [ ] Complete Testing

**Comment by yeedle** [comment]
Objects seem to work, am I missing something? The following works for me

```
---
...
foo: { bar: "baz" }
...
---
{{ $page.frontmatter.foo.bar }}
```

resolves to "baz" for me.

**Comment by yyx990803** [comment]
Closing and tracking together in #141
