### ISSUE TITLE
Please remove clearscreen from cli output

### ISSUE THREAD

**Issue by simbo** [vuejs/vuepress#1421]
First of all, I'm using vuepress since yesterday and got pretty far with this little website project I'm working on. I used a lot of different static site generators in the last years and you guys did an awesome job with vuepress. I love how you combined simplicity and extensibility!

Nevertheless, there's something that really annoys me... :)

## Feature request

Please stop sending a clearscreen ansi code when using the cli with `vuepress dev`.
This is such a bad user experience. Clearing the screen would be worth it, if there would be some fullscreen-benefiting output coming from the cli, but there isn't. Also, when you check the terminal output during development, you want to see the history of logs and not just the last line, so you always have to scroll up...
You did such a nice job with your cli log messages during startup and rebuild, why hide them at all...

#### What problem does this feature solve?

Improves cli user experience.

#### What does the proposed API look like?

No api changes needed.

(Maybe a `--clearscreen` flag for `vuepress dev` if you are in love with this feature and want to enable it, but imho you should just stay away from it...)

#### How should this be implemented in your opinion?

Just remove the clearscreen ansi code from the respective log output.

#### Are you willing to work on this yourself?**

Yes, I can create a PR. I just wanted to know, how you think about it, before I dig into this.

**Comment by ulivz** [comment]
Supported `--no-clear-screen` at e5f51de.
