### ISSUE TITLE
Vue Press dynamic heading not searchable rendered in component using interpolation

### ISSUE THREAD

**Issue by kims901** [vuejs/vuepress#1423]
Hi, 

I'm using default VuePress search, all the static headings are searchable but the headings rendered in vue component not searchable. 

I tried 2 different approaches, 

1. Add h2 in vue component:
<h2>{{prod.Name}} </h2>

2. Adding a slot in vue component and add heading using ### in markdown file
## {{prod.Name}}

both the appraoches didn't work, 

really appreciate your help on this issue. Thank you.

**Comment by ulivz** [comment]
All the dynamic headings will be resolved at client runtime but built-in search is based on data generated at build time.

**Comment by JStumpp** [comment]
@ulivz same Problem here. We render most of our content with components but the headings do not appear in the sidebar and search e.g. 
https://docs.movisens.com/movisensXS/mobile_sensing/#features-library-version-version

This is really problematic for us. I see two possibilities:
1. Is there an API where we can programmatically add headings during build time?
2. The headings are resolved at build time after ssr
I could help in implementing, if what you think is the best approach. Thanks!

**Comment by ptandler** [comment]
I ran into the same issue. I'd like to have an API I could use in Vue components to add headings during build time / ssr. Any news here?

I found a related question on stackoverflow: https://stackoverflow.com/questions/55328002/how-to-generate-headings-from-within-vue-components-in-vuepress
