### ISSUE TITLE
chokidar or inquirer clear the console...

### ISSUE THREAD

**Issue by f3ltron** [vuejs/vuepress#1428]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I am creation a plugin for vuepress. I want to debug it.

On mac all is good. But i am also working on windows and linux. When i run the npm run docs:dev it clear the console all the time after building.

#### Version
 "vuepress": "^1.0.0-alpha.42"

#### Steps to reproduce

npm run docs:dev

#### What is expected?

It should doesn't delete the console history so we can scroll back to it

#### What is actually happening?

delete everything

#### Other relevant information

- Your OS: linux mint xfce last version / windows 10
- Node.js version: v10.15.3
- Browser version: 
- Is this a global or local install? local
- Which package manager did you use for the install? npm
- Does this issue occur when all plugins are disabled?

**Comment by ulivz** [comment]
--debug
