### ISSUE TITLE
vuepress build fails - Module not found: Error: Can't resolve 'electron'

### ISSUE THREAD

**Issue by songololo** [vuejs/vuepress#1431]
- [x] I confirm that this is an issue rather than a question.

## Bug report
The dev server works fine.

But when building the following error (more below) is triggered:

`Module not found: Error: Can't resolve 'electron' in '.../node_modules/got'`

It seems to be related to `mapbox-gl`. The docs build fine if `electron` is added to `package.json`

#### Version
`"^1.0.0-alpha.44"`

#### Steps to reproduce

https://github.com/cityseer/vue-mapbox-map

#### What is expected?
Expected docs to build.

#### What is actually happening?
```
[3:49:19 PM] Compiling Client
[3:49:19 PM] Compiling Server
[3:49:24 PM] Compiled Server in 5s
[3:49:32 PM] Compiled Client in 13s
(undefined) ./node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in '/Users/gareth/dev/github/cityseer/vue-mapbox-map/node_modules/got'
resolve 'electron' in '/Users/gareth/dev/github/cityseer/vue-mapbox-map/node_modules/got'
  Parsed request is a module
  using description file: /Users/gareth/dev/github/cityseer/vue-mapbox-map/node_modules/got/package.json (relative path: .)
    resolve as module
      looking for modules in /Users/gareth/dev/github/cityseer/vue-mapbox-map/node_modules
        using description file: /Users/gareth/dev/github/cityseer/vue-mapbox-map/package.json (relative path: ./node_modules)
          using description file: /Users/gareth/dev/github/cityseer/vue-mapbox-map/package.json (relative path: ./node_modules/electron)
            no extension
...
 @ ./node_modules/got/index.js 91:20-39
 @ ./node_modules/@mapbox/mapbox-sdk/lib/node/node-layer.js
 @ ./node_modules/@mapbox/mapbox-sdk/lib/node/node-client.js
 @ ./node_modules/@mapbox/mapbox-sdk/lib/client.js
 @ ./node_modules/@mapbox/mapbox-sdk/services/service-helpers/create-service-factory.js
 @ ./node_modules/@mapbox/mapbox-sdk/services/geocoding.js
 @ ./node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/VueMapboxMap.vue?vue&type=script&lang=js&
 @ ./src/VueMapboxMap.vue?vue&type=script&lang=js&
 @ ./src/VueMapboxMap.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./docs/.vuepress/components/Demo.vue?vue&type=script&lang=js&
 @ ./docs/.vuepress/components/Demo.vue?vue&type=script&lang=js&
 @ ./docs/.vuepress/components/Demo.vue
 @ ./node_modules/@vuepress/core/.temp/app-enhancers/global-components-1.js
 @ ./node_modules/@vuepress/core/.temp/internal/app-enhancers.js
 @ ./node_modules/@vuepress/core/lib/client/app.js
 @ ./node_modules/@vuepress/core/lib/client/serverEntry.js
 @ multi ./node_modules/@vuepress/core/lib/client/serverEntry.js

```

#### Other relevant information

- Your OS: Mac 10.14.3
- Node.js version: v11.10.0
- Browser version: Chrome Version 72.0.3626.121
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn
- Does this issue occur when all plugins are disabled? No plugins used.

**Comment by ulivz** [comment]
Sorry but I cannot reproduced your error mentioned in your repro, I recommend that you create a minimal and valid repro. 🙂 

![image](https://user-images.githubusercontent.com/23133919/54222628-bf324400-4530-11e9-80ac-e31e1e16d8c6.png)

**Comment by songololo** [comment]
@ulivz I currently have `electron` installed in order to avoid the problem, so if running `yarn remove electron` then the error is likely to occur.

**Comment by Shigma** [comment]
@songololo If your problem can be reproduced and is indeed an issue of VuePress, we will always be happy to help.

**Comment by songololo** [comment]
@Shigma I've set the repository back to using dynamic imports.

It works at present because I've added the `electron` package to dev dependencies, so to reproduce the issue:

```
yarn remove electron
yarn run docs:build
```

It seems to be related to dynamic imports of `mapboxgl` which clashes for some reason with the `webpack` config for Vuepress' build step. (It works fine for dev server.)
