### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by GongJS** [vuejs/vuepress#1434]
## Bug report
ReferenceError:  global is not defined

#### Version
0.14.0

#### Steps to reproduce
so i  install the modules -  `file-saver`,but when i import it in my project, the chrome throw the error:
`global is not defined`

i import it like this:
`import FileSaver from 'file-saver'
`
#
![image](https://user-images.githubusercontent.com/25744301/54270296-13353b00-45ba-11e9-984c-410ac18fd863.png)
### What is expected?
i hope i can use the file-saver normaly;

#### What is actually happening?
it doesn't work

#### Other relevant information

- Your OS: mac
- Node.js version: 10.0
- Browser version: 
- Is this a global or local install?
 yarn add file-saver
- Which package manager did you use for the install?
yarn
- Does this issue occur when all plugins are disabled?
no

**Comment by ulivz** [comment]
You're using a node module at client code...

**Comment by lilisako** [comment]
How did you solve this? I'm having a same issue...

**Comment by ChucKN0risK** [comment]
I'm also having this issue while trying to use [swagger-js](https://github.com/swagger-api/swagger-js):

```vue
<template>
  <div>
    {{ text }}
    <Content />
  </div>
</template>

<script>
  import Swagger from 'swagger-client';

  export default {
    data() {
      return {
        text: 'Test textttt'
      };
    },
    async created() {
      console.log(await Swagger.resolve({
        url: 'http://petstore.swagger.io/v2/swagger.json'
      }));
    },
  };
</script>
```

**Comment by salazarr-js** [comment]
I have been trying to use `axios` and `cheerio` in a component but just have the same error message

```
[Vue warn]: Failed to resolve async component: function () {
  return Promise.all(/*! import() */[__webpack_require__.e(0), __webpack_require__.e(2)]).then(__webpack_require__.bind(null, /*! ./notes/.vuepress/components/Bookmark */ "./notes/.vuepress/components/Bookmark.vue"));
}
Reason: ReferenceError: global is not defined
```
Is just a simple implementation
```javascript
import axios from 'axios';
import cheerio from 'cheerio';

export default {
  props: {
    url: { type: String, required: true }
  },
  mounted:() {
    axios.get(this.url)
    .then(response => {
      const html = response.data;
      let $ = cheerio.load(html);

      ...
    });
  }
}
```

**Comment by bougieL** [comment]
Seems error appears when use npm library in global components

**Comment by 13632225945** [comment]
i'm having a same trouble

**Comment by superhos** [comment]
I'm in the same trouble. And sure I am importing a client components.
Any suggestion?

**Comment by cdauth** [comment]
I'm having the same problem and really don't understand what's going on.

I managed to build a workaround for it by using `window.global = window` in `enhanceApp.js`. However, since this has to run before the imports, I have to use `require` instead of `import`:

```javascript
window.global = window;
const qrcode = require("vue-qrcode").default;
```
