### ISSUE TITLE
refresh 404

### ISSUE THREAD

**Issue by lhz960904** [vuejs/vuepress#1435]
- [x] I confirm that this is an issue rather than a question.

#### Version
^1.0.0-alpha.44

#### Steps to reproduce
 after build, deployed to GitHub page, I can goTo a page by clicking, but refresh at the current page, it 
 will redirect 404

#### What is expected?

it should refresh the page

#### What is actually happening?

redirect 404

#### Other relevant information
[site - homepage](https://ihaoze.me/) 
[site - page detail](https://ihaoze.me/_posts/throttling-and-debouncing.html)   it will not found

error msg: ![](https://imgcdn.meizhuahuyu.com/1552472600516.jpg)

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?
- Does this issue occur when all plugins are disabled?

**Comment by Shigma** [comment]
I would like to know the details about your website. Can you provide a reproduction repo or fill in the form in the issue template?

It seems a SSR mismatch issue (#1382). If it is, you can try this [plugin](https://github.com/Shigma/vuepress-plugin-ssr-mismatch-workaround).

**Comment by lhz960904** [comment]
> I would like to know the details about your website. Can you provide a reproduction repo or fill in the form in the issue template?
> 
> It seems a SSR mismatch issue (#1382). If it is, you can try this [plugin](https://github.com/Shigma/vuepress-plugin-ssr-mismatch-workaround).

thanks, this plugin resolve my problem! 😁
