### ISSUE TITLE
Error on sub-pages in dev-mode

### ISSUE THREAD

**Issue by peXed** [vuejs/vuepress#144]
Hello!

I followed the guid but always get the following error as soon as I create a subsite (in a subfolder) and try to open it.

`Error in render: "TypeError: Cannot read property 'path' of undefined"`

I looked into the issue and it seems the $page variable doesn't get set correctly, before the Content-Component gets inserted.
With the default theme, you get a slightly different error:

`Error in render:  "TypeError: Cannot read property 'frontmatter' of undefined"`

If I build the project, everything works great and the output looks correct.

I'm on Windows 10.

Here is a small test repo: https://github.com/peXed/vuepress-test

**Comment by yyx990803** [comment]
This is probably because the underlying file watching is slow or is not catching the newly created files on Windows. Unfortunately you'll probably have to restart the dev server in this case.

**Comment by peXed** [comment]
Thanks for the fast reply.

Even restarting the dev server is not fixing the issue (I also tried to run the process as administrator).
