### ISSUE TITLE
Ability to fetch page content HTML via AJAX

### ISSUE THREAD

**Issue by rubenduiveman** [vuejs/vuepress#1445]
## Feature request
I'd like to be able to load a page content HTML via AJAX.

#### What problem does this feature solve?
I'm writing a component that auto-loads the next page of a certain category (subfolder) when the user hits the bottom of the page. The only thing I can do now is GETting a page, but a minimal unhydrated html is returned (which is great for virtually all other use cases, so thumbs up!). However, there is no way for me to fetch the page content via AJAX for me to append to the DOM myself.

#### What does the proposed API look like?
- The first option that comes to mind is exposing an endpoint like `[root]/_api/pages/` where a GET request could be fired to, based on the `path` of the page, like `GET [root]/_api/pages?path=theme/writing-a-theme.html`. Downside to this is that `[root]/_api/` would be a reserved path.
- Another option would be to generate a `page.content.html` besides every page. So there's `[root]/theme/writing-a-theme.html` and `[root]/theme/writing-a-theme.content.html`. This page should probably contain a `robots` meta tag to prevent indexing by search engines.

#### How should this be implemented in your opinion?
I'm thinking this sould be a plugin, since it's not a common use case.

#### Are you willing to work on this yourself?
I'd like to give it a go, sure. Just need an introduction to the codebase first :).

**Comment by ulivz** [comment]
You can using built-in [\<Content />](https://v1.vuepress.vuejs.org/guide/using-vue.html#content) component. Only when you use this component will the page's content be loaded.

**Comment by rubenduiveman** [comment]
Works!
