### ISSUE TITLE
v1.0 use a theme report an error

### ISSUE THREAD

**Issue by paocaijun** [vuejs/vuepress#1447]
[x]

- [x] I confirm that this is an issue rather than a question.

#### What is expected?
Using a theme from a dependency. then in config.js  {... theme:"yubisaki"...} 
vuepress v1.0.0  &&  vuepress-theme- yubisaki

#### What is actually happening?
![image](https://user-images.githubusercontent.com/24297271/54346554-3fb38a80-4680-11e9-9e7e-e626a9215966.png)

#### Other relevant information

- Your OS: window 10
- Node.js version: v8.13.0
- Browser version: google  67.0.3396.87
- Is this a global or local install?  global
- Which package manager did you use for the install? npm 
- Does this issue occur when all plugins are disabled? yeah

**Comment by Shigma** [comment]
This is an issue of [vuepress-theme-yubisaki](https://github.com/Yubisaki/vuepress-theme-yubisaki). `package.json` should contain a `main` entry.

See: https://github.com/Yubisaki/vuepress-theme-yubisaki/blob/master/package.json

@Bloss

**Comment by paocaijun** [comment]
yeah,thanks

**Comment by paocaijun** [comment]
> This is an issue of [vuepress-theme-yubisaki](https://github.com/Yubisaki/vuepress-theme-yubisaki). `package.json` should contain a `main` entry.
> 
> See: https://github.com/Yubisaki/vuepress-theme-yubisaki/blob/master/package.json
> yeah.thanks
> @Bloss
