### ISSUE TITLE
VuePress dev Does not run server on MacOs

### ISSUE THREAD

**Issue by Porya200** [vuejs/vuepress#1454]
Hi , my server Does not run in macOs 

> $ vuepress dev
> -bash: vuepress: command not found

I did all this 👍 
```
npm install -g vuepress
echo '# Hello VuePress' > README.md
```

- My OS: macOs 10.14.13
- Node.js version: v11.12.0
- NPM version: 6.7.0
- VuePress version : 0.14.10

**Comment by ulivz** [comment]
If you think about it carefully, you should know that this is not a issue of VuePress.

You can re-install VuePress and retry it.

**Comment by timaschew** [comment]
install it locally and then try to run `node_modules/.bin/vuepress dev`

**Comment by ZakLiml** [comment]
I have encountered it in mac too and it seems missing bin folder. It's that a bug?

**Comment by ZakLiml** [comment]
While I choose yarn instand of npm and then run command `yarn global add vuepress`, it works @Porya200
