### ISSUE TITLE
Unable to inject CSS using module.exports? 

### ISSUE THREAD

**Issue by irontribe** [vuejs/vuepress#1456]
My goal is to be able to use Github Pages AND VuePress at the same time. Github Pages expects style sheets to be in /assets/css/, so I'm trying this. Note I tried both .scss and .css just to be sure. Neither gets loaded, even though the files are obviously in the /assets/css/ directory. Can someone help me with this?

```
module.exports = {                                                                                                                    
  head: [                                                                                                                             
        ['link', {rel: 'stylesheet', type: 'text/css', href: '/assets/css/style.scss'}],                                              
        ['link', {rel: 'stylesheet', type: 'text/css', href: '/assets/css/foo.css'}]                                                  
    ]                                                                                                                                 
}                                                                                                                                     
 
```

**Comment by Shigma** [comment]
Well I tried, and it works.

Did you place your css files under `.vuepress/public/assets/css` folder?

**Comment by ulivz** [comment]
BTW, please following issue guidelines and DO NOT delete issue template. 🙁

**Comment by Shigma** [comment]
We're closing this issue as stale as it's more than 2 weeks without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
