### ISSUE TITLE
serverPrefetch not called in dev

### ISSUE THREAD

**Issue by mathieutu** [vuejs/vuepress#1458]
- [x] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.44
#### Steps to reproduce

I have a `serverPrefetch` method in a component.
When building dist, the method is properly called and the component work.

When using dev server, the method seems to be not called.

```js
async serverPrefetch() {
    this.foo = await fetchData();
  },
```

Thanks.
Matt'

**Comment by mathieutu** [comment]
Actually, I'm seeing that even if the method is called during the build, the `foo` data is emptied when the app load. I probably missed something and will investigate further.

**Comment by ulivz** [comment]
`serverPrefetch` was added in Vue@2.6+ but VuePress is powered by Vue@2.5+.

**Comment by mathieutu** [comment]
@ulivz You should not have read my previous messages, as you would know that it works.

Moreover, sorry to tell you that but actually **vuepress is running `vue@2.6.9`**, which is quite normal as it is requested as `"vue": "^2.5.16",` in https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/package.json#L57

**Comment by ulivz** [comment]
Also sorry to tell you:

![image](https://user-images.githubusercontent.com/23133919/54542561-f85a3080-49d6-11e9-8c0b-e0aa0dbeb4d9.png)

ref: https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components

**Comment by mathieutu** [comment]
Yeah, I know that, this is **server** prefetching 🤷‍♂️ . 
Are you saying that the dev server isn't doing any ssr at all?

I'm sorry but I totally don't understand what's going on here: firstly the wrong version response, and now this screenshot. Am I missing something? I'm sorry if I did or wrote something that bothered you. 🤔 

Here what I'm trying to do is to make some calls only on server side, and not client side. It seems to work with build phase, but not dev one.
