### ISSUE TITLE
Does themeConfig.docsDir serve any purpose other than for GitHub?

### ISSUE THREAD

**Issue by tomcam** [vuejs/vuepress#147]
I am uncertain about the purpose of themeConfig.docsDir. I searched the source and still don't quite get it. It seems to be a way to choose a docs directory for GitHub Pages. I thought it might be a way to establish a root directory for markdown files, so that if you set themeConfig.docsDir to `docs` and put the file `foo.md` into the `/docs` directory, it would be referenced as `[Foo](foo.md)` and not `[Foo](/docs/foo.md)`.

Am I just making up this notion of a root document directory? Thanks.

**Comment by yyx990803** [comment]
No, it's only used for generating the correct github edit link.

**Comment by tomcam** [comment]
LOVE VuePress. Thanks tons.
