### ISSUE TITLE
vuepress build "failed to compile with errors."

### ISSUE THREAD

**Issue by DRD161** [vuejs/vuepress#1483]
When following the instructions to install and build (yarn add vuepress@next -D and vuepress build) I keep getting the following error during the build process: **Error: Failed to compile with errors** (See screen shot below for full error report) I'm sure I'm doing something wrong but I'm not sure what. I'm relatively new to Vue and open source so forgive my ignorance :/
I'd like to get this settled so I can contribute! Thanks for any help in advance!

<img width="1680" alt="Screen Shot 2019-03-27 at 10 12 41 AM" src="https://user-images.githubusercontent.com/29187448/55083315-b5085d80-5079-11e9-976f-5ed487a22fe7.png">

**Comment by timaschew** [comment]
Please provide the full log as text (no screenshot).

**Comment by DRD161** [comment]
I figured out part of the problem. In the README.md file it says to run yarn dev but the yarn documentation says to use yarn --dev. I tried that and the error went away.

**Comment by SanGongHappy** [comment]
I encountered the same issue, and it was resolved when I downgraded my npm version to 16.
