### ISSUE TITLE
plugin-last-updated transformer option not working

### ISSUE THREAD

**Issue by chhpt** [vuejs/vuepress#1487]
- [x] I confirm that this is an issue rather than a question.

#### Version

- vuepress: 1.0.0-alpha.44
- theme-default: 1.0.0-alpha.0

#### Steps to reproduce

[see the repo](https://github.com/chhpt/vuepress-report)

#### What is expected?

```js
'@vuepress/last-updated': {
    transformer(timestamp) {
        const time = dayjs(timestamp).format('YYYY-MM-DD HH:mm:ss');
        return time;
    }
}
```

I use dayjs to format the last updated time. It should be like YYYY-MM-DD HH:mm:ss , but it be like 3/28/2019, 4:25:12 PM.

#### What is actually happening?

transformer not working

#### Other relevant information

- Your OS: macOS 10.14.3
- Node.js version: 8.11.4
- Browser version: Chrome 73.0.3683.86
- Is this a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled?

**Comment by Shigma** [comment]
Does it happen only in build or in both dev and build?

**Comment by chhpt** [comment]
@Shigma It happen in both dev and build stage.

**Comment by ulivz** [comment]
`theme-default: 1.0.0-alpha.0`? Please install the newest version same as vuepress.
