### ISSUE TITLE
activeHeaderLinks config don't work in alpha release

### ISSUE THREAD

**Issue by oott123** [vuejs/vuepress#1488]
- [x] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.44

#### Steps to reproduce

create `.vuepress/config.js`:

```js
module.exports = {
  themeConfig: {
    activeHeaderLinks: false,
    sidebar: 'auto',
  }
}
```

and add some docs with headers. Scroll and look at the url. Url is changing regardless of you set it to true or false.

#### What is expected?

Url is not change when you set `activeHeaderLinks` to false

#### What is actually happening?

Url is change when you set it to false

#### Other relevant information

- Your OS: macOS 10.14.3
- Node.js version: v8.12.0
- Browser version:  Google Chrome | 73.0.3683.86
- Is this a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled? actually is the bug in the default theme which enabled @vuepress/plugin-active-header-links by default.

**Comment by Shigma** [comment]
Fixed at #1508.
