### ISSUE TITLE
Installing vuepress breaks project build

### ISSUE THREAD

**Issue by matsp** [vuejs/vuepress#150]
After installing vuepress as dev dependency the build of my project is broken.

I've got the same error in vuepress build and my own webpack based build:

*vuepress*
```shell
Error: Module build failed: TypeError: Cannot read property 'transforms' of null
```

*my lib*
```shell
ERROR in ./components/typography/Typography.vue (./node_modules/buble-loader!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./components/typography/Typography.vue)
Module build failed: TypeError: Cannot read property 'transforms' of null
    at Object.module.exports (/home/mp/development/material-components-vue/node_modules/buble-loader/index.js:18:47)
```

In my own lib I'm using babel-loader but since installing vuepress I've got errors from buble-loader...

Reproduction:

*vuepress*
1. Clone https://github.com/matsp/material-components-vue
2. Checkout chore/docs/vuepress branch
3. Execute yarn && yarn docs:dev

*my lib*
1. Clone https://github.com/matsp/material-components-vue
2. Checkout chore/docs/vuepress branch
3. Execute yarn && yarn build:lib

**Comment by dacsang97** [comment]
I think you should you `enhanceApp.js` in `.vuepress` to use `Vue.use()`.
_
Sample **enhanceApp.js**
``` js
import Button from "../../components/button";

export default ({
  Vue, // the version of Vue being used in the VuePress app
  options, // the options for the root Vue instance
  router // the router instance for the app
}) => {
  Vue.use(Button);
};
```

**Comment by matsp** [comment]
Thanks for the tip!

I will try it out, but this could only fix vuepress. 

Vuepress seems to introduce dependencies that break my webpack based build.

**Comment by dacsang97** [comment]
Update your **webpack.config** for `vue-loader`. 
I find it in **webpack.config.lib.common**
``` js
rules: [
      {
        test: /\.vue$/,
        loader: "vue-loader",
        options: {
          loaders: {
            js: "babel-loader"
          }
        }
      }
     ...
]
```

**Comment by matsp** [comment]
>When vue-loader detects the presence of babel-loader or buble-loader in the same project, it will use them to process the <script>parts of all *.vue files, allowing us to use ES2015 in our Vue components.

Shouldn't be necessary to set this. And it worked before..

**Comment by matsp** [comment]
Found the issue. Vuepress installs buble-loader and the vue-loader defaults to buble when both are detected.

So you are right to explicitly use babel-loader when both are installed.

**Comment by MwumLi** [comment]
解决办法有两个:
1. 使用 `yarn` 安装依赖会解决此问题
2. 为 vue-loader 指定 `babel-loader` 作为处理 js 的 loader

**原因**:  `npm` 和 `yarn` 安装依赖策略不一致，在加上 `vue-loader` 不添加任何选项默认使用 `buble-loader` 会有问题  

**具体分析**:  
下图是 vue-loader 选择解析 js 的 loader 的判断: 
![image](https://user-images.githubusercontent.com/6889433/40041469-a314b424-5850-11e8-89cb-980e255291ef.png)
可以看到优先使用 `buble-loader`, 在找不到的情况下, 使用 `babel-loader`, 而 vuepress 依赖 `buble-loader`, 使用 `npm` 和 `yarn` 安装依赖会有不同的效果:  
 
* npm 安装依赖: `buble-loader` 会被安装在外层 node_modules, 这个时候 `vue-loader` 当然使用 `buble-loader` 去处理 js, 因为直接使用 `buble-loader` 会有问题, 所以报错  
* yarn 安装依赖, `buble-loader` 被安装在 `vuepress` 自身的  `node_modules/` 下, 所以 `vue-loader` 使用的是 `babel-loader` 所以没问题
