### ISSUE TITLE
Handle SSR in dev mode

### ISSUE THREAD

**Issue by mathieutu** [vuejs/vuepress#1500]
#### What problem does this feature solve?

In dev mode, Server Side rendering functions can't be used.
It forces to re-build the bundle each time (I've personally set a nodemon, but it isn't convenient at all) and serve the generated html file with a server.

I propose to handle ssr part in dev server too, like @Akryum did in https://github.com/Akryum/vue-cli-plugin-ssr

#### Are you willing to work on this yourself?
I could, if needed, and if I can be useful!

**Comment by ulivz** [comment]
Thanks for the interest in VuePress, but as you mentioned above, SSR under dev at vue-cli is also supported via a plugin, so you can try to create a plugin by yourself. feel free to create pull request if current plugin api cannot satisfy you.

**Comment by mathieutu** [comment]
@ulivz unlike vuepress, the server side part isn't a core and main feature of vue-cli. It's why it needs a plugin for that. However, Vuepress is using server compilation for any build, and this is its strengh: "Static Site Generator" are the first words you can see on the project website. 

For now there is a inconstancy in the vuepress process. 
The build part is using the server side, the dev is not. For me, it can even be considerate as a bug, as the behavior are both different.

A optional plugin to "fix" that is in my opinion a bad idea.

**Comment by hypeJunction** [comment]
I must agree with @mathieutu. I keep running into issues during the build process, which don't occur in dev mode. It would help if those errors were throw in dev mode and not revealed with some useless error message during the build step. It takes effort to debug build failures that don't have any trace information.
