### ISSUE TITLE
Site config base will always get / (bug in v1.0.0-alpha.46)

### ISSUE THREAD

**Issue by afeiship** [vuejs/vuepress#1503]
// routerBase will always get '/'
- version: v1.0.0-alpha.44 is `correct`
- version: v1.0.0-alpha.46 is `wrong`

```js
// @vuepress/core/lib/client/app.js
export function createApp (isServer) {
  const routerBase = typeof window !== 'undefined'
    ? window.__VUEPRESS_ROUTER_BASE__
    : (siteData.routerBase || siteData.base)

  const router = new Router({
    base: routerBase,
```

**Comment by timaschew** [comment]
With version v1.0.0-alpha.44 I was using `base` in my config which has worked.
Now in version v1.0.0-alpha.46 it doesn't work anymore, I get a 404 if I want to access the url which is specified via `base`. But the page works if I manually open `/`.

**Comment by timaschew** [comment]
For anyone else: to fix this you need to downgrade not vuepress itself, but the core:

`npm i @vuepress/core@1.0.0-alpha.44`

**Comment by afeiship** [comment]
@timaschew thanks!

**Comment by Shigma** [comment]
@ulivz 

Can you look into this regression?

**Comment by ulivz** [comment]
Why did you always get `/`?
