### ISSUE TITLE
执行打包命令后，index文件引入js或者css文件是绝对路径/开头，如何配置成相对路径./

### ISSUE THREAD

**Issue by keer6** [vuejs/vuepress#1506]
![Snipaste_2019-04-02_14-26-58](https://user-images.githubusercontent.com/33250972/55380644-63694280-5553-11e9-945e-9b5782c32f8e.png)
如图

**Comment by Shigma** [comment]
目前暂不支持。当然我们不排除以后支持的可能性。已经有类似的 issue 了。

PS：请不要删除 issue template，谢谢！
