### ISSUE TITLE
Links to improve documentation follow improper path through Github

### ISSUE THREAD

**Issue by siddhartha-crypto** [vuejs/vuepress#1512]
#### What problem does this feature solve?

When a user clicks on the "Improve this page on Github" link, they are directed to the Github page where the error is found. 

The user then edits the page and, according to the Github UI, clicks "Propose Change."

From there, the user can also submit a Pull Request, based on this proposal. All of this happens automatically in the Github UI.

The problem is that a user may not realize that the Github project they are attempting to improve may have a formal Pull Request process, such as here, on Vuepress. 

The formal process may include a request from the team to check boxes giving information about the Pull Request specifics.

The user has thus submitted a PR incorrectly, and the project owner is likely to reject the proposal, making this a waste of time, and if the owner does not take time to properly explain, the user will not even know why the request was rejected.. 

This has happened to me on a few separate occasions.

Users get lost while trying to make improvements to doc pages, and can end up improperly submitting requests.

#### How should this be implemented in your opinion?
Instead, what should happen is that the link to "Improve this page on Github" should lead to a page that walks the user through the process of properly submitting a pull request, and provide a link to the correct page for editing.

Perhaps this is a task for those who utilize Vuepress to consider, but as this has happened to me a few times, I would imagine that automating this would be better. 

#### Are you willing to work on this yourself?

Perhaps! I do use Vuepress daily for work, and I could probably help here.

**Comment by timaschew** [comment]
I don't understand what the problem is.

> The formal process may include a request from the team to check boxes giving information about the Pull Request specifics.

What do you exactly mean with that?
When you creating the Pull Request the correct template is used and pre filled in the description of the Pull Request. What do you expect exactly?

> Instead, what should happen is that the link to "Improve this page on Github" should lead to a page that walks the user through the process of properly submitting a pull request, and provide a link to the correct page for editing.

So you talking about to link to the CONTRIBUTING.md or something like that? I disagree with that.  It should be enough to add a CONTRIBUTING.md, so that a hint is shown when creating issues. For Pull Request the CONTRIBUTING.md can be just linked within the template.

**Comment by siddhartha-crypto** [comment]
> When you creating the Pull Request the correct template is used and pre filled in the description of the Pull Request. What do you expect exactly?

This is incorrect. 

When you go to make a pull request via the default link path, no template is ever seen. 

If there is a way to make the Github GUI show it, I'm not aware of what that is.

The only way I have found to make the Github GUI show the template is to first fork the repository, make the changes on your own fork, then submit the pull request. 

If you try to do the proposal for changes following what Vuepress leads the user into doing, you won't see the template.
