### ISSUE TITLE
When base set, homepage shows 404

### ISSUE THREAD

**Issue by intijk** [vuejs/vuepress#1519]
- [x] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.46

#### Steps to reproduce
git clone git@github.com:intijk/vuetest.git
cd vuetest
yarn install
npx vuepress dev docs

#### What is expected?
Should display home webpage with 123

#### What is actually happening?
Display 404 information

#### Other relevant information

- Your OS: 

System:    Host: logica Kernel: 4.15.0-47-generic x86_64 bits: 64
           Desktop: Gnome 3.28.3 Distro: Ubuntu 18.04.2 LTS

- Node.js version: 
~$ node --version
v10.15.3

- Browser version: 
Firefox 66.0.2

- Is this a global or local install? 
local

- Which package manager did you use for the install?
yarn

- Does this issue occur when all plugins are disabled?
Non plugins are used.

**Comment by intijk** [comment]
By the way, when use 0.x vuepress, it works.

**Comment by Shigma** [comment]
It's a regression of `vuepress 1.0.0-alpha.46`. Fixed at 9fba54931c80bab6b0ab7a446ca97687342baf7d.

Now you can wait for the release of `vuepress 1.0.0-alpha.47` 🤣
