### ISSUE TITLE
General redirects from old urls to new ones

### ISSUE THREAD

**Issue by gcharang** [vuejs/vuepress#1520]
## Feature request

A way to redirect an older url to an existing url in the current site structure. 
Example:
Old link: `https://docs.examplesite.com/intro/basics.html` to be redirected to 
New Link: `https://docs.examplesite.com/start-here/introduction.html` 

The absence of a straightforward way to do this has been discussed in Issue #160   

#### What problem does this feature solve?

When reorganizing the directory structure as well as changing the names of files and directories, this feature is useful to not break the existing bookmarks and links from other websites.

The plugin [vuepress-plugin-redirect](https://vuepress.github.io/en/plugins/redirect/) exists but it is only useful for a subset of redirects where "redirecting any page to its subpages" is needed. 

#### What does the proposed API look like?

I would suggest requiring a file like https://github.com/vuejs/vue-router/blob/dev/docs/.vuepress/public/_redirects which contains the old and new links side by side or as an array of JSONs. The plugin should read the file to generate the redirects.

#### How should this be implemented in your opinion?

I am not sure, but the redirects in the above-linked file are working in the `vue-router`'s website: `https://router.vuejs.org/`
Ex: https://router.vuejs.org/en/essentials/getting-started.html
properly gets redirected to
https://router.vuejs.org/guide/

#### Are you willing to work on this yourself?

I am a newbie to JS and Vue, happily using vuepress to create documentation like: https://developers.komodoplatform.com/

But, @Shigma [suggested](https://github.com/vuejs/vuepress/issues/160#issuecomment-479844330) they were considering to support this feature in the plugin [vuepress-plugin-redirect](https://vuepress.github.io/en/plugins/redirect/)

**Comment by Shigma** [comment]
> But, @Shigma suggested they were considering to support this feature in the plugin vuepress-plugin-redirect

So you had better open an issue there instead of here.

Actually VuePress is not going to support such features cause they can be easily realized by a plugin......

**Comment by gcharang** [comment]
Ah, sorry. Didn't realize the difference. Will open the feature request in its repo.
