### ISSUE TITLE
vuepress dev <projectDir> goes ahead even if the directory doesn't exist

### ISSUE THREAD

**Issue by open-source-explorer** [vuejs/vuepress#1521]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?

`vuepress dev <directory>` should show an appropriate warning if the directory doesn't exist.

#### What is actually happening?

The default template is being served.

System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 66.0.2

**Comment by open-source-explorer** [comment]
@ulivz Your thoughts?

**Comment by ulivz** [comment]
Maybe we should emit warning instead of an error since a VuePress application can be all composed with dynamic [`additionalPages`](https://v1.vuepress.vuejs.org/plugin/option-api.html#additionalpages).

**Comment by ulivz** [comment]
Updated at https://github.com/vuejs/vuepress/commit/6da9a5f112fae442ca26b14374d18ca560769053
