### ISSUE TITLE
Index.styl is not injected at the end of the style bundle

### ISSUE THREAD

**Issue by Slashgear** [vuejs/vuepress#1523]
- [x] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.46

#### Steps to reproduce

Try to override `body` background color in index.styl file.
For example,
```css
body {
  background-color: black;
}
```

The body will use default theme and won't be black.

#### What is expected?
Custom style in injected at the end of style bundle

#### What is actually happening?
Style is injected at the beginning of the bundle, so there is no way to override defaut theme.
😭 
#### Other relevant information

- Your OS: MacOs 10.14.4
- Node.js version: 10.15
- Browser version: Safari 12.1
- Is this a global or local install? local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled? no

**Comment by ulivz** [comment]
Fixed at https://github.com/vuejs/vuepress/commit/dabf506022978ecf5101ff49cc9de1776a552ab5
