### ISSUE TITLE
redirect to 404 page in production,need help~~

### ISSUE THREAD

**Issue by 34678** [vuejs/vuepress#1526]
- [ ] I confirm that this is an issue rather than a question.

#### Version
0.14.10
#### Steps to reproduce
i run the project locally and  visit http://localhost:8080/, its normal.
when i deploy on server , i visit my page by www.xxx.com/xxx/xxxx/index.html
and i console log the router
path is /xxx/xxxx/index.html
so the component didnt exsit ! 
then i saw 404
i need help 
how should i config my vue-router??

#### What is expected?
show me normal page~
#### What is actually happening?
show me 404 page
#### Other relevant information
none~
- Your OS:  mac 10.13.6
- Node.js version:  8.x.x
- Browser version:  chrome
- Is this a global or local install? locally
- Which package manager did you use for the install?npm
- Does this issue occur when all plugins are disabled? yep?

**Comment by timaschew** [comment]
This not really helpful. Visit localhost:8080 without providing a repository is useless.  
BTW: you are not using the latest stable version. You should update to version 0.14.15

**Comment by 34678** [comment]
> This not really helpful. Visit localhost:8080 without providing a repository is useless.
> BTW: you are not using the latest stable version. You should update to version 0.14.15

thx  i will try the latest version
btw  my problem is on dev server  ,not localhost~~~~

**Comment by timaschew** [comment]
> btw my problem is on dev server ,not localhost~~~~

If you can't reproduce the problem locally with `vuepress build` command it's not related to VuePress.

Nobody can help you if you don't explain which commands, config and code you've used.

**Comment by 34678** [comment]
> > btw my problem is on dev server ,not localhost~~~~
> 
> If you can't reproduce the problem locally with `vuepress build` command it's not related to VuePress.
> 
> Nobody can help you if you don't explain which commands, config and code you've used.

thx ，i solved this problem by set config.base = '/xxx/xxx/index.html'
(my website is www.xxx.com/xxx/xxx/xxx/index.html)~
