### ISSUE TITLE
back-to-top

### ISSUE THREAD

**Issue by qiufeihong2018** [vuejs/vuepress#1532]
- [x] I confirm that this is an issue rather than a question.

#### Other relevant information

- Your OS:
 ubuntu16.04
- Node.js version:
 v11.2.0
- Browser version: 
Version 73.0.3683.86 (Official Build) (64-bit)
- Is this a global or local install? 
global
- Which package manager did you use for the install? 
npm install -D @vuepress/plugin-back-to-top@next

- Does this issue occur when all plugins are disabled?
According to the official website configuration, it cannot take effect

**Comment by timaschew** [comment]
Why you're install it globally?  
I don't think it's designed to work that way.

**Comment by daltondiaz** [comment]
What's the bug? Please write more information. I use the plugin back to top in dev dependencies too. 

My package.json

```
{
  "name": "nfs-docs-vuepress",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "keywords": [],
  "author": "daltondiaz",
  "license": "MIT",
  "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.44",
    "vuepress": "1.0.0-alpha.44"
  }
```


This tutorial works well [install plugin back to top](https://v1.vuepress.vuejs.org/plugin/official/plugin-back-to-top.html#install)

**Comment by qiufeihong2018** [comment]
{
  "name": "vuepress-blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "vuepress dev docs",
    "build": "vuepress build docs",
    "server": "npm run build && pm2 start blog.js",
    "d": "bash deploy.sh"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "element-ui": "^2.5.4",
    "express": "^4.16.4",
    "leancloud-storage": "^3.12.0",
    "pm2": "^3.2.9",
    "valine": "^1.3.4",
    "vuepress": "^0.14.9"
  },
  "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.47",
    "vuepress-plugin-demo-block": "^0.7.2"
  }
}


> What's the bug? Please write more information. I use the plugin back to top in dev dependencies too and Ubuntu 18.04.2 LTS .
> 
> My package.json
> 
> ```
> {
>   "name": "nfs-docs-vuepress",
>   "version": "1.0.0",
>   "description": "",
>   "scripts": {
>     "docs:dev": "vuepress dev docs",
>     "docs:build": "vuepress build docs"
>   },
>   "keywords": [],
>   "author": "daltondiaz",
>   "license": "MIT",
>   "devDependencies": {
>     "@vuepress/plugin-back-to-top": "^1.0.0-alpha.44",
>     "vuepress": "1.0.0-alpha.44"
>   }
> ```
> This tutorial works well [install plugin back to top](https://v1.vuepress.vuejs.org/plugin/official/plugin-back-to-top.html#install)

it's my package.json
{
  "name": "vuepress-blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "vuepress dev docs",
    "build": "vuepress build docs",
    "server": "npm run build && pm2 start blog.js",
    "d": "bash deploy.sh"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "element-ui": "^2.5.4",
    "express": "^4.16.4",
    "leancloud-storage": "^3.12.0",
    "pm2": "^3.2.9",
    "valine": "^1.3.4",
    "vuepress": "^0.14.9"
  },
  "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.47",
    "vuepress-plugin-demo-block": "^0.7.2"
  }
}

**Comment by timaschew** [comment]
You’re using a plugin for vuepress 1.x but using vuepress 0.x

**Comment by qiufeihong2018** [comment]
> You’re using a plugin for vuepress 1.x but using vuepress 0.x

Thank you!

**Comment by ZhongHongLi** [comment]
我想问下为啥返回top插件失效

**Comment by ZhongHongLi** [comment]
{
  "name": "docs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "keywords": [],
  "author": "hongli",
  "license": "ISC",
  "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-rc.1",
    "@vuepress/plugin-pwa": "^1.0.0-rc.1",
    "vuepress-plugin-nprogress": "^1.1.1"
  },
  "dependencies": {
    "leancloud-storage": "^3.15.0",
    "valine": "^1.3.9"
  }
}
