### ISSUE TITLE
vuepress: command not found

### ISSUE THREAD

**Issue by magick93** [vuejs/vuepress#1533]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
1. Following the directions on https://v1.vuepress.vuejs.org/guide/getting-started.html

```
user@user-HP-ZBook-Studio-G4:~/git/docs$ yarn global add vuepress
yarn global v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "vuepress@0.14.10" with binaries:
      - vuepress
Done in 2.61s.
user@user-HP-ZBook-Studio-G4:~/git/docs$ vuepress dev
vuepress: command not found
```

#### What is expected?

Expect to be able to use the `vuepress` command

#### What is actually happening?

`vuepress: command not found`

#### Other relevant information

- Your OS: ` Linux user-HP-ZBook-Studio-G4 4.18.0-17-generic #18~18.04.1-Ubuntu `
- Node.js version: ` v10.15.1` 
- Browser version: ` Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)`
- Is this a global or local install? `global`
- Which package manager did you use for the install? `yarn`
- Does this issue occur when all plugins are disabled? I dont know. But yarn was freshly installed, so there shouldnt be any other plugins.

**Comment by magick93** [comment]
Fixed by following instructions on https://stackoverflow.com/a/40333409/265119

**Comment by Boom-BO** [comment]
yarn add -D vuepress

**Comment by ThaisCerutti** [comment]
> yarn add -D vuepress

Thanks <3
