### ISSUE TITLE
Hot reload doesn't normal work without --temp .temp

### ISSUE THREAD

**Issue by xinyii** [vuejs/vuepress#1536]
- [x] I confirm that this is an issue rather than a question.

## Bug report

If you do not set `--temp .temp`, hot reload can only reload markdown, but can not reload `config.js` files, navigation bar, sidebar title, front matter, etc.

#### Steps to reproduce

1. `npm install -g vuepress@next`
2. `echo '# Hello VuePress!' > README.md`
3. Create file `.vuepress/config.js`
```js
module.exports = {
  themeConfig: {
    nav: [
      { text: 'home', link: '/' }
    ],
    sidebarDepth: 2,
    sidebar: {
      '/': [
        ['', 'home']
      ]
    }
  }
}
```
4. `vuepress dev .`
5. Edit file `.vuepress/config.js`
```js
module.exports = {
  themeConfig: {
    nav: [
      { text: 'home', link: '/' }
    ],
    sidebarDepth: 2,
    sidebar: {
      '/': [
        ['', 'newHome']
      ]
    }
  }
}
```

#### What is expected?

sidebar title '`home` to `newHome`

#### What is actually happening?

no change

#### Other relevant information

Websocket connection is normal.

- Your OS:  Windows 10
- Node.js version:  v11.2.0
- Browser version: Google Chrome  73.0.3683.103
- Is this a global or local install? global
- Which package manager did you use for the install? npm 6.4.1
- Does this issue occur when all plugins are disabled? yes

**Comment by Xinyii** [comment]
![temp文档描述](https://user-images.githubusercontent.com/17895104/56073217-00896e00-5dd3-11e9-8f44-bcd547717f2b.png)

而且默认设置并不生效，只能用 `vuepress dev . --temp .temp`

**Comment by timaschew** [comment]
I've realized that changing (adding or deletigin items) in the sidebar are not properly hot-reloaded.  
Renaming existing items works fine.

Navbar is not affected.

**Comment by ulivz** [comment]
Since you're using a globally installed vuepress, the temp files will be placed under the global installed directory so that VuePress cannot detect the change of it.

---

BTW, the docs has been updated.

**Comment by AJLoveChina** [comment]
@Xinyii **非常感谢你提供的帮助** ：`vuepress dev . --temp .temp`，它确实可行。
在这之前，我在官方文档中找不到这行命令的说明，我被sidebar无法自动更新的问题困扰了很久。

在0.x的版本中，sidebar自动更新是可以正常工作的。
但是当我切换到1.x版本之后，sidebar就无法自动更新了

我特地制作了一个Gif图，希望它对你们有帮助。
![vue-press-sidebar-bug3](https://user-images.githubusercontent.com/11222746/56874574-56b20e80-6a6d-11e9-9f68-e3ad129d931d.gif)

**Comment by Molunerfinn** [comment]
@AJLoveChina 我也遇到同样的问题。在1.x下，必须指定 `--temp` 才能更新sidebar的目录。而这个问题在1.x是没有的。我并没有全局安装Vuepress，而是安装在项目目录下。

**Comment by quanzaiyu** [comment]
The same issue +1

**Comment by Akimotorakiyu** [comment]
The same issue +1

**Comment by nbgmtin** [comment]
The same issue +1
