### ISSUE TITLE
rollup project, all vuepress dynamic import are broken

### ISSUE THREAD

**Issue by ale-grosselle** [vuejs/vuepress#1537]
- [ ] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.47
#### Steps to reproduce
In my rollup project, run decs:dev, "You may need an appropriate loader to handle this file type" import("/Users/al....")

All dynamic import are broken

#### What is actually happening?

All dynamic import are broken

#### Other relevant information

- Your OS: MAC Os
- Node.js version: 10.15.3
- Browser version: 
- Is this a global or local install?  CHROME
- Which package manager did you use for the install? NPM
- Does this issue occur when all plugins are disabled?

![image](https://user-images.githubusercontent.com/6173088/56062877-1a449a00-5d6e-11e9-854e-0dda94958da5.png)

**Comment by ulivz** [comment]
You should at least provide a minimal repro repo to prove that it's really just a problem working with Rollup.

**Comment by ale-grosselle** [comment]
@ulivz I investigate and without webpack installed in your repo vuepress generates the error i posted.

If you use different module bundler Is not intuitive Easy ti understand that you must have webpack
