### ISSUE TITLE
Links with anchors don't scroll to the correct position *the first time*

### ISSUE THREAD

**Issue by gauravve** [vuejs/vuepress#1541]
- [x] I confirm that this is an issue rather than a question. This is same issue as reported in #1499 but I am not able to open that issue. 

## Bug report
Anchors in links to other pages within a vuepress site don't work the first time the link is clicked. "Don't work" means that the page is not scrolled to the element, but the sidebar does have correct item highlighted. Once the page is loaded the first time, any consecutive clicks through the link to that page do work as expected.

#### Version
1.0.0-alpha.47

#### Steps to reproduce
Copied from #1499 comments. 

I found a way to reproduce this using vuepress's own site. Go to this link and click the first link with the text header on that page. Again, it doesn't scroll to correct position on the first try, but does when you go back and try again AFTER the page has been loaded.

This only happens first time. 

#### What is expected?
Links with anchors should work even when clicking them the first time during a session.

#### What is actually happening?
Links with anchors don't scroll to the correct position the first time they are used.

#### Other relevant information

- Your OS: Mac OS Mojave 
- Node.js version: 8.15
- Browser version: Chrome 73
- Is this a global or local install? global 
- Which package manager did you use for the install? npm
- Does this issue occur when all plugins are disabled? yes

**Comment by ulivz** [comment]
Truly an issue and contribution welcome!

**Comment by gauravve** [comment]
@ulivz Wondering if this is fixed as part of #1594

**Comment by ulivz** [comment]
Yup, there are the same issue.
