### ISSUE TITLE
Stylus is not compiled in markdown file.

### ISSUE THREAD

**Issue by LasyIsLazy** [vuejs/vuepress#1545]
- [x] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.47
#### Steps to reproduce

I have stylus code in my markdown file, but it is not compiled in browser.

Code example:
```CSS
<style lang="stylus">
.test
  width 200px
</style>
```

#### What is expected?

It should be compiled to
```CSS
.test {
  width: 200px;
}
```

#### What is actually happening?

Not compiled.

#### Other relevant information

- Your OS: Mac
- Node.js version: v10.15.0
- Browser version: Chrome v75
- Is this a global or local install? Local install. 
- Which package manager did you use for the install? Yarn.
- Does this issue occur when all plugins are disabled? Yes.

**Comment by ulivz** [comment]
Sorry but I cannot reproduce it.

![image](https://user-images.githubusercontent.com/23133919/56222254-4594f500-609e-11e9-9eb4-6bbb49ab9018.png)
