### ISSUE TITLE
Isolating components in iframe

### ISSUE THREAD

**Issue by romanslonov** [vuejs/vuepress#1548]
#### What problem does this feature solve?
Styles intersection. 

#### What does the proposed API look like?
Users components might be wrapped with iframe. 

#### How should this be implemented in your opinion?
As a plugin.

#### Are you willing to work on this yourself?
Yes, but for now I don't know where to start. 

Okay, I am developing design system and vue components library and found that my components styles are overwritten by vuepress default theme. Specifically component like table, etc. So it would be great if we can develop plugin/component which will render provided component in iframe. 

Example:
```html
<v-frame>
  <my-button>My isolated button</button>
</v-frame>
```

This might be extremely useful for UI library authors. 

I'd develop this plugin/component but need to help to figure out how to throw styles into iframe?

**Comment by Shigma** [comment]
Actually I don't consider it an issue with VuePress...... It's a question with Vue.

**Comment by timaschew** [comment]
Why you would wrap a component into a iframe? This sounds weird to me.

**Comment by romanslonov** [comment]
@timaschew seems like I described it in first post of this issue.

**Comment by timaschew** [comment]
True.

So you want to use an iframe in order to isolate styles of components which you don’t control (3rd party components, not yours), right?

I dont think iframe is a good choise for it. 
The components should just use webcomponent API. This allows to isolate styles. Style values can also be provided as variables, which can be of course overwritten by specificity. Even if vuepress is overwriting them, you can always write more specific selectors.

**Comment by romanslonov** [comment]
> components which you don’t control (3rd party components, not yours), right?

No, it's my library. I'm using vuepress to build a documentation for it.

**Comment by timaschew** [comment]
> No, it's my library. I'm using vuepress to build a documentation for it.

One reason more not to iframes.  
Just use more specific selectors or variables.

**Comment by larionov** [comment]
Iframes might also be useful to display components at different breakpoints for responsive design.

**Comment by larionov** [comment]
Also more specific selectors will not save you from styles apllied by vuepress itself

**Comment by ulivz** [comment]
Actually I always have a idea, in VuePress we can provide a capacity of isolating context between application and preview, just like what Storybook did.

**Comment by f3ltron** [comment]
Hum i understand the problem you have actually.

@larionov For breakpoints you should not need iframes.

The problem of iframes is actually storybook are using it too. But they seem's to be bloked for evolution now. But they have something cool anyway.

Maybe we can add some reset css on a custom wrapper component that inherit everything. But it's look a lot of work to do and maintain.

Hum yeah iframes look the best stuff.

**Comment by timaschew** [comment]
Just use a shadow DOM, then your styles will be isolated, they can only be overwritten by variables, which you can control by giving a unique name.

**Comment by larionov** [comment]
@timaschew not everybody can use shadow dom, for example it will not work if you need to ssr/prerender the components.

**Comment by larionov** [comment]
@f3ltron how do you demonstrate breakpoints without iframes?

**Comment by f3ltron** [comment]
I heard about something will be implemented in this way but probably as shadow dom not really good supported

**Comment by f3ltron** [comment]
Before using iframe we should find if there is any better way to do that ^^

**Comment by pangao66** [comment]
why this issues was closed?
I think iframe  is very useful  for  some conditions
now I want to write a ui frameworks 
there is a 'x-table' component to show in vuepress
if I don't use iframe  the  style of vuepress theme will influence the style of 'x-table'
becase of the default theme of vuepress has write the style of table https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/styles/index.styl
even though I can rewrite the style to overwise the default style
but I  only want not infulence the 'x-table' not all of the document of vuepress

为什么关闭了这个issues呢?
我认为这个iframe模式在一些条件下非常有用
比如 现在我需要写一个ui框架
有一个'x-table'组件需要在vuepress里面展示
如果不使用iframe, vuepress 默认的样式将会影响到这个'x-table'组件
因为vuepress 默认的主题已经写了一些table默认的样式
https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/styles/index.styl
虽然我可以重写样式覆盖默认的样式
但是我只想默认的样式不影响'x-table'组件而不是整个文档
