### ISSUE TITLE
Vuepress could provide cli or pluginAPI to compile some specific markdown files?

### ISSUE THREAD

**Issue by JimmyVV** [vuejs/vuepress#1562]
#### What problem does this feature solve?

when the project is large, everytime vuepress will completely compile it again, which it cost much time. 

#### What does the proposed API look like?

provide plugin with markdownEntry API

#### Are you willing to work on this yourself?

ok

**Comment by ulivz** [comment]
You can create a plugin to get it. and the basic solution is to filter pages in ready hook.

Refs:

- [Ready Hook](https://v1.vuepress.vuejs.org/plugin/life-cycle.html#ready)
- [Context API > ctx.pages](https://v1.vuepress.vuejs.org/plugin/context-api.html#ctx-pages)
