### ISSUE TITLE
Parent component can get mixins data, but not child components

### ISSUE THREAD

**Issue by hckherbert** [vuejs/vuepress#1566]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Parent component can get mixins data, but not child components

#### Version
3.3.0

#### Steps to reproduce
1. Create mixins file, let's say viewer.js
```
export const viewer =  {
    data() {
        return {
            foo:"bar",
            hello:"world"
        }
    },
    methods: {
        testFunc() {
	     console.log("test func");
        }
    },
    computed: {
	testComputed(){
	     return "123";
	}
   }
```
2. Create a parent component, let's say mainCompo:
```
import {viewer} from 'mixins/viewer';
export default {
        components:  {
                compoChildA,
                compoChildB,
                compoChildC
        },
        mixins: [viewer],
        data() {
            //...
        }
        mounted() {
	    console.log(this.testComputed);
	    console.log(this.foo);
	    console.log(this.hello);
            console.log(this.testFunc());
	},
	//....
}

<div>
	<compo-child-a></compo-child-a>
	<compo-child-b></compo-child-b>
	<compo-child-c></compo-child-c>
	...
</div>
```
3. Create a child component, for example, compoChildA, that will be imported to mainCompo

```
import {viewer} from 'mixins/viewer';
export default {
        mixins: [viewer],
        data() {
            //...
        }
	mounted() {
	    console.log(this.testComputed);
	    console.log(this.foo);
	    console.log(this.hello);
            console.log(this.testFunc());
	},
      //....
}

<div>
```	

#### What is expected?
All the methods, computed and data values should be printed by the console.log() in the mounted hook of compoChildA.
```
this.testComputed --> 123
this.foo --> bar
this.hello --> world
this.testFunc() --> test func
```
#### What is actually happening?
foo, and hello from the mixins data() cannot be accessed by _compoChildA_. However, methods and computed properties do work. And all data, computed and methods work well in the parent component _mainCompo.
```
this.testComputed --> 123
this.foo --> undefined
this.hello --> undefined
this.testFunc() --> test func
```

**Comment by ulivz** [comment]
Hello! It appears you opened an issue concerning [vue](https://github.com/vuejs/vue) itself, could you please post a new issue with the content of this one?
