### ISSUE TITLE
vuepress@next fails to resolve custom theme when run globally

### ISSUE THREAD

**Issue by stasson** [vuejs/vuepress#1568]
- [ X] I confirm that this is an issue rather than a question.

#### Version

1.0.0-alpha.47

#### Steps to reproduce

considering such config file

```javascript
// .vuepress/config.js
module.exports = {
  theme: '@myscope/my-theme'
};
```

when installing vuepress globally  and a custom theme locally
```bash
> npm i -g vuepress@next
> npm i  @myscope/vuepress-theme-my-theme
```

vuepress fail to resolve the custom theme

```bash
> vuepress dev .
Error: Cannot find module '@myscope/vuepress-theme-my-theme/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at normalizeThemePath (C:\Users\az02080\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\loadTheme.js:59:33)
```
#### What is expected?

expecting custom theme to be resolved as in cwd.

#### What is actually happening?

custom theme is not resolved. 

#### Other relevant information
- Your OS:  win10
- Node.js version:  node 10.15.0 
- Browser version: chrome 73
- Is this a global or local install? global
- Which package manager did you use for the install? npm
- Does this issue occur when all plugins are disabled? no

if vuepress installed and run locally , everything is fine, so this is not a critical issue. 
Still would be a nice fix:  vuepress installed globally in docker while theme installed in repo allows to speed up our CI big time. also nice to have for dev env.

**Comment by stasson** [comment]
at [loadTheme.js  L59](https://github.com/vuejs/vuepress/blob/41b5cfba3f0aa6e0d6b0df9a31c1eb7d3d76faa8/packages/%40vuepress/core/lib/node/loadTheme.js#L59) 

```javascript
const packageRoot = require.resolve(`${name}/package.json`)
```

probably would work if we had ?

```javascript
const packageRoot = require.resolve(`${name}/package.json`, {paths: [process.cwd()] })
```

**Comment by stasson** [comment]
also probably same issue as https://github.com/vuejs/vuepress/pull/399 but for v1.x

**Comment by f3ltron** [comment]
hello i am closing this issue as we are not using next. Please consider to not install vuepress globally but in project instead
