### ISSUE TITLE
Google Analytics not working - Vue 1.x

### ISSUE THREAD

**Issue by JeffBeltran** [vuejs/vuepress#1579]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Google Analytics does not appear to work. https://github.com/JeffBeltran/faker.js-docs for code or https://fakerjsdocs.netlify.com/ for deployed site. Inspecting the site i can see the ga id in the source so it's making it's way to the deployed site.

One thing i did notice is that when i build the site locally i only see the following

```sh
yarn run v1.15.2
$ vuepress build docs
wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
[2:42:17 PM] Compiling Client
[2:42:17 PM] Compiling Server
[2:42:23 PM] Compiled Server in 6s
[2:42:27 PM] Compiled Client in 10s
wait Rendering static HTML...
success Generated static files in dist.
```

so not sure if the plugin is even being called?

#### Version
```
"@vuepress/plugin-google-analytics": "^1.0.0-alpha.47",
"vuepress": "^1.0.0-alpha.47"
```
#### Steps to reproduce

Using netlify to build and deploy docs from https://github.com/JeffBeltran/faker.js-docs to https://fakerjsdocs.netlify.com/ followed instructions via https://v1.vuepress.vuejs.org/plugin/official/plugin-google-analytics.html

#### What is expected?

To see that google analytics url is called `https://www.googletagmanager.com/gtag/js?id=UA-00000000`

#### What is actually happening?

nothing

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: chrome/firefox/safari
- Is this a global or local install?  both
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled? n/a

**Comment by ulivz** [comment]
Hi and thanks for your issue! In the interest of keeping this project organized, we try to keep requests on this repo to a few main topics. Unfortunately, you may have created a wrong issue.

The google-analytics plugin only integrates Google Analytics, but not include GTM, and this is the real tracking request:

![image](https://user-images.githubusercontent.com/23133919/57245010-608ad180-706c-11e9-93a2-0533ced9571f.png)

**Comment by JeffBeltran** [comment]
sorry about that, i honestly didn't realize there was a difference. Thanks for taking the time to look over this and reply.
