### ISSUE TITLE
Plugin-API options extendMarkdown not work

### ISSUE THREAD

**Issue by Haujilo** [vuejs/vuepress#1580]
- [ ] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.47

#### Steps to reproduce

在.vuepress/config.js配置
```javascript
module.exports = {
  markdown: {
    extendMarkdown: md => {
      md.set({
        highlight: function (str, lang) {
          return '<pre class="test"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
        }
      });
    },
  }
}
```
可以看到markdown渲染的`<pre>`块可以带上test这个class。

但是根据文档配置.vuepress/theme/index.js

```javascript
module.exports = {
  plugins: [
    [
      (pluginOptions, context) => ({
        name: 'vuepress-plugin-xx',
        extendMarkdown: md => {
          md.set({
            highlight: function (str, lang) {
              return '<pre class="test"><code>' + md.utils.escapeHtml(str) + '</code></pre>';
            }
          });
        },
      })
    ]
  ]
}
```
执行`yarn docs:dev`可以看到输出`tip Apply plugin vuepress-plugin-xx ...`，但是实际渲染出来的页面没有任何效果。

#### What is expected?

自行开发的主题应该是可以修改markdown-it的渲染？

#### What is actually happening?

实际上不同过主题以外的配置，无法替换markdown-it的渲染

#### Other relevant information

- Your OS:  macOS 10.14.3
- Node.js version:  v10.14.2
- Browser version:  Google Chrome 73.0.3683.103
- Is this a global or local install?  local
- Which package manager did you use for the install? yarn
- Does this issue occur when all plugins are disabled? not try

**Comment by ulivz** [comment]
This is caused by the built-in `cache-loader` since for now the the config of the `plugin` will not be considered part of the cacheIdentifier, you can fix issue by:

1. Running `yarn build`.
2. Running `yarn dev --no-cache`.
