### ISSUE TITLE
vuepress/plugin-pagination can not return correct Data

### ISSUE THREAD

**Issue by yuicer** [vuejs/vuepress#1581]
- [x] I confirm that this is an issue rather than a question.

## Bug report
vuepress/plugin-pagination can not return correct Data
#### Version
@vuepress/plugin-pagination@1.0.0-alpha.47

the $pagination param never return the correct Data

I have read the code, it seems to be like this

plugin-pagination/index.js
```js
  const pagination = {
      paginationPages: intervallers.map((interval, index) => {
        const path = index === 0 ? firstPagePath : `/${paginationDir}/${index + 1}/`
        return { path, interval }
      }),
      postsFilter: postsFilter.toString(),
      postsSorter: postsSorter.toString()
    }
```

plugin-pagination/enhanceAppFile.js
```js
    const { path } = route
    const { paginationPages } = pagination

    paginationPages.forEach((page, index) => {
      if (page.path === path) {
        this.paginationIndex = index
      }
    })
```

ok , it seems that the real path in $router will never equal to the path created by 
```js
const path = index === 0 ? firstPagePath : `/${paginationDir}/${index + 1}/`
```

could we get this plugin better ? it even does not have the docs yet..... 

and i saw the [project](https://github.com/vuejs/vuepress/projects/1#card-17994124), will the offical theme comming soon ?

**Comment by ulivz** [comment]
Thank you for your interest in VuePress. If you think that pagination plugin can not return the correct data, please don't delete the issue template and tell us why it's wrong and what's expected, Also, please include a minimal reproduction using e.g.[CodeSandbox](https://codesandbox.io/s/github/vicbergquist/codesandbox-vuepress) (Recommended), CodePen, or a GitHub repository.
