### ISSUE TITLE
Extending Layout.vue can't resolve '@AlgoliaSearchBox'

### ISSUE THREAD

**Issue by sdailly** [vuejs/vuepress#1582]
- [x] I confirm that this is an issue rather than a question.

#### Version
1.0.0-alpha.47

#### What is expected?
1. Create a Layout that extends @vuepress/theme-default/layouts/Layout.vue  
`CustomLayout.vue`

```vue
<script>
import Layout from "@vuepress/theme-default/layouts/Layout.vue";

export default {
  extends: Layout
}
</script>
```
2. Use Layout
`index.md`

```
---
layout: CustomLayout
---
```

#### What is actually happening?
Can't resolve @AlgoliaSearchBox 

```
./docs/.vuepress/theme/components/Navbar.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./docs/.vuepress/theme/components/Navbar.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@AlgoliaSearchBox' in '/vuepress/docs/.vuepress/theme/components'
```

I had the same problem with `@Searchbox`but i fixed it with plugin `@vuepress/plugin-search`

Need to install a plugin for `@AlgoliaSearchBox` ?

#### Other relevant information

- Your OS: MacOs Mojave
- Node.js version: 8.9.4
- Browser version: Chrome
- Is this a global or local install? local
- Which package manager did you use for the install? npm
- Does this issue occur when all plugins are disabled? Yes

**Comment by ulivz** [comment]
Thanks for submitting this issue! To help us investigate your problem, please include a minimal reproduction using e.g. CodeSandbox, CodePen, or a GitHub repository.

**Comment by godfrey-cw** [comment]
@sdailly would you mind explaining how you resolved a similar issue with `@SearchBox` using `@vuepress/plugin-search`?

I've installed that plugin and included it in the config, but still get "Can't resolve @SearchBox" errors.

**Comment by sergeymorkovkin** [comment]
Same here. Was there a solution?

**Comment by BFMarks** [comment]
Plus  ! @bradumbaugh

**Comment by kefranabg** [comment]
@sdailly did you manage to fix your issue?

**Comment by imaegoo** [comment]
Same here. Was there a solution?

**Comment by imaegoo** [comment]
Change
``` js
import Layout from "@vuepress/theme-default/layouts/Layout.vue";
```
to
``` js
import Layout from "@parent-theme/layouts/Layout.vue";
```
Define parent theme in `.vuepress/theme/index.js`
``` js
module.exports = {
  extend: '@vuepress/theme-default'
}
```

Works for me.
