### ISSUE TITLE
建议增加 记录语言 功能

### ISSUE THREAD

**Issue by eliot-ye** [vuejs/vuepress#1585]
#### What problem does this feature solve?
建议在 选择语言 设置后，在本地记录当前选择。之后再进入将检测本地记录的语言，自动跳转到相应语言，这是为了pwa的用户体验

**Comment by ulivz** [comment]
谢谢你对 VuePress 的兴趣。

不过，不同的语言 URL 并不一样，当你首先阅读了中文文档，下次再进入这个 URL 时，一定是当前的语言而无需切换。

其次，即使真地要做这个功能，也应该是写一个插件来解决。

**Comment by Shigma** [comment]
@eliot-ye 你或许可以看看 vuepress-plugin-redirect 插件，它可以实现根据 localStorage 和 navigator.languages 实现自动语言重定向的功能。

**Comment by eliot-ye** [comment]
@ulivz 可是pwa只记录域名，每次进入都是进入域名首页，我的建议是针对这种情况的

**Comment by eliot-ye** [comment]
@Shigma 谢谢，这个插件貌似解决了我说的问题
