### ISSUE TITLE
Error extracting metadata

### ISSUE THREAD

**Issue by ederchrono** [vuejs/vuepress#159]
I just installed VuePress on a project and I'm getting this error after running the dev command:
```
Extracting site metadata...TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/.../node_modules/mini-css-extract-plugin/dist/index.js:26:9)
```
The project is not that recent, it was created with an older Vue CLI than the latest and I'm not sure if there's a config or dependency that's causing a conflict.

Installed with npm as a dev dependecy, not globally

**Comment by ederchrono** [comment]
I just made a branch with the error https://github.com/ederchrono/vue-css-grid/tree/feat/add-vuepress
Just `npm i` and then `npm run docs:dev`
Also when installing dependencies it throws these warnings:
```
npm WARN koa-webpack@3.0.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.1.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mini-css-extract-plugin@0.4.0 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN time-fix-plugin@2.0.0 requires a peer of webpack@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-hot-client@2.2.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-serve@0.3.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
```
Installing webpack 4 after that makes vuepress work but breaks my project, it looks like I have to do a clean install with the Vue CLI beta that has the webpack 4 config

**Comment by yyx990803** [comment]
Did you see the warning in docs? You need to use Yarn if your project has webpack 3 in dependencies.

**Comment by ederchrono** [comment]
Thanks for pointing that out! Looks like I was looking to an old version of the getting started guide or something because it used `npm` for the instructions instead of `yarn`.

Keep up the good work!
