### ISSUE TITLE
Command failed with exit code 1, and build failed in Netlify.

### ISSUE THREAD

**Issue by chenweigao** [vuejs/vuepress#1590]
when I updated my code, something goes wrong with the build and deploy(I have added some .vue file and updated the version of  `element-ui`.
Everything goes right when I run `yarn docs:dev` and there are no problems.
But, when I deployed the site, this happened:
![image](https://user-images.githubusercontent.com/19328388/57452557-bb077600-7296-11e9-9fc1-639d9955dd4c.png)
and I tried to build code on my computer, the error is:

![image](https://user-images.githubusercontent.com/19328388/57452680-01f56b80-7297-11e9-8033-ac3e69fbee6f.png)

Could you please help me with this? I am not sure it is a bug or some mistake about me.

I have tried to delete the `docs/.vuepress/styles/mycss.css` file which I am not sure, but it did not work.

this is my [repos](https://github.com/chenweigao/vueblog/tree/preview)

**Comment by chenweigao** [comment]
I have solved this question by degrading the `element-ui` and I found it is a bug caused by `element-ui`.
Thanks and sorry for the trouble.

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/issues/1583#issuecomment-489689412
