### ISSUE TITLE
Bug Report: Search result cannot jump to the correct hash anchor

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#1594]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. Open https://v1.vuepress.vuejs.org/;
2. Type `Table`, choose a result and tap enter;
3. The page will move to the target page but not move to the correct correct hash anchor.

#### What is expected?

The search result should jump to the correct hash anchor.

#### What is actually happening?

The search result doesn't jump to the correct hash anchor.

#### Other relevant information

- [x] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 1.0.0-alpha.47
  - OS: OSX
  - Node.js version: -
  - Browser version: -
  - Is this a global or local install?  -
  - Which package manager did you use for the install? -
  - Does this issue occur when all plugins are disabled? -

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by JeffBeltran** [comment]
I just setup the algolia docsearch for a project and this problem went away for me. Figured i'd mentioned this just in case it helps troubleshoot this problem.
