### ISSUE TITLE
Java Hight

### ISSUE THREAD

**Issue by skythinking** [vuejs/vuepress#1598]
https://github.com/vuejs/vuepress/issues/1595#issuecomment-491610745

It doesn't seem to work,why?

**Comment by ulivz** [comment]
Why send illegal issue over and over again?

![image](https://user-images.githubusercontent.com/23133919/57585499-8e17c500-751b-11e9-9ff4-7b932a9799ee.png)

**Comment by ulivz** [comment]
In addition, if you expect others to help you, please follow our issue guidelines and DO NOT delete the issue template.

And we will block you If you continue to pollute the issue.
