### ISSUE TITLE
error in iOs 9 safari : `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.` 

### ISSUE THREAD

**Issue by francoisromain** [vuejs/vuepress#1606]
- [X] I confirm that this is an issue rather than a question.

#### Steps to reproduce

repro: 
- clone https://github.com/francoisromain/vuepress-ios9-bug
- install: `npm i`
- `npm run dev`
- open in a iOs 9 safari 

#### What is expected?

The website should work in iOs 9 safari

#### What is actually happening?

blank page with an error: `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

#### Other relevant information

This works well with vuepress `0.14.10`, but not with `1.0.0-alpha.48`

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 1.0.0-alpha.48
  - OS: macOs 10.13.6
  - Node.js version: 12.1.0
  - Browser version: safari iOs 9
  - Is this a global or local install? local
  - Which package manager did you use for the install? npm
  - Does this issue occur when all plugins are disabled?

- [x] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.5
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.0.0-alpha.48 
    @vuepress/theme-default:  1.0.0-alpha.48 
    vuepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48 
  npmGlobalPackages:
    vuepress: Not Found

**Comment by deliverymanager** [comment]
+1

**Comment by deliverymanager** [comment]
@francoisromain  Did you find any solution on that?

**Comment by ulivz** [comment]
Could you upgrade to the latest version of VuePress?

**Comment by francoisromain** [comment]
@ulivz Ok I'll try that this evening and let you know

**Comment by francoisromain** [comment]
@ulivz I upgraded to the latest version and the problem is still here: 

``

**Comment by deliverymanager** [comment]
I am in the latest version too. Problem is there

**Comment by tretapey** [comment]
Hello, I haven't tried this yet but I'm pretty sure that your browserslist is not including IOs 9, and there when it bundles is not supported.

Your actual browserslits configuration is: https://browserl.ist/?q=%3E1%25

I don't think that giving support for IOs 9 is needed though
