### ISSUE TITLE
Linking to permalink

### ISSUE THREAD

**Issue by luaz** [vuejs/vuepress#1609]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?
For `docs/privacy.md`, I use the following markdown

```markdown
---
permalink: /privacy
---

# Privacy
```

Which allow me to access the page as `http://localhost:8080/privacy/`

When I try to link to the page via `[Privacy](./privacy.md)`, `/privacy.html` is generated instead of `/privacy/`.

#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 
  - OS:
  - Node.js version: 
  - Browser version: 
  - Is this a global or local install? 
  - Which package manager did you use for the install?
  - Does this issue occur when all plugins are disabled?

- [x] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (2) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
  npmPackages:
    @vuepress/core:  1.0.0-alpha.48 
    @vuepress/theme-default:  1.0.0-alpha.48 
    vuepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48 
  npmGlobalPackages:
    vuepress: 0.14.4

**Comment by ulivz** [comment]
> What is actually happening?

**Comment by luaz** [comment]
When I try to link to the page via [Privacy](./privacy.md), /privacy.html is generated instead of /privacy/.
