### ISSUE TITLE
VuePress dev server not working

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#162]
$ vuepress dev
      Extracting site metadata...[21:09:42] Compiling Client
      [21:09:46] Compiled Client in 4s

      VuePress dev server listening at http://localhost:8080/

On the road he does not show me anything as if I did not find him

**Comment by xubowenjx** [comment]
I got a 404 page.

**Comment by yyx990803** [comment]
Please at least provide your OS, Node version, vuepress version etc. We can't do anything with reports like this.

**Comment by luisDanielRoviraContreras** [comment]
- window
- node v8.4.0
- vuepress v0.7.0
It shows me that if I compile but when I go to the locarl server with the port it literally appears **Not Found**

**Comment by yyx990803** [comment]
Do you have at least a `README.md`?...

**Comment by luisDanielRoviraContreras** [comment]
run the tutorial litarialmente equal 

       # install globally
        yarn global add vuepress # OR npm install -g vuepress

       # create a markdown file
        echo '# Hello VuePress' > README.md

       # start writing
       vuepress dev

       # build 
       vuepress build

the name of readme is

README.md

**Comment by luisDanielRoviraContreras** [comment]
Could they at least explain to me why the file does not work? It has to be readme.md? in lowercase everything? or I do not understand and of course when I say follow literal is to execute a command at a time not everything until comments

could give me a functional example please really I love the proposal of vuepress at the moment use hexo and I would love to migrate to vuepress

**Comment by SebastianNiemann** [comment]
Seeing spaces within the @luisDanielRoviraContreras's project path, I assume this is also due to https://github.com/webpack/webpack-dev-server/issues/1373 and https://github.com/webpack/webpack-dev-middleware/issues/296.

Currently, `webpack-dev-middleware` can't handle spaces within the fully resolved path anymore.

I have also reproduced this behaviour for `vuepress` on my local Windows machine.

**Comment by luisDanielRoviraContreras** [comment]
@SebastianNiemann  
Thank you very much but where does my route have spaces?

**Comment by Ragura** [comment]
@luisDanielRoviraContreras 
You have a space in your Windows-generated user path, because of the username "pc 01".

**Comment by luisDanielRoviraContreras** [comment]
@Ragura @SebastianNiemann 

Thanks alfin I worked with the name change without spaces :grinning: .

**Comment by dannyk08** [comment]
@SebastianNiemann  thank you, you saved me from a night full of headaches!
I was trying to implement express and webpack with webpack-dev-middleware and it kept failing on me. the process wouldn't write files to a directory

**Comment by Porya200** [comment]
hi , my server not run in macOs 

> $ vuepress dev
> -bash: vuepress: command not found

my nodejs version : v8.12.0
my vuepress version : v0.14.10
my npm version : v6.4.1

I did all this 👍 
```
npm install -g vuepress
echo '# Hello VuePress' > README.md
```

**Comment by ajthenewguy** [comment]
The dev script said it was "listening at http://localhost:8080" but I had to access at http://0.0.0.0:8080

**Comment by Lmpgdn** [comment]
> The dev script said it was "listening at http://localhost:8080" but I had to access at http://0.0.0.0:8080

The same issue happened to me. I did what @ajthenewguy did and now I can access the doc.

**Comment by wdmtech** [comment]
Thanks to Evan, I realised I had `README.MD` (the file extension was in caps), causing a 404 on the index page. 

Should I create an issue for this?
