### ISSUE TITLE
process is not defined when checking if I am in a browser environment

### ISSUE THREAD

**Issue by AMontagu** [vuejs/vuepress#1625]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Use a vue component that call process node variable:

created() {
	console.log(process);
},

#### What is expected?

In vue project process variable should be accessible.

#### What is actually happening?

![image](https://user-images.githubusercontent.com/11883225/58488100-1081c500-8169-11e9-84fd-88bde21e9e28.png)

#### Other relevant information

I use process variable to know if I am in a broswer mode to load not ssr compatbile components vue-dropzone. code from here: [https://github.com/Etheryte/nuxt-dropzone/blob/master/index.js](https://github.com/Etheryte/nuxt-dropzone/blob/master/index.js)

I use a workaround with lazy loading but just wanted to report it and understand if it's normal:
vueDropzone: () => import('vue2-dropzone'),

- [x] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 0.14.11
  - OS: Linux
  - Node.js version: 10.9.0
  - Browser version: latest chrome
  - Is this a global or local install? local
  - Which package manager did you use for the install? npm
  - Does this issue occur when all plugins are disabled? yes

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
`process` is Node-only variable. if you want to access it in client side code, you should use [define] to define it.

**Comment by luchuanqi** [comment]
我也遇到同样的问题

**Comment by luchuanqi** [comment]
> 我也遇到同样的问题

我这个还比较尴尬的是，我这个是npm包中使用到了process

**Comment by davestewart** [comment]
To clarify the note on `[define]` I've just discovered it's actually this, not a complete WebPackDefinePlugin setup:

https://v2.vuepress.vuejs.org/advanced/cookbook/passing-data-to-client-code.html#use-define-hook
