### ISSUE TITLE
_vm._ssrEscape is not a function

### ISSUE THREAD

**Issue by f3ltron** [vuejs/vuepress#1630]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

```bash
git clone https://github.com/f3ltron/vuepress-plugin-docgen

yarn
```

delete no-ssr from components/Functionnals/withtemplate.vue

```bash
yarn run docs:build 
```
#### What is expected?

it should build the component

#### What is actually happening?

actually got this error:

```bash
wait Rendering static HTML...
Rendering page: /Components/Functionnals/withtemplate.htmlerror Error rendering /Components/Functionnals/withtemplate.html: false
undefined
TypeError: _vm._ssrEscape is not a function
    at render (components/Functionnals/withtemplate.vue?21c3:1:46)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:78:0)
    at createFunctionalComponent (/Users/florent/workdir/vuepress/vuepress-plugin-docgen/node_modules/vue-server-renderer/build.dev.js:7944:30)
    at createComponent (/Users/florent/workdir/vuepress/vuepress-plugin-docgen/node_modules/vue-server-renderer/build.dev.js:8117:12)
    at resolve (/Users/florent/workdir/vuepress/vuepress-plugin-docgen/node_modules/vue-server-renderer/build.dev.js:8426:24)
error Command failed with exit code 1.
```

#### Other relevant information

I added no-ssr for working by reading [THIS](https://github.com/vuejs/vue-loader/issues/1170)

- [] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 
  - OS:
  - Node.js version:
  - Browser version:
  - Is this a global or local install? 
  - Which package manager did you use for the install?
  - Does this issue occur when all plugins are disabled?

- [x] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/.npm-packages/bin/yarn
    npm: 6.9.0 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.0.0-alpha.48
    @vuepress/theme-default:  1.0.0-alpha.48
    vuepress: ^1.0.0-alpha.48 => 1.0.0-alpha.48
  npmGlobalPackages:
    vuepress: Not Found

**Comment by Maissacrement** [comment]
Hi i can you try install : `core-js@2.6.5` it's work for me.

**Comment by f3ltron** [comment]
i will try let me two day to bacck on it

**Comment by f3ltron** [comment]
update core js worked

**Comment by kepi0809** [comment]
Found the solution for my own problem: I needed to wrap the components that contain functional component(s) with `<ClientOnly>`
