### ISSUE TITLE
Title of the Markdown Page is not shown

### ISSUE THREAD

**Issue by rjain15** [vuejs/vuepress#1633]
Using the latest 1.x release .

- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

The markdown H1 (#) title is not getting rendered. 

#### What is expected?

Title to be rendered for each of the markdown page. 
(https://sk8s.kubelabs.io/) 
#### What is actually happening?

Title not getting rendered. 
The markdown is here (https://github.com/rjain15/solid-kubernetes/docs) 
#### Other relevant information

Config files are in https://github.com/rjain15/solid-kubernetes/doc/.vuepress

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version:1.0.0-alpha.48
  - OS: Mac/Ubuntu - Netlify
  - Node.js version: 10.x
  - Browser version: Chrome
  - Is this a global or local install? Global/Local doesn't work in either cases. 
  - Which package manager did you use for the install? yarn
  - Does this issue occur when all plugins are disabled? yes

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by rjain15** [comment]
There was another element which was overflowing. Sorry about the issue.

**Comment by to-jk11** [comment]
I have the same issue and the `<ul>` 's are also not rendering - what was your solution? I have removed all the tags that could get in the way, but it is still not rendering the markdown
