### ISSUE TITLE
vuepress dev server not working

### ISSUE THREAD

**Issue by gilfuser** [vuejs/vuepress#1642]
- [ x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

```sh
# install globally
yarn global add vuepress # OR npm install -g vuepress

# create a markdown file
echo '# Hello VuePress' > README.md

# start writing
vuepress dev
```
or

```sh
# install as a local dependency
yarn add -D vuepress # OR npm install -D vuepress

# create a docs directory
mkdir docs
# create a markdown file
echo '# Hello VuePress' > docs/README.md
```
Then, add some scripts to package.json:

```json
{
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  }
}
```
```sh
yarn docs:dev # OR npm run docs:dev
```

#### What is expected?

Run dev server

#### What is actually happening?

I'm getting this error:
```sh
 DONE  [12:16:18] Build c61380 finished in 4029 ms! 

> VuePress dev server listening at http://localhost:8080/


#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffcbcc73a10[1]    3076 illegal hardware instruction (core dumped)  vuepress dev

```

#### Other relevant information

- [ x] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 0.14.11
  - OS: Ubuntu Studio 18.04
  - Node.js version: 12.0
  - Browser version: Google Chrome 74.0
  - Is this a global or local install? global and/or local
  - Which package manager did you use for the install? I tried both npm and yarn. Removing from one before trying with the other.
  - Does this issue occur when all plugins are disabled? It occurs with the most simple example

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by viniciuskneves** [comment]
Are you using NVM? It looks more like a Node error than Vuepress itself.
There is a similar issue from Gatsby here: https://github.com/gatsbyjs/gatsby/issues/13854
Try to install node without NVM (if you're using it) and try again.
Another solution is to try another version of Node itself.

**Comment by f3ltron** [comment]
Hello @gilfuser thank's for your issue but as @viniciuskneves it's more related to your node environment than vuepress. I am closing the issue for now feel free to re open if you think it's related to vuepress
