### ISSUE TITLE
vuepress 首页语言切换不生效

### ISSUE THREAD

**Issue by PsChina** [vuejs/vuepress#1648]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1、进入 vuepress 生成的静态网页首页（或者在开发环境）。
2、选择切换语言。
3、首页语言未切换，其他页面均切换成功。

bug链接🔗:[首页语言切换不生效bug](https://pschina.github.io/easy-filter/)

源码仓库🔗: [源码仓库](https://github.com/PsChina/eafy-filter-home)

#### What is expected?

当点击选择语言切换语言后首页会随之切换到所选语言。

#### What is actually happening?
当点击选择语言切换语言后首页无任何更改，但其他页面全部切换，包括首页底部的导航按钮。

切换前：

![image](https://user-images.githubusercontent.com/18566166/59176708-82f09d00-8b8c-11e9-8988-4ba3f24488d8.png)

切换后：

![image](https://user-images.githubusercontent.com/18566166/59176739-9dc31180-8b8c-11e9-9a93-8d2b9794129c.png)

强制刷新后：

![image](https://user-images.githubusercontent.com/18566166/59176776-b7fcef80-8b8c-11e9-87ba-95ee35633891.png)

#### Other relevant information

- [x] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:
```bash
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.1
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.0.1 
    @vuepress/theme-default:  1.0.1 
    vuepress: ^1.0.0-rc.1 => 1.0.0-rc.1 
  npmGlobalPackages:
    vuepress: Not Found
```

项目结构:
![image](https://user-images.githubusercontent.com/18566166/59176826-dc58cc00-8b8c-11e9-8ad7-0ad5e813a226.png)
config:
![code](https://user-images.githubusercontent.com/18566166/59176946-1fb33a80-8b8d-11e9-90b7-6e7492e17a37.png)

**Comment by PsChina** [comment]
解决了，这不是一个issuse。导致这个问题的原因是因为我在两个页面 import 同一个对象导致的，改写一下就好了。

将
```js
  import vm from '@views/introduce'
  export default vm
```

改写为

```js
  import vm from '@views/introduce'
  export default Object.assign({},vm)
```

**Comment by PsChina** [comment]
解决了，这不是一个 issues 是一个我的一个 bug 。
解决方案如下:
将首页:
```js
  import vm from '@views/introduce'
  export default vm
```
改为:
```js
  import vm from '@views/introduce'
  export default Object.assign({},vm)
```
避免抛出同一个实例。

**Comment by ulivz** [comment]
😂
