### ISSUE TITLE
Error installing VuePress Globally

### ISSUE THREAD

**Issue by danvega** [vuejs/vuepress#1652]
- [ x] I confirm that this is an issue rather than a question.

## Bug report

I installed VuePress using `yarn global add vuepress` which installed the latest version (1.0.1 I believe) and everything looked like it went fine. When I run the command the `vuepress -V` I get an error. 

#### Steps to reproduce

`yarn global add vuepress`
`vuepress -V`

#### What is expected?

output current version to console

#### What is actually happening?

```
(node:14267) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, scandir '/Users/vega/Library/Calendars'
(node:14267) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14267) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 1.0.1
  - OS: macOS
  - Node.js version: 10.15.0
  - Browser version: Chrome 74
  - Is this a global or local install? Global 
  - Which package manager did you use for the install? yarn
  - Does this issue occur when all plugins are disabled? n/a

- [x ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

```
vega ~ $ npx vuepress info
(node:14316) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, scandir '/Users/vega/Library/Calendars'
(node:14316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by danvega** [comment]
If I actually create a project and run `vuepress dev` everything works fine so I am not sure what is going on.

**Comment by cfjedimaster** [comment]
I am seeing the same, installed via npm, not yarn.

**Comment by cfjedimaster** [comment]
Oh, and on Windows, not Mac.

**Comment by ulivz** [comment]
Obviously it's not an issue of VuePress, please change the position of globally installed packages and install again.

**Comment by cfjedimaster** [comment]
How is this "obviously not an issue of Vuepress"? I didn't change  (afaik) my default npm install directory and Dan didn't mention doing so for Yarn. If the defaults don't work, why wouldn't that be a VuePress issue?

**Comment by cfjedimaster** [comment]
I can confirm changing my npm install directory helps. So are you saying this CLI will not work in a default npm installation (or yarn) folder? If so - why - and is it documented that you must change this setting? I've never seen a npm requirement for a project that forced you to do that.

**Comment by sodatea** [comment]
See https://github.com/vuejs/vuepress/issues/1721
