### ISSUE TITLE
How to add favicon 

### ISSUE THREAD

**Issue by ankit20893** [vuejs/vuepress#1653]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version:
  - OS:
  - Node.js version: 
  - Browser version: 
  - Is this a global or local install? 
  - Which package manager did you use for the install?
  - Does this issue occur when all plugins are disabled?

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by florimondmanca** [comment]
VuePress serves everything in the `.vuepress/public` directory at the root (see [Public Files](https://vuepress.vuejs.org/guide/assets.html#public-files)). Browsers automatically request `/favicon.ico` to get the site's favicon, so you can place your `favicon.ico` file there and it should work as expected (it works for me, at least). :+1:

If you need to generate the favicon file, take a look at [Favicon Generator](https://www.favicon-generator.org/).

**Comment by Sandstedt** [comment]
you can also add them in the .vuepress/config.js file like so:

```js
module.exports = {
  title: 'Title of the site',
  description: 'Description of the site',
  head: [
    ['link', { rel: "apple-touch-icon", sizes: "180x180", href: "/assets/favicons/apple-touch-icon.png"}],
    ['link', { rel: "icon", type: "image/png", sizes: "32x32", href: "/assets/favicons/favicon-32x32.png"}],
    ['link', { rel: "icon", type: "image/png", sizes: "16x16", href: "/assets/favicons/favicon-16x16.png"}],
    ['link', { rel: "manifest", href: "/assets/favicons/site.webmanifest"}],
    ['link', { rel: "mask-icon", href: "/assets/favicons/safari-pinned-tab.svg", color: "#3a0839"}],
    ['link', { rel: "shortcut icon", href: "/assets/favicons/favicon.ico"}],
    ['meta', { name: "msapplication-TileColor", content: "#3a0839"}],
    ['meta', { name: "msapplication-config", content: "/assets/favicons/browserconfig.xml"}],
    ['meta', { name: "theme-color", content: "#ffffff"}],
  ],
  ...
}
```

**Comment by florimondmanca** [comment]
^ Oh yes that's actually a *required* change to include favicons in other formats than `favicon.ico`. Nice one!

**Comment by kaceo** [comment]
When I put a "head" configuration inside the project's  .vuepress/config.js, that works in the final site build.

But when I do the same configuration changes to a custom theme's index.js, and makes use of that custom theme in a project, the favicon lines are not applied into the build.  

Any idea why?

**Comment by mesqueeb** [comment]
> you can also add them in the .vuepress/config.js file like so:
> 
> ```js
> module.exports = {
>   title: 'Title of the site',
>   description: 'Description of the site',
>   head: [
>     ['link', { rel: "apple-touch-icon", sizes: "180x180", href: "/assets/favicons/apple-touch-icon.png"}],
>     ['link', { rel: "icon", type: "image/png", sizes: "32x32", href: "/assets/favicons/favicon-32x32.png"}],
>     ['link', { rel: "icon", type: "image/png", sizes: "16x16", href: "/assets/favicons/favicon-16x16.png"}],
>     ['link', { rel: "manifest", href: "/assets/favicons/site.webmanifest"}],
>     ['link', { rel: "mask-icon", href: "/assets/favicons/safari-pinned-tab.svg", color: "#3a0839"}],
>     ['link', { rel: "shortcut icon", href: "/assets/favicons/favicon.ico"}],
>     ['meta', { name: "msapplication-TileColor", content: "#3a0839"}],
>     ['meta', { name: "msapplication-config", content: "/assets/favicons/browserconfig.xml"}],
>     ['meta', { name: "theme-color", content: "#ffffff"}],
>   ],
>   ...
> }
> ```

Is this the official method to add favicons to VuePress ?

**Comment by xgqfrms** [comment]
# official way

> according to the official docs, you can create a `public` folder, and put your favicon.ico in it, that all.

![image](https://user-images.githubusercontent.com/7291672/106696226-35555d80-6617-11eb-900b-ec54e490a300.png)

## refs

https://vuepress.vuejs.org/guide/assets.html#public-files

**Comment by Sandstedt** [comment]
@xgqfrms Thats great for just a simple favicon.ico, but if you wanna add other meta information, this doesn't help. But good to point out.

**Comment by aeron7** [comment]
Also, Read this - https://vuepress.vuejs.org/plugin/official/plugin-pwa.html#usage
