### ISSUE TITLE
seems hard to add new layout to default theme

### ISSUE THREAD

**Issue by icaruseeee** [vuejs/vuepress#1657]
## Feature request

Recently I'm trying to use vuepress for personal blog. I love stylus of default theme and try to use blog plugin to form a list page. But it's hard to combine them since some related layouts
are not included in default theme.

Is it possible for us to modify default theme? Thank.

**Comment by ngocbnv-0940** [comment]
@icaruseeee 
You can inherit the default theme for customization
https://v1.vuepress.vuejs.org/theme/inheritance.html
Demo: [My blog](https://nobi.dev/)

**Comment by icaruseeee** [comment]
> @icaruseeee
> You can inherit the default theme for customization
> https://v1.vuepress.vuejs.org/theme/inheritance.html
> Demo: [My blog](https://nobi.dev/)

Thank you bro. I didn't find it on 1.x docs. 
Will try inheritance later~
