### ISSUE TITLE
Options of @vuepress/medium-zoom do not work

### ISSUE THREAD

**Issue by whiteeagle44** [vuejs/vuepress#1660]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?
This code (config.js)
``` 
   plugins: {
        '@vuepress/medium-zoom': {
          selector: 'img',
          options: {
              background: "blue",
              margin: 16
          }
        }
    }
```
should make the image zoom on click with blue background and a margin of 16px.

#### What is actually happening?
It does zoom image on click but with white background and no margin.

#### Other relevant information
This plugin is installed with yarn.

- [x] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 1.0.0-rc.1
  - @vuepress/plugin-medium-zoom version: ^1.0.0-rc.1
  - VuePress theme: default
  - Is this a global or local install? local
  - Which package manager did you use for the install? Yarn

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
This issue has been fixed at https://github.com/vuejs/vuepress/commit/42f19e0ce653e42ea1187a9f108f884b92e1febd
