### ISSUE TITLE
Can NOT work with markdown-it-katex.

### ISSUE THREAD

**Issue by long568** [vuejs/vuepress#1662]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?
Show Math-Formula
#### What is actually happening?
It works fine on my macbook, but  it does not work on my macmini and pc(windows).
$a=b^{-6}$, here is one of Math-Formula is used.
It seems like something missing on the 2 computers.
#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version: 1.0.1
  - OS: MacOSX / Windows
  - Node.js version: 10.16.0
  - Browser version: Google Chrome 75.0.3770.80
  - Is this a global or local install? 
Global
  - Which package manager did you use for the install?
None
  - Does this issue occur when all plugins are disabled?
No

- [ ] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
Did markdown-it-katex itself work under macmini and windows?

**Comment by long568** [comment]
> Did markdown-it-katex itself work under macmini and windows?

No, 
I reinstalled nodejs on the macbook, then it does NOT work too.
So, I guess, some modules is NOT included in the default package of Node.js.
I checked some web created by other one, they works fine in my google chrome.

**Comment by FriendlyUser** [comment]
markdown-it-katex worked for me in my project for vuepress@1.0.3, keep in mind you may need to update your config file and include a link to css style sheet/
```
head: [
    ['link', { rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css' }],
	  ['link', {href: 'https://fonts.googleapis.com/icon?family=Material+Icons', rel :'stylesheet'}]
  ],
```

**Comment by Mister-Hope** [comment]
You can try vuepress-plugin-mathjax. It works well.

**Comment by long568** [comment]
It is my fault. Use "extendMarkdown" to replace the old string, then it works fine.

**Comment by lianyongxing** [comment]
Hello, I ran into the same problem as you, how did you solve it
