### ISSUE TITLE
side bar 在vuepress dev dos 模式下运行良好，vuepress build docs却会失败

### ISSUE THREAD

**Issue by TRUEJASONFANS** [vuejs/vuepress#1665]
#### Steps to reproduce
https://github.com/TRUEJASONFANS/front_doc_repo
yarn run dev -> successfully
yarn run build -> failed

#### What is actually happening?
![image](https://user-images.githubusercontent.com/5670289/59652441-4b06dc80-91c0-11e9-8ff1-3a50fc81944b.png)

#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:
  - VuePress version: "^1.0.0-rc.1"
  - OS: Win 10
  - Node.js version:  v10.15.1
  - Browser version:  chrome
  - Is this a global or local install?  local
  - Which package manager did you use for the install? yarn

**Comment by TRUEJASONFANS** [comment]
貌似是我在文章里面手写的导航有问题。

**Comment by OrangeSAM** [comment]
解决了吗...我现在也遇到了。
