### ISSUE TITLE
how to stop external libraries in build mode

### ISSUE THREAD

**Issue by xxholly32** [vuejs/vuepress#1669]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

i wrote a component with openlayer.  can run in dev mode but cant build in build mode

#### What is expected?

build works 

#### What is actually happening?

build failed with error "window is not definded"

#### Other relevant information

[ssr docs](https://ssr.vuejs.org/#why-ssr) not tell us how to avoid external libraries. i wonder if vuepress docs can show me how to do. or maybe provide a config to stop ssr 

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:

  - VuePress version:
  - OS:
  - Node.js version: 
  - Browser version: 
  - Is this a global or local install? 
  - Which package manager did you use for the install?
  - Does this issue occur when all plugins are disabled?

- [x] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
See: https://v1.vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions

**Comment by xxholly32** [comment]
ty for your help
