### ISSUE TITLE
sidebar menu default/index page

### ISSUE THREAD

**Issue by aliartiza75** [vuejs/vuepress#1671]
## Feature request
Hello guys,

I am wondering if there is a way to load a default page whenever I click on a drop-down item that is given on the left sidebar. As I am not a frontend guy I want to apologize if I used any wrong words. 

I am unable to find anything regarding this feature, therefore, I have created a feature request for it.

Thank you in advance.

#### What problem does this feature solve?
Clicking on the drop-down item a default page should load on the right side.

#### What does the proposed API look like?
Not applicable

#### How should this be implemented in your opinion?
When someone clicks on the left sidebar drop-down item it should do two things:

* Show the items of the drop-down list.
* Load a default page on the right side.

#### Are you willing to work on this yourself?
No, I can't because I don't have frontend experience.

**Comment by aliartiza75** [comment]
@ulivz kindly have a look at this issue.

**Comment by aliartiza75** [comment]
@xr0master currently, when I click on the collapsible sidebar a drop-down list is shown but on the right side, a default page(README.md) is being shown. 

What I want is to display a default page instead of README.md regarding the collapsible sidebar unless the user clicks on any particular item of the dropdown menu

**Comment by aliartiza75** [comment]
@xr0master waiting for your response!

**Comment by aliartiza75** [comment]
@xr0master waiting for your response!

**Comment by aliartiza75** [comment]
@xr0master waiting for your response.

**Comment by aliartiza75** [comment]
@xr0master waiting for your response

**Comment by newsbielt703** [comment]
Hey @aliartiza75, let me help you. 

> What I want is to display a default page instead of README.md regarding the collapsible sidebar unless the user clicks on any particular item of the dropdown menu

Why don't you put what you want to display into `README.md`. You said you want a default page, the truth is `README.md` under the that certain group (folder) is a default page.

**Comment by aliartiza75** [comment]
@newsbielt703 okay
