### ISSUE TITLE
Markdown extension works in main project, does not work in custom theme

### ISSUE THREAD

**Issue by kaceo** [vuejs/vuepress#1672]
[Y ] I confirm that this is an issue rather than a question.

## Bug report
Configuring Markdown extension works in main project, but not in custom theme.

I am trying to make a custom theme for our team which incorporates most of our frequently used markdown plugins inside it, so that each project does not need local configuration.

#### Steps to reproduce
This section 

~~~
markdown: {
  extendMarkdown: md => {
    md.use(require('markdown-it-deflist'))
    md.use(require('markdown-it-attrs'))
  },
}
~~~

works when placed in main project's .vuepress/config.js

but does not work if moved to the custom theme's index.js

#### What is expected?
Should work in both location, since they implement the same API

#### What is actually happening?
Only works in 1st case not in second case.  

#### Other relevant information

- [ ] My VuePress version is lower and euqal than `1.0.0-alpha.47`:
- [ Y] My VuePress version is higher than `1.0.0-alpha.47`, the following is the output of `npx vuepress info` in my VuePress project:

 System:
    OS: Linux 4.19 Debian GNU/Linux buster/sid undefined
    CPU: (2) x64 Intel(R) Pentium(R) Dual  CPU  E2200  @ 2.20GHz
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.0.1
    @vuepress/theme-default:  1.0.1
    vuepress: ^1.0.1 => 1.0.1
  npmGlobalPackages:
    vuepress: Not Found

**Comment by ulivz** [comment]
Using:

```js
module.exports = {
  extendMarkdown: md => {
    md.use(require('markdown-it-deflist'))
    md.use(require('markdown-it-attrs'))
  },
}
```

Instead of:

```js
module.exports = {
  markdown: {
    extendMarkdown: md => {
      md.use(require('markdown-it-deflist'))
      md.use(require('markdown-it-attrs'))
    }
  }
}
```
