### ISSUE TITLE
V0官网上自定义markdown-it插件的配置参数居然是config（无效）而不是extendMarkdown（有效）

### ISSUE THREAD

**Issue by choaklin** [vuejs/vuepress#1673]
V0官网上自定义markdown-it插件的配置参数居然是config（无效）而不是extendMarkdown（有效）

**Comment by ulivz** [comment]
你用的是 1.x 吧，那为什么要要看 0.x 的文档？

**Comment by choaklin** [comment]
我操作时参考的是V0的文档， 安装vuepress 用的命令也是文档上的  npm install vuepress，这本该是0.x 版本吧？ 1.x的安装命令不是 npm install -g vuepress@next？

现在才发响 package.json 里的 vuepress 确实是 "^1.0.1"

**Comment by ulivz** [comment]
1.0 都正式发布了，为什么还要 next？
