### ISSUE TITLE
documentation of google analytics plugin wrt IP anonymization

### ISSUE THREAD

**Issue by shadiakiki1986** [vuejs/vuepress#1687]
#### What problem does this feature solve?
The documentation page [here](https://v1.vuepress.vuejs.org/plugin/official/plugin-google-analytics.html#install) says "consider setting Google Analytics to anonymize IPs",

but he plugin source code already enables IP anonymization ([ref](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-google-analytics/enhanceAppFile.js#L20)).

I was mislead by the documentation to think that I need to make a modification or configuration somewhere to enable IP anonymization.

#### What does the proposed API look like?

The documentation should say that IP anonymization is already enabled in this plugin (in version 1 and not in v0?)

#### How should this be implemented in your opinion?

Maybe re-word the statement

#### Are you willing to work on this yourself?

Sure!

PS: Awesome project!

**Comment by ulivz** [comment]
Thanks for the suggestion, welcome to help us to enhance the docs!

**Comment by shadiakiki1986** [comment]
Shall I submit a PR about it?

**Comment by ulivz** [comment]
@shadiakiki1986 Yes, feel free to submit it
