### ISSUE TITLE
ctx.isProd 一直是 undefined

### ISSUE THREAD

**Issue by eliot-ye** [vuejs/vuepress#1691]
不知道是不是我用错了，我在以下情况都试过了，ctx.isProd 一直是 undefined

```js
module.exports = (options, ctx) => ({
  async ready(){
    console.log(ctx.isProd) //undefined
  }
})
```

```js
module.exports = (options, ctx) => {
  console.log(ctx.isProd) // undefined
}
```

只有在 generated 生命周期里才是 true，但 generated 生命周期本来就是 build 的时候才触发的，没什么用吧？或者只有特定的 dev build 的时候才有用？

```js
module.exports = (options, ctx) => ({
  async generated(){
    console.log(ctx.isProd) // true
  }
})
```

**期望：可以在所有地方使用 ctx.isProd，或者有一个 API 可以区分 dev 和 build**

**Comment by ulivz** [comment]
Please follow our issue guidelines and submit an issue with issue template and English, Thanks.
