### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by Luxiaoshi** [vuejs/vuepress#1692]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

When I develop my docs in development environment, it is ok.
When i build it and put it on my server with nginx, it  is also ok.
However when i refresh the page with routes like this http://xxx.com/develop
It has the error below
![image](https://user-images.githubusercontent.com/8713879/60865729-38c90d00-a259-11e9-9914-869adff1ab58.png)

**Comment by MaxHershey** [comment]
I'm getting the same issue. It appears to be related to the SearchBox Component perhaps?

**Comment by Luxiaoshi** [comment]
I have resolved this question, which i have wrong nginx config.

**Comment by MaxHershey** [comment]
> I have resolved this question, which i have wrong nginx config.

Do you mind me asking what the config issue was?

**Comment by busyrat** [comment]
I had the same problem, and then I found out it had to do with `document`

enhanceApp.js
```
  if (typeof window !== 'undefined') { // add this line
    window.document.xxx
  }
```

**Comment by hugojing** [comment]
> I had the same problem, and then I found out it had to do with `document`
> 
> enhanceApp.js
> 
> ```
>   if (typeof window !== 'undefined') { // add this line
>     window.document.xxx
>   }
> ```

I have no enhanceApp.js file and no nginx, but still have this issue.

**Comment by agrass-GitHub** [comment]
how to solve problems ?

**Comment by thaycacac** [comment]
I had the same problem.

**Comment by cwaring** [comment]
I also noticed this issue appear once I enabled the PWA plugin, so it may be related to the caching. If I find the root cause I'll report back here.

**Comment by ludanxer** [comment]
Can anyone who encounters this problem build a minimal reproduction?

Or describe how to reproduce the problem?

**Comment by hugojing** [comment]
> Can anyone who encounters this problem build a minimal reproduction?
> 
> Or describe how to reproduce the problem?

You can see this:  https://douweimusic.com/albums/

Code repo: https://github.com/hugojing/douwei-music

**Comment by ludanxer** [comment]
Thx for your repo @hugojing ,

In your case, simply change all of the `[<h2>***</h2>](***)` into `## [***](***)` will solve the problem.

I don't know if others are suffering from this problem because of the similar reason, but I suggest you all double check your HTML syntax in your corresponding page.

If anyone still can't fix this problem, pls provide a minimal reproduction or describe how to reproduce the problem.

**Comment by binnymaster** [comment]
Hey I'm also getting same error, My application is based on vue.js 
![Screen Shot 2020-02-13 at 2 52 15 PM](https://user-images.githubusercontent.com/14200541/74472798-7eddf300-4e70-11ea-8613-501171f1ce31.png)

**Comment by lucduong** [comment]
@Luxiaoshi Could you share the `nginx` config? I got the same error and figured out it related to `nginx`. But Don't know how to fix this.

**Comment by rwpswami** [comment]
I am still getting this issue. Anybody got solution on this?

**Comment by mashpie** [comment]
Just a hint: Another common mistake is to use dynamic vue components that should render client side but forget to ignore them in static builds... 99% of those issues in our projects were missing `<ClientOnly>`. So try:

```html
<ClientOnly>
  <NonSSRFriendlyComponent/>
</ClientOnly>
```

and read https://vuepress.vuejs.org/guide/using-vue.html

**Comment by gcharang** [comment]
Leaving a comment here in case someone else made the same mistake as me.
using an XML comment like: `<!-- Comment -->` inside a markdown table in a .md file used by Vuepress causes this error as well

**Comment by vikrantmagare6** [comment]
> Just a hint: Another common mistake is to use dynamic vue components that should render client side but forget to ignore them in static builds... 99% of those issues in our projects were missing `<ClientOnly>`. So try:
> 
> ```
> <ClientOnly>
>   <NonSSRFriendlyComponent/>
> </ClientOnly>
> ```
> 
> and read https://vuepress.vuejs.org/guide/using-vue.html

I also have same issue in my case it on v-html 
example : <p v-html="item.description"></p>
so I just wrap it it resolve
<client-only>
            <p v-html="item.description"></p>
            </client-only>

**Comment by vikrantmagare6** [comment]
I also have same issue in my case it on v-html 
example : <p v-html="item.description"></p>
so I just wrap it it resolve
<client-only>
            <p v-html="item.description"></p>
            </client-only>

**Comment by beMySun** [comment]
> Just a hint: Another common mistake is to use dynamic vue components that should render client side but forget to ignore them in static builds... 99% of those issues in our projects were missing `<ClientOnly>`. So try:
> 
> ```
> <ClientOnly>
>   <NonSSRFriendlyComponent/>
> </ClientOnly>
> ```
> 
> and read https://vuepress.vuejs.org/guide/using-vue.html

YES, it works ! 💗

**Comment by Gary50613** [comment]
still having the problem

but it only happened when it deploy to production enviorement
I didnt get any error when running in local enviorement
![image](https://user-images.githubusercontent.com/33802653/134111761-ac596c41-b75a-4ad7-bb39-4e2513f1e04b.png)

**Comment by Gary50613** [comment]
> still having the problem
> 
> but it only happened when it deploy to production enviorement
> I didnt get any error when running in local enviorement
> ![image](https://user-images.githubusercontent.com/33802653/134111761-ac596c41-b75a-4ad7-bb39-4e2513f1e04b.png)

resolved, same as nuxt/nuxt.js#1552
disable cloudflare auto minify worked for me
![image](https://user-images.githubusercontent.com/33802653/134119020-267b83a5-ab13-4287-9698-d3fa6bbb21ae.png)

**Comment by huangzonggui** [comment]
When I wrote a typo, the development environment was normal, but the error burst after deployment
![image](https://user-images.githubusercontent.com/15973603/145417702-230c03cc-21bf-4d70-a88c-82968534057a.png)

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by QuinnTian** [comment]
我也遇到了

**Comment by FanSirSan** [comment]
nginx

try_files $uri $uri/ /index.html;

**Comment by littlegreay** [comment]
how to solve the problem，it does not solve the problem
<client-only>
<p v-html="item.description"></p>
</client-only>

**Comment by littlegreay** [comment]
> 

no

**Comment by ctrlaltdylan** [comment]
Just adding to this thread, I'm experiencing this same issue with Vercel as the host.

However, it's very strange, I have run the build locally with a simple express server:

```javascript
import express from "express";
const app = express();

app.use("/", express.static("docs/.vuepress/dist"));

app.listen(8000);
```

And the site works completely fine.

It's only on Vercel preview deployments where this bug occurs. And it's only on page refreshes, not on initial load. 

There's no server side components running on the site, and the `enhanceApp.js` was fully commented out as a test, no change.

Will report back when I learn more.

**Comment by Aleksandr-JS-Developer** [comment]
Carefully check your syntax in MD files and the correctness of the names of the values in the configuration. If there are errors in the MD and configuration, the build proceeds normally, without errors, but the build contains errors that cause this exception. In my case, I had the wrong path in `config.js > themeConfig > logo`

**Comment by cyanar** [comment]
I have resolved this problem.
In my case 
I change the syntax in the related makdown file and it works

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by PowersYang** [comment]
I solved this question by change nginx config from `try_files $uri /index.html` to `try_files $uri $uri/ /index.html`. Final results like:
```
server {
    # omit
    # try_files $uri /index.html;
    try_files $uri $uri/ /index.html;
}
```

**Comment by jvectormap** [comment]
> I had the same problem, and then I found out it had to do with `document`
> 
> enhanceApp.js
> 
> ```
>   if (typeof window !== 'undefined') { // add this line
>     window.document.xxx
>   }
> ```





https://lnkr.fun/9ed4de5

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!
