### ISSUE TITLE
Help deploying to relative urls 

### ISSUE THREAD

**Issue by werner-kotze** [vuejs/vuepress#1695]
I've read most of the previous issues regarding this problem but I still can't seem to come right.

I'm intergating vuepress into my current project and it works perfectly locally but I'm having issues with the deployment.

Setting the `base` directory works locally but when I deploy, the base should change to the branch I'm deploying to. For example locally I would deploy to local.test/docs/foo/ but when I deploy to staging it would be qa.staging/feature-branch/docs/foo.

**Comment by ulivz** [comment]
We recommend you to ask question in the [Discord server](https://vue-land.js.org/), [forum](https://forum.vuejs.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress).

BTW, please DON'T delete the issue template!
