### ISSUE TITLE
GA in config.js don't work

### ISSUE THREAD

**Issue by zloyAltr** [vuejs/vuepress#1696]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Use vuepress@1.0.2

.vuepress\config.js
```
module.exports = {
....
ga: 'UA-000000000-0',
....
```
It is as described in [tutorial](https://vuepress.vuejs.org/config/#ga).
But the GA's script does not appear in the code.
If you install @vuepress/plugin-google-analytics (1.0.2)  and use plagins, the script appears.
.vuepress\config.js
``` js
module.exports = {
....
plugins: [
      ['@vuepress/google-analytics',
        {
          'ga':'UA-000000000-0'
        }
      ]
    ]
```
By default @vuepress/plugin-google-analytics is not in the directory node_modules\@vuepress\

What am I doing wrong?

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
See `Migration from 0.x`: https://v1.vuepress.vuejs.org/miscellaneous/migration-guide.html#ga

**Comment by lz1998** [comment]
Does it work for ga4?
