### ISSUE TITLE
which version to install? @next or @latest

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vuepress#1697]
When looking at the docs, it says [here](https://v1.vuepress.vuejs.org/guide/getting-started.html#global-installation) to install via `@next`.

However, with `@next` it installs `vuepress@1.0.0-rc.1`

With `@latest` instead I get `vuepress@1.0.2`.

What is the best way to install this library?

**Comment by ulivz** [comment]
```
yarn add vuepress
```

**Comment by mesqueeb** [comment]
@ulivz thanks! I saw you updated the docs as well! Keep up the good work!!!
much appreciated ;)
