### ISSUE TITLE
can't override css styling

### ISSUE THREAD

**Issue by oupala** [vuejs/vuepress#1709]
I'm trying to migrate from VuePress 0.14.11 to 1.0.2.

I used to override the default theme using an `override.styl` file with some new colors:

```styl
// showing default values
$accentColor = #ff6600
$textColor = #2c3e50
$borderColor = #ff6600
$codeBgColor = #282c34
```

When I switch to VuePress 1.0.2, my overriding style is not applied at all (and do not seem to be in the published css). I also have a warning at build time:

> tip override.styl has been deprecated from v1.0.0, using .vuepress/styles/palette.styl instead.

If I rename the file `override.styl` to `palette.styl`, I don't have the warning any more but the overriding style is still not applied.

By the way, the new `palette.styl` is not yet in [the documentation](https://vuepress.vuejs.org/default-theme-config/#simple-css-override).

My question is then simple: how can we override the styling of the default theme with VuePres 1.x.x?

**Comment by ulivz** [comment]
As you mentioned:

> `override.styl` has been deprecated from v1.0.0, using `.vuepress/styles/palette.styl` instead.

Besides of renaming, you also need to put this file under `styles` directory.

**Comment by oupala** [comment]
Thanks a lot @ulivz! You had the right answer.

This information should definetly be in the documentation.
