### ISSUE TITLE
How I exclude css, js file for webpack config

### ISSUE THREAD

**Issue by dacsang97** [vuejs/vuepress#171]
I want to exclude `.css` file into `style.css` chunk. Example for integrating Netlify CMS to Vuepress, I need ignore `cms.css` file, not compile into `style.css`. 
In progress integrate Netlify CMS into Vuepress, in `development mode` it seems OK, but in `production mode`, `cms.js` (Netlify script) and `cms.css` also load in the root path (all route of app).
I want `cms.js` and `cms.css` only show in `/admin` path.
_
**Admin.vue**
``` vue
<template>
  
</template>

<script>
import CMS from "netlify-cms";
import "netlify-cms/dist/cms.css";
import netlifyIndentityWidget from "netlify-identity-widget";

export default {
  mounted() {
    window.netlifyIndentityWidget = netlifyIndentityWidget;
    netlifyIndentityWidget.init();
  }
};
</script>
```
_
**enhanceApp.js**
``` js
const Admin = () => import("./Admin");

export default ({ Vue, options, router }) => {
  router.addRoutes([
    {
      path: "/admin",
      component: Admin
    }
  ]);
};

```

**Comment by dgpgdev** [comment]
maybe you can check 
```js
 chainWebpack: config => {
    const jsRule = config.module.rule('js')
  }
```
in your config.js file

**Comment by dacsang97** [comment]
@dgpgdev thank you, I will try.

**Comment by ulivz** [comment]
Same to @dgpgdev's anwser.

```js
 chainWebpack: config => {
    config.module
      .rule('js' /* or css */)
      .exclude 
        .add(/* Your extra excluded files */)
  }
```

See: [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain)
