### ISSUE TITLE
Ability to switch SearchBox and navbar links positions

### ISSUE THREAD

**Issue by thunderBiscuit** [vuejs/vuepress#1713]
#### What problem does this feature solve?
The default theme keeps the searchbox to the left of the navbar links, which is not as intuitive as having it as the furthest item on the right of the navbar. The searchbox often ends up somewhere in the middle of the page. The ability to force it to be the the last item on the navbar would be great!

#### What does the proposed API look like?
I'm not sure... some option in `themeConfig`, something like `searchBoxLast: true`?

#### Are you willing to work on this yourself?
I'm sorry I don't think I know Vue enough yet... if someone would like to give me pointers I am more than happy to give it a try!

**Comment by thunderBiscuit** [comment]
Ok I now understand this should be easily achieved using theme inheritance. 

I am having troubles making it work however. Where can I go to ask questions? I added `extend = '@vuepress/theme-default'` to my config.toml file and added a `.vuepress/theme/components/Navbar.vue` file to test it, but the compiler is telling me that it cannot resolve `Layout.vue`. I was under the impression that only the file I needed to change needed to be included in my `theme` directory.

Any idea where I am going wrong? Also, if this is not the right place to ask these questions, let me know where I should!

Cheers!

**Comment by ulivz** [comment]
Yes, this should be easily achieved using theme inheritance.

> Where can I go to ask questions?

You can ask question in the [Discord server](https://vue-land.js.org/), [forum](https://forum.vuejs.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress).

**Comment by thunderBiscuit** [comment]
Just for people coming into this thread; it turns out that if you want the theme inheritance to work, you need a file called `index.js` in the root directory of your `.vuepress/theme`.  This file needs to have at least the following:
```
module.exports = {
    extend: '@vuepress/theme-default'
}
```

This is not quite clear from the docs! I hope it's the proper way to do it. Cheers!

**Comment by Aratramba** [comment]
For anyone trying to do this without updating the theme, I achieved this updating index.styl:

```css
.search-box {
  order: 1;
  margin-right: 0;
  margin-left: 1rem;

  .suggestions {
    left: auto !important;
    right: 0 !important;
  }
}
```
