### ISSUE TITLE
`plugin-register-components` only works with `shorthand` syntax

### ISSUE THREAD

**Issue by chris-dura** [vuejs/vuepress#1717]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Using Plugin longhand with `@vuepress/plugin-register-components` breaks with explicit component registering.

The general "using a Plugin" docs indicate you _can_ use shorthand, but doesn't really make it clear that _only_ shorthand will work with explicit registering.

#### Steps to reproduce

```js
// .vuepress/config.js

module.exports = {
  plugins: [
    [ '@vuepress/register-components',
      {
        components: [
          {
            name: 'some-other-name',
            path: 'MyComponent.vue'
          }
        ]
      }
    ]
  ]
}
```

#### What is expected?

No console errors.

#### What is actually happening?

Console error:
```shell
Module not found: Error: Can't resolve 'MyComponent.vue' in '/Users/CDura/my-project/node_modules/@vuepress/core/.temp/app-enhancers'
```

#### Other relevant information

Using the shorthand syntax, instead produces no console errors.
```js
plugins: [
    [ 'register-components',
...
```

- Output of `npx vuepress info` in my VuePress project:

```shell
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 64.0
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.0.2 
    @vuepress/theme-default:  1.0.2 
    vuepress: 1.0.2 => 1.0.2 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ulivz** [comment]
The "path" option only accepts absolute path.
