### ISSUE TITLE
app.js is loaded slowly

### ISSUE THREAD

**Issue by liycode** [vuejs/vuepress#172]
- Windows
- Node.js 8.11.1
- VuePress 0.7.0
- Google Chrome 65.0.3325.181
- global install
- package manager npm

When I first visited,the app.js is loaded slowly.

![20180420181004](https://user-images.githubusercontent.com/12079366/39046220-06fb0570-44c8-11e8-83c7-235eb4680760.jpg)

**Comment by ycmjason** [comment]
Does this happen only on the first visit? Or does it persist being slow?

**Comment by liycode** [comment]
Only the first time.When I skip to other pages it does't happen.

**Comment by ycmjason** [comment]
@liycode can you try actual reload without restarting the server to see if `app.js` is served slowly too? 

Anyways, the speed of the dev server shouldn't be a concern after all it is just a dev server. You are not supposed to use it for production. See more about deploying your content [here](https://vuepress.vuejs.org/guide/deploy.html)

**Comment by liycode** [comment]
Thanks!
