### ISSUE TITLE
Announcement on the Establishment of VuePress Team

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#1726]
With the growing ecosystem of VuePress, it will be more and more difficult for only my spare time to support all the daily maintenance.

In such a state, it seems also difficult for us to reach to the next stage (platform capability) of R&D:

<img width="400" src="https://user-images.githubusercontent.com/23133919/62010844-65aa7900-b1a2-11e9-9b04-2a4aa37c9cac.png">

To break the current situation, as a core maintainer, I plan to set up a team - so I'm here to post a recruitment announcement.

---
 
If you want to participate in the maintenance or development of VuePress in your spare time, please contact chl814@foxmail.com with following information:

### Title

${name} - ${location} - Apply to join the VuePress team

### Content

- Github
- Expected roles (developer, curator, designer, community spokesperson etc.)
- Simple self-introduction

I will reply to your application ASAP.

---

Note that open source means that you need to invest your spare time without material rewards. So before you consider applying becoming a member of the VuePress team, think carefully about whether you are really in a pure love of Vue and open source.

Of course, even without material rewards, you can acquire these valuable experiences: the fresh and advanced static website generation technology, participation in the maintenance of a well-known open source product, leave your name in the history of Vue / VuePress, etc.

Welcome to join us. ❤️

---

// cc @yyx990803 @kazupon

**Comment by ulivz** [comment]
Actually, I don't want every member to be under too much pressure. so I expect our team to look like this in the end:

1. Curator of English Documents (1-2 persons) - focus on [docs](https://github.com/vuejs/vuepress/tree/master/packages/docs);
2. Curator of Chinese Documents (1-2 persons) - focus on [docs/zh](https://github.com/vuejs/vuepress/tree/master/packages/docs/zh/);
3. Lead of Plugin Ecology (1-2 persons) - focus on [@vuepress/plugin-*](https://github.com/vuejs/vuepress/tree/master/packages/@vuepress);
4. Curator of Blog plugin and theme (2-3 persons) - focus on [theme-blog](https://github.com/ulivz/vuepress-theme-blog) & [plugin-blog](https://github.com/ulivz/vuepress-plugin-blog);
5. Core maintainers, (2-3 persons); focus on [@vuepress/core](https://github.com/vuejs/vuepress/tree/master/packages/@vuepress/core);
6. Lead of innovation ability (2-3 persons);
7. Director of Visual Design (1 person), focus on the enhancement of official default docs theme and blog theme;

**Comment by f3ltron** [comment]
this is awesome ! Of course i will apply ! :+1:

**Comment by lauragift21** [comment]
Hi @ulivz I got your mail. Will be interested in taking on the role of Curator of English Documents.

**Comment by ShailenNaidoo** [comment]
Hi @ulivz, I am interested in taking a role as curator of English documents.

**Comment by malgamves** [comment]
Hey @ulivz I'd like to take up something with the Blog Plugin and theme don't mind helping out with English Documentation.

**Comment by blakemorgan** [comment]
@ulivz I'd like to take on the position of a core maintainer. If not that, then a curator of English documentation.

**Comment by starkovsky** [comment]
Hi @ulivz 
Position Curator of Russian Documents
(After finished translation and send PR)

**Comment by cfjedimaster** [comment]
@ulivz I'd like to take on a position related to the docs, English language.

**Comment by danvega** [comment]
@ulivz I would like to work on the english docs.

**Comment by joshgrib** [comment]
@ulivz I'd like to work on plugin ecology, I'd also be interested in helping with English documentation

**Comment by edisdev** [comment]
@ulivz  Hi Sir, 

I would you like to work software development for project. :) I will make PR :)

**Comment by IgorHalfeld** [comment]
@ulivz 
I would you like to work with Plugin Ecology, Blog plugin and theme or Core Maintainers :D

**Comment by mayashavin** [comment]
@ulivz I'd love to take
1. Core maintainers
or
2. Lead of innovation ability

**Comment by jamesgeorge007** [comment]
@ulivz I would really love to be a part of the core-maintainers team :heart:

**Comment by vinayakkulkarni** [comment]
Hey @ulivz 

First of all, I'm grateful for this opportunity & extremely delighted!

As mentioned in the reply email, I'd be honoured to contribute towards the plugin ecosystem. I've already had some experience regarding building / updating & integrating 3rd party plugins in the Nuxt ecosystem and I think I could be good candidate for this.

- First preference would be contributing in plugin ecosystem, the `@vuepress/plugin-*`!
- Second would be contributing towards `@vuepress/core` but I'd need some code walk through or docs related to the internals.

Cheers 🍻

**Comment by nkhdo** [comment]
Hi @ulivz , I would love to maintain the blog plugin and theme.
Cheers!

**Comment by ishan-me** [comment]
Hi @ulivz I am extremely happy and eager to contribute to the project. It would be a great responsibility if I can get the role of Designer.

Cheers 🍻

**Comment by f3ltron** [comment]
Thank you everyone for the enthusiastic response to the announcement! 

At this time, we have filled the primary roles for the core team.  

However, we still strongly encourage those who desire to join the core team to continue making contributions in their desired area of expertise so we can keep you in mind when additional spots open up on the core team.

VueJS(PRESS) lovers <3
