### ISSUE TITLE
Globally disable Prev/Next links

### ISSUE THREAD

**Issue by chris-79** [vuejs/vuepress#1727]
## Feature request

Add option to globally disable Previous and Next links

#### What problem does this feature solve?

Not having to add code to each-and-every file/page

#### What does the proposed API look like?

¯\\\_(ツ)_/¯ Dunno

#### How should this be implemented in your opinion?

Options in `themeConfig`

#### Are you willing to work on this yourself?

Can't :(

**Comment by chris-dura** [comment]
These are added via a plugin in the default theme, so you could just remove that plugin in your config, I believe. Or, if you want to go nuclear, add this one line of CSS...
