### ISSUE TITLE
Update the domain setting for documentation

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#1737]
## Feature request

Since 1.x is stable enough, it's time to use [vuepress.vuejs.org](https://vuepress.vuejs.org) to host the latest documentation, while [v0.vuepress.vuejs.org](https://v0.vuepress.vuejs.org) could be used for the docs of 0.x.

Note that after this change, the [v1.vuepress.vuejs.org](https://v1.vuepress.vuejs.org) should be CNAME or redirected to [vuepress.vuejs.org](https://vuepress.vuejs.org). 

#### What problem does this feature solve?

User can see the latest documentation with the short website link.

#### What does the proposed API look like?

N/A

#### How should this be implemented in your opinion?

Current vuepress.vuejs.org (v0.x) gets moved to v0.vuepress.vuejs.org
Current v1.vuepress.vuejs.org (v1.x) gets moved to vuepress.vuejs.org
Redirect from v1.vuepress.vuejs.org (v1.x) points to vuepress.vuej.s.org

#### Are you willing to work on this yourself?

N/A

**Comment by bencodezen** [comment]
A huge thanks to @yyx990803 for taking care of this! 🏆
