### ISSUE TITLE
How to get an overview from a markdown file

### ISSUE THREAD

**Issue by Bloss** [vuejs/vuepress#174]
How to get an overview from a markdown file like `<!-- more -->` tag in hexo

**Comment by mdaffin** [comment]
Vuepress uses [yaml-front-matter](https://www.npmjs.com/package/yaml-front-matter) which as far as I can tell does not support this feature. [gray-matter](https://www.npmjs.com/package/gray-matter#optionsexcerpt) however does support this and @yyx990803 is open to a pull request to switch to it (as part of also supporting toml/json frontmatter in #141)

**Comment by ulivz** [comment]
You mean the [TOC](https://vuepress.vuejs.org/guide/markdown.html#table-of-contents)?

**Comment by Bloss** [comment]
@ulivz  Not the `TOC`,  what  I want is a part of the article as an overview to show in the article list

**Comment by Bloss** [comment]
@mdaffin Thanks!
