### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by sobolevn** [vuejs/vuepress#1747]
## Feature request

We need to create a `CONTRIBUTING.md` guide.
Original idea from #1745  and #1741 

#### What problem does this feature solve?

It allows new contributors to understand the process of creating new PRs to the repo.
Ideally, it covers topics like:
1. Forking and branching, including branch names and commit messages
2. Project and mono-repo layout
3. Code quality standards and agreements 
4. CI process and how to fix it
5. Common tips that we know about

#### Are you willing to work on this yourself?

I would better ask for help of someone who works on this repo for a longer period of time.
And knows all the conventions and tools.

**Comment by sarahdayan** [comment]
Hey! @ulivz created one already, let's finish it :) https://github.com/vuejs/vuepress/pull/1739

**Comment by f3ltron** [comment]
I am closing this one because the #1739 is merged feel free to re open it if you think it should not be close
