### ISSUE TITLE
Enable CI build for forked Pull Requests

### ISSUE THREAD

**Issue by kefranabg** [vuejs/vuepress#1749]
## Feature request

CI process is not fired for forked pull requests.
It means no CI for external contributors 😭

We should turn on this on CircleCI:

![Capture d’écran 2019-08-06 à 11 30 20](https://user-images.githubusercontent.com/9840435/62529014-1ae1ce80-b83e-11e9-9bef-4db449f45848.jpg)
 

#### Are you willing to work on this yourself?

I don't think I have permission on CircleCI for now 😄

**Comment by ulivz** [comment]
Wow, cool! I just open it.

![image](https://user-images.githubusercontent.com/23133919/62633117-38aa5300-b966-11e9-9468-f9abd3e991c4.png)
