### ISSUE TITLE
- [ ] vuejs  markdown not support

### ISSUE THREAD

**Issue by wsdo** [vuejs/vuepress#1752]
- [x] I confirm that this is an issue rather than a question.

#### Other relevant information
- [ ] vuejs  markdown not support
- Output of `npx vuepress info` in my VuePress project:

**Comment by wsdo** [comment]
- [ ] vuejs  markdown  todo   not support

**Comment by f3ltron** [comment]
as vuepress use markdown you can add plugin from makdown it. I will give you a look this weekend when i will have time

**Comment by kefranabg** [comment]
Hi @wsdo,

As @f3ltron said, you can use `markdown-it` plugins. Please refer to this [section of the documentation](https://v1.vuepress.vuejs.org/guide/markdown.html#advanced-configuration).

And [here](https://www.npmjs.com/search?q=keywords%3Amarkdown-it-plugin%20checkbox) are some plugin you could use.

However, we might consider adding one of these plugins in `@vuepress/core` so checkbox syntax could be supported by default in VuePress. @f3ltron @fatihacet what do you think?

**Comment by f3ltron** [comment]
Sure i agree if it's really ask. As long as we support any addon it could be not necessary maybe improve the documentation is better

**Comment by f3ltron** [comment]
@wsdo just to help you on that

What it should look like with [markdown-it-task-lists plugin](https://github.com/revin/markdown-it-task-lists)

```js

module.exports = {
  title: 'VuePress Docgen',
  description: 'Preview your components',
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' }
    ]
  },
  markdown: {
    extendMarkdown: md => {
      md.use(require('markdown-it-task-lists'), {enabled: true});
    }
  }
}

```

Now with that example you should have beautiful todo

```md
### Solar System Exploration, 1950s – 1960s

- [ ] Mercury
- [x] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
- [ ] Neptune
- [ ] Comet Haley

```

If it's ok for you we can close the issue give me your feedback :)

**Comment by sarahdayan** [comment]
We're going to close this one now as @f3ltron's solution is fixing the issue. We'll make it clearer in the docs how to extend the existing Markdown configuration with markdown-it plugins, and consider what types of plugins we want to add by default in the future.
