### ISSUE TITLE
Tapable.plugin is deprecated

### ISSUE THREAD

**Issue by ederchrono** [vuejs/vuepress#176]
- Mac OS High Sierra
- Node.js version: 8.6.0
- VuePress version: ^0.7.0
- Browser version: Chrome latest
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

Repo for reproduction: https://github.com/ederchrono/vue-css-grid/tree/bug/vuepress-tapable-error

When running vuepress shows this warning:
```
$ vuepress dev docs
Extracting site metadata...(node:13230) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
Followed by these errors after building:

```
ERROR in   TypeError: compilation.templatesPlugin is not a function

  - SetVarMainTemplatePlugin.js:17 SetVarMainTemplatePlugin.apply
    [vue-css-grid]/[webpack]/lib/SetVarMainTemplatePlugin.js:17:15

  - Tapable.js:71 Compilation.apply
    [vue-css-grid]/[tapable]/lib/Tapable.js:71:16

  - util.js:52 Compilation.deprecated [as apply]
    internal/util.js:52:15
... more errors
```

**Comment by ederchrono** [comment]
Found the problem, I'm not an active yarn user so I had an old version.
For the record if anyone finds this message upgrade at least to yarn `v1.6.0`

**Comment by dabit3** [comment]
For anyone here with the same issue, upgrading to webpack to `4.39.3` fixed it for me.
