### ISSUE TITLE
Enable editLink on specific page

### ISSUE THREAD

**Issue by kefranabg** [vuejs/vuepress#1762]
## Feature request

For now we can globally enable `editLinks` (for page edition) and disable it per page with `editLink` front matter property, but we can't do the opposite: Having global `editLinks` prop to be `false`, and enable `editLink` per page.

For example:

If `themeConfig.editLinks` from my `.vuepress/config` file is `false` and `editLink` from one of my pages is `true`, it won't work, the page will not show the edit link.

#### What problem does this feature solve?

If I want **only one page** of my app to be editable, I need to enable page edition globally and then set `editLink` to `false` on **all other pages** . We should be able to do the opposite

#### What does the proposed API look 

We should use `editLinks` property from `themeConfig` by default, and overwrite it with the `editLink` property defined on the current page **if** it exists.

#### How should this be implemented in your opinion?

This behavior has been implemented for next/previous links in this [commit](https://github.com/vuejs/vuepress/pull/1761/commits/f19dc20df7ea646ce921ef216bdd1ffee38f649f)

#### Are you willing to work on this yourself?

Why not, however it could be a good first issue for external contributors 😉

**Comment by edisdev** [comment]
Wow, I think good idea :)  If you don't mind, I'd like to contribute to this when developing feature. :)

**Comment by edisdev** [comment]
Wow, I think good idea :) If you don't mind, I'd like to contribute to this feature . :) @kefranabg

**Comment by pniedzwiedzinski** [comment]
+1
