### ISSUE TITLE
Difficulty using syntax hilighting for a language not in highlight.js

### ISSUE THREAD

**Issue by mikesol** [vuejs/vuepress#1765]
## Feature request

Documentation for working with languages not covered by highlight.js.

#### What problem does this feature solve?

It is currently difficult, if not impossible, to work with languages outside of highlight.js. I've tried hacking together several pathways to activate a new language (ie https://github.com/vuejs/vuepress/issues/1580) but to no avail. I'm sure there's a painless way to do it, I just haven't found it yet.

#### What does the proposed API look like?

Ideally exactly as it works now: I'm sure there is already a way to do it, it is just documented. My guess is that you'd have to import highlight.js, add a language somehow and then use a custom plugin?

#### How should this be implemented in your opinion?

Purely documentation, ideally an example.

#### Are you willing to work on this yourself?

Yes: if someone can give me a minimum viable example (ie a fake language called `foobar` with only two keywords `foo` and `bar` that are highlighted), I can turn it into an example for the documentation.

**Comment by kefranabg** [comment]
Hi @mikesol,

What language are you trying to use? We're using [Prism](https://prismjs.com/) for syntax highlighting.

[Here is the list of supported languages](https://prismjs.com/#supported-languages).

**Comment by mikesol** [comment]
I'm creating my own language (wall-lang.netlify.com, github.com/mikesol/wall). So I'd like to create syntax highlighting for it in vuepress. Could you give me a brief example of how to sync up a new language in prism and vuepress? Thanks!

**Comment by kefranabg** [comment]
We could have added a new option to the global config to cover your need, but it's seems that it's not possible to add a new language highlight in Prism at runtime: see [how to extend Prism.js](https://prismjs.com/extending.html).

The only (painful I know) way would be that you open a PR to Prism to introduce your highlight syntax and then wait for us to update our prism version to include your changes.

The other way could be trying to found a new syntax highlighter that supports what you need, but as I think you're the only one to ask for this feature, it won't be our priority 😢

**Comment by mikesol** [comment]
Hm, it looks like highlight.js does not allow for (easy/obvious) custom definitions either. What a pity, as it seems that there's no straightforward way for people experimenting with new languages to do syntax highlighting in JavaScript. Of course, not VuePress's problem! Closing the issue then, thanks for your help!

**Comment by pragdave** [comment]
I bumped into this issue too, and wrote a trivial plugin that uses highlight.js, and which allows user-written grammars to be added via the config.ts file.

https://www.npmjs.com/package/vuepress-plugin-highlightjs

**Comment by CanadianBeaver** [comment]
> Hi @mikesol,
> 
> What language are you trying to use? We're using [Prism](https://prismjs.com/) for syntax highlighting.
> 
> [Here is the list of supported languages](https://prismjs.com/#supported-languages).

I have the same issue for something called `blueprint`. It works pretty well on github and all what I want is to hide warnnig in vuepress: `Language does not exist: blueprint.` Is it possible?
