### ISSUE TITLE
        "activeHeaderLinks: false"    don't work 

### ISSUE THREAD

**Issue by iandstanley** [vuejs/vuepress#1767]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. create custom theme (see my repo details below)
add following to config.js with custom theme:...

```
module.exports = {
    
    title: 'Starlife Company Services Ltd',
    description: 'Cleaning and Security services across the South East',
    
    themeConfig: {
        activeHeaderLinks: false
    }
}

```

2. Create markdown file (say index.md in cleaning/ in my repo) with markdown headings

(please note  that I have had to hard code HTML `<h2>/<h2>` headers as a temporary fix for this situation.

3. 'sudo vuepress dev src' to build and view

4. navigate to 0.0.0.0:8080/cleaning/  to the page with the ## headings 

5. observe that despite turning activeHeaderLinks to false they still appear    **:(**

i'm guessing it can be easliy done on most repos 

but here is my repo 

https://github.com/kingdom-values-clients/starlife-website/tree/9c9dc044ff85fba377af3c8ed8db312cde54fc62

just change the <h2></h2> back to ## and you will see it fail

#### What is expected?

the config option should turn off the '#' marks for the headers

#### What is actually happening?

- '#' marks are not turned off
- you cannot  turn them off by addressing in your CSS
```
a.header-anchor
    display: none
```
- the only way to turn off is by hard coding <h2></h2> tags into your markdown thus defeating the purpose of using markdown in the first place.

#### Other relevant information

my repo

https://github.com/kingdom-values-clients/starlife-website/tree/9c9dc044ff85fba377af3c8ed8db312cde54fc62

- Output of `npx vuepress info` in my VuePress project:
ian:~/GitHub/starlife-website $ npx vuepress info

Environment Info:

  System:
    OS: Linux 4.19 Raspbian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) arm ARMv7 Processor rev 3 (v7l)
  Binaries:
    Node: 12.7.0 - /usr/bin/node
    Yarn: 1.17.3 - ~/GitHub/starlife-website/node_modules/.bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.0.3 
    @vuepress/theme-default:  1.0.3 
    vuepress: ^1.0.3 => 1.0.3 
  npmGlobalPackages:
    vuepress: 1.0.3

**Comment by mayashavin** [comment]
@iandstanley `activeHeaderLinks` is meant to disable/enable the auto-update for the hash in the URL as the user scrolls to view the different sections of the page. For example, if user scrolls to `Working regionally, working locally`, the hash in URL and the sidebar (if there is) will change to something similar to `http://localhost:8082/cleaning/#working-regionally-working-locally`, and the sidebar section will be highlighted accordingly.

Setting this to `false` means to disable the auto-updating of the hashing and the sidebar highlights according to scrolling. It is not related to hiding/not hiding the markdown `#` as you reported.

**Comment by iandstanley** [comment]
Thanks it was the scoping that threw me

I'd tried 
```
a.header-anchor {
    display: none
}
```

but it hadnt done anything 

I was following a tutorial that used for the component 

```
<style lang="stylus" scoped>
