### ISSUE TITLE
In-component Navigation Guards

### ISSUE THREAD

**Issue by chris-dura** [vuejs/vuepress#1773]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Create a global component with `beforeRouteEnter`, `beforeRouteUpdate` and `beforeRouteLeave` navigation guards.

https://codesandbox.io/embed/codesandbox-vuepress-navigation-guards-9iobr

#### What is expected?

The in-component navigation guards output to console.

#### What is actually happening?

The in-component navigation guards do not output.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```shell
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 64.0
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.0.2 
    @vuepress/theme-default:  1.0.2 
    vuepress: 1.0.2 => 1.0.2 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by newsbielt703** [comment]
[Vue Router - in-component-guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards):
> Finally, you can directly define route navigation guards inside route components (the ones passed to the router configuration) with the following options

Global components are not route components, so you're not able to use the in-component navigation guards.

**Comment by Mister-Hope** [comment]
> [Vue Router - in-component-guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards):
> 
> > Finally, you can directly define route navigation guards inside route components (the ones passed to the router configuration) with the following options
> 
> Global components are not route components, so you're not able to use the in-component navigation guards.

I understand this part. But how could us hanle the logic, make Global components listen the url and change with it?

Could you give me an example or thought?

**Comment by Mister-Hope** [comment]
Oh I just remember the `enhanceApp.js`, I will try to puta pub/sub module on the Vue instance, it may works.

**Comment by Mister-Hope** [comment]
I solve it by put a pub/sub module on the Vue prototype and emit it on `router.beforeResolve`, since there isn't a Vue instance in `enhancedApp.js`. But I still wonder if there is a way to use the pub/ sub module in Vue instead if importing one.

**Comment by davestewart** [comment]
@Mister-Hope - you shouldn't need to do this, as `this.$page.path` is reactive, and so can drive your breadcrumbs; just make a computed property that references the page's `path` or `regularPath`.

**Comment by Mister-Hope** [comment]
> @Mister-Hope - you shouldn't need to do this, as `this.$page.path` is reactive, and so can drive your breadcrumbs; just make a computed property that references the page's `path` or `regularPath`.
> 
> 

I am not a Vue new comer. I need hooks to call up functions.

**Comment by Mister-Hope** [comment]
> @Mister-Hope - you shouldn't need to do this, as `this.$page.path` is reactive, and so can drive your breadcrumbs; just make a computed property that references the page's `path` or `regularPath`.
> 
> 

I am not a Vue new comer. I need hooks to call up functions.

**Comment by davestewart** [comment]
Sure. And sorry, wasn't implying you're a newcomer by the way! I've seen your themes.

Perhaps I should have said "you can also" rather than "you shouldn't need to".

Anyway, the reason I suggested `$page` is because you get access to both `regularPath` (the path of the physical page folder) and `path` the router `route` which may be different if you've set a frontmatter permalink.

The reason I found this page is because I'm also building breadcrumbs (and I used `$page` to do it):

![image](https://user-images.githubusercontent.com/132681/110927139-2c922e80-831d-11eb-9b13-d1a3a980bd5e.png)

Thanks for your explanation also.

:D

**Comment by Mister-Hope** [comment]
> Sure. And sorry, wasn't implying you're a newcomer by the way! I've seen your themes.
> 
> Perhaps I should have said "you can also" rather than "you shouldn't need to".
> 
> Anyway, the reason I suggested `$page` is because you get access to both `regularPath` (the path of the physical page folder) and `path`; normally this is the same as `$route.path`, but is different if you've set a frontmatter `permalink`.
> 
> The reason I found this page is because I'm also building breadcrumbs (and I used `$page.regularPath` to do it):
> 
> ![image](https://user-images.githubusercontent.com/132681/110927139-2c922e80-831d-11eb-9b13-d1a3a980bd5e.png)
> 
> Thanks for your explanation also.
> 
> :D
> 
My logic is different. For a link `/a/b` permal to `c/d/e`, I am still trying to provide c c/d  for breadcrumbs. That works good when you are setting a type(or category) based permalink. But breadcrumb the real link do works better on time based permalink. Thanks for the idea. I will see if I can add them both and provide user an option.

**Comment by davestewart** [comment]
I think I see what you mean.

Yes, my site also has index pages for every category (path).

I presume you are also then using `$site.pages` to look up the page of each of the breadcrumbs and get the titles?

I just work backwards, down the path segments.

Probably too difficult for each of us to explain our logic here, but I'm glad it's working for you.

Did you get this online in the end?

**Comment by Mister-Hope** [comment]
https://vuepress-theme-hope.github.io/guide/layout/breadcrumb/

This is what I build now.

Related files are under https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/components/src/client/BreadCrumb.ts

Finally use computers.

I was trying to build the whole structure through $site.pages, and even tring to cache the keys to fast uodate structure in an HMR.

Sadly that vuepress broke hmr in its updates.

**Comment by davestewart** [comment]
It's so interesting to see another theme solving the same problems I am!
