### ISSUE TITLE
Redirect `/` to section, instead of "home" README.md

### ISSUE THREAD

**Issue by chris-dura** [vuejs/vuepress#1777]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Given this directory structure, I want a user who visits `http://my-site.com/` to be redirected to `http://my-site.com/core/overview.html`.

```
.
├── docs
│   ├── .vuepress (Optional)
│   │ 
│   ├── README.md
│   ├── core
│   │   ├── overview.md
│   │   └── library.md
│   ├── web
│   │   ├── README.md
│   │   └── library.md
│   ...
└── package.json
```

Reading through other "best practices" and issues filed here about redirecting, I should be able to add a route to `enhanceApp` to redirect to a subsection; however, since there is a `/README.md` file, it seems to break the redirect, and AFAICT, the `/README.md` is required in order to generate a `dist/index.html` file, which is obviously necessary for the app to run...

#### Steps to reproduce

https://codesandbox.io/embed/codesandbox-vuepress-home-redirect-9iobr

#### What is expected?

`/` redirects to `/section/` or `/section/some-page.html`

#### What is actually happening?

`/` displays project `/README.md` content

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 64.0
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.0.2 
    @vuepress/theme-default:  1.0.2 
    vuepress: 1.0.2 => 1.0.2 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by newsbielt703** [comment]
I found the code in your `enhanceApp .js`:
```js
router.addRoutes([{ path: "/", redirect: "/core/overview" }]);
```
 It's not a bug of VuePress, since `addRoutes` won't replace existed routes.

**Comment by chris-dura** [comment]
@newsbielt703 -- Thanks for your response...
I suppose you can say it's not a "bug" in Vuepress; however, I have a few questions, then...

1. Are you saying that the `router.addRoutes()` (and the `vuepress-plugin-redirect`), which are the documented "best practices" for redirecting only support redirecting from "non-existent" paths to somewhere else?

**Comment by newsbielt703** [comment]
@chris-dura I can offer you some approaches  but I can't tell which is the best way:

1. [Set Permalink](https://v1.vuepress.vuejs.org/guide/permalinks.html#background)
Don't redirect. You can just set permalink to `/README.md`.
```
---
permalink: /core/overview
---
```

2. [Set Layout](https://v1.vuepress.vuejs.org/guide/frontmatter.html#layout)
Since you don't care about the layout of home page, you can set a different layout component which handle redirecting.

```
---
layout: Redirect
---
```
```
// Redirect.vue
<template></template>

<script>
export default {
  mounted() {
    this.$router.push("/core/overview");
  }
};
</script>
```

**Comment by chris-dura** [comment]
Thanks @newsbielt703 --

> 1. Set Permalink
> Don't redirect. You can just set permalink to /README.md.

I actually did try this and forgot to note it... I'm not sure if it's a bug, but when I have a `permalink` in the `/README.md`, there is no `dist/index.html` output when I run `vuepress build docs` 😖 

Maybe there's a way to workaround that (or I'm doing it wrong) but any typical/simple server setup for the SPA is pretty much going to require a `dist/index.html` file 🤷‍♂ 

> 2. Set Layout
Since you don't care about the layout of home page, you can set a different layout component which handle redirecting.

Thanks! I didn't even consider creating a `Redirect.vue` layout that essentially does "nothing" but redirect. I see no reason this wouldn't work!

> Btw, is #239 the "best practices" you mentioned?

Yes... among some other posts in forums... they all mention using `addRoutes` and `enhanceApps`, but I don't know, perhaps there's a good deal of context missing from those, because obviously, it only works in some (imo) pretty specific cases?

Or, maybe the real problem is that the app that VuePress generates isn't _quite_ apples-to-apples with other apps I've built with `vue-cli` in that (afaict) VuePress abstracts some of the app-level things that you would normally have no problem accessing in a typical `vue-cli` project... like being able to override the router/routes...
