### ISSUE TITLE
Error compiling upgraded to "css-loader": "^3.2.0"

### ISSUE THREAD

**Issue by Gompje** [vuejs/vuepress#1785]
- [ x] I confirm that this is an issue rather than a question.

## Bug report

**I'm reporting this mainly for others that could have the same issue**

#### Steps to reproduce

1. Project that uses the `css-loader` package.
1. upgrade it to the latest (I did it with the yarn command) to `"css-loader": "^3.2.0"`
1. `docs:build` gives massive error during the last step

#### What is expected?

docs build

#### What is actually happening?

error
```bash
undefined) ./node_modules/@vuepress/core/.temp/style.styl
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous>
```
#### Solution

Use older version `"css-loader": "^2.1.0",` gives no issues so far.

#### Other relevant information

- could be error inside that package
- upgraded all others to latest as of today, including webpack: no issues
- complex project

**I'm reporting this mainly for others that could have the same issue**

**Comment by Mombuyish** [comment]
The `docs:dev` is the same as error.
I do install `css-loader` to `2.1.1` in my `package.json` instead of the underlying version.

It should be worked, however, I think this is an issue.

**Comment by f3ltron** [comment]
Hello @Gompje i think it was related to another bug that we correct in the new release 1.0.4 can you upgrade vuepress from 1.0.3 to 1.0.4 and tell me please
