### ISSUE TITLE
Page Navigation Fails if Visiting Folder URL without Trailing Slash

### ISSUE THREAD

**Issue by SlvrEagle23** [vuejs/vuepress#1787]
- [x] I confirm that this is an issue rather than a question.

## Bug report

~~If navigating directly to a URL that corresponds to a folder (with or without the trailing slash), everything looks fine on the initial page render, and when navigating around the site, the address bar continues to update, but the contents of the page itself are frozen and don't change.~~

Edit: Please disregard...my tests revealed that it was one of the following issues on the page that was causing the problem. Removing these items resolved the issue:

#### A header with a colon and exclamation point

```
## Step 1: Read the Logs!
```

#### A link that looks like an e-mail address but is in standard Markdown link format:

```
- Follow us on Mastodon at [@AzuraCast@fosstodon.org](https://fosstodon.org/@AzuraCast)
```

One of the two issues above definitely caused the Vuepress engine to fail to process the page correctly, throwing a JS error and preventing the user from further navigating the page. It seems this issue only became apparent when directly navigating to the page in question instead of navigating indirectly to it from any other page.

I'm not sure which of the two caused the problem (and I don't have enough under-the-hood expertise with VuePress to know how to narrow down the cause any more specifically than that) but it caused the symptoms reported in my initial report.

**Comment by kefranabg** [comment]
Hi @SlvrEagle23 ,

I can't reproduce. Could you provide a reproduction link and the output of this command: `vuepress info`

**Comment by SlvrEagle23** [comment]
Closing as my reproduction link doesn't seem to be demonstrating the problem in the same way that my original static site did. I strongly suspect the problem was due to Vuepress "double-parsing" a link that looks like an e-mail address, but I can't seem to demonstrate that.
