### ISSUE TITLE
Invalid configuration Port parameter

### ISSUE THREAD

**Issue by busyrat** [vuejs/vuepress#1789]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Upgrade to 1.0.3 Configuring port in config.js is invalid

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by kefranabg** [comment]
Hi @busyrat,

Could you translate your issue so more people can help you?

**Comment by busyrat** [comment]
@kefranabg 
Sorry, I have changed
English is not good /(ㄒoㄒ)/~~

**Comment by OverTree** [comment]
you should look at this
[portfinder@1.0.22 returns random port](https://github.com/http-party/node-portfinder/issues/87)

**Comment by fancyfx** [comment]
This is a problem with portfinder@1.0.22,I try re-install vuepress solved this problem。
Because portfinder v1.0.23 fixed this bug.
check your portfinder version:
```
yarn list portfinder 
or 
npm list | grep portfinder
```
