### ISSUE TITLE
No version in package.json

### ISSUE THREAD

**Issue by Swader** [vuejs/vuepress#1790]
The current `package.json` has no `version` or `name` fields. These would be irrelevant in all cases, except that Yarn depends on them to be able to install the package locally from a specific branch, tag, or commit or even local folder. Thus, it is impossible to test local fixes from other contributors without silly workarounds like manually hacking `package.json` in the fork.

Reference issue: https://github.com/yarnpkg/yarn/issues/6195

If I'm using the wrong approach, please let me know of a better way to test things (specifically, I'm testing a bounty: https://gitcoin.co/issue/vuejs/vuepress/1613/3333)

**Comment by f3ltron** [comment]
Hello @Swader can you give us a reproduction in what you want to achieve please. Actually the version of the global package is in packages/*package.json or in lerna.json.

Give me a complete step to reproduce here please

**Comment by Swader** [comment]
I was trying to install Vuepress from a locally cloned branch to use that one, but you gave me a better method so I'll close this.
