### ISSUE TITLE
Adding routes does not work after build

### ISSUE THREAD

**Issue by rohaanhamid** [vuejs/vuepress#1792]
https://v1.vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements

Steps to reproduce:

1) Add routes to the router using the .addRoutes(<Array>) method.
2) Build the app using vuepress build.
3) Navigate to one of the paths specified during .addRoutes

**Comment by jojosgirls** [comment]
Totally my fault. I was using the <a/> instead of <router-link/>. 

<a/> works in dev mode but not after build. This because during build all routes added to the router are applied to instances of <router-link/> and not <a/>.

Please close this issue.

**Comment by rohaanhamid** [comment]
I was using `<a/>` instead of `<router-link/>`.
