### ISSUE TITLE
Spelling Mistake in Documentation

### ISSUE THREAD

**Issue by christyjacob4** [vuejs/vuepress#1797]
I came across a spelling mistake in the vue-press documentation website as you can see in the attached screenshot.

![mistake](https://user-images.githubusercontent.com/20852629/63459313-edb63280-c471-11e9-9bf4-48bc3ac9fcd2.png)

"They" is misspelled as "The".

**Comment by kefranabg** [comment]
@christyjacob4 Could you open a PR based one [your fork](https://github.com/vuejs/vuepress/issues/1797) ?

**Comment by christyjacob4** [comment]
@kefranabg I have already raised a pull request for this and it has been merged. #1798.  could you please verify this?

**Comment by f3ltron** [comment]
@christyjacob4 hello ! :) It seem's it has been merge vuepress 0x version. It is existing on v1 too ?

**Comment by christyjacob4** [comment]
@f3ltron This is the corresponding page in v1 . There is no issue in v1.
https://v1.vuepress.vuejs.org/guide/basic-config.html#config-file

**Comment by f3ltron** [comment]
Ok so its related to v0 just to be sure :)

**Comment by f3ltron** [comment]
https://vuepress.vuejs.org/guide/basic-config.html#config-file i saw the "they" so i close this issue feel free to reopen if you have more infos thank's @christyjacob4

**Comment by christyjacob4** [comment]
Yes this is an issue on v0. You're welcome @f3ltron
