### ISSUE TITLE
请问如何再VUEPRESS的VUE组件内使用别名

### ISSUE THREAD

**Issue by anyclub** [vuejs/vuepress#1805]
请问如何再VUEPRESS的VUE组件内使用别名,

大致需求如下
![asd](https://user-images.githubusercontent.com/19922265/63757244-4fe8ba80-c8ec-11e9-8408-4991658c90a8.png)
vuepres里面使用的vue组件内,需要根据项目src目录下某个JS文件的数据,目前只能用类似 ../../这样的方案么

**Comment by kefranabg** [comment]
Could you translate this issue so we can help you?

**Comment by Mister-Hope** [comment]
I think you can use the clainwebpack configuration, just as vue.

**Comment by meteorlxy** [comment]
Replace literal `'../../src'` to `path.resolve('......')`

e.g.

```js
const path = require('path')

// ....

configureWebpack: {
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'path/to/src')
    }
  }
}
```

**Comment by ulivz** [comment]
Same opinion with @meteorlxy , you should set the target path of a alias to a absolute path so that you use it at any level of directories.

**Comment by MissNanLan** [comment]
![image](https://user-images.githubusercontent.com/22790863/88124456-c0cd4b00-cbff-11ea-99a5-8c77224d5970.png)
It's my project structure
![image](https://user-images.githubusercontent.com/22790863/88124491-db9fbf80-cbff-11ea-9bb2-04fcee533f68.png)
Why not set  alias on this component?
![image](https://user-images.githubusercontent.com/22790863/88124825-9465fe80-cc00-11ea-8eec-1979e9a598fd.png)
It's my error message
