### ISSUE TITLE
medium-zoom plugin is displaying images with wrong proportions

### ISSUE THREAD

**Issue by tomrndom** [vuejs/vuepress#1806]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Use the medium-zoom plugin with images that had a modified width. In the example, the images are inside a flex container. Also the images had an `data-zoom-src` value for the high resolution picture.

Here's a repository with the example [https://github.com/tomrndom/vuepress-zoom-test/](https://github.com/tomrndom/vuepress-zoom-test/)

#### What is expected?

The images should be zoomed in with the proportions of the `data-zoom-src` image.

#### What is actually happening?

The images are zoomed in with the proportions of the thumbnail images.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

Environment Info:

      System:
        OS: 
	        Windows 10
        CPU: 
	        (12) x64 AMD Ryzen 5 1600X Six-Core Processor   
        Binaries:
        Yarn: 
	        1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
        npm: 
	        6.4.1 - C:\Program Files\nodejs\npm.CMD   
        Browsers: 
	        Edge: 44.18362.267.0   
        npmPackages:
	        @vuepress/core:  1.0.3
	        @vuepress/theme-default:  1.0.3
        vuepress: 
	        ^1.0.3 => 1.0.3   
	    npmGlobalPackages:
	        vuepress: Not Found

**Comment by gabrielrumiranda** [comment]
Can I take this issue ?

**Comment by kefranabg** [comment]
@gabrielrumiranda sure !

**Comment by gabrielrumiranda** [comment]
@tomrndom you cant take screenshot of this problem ? I test in environment similar yo your but I use mac. I could not replicate this problem. For example in your example when I remove ` data-zoom-src`  the zoomed image is different

**Comment by tomrndom** [comment]
@gabrielrumiranda Sure. 

For the zoom there are 2 different versions of the same picture, a small one on the `href` (thumbnail) and another with high resolution on the `data-zoom-src` (image displayed on zoom).

Here's an example on the zoom when the thumbnail has his original width
![container with original width](https://user-images.githubusercontent.com/19543853/64913385-b1df5780-d715-11e9-8a70-1de99c78b3f6.jpg)

And this is the zoomed image when the thumbnail has a modified width
![container with modified width](https://user-images.githubusercontent.com/19543853/64913389-c0c60a00-d715-11e9-8c66-bd8cdfb5975f.jpg)

**Comment by gabrielrumiranda** [comment]
I test this related problem using only the medium zoom, and also occurred. I think you must report this in [medium-zoom repository](https://github.com/francoischalifour/medium-zoom) because is not a problem with the plugin but with the framework

**Comment by kefranabg** [comment]
@tomrndom do you confirm?

**Comment by tomrndom** [comment]
@kefranabg Yes, there's something similar happening with this library, so the problem should be comming from there

**Comment by kefranabg** [comment]
Ok I'll close the issue as it's not a VuePress issue. Feel free to open one to the [medium zoom repos](https://github.com/francoischalifour/medium-zoom) 😉
