### ISSUE TITLE
Broken link in chinese doc

### ISSUE THREAD

**Issue by jobbr88** [vuejs/vuepress#1812]
https://v1.vuepress.vuejs.org/zh/miscellaneous/design-concepts.html
解耦部分的“插件”链接。

**Comment by kefranabg** [comment]
Could you translate this issue so we can help you?

**Comment by mafeifan** [comment]
https://v1.vuepress.vuejs.org/zh/miscellaneous/design-concepts.html

![image](https://user-images.githubusercontent.com/4178463/64402999-71466500-d0a9-11e9-8626-5013d4633a18.png)

**Comment by kefranabg** [comment]
Got it ! We need to fix the broken link in the chinese documentation. Based on @mafeifan screenshot, the link in the `Decoupling` section from `Design Concepts of VuePress 1.x` page is broken.
