### ISSUE TITLE
Cyrillic "л" is replaced by Latin "n" in the anchor link

### ISSUE THREAD

**Issue by Phenomen** [vuejs/vuepress#1815]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Repo: [https://github.com/Phenomen/ose](https://github.com/Phenomen/ose)
Deployed version (with bugged anchor links): [https://ose.phenomen.now.sh/classic-fantasy/](https://ose.phenomen.now.sh/classic-fantasy/)

1. Add a heading (h1-h6) with lowercase Cyrillic letter "л" (## Терминология)
2. Check generated anchor link.

#### What is expected?

Anchor link is #терминология

#### What is actually happening?

Anchor link is: #терминоnогия
Cyrillic "л" is replaced by Latin "n" in the anchor link.

#### Other relevant information

Zeit is used for build and deploy. Result is the same as on local machine.

- Output of `npx vuepress info` in my VuePress project:

**Comment by Phenomen** [comment]
#andrewrk/node-diacritics/pull/33

**Comment by larionov** [comment]
Related: https://github.com/kentcdodds/match-sorter/issues/57

Their solution is to replace `diacritics` with `remove-accents` instead.

**Comment by f3ltron** [comment]
Do you think you can work on it ? We are using remove accents actually maybe bad configs

**Comment by larionov** [comment]
@f3ltron I would like to try

**Comment by f3ltron** [comment]
top @larionov ! Dont hesitate to ask me if you need some help about understanding part of vuepress

**Comment by larionov** [comment]
@f3ltron sorry, figured it out, realized that I had a very old fork of vuepress. 
Please see the PR.

**Comment by f3ltron** [comment]
just start to pull master into your fork.

yarn boostrap
yarn test and it should work

Tell me more about what u doing now.

**Comment by larionov** [comment]
I did the fix, opened the PR #1855 and waiting for the comments on it

**Comment by youngpirate32** [comment]
This error has affected me too, can you please see please

**Comment by namereva** [comment]
I have the same problem. How is progress?

**Comment by larionov** [comment]
I will try to resolve the conflicts today

**Comment by larionov** [comment]
Resolved

**Comment by v1talii-dev** [comment]
It also appears on the letter "й".
