### ISSUE TITLE
Accessibility: Navbar dropdown can't be used with just a keyboard

### ISSUE THREAD

**Issue by missmatsuko** [vuejs/vuepress#1818]
- [x] I confirm that this is an issue rather than a question.

## Bug report
There doesn't seem to be any way to access dropdown items in the navbar using keyboard navigation.

#### Steps to reproduce
1. Go to <https://vuepress.vuejs.org/>
2. Tab through the navbar menu items
3. The navbar menu item with a dropdown ("languages") is completely skipped. There's no way to select a language from the navbar using keyboard navigation.

#### What is expected?
Someone using a keyboard to navigate the site should be able to access dropdown items (and in this case, change the site's language).

#### What is actually happening?
Someone using a keyboard to navigate the site can't access dropdown items.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by edisdev** [comment]
Hi Sir  @f3ltron ,  I opened pull request for this issue. pr link : https://github.com/vuejs/vuepress/pull/1837

**Comment by f3ltron** [comment]
Hello @edisdev i will check for it top !
