### ISSUE TITLE
Question: Is it possible to edit the main theme?

### ISSUE THREAD

**Issue by EarlyPacker** [vuejs/vuepress#1822]
Hello,

I've seen that it is possible to make your own theme, but what I wanted was to simple add new stuff like for example html tags and other things to the main theme.
I like how it looks so I'd be mostly adding more to it, is it possible?
From the guides I got a little confused.
First time using vue.

**Comment by newsbielt703** [comment]
Please take a look at:
[Custom Layout for Specific Pages](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#custom-layout-for-specific-pages)

[Ejecting](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#ejecting)

[Theme Inheritance](https://v1.vuepress.vuejs.org/theme/inheritance.html#theme-inheritance)
