### ISSUE TITLE
Can add a copy button to the code block?

### ISSUE THREAD

**Issue by liyuj** [vuejs/vuepress#1823]
#### What problem does this feature solve?
This feature helps developers copy code fragments
#### What does the proposed API look like?
In the upper right corner of the code block, add a copy button.
#### How should this be implemented in your opinion?
When rendering code blocks, add a button.
#### Are you willing to work on this yourself?
Not very likely.

**Comment by f3ltron** [comment]
Hello @liyuj thank's for your feature request it is relevant to have it. It can be a markdown it plugin or maybe more about prism.

**Comment by ChetanGoti** [comment]
Based on discussions at https://github.com/vuejs/vuepress/issues/703, You can use `@dovyp/vuepress-plugin-clipboard-copy` till than.

- Add "@dovyp/vuepress-plugin-clipboard-copy": "^1.0.0-alpha.7" in package.json 
- Add it as plugin in config.js: ['@dovyp/vuepress-plugin-clipboard-copy', true]

**Comment by liyuj** [comment]
Hi,

npm i @dovyp/vuepress-plugin-clipboard-copy

Execute the above command and throw the following error

npm ERR! code ETARGET
npm ERR! notarget No matching version found for 
@dovyp/vuepress-plugin-clipboard-copy@^1.0.0-alpha.7
npm ERR! notarget In most cases you or one of your dependencies are 
requesting
npm ERR! notarget a package version that doesn't exist.

在 2019/9/11 下午9:03, Chetan Goti 写道:

**Comment by kefranabg** [comment]
@liyuj executing `npm i @dovyp/vuepress-plugin-clipboard-copy` works well for me.

**Comment by liyuj** [comment]
Hi,

The reason has been found is the problem with the NPM mirror I use here.
The plug-in has been tested and can be used. No problem.

在 2019/9/21 下午8:42, Franck Abgrall 写道:
