### ISSUE TITLE
$page variable doesn't gets set probably on urls without a trailing slash

### ISSUE THREAD

**Issue by peXed** [vuejs/vuepress#183]
**OS:** Windows 10
**Node:** 8.10.0
**VuePress:**  0.6.1
**Browser:** Chrome 65
Local install
**Package manager:** Yarn

**Bug:**
If you visit a route without a trailing slash, the $page variable doesn't gets set probably and the page won't render correctly.
You also don't get redirected to the path with the trailing slash.

**How to reproduce:**
1.  Clone offical repository
2.  Run dev server (yarn dev)
3.  Open a route without the taling slash (e.g. localhost:8080/guide )

**Expected Behavior:**
You get redirected to the correct path (with the trailing).
This would fix potential SEO problems as well (for more infos: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html?m=1 )

Issue is linked to: #144

**Comment by ulivz** [comment]
Fixed at #185
