### ISSUE TITLE
Support Kotlin Code Highlight

### ISSUE THREAD

**Issue by bamboovir** [vuejs/vuepress#1831]
#### What problem does this feature solve?

Support Kotlin Code Highlight

#### How should this be implemented in your opinion?

@vuepress/core/lib/client/style/config.styl

$codeLang += kt

@vuepress/markdown/lib/highlight.js +=

if(lang === 'kt') {
  lang = 'kotlin'
}

**Comment by kefranabg** [comment]
Hi @bamboovir ,

As we're using [prismjs](https://prismjs.com/#supported-languages) for code highlighting, we're already supporting Kotlin code highlight. Just use the alias `kotlin`.

**Comment by bamboovir** [comment]
Hi @kefranabg, kotlin code highlighting is not work for Code Snippets，
This means that kotlin code imported from other files cannot be highlighted correctly.
https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets

**Comment by kefranabg** [comment]
You mean it's not working only with code snippets imports ?

**Comment by bamboovir** [comment]
Yes, and I have given a fix.

```
@vuepress/core/lib/client/style/config.styl

$codeLang += kt

@vuepress/markdown/lib/highlight.js +=

if(lang === 'kt') {
lang = 'kotlin'
}
```

**Comment by larionov** [comment]
@kefranabg @bamboovir Highlighting Kotlin is working already, you just need to use correct language alias (https://prismjs.com/#basic-usage)

[
![2019-09-14_13-17](https://user-images.githubusercontent.com/174250/64904264-c27dd680-d6f1-11e9-9fa3-e65951562b1c.png)
](url)

**Comment by bamboovir** [comment]
@larionov it's not working with code snippets imports :(

**Comment by kefranabg** [comment]
I confirm that it is not working.
