### ISSUE TITLE
引用网络图片报错：403

### ISSUE THREAD

**Issue by dmljc** [vuejs/vuepress#1836]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

我项目引用网络图片之前还是可以的展示的。但是，最近我发现所有引用的网络图片地址，都会报错403。

下边这种格式是返回的403的：
`![box](https://user-gold-cdn.xitu.io/2019/8/30/16ce245b8f2a63c0?imageView2/0/w/1280/h/960/format/webp/ignore-error/1)`

而通过img标签引入的图片就可以正常展示：
`<img :src="$withBase('/box.jpg')" />`

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by f3ltron** [comment]
Hello ! Can you please translate in english what you need please. Thank's for your time !

**Comment by f3ltron** [comment]
thank you @ludanxer that help a lot ! 👍 

the https error is i think just the server tell you yout can't use the image it doesnt look like to be about vuepress so i am closing the issue for now.

Thank's for him a lot @ludanxer

**Comment by dmljc** [comment]
> 你好 ！你能用英语翻译你需要的东西吗？谢谢你的时间 ！

Do you know that Google's browser can be translated into English?
