### ISSUE TITLE
Update Semantic Pull Request check configuration

### ISSUE THREAD

**Issue by kefranabg** [vuejs/vuepress#1850]
We should disable the commit name check and just keep the PR title check.

This is ok if we consider that we're supposed to rename the PR title and use the "squash and merge" feature. This would be far easier for us to handle this Semantic Pull Request check.

**Comment by f3ltron** [comment]
The best could be to just allow squash merging on master. It is possible no ?

**Comment by kefranabg** [comment]
This is already availables:

![Capture d’écran 2019-09-12 à 09 37 42](https://user-images.githubusercontent.com/9840435/64763804-0f6e7b00-d541-11e9-8c0e-8424024f2985.jpg)

But the problem is the Github check, not the way we merge branch

**Comment by f3ltron** [comment]
Yeah but you can limit to it no ?

**Comment by kefranabg** [comment]
Oh! Actually that's a good idea! Yes it's possible but @ulivz is the only one that can access the repos settings to do that
