### ISSUE TITLE
Adding analytics to vuepress

### ISSUE THREAD

**Issue by f3ltron** [vuejs/vuepress#1851]
#### What problem does this feature solve?

In vuepress we are not using analytics to have more datas. Currently with translation we have many demands. It's a great use case that we should add an analytics on him.

@ulivz Maybe you can create one account or maybe one is existing already ?

#### Are you willing to work on this yourself?
sure

**Comment by kefranabg** [comment]
Actually I think we already have an analytics for VuePress doc 😉 Checkout `packages/@vuepress/docs/docs/.vuepress/config.js`

**Comment by f3ltron** [comment]
oh i feel stupid ^^. Ok thank's  @kefranabg
