### ISSUE TITLE
@vuepress/plugin-last-updated need dynamic time

### ISSUE THREAD

**Issue by NicholasCao** [vuejs/vuepress#1854]
#### What problem does this feature solve?

Now, the time is fixed at `build` time.
This can lead to a fixed time when using the following code, such as when build is 4 hours from the last commit, it will always be `4 hours ago`.
```js
transformer: (timestamp, lang) => {
  const moment = require('moment')
  moment.locale(lang)
  return moment(timestamp).fromNow()
}
```
In addition, when I need to show time in different time zones, I also need this feature.
```js
transformer: (timestamp, lang) => {
  return new Date(timestamp) // show local time
}
```

Time is dynamically acquired, it should be possible to pass in a function that dynamically fetches the time when the page refreshes, rather than fixing string forever.

#### What does the proposed API look like?
```js
['@vuepress/last-updated', {
  transformer: (timestamp, lang) => {
    const moment = require('moment')
    moment.locale(lang)
    return moment(timestamp).fromNow()
  }
}, true]
```

add a whether need dynamic function options

#### How should this be implemented in your opinion?

 It should be possible to pass in a function that dynamically fetches the time when the page refreshes

#### Are you willing to work on this yourself?
yes, but need some time.

**Comment by NicholasCao** [comment]
Hi @kefranabg ,
I need to converting UTC time to time in each time zone, so dynamic time is required.

And the offical demo
```js
transformer: (timestamp, lang) => {
  const moment = require('moment')
  moment.locale(lang)
  return moment(timestamp).fromNow()
}
```
if you use it, last updated time is fixed `four hours ago`(or other time, it depends on the time difference between your build and the last commit.)

**Comment by kefranabg** [comment]
This feature is very specific to your need. What I mean is that a small part of VuePress users will need this feature. I suggest you to use [default theme inheritance](https://vuepress.vuejs.org/theme/inheritance.html#concepts) to solve your problem.
