### ISSUE TITLE
Add a description to README

### ISSUE THREAD

**Issue by joshduck** [vuejs/vuepress#1863]
## Feature request

The project's README forgets to mention what the project is. Dropping a quick explanation at the top of the file is good practice. 

#### What problem does this feature solve?
PR for the project.

**Comment by kefranabg** [comment]
I assume that you're talking about [this readme](https://github.com/vuejs/vuepress/blob/master/README.md)

**Comment by k9uma** [comment]
Is there an official standard description available?
Are we lifting it from [this](https://v1.vuepress.vuejs.org/)

**Comment by kefranabg** [comment]
We can create a short description of VuePress from [this](https://vuepress.vuejs.org/guide/)

**Comment by ivandevp** [comment]
I can help with this if nobody else is looking at it.

**Comment by ulivz** [comment]
Fixed at #1912
