### ISSUE TITLE
Ability to disable the site name on the navbar

### ISSUE THREAD

**Issue by abishekrsrikaanth** [vuejs/vuepress#1866]
## Feature request
A configuration to disable the site name on the navbar when the logo is enabled on the configuration.

#### What problem does this feature solve?
It allows to not show the Site Name on the navbar when the logo is enabled.

**Comment by kefranabg** [comment]
Hi @abishekrsrikaanth 

Such a feature would be very specific to your need. If we add a new config option every time a user needs something, VuePress would become very complex 😕(This is my opinion) @ulivz @f3ltron What do you think?

However you can use [this](https://vuepress.vuejs.org/theme/inheritance.html#motivation) for more customization.

**Comment by f3ltron** [comment]
if you just want to see nothing you can put an empty string for now. I know the html is here but you will not have text

**Comment by ulivz** [comment]
As @kefranabg said, you can use [Theme Inheritance](https://vuepress.vuejs.org/theme/inheritance.html) to custom the `<Navbar />` component.

**Comment by LenonTolfo** [comment]
both links direct to a 404 page, how to remove the site-name from the navbar now?
