### ISSUE TITLE
messed order when import parent-theme style using @parent-theme

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#1870]
There are some problems here.

When I simply wrote this:

```styl
@require '~@parent-theme/styles/index.styl'

.XXX
  ....
```

It works normally.

But when I add a import:

```styl
@require '~@parent-theme/styles/index.styl'
@require './test.styl'
```

It is not working, the `@parent-theme/styles/index.styl` is not being applyed.

So why is this happenning?

**Comment by Mister-Hope** [comment]
My fault, I just realize I have to add a `~` before the require path to make it become a module

**Comment by Mister-Hope** [comment]
There are sill some problems here.

When I simply wrote this:

```styl
@require '~@parent-theme/styles/index.styl'

.XXX
  ....
```

It works normally.

But when I add a import:

```styl
@require '~@parent-theme/styles/index.styl'
@require './test.styl'
```

It is not working, the `@parent-theme/styles/index.styl` is not being applyed

**Comment by PeppeL-G** [comment]
Is `test.styl` imported correctly? You see the result of the CSS code in it in your web browser?

**Comment by Mister-Hope** [comment]
> Is `test.styl` imported correctly? You see the result of the CSS code in it in your web browser?

It is an empty file.

Besides, when I wrote 

```styl
@require '~@parent-theme/styles/index.styl'
```

in `.vuepress/theme/styles/index.styl`

the imprt order is messed, the style behave is different to.

**Comment by Mister-Hope** [comment]
Besides, when I wrote 

```styl
@require '~@parent-theme/styles/index.styl'
```

in `.vuepress/theme/styles/index.styl`(the file only contains this line)

the imprt order is messed, the style behave is different to.

So I think at least this way to import index.styl is incorrect, or the logic importing it is not being handled right.

**Comment by PeppeL-G** [comment]
I don't know how errors are handled in this case, but maybe the import of `~@parent-theme/styles/index.styl` stops working because the import `./test.styl` fails (e.g. wrong path to file)?

**Comment by Mister-Hope** [comment]
I don't think the path is wrong, and if I dont import `test.styl`, the style still ctaches problems.

> The parent theme(my case is theme-default) index.styl imprt order is messed, the style behavior is different to. You can simply create a project and create the file with this line, and you will see the page has a huge marginleft in mobile view which caused by the messed stype order.

**Comment by ulivz** [comment]
Could you prepare a minimal reproduction?

**Comment by Mister-Hope** [comment]
wrote

@require '~@parent-theme/styles/index.styl'
in .vuepress/theme/styles/index.styl(the file only contains this line)

**Comment by ulivz** [comment]
You don't need do this import since VuePress will do it.

**Comment by Mister-Hope** [comment]
> You don't need do this import since VuePress will do it.

You must be kidding me. When I add index.styl in my theme folder, it will overide the theme-default index.styl. No style will be used.

**Comment by Mister-Hope** [comment]
So I am trying to import it when I overide it.

I know I can just change the file name which is no confilt with theme-default and import it in all layout I wrote to prevent this error, but I do think it is a bug.

**Comment by ulivz** [comment]
See: https://v1.vuepress.vuejs.org/miscellaneous/design-concepts.html#overriding

**Comment by Mister-Hope** [comment]
😢 My error,I just reproduced it, and  found out I use a varible which is used by offical, and I give it a different type, I think it caused some errors for showing the styles.

P.S. : I wonder if a list of official variable can be made, or maybe there is and I didnot find out?

**Comment by Mister-Hope** [comment]
Besides, I noticed many commits to the doc only changed the English version, while the Chinese version remain unchanged, I can help out with that to sync the modification to chinese, can this type of PR be accepted?

**Comment by ulivz** [comment]
For all internal Stylus variables, you can get them here: https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/style/config.styl

For the problem of stale CN docs, at present, we may not be able to synchronize in time, so I really want someone to help me to compare and sync it. contribution welcome if you want!
