### ISSUE TITLE
Vuepress should fail if imported code snippets is not found

### ISSUE THREAD

**Issue by nfnt** [vuejs/vuepress#1872]
#### What problem does this feature solve?
Currently, when trying to import a code snippet from a non-existing file, vuepress will create a snippet that says "File not found".
Input:
```
<<< @/file_does_not_exist.js
```
Output:
```
Not found: /app/file_does_not_exist.js
```
This is a problem because it results in broken documentation. In a CI/CD environment it would be great to surface this problem early.

#### What does the proposed API look like?
Vuepress should fail to render if a code snippet isn't found.

**Comment by ivandevp** [comment]
Can I work on this?

**Comment by kefranabg** [comment]
@ivandevp sure !

**Comment by ivandevp** [comment]
Hey guys! I've created a PR with the changes I'm making for this issue (#1910). I want your suggestions on this. By this moment, I've added the logger to show an error in the building process but, it won't stop the process. I haven't found a way to throw an error in other plugins used in the codebase, so I would like to know if you have an idea of how it should be. Let me know your thoughts, please.

**Comment by kefranabg** [comment]
Hi @ivandevp, let's discuss this in your PR 😉
