### ISSUE TITLE
Extra head tags injections not working

### ISSUE THREAD

**Issue by Kerollmops** [vuejs/vuepress#1873]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I wanted to add a custom script to the head of vuepress and after many attempts I did not succeed to even get a `console.log("Hello")`.

I tried to CTRL-C an re-run the `vuepress dev` command.

#### Steps to reproduce

Use the current documentation to load extra tags to the head.
https://v1.vuepress.vuejs.org/config/#head

```js
module.exports = {
  head: [
    ['script', {}, `console.log("Hello")`]
  ]
}
```

#### What is expected?

A script is visible in the head of the vuepress generated page.

#### What is actually happening?

No script tags in the head apart from the vuepress ones.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
$ vuepress --version
vuepress/1.1.0 darwin-x64 node-v10.16.3
```

```
$ vuepress info

Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.nix-profile/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ulivz** [comment]
You need to restart the dev server after you add it.

![image](https://user-images.githubusercontent.com/23133919/65390975-0332bb00-dd96-11e9-98bd-b142b4c98d2e.png)

This introduced another problem: VuePress doesn't respect the change of head before the development process restart.

**Comment by f3ltron** [comment]
We should watch on it ? @ulivz  ?  You closed it

**Comment by ulivz** [comment]
What I want to express is that we need know the problem I mentioned above: VuePress doesn't respect the change of head before the development process restart.

I closed it since a new issue should be for it.

**Comment by f3ltron** [comment]
ok it's about the watch stuff on chockidar i will have a look for this one

**Comment by Kerollmops** [comment]
Thank you any way, I did tried to restart the dev server but this time it worked :)
