### ISSUE TITLE
Code blocks occupy the whole width on mobile phone

### ISSUE THREAD

**Issue by ludanxer** [vuejs/vuepress#1891]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Open Vuepress website with a phone, and then scroll down to any code blocks.

Actually, I'm not sure if this is by design. But it looks kind wired on a phone with a black border (e.g. iPhone XR)

Relevent code [theme-default/styles/mobile.styl#line 36](https://github.com/vuejs/vuepress/blob/c17c70e96af5542edba86032c22cc67348251d78/packages/%40vuepress/theme-default/styles/mobile.styl#L36)

#### What is expected?

Something like this looks better?

![WeChat Image_20190926122542](https://user-images.githubusercontent.com/27280733/65658088-d19d4680-e058-11e9-81dd-3be3efb17454.png)

#### What is actually happening?

![WeChat Image_20190926122550](https://user-images.githubusercontent.com/27280733/65658094-d661fa80-e058-11e9-9af6-36ea41e6a30e.png)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by kefranabg** [comment]
@ludanxer this is expected design ;) Thanks for asking
