### ISSUE TITLE
siderBar support html tag and font icons?

### ISSUE THREAD

**Issue by uwings** [vuejs/vuepress#1896]
hi guys , before i user vuepress , i use docsify write articles.
know i like vuepress more
but there is some thing i cant handle it , maybe because i just not an coder ,im an designer , so more and more thing i cant do it by my self.  pls help me , thanks a lot

1, sidebar  html tag， i want use spacial tag(class) or font icon 
**want :**
![](https://static.uxlib.net/WX20190928-095054-2x.png)

![img](https://static.uxlib.net/WX20190928-094909-2x.png)
**in fact:**
![](https://static.uxlib.net/WX20190928-095122-2x.png)
![img](https://static.uxlib.net/WX20190928-095142-2x.png)

**Comment by haochenli** [comment]
The thing gets complicated when you want to customize everything.
So from my understanding, you can use `vuepress eject` command to extract the theme. Here is the [link](https://vuepress.vuejs.org/theme/default-theme-config.html#custom-page-class). Seems you want to custom your sidebar, so after `vuepress eject`, go to `/.vuepress/theme/components/Sidebar.vue`, and then customize the part in the component. Have fun!

**Comment by kefranabg** [comment]
As @haochenli you can [extend the default theme](https://vuepress.vuejs.org/theme/inheritance.html) to customize this.
