### ISSUE TITLE
Vue Router parameters empty for Markdown pages

### ISSUE THREAD

**Issue by tomhrtly** [vuejs/vuepress#1897]
- [x] I confirm that this is an issue rather than a question.

After setting up a fresh VuePress installation, when adding markdown files in the docs directory as instructed here and opening the Vue dev console in Chrome, the parameters are not shown in the `params` object.

#### Steps to reproduce

1. Follow the instructions on the VuePress documentation page "Getting Started" to create a basic VuePress site.
2. Add a markdown file within `docs/test/directory/`
3. Start the local server, go the markdown file in the browser and open the Vue dev tools extension.

#### What is expected?

To see the url parameters in the `params` object in `$route`. For example I would expect to see `docs`, `test` and `directory`

#### What is actually happening?

The `params` object is empty.

**Comment by Shanery** [comment]
I can confirm that is occurring.

`[Vue warn]: Unknown custom element: <v-565e8225> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

My theory is that dynamic component imports are not working correctly.

**Comment by Shanery** [comment]
@tomhrtly 

I played around and realized the issue was with my browser. Firefox didn't like it while Chrome had no issues. Should look into why this doesn't work on firefox.

**Comment by tomhrtly** [comment]
@kefranabg So is there no way of extracting `docs`, `test` or `directory` as a string from my route? I'm sure this is possible when creating a standard SPA with Vue Router.
