### ISSUE TITLE
page nav link broken , when use external link.

### ISSUE THREAD

**Issue by uwings** [vuejs/vuepress#1898]
if in config , i user  
relative link, like  `target.html` ,it's not working .  but when i use full link `https://a.com/target.html`
in page nav `prev` , `next` link , i got `http://a.com/currentdir/https://a.com/target.html` how can i fix it?

**Comment by kefranabg** [comment]
Hi @uwings,

Why are you trying to target a `html` file ?
We need more context, please provide a reproduction link so we can help you.

**Comment by uwings** [comment]
I mean sometimes i need link an external link in sidebar.   so this link end with html, or start with http header.
about why i want use external link, i think:

1. I'm not an dev guys, I'm an designer , just interesting in html , css, program thing. but need more study. so icant use vue codes in vuepress , i just use it as an tool.  like gitbook .
2. Sometimes  the Docment(vuepress project) references another URL, or web site.
3. Some Complex page, need more style sheets, or html codes, because i cant write is withe vue language,so i use html & css & js edit this page as html.   

4 preview  [UX library- font](https://uxlib.net/content/guidelines/font.html) ,  in this page , next link is "图标(icons.html)" page  it's an external link

**Comment by kefranabg** [comment]
`Prev` or `Next` link are not supposed to target external urls. These are used to link next or previous pages of your VuePress app. You can add external link on the main navbar or in the markdown content. Feel free to reopen this issue if it did not solve your problem.

**Comment by uwings** [comment]
i know that.  external url can use in sidebar and nav bar , I mean , if support external  in sidebar and bav bar why  can't support at page nav?   is there a conflict？
