### ISSUE TITLE
NPM - Unable to find a readme for vuepress@1.1.0

### ISSUE THREAD

**Issue by atilacamurca** [vuejs/vuepress#1908]
The NPM page for vuepress is not able to find a README file <https://www.npmjs.com/package/vuepress>.

As we can see here <https://unpkg.com/browse/vuepress@1.1.0/>, the file is, indeed, not present.

**Comment by kefranabg** [comment]
Yep, the `vuepress` package does not contains any README.

**Comment by kristiyan-ASW-G-08** [comment]
I'd like to take this one.

**Comment by kristiyan-ASW-G-08** [comment]
What should the README contain?
