### ISSUE TITLE
How to modify the <Content />?

### ISSUE THREAD

**Issue by cnguu** [vuejs/vuepress#1911]
I want to modify the contents of <Content />.

For example, I want to modify the links to all the images in <Content />, how can I do this? Is there an interface that can be done?

**Comment by ulivz** [comment]
`<Content>` is a Vue component which renders the compilation output at build time. so you cannot modify it directly at runtime.
 
You have following approaches:

1. Modify the source markdown content: [Plugin API > extendPageData](https://v1.vuepress.vuejs.org/plugin/option-api.html#extendpagedata);
2. Apply extra markdown-it plugins to extend the internal markdown compiler: [Plugin API 
 > chainMarkdown](https://v1.vuepress.vuejs.org/plugin/option-api.html#extendmarkdown):

Note that all plugin apis can be used directly in `.vuepress/config.js`.

**Comment by cnguu** [comment]
@ulivz 

I try to modify the source markdown content, but it doesn't work.

```js
    extendPageData($page) {
        $page._content = 'sonething change';
    }
```
