### ISSUE TITLE
nested sidebar will not work，Clicking on the menu will not expand

### ISSUE THREAD

**Issue by zq99299** [vuejs/vuepress#1913]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- repository：https://github.com/zq99299/linux-tutorial.git

```
yarn docs:build
```

Through the nginx deployment, or https://zq99299.github.io/linux-tutorial/, nested sidebar will not work，Clicking on the menu will not expand

通过 nginx 部署，或则使用 GitPage https://zq99299.github.io/linux-tutorial/， 嵌套的侧边栏无法工作，点击菜单无法展开

#### What is expected?

The normal work

侧边栏正常工作

#### Other relevant information
- version ：vuepress v1.1.0
- yarn docs:dev   (This mode is normal)

**Comment by ludanxer** [comment]
Hi,

**Renaming all of your `index.md` files to `README.md`** seemsto solve the problem.

See my [fork](https://github.com/ludanxer/linux-tutorial) and [deployed demo](https://linux-tutorial.netlify.com).

BTW, I don't get it why you overwrite the variable `dest` to `build/.vuepress/dist`. Simply ignore it, and the files will be built into `docs/.vuepress/dist`.

**Comment by zq99299** [comment]
Thank you, I will try it.
I don't want to submit this directory `docs/.vuepress/dist ` to git , so I changed it to the outside

**Comment by ludanxer** [comment]
Cool.

I mentioned it because it took me while to find it...

**Comment by zq99299** [comment]
Thank you again for helping me solve this thorny problem.
Never understood when to use index.md? When do you use README.md?

**Comment by ludanxer** [comment]
I think you should always use `README.md` instead of `index.md`, see [default-page-routing](https://vuepress.vuejs.org/guide/directory-structure.html#default-page-routing) for more detail.

**Comment by zq99299** [comment]
index.md files to README.md 

Already tried, still can't expand the menu

I don't know what caused it.

**Comment by ludanxer** [comment]
You forget [this one](https://github.com/zq99299/linux-tutorial/blob/master/docs/tutorial-basis/index.md)

**Comment by zq99299** [comment]
All modified

**Comment by ludanxer** [comment]
Sorry, my bad

I always remove the `--debug` flag in your `package.json` to faster the build and never realize this is the problem

Remove `--debug` while you deploy and everything seem to be fine

---

This only seems to happen when build with `--debug`

Minimal Reproduction:
- [Repo](https://github.com/ludanxer/vuepress-unexpand)
- [Demo](https://vuepress-unexpand.netlify.com/)

**Comment by zq99299** [comment]
thank you very much,

Is the problem of `--debug`
