### ISSUE TITLE
Permalinks can provide the default value of template variable like year,month,day

### ISSUE THREAD

**Issue by fangbinwei** [vuejs/vuepress#1923]
#### What problem does this feature solve?
Provide reasonable default value for template variable such as `year, month, day`
#### What does the proposed API look like?
null
#### How should this be implemented in your opinion?
like what [@vuepres/plugin-last-updated](https://github.com/vuejs/vuepress/blob/fa8a41d148d993e0f5d73cfa84a1b6a601126eb8/packages/%40vuepress/plugin-last-updated/index.js#L25-L29) did

if `DATE_RE`not match the date in `filename,dirname`, and `frontmatter.date` is not provided, we can find the commit where this file was first added( i'm not sure if it will course performance problem in large repo)
```js
    addedTimeStamp =
      parseInt(
        spawn
          .sync(
            'git',
            [
	      'log',
	      '--follow', // continue listening the history of renamed file
	      '--diff-filter=A',
	      '--format=%at',
	      path.basename(filePath)
	    ],
            {
              cwd: path.dirname(filePath)
            }
          )
          .stdout.toString('utf-8')
      ) * 1000
```

I wrote my own plugin to set `frontmatter.date`. It's cool if offical can provide this feature(maybe not necessary). 
#### Are you willing to work on this yourself?

**Comment by newsbielt703** [comment]
Apologies for the delayed response. I guess it's an expected value since timestamp starts at the Unix Epoch on January 1st, 1970 at UTC. 

Your suggestion is using the timestamps from git to as default values, right?

**Comment by fangbinwei** [comment]
Close since it's not a big deal, and it can be done with plugin
