### ISSUE TITLE
Syntax highlighting for Markdown files that have Vue components

### ISSUE THREAD

**Issue by bencodezen** [vuejs/vuepress#1927]
## Feature request

Users should have syntax highlighting for Vue components in Markdown files.

#### What problem does this feature solve?

It improves developer experience.

#### How should this be implemented in your opinion?

For now, a VS Code extension perhaps.

**Comment by PeppeL-G** [comment]
VS Code supports syntax highlighting for HTML code in markdown files? Are you talking about implementing Vue components directly in a markdown file?

**Comment by bencodezen** [comment]
@PeppeL-G Hmm.. You're totally right. When I filed this issue, I thought it wasn't highlighting, but I just checked and it's fine for me. Thanks for the comment!
