### ISSUE TITLE
Search "plugin" does not include project base in url

### ISSUE THREAD

**Issue by ProTip** [vuejs/vuepress#1929]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

* Build the docs with a base other than `/`: ie `/docs/`

#### What is expected?
Search links will include the base and link to the appropriate pages:  
`domain.com/docs/welcome.html`

#### What is actually happening?
Search links do not include the base and link to the page on the domain root:  
`domain.com/welcome.html`

**Comment by meteorlxy** [comment]
Not sure if this issue is related to algolia search.

If yes, it's fixed by #2007
