### ISSUE TITLE
Custom theme dependencies when using nmp link

### ISSUE THREAD

**Issue by andreasvirkus** [vuejs/vuepress#193]
- OS: Windows 10
- Node.js version: v9.6.0
- VuePress version: 0.4.2
- Is this a global or local install? Local
- Which package manager did you use for the install? npm 5.8.0
Custom theme repo used:
https://github.com/andreasvirkus/vuepress-theme-ajv

When trying to develop the theme locally with `npm link`, by running this in my Vuepress project root:
```
npm link ../vuepress-theme-ajv
```
It complains about dependencies missing theme-side:
```
ERROR in ../vuepress-theme-ajv/Layout.vue
Module not found: Error: Can't resolve 'vue' in 'C:\Users\antc\code\vuepress-theme-ajv'
 @ ../vuepress-theme-ajv/Layout.vue 24:14-28
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js

ERROR in ../vuepress-theme-ajv/Layout.vue?vue&type=script&lang=js (./node_modules/vue-loader/lib??vue-loader-options!../vuepress-theme-ajv/Layout.vue?vue&type=script&lang=js)
Module not found: Error: Can't resolve 'nprogress' in 'C:\Users\antc\code\vuepress-theme-ajv'
 @ ./node_modules/vue-loader/lib??vue-loader-options!../vuepress-theme-ajv/Layout.vue?vue&type=script&lang=js 19:0-33 56:4-13 60:8-17 66:6-15
 @ ../vuepress-theme-ajv/Layout.vue?vue&type=script&lang=js
 @ ../vuepress-theme-ajv/Layout.vue
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js
```

But the theme works fine when installing it from the registry:
https://www.npmjs.com/package/vuepress-theme-ajv

**Comment by andreasvirkus** [comment]
Also tried setting `resolve.symlinks` to `false` in the `configureWebpack` setting under `config.js`:
```
  configureWebpack: {
    resolve: {
      symlinks: false
    }
  },
```
But the same errors persist

**Comment by meteorlxy** [comment]
```js
    chainWebpack: (config, isServer) => {
        config.resolveLoader
            .modules
            .add(path.resolve(__dirname, './node_modules'))
    }
```
Can solve it temporarily

**Comment by ulivz** [comment]
Hmmm, cannot reproduced It at my side (OSX), but the solution from @meteorlxy should work for you.

BTW, The mistakes which blocked the build in your project are too much. 😅

**Comment by andreasvirkus** [comment]
@ulivz what were the mistakes you encountered?
