### ISSUE TITLE
Default theme's smooth scrolling feature not working

### ISSUE THREAD

**Issue by wallslide** [vuejs/vuepress#1930]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Here is the link to the repository with the issue --> https://github.com/appsocially/upil-site
The corresponding vuepress site is at https://upil.org/

I added the `smoothScroll` option to `config.js` [here](https://github.com/appsocially/upil-site/blob/master/docs/.vuepress/config.js#L9) as is detailed in the [docs](https://vuepress.vuejs.org/theme/default-theme-config.html#smooth-scrolling).

#### What is expected?
Clicking links on the sidebar that point to the current page should smoothly scroll the page to that section.

#### What is actually happening?
The page jumps to intra-page anchors instead of smoothly scrolling to them.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: Not Found
    Safari: 13.0.2
  npmPackages:
    @vuepress/core:  1.1.0 
    @vuepress/theme-default:  1.1.0 
    vuepress: ^1.1.0 => 1.1.0 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by kefranabg** [comment]
Hi @wallslide,

Actually `smoothScroll` feature was not released yet... It will be available in the next version of VuePress.

Our doc is always in bit ahead of releases 😅We need to fix this.

**Comment by Mister-Hope** [comment]
HHH I found this question ,too.

Maybe you can release a website called `beta-vuepress.vuejs.com`  and merge your ahead Doc changes when new versin release?

**Comment by kefranabg** [comment]
@Mister-Hope I described something that might be the solution [here](https://github.com/vuejs/vuepress/issues/1931)

**Comment by wallslide** [comment]
When I searched for related issues first, I found this one https://github.com/vuejs/vuepress/issues/567 and saw that it resulted in a merged pr, so I got thrown off by that :)

**Comment by ulivz** [comment]
@kefranabg We can let each new feature have a compatibility badge, e.g.

- input:

```
# Content <Badge text="1.0.0+" />
```

- output:

![image](https://user-images.githubusercontent.com/23133919/66687390-72c50780-ecbd-11e9-8535-781878a39cfb.png)

Maybe it should be listed in the contribution guide and pull request template.

// cc @f3ltron @bencodezen @meteorlxy

**Comment by kefranabg** [comment]
@ulivz I think using badge is a good idea to solve this 👍
