### ISSUE TITLE
Default theme: Navbar Logo Docs Missing

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#1932]
See below

**Comment by Mister-Hope** [comment]
It can not be hot loaded, I clear the cache and rerun the dev server and it's working now. I hope the official docs can add a description or at least metion it. It's a cool feature.

I'll make a PR later.

**Comment by chrtz** [comment]
It's actually described in the docs: https://vuepress.vuejs.org/default-theme-config/#navbar-logo

**Comment by Mister-Hope** [comment]
> It's actually described in the docs: https://vuepress.vuejs.org/default-theme-config/#navbar-logo

The link you provide is 404

**Comment by CodesOfRa** [comment]
The url is for v0 docs, check it out - https://v0.vuepress.vuejs.org/default-theme-config/#navbar-logo .

Somehow that section is not available in the v1 docs. No idea why, but I see no reason not to be there :), so I created a PR for this
