### ISSUE TITLE
google analytics not works

### ISSUE THREAD

**Issue by llccing** [vuejs/vuepress#1936]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
i use the lastest vuepress and "@vuepress/plugin-google-analytics"，write plugins config in .vuepress/config.js file , and deploy by Travis,  content initial at project gh-pages branch.

#### What is actually happening?
google analytics not works
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.1.0
    @vuepress/theme-default:  1.1.0
    vuepress: ^1.1.0 => 1.1.0
  npmGlobalPackages:
    vuepress: Not Found

**Comment by llccing** [comment]
[这里是版本库](https://github.com/llccing/FrontEnd)

[这是最新的构建版本](https://llccing.github.io/FrontEnd/)

有在这里说明：https://github.com/vuejs/vuepress/issues/1286#issuecomment-539548676

**Comment by ludanxer** [comment]
Sorry, I can not reproduce this.

Here is my minimal successful deployment:
- [Repo](https://github.com/ludanxer/vuepress-support)
- [Demo](https://vuepress-support.netlify.com)

My suggestion is:
1. Clean up your repo (for example, remove all `.DS_Store` and add it to `gitignore`)
2. Upgrade your `vuepress` and all of the related plugins
3. Review your customization

If this problem is still happening, try to build a minimal reproduction and post it here.

**Comment by kefranabg** [comment]
Thanks for testing @ludanxer 🙏 I close this issue. @llccing feel free to comment if you're still not able to solve your problem

**Comment by llccing** [comment]
@ludanxer thanks for help. i notice you deploy by netlify, and i deploy by travis ci, so i think may be problem happen in travis ci. 

i search ‘google analytics’ in the /dist/app.xxx.js file, in your repo i found, but not in my repo. so i build in local, i found it too. so i think this because deploy tool -- travis ci.

this is my old travis ci config 
```js
language: node_js
node_js:
  - '10'
install:
  - npm install -g vuepress
script:
  - npm run build
cache:
  directories:
    - 'node_modules'
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $github_token # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
```

this is vuepress doc [Travis ci config](https://v1.vuepress.vuejs.org/zh/guide/deploy.html#github-pages-and-travis-ci)

```js
language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
```

because i use yarn, so i change the  travis ci config to
```js
language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
cache:
  directories:
    - 'node_modules'
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $github_token # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
```

the change section is
```
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn build
```

this is the success [page](https://llccing.github.io/FrontEnd/)

so, success, thanks @ludanxer
