### ISSUE TITLE
Error in new Smooth scroll feature

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#1943]
- [x] I confirm that this is an issue rather than a question.

## Bug report

After update to version 1.2.0,  adding  `smoothScroll: true` in my themeConfig, got  an error.

```
wait Extracting site metadata...
tip Apply theme vuepress-theme-hope (extends @vuepress/theme-default) ...

warning An error was encounted in plugin "smooth-scroll"

tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin copyright (i.e. "vuepress-plugin-copyright") ...
tip Apply plugin flowchart (i.e. "vuepress-plugin-flowchart") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin mathjax (i.e. "vuepress-plugin-mathjax") ...
tip Apply plugin named-chunks (i.e. "vuepress-plugin-named-chunks") ...
```

while the smoth scroll featrue doesn't work.

I was using it when vuepress@1.1.0, I enable it by my own, and there are no errors and the feature works well.

#### Steps to reproduce

Figuring out now. Reson listed below

#### Reson of this error

It seems sometime npm will generate a different tree, and put `plugin-smooth-scroll` under `theme-default/node_modules` folder. That 100% cause the error I mentioned.

But the strange thing is when I run `npm list` , plugin-smooth-scroll is only under theme-default, with no other version in the project.

When I dragged this folder out,  the error disappeared. (But the feature is not working)

![image](https://user-images.githubusercontent.com/33315834/66702161-2e764d80-ed37-11e9-8888-f56141231902.png)
![image](https://user-images.githubusercontent.com/33315834/66702166-3b933c80-ed37-11e9-8943-f5d42ce748e6.png)

The left is the error one, while the right one with no error.

The most rediculous part is that I use the same package.json and run `npm install` in two folders, and I got a different result above.(I got the left one three times, while the right one 1 times)

#### My package.json
```json
{
  "name": "vuepress-theme-hope-doc",
  "version": "1.0.0",
  "description": "An example for vuepress-theme-hope",
  "scripts": {
    "serve": "vuepress dev src",
    "cleanServe": "vuepress dev src --no-cache",
    "build": "vuepress build src",
    "build-with-base": "VuePress_BASE=/BASE/ vuepress build src",
    "test": "echo \"Warning: no test specified\" && exit 0"
  },
  "author": "Mr.Hope",
  "license": "MIT",
  "dependencies": {
    "vuepress": "^1.2.0"
  },
  "devDependencies": {
    "@vuepress/plugin-blog": "^1.4.0",
    "eslint": "^6.5.1",
    "eslint-plugin-vue": "^5.2.3",
    "vuepress-plugin-named-chunks": "^1.0.2",
    "vuepress-theme-hope": "0.0.9-alpha2"
  }
}
```

npx vuepress info:

```
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

P.S. I am not sure whether it is related to my node version.

**Comment by kefranabg** [comment]
@Mister-Hope could you provide a minimal reproduction repos?

**Comment by kefranabg** [comment]
@meteorlxy any idea on this one?

**Comment by meteorlxy** [comment]
@kefranabg 

He is using theme extending. This issue was caused by the wrong deps tree generated by npm. See https://github.com/vuepress/vuepress-community/issues/1#issuecomment-541422143

**Comment by Mister-Hope** [comment]
I moved the vuepress to peerDependencies and it works well?

At least it’s not bothering me anymore
