### ISSUE TITLE
Broken link to CONTRIBUTING.md in README.me

### ISSUE THREAD

**Issue by talkor** [vuejs/vuepress#1953]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. Go to README.md.
2. Click on `Contribute` under "Code Contributors".

#### What is expected?

Should open the `CONTRIBUTING.md` page.

#### What is actually happening?

Page doesn't exists (404).

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by kefranabg** [comment]
Fixed in #1954
