### ISSUE TITLE
error Code snippet path not found: @vuepress\markdown\__tests__\fragments\snippet.js

### ISSUE THREAD

**Issue by liudonghua123** [vuejs/vuepress#1957]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

I have a repo (https://github.com/ynu/ynu-api-docs) which build on vuepress, and I added some content to it, then it failed on the `travis-ci`, the error was something like the belows. And I can reproduce the issue via manully delete `yarn.lock` , execute `yarn` to update the dependences and then execute `yarn build`.

1. update vuepress from 1.0.3 to 1.2.0
2. yarn build

#### What is expected?

execute `yarn build` successfully.

#### What is actually happening?

![image](https://user-images.githubusercontent.com/2276718/66802073-d6fdfa80-ef4d-11e9-936a-2e11db1256ab.png)

**Comment by liudonghua123** [comment]
I found the problem, the `@/../@vuepress/markdown/__tests__/fragments/snippet.js` path was not exist.
![image](https://user-images.githubusercontent.com/2276718/66802645-b9ca2b80-ef4f-11e9-8c5d-e85b34d9b70a.png)

If I use vuepress v1.0.3, it just maybe a warning, but now it was a error in vuepress 1.2.0. Hope this changes could show in the docs.
![image](https://user-images.githubusercontent.com/2276718/66802757-175e7800-ef50-11e9-8b26-6dfabcb88d31.png)

**Comment by liudonghua123** [comment]
![image](https://user-images.githubusercontent.com/2276718/66805264-1bda5f00-ef57-11e9-8bf1-79d13e215b06.png)

**Comment by upcwangying** [comment]
I have the same problem, how do you solve it ?

**Comment by liudonghua123** [comment]
@upcwangying You should fix the file path in markdown snippets.
