### ISSUE TITLE
external url can use in sidebar and nav bar but it's broken at bottom nav bar(prev ,next)

### ISSUE THREAD

**Issue by uwings** [vuejs/vuepress#1962]
external url can use in sidebar and nav bar , I mean , if support external in sidebar and bav bar why can't support at page nav? is there a conflict？

**Comment by ludanxer** [comment]
I can work on this if it is expected

**Comment by kefranabg** [comment]
@uwings `prev` and `next` links are meant to target (as their name indicates) a previous or next link in the sidebar. Allowing them to target external url would be strange in my opinion.

If you need to target an external url in your page, use [custom vue components](https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions) in your markdown or [theme inheritance](https://vuepress.vuejs.org/theme/inheritance.html) to custom the default-theme.

**Comment by uwings** [comment]
@kefranabg yes , u can have u own opinion , but  vuepress support external links in sidebar .  so is this an conflict?   in my opinion  u can fix sidebar (cancel support external link), or fix bottom navbar (support external link), what do u think ?

**Comment by uwings** [comment]
by the way , [prev-next-links](https://vuepress.vuejs.org/theme/default-theme-config.html#prev-next-links) can resolve the issue , for now .

**Comment by Mister-Hope** [comment]
Yes, tried same opinion, I have external links in sidebar too

**Comment by kefranabg** [comment]
@uwings I didn't know that external links were supported by navbar, in that case supporting external links for prev/next make sense 😉

**Comment by uwings** [comment]
@kefranabg @ludanxer thank you guys very much .
