### ISSUE TITLE
Language does not exist undefined

### ISSUE THREAD

**Issue by KyleThanas** [vuejs/vuepress#1966]
最近执行dev或者build都会报错Language does not exist undefined，
代码块显示不出来，
包括css代码块、jsx代码块等

**Comment by ludanxer** [comment]
Hi @KyleThanas ,

Please use English to describe your problem next time, so everyone can help.

And please do provide more detail, maybe a repo to reproduce the problem you encountered?

---

Translation:

Recently, an error "Language does not exist undefined" are shown whenever I run `dev` or 
`build`, and code blocks (css, jsx, etc.) are not showing anymore.

**Comment by kxbk100** [comment]
I met the same problem, and don't know why this issue is closed.

**Comment by ludanxer** [comment]
Hi @kxbk100 ,

I believe this issue is closed because there is very few context. The problem you encountered may have many reasons.

Can you make a minimal reproduction? Or maybe describe how to reproduce this problem in detail?

**Comment by yanghong** [comment]
When I just install node14.5 and run `vuepress dev .` first time under my centos7, error "Language does not exist: console" came out and finally "FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory".

**Comment by dakuohao** [comment]
![image](https://user-images.githubusercontent.com/19989280/95735117-00637a80-0cb7-11eb-95ad-b251705941c4.png)
我也遇到了这个错误，google无果，自己翻源码，发现这个此报错来自prismjs（代码美化的插件）官网：
https://prismjs.com/
```

	arr.forEach(function (language) {
		if (!components.languages[language]) {
			console.warn('Language does not exist ' + language);
			return;
		}
		// Load dependencies first
		if (!withoutDependencies && components.languages[language].require) {
			loadLanguages(components.languages[language].require);
		}
```
这是个 warn，可以忽略
意思就是 你的makrdown ```后边没写语言

**Comment by JohnLulzh2002** [comment]
I ran into the same problem. Maybe you were using a language that prismjs doesn't support.

For example, an error may occur when using `` ```c++`` while you should use `` ```cpp`` instead.

Here are some languages that should be fixed:

|❌Wrong|✔Right|
|-|-|
|c++|cpp|
|c#|cs|
|mysql|sql|

A complete list of supported languages can be found [here](https://prismjs.com/#supported-languages)
