### ISSUE TITLE
How to import stylus in plugins and let them accept var in pattern.styl

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#1970]
## Question

- If my plugin has no vue files,how can I import stylus file?

> I tried to import it in enhancedAppFile, and it works

- How can I import var in pattern.styl?

For example, users may edit the navBar Height, and that will make my plugin placed in a wrong position, so I would like to get the variable in my stylus file to generate the right css file.
So how can I get the variable?

**Comment by ulivz** [comment]
1. using `enhanceAppFiles ` instead;
2. you don't need import it, because you can use them directly.


---

We recommend you to ask question in the [Discord server](https://vue-land.js.org/), [forum](https://forum.vuejs.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress).

**Comment by Mister-Hope** [comment]
It's my fault.

But I wonder if the docs can add these parts, because nothing about style is methoned in [here](https://v1.vuepress.vuejs.org/zh/plugin/writing-a-plugin.html).
