### ISSUE TITLE
No JSON.stringify in define

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#1975]
![image](https://user-images.githubusercontent.com/33315834/67411308-036de280-f5f0-11e9-81d6-a48fd4d79cdc.png)

- [x] I confirm that this is an issue rather than a question.

## Bug report

index.js in plugin:

```js
const { resolve } = require('path')

module.exports = (options, ctx) => ({
  name: 'share',

  define: {
    ShareOption: { a: 1 }
  },

  enhanceAppFiles: [resolve(__dirname, './enhanceAppFile.js')],

  globalUIComponents: 'ShareCtn'
});
```

// other vue files

```js
console.log(ShareOption) // got {a:1} not '{a:1}'
```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
Please take a serious look at the documentation of [DefinePlugin](https://webpack.js.org/plugins/define-plugin/):

> Note that because the plugin does a direct text replacement, the value given to it must include actual quotes inside of the string itself. Typically, this is done either with alternate quotes, such as '"production"', or by using JSON.stringify('production').
