### ISSUE TITLE
Invalid reference in [[toc]] with plugin markdown-it-custom-header-link

### ISSUE THREAD

**Issue by abernov** [vuejs/vuepress#1979]
- [x] I confirm that this is an issue rather than a question.

## Bug report

if header has custom link (used plugin markdown-it-custom-header-link) then the table of content has a wrong link.

#### Steps to reproduce

install markdown-it-custom-header-link
add plugin to config

set header link
`## title <!-- link -->`

add [[toc]]

#### What is actually happening?

in [[toc]]wrong reference to this header

#### Other relevant information

How to resolve:

for reference in the vuepress [[toc]] need use token.attr.id or $page.headers.slug

Then all will work fine!

- Output of `npx vuepress info` in my VuePress project:

**Comment by kefranabg** [comment]
VuePress is using [markdown-it-table-of-contents](https://github.com/Oktavilla/markdown-it-table-of-contents) which is not able to understand markdown-it-custom-header-link syntax.

Why do you need your link to be different from your header title?

**Comment by brindosch** [comment]
Hello @kefranabg,
Sadly, i noticed the same with the "badge" feature. 
```` md
### TEXT <Badge text="TBA 2.1+"/>
````
The [[TOC]] will create a link to `#text-badge-text-tba-2-1: ` instead of `#text`

**Comment by kefranabg** [comment]
@brindosch your comment is not related to the initial issue. Please report it in another issue, if you think you've found a bug.

**Comment by abernov** [comment]
>Why do you need your link to be different from your header title?

1. I need references from my WEB-app to vuepress docs headers.
App is Multilingual. In this case, each language has its own unique link to header.

1.  Easier to create a new locale. Copy the existing one - all links will remain. You only need to translate the text.

see also [discuss at this Feature request](https://github.com/vuejs/vuepress/issues/679)

**Comment by abernov** [comment]
I look at code of markdown-it-table-of-contents and found this bug!

**Comment by abernov** [comment]
I look at code of 'markdown-it-table-of-contents' plugin.

This plugin needs to be rewritten for badge and custom link works.

**Comment by kefranabg** [comment]
Unfortunately we don't own this plugin, you can still try to open an issue to the toc repos, but i don't think maintainers will accept such a feature 🤔
