### ISSUE TITLE
[Discussion] Roadmap

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#198]
Hey guys, about the next direction or planning of VuePress, specially set up a **"channel"** to discuss here.

Above all, we need to make clear that the original intention of VuePress is to write documents to Vue and its sub projects. As mentioned in the document, VuePress is composed of two parts: 

1. A static site generator
2. A vue-styled default theme

If we leave everything to the default theme, then when you decide to develop a new theme, you would repeat many things. so for some of our new features, we should consider whether it is handled in `1` or `2`. 

In fact, I expect to complete the development of the core functionality as soon as possible, Only core is STABLE can we focus on **migrating the documents** and **blog theme development** (Maybe need to create a separate repo called `vuepress-theme-blog`). Of course, the premise is that we have prepared useful enough data and APIs for the beginning of the custom theme. 

At present, the core function I think is probably only **Algolia DocSearch Integration**. If you think there are other deserved suitable core needs, feel free to tell us here.

Regards,
Thanks.

## Radmap

- 0.8.0
    - Algolia DocSearch Integration.

**Comment by dgpgdev** [comment]
nice to centralize info :) .

I'll just finish to create a vue cli plugin for vuepress maybe add that inside project features.  https://github.com/dgpgdev/vue-cli-plugin-vuepress

**Comment by dgpgdev** [comment]
Before work algolia docsearch maybe merge pullrequest validated. I don't think blog are useless... vuepress is perfect for documentation.

**Comment by yyx990803** [comment]
One extra thing we need to finalize in core: API for custom themes to write additional files during build.

**Comment by mdaffin** [comment]
> so for some of our new features, we should consider whether it is handled in 1 or 2.

Or we can implement things in a theme, then once they are proven or popular look to migrating them into the core. As long as the core is flexible enough for themes to do this extra useful common features can be backported into the core so that more themes can take advantage of them.

For these, we need a way for themes to write additional files like @yyx990803 suggests. I have attempted to introduce this in #196 but we should probably take about the implementations details a bit more. In short, it loads `themeDir/index.js` and `.vuepress/index.js` and expects them to export a function that takes `{options}` as an argument. This function runs in the context of the server as part of the prepare method so has access to write files to the `outDir` and otherwise manipulate the set options before the site is generated (allowing injection of extra headers or other things).

One thing it does not expose is a way to hint to the build about extra routes that should be generated (such as routes added in enchanceApp.js like in #143)

**Comment by ulivz** [comment]
@mdaffin @dacsang97 Thanks for your two guys' contribution for the plugin support (#196 & #216). Let me summarize for that here.

### 1. Figure out the reponsibility of plugin.

Obviously, VuePress core's prepare process is only to do some `pre-build` work for the default theme. When we need to extent some data before building, plugins come in handy. So we should consider what can be changed by the developer of the plugin.

So the `options` should not be exposed directly, especially some values that are not allowed to be changed, such as `sourceDir`, `outDir`, plugin system shouldn't let plugins to have permissions to modify them. So it would be better to create a shallow-cloned options to expose:

```typescript
interface exposedOptions {
	// sourceDir: string;        // readable
	// outDir: string;           // readable
	// publicPath: string;       // readable
	// markdown: Object;         // readable
	// themePath: string;        // readable，Theme compoennt entry
	// useDefaultTheme: boolean; // readable
	// notFoundPath: string;     // readable， 404 component entry
	
	siteConfig: Object;    
	pageFiles: string[];         // A list containing relative paths of source makrdown files
	siteData: Object;     
}

interface Page {
	path: string;
	title: string;
	headers: Array<{ level: number, title: string, slug: string }>;
	frontmatter: { [key: string]: string };
}

interface siteData {
	title: '',
	description: '',
	base: '/',
	pages: Page
}
```

### 2. Determine the timing of the plugin's execution.

At the moment, I found out that both of yours put the excution timing at the end of `prepare`. I agree that at least we can ensure that the core is stable enough. and @yyx990803 what do you think about this?

### 3. Deciding on the plugin's API.

Obviously, I think everyone supports pure function API, However, at this stage we have two options：

  1. First-order function

  The extra `pluginOptions` was mixin in the exposed options object.
  
  ```js
  module.exports = ({siteConfig, siteData, pageFiles, pluginOptions}) => {}
  ```
  
  2. High-order function

  Also from @dacsang97:
  
  ```js
  module.exports = (pluginOptions) => ({siteConfig, siteData, pageFiles}) => {}
  ```
  
  Let's vote:
  
  [![](https://api.gh-polls.com/poll/01CBS2K4884SN1V4CVERMWN797/First-order%20function)](https://api.gh-polls.com/poll/01CBS2K4884SN1V4CVERMWN797/First-order%20function/vote)
  [![](https://api.gh-polls.com/poll/01CBS2K4884SN1V4CVERMWN797/High-order%20function)](https://api.gh-polls.com/poll/01CBS2K4884SN1V4CVERMWN797/High-order%20function/vote)
  
 
It is worth mentioning that the plug-in should support the `async function` and `return Promise`.

### 4. Deciding on the usage of plugins

User can add extra plugins via `plugins` field at `docs/.vuepress/config.js`, there are 4 optional types of usage:

1. Function in Array

  ```js
  module.exports = {
      plugins: [
          require('./rssPlugin.js')   
      ]
  }
  ```

2. String in Array

  ```js
  module.exports = {
      plugins: [
          'pluginName', // will to load 'vuepress-plugin-${pluginName}'
          'vuepress-plugin-rss', // also support full name
      ]
  }
  ```

3. Array in Array (Babel Style)

  This configuration style comes from babel: 

  ```js
  module.exports = {
      plugins: [
          [
            'rss',
            {
                option1: '1',
                option2: '2'
                // ...
            }
          ]
      ]
  }
  ```

4. Object in Array

  This configuration style comes from @dacsang97: 

  ```js
  module.exports = {
      plugins: {
          resolve: 'rss', // resolve => 'name' ?
          options: {
              option1: '1',
              option2: '2'
          }
      }
  }
  ```
  
  I think that the first two style are sure to support. so we need to make choices in the latter two:
  
  [![](https://api.gh-polls.com/poll/01CBS258KKKNPXT60K2T43W2TT/Array%20in%20Array%20(Babel))](https://api.gh-polls.com/poll/01CBS258KKKNPXT60K2T43W2TT/Array%20in%20Array%20(Babel)/vote)
  [![](https://api.gh-polls.com/poll/01CBS258KKKNPXT60K2T43W2TT/Object%20in%20Array)](https://api.gh-polls.com/poll/01CBS258KKKNPXT60K2T43W2TT/Object%20in%20Array/vote)
  
  
  Thank you for all of your guys' participation!

**Comment by dacsang97** [comment]
I had implemented to run `Function` and `AsyncFunction`
https://github.com/dacsang97/vuepress/blob/673cc2e44d6f1694d21ef855aaadc2b73de7e5eb/lib/prepare.js#L79-L82
Do you think we should support `Generator Function` ?

**Comment by ulivz** [comment]
@dacsang97 I have seen your change, cool, but`Generator Function` is unnecessary. maybe you can add support for `return Promise`.

**Comment by mdaffin** [comment]
> 1. Figure out the responsibility of plugin.

I agree on the options side, my pull request was just an experiment to figure out what would be required. Your object looks reasonable but I think it might be worth adding a `routes: []` section to allow plugins to hint to the ssr additional routes that it should attempt to render that don't have corresponding markdown files (ie more dynamic components added by the theme). This might want to live inside `siteData` though.

It is also worth adding a base URL to `siteData` as a number of plugins require this value (RSS feeds, sitemaps etc) and being able to inject this at build time is also worthwhile (for example for changing it during [netlifys preview deploys](https://www.netlify.com/docs/continuous-deployment/#branches-deploys)).

> 3. Deciding on the plugin's API.

I vote for 1. First-order function as it looks cleaner to plugin developers and it is only ever going to be a run once function.

> 4. Deciding on the usage of plugins

I prefer the Object in Array like the way Nuxt does it:

```
module.exports = {
  plugins: [
    { src: '~/plugins/vue-notifications', ssr: false }
  ]
}
```

Keeping things similar to Nuxt is a good way to go as I suspect there will be a crossover of the user base here.

**Comment by mdaffin** [comment]
Also, what about theme/site plugins? ie ones that are baked into a theme or site like in my original implementation. I think we can get rid of the site ones as that is covered by the plugins array in the config, but there should be a way for themes to add to the list of plugins, maybe a `config.js` inside the theme? Or just treat the theme as a plugin (as my implementation does)?

**Comment by dgpgdev** [comment]
i agree with @ulivz, if anyone can write a plugin we need to secure input data. 
i agree too with @mdaffin to expose plugin as nuxt way.

**Comment by dgpgdev** [comment]
i love how vue cli use plugin maybe can we use same for vuepress to install and manage plugin .

**Comment by ycmjason** [comment]
@dgpgdev I don't think it is suitable. As a cli, the plugins installed are global. It would be confusing to have `vuepress add <plugin>` since the plugin is not installed globally. It would make much more sense to do `npm i --save-dev vuepress-plugin-<plugin>`.

**Comment by dgpgdev** [comment]
i agree, but often we need same configuration (rssfeed, sitemap...) for many project. ```yarn add vuepress-plugin-<plugin>``` is correct too. I try to think of what is simpler to use.

**Comment by mdaffin** [comment]
@dgpgdev all dependencies of a project should be inside the `package.json` for that project and there should be no side effects from globally installed packages (or you end up wot the 'It works for me' problem).

If you want to use the same plugins/base structure for many projects you should use vue cli to create a template for vuepress with all your plugins and desired config in the template. Vuepress does not need to know or understand vue cli at all and yarn/npm are the tools you should be using for managing project level dependencies.

**Comment by ycmjason** [comment]
as vue-cli is moving away from templates, it makes sense to create a vue-cli plugin that create a vuepress project with a bunch of vuepress plugin options to be selected during `vue create`.

**Comment by mdaffin** [comment]
Another point to consider: allowing plugins a hook into the client side code to allow them to register new dynamic components or otherwise change the client-side behaviour in a similar way to the `enhanceApp.js` currently does.

**Comment by dacsang97** [comment]
Based on the results of the voting, I had updated plugin API to `first-order function`, use `Babel style` for configuring extra options. Now plugin support return Promise (5cdb744). Then I clone `options` to `exposedOptions` in order to avoid user modify system config (8aec214).

**Comment by samburgers** [comment]
+1 for Additional content sources... such as Contentful, WordPress Headless etc at build time!

**Comment by eyleron** [comment]
### Headless CMS, data via REST / GraphQL
A lot of the static site generators hook to data-driven content sources, such as headless headless CMS like DatoCMS, StoryBlok, Netlify, Snipcart, ButterCMS, etc. 
Some have RESTful API's, some provide GraphQL. 

For my less technical staff, I was considering a headless CMS for topic editing as opposed to a Markdown or AsciiDoc file editor.

**Comment by lunelson** [comment]
One cloud CMS which would integrate quite easily is Dato, which —in addition to REST and soon GraphQL APIs— provides a workflow where all content can be 'dumped' to markdown files and then processed by a further the build process

https://www.datocms.com/

**Comment by EnMod** [comment]
I am currently trying to finagle a workflow for DatoCMS import at build time that involves _another_ SSG running a build, then grabbing JSON from that build to add to VuePress.  To have Dato or other headless CMSs import-able (?) and configurable directly within VuePress would be amazing.

**Comment by lunelson** [comment]
@EnMod check out this dato documentation WRT metalsmith, it walks through how to dump your data in to markdown files, and it should give you an idea how to configure the script to output in the directory / naming scheme required by VuePress. 

https://www.datocms.com/docs/metalsmith/

Alternately you can dump Dato data to YML or JSON, and just `require()` them in to your app, as this is also supported by webpack

**Comment by EnMod** [comment]
@lunelson Thanks for that, very nifty! I'm managing a slider gallery as one of my models, so I might either:

- dump all gallery items to markdown files and include them in the gallery's page (will have to check docs again to see if I can read the file system and include all in a folder) 
- Go the JSON route and loop with a `v-for`

Either way, metalsmith's integration a good solution.  Having it right there in VuePress, ready at build time, would save quite a bit of trouble though haha.

**Comment by ulivz** [comment]
#421
