### ISSUE TITLE
Build does not work in IE11, .js files don't get transpiled

### ISSUE THREAD

**Issue by kouts** [vuejs/vuepress#1990]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Vuepress site does not work on IE11, console throws syntax and invalid character errors.
By examining the generated .js files it seems that they don't get transpiled for IE11, e.g there are
still arrow functions present etc.
#### Steps to reproduce
You can reproduce it with a default Vuepress installation 
and you can also view it [here](https://kouts.github.io/vue-modal/demo/#) 
Check for example files generated inside the [js dir](https://github.com/kouts/vue-modal/tree/master/demo/assets/js)

#### What is expected?
Vuepress to be compatible with IE11

#### What is actually happening?
Vuepress is not compatible with IE11, js files don't get transpiled.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
  System:
    OS: Linux 3.16 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (2) x64 Intel(R) Core(TM) i7-4712MQ CPU @ 2.30GHz
  Binaries:
    Node: 9.11.2 - ~/.nvm/versions/node/v9.11.2/bin/node
    Yarn: Not Found
    npm: 5.6.0 - ~/.nvm/versions/node/v9.11.2/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.2.0
    @vuepress/theme-default:  1.2.0
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found

**Comment by kefranabg** [comment]
Hi @kouts

Did you check if there was already an existing issue that solve your problem? Please check [these issues](https://github.com/vuejs/vuepress/issues?utf8=%E2%9C%93&q=is%3Aissue+IE11+) that might solve your problem.

**Comment by kouts** [comment]
Thank you @kefranabg, I have already searched for a workaround but haven't managed to find a solution yet. In my opinion, VuePress should work OOB with IE11 as also stated by @yyx990803 [here](https://github.com/vuejs/vuepress/issues/135#issuecomment-382422190)
If that's not the case maybe it should be added in the docs that VuePress doesn't support IE11.

**Comment by wesgro** [comment]
Ran into this as well. Seeing arrow functions not getting transpiled in the app bundle

**Comment by kouts** [comment]
Digging a little more into this it seems that the regex defined [here](https://github.com/vuejs/vuepress/blob/1138db48637a3befa0b7e2f02c61175385697119/packages/%40vuepress/core/lib/node/webpack/createBaseConfig.js#L149) doesn't match anything and this results in files not getting transpiled.
Now, replacing the regex with something like
```
if (filePath.includes('/node_modules/@vuepress/') && filePath.endsWith('.js')) {
  return false;
}
```
transpiles the files but polyfills required by IE11 seem that are not present.

**Comment by meteorlxy** [comment]
#2064 can partially fix this issue.

But I found `Object.assign` is still not polyfilled. Those polyfills are splitted into other bundles, which are not imported by webpack correctly.
