### ISSUE TITLE
Open a PR on Wappalyzer to detect VuePress sites

### ISSUE THREAD

**Issue by kefranabg** [vuejs/vuepress#1992]
## Feature request

Open a PR to [Wappalyzer](https://github.com/AliasIO/Wappalyzer) chrome extension so it can detect VuePress sites.

#### Are you willing to work on this yourself?
Yes

**Comment by kefranabg** [comment]
We can identify a VuePress website by adding a generator meta tag `<meta name="generator" content="Vuepress v1.2.0">`

**Comment by nimitbhargava** [comment]
Can I take this up? @kefranabg

**Comment by kefranabg** [comment]
Sure @nimitbhargava, let me know if you have some questions.

**Comment by nimitbhargava** [comment]
@kefranabg 
I checked [https://vuepress.vuejs.org/](https://vuepress.vuejs.org/) but I don't see `<meta name="generator" content="Vuepress v1.2.0">` tag there. Is this going to implemented later? 🤔

**Comment by kefranabg** [comment]
Nope, you have to open a PR in VuePress 😉

**Comment by nimitbhargava** [comment]
Got it. So I will create PR in VuePress and then Wappalyzer 👍

**Comment by nimitbhargava** [comment]
Shall I use `VuePress` instead of `Vuepress` here (`<meta name="generator" content="Vuepress v1.2.0">`)?

**Comment by kefranabg** [comment]
I think `VuePress` is better. I think you can remove the version after VuePress for now.

**Comment by nimitbhargava** [comment]
Just letting you know, I haven't start this yet. But do plan to 😁
I am currently going through VuePress source code.

**Comment by kefranabg** [comment]
Hi @nimitbhargava are you still working on this one?

**Comment by nimitbhargava** [comment]
I got stuck while running VuePress locally.
@kefranabg Is it possible to pair up for sometime?

**Comment by kefranabg** [comment]
@nimitbhargava sorry for the delay 😅I just made the PR as it was just an html tag to add to the template. see #2133 Hope it's ok for you! Feel free to do a code review if you want to

**Comment by JordanPlayz158** [comment]
It seems that the meta tag shows up in page source but not in developer tools unlike the other meta tags (description and theme-color) which is causing Wappalyzer to not detect VuePress as a technology on VuePress sites.
