### ISSUE TITLE
Feature Request: Custom .eslintrc file

### ISSUE THREAD

**Issue by hankchizljaw** [vuejs/vuepress#202]
Hey team,

First up: amazing work on this project — thank you so much for releasing it! 

What would be great would be enabling us to be able to use our own `.eslintrc` file. I get the situation (screenshot attached) where I consistently get a `File ignored because of a matching ignore pattern` warning when working on components in the `.vuepress/components` and `.vuepress/themes` directories. It'd be great to be able to ignore that and also have my own rules.

### Screenshot
![Screenshot of my Vim editor showing the eslint message referenced above](https://user-images.githubusercontent.com/8672583/39089138-25dd7d06-45b8-11e8-9537-9828095b02fd.png)

Again, thanks for all of the hard work 🚀

**Comment by ulivz** [comment]
Thanks for your reporting!

But VuePress doesn't check you code at runtime. if you use VuePress in your own project, our built-in eslint configuration will not affect you.

**Comment by hankchizljaw** [comment]
Good to know. Thanks again for this project!
