### ISSUE TITLE
Monorepo surpport

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#2020]
- [x] I confirm that this is an issue rather than a question.

## Bug report

In a word, the example below is working well after published, but the plugins are not working while the logs say they are working when in a monorepo environment.

#### Steps to reproduce

I have open issue(#2006 ) a few days ago with no reply. So I am working on my own trying to solve this problem. As I mentioned in #2006, vuepress cannot resolve plugins under another theme / plugins folder correctly. Besides, when using yarn, I found vuepress support for mono repo is still bad.

Here is an example.

In [vuepress-theme-hope](https://github.com/Mister-Hope/vuepress-theme-hope), you can run the `theme-test:serve` script with yarn. It is using monorepo behavior to provide some packages in the workspace. The log display while serving says that al;l the plugin applyed successfully, but will looking at the serve / build result , I found none of them is working.

But when it is on a non-monorepo environment (I publish it to npm, and serve the theme as a package), all the feature works well. The plugins are applying successfully. You can see it at [here](https://github.com/Mister-Hope/blog).

I wonder you can give some helps about it, or have a look at #2006 and fix it. Both of them will improve my situation now.

#### What is expected?

When runing `theme-test:serve`, the plugins should be applyed.

#### What is actually happening?

- Monorepo env

```
wait Extracting site metadata...
tip Apply theme vuepress-theme-hope (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin copyright (i.e. "vuepress-plugin-copyright") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin named-chunks (i.e. "vuepress-plugin-named-chunks") ...
tip Apply plugin @mr-hope/comment (i.e. "@mr-hope/vuepress-plugin-comment") ...
tip Apply plugin md-enhance (i.e. "vuepress-plugin-md-enhance") ...
tip Apply plugin mathjax (i.e. "vuepress-plugin-mathjax") ...
tip Apply plugin @mr-hope/screen-full (i.e. "@mr-hope/vuepress-plugin-screen-full") ...
tip Apply plugin @mr-hope/theme-color (i.e. "@mr-hope/vuepress-plugin-theme-color") ..
```

No error in the log, while part of the plugin is working, part of the plugin is not.

- Use the publish packages which contains exactly the same code:

All the plugins are working well.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by meteorlxy** [comment]
#2022 #2006
