### ISSUE TITLE
Service worker not registered in index.html

### ISSUE THREAD

**Issue by thepassle** [vuejs/vuepress#2021]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- clone https://github.com/open-wc/open-wc/
- update vuepress to 1.2.0
- follow instructions https://vuepress.vuejs.org/plugin/official/plugin-pwa.html#usage

#### What is expected?

Vuepress generates a service worker and registers the generated service worker in the index.html

#### What is actually happening?

The service worker is generated, but there is no service worker registration in the index.html

Edit: I also see the `SWUpdatePopup` isn't being handled, which results in errors:

<img width="734" alt="Screenshot 2019-11-13 at 21 14 15" src="https://user-images.githubusercontent.com/17054057/68800563-a3041b00-065a-11ea-925c-90d3b0a19a2f.png">
<img width="297" alt="Screenshot 2019-11-13 at 21 14 08" src="https://user-images.githubusercontent.com/17054057/68800565-a3041b00-065a-11ea-97d7-f5e67db55910.png">

**Comment by meteorlxy** [comment]
Service worker is not available on `127.0.0.1`.

Test on `localhost` or domains with HTTPS enabled.

See https://developers.google.com/web/fundamentals/primers/service-workers
