### ISSUE TITLE
Extending theme can not handle plugins correct on Linux

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#2022]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I create a minal bug repo [here](https://github.com/Mister-Hope/vuepress-bug) for you.

#### Steps to reproduce

```bash
yarn global install lerna
yarn run lerna:bootstrap
yarn run theme-test:serve #Or yarn run theme-test:build  They should have the same result
```

#### What is expected?

A backtotop button working well.

#### What is actually happening?

On Windows it's working fine:
![image](https://user-images.githubusercontent.com/33315834/68843852-c3d47b00-0703-11ea-9b8d-0374ce7f8295.png)

But on Linux, it's not:

![image](https://user-images.githubusercontent.com/33315834/68843931-e2d30d00-0703-11ea-958e-e6bf1bf51a94.png)

#### Other relevant information

Linux Env:
- ubuntu 18.04
- node 12.13.0
- yarn 1.19.1
- vuepress 1.2.0

Windows Env:
- 19H2(1909)
- node 12.13.0
- yarn 1.19.1
- vuepress 1.2.0

Besides, this problem belongs to #2020 .

I met this problem nearly half a month ago, and now I finally found out some bugs. With your help, this can be faster. Really needs the offical helps here bro! TAT

**Comment by Mister-Hope** [comment]
Hey, you are ignoring my issues.

If you don’t have time to fix it, or just don’t want to fix it, at least make a comment or add a “won’t fix” label please. 

Besides I tried it on two windows machines and three linux machines.

**Comment by kefranabg** [comment]
@Mister-Hope thanks for opening the issue.

> Hey, you are ignoring my issues.
> 
> If you don’t have time to fix it, or just don’t want to fix it, at least make a comment or add a “won’t fix” label please.

We're not ignoring your issue.

Remember that open source means we work on our free time and don't get paid for it. 

There's more than 150 ongoing issues opened on this project. Your turn will come.

**Comment by Mister-Hope** [comment]
> @Mister-Hope thanks for opening the issue.
> 
> > Hey, you are ignoring my issues.
> > If you don’t have time to fix it, or just don’t want to fix it, at least make a comment or add a “won’t fix” label please.
> 
> We're not ignoring your issue.
> 
> Remember that open source means we work on our free time and don't get paid for it.
> 
> There's more than 150 ongoing issues on this project. Your turn will come.

Thanks, I know all the things you reply, I just thought you are replying thought the timeline. I have been waiting for 12 days patiently.
, but today I saw you replyed on newer issues, soI misunderstood you ignore this one, sorry about that. 😅

**Comment by Mister-Hope** [comment]
Appreciate for your work on the awesome vuepress first. 

Just a personal opinion, for a open source project, I think solving the issues at any time with any sequence is right. But I really think it’s not good to review and apply the issues partially if the ignore ones already provided all that he can.

**Comment by kefranabg** [comment]
No answer does not mean your issue is ignored. I saw your issue and didn't answer yet because it requires me to check your reproduction repo, check if it's a real bug and so on.

Also I won't label the issue as a bug as I'm not sure that it's a real one. And this requires some time.

**Comment by Mister-Hope** [comment]
Got it :)

Franck Abgrall <notifications@github.com> 于 2019年11月26日周二 21:12写道：

**Comment by meteorlxy** [comment]
You are wasting our time. Check your file name `enhanceAppFIle.js` => `enhanceAppFile.js`
