### ISSUE TITLE
sideBar config

### ISSUE THREAD

**Issue by Myu1533** [vuejs/vuepress#203]
![default](https://user-images.githubusercontent.com/6835660/39090007-b7f8c75c-4605-11e8-8758-0b10cbb6b3c0.png)

if didn't set `sideBar: auto` with YAML,the sideBar didn't match the title of each page,only show the path for each page.

But in official demo, it didn't set  `sideBar: auto` yet, but the sideBar worked well.

**Comment by ulivz** [comment]
Where can I to get this file's content?

**Comment by ulivz** [comment]
reproduced this bug, `sideBar: auto` is not necessary, for now you just need to remove this comments.

**Comment by ulivz** [comment]
This bug is due to your `frontmatter` has some duplicate space which will cause the frontmatter get unexpected parsing result:

```yml
[Cannot have space]---[Cannot have space]
...
[Cannot have space]---[Cannot have space]
```

**Comment by Myu1533** [comment]
![default](https://user-images.githubusercontent.com/6835660/39129209-7e39bde0-473c-11e8-96be-30ea6d6f4f42.png)


this is my config.js. translate is a practicing for fun : ).
