### ISSUE TITLE
The dropbox was not closed when I select language

### ISSUE THREAD

**Issue by tuhongwei** [vuejs/vuepress#2032]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce
reproduce address: [https://github.com/tuhongwei/issueDemo/tree/master/vuepress](https://github.com/tuhongwei/issueDemo/tree/master/vuepress)
1. yarn install
2. yarn dev
3. Click the '选择语言' button and then click the 'English' button, the dropdown box is still not closed, but clicking the '简体中文' button is no problem. 

The another problem is that the build process will stop when I modify the 'config,js' file.

#### What is expected?
The dropdown box is closed like clicking the '简体中文' button
#### What is actually happening?
The dropdown box is not closed
#### Other relevant information
I try to clone the official repository and it is no problem, I guess may be the environment effect.
- Output of `npx vuepress info` in my VuePress project:

**Comment by ludanxer** [comment]
Hi @tuhongwei ,

Thx for the report

This is a known issue, which was fixed in #1952 

pls wait for the next release

**Comment by tuhongwei** [comment]
@ludanxer does the another problem that the build process will stop when I modify the 'config,js' file have a solution?

**Comment by kefranabg** [comment]
@tuhongwei please report the second problem in a separate issue and provides more infos (steps to reproduce or link to a repos that reproduce the error)
