### ISSUE TITLE
Plugins declared in config.js do not work

### ISSUE THREAD

**Issue by Buydens** [vuejs/vuepress#2033]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
Running yarn dev or yarn build will throw a warning:
`warning An error was encounted in plugin "@vuepress/plugin-back-to-top"`

When running dev server or after building, none of the plugins work.
And neither of both work.

#### Steps to reproduce
I simply ran `yarn create vuepress` and selected the Doc theme preset.

#### What is expected?
For the plugins to work when added via Yarn and added in the config.js

#### What is actually happening?
There are two plugins added in config.js:
`plugins: [
    '@vuepress/plugin-back-to-top',
    '@vuepress/plugin-medium-zoom',
  ]`

None of these work, both have the same warning when running yarn dev or yarn build.

#### Other relevant information
I used to run my Vuepress but kept getting these errors, then I decided to use this boilerplate but the issues continue.

Pretty novice in Vuepress but I just followed the documentation and I can't find a way to see what activates these warning.

**Comment by Buydens** [comment]
It works after running: `yarn add -D @vuepress/plugin-back-to-top` looks like it just didn't work right out of the box via `yarn create vuepress` and then going for the docs boilerplate. (for me)

**Comment by renqi1996** [comment]
I used npm to create my Vuepress project, and I found this problem too. Still do not know how to fix it...

**Comment by ludanxer** [comment]
@renqi1996 As warned in the [document site](https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project), try to yarn instead of npm. And as @Buydens suggested, run `yarn add -D @vuepress/plugin-back-to-top` to add the dependency. If the problem is still there, can you provide more context?
> We currently recommend using Yarn instead of npm when installing VuePress into an existing project that has webpack 3.x as a dependency, because npm fails to generate the correct dependency tree in this case.
