### ISSUE TITLE
Service worker not registered in index.html and SWUpdatePopup is not handled

### ISSUE THREAD

**Issue by thepassle** [vuejs/vuepress#2035]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- clone https://github.com/open-wc/open-wc/
- update vuepress to 1.2.0
- `yarn add -D @vuepress/plugin-pwa@next`
- add `'@vuepress/pwa'` to plugins in `config.js`
- add links etc in the `head` property
- `npm run vuepress:build`
- `cd _site && npx http-server -o`
- navigate to `localhost:8080` instead of `127.0.0.1:8080`

#### What is expected?

Vuepress generates a service worker and registers the generated service worker in the index.html

#### What is actually happening?

The service worker is generated, but there is no service worker registration in the index.html

<img width="1680" alt="Screenshot 2019-11-24 at 21 33 21" src="https://user-images.githubusercontent.com/17054057/69501128-344c7a80-0f02-11ea-885f-8084d9a6300d.png">

`config.js`:

```js
  /* ... */
  plugins: ['@vuepress/google-analytics', '@vuepress/pwa'],
  head: [
    ['link', { rel: 'icon', href: '/logo.png' }],
    ['link', { rel: 'manifest', href: '/manifest.json' }],
    /* etc */
```

**Comment by kefranabg** [comment]
@thepassle Could you try with the latest version of VuePress ?

**Comment by thepassle** [comment]
I tried with vuepress 1.2.0 as mentioned in the original post, and seems to be the most recent version according to npm https://www.npmjs.com/package/vuepress

**Comment by kefranabg** [comment]
Oops, I read to fast 😉

**Comment by meteorlxy** [comment]
It would be nice if you can provide a __direct__ reproduce repo/branch for this 😅

**Comment by meteorlxy** [comment]
WTF

https://github.com/open-wc/open-wc/blob/745c945918760067ecb97b0785ad6eb5e9c8aba3/docs/.vuepress/config.js#L149

**Comment by thepassle** [comment]
Well damn. Sorry about that guys, I totally missed that. Thanks for taking a look, I appreciate it!
