### ISSUE TITLE
Changing `temp` in `config.js` as per https://vuepress.vuejs.org/config/#temp does not work

### ISSUE THREAD

**Issue by mponton** [vuejs/vuepress#2038]
- [X] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. Change `temp` to another path in `.vuepress/config.js`
2. Run `vuepress build`
3. Temporary files are still created under `/path/to/@vuepress/core/.temp`

#### What is expected?

Reading https://vuepress.vuejs.org/config/#temp I understand that by changing `temp` in `config.js` like this:

```
module.exports = {
    temp: "D:/TEMP/6f35127b-d15a-408e-b976-9a6e7d8b00fe/work"
}
```

Should tell `vuepress build` to use this folder instead of `/path/to/@vuepress/core/.temp`.

#### What is actually happening?

Running `vuepress build` still generate temp files under `/path/to/@vuepress/core/.temp` even if `.vuepress/config.js` contains another path for `temp`.

#### Other relevant information

Running `vuepress build --temp D:/TEMP/6f35127b-d15a-408e-b976-9a6e7d8b00fe/work will correctly create temp files under the specified directory so this is not a show stopper, but I wanted to report the issue so it's addressed or the doc is updated appropriately.

I want to change the temporary files location because the `vuepress build` process is to be run under an account that should not have write access to `/path/to/@vuepress/core` even if limited to `.temp`.

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: Windows Server 2016
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
  Binaries:
    Node: 12.13.0 - E:\<removed>\node\node.EXE
    Yarn: Not Found
    npm: 6.12.0 - E:\<removed>\node\npm.CMD
  Browsers:
    Edge: Not Found
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress:  1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

**NOTE:** I'm not sure why `envinfo` is not picking up all information needed below. My `node` setup is "portable" and contains the following in `etc/npmrc`:

```
prefix=E:\<removed>\node\npm-global
cache=E:\<removed>\node\npm-cache
```

`vuepress` work as expected (other than the current issue being reported).

Thanks for the great project!

**Comment by mponton** [comment]
@ludanxer @meteorlxy Wow! Incredible turnaround! 😃 Thanks a lot!

**Comment by Mister-Hope** [comment]
When can this be publish? 😭
This is the second bug I met since the 1.2.0 release @ulivz , please spend a couple of minute publishing a new version. It has been almost three month.
