### ISSUE TITLE
Title is being rewrited with VuePress

### ISSUE THREAD

**Issue by IdkWhosThis** [vuejs/vuepress#2042]
- [ ] I confirm that this is an issue rather than a question.

## Bug report

Hello,
I just started with using VuePress for my API docs and I have one problem rn.
I set image in navbar instead of title (in config.js):
```js
themeConfig: {
    logo: '/navLogo.png',
}
```
and its working. When I used vuepress build command, I hade site title VuePress. I went into index.html and edited
```html
<title>VuePress</title>
```
to
```html
<title>CRAPI</title>
```
but it still keep showing VuePress as title. Is there any other way, how to do that without adding title in config.js? (because I want only image in nav bar, not text)

#### Steps to reproduce
See above ^^

#### What is expected?
Title will not be rewrited with VuePress.

#### What is actually happening?
Title is rewrited with VuePress.

#### Other relevant information

- Your OS: Ubuntu 18.04
- Node.js version: 10.17.0
- Browser version: Chrome: N/A
- Is this a global or local install?: Global
- Which package manager did you use for the install?: npm

**Comment by meteorlxy** [comment]
https://vuepress.vuejs.org/config/#title
