### ISSUE TITLE
EPERM when running scandir

### ISSUE THREAD

**Issue by ryanccn** [vuejs/vuepress#2045]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

I don't know whether this is a macOS-specific issue.

```bash
$ npm i -g vuepress (or yarn global add vuepress)
$ vuepress
```

#### What is expected?

The expected thing was that Vuepress was supposed to build up a fully working Vue-powered website and be able to serve Markdown files.

#### What is actually happening?

[![asciicast](https://asciinema.org/a/284113.svg)](https://asciinema.org/a/284113?t=99)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
(node:55057) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, scandir '/Users/ryanccn/.Trash'
(node:55057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:55057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ludanxer** [comment]
Hi @ryanccn 

I can indeed reproduce this error when I try to run `vuepress` in my HOMEPATH on Windows 10, create a new folder and run the command inside it seems to solve the error:

```shell
cd ~
mkdir test
cd test
vuepress
```

However, I'm confused about what you are trying to do. Please check out the [getting-started](https://vuepress.vuejs.org/guide/getting-started.html) for more detail and find all available CLI commands in the [document](https://vuepress.vuejs.org/api/cli.html)

**Comment by ryanccn** [comment]
@ludanxer The [getting-started](https://vuepress.vuejs.org/guide/getting-started.html) talks about playing around with Vuepress globally, and this

```sh
# install globally
yarn global add vuepress # OR npm install -g vuepress

# create a markdown file
echo '# Hello VuePress' > README.md

# start writing
vuepress dev

# build
vuepress build
```

did not work.

I tried this in a separate folder and it worked, but the Getting Started talks nothing of this error. Maybe can edit the Getting Started to create a new folder or change the `scandir` in the Vuepress code?

**Comment by ryanccn** [comment]
`vuepress` was just something used to invoke the error. I wasn't trying to do anything. :smile:

**Comment by ludanxer** [comment]
You can try to open a PR that adds something like `mkdir my-doc-site && cd my-doc-site`, I'm not sure if it will get merged.

I recall that I see a [blog](https://medium.com/@_ulivz/intro-to-vuepress-1-x-7e2b7885f95f) mentions a quick start `yarn create vuepress`, it also requires you to run the command **inside an empty directory**. However, the project [create-vuepress](https://github.com/vuepressjs/create-vuepress) is not maintained for a while.

You can wait for core contributors come across this issue, I'm not sure what they want. Creating a new CLI command `vuepress create <folder-name>` may also be a choice.

**Comment by ryanccn** [comment]
Okay. Thanks! This is pull request #2051.
