### ISSUE TITLE
Feature Suggestion: Markdown Inside Slotted Components

### ISSUE THREAD

**Issue by Loilo** [vuejs/vuepress#205]
It would be nice to be able to write markdown syntax *inside* Vue components located in markdown files. That would allow for markdown-centric UI components:

```html
<!-- readme.md -->
<Accordion>
  <AccordionItem label="One">
  This is the *first* section.
  </AccordionItem>
  <AccordionItem label="Two">
  This is the *second* section.
  </AccordionItem>
  <AccordionItem label="Three">
  This is the *third* section.
  </AccordionItem>
</Accordion>
```

While I could parse these slots inside the `AccordionItem`, that would unfortunately not benefit from SSR. So it would be cool having some way to enable the markdown renderer inside component slots. I'm not sure what a good API would look like, but I could imagine a special attribute, for example `<AccordionItem vp-markdown />`.

Such a component could be designed even more content-centric:

```html
<Accordion vp-markdown>
* One

  This is the *first* section.

* Two

  This is the *second* section.

* Three

  This is the *third* section.
</Accordion>
```

That's obviously not the greatest use of Vue components (since it could easily be implemented in plain JavaScript), but it's nice & clean markdown for content authors and would produce readable markup in the SSR.

**Comment by ulivz** [comment]
Thanks! But it should be worked. You just **missed two blank lines:**

```vue
<Accordion vp-markdown>

* One

  This is the *first* section.

* Two

  This is the *second* section.

* Three

  This is the *third* section.

</Accordion>
```

**Comment by Loilo** [comment]
Oh dear, I didn't realize that. Thanks for pointing it out!

**Comment by Eterion** [comment]
Can I ask why are those blank lines required?

I wanted to create custom component that would replace [custom blocks](https://vuepress.vuejs.org/guide/markdown.html#custom-containers), because that custom block syntax `:::` doesn't play well with prettier.

Is there any way to circumvent this? So I could write

```vue
<Tip>
Content with **markdown** support
</Tip>
```

instead of


```vue
<Tip>

Content with **markdown** support

</Tip>
```

with my component?

**Comment by Loilo** [comment]
I don't think there's a way to do that unless you're going to change the parser directly. 
This behaviour is provided by [`markdown-it`](https://github.com/markdown-it/markdown-it), the markdown parser VuePress uses.

See [this `markdown-it` demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3CTip%3E%5CnContent%20with%20%2A%2Amarkdown%2A%2A%20support%5Cn%3C%2FTip%3E%5Cn%5Cn%3CTip%3E%5Cn%5CnContent%20with%20%2A%2Amarkdown%2A%2A%20support%5Cn%5Cn%3C%2FTip%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Comment by Eterion** [comment]
Thanks for the info. I'll just keep the blank lines, it's not a deal breaker for me.
