### ISSUE TITLE
@vuepress/back-to-top Can't work.

### ISSUE THREAD

**Issue by xiaoojun** [vuejs/vuepress#2050]
@vuepress/back-to-top Can't work.

**Comment by ludanxer** [comment]
@xiaoojun Please use the issue template.

See #2033 , run `yarn add -D @vuepress/plugin-back-to-top` to add the dependency.

Provide more detail if that doesn't work for you.

**Comment by xiaoojun** [comment]
Thank you for your reply, but  it still can't wrok.
code: 
# package.json 
"devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.2.0",
    "vuepress": "^1.2.0"
  }
# config.js
module.exports  = [
    '@vuepress/back-to-top',
]

**Comment by ludanxer** [comment]
Please check out the [document > using-a-plugin](https://vuepress.vuejs.org/plugin/using-a-plugin.html#using-a-plugin), your `config.js` is wrong.

**Comment by xiaoojun** [comment]
I found the cause of the error. I put the plugin under the themeConfig, 😂
 Thank you very much.

**Comment by ludanxer** [comment]
@xiaoojun Can you close this issue if your problem is solved? Thanks.

**Comment by meteorlxy** [comment]
@ludanxer Thanks for your help to answer questions :heart:
