### ISSUE TITLE
Is slot working in ParentLayout?

### ISSUE THREAD

**Issue by stardustrain** [vuejs/vuepress#2054]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. I'd made theme folder at under .vuepress folder.
2. Make index.js file at under theme folder and write this:
```
module.exports = {
  extend: '@vuepress/theme-default'
}
```
3. And make layouts folder at under .theme, Layout.vue file at layouts folder and write this:
```
<template>
  <ParentLayout>
    <template #page-bottom>
      <vue-disqus />
    </template>
  </ParentLayout>
</template>

<script>
  import ParentLayout from '@parent-theme/layouts/Layout'

  export default {
    components: {
      ParentLayout,
    },
  }
</script>
```

#### What is expected?
I will render disqus component every page.

#### What is actually happening?
Doesn't render disqus component.

#### Other relevant information
I'd refereced by https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-vue/layouts/Layout.vue.

- Output of `npx vuepress info` in my VuePress project:

System:
    - OS: macOS Mojave 10.14.6
    - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Binaries:
    - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    - Yarn: 1.19.1 - /usr/local/bin/yarn
    - npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
Browsers:
    - Chrome: 78.0.3904.108
    - Firefox: 70.0.1
    - Safari: 13.0.3
npmPackages:
    - @vuepress/core:  1.2.0 
    - @vuepress/theme-default:  1.2.0 
    - vuepress: ^1.2.0 => 1.2.0 
npmGlobalPackages:
    - vuepress: Not Found

**Comment by ludanxer** [comment]
Hi @stardustrain ,

Thanks for the report. I think it's fixed by #1951 , and hasn't come out yet. Please patiently wait for the next release.

**Comment by stardustrain** [comment]
@ludanxer Thank you for your notice! Therefore is it possible to close this issue?

**Comment by ludanxer** [comment]
I'm not sure. You can wait for the core contributors to come across this issue. There are quite a few commits after 1.2.0, maybe it's time for a new release.

**Comment by kefranabg** [comment]
The fix will be available in the next release

**Comment by AntoineAugusti** [comment]
Hello!

Any way to use the `master` version with this unreleased fix?

I've tried pulling the master version in `package.json` with `"vuepress": "vuejs/vuepress#master",` but the `vuepress` CLI is unavailable after installation.
