### ISSUE TITLE
[Bug Report] files are not transpiled correctly

### ISSUE THREAD

**Issue by worships** [vuejs/vuepress#2060]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- https://worships.github.io/vuepress-1.x/
- Click SidebarButton on mobile phone

#### What is expected?

- Sidebar appears

#### What is actually happening?

- When click SidebarButton it does not work, the sidebar has not appears

#### Other relevant information

- On mobile phone
    -  iphone
        - [ ] vuepress 1.x
        - [x] vuepress 0.x
    -  android
        - [ ] vuepress 1.x
        - [x] vuepress 0.x

But the official website works well on my mobile phone (https://vuepress.vuejs.org/)

- On PC in debugger mode, F12 press
    -  chrome
        - [x] vuepress 1.x
        - [x] vuepress 0.x
    -  firefox
        - [x] vuepress 1.x
        - [x] vuepress 0.x
    -  edge
        - [x] vuepress 1.x
        - [x] vuepress 0.x
    -  ie
        - [ ] vuepress 1.x (official website also does not work, the sidebar has not appears)
        - [x] vuepress 0.x

#### Test url
- vuepress 1.x https://worships.github.io/vuepress-1.x/ (https://github.com/worships/vuepress-1.x)
- vuepress 0.x https://worships.github.io/vuepress-0.x/ (https://github.com/worships/vuepress-0.x)

**Comment by meteorlxy** [comment]
Sorry but I cannot reproduce this issue.

**Comment by meteorlxy** [comment]
Can only confirm that vuepress 1.x docs site failed in ie 11.

Seem that codes from 3rd party packages are not transpiled correctly (e.g. vuepress-plugin-flowchart, vuepress-plugin-smooth-scroll, etc.)

**Comment by meteorlxy** [comment]
#2064 can partially fix the failure in IE 11.

But `Object.assign` is still not polyfilled.

**Comment by worships** [comment]
> 
> 
> #2064 can partially fix the failure in IE 11.
> 
> But `Object.assign` is still not polyfilled.

Thanks, i don't know how to fix it.

**Comment by meteorlxy** [comment]
Duplicate #1990
