### ISSUE TITLE
Cannot import json file

### ISSUE THREAD

**Issue by Linkontoask** [vuejs/vuepress#2062]
#### Steps to reproduce

Modify the configuration file `config.js`

```
configureWebpack: {
    resolve: {
      alias: {
        'util': path.join(__dirname, 'util')
      }
    },
    module: {
      rules: [
        {
          test: /\.json$/,
          loader: 'json-loader'
        }
      ]
    }
  }
```

Importing json file with `import` in a MD file failed

`Uncaught (in promise) Error: Cannot find module 'util/ttf.json'`

But I created a new `vue` file under the` util` folder, and this vue file can be imported successfully.

#### What is expected?

Compile and get the correct data

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - G:\node\node.EXE
    Yarn: 1.21.0 - C:\Users\LinkMax\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - G:\node\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: 1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by meteorlxy** [comment]
Please provide a reproduction repo.

BTW, you do not need `json-loader` to import json files

**Comment by Linkontoask** [comment]
Sorry, it was my fault that I can load the `json` file correctly
