### ISSUE TITLE
Allow per-component overriding

### ISSUE THREAD

**Issue by davestewart** [vuejs/vuepress#207]
It would be really useful to be able to override theme-components on a per-component basis.

If they were registered globally not locally, could we then override them in `enhanceApp`? :

```js
import Home from './components/theme/Home'

export default ({ Vue, options, router }) => {
    Vue.component('home', Home)
}
```

Either that, or specify components in `config.js` ?:

```js
import Home from './components/theme/Home'

themeConfig: {
    components: {
        home: Home
    }
}
```
Maybe `eject` could be modified, or a new command added to extract the component to override:

```
vuepress extract Home.vue
```

**Comment by davestewart** [comment]
You think it would introduce problems, or you just don't like the idea?

Wordpress has child themes. You can override styles. You can override routing.

Why not just be able to tweak a single element of an otherwise appropriate theme?

**Comment by ulivz** [comment]
Hmmm...

If you just want to override a default theme component, you can just eject out of the custom theme directly.

if only one of the component was ejected, then we will need to clarify the internal interface of all the default themes at the present stage and load the components dynamically at run time according to your preferences. 

The default theme does not want to be so complex. Our priority is to ensure that the core is stable and applied to all the documents of the Vue sub project.

**Comment by davestewart** [comment]
The problem with ejecting, as the docs say, is you lose the ability to upgrade.

So I just tested it...

```vue
// Layout.vue
export default {
  components: { Page, Sidebar, Navbar }, // removed Home
  ...
```
```
// enhanceApp.js
import Home from './components/Home'

export default ({Vue, options, router}) => {
  Vue.component('Home', Home)
}
```

... and it delivers the desired result:

![image](https://user-images.githubusercontent.com/132681/39098093-68e82d12-465d-11e8-9ef7-e970a0f1b123.png)

I don't see how that would affect core stability, it just allows those who know enough about the theme to tweak a component by itself.

**Comment by ulivz** [comment]
"lose the ability to upgrade." —— This is the biggest problem. It seems that you can work in this way, and just demonstrate the simplest component, but if we modify the internal interface? next, will we get the inexplicable issue?

**Comment by davestewart** [comment]
>  but if we modify the internal interface? 

You mean, like this?

```
    <div class="features" v-if="data.features && data.features.length">
      <div class="feature" v-for="feature in data.features">
        <h2>{{ feature.title }}</h2>
        <p>{{ feature.details }}</p>
      </div>
    </div>
```

Well, let's say you change the format for features;  if you do that, the user would need to update his `README.md` front-matter *anyway*, so entire theme, or single component changing a theme's internal or external mechanisms would run the risk of something not working.

> next, will we get the inexplicable issue?

You mean users complaining that something broke?

Well I'm guessing that any developer ejecting the entire theme would have enough Vue knowledge / confidence to work with 15 or so fairly complex components, so surely just ejecting a single component, then having something not work (hypothetically) then that narrows it down a bit?

Would you, at the very least, tag this as a discussion?

**Comment by yyx990803** [comment]
Sorry but no. The whole point is the default theme was designed to fit a specific use case and not aiming to be generically extendable. We have no intention to increase the maintenance surface of the default theme. If you have some specific need, you can either eject or build your own theme.

**Comment by davestewart** [comment]
I guess it can still be done, just not with the default theme then.

Cheers :)
