### ISSUE TITLE
enhanceApp does not always await all promises on page refresh

### ISSUE THREAD

**Issue by staghouse** [vuejs/vuepress#2074]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. Create enhanceApp.js
2. Add 1 or more Promises
3. Store promises in Vue.prototype, siteData, etc, for example, `Vue.prototype.myPromisedData = await myPromiseFunction()`, though it doesnt matter if its a function or try/catch with storage on success
4. Retrieve, for example, `this.myPromisedData` in a component

#### What is expected?

`this.myPromisedData` should always return what data is expected

#### What is actually happening?

The data returns undefined/promise pending/sometimes loads/only returns some promises. Its all wildly inconsistent other than the first promise returned has a higher chance of returning valid.

This seems to be a local-only issue as it does not happen on my production server. Could it be related to the HMR?

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 71.0
    Safari: 13.0.3
  npmPackages:
    @vuepress/core:  1.0.3 
    @vuepress/theme-default:  1.0.3 
    vuepress: ^1.0.3 => 1.0.3 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by meteorlxy** [comment]
Currently, enhanceApp does not handle async functions:

https://github.com/vuejs/vuepress/blob/c2bd6ded5015ede13a24252ca8f726f126e91073/packages/%40vuepress/core/lib/client/app.js#L93-L97

Maybe something like this, or use `Promise.all()` ?

```js
  appEnhancers.forEach(async enhancer => { 
   if (typeof enhancer === 'function') { 
     await enhancer({ Vue, options, router, siteData, isServer }) 
   } 
 }) 
```

**Comment by staghouse** [comment]
As a note, I have tried Promise.all as well, with some variation in consistency: Either all promises resolve, or none.
