### ISSUE TITLE
Why warning in custom container bu warn in built-in component Badge?

### ISSUE THREAD

**Issue by showmethecode9527** [vuejs/vuepress#2080]
#### What problem does this feature solve?
When using warning custom containers, we write like this:
```
::: warning
This is a warning
:::
```

and when using warn(warning) Badge, we write like this:
```html
<Badge text="beta" type="warn"/>
```

in custom containers is `warning` but in built-in component Badge is `warn`, why?

#### What does the proposed API look like?
```html
<!-- use warning rather than warn -->
<Badge text="beta" type="warning"/>
```

#### How should this be implemented in your opinion?
use `warning` as a optional value in built-in component `Badge` rather than `warn`.

#### Are you willing to work on this yourself?
No.

**Comment by kefranabg** [comment]
Actually `warning` value is already supported for the type property, but documentation is not up to date. I'll do an update.
