### ISSUE TITLE
vuepress dev docs不支持https

### ISSUE THREAD

**Issue by iLoveBug** [vuejs/vuepress#2081]
#### What problem does this feature solve?
本地调试时采用https，可以调试一些特定组件如定位组件，这需要https，否则会被拒绝访问

#### What does the proposed API look like?
在config.js中可以这样写：
configureWebpack: (config, isServer) => {
    if (!isServer) {
      return {
        devServer: {
          open: true,
          https: true
        }
      }
    }
  }

#### Are you willing to work on this yourself?
I do, but have no idea

**Comment by ludanxer** [comment]
Hi @iLoveBug , please try to use English next time, so everyone can understand you.

---

`vuepress dev docs` do not support `https`

**What problem does this feature solve?**

While developing locally, some components need `https` to work.

**What does the proposed API look like?**

You can write in the `config.js` like:

```js
configureWebpack: (config, isServer) => {
  if (!isServer) {
    return {
      devServer: {
      open: true,
      https: true
      }
    }
  }
}
```

**Comment by kefranabg** [comment]
> While developing locally, some components need https to work.

🤔 

@iLoveBug can you provide more context?

**Comment by iLoveBug** [comment]
I am developing a vue-based map library, and plan to use VuePress as the documentary tool. During the development, I found I need HTTPS support, for example, I need call the location API to do the further route planning. But recently, location API is forbidden by default for HTTP request, and only allowed for HTTPS. That means I could not do local debugging.

So I prefer to have an easy config method to enable HTTPS in vuepress just as we can do for vue.config.js:
module.exports = {
  devServer: {
    open: true,
    https: true
  }
}

**Comment by kefranabg** [comment]
You can't get HTTPS in a local environment. If you're talking about the [html Geolocation API](https://developer.mozilla.org/fr/docs/Web/API/Geolocation_API) you can use it with localhost.
