### ISSUE TITLE
How to debug with Visual Studio Code and add a property value of Lang

### ISSUE THREAD

**Issue by bosens-China** [vuejs/vuepress#2082]
## Feature request

I also saw chainwebpack in vuecli's document. It has a property, Vue inspect, which is convenient for me to check the configuration of internal webpack. Will vuepress add this property?
At the same time, for multiple languages, I can configure the attribute value of Lang to apply to the page, but if I just want to change the lang attribute of HTML page, such as lang = "zh", then I can hardly set it, so can I add a default lang attribute in config.js?
Finally, how to debug the vuepress project through visual studio code? I found an article by Google, but I couldn't do it by hand
[DEBUGGING VUEPRESS IN VISUAL STUDIO CODE](https://www.marcomark.net/code/vuepress/debugging-vuepress-vscode.html)

#### What problem does this feature solve?
1. Lang default attribute value
2. Configuration details of internal webback of vuepress
3. Visual studio code debugging

#### What does the proposed API look like?
No time

#### How should this be implemented in your opinion?
No time
#### Are you willing to work on this yourself?
No time

**Comment by tolking** [comment]
locales: { '/': { lang: 'zh-CN' }},

**Comment by bosens-China** [comment]
Thank you, locales: {'/': {Lang: 'zh CN'}}, valid
