### ISSUE TITLE
Hi, why does this text prompt errors? What is the correct way

### ISSUE THREAD

**Issue by bosens-China** [vuejs/vuepress#2083]
- [x] I confirm that this is an issue rather than a question.

## Bug report
  Errors compiling template:

  tag <T> has no matching end tag.
#### Steps to reproduce
``` txt
这一更严格的检查应用于除方法或构造函数声明以外的所有函数类型。
方法被专门排除在外是为了确保带泛型的类和接口（如 Array<T>）总体上仍然保持协变。
```

#### What is expected?
By compiling
#### What is actually happening?
error
#### Other relevant information
``` sh

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by ludanxer** [comment]
@bosens-China Interesting use case, change:

```markdown
如 Array<T>
```

into:

```markdown
如 `Array<T>`
```

**Comment by bosens-China** [comment]
> @bosens-China Interesting use case, change:
> 
> ```gfm
> 如 Array<T>
> ```
> 
> into:
> 
> ```gfm
> 如 `Array<T>`
> ```

虽然这样做没问题，但是有没有更优雅的方式，这应该不是vuePress本身的问题

**Comment by ludanxer** [comment]
Sorry, I don't know if there is another way, so it's important that you **use English** here. People who could solve your problem may not speak Chinese.

Actually, if you put `Array<T>` directly in the comment and click preview, you will find the `<T>` disappeared, so I'm not sure that there is a better way.

**Comment by bosens-China** [comment]
> Sorry, I don't know if there is another way, so it's important that you **use English** here. People who could solve your problem may not speak Chinese.
> 
> Actually, if you put `Array<T>` directly in the comment and click preview, you will find the `<T>` disappeared, so I'm not sure that there is a better way.

Thank you. I found that escape characters can be used to solve this problem
Array&lt;t&gt;
