### ISSUE TITLE
How to create a dynamic vue component and include it on vuepress

### ISSUE THREAD

**Issue by SanaviaNicolas** [vuejs/vuepress#2089]
I would like to create a dynamic vue component handle by an input text.

For example I have this phrases: 

- My name is ` `
- ` ` has all root privileges

If an user insert his name in the component I would like to read:

- My name is `John Doe`
- `jdoe` has all root privileges

How can I integrate this in a vuepress .md file?

Thank  you for your support.

**Comment by meteorlxy** [comment]
https://vuepress.vuejs.org/guide/using-vue.html
