### ISSUE TITLE
Using Vue components inside Markdown

### ISSUE THREAD

**Issue by ycmjason** [vuejs/vuepress#209]
Hello,

I am curious if when using custom vue components in markdown, is there anyway to for the vue component to process markdown using the config and library that vuepress is using?

Thank you! I am happy to add a PR and update the doc if it is not already written. 

🎉

**Comment by ulivz** [comment]
Thank you for your idea, but this is not very necessary, because users can use any pre-processor as long as they want.

**Comment by ycmjason** [comment]
As a user, I would love to have the same processor that vuepress is using to keep my markdown writing consistent.

**Comment by ulivz** [comment]
`v-md` is runtime only but processor is compile time only ... ...
