### ISSUE TITLE
Solve ChunkLoadError issue after new deployment

### ISSUE THREAD

**Issue by favoyang** [vuejs/vuepress#2090]
#### What problem does this feature solve?
I use Netlify to deploy a vuepress website. If I leave the website open in browser, then have a new deployment right after, the existing web page will be no longer functional. i.e. search in the existing web page, click on one item. It was hanging.

The console shows the issue of 404

![image](https://user-images.githubusercontent.com/125390/71369384-95d93500-25e5-11ea-9ec3-146fe9363f79.png)

I go back to old deployment and figure out the missing file is usually something like 
```
(window.webpackJsonp=window.webpackJsonp||[]).push([[30],{422:function(t,e,n){"use strict";n.r(e);var s=n(2),l=Object(s.a)({},(function(){var t=this.$createElement;return(this._self._c||t)("ContentSlotsDistributor",{attrs:{"slot-key":this.$parent.slotKey}})}),[],!1,null,null,null);e.default=l.exports}}]);
```

The reason is that each new deployment by netlify is fresh, and trying to reach to old deployment file is no longer existed on new build. I guess this is a common issue for static generator, but is more frequently for vuepress, because of fusing static generator and dynamic vue functions.

Toggle pwa plugin shows no difference.

I wonder what is the best strategy to solve the issue. I hope there's a smart way to force reload the page if vuepress detects a new deployment.

#### What does the proposed API look like?
n/a
#### How should this be implemented in your opinion?
maybe
#### Are you willing to work on this yourself?
maybe

**Comment by favoyang** [comment]
Related posts
- https://community.netlify.com/t/keep-js-chunks-from-old-deploys/5991
- https://github.com/gatsbyjs/gatsby/issues/18866

Seems the suggestion is either
- Catch the chunk error then do a reload
- Starts a service to check etag of index.html regular, then do a reload
- The reload can be a graceful alert like the pwa plugin did

**Comment by favoyang** [comment]
Maybe related https://github.com/vuejs/vuepress/issues/2076

**Comment by cwaring** [comment]
I made [a plug-in](https://github.com/cwaring/vuepress-plugin-chunkload-redirect) to fix this issue for my sites, perhaps you may find it useful too 😎

**Comment by favoyang** [comment]
@cwaring the plugin resolved the issue. Thank you.
