### ISSUE TITLE
Can the sidebar support custom fields?

### ISSUE THREAD

**Issue by veaba** [vuejs/vuepress#2092]
Like:

```js
{'title': 'tf', 'collapsabel': false, 'isExperiment': true, 'children': tfLinks,llda:1},
```

Missing field：
![image](https://user-images.githubusercontent.com/8652596/71398586-d96e8600-265b-11ea-99e3-206c700b271b.png)

The source code should be limited, or can you tell me how to support it?

Sometimes, I may need to make a mark, such as:

![image](https://user-images.githubusercontent.com/8652596/71398670-218da880-265c-11ea-8cf1-14f907a62ac4.png)

**Comment by ludanxer** [comment]
You can try to use [Theme Inheritance](https://vuepress.vuejs.org/theme/inheritance.html#theme-inheritance) to [override ](https://vuepress.vuejs.org/theme/inheritance.html#override-components)the relavent components

**Comment by veaba** [comment]
Reload  CLI ,  will be see it.
Remember to modify the util/index.js file
