### ISSUE TITLE
Front Matter: inconsistent date property

### ISSUE THREAD

**Issue by Hill-98** [vuejs/vuepress#2097]
- [x] I confirm that this is an issue rather than a question.

## Bug report

![1.png](https://i.loli.net/2019/12/27/eZXsVTC1ODq7Rja.png)
![2.png](https://i.loli.net/2019/12/27/m1ArDanbixezG3P.png)

As shown, if a two-digit date, $frontmatter.date have different performance behaviors.

This problem affects how the subject developer handles time

#### Steps to reproduce

https://github.com/Hill-98/vuepress-frontmatter-test

#### What is expected?

Same $frontmatter.date

#### What is actually happening?

Different $frontmatter.date

#### Other relevant information

NodeJS: 13.5.0

Browser: Chrome Canary 81

VuePress: 1.2.0

**Comment by newsbielt703** [comment]
Hi @Hill-98, 

FYI, VuePress' using `gray-matter` which depends `js-yaml` which follows standard yaml types, so all available formats are [here](https://yaml.org/type/timestamp.html).

Currently, we've handled both 2-digits and single-digit in default blog theme, but if it's possible, we should support both format in VuePress.

**Comment by Hill-98** [comment]
I think in all writing formats, the date attribute should return a uniform format.
