### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by LeCoupa** [vuejs/vuepress#21]
When trying to run `vuepress dev .`, this error is triggered. Any idea? :/

<img width="783" alt="screen shot 2018-04-14 at 4 55 12 pm" src="https://user-images.githubusercontent.com/1658644/38770060-e0749dc0-4004-11e8-9980-9b7bd5b673ac.png">

EDIT: I think it is because my version of Node is `v7.5.0`. Let me check one minute. ^^

**Comment by filipsobol** [comment]
Vuepress required Node 8.0 +. Please see [https://github.com/vuejs/vuepress/blob/master/package.json#L98](package.json)
