### ISSUE TITLE
[gray matter] will default transform date format string to utc time

### ISSUE THREAD

**Issue by yuicer** [vuejs/vuepress#2104]
vuepress `"version": "1.2.0"`

well , I find that if I write 
```
---
title: xxx
date: 2019-06-16 17:32:27
---
```
into the MD file.
the $frontmatter.date will be `date: "2019-06-16T17:32:27.000Z"`
it seems the package `"gray-matter": "^4.0.1",` will transform the Date into UTC time.
`vuepress/packages/@vuepress/shared-utils/src/parseFrontmatter.ts`

this is definitely unfriendly to the blog powered by vuepress.
can we have some configuration or hooks before the markdown file stared to compress?

**Comment by newsbielt703** [comment]
It's the intended behavior of [yaml](https://yaml.org/type/timestamp.html).

**Comment by yuicer** [comment]
@newsbielt703 
thanks, I think I will get it transformed myself
