### ISSUE TITLE
How to set the value of threshold in the back-to-top plugin?

### ISSUE THREAD

**Issue by upcwangying** [vuejs/vuepress#2105]
- [x] I confirm that this is an issue rather than a question.

How to set the value of `threshold` in the `back-to-top` plugin?

**Comment by meteorlxy** [comment]
It's not available yet.

---

So why you check this?

> - [x] I confirm that this is an issue rather than a question.

**Comment by upcwangying** [comment]
Thanks. Is this not a bug?

**Comment by meteorlxy** [comment]
It's not listed in the docs: https://vuepress.vuejs.org/plugin/official/plugin-back-to-top.html

You can only find it in the source code.

If you want this feature, you can open a Feature Request, or create a Pull Request for it.

**Comment by upcwangying** [comment]
In my opinion, properties defined in props are for modification by third parties, unless defined in data or in the form of constants
