### ISSUE TITLE
"Module not found" for external scripts in Markdown

### ISSUE THREAD

**Issue by samuba** [vuejs/vuepress#211]
Version 0.7.1

In Markdown files using something like this:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap-reboot.js"></script>`

results in:
```
ERROR in ./README.mdModule not found: Error: Can't resolve 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap-reboot.css?vue&type=script&lang=js' in 'C:\Users\samue_000\test\vuepress' @ ./README.md 2:0-132 3:0-127 3:0-127 9:2-8 @ C:/Users/samue_000/AppData/Roaming/npm/node_modules/vuepress/lib/app/.temp/routes.js
 @ C:/Users/samue_000/AppData/Roaming/npm/node_modules/vuepress/lib/app/app.js
 @ C:/Users/samue_000/AppData/Roaming/npm/node_modules/vuepress/lib/app/clientEntry.js
 @ multi C:/Users/samue_000/AppData/Roaming/npm/node_modules/vuepress/lib/app/clientEntry.js
```

**Comment by yyx990803** [comment]
Remember the whole markdown file is also a Vue single file component, so the script tag will be processed by webpack. For global scripts you need to add it via `head` option in `.vuepress/config.js`.

**Comment by luisDanielRoviraContreras** [comment]
@yyx990803  You could add an example of an external probe probe with something like that but it does not work

```js
head: [
    ['link', { rel: 'icon', href: `/favicon-vuesax.png` }],
    ['script', { src: `https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.min.js` }]
  ],
```

the link works fine but the script does not

**Comment by yyx990803** [comment]
It's working fine for me. Please, don't ask for help for every little problem that you run into... spend a few more minutes and maybe you'll figure out why on yourself. If it's really a bug, **always open a issue with proper reproduction.** Commenting on an existing issue without proper reproduction doesn't help at all.

**Comment by meteorlxy** [comment]
@luisDanielRoviraContreras Some vue-related packages should be involved via `enhanceApp`

**Comment by luisDanielRoviraContreras** [comment]
@meteorlxy Thank you very much and I could solve it by adding

``` js
import Vuesax from 'vuesax'

export default ({
  Vue, // the version of Vue being used in the VuePress app
  options, // the options for the root Vue instance
  router // the router instance for the app
}) => {
  // ...apply enhancements to the app
  Vue.use(Vuesax)
}


```

@yyx990803 Sorry for the inconvenience I will review the problems better and try to find a solution before asking any questions thanks

**Comment by apekarawang** [comment]
For note, I need to restart the dev server for it to works
