### ISSUE TITLE
Why I can't use plugins in vuepress ?

### ISSUE THREAD

**Issue by captainAldi** [vuejs/vuepress#2110]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
I can't use plugins in my vuepress 

#### Steps to reproduce

1) make a empty folder
2) create readme.md and some folder then sub *.md file
3) install a plugins that refer to official docs of vuepress and some youtube videos
4) It says i dont have pakcage.json
5) i create it, and add "script.."
6) i install the plugin again and its has installed
7) change the config.js
8) check my page and not working

#### What is expected?
plugins is working

#### What is actually happening?
plugins not working

#### Other relevant information
i create a new empty folder not in existing project

- Output of `npx vuepress info` in my VuePress project:

![image](https://user-images.githubusercontent.com/48024406/71773746-5b807800-2f95-11ea-9ac6-b1aaefbe11b9.png)

**Comment by ludanxer** [comment]
@captainAldi can you share your repo? So that I can better understand what you are doing.

**Comment by captainAldi** [comment]
> @captainAldi can you share your repo? So that I can better understand what you are doing.

https://github.com/captainAldi/vuepress-test

Thats my repos

**Comment by ludanxer** [comment]
I'm not sure which specific plugin are you referring to. Can you provide more detail to indicate that this is a VuePress' bug?

**Comment by captainAldi** [comment]
> I'm not sure which specific plugin are you referring to. Can you provide more detail to indicate that this is a VuePress' bug?

when i using
https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html#install
and follow the docs, its not working..

when i use
https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html#install
and follow the docs, restart the dev.. its working..

why is that ?

**Comment by ludanxer** [comment]
Well, there is a known issue regarding the hot reload problem: #1283 . You can find more information there.

Basically, if something is not working, try to restart the service.

If this solves your problem, please close this issue, thanks.

**Comment by captainAldi** [comment]
> Well, there is a known issue regarding the hot reload problem: #1283 . You can find more information there.
> 
> Basically, if something is not working, try to restart the service.
> 
> If this solves your problem, please close this issue, thanks.

sorry but the seecond link is different plugin, i updated it..my fault that i wrong paste it before to the same link in the first place... 

i still cant use the official plugin medium zoom or back to top..

**Comment by ludanxer** [comment]
Run `yarn add -D vuepress` to **install VuePress locally**, your problem should be solved. Check out [install inside an existing project](https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project) for more detail.

Thanks for your report.

BTW, you forget to enable [plugin back to top](https://vuepress.vuejs.org/plugin/official/plugin-back-to-top.html) in the `config.js`.

**Comment by captainAldi** [comment]
> Run `yarn add -D vuepress` to **install VuePress locally**, your problem should be solved. Check out [install inside an existing project](https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project) for more detail.
> 
> Thanks for your report. I'm not sure if this is a bug, the globally installed VuePress can't find locally installed plugins.
> 
> BTW, you forget to enable [plugin back to top](https://vuepress.vuejs.org/plugin/official/plugin-back-to-top.html) in the `config.js`.

Thanks, when i install vuepress locally in my project with yarn its success..
but not with npm.. i dont know why.. (i see in this docs, that to install on existing project using yarn instead)

but i think, i'm not add vuepress in existing project..

i just installed globally and then i think i dont have to install it locally again (cause i start from scratch)

thanks for your help, sorry that i perhaps miss reading the docs...
