### ISSUE TITLE
Refine getting started documentation

### ISSUE THREAD

**Issue by ludanxer** [vuejs/vuepress#2111]
## Feature request

The [Getting Started](https://vuepress.vuejs.org/guide/getting-started.html#getting-started) section does not contain the situation described in #2110 (Start from scratch, local install). And it doesn't mention nor provide a link about [Using a plugin](https://vuepress.vuejs.org/plugin/using-a-plugin.html) or [Using a theme](https://vuepress.vuejs.org/theme/using-a-theme.html).

Another related issue is #1801 , a tutorial that guides users to start from nothing to a website that uses most of the VuePress features would be very helpful?

#### What problem does this feature solve?

Make the documentation more user-friendly for beginners.

#### How should this be implemented in your opinion?

Rename `Inside an Existing Project` title, and add a section about starting from scratch with locally installed VuePress.

#### Are you willing to work on this yourself?

Yes

**Comment by kefranabg** [comment]
Thanks for the report @ludanxer. Feel free to open an PR if you're willing to on work on this 👍

**Comment by ludanxer** [comment]
Hi @kefranabg , Thanks for your reply! I have a question about the official way to quickly set up a VuePress site.

I know about the command `yarn create vuepress`, however, that package has not been updated for quite a while. Do you know if there is any plan to update it? Or a new CLI command `vuepress new docs` is expected?

**Comment by bencodezen** [comment]
@ludanxer We definitely plan on providing an official CLI for scaffolding VuePress projects for sure. We know that this is a major pain point as a new user.
