### ISSUE TITLE
Using the master version of VuePress

### ISSUE THREAD

**Issue by AntoineAugusti** [vuejs/vuepress#2113]
Hello there 👋 

I'm interested by the fix in #1951, but it hasn't come out yet. While waiting for the next release with this fix, **I'd like to use the `master` version of VuePress.**

I've tried pulling the master version in `package.json` with `"vuepress": "vuejs/vuepress#master",` but the `vuepress` CLI is unavailable after installation. Running `npm install github:vuejs/vuepress` gives an error as well.

**Comment by meteorlxy** [comment]
Vuepress repo is a monorepo, so it cannot be installed via github source.

> See cons of [monorepo design doc](https://github.com/babel/babel/blob/master/doc/design/monorepo.md)

BTW, please follow the issue template
