### ISSUE TITLE
Html Webpack Plugin is error

### ISSUE THREAD

**Issue by zhengxiaodong502** [vuejs/vuepress#2114]
TypeError: Cannot read property '0' of undefined
  
  - index.js:14 exports.normalizeHeadTag
    [myBlog]/[@vuepress]/core/lib/node/util/index.js:14:22
  
  - HeadPlugin.js:23 tags.forEach.tag
    [myBlog]/[@vuepress]/core/lib/node/webpack/HeadPlugin.js:23:28
  
  - Array.forEach
  
  - HeadPlugin.js:22 compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync
    [myBlog]/[@vuepress]/core/lib/node/webpack/HeadPlugin.js:22:21
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [myBlog]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 
    [myBlog]/[vuepress-html-webpack-plugin]/index.js:673:47
  
  - index.js:187 Promise.resolve.then.then.then.then.then.then.then.result
    [myBlog]/[vuepress-html-webpack-plugin]/index.js:187:18
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

**Comment by newsbielt703** [comment]
Please use issue template.
