### ISSUE TITLE
部署到github.io上样式不生效

### ISSUE THREAD

**Issue by s2265681** [vuejs/vuepress#2124]
![image](https://user-images.githubusercontent.com/41536679/72202322-ecc18400-3498-11ea-9b15-f406debf06af.png)

source里面显示html没有加载css文件，不知道哪里出了问题，本地dist文件里面的html也不能正常显示，vuepress dev . 本地运行是对的

**Comment by s2265681** [comment]
https://s2265681.github.io/

**Comment by ludanxer** [comment]
@s2265681 Please use the **issue template**, and **use English** so everyone can understand you. Thanks.

And there is no source code on your repo, so I don't know how to help you.

Please go through the document carefully, especially the [Github Pages](https://vuepress.vuejs.org/guide/deploy.html#github-pages) section. And make sure that you Set correct base in docs/.vuepress/config.js.

**Comment by pokitpeng** [comment]
> https://s2265681.github.io/

兄弟，你是怎么解决的，我也遇到了

**Comment by s2265681** [comment]
我最后也没找到解决方法。我怀疑版本问题 去github拉了别人的基础代码。比较了一下。除了版本没有区别。 后来实在找不到。用了github中一个代码基础上写的


| |
sjw
|
|
邮箱：s2265681@163.com
|

Signature is customized by Netease Mail Master

在2020年01月18日 11:52，pokitpeng 写道：

https://s2265681.github.io/

兄弟，你是怎么解决的，我也遇到了

**Comment by gg343917542** [comment]
我也遇到了，但我已经解决了，删除.vuepress目录下的templates目录就好了
