### ISSUE TITLE
Not generating page, it shows 404 page

### ISSUE THREAD

**Issue by Balmat** [vuejs/vuepress#2130]
- [ ] I confirm that this is an issue rather than a question.

#### Its only showing home page and other internal pages not showing
1. I have created three pages Home, Guides, Info 
2. Guides, Info page when redirect it shows 404 page

Here is the source code, please rename "vuepress" to ".vuepress"  folder
https://github.com/Balmat/vuepress-site

**Comment by kefranabg** [comment]
Your guides and infos folders should not be placed under .vuepress folder.
