### ISSUE TITLE
Prev / Next Links display abnormally and cannot be disabled

### ISSUE THREAD

**Issue by heiyehk** [vuejs/vuepress#2131]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
I don't know how this problem appeared.this is my github address.
[github address](https://github.com/heiyehk/githubio)

#### Versions
node:12.13.1
npm:6.12.1
vuepress: ^0.14.8-1.2.0
OS: Windows 10

#### What is expected?
I want stable Prev / Next Links.
#### What is actually happening?
Prev / Next Links are not displayed properly and cannot be disabled
#### Other relevant information
- When this problem appeared in v ^ 0.14.8, I recreated the global v1.2 project locally, and then copied the .md file of the v ^ 0.14.8 project into the new project, it still appeared.
- Prev / Next Links cannot also be disabled in YAML front matter and .vuepress / config.js.
![image](https://user-images.githubusercontent.com/33891067/72242224-da278600-3623-11ea-9ff9-0350a294b022.png)

![image](https://user-images.githubusercontent.com/33891067/72242161-ae0c0500-3623-11ea-8501-78a29aa22ca4.png)

**Comment by kefranabg** [comment]
Hi,

prevLinks & nextLinks are not available in `0.14.8`. Please try it with a new fresh project with an updated version of VuePress. If it does not work, please provide to the repos.

**Comment by heiyehk** [comment]
> 你好
> 
> prevLinks和nextLinks在中不可用`0.14.8`。请尝试使用VuePress更新版本的新项目。如果它不起作用，请提供给仓库。

Hello
the screenshot above is the latest version of `1.2`. All articles are copied from `0.14.8`

**Comment by heiyehk** [comment]
> 你好
> 
> prevLinks和nextLinks在中不可用`0.14.8`。请尝试使用VuePress更新版本的新项目。如果它不起作用，请提供给仓库。

![image](https://user-images.githubusercontent.com/33891067/72245262-19a5a080-362b-11ea-9bee-f4d5e13bd870.png)
