### ISSUE TITLE
Strictly followed the docs, but build failed

### ISSUE THREAD

**Issue by MagicGary** [vuejs/vuepress#2136]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Followed exactly the documentation here on deploying. But it failed for both Netfly and Heroku. 

https://github.com/MagicGary/DouglasCourses

https://v1.vuepress.vuejs.org/guide/deploy.html
https://v1.vuepress.vuejs.org/guide/deploy.html#netlify
https://v1.vuepress.vuejs.org/guide/deploy.html#heroku

#### What is expected?
Successfully deployment? 

#### What is actually happening?
On Netfly: 
``sh: 1: vuepress: not found``

On Heroku
Build successfully 
But ``2020-01-15T03:22:57.991031+00:00 app[web.1]: npm ERR! missing script: start``

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
``vuepress v1.2.0``

**Comment by ludanxer** [comment]
Hi @MagicGary , I notice your question on the [stackoverflow](https://stackoverflow.com/questions/59744648/vuepress-deployment-to-netfly-failed). As the answer said:
> you must install vuepress locally before deploying it to Netlify

And when you deploy it to Netlify, you won't need to set `base` in the `config.js`, check out the [document](https://vuepress.vuejs.org/config/#base) for more detail.

**Comment by MagicGary** [comment]
Hi @ludanxer 

Thanks for the reply. I did take out the ``base `` in my ``config.js``. I first pushed to heroku, built succeeded but still showed the wrong index page. 
I checked the Netlifty since it deployed automatically and that showed the correct index. 
Went back to heroku site 5 mins later and it showed correctly, guess it has a tiny bit delay, huh?
