### ISSUE TITLE
Cannot resolve `::: Vue` code block

### ISSUE THREAD

**Issue by jenkey2011** [vuejs/vuepress#2140]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce
In the. MD file, if you use `::: Vue` code block, it cannot be parsed correctly, just like `README.md` in this project

#### What is expected?
I hope `::: Vue` code block can be parsed correctly, just like the official documents

#### What is actually happening?
`::: Vue` code block  cannot be parsed correctly
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
none

**Comment by newsbielt703** [comment]
It's not a feature of VP or default theme.

You might want to check out [vuepress-plugin-container](https://vuepress.github.io/en/plugins/container/).

And here's how we configure the docs - [source](https://github.com/vuejs/vuepress/blob/master/packages/docs/docs/.vuepress/config.js#L80)

**Comment by jenkey2011** [comment]
Thanks @newsbielt703!  It works! 
I will close the issue, thanks again!
