### ISSUE TITLE
Please remove the words "TIP" and "WARNING" from custom containers

### ISSUE THREAD

**Issue by Maxhodges** [vuejs/vuepress#2141]
## Feature request
For the customer containers plugin, please don't insert the words "TIP" or "WARNING" into the container! 

#### What problem does this feature solve?
That makes the container much less flexible in how it could be used. I might want to use the yellow container to highlight something. But it always says "WARNING". Also, inserting these English words makes it much harder if I want to use VuePress to publish non-English content! Just leave the words out.

#### What does the proposed API look like?
same
#### How should this be implemented in your opinion?
remove lines which add "TIP" or "WARNING" to the custom containers

#### Are you willing to work on this yourself?
Yes!

**Comment by Maxhodges** [comment]
Ah I see you can do it like this

`<div class="warning custom-block"><p class="custom-block-title">IMPORTANT</p> <p>Make sure a custom component’s name either contains a hyphen or is in PascalCase. Otherwise it will be treated as an inline element and wrapped inside a <code>&lt;p&gt;</code> tag, which will lead to hydration mismatch because <code>&lt;p&gt;</code> does not allow block elements to be placed inside it.</p></div>`

does really seems to be documented.

**Comment by bencodezen** [comment]
Hey @Maxhodges. Is the concern that there is default titles for these custom containers? Or did you just want the ability to override it?

```
::: tip Suggestion
This is my suggestion
:::
```

Or are you saying you want to be able to use the styling with no title at all?

**Comment by Maxhodges** [comment]
Ideally, yes, I'd like to be able to supply my own title (in Japanese or French or example); or, use it with no title at all!

I didn't realize you could override like that! Great! My bad. I'll close this issue.

**Comment by bencodezen** [comment]
No worries at all. We should try to highlight that feature better in the docs. I'm going to reopen this issue so we address it.

**Comment by meteorlxy** [comment]
I think our docs has already "highlighted" this feature:

![image](https://user-images.githubusercontent.com/18205362/73607507-b7203e80-45f1-11ea-86d0-9de04211ea0e.png)

**Comment by bencodezen** [comment]
@meteorlxy Agreed, but I think the fact that it was missed means that it could be rewritten in a way that's more obvious. I'm going to experiment a bit with this to see what I can come up with.

**Comment by lalawow** [comment]
I just commit a PR to this issue. If this PR is good, I can make a PR for the chinese docs too.
