### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#2144]
I am curious that since this project is well introduced in Vue 3.0 's speech, why did vuepress only have one maintainer(@ulivz ) has right to publish it. He hasn't show up for three month, so that we have to bear the bugs by using the 1.2.0 which publish 3 months go.

You get thousands of stars, because we think it's a good project maintained by a professianl team, but now you really act as it's a personal project which belongs to @ulivz .

I am not angry that he is busy, but I am angry at you said you have a team in readme, while you cannot release a 1.2.1 version to publish the bug-fixes and features we gave you in the past three month. Think about it, please! I have no rights to blame the project quality, I have no right to force you fix the issue, but I think I have the rights to blame you left the community work behind and remain not to publish their work for features and bug fix.

Also I am disappointed for @yyx990803 , I don't think a project which is abandoned for 3 month while having known bugs fixed can be called as a good project.

P.S.: I asked several of your team member, I mailed @ulivz ,I commented him on twitter. I think I have done all I could. Sorry for throwing anger on all of you. But you shold know that you gave that anger to me.

**Comment by yyx990803** [comment]
Maintainers have priorities in life. I have currently focused on Vue 3, and @ulivz is probably busy with real life.

BTW, this is open source - here's the more constructive ways you could have handled this:

- You are free to fork and publish with your own fixes if you are in urgent need of the fix.
- You can offer to join the team and take up the maintenance responsibility.

The worst way possible is come here venting your "anger" and "disappointment" for something you get for free.

**Comment by ChristianKienle** [comment]
@yyx990803 Agreed. This is an open source project and every second someone works on any open source project is a second we should be thankful for.

You are probably correct: @ulivz seems to be busy with other things – which is totally fine. :) 

I am using VuePress myself for some of my side-projects and in general I am very happy with VuePress.

That all being said I would like to mention that your second point (offer to join the team) does not really work in practice. I offered @ulivz my resources after the VuePress team was founded and I saw not a lot of commits. Got no response. Which is totally fine. :)

@mister-hope: What do you think about forking VuePress and "simply" releasing it yourself for now? Maybe people will start to use your fork and contribute to *your* fork. Once this repository sees more attention again you could even create a PR which contributes everything back to VuePress...

**Comment by yyx990803** [comment]
To be clear, I will eventually allocate time to get VuePress maintenance back on track (and in case ulivz can no longer lead the maintenance, I will work on finding a new lead for VuePress), but it has to wait until work on Vue 3 is completed.

**Comment by Mister-Hope** [comment]
> To be clear, I will eventually allocate time to get VuePress maintenance back on track (and in case ulivz can no longer lead the maintenance, I will work on finding a new lead for VuePress), but it has to wait until work on Vue 3 is completed.

Thanks, after all it's not good that a team leader left this project behind while not gives his teammates the rights to publish the package. It' midnight in China(If you are in it now) Take a good rest.

**Comment by Mister-Hope** [comment]
> That all being said I would like to mention that your second point (offer to join the team) does not really work in practice. I offered @ulivz my resources after the VuePress team was founded and I saw not a lot of commits. Got no response. Which is totally fine. :)

Agree with that, often gets no response from ulivz and his team.

**Comment by meteorlxy** [comment]
We still have some active collaborators like @kefranabg @newsbielt703 @meteorlxy , and some active contributors like @ludanxer .

Things are still working, the problem is that we cannot publish version, and cannot make some major decisions.

For me I'm still willing to help maintain this project.

**Comment by Mister-Hope** [comment]
> We still have some active collaborators like @kefranabg @newsbielt703 @meteorlxy , and some active contributors like @ludanxer .
> 
> Things are still working, the problem is that we cannot publish version, and cannot make some major decisions.
> 
> For me I'm still willing to help maintain this project.

Yes, specially appreciate for you vuepress-types, which helped me moved my theme and plugins to typescript. I noticed a few of you are contributing day by day, especially you, working on the vupress comunity.

**Comment by meteorlxy** [comment]
@Mister-Hope I know you are an active developer, But being a problem solver is much better than being a grumbler.

And I hope you can understand we are all "full free time" open source developers. ulivz had spent lots of months on VuePress last year. Maintaining an open source project is not a easy work.

可以看看尤大前两天发的文章 https://zhuanlan.zhihu.com/p/103632957

**Comment by Mister-Hope** [comment]
But fork and publish a vuepress is not simple as you say. @yyx990803 

It's a monorepo. It's package are requiring others. That means I have to be extra carefully replacing any import files from _at_vuepress/core to _at_mr-hope/vuepress-core, and so is the theme-default package and the 2 markdown package Also, I have to fork a few repos from others which their PR have not been accepted, and merged them to master for respecting their work. I have to edit a few package.json then publish them to npm.

If vuepress contains only 1 package like vue, I would have done it month before. :cry:

**Comment by bencodezen** [comment]
Hey @Mister-Hope. Thank you for sharing your feedback with the team. Your frustrations are heard and understandable. To be honest, we have also been disappointed with our lack of progress and have been trying to figure out a better path moving forward. 

While it's completely understandable that it looks like a personal project for @ulivz, VuePress has always been an open-source project that is built for the community. Your point is well made that a core team was organized to maintain this project and thus should have a faster iteration process. However, while the intention to create a team was good, it has had its obstacles as many of us are new to maintaining a project of this size. As a result, progress has been slow at best due to the team getting ramped up on maintaining an open-source project. 

Nevertheless, I want you to know that we had our first team call this past week and want to reassure you and the rest of the community that we hear your frustrations and will be taking steps to making VuePress a product that the community loves and we are proud to maintain.

**Comment by kefranabg** [comment]
@Mister-Hope are you ok with these answers?

If so I'll close this issue.

**Comment by Mister-Hope** [comment]
Yes, of course, actually I just want the team make in contact with ulivz, gain the publish access and make the publish cycle shorter. That's all I want actually. And my anger is only to ulivz and a liitle to Mr yo since he really preached this project on the Vue Conf Shanghai.  I take fully understrand of your situation after @bencodezen intrroduce your team situation. 

But I am still curious about ulivz himself, it doesn't make sence that he stopped using Github, Twitter, and email for half a month right? **That really hurts**, because it means that he choose to ignore all request from publish a new version himself to give the access to you. It means that he choosed to abandon this project since his busy.

That makes me very **disappointed** at this leader.(not you and the others).

**Comment by Mister-Hope** [comment]
And since Mr. 尤 suggested me to publish my vuerpess, so I tried actually, but you see it's a monorepo, and I probably missed something when dealing the packages require or package.json when tring to publish it. So....

**Comment by ulivz** [comment]
Every time I see such comments, I seem to lose a little confidence in open source.

I have spent more than 1000 hours working on this project without concern for return. because I have to take care of my own work and life, leave for a while, and then I will be criticized and scolded?

In addition, I want to make a statement that before I leave for a short time, I have added NPM publishing permission for more than one core member, so please DO NOT use your prejudice to see the problem, and DO NOT make such ridiculous remarks as "a team leader left this project behind while not giving his teams matters the rights to publish the package".

If you really love open source and VuePress, then you will use your time to contribute more, rather than make these negative comments here.

**Comment by Mister-Hope** [comment]
1. The word "we don't have the right to publish package" came from on of vuepress team members's mouth, IT'S NOT MY IMAGINATION. I contacted three of the team members and than waited for a whole month before opening this issue.

2. I opened a dozen PR on vuepress while most of them are not being handled or reviewed.

3. This project really has little progress in the past six months.

**Comment by yyx990803** [comment]
@Mister-Hope as I said, fork it or leave it. You are not entitled to anything.
