### ISSUE TITLE
The navbar last item always exists

### ISSUE THREAD

**Issue by KongValley** [vuejs/vuepress#2150]
- [ ] I confirm that this is an issue rather than a question.

#### Version
vuepress@1.2.0

#### Steps to reproduce
![1](https://user-images.githubusercontent.com/30281453/73122992-bc640480-3fc5-11ea-8369-e65105e57158.gif)
In [VuePress Community](https://vuepress.github.io/en/), I repeat the problem
![2](https://user-images.githubusercontent.com/30281453/73123028-24b2e600-3fc6-11ea-9c96-a75ab238e6a8.gif)

#### What is expected?
I think the last item should be destroy
#### What is actually happening?
I don't know.
#### Other relevant information
Your OS: Win 10 1903
Node.js version: v11.10.0
Browser version: 75.0.3770.80
Is this a global or local install? local
Which package manager did you use for the install? yarn

**Comment by ludanxer** [comment]
Hi @KongValley , thanks for your report, this issue is fixed in #1952 . Please wait for the next release.
