### ISSUE TITLE
back-to-top plugin won't work in Safari 13

### ISSUE THREAD

**Issue by kid1412621** [vuejs/vuepress#2154]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. enable `back-to-top` plugin then run `vuepress dev docs`
2. browse in Safari 13

#### What is expected?

show back-to-top icon when scroll to bottom

#### What is actually happening?

nothing shows up

#### Other relevant information

```
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: 1.2.0
```

**Comment by ludanxer** [comment]
@kid1412621 Can you provide more details to reproduce the problem?  It seems to be fine on the official documentation site.

BTW, you may need to manually install the `back-to-top` plugin to make it work, check out more detail in the [documentation](https://vuepress.vuejs.org/plugin/#out-of-the-box).

**Comment by kid1412621** [comment]
> @kid1412621 Can you provide more details to reproduce the problem? It seems to be fine on the official documentation site.
> 
> BTW, you may need to manually install the `back-to-top` plugin to make it work, check out more detail in the [documentation](https://vuepress.vuejs.org/plugin/#out-of-the-box).

I've installed the plugin via npm.
And tried on Chrome, it's fine. But comes to Safari 13, it won't show up(even the official site).

**Comment by ludanxer** [comment]
Can you share your repo? Preferably a minimize one.

And you can also try to switch from npm to yarn as suggested in the documentation site:

> We currently recommend using Yarn instead of npm when installing VuePress into an existing project that has webpack 3.x as a dependency, because npm fails to generate the correct dependency tree in this case.

**Comment by kid1412621** [comment]
> Can you share your repo? Preferably a minimize one.
> 
> And you can also try to switch from npm to yarn as suggested in the documentation site:
> 
> > We currently recommend using Yarn instead of npm when installing VuePress into an existing project that has webpack 3.x as a dependency, because npm fails to generate the correct dependency tree in this case.

[try this](https://github.com/kid1412621/kid1412621.github.io), just about to start up.

I thought npm doesn't suck anymore nowadays. 😂

**Comment by ludanxer** [comment]
I use Yarn to install all my dependencies, and it works fine for me. You may want to check your Safari Preference.

```
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @vuepress/core:  1.2.0
    @vuepress/theme-default:  1.2.0
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

<img width="1275" alt="Screen Shot 2020-01-27 at 5 08 15 PM" src="https://user-images.githubusercontent.com/27280733/73162304-7d01f900-4128-11ea-93e0-8caada0a4540.png">

<img width="1275" alt="Screen Shot 2020-01-27 at 5 06 38 PM" src="https://user-images.githubusercontent.com/27280733/73162316-84290700-4128-11ea-98dd-0f9c27a78509.png">

**Comment by kid1412621** [comment]
sorry! my bad, turns out it's a safari plugin I've installed to block ads.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/26278054/73163607-51344280-412b-11ea-9557-c98adf4f4fb3.png">

**Comment by kid1412621** [comment]
@ludanxer btw, is there possible to support mobile site?

**Comment by ludanxer** [comment]
I'm not sure, but I think it would be great.

You can create a feature request in another issue.
