### ISSUE TITLE
details custom container is not working

### ISSUE THREAD

**Issue by aliartiza75** [vuejs/vuepress#2159]
## Bug report
details custom container is not working

#### Steps to reproduce

I have added a container in my project with the following details but it is not working

```markdown
::: details Click me to view the code
    ```js
    console.log('Hello, VuePress!')
    ```
:::
```

It prints the container in raw format.

#### What is expected?
It should not print the data in raw format.

#### What is actually happening?
It is printing the data in raw format.

**Comment by newsbielt703** [comment]
Because the feature has't been released, we should have add a version badge in the documentation.

No worries, the next minor version will be released very soon.

**Comment by aliartiza75** [comment]
@newsbielt703 thank you

**Comment by wanmaoor** [comment]
> Because the feature has't been released, we should have add a version badge in the documentation.
> 
> No worries, the next minor version will be released very soon.

When the new version will release? just curious about that, I thought this a good feature.

**Comment by ludanxer** [comment]
It's already been released. In vuepress 1.3.0, checkout https://github.com/vuejs/vuepress/releases

**Comment by wanmaoor** [comment]
> It's already been released. In vuepress 1.3.0, checkout https://github.com/vuejs/vuepress/releases

thanks.

**Comment by aliartiza75** [comment]
@ludanxer thank you :+1:
