### ISSUE TITLE
[Feature request] add toLocaleString options for @vuepress/plugin-last-updated

### ISSUE THREAD

**Issue by YunYouJun** [vuejs/vuepress#2168]
## Feature request

add options config for @vuepress/plugin-last-updated

#### What problem does this feature solve?

In @vuepress/plugin-last-updated, [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) is the default transformer.
`toLocaleString` has some options, so sometimes we don't need use custom [transformer](https://vuepress.vuejs.org/plugin/official/plugin-last-updated.html#options) here.

Example: We just need pass `{ hour12: false }` to get 24-hour.

#### What does the proposed API look like?

```js
module.exports = {
  plugins: [
    [
      '@vuepress/last-updated',
      {
        options: {
          // more options
          // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
          hour12: false
        }
      }
    ]
  ]
}
```

#### How should this be implemented in your opinion?

Add `options` param for [defaultTransformer](https://github.com/vuejs/vuepress/blob/ca3679c3eb2b0406bcc7c3224fc54c6a48a48f9a/packages/%40vuepress/plugin-last-updated/index.js#L18).

#### Are you willing to work on this yourself?

Yes.

**Comment by mishengqiang** [comment]
#2192 这个特性可能导致一些第三主题出现Invalid Date的错误，比如[vuepress-theme-ououe](https://github.com/tolking/vuepress-theme-ououe)主题。

相关的[中文文档](https://vuepress.vuejs.org/zh/plugin/official/plugin-last-updated.html#%E9%80%89%E9%A1%B9)及时跟进，现在默认值还是`undefined`。

**Comment by kefranabg** [comment]
Has been fixed in https://github.com/vuejs/vuepress/commit/369c31520b48131d1c8dcff6dcc95f2699ed68bb . Will be in the next release
