### ISSUE TITLE
Report base URL in analytics plugin

### ISSUE THREAD

**Issue by ghana04** [vuejs/vuepress#2169]
- [x ] I confirm that this is an issue rather than a question.

## Bug report

When using Google Analytics plugin, the base Url configured in the config.js file is not returned by the plugin.

It seems that a fix for this was introduced in v0.14.4 which is not carried over to version 1.x.x. --> [fix](https://github.com/vuejs/vuepress/commit/559888bbb1119a3123feb87f928803fd76d41e72) | [current 0.x file](https://github.com/vuejs/vuepress/blob/0f2c9f0f30542c2e0c470ad1fba0e742751961f1/lib/app/clientEntry.js#L33).

Compare that to the current file in 1.x: [enhanceAppFile.js](https://github.com/vuejs/vuepress/blob/ca3679c3eb2b0406bcc7c3224fc54c6a48a48f9a/packages/%40vuepress/plugin-google-analytics/enhanceAppFile.js#L23)

It seems that the only change required might be the following:

```js
ga('set', 'page', to.fullPath) \\ current
ga('set', 'page', app.$withBase(to.fullPath)) \\ possible fix
```

#### Steps to reproduce

Implement GA plugin in your project with a `config.base` value configured.

#### What is expected?

The base URL is returned by the plugin.

#### What is actually happening?

The base URL is only returned when accessing pages from outside the VuePress site but not when navigating between pages on the VuePress site itself.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by newsbielt703** [comment]
Nice catch!

**Comment by rneto** [comment]
In have implemented in the #2474 pull request the @ghana04 solution proposal.

**Comment by mkfsn** [comment]
Is there any workaround before this is merged/released?

**Comment by vittominacori** [comment]
@ulivz any chance to check if #2687 solves and can be merged.

All of my projects with base path are sending wrong analytics data.
