### ISSUE TITLE
@vuepress/pwa 无法弹出 updatePopup

### ISSUE THREAD

**Issue by nuochong** [vuejs/vuepress#2172]
在更新Chrome浏览器后打包上线后无法显示更新对话框 updatePopup

·sw-updated· 无法被触发

VuePress官网也存在该情况

有关参数
···
chrome浏览器版本 80.0.3987.87（正式版本） （64 位）
"@vuepress/plugin-pwa": "^1.2.0",
"vuepress": "^1.2.0",
···

**Comment by ludanxer** [comment]
@nuochong Thanks for the report.
Please use English next time so everyone could understand and help you.

---

Translation:

@vuepress/plugin-pwa stop showing popup after updating Chrome

`sw-updated` can't be triggered

This is also happening on VuePress official document site.

Relevant information

```
Chrome 80.0.3987.87 (64-bit)
"@vuepress/plugin-pwa": "^1.2.0",
"vuepress": "^1.2.0",
```

**Comment by kefranabg** [comment]
If you've updated Chrome, you've probably reloaded your VuePress website and get the latest version, this is why the popup does not show up anymore. Feel free to comment you think something is uncorrect. Thanks @ludanxer for the translation 👍

**Comment by wwavelet** [comment]
> 在更新Chrome浏览器后打包上线后无法显示更新对话框 updatePopup
> 
> ·sw-updated· 无法被触发
> 
> VuePress官网也存在该情况
> 
> 有关参数
> ···
> chrome浏览器版本 80.0.3987.87（正式版本） （64 位）
> "@vuepress/plugin-pwa": "^1.2.0",
> "vuepress": "^1.2.0",
> ···

I also can't see the refresh button popup when I set {updatePopup:true}, but sw-updated works to me，as the [docs](https://www.vuepress.cn/zh/plugin/official/plugin-pwa.html#vuepress-plugin-pwa) say, you must close all the client, webpage tabs and installed application window then open the page again and you will see the updated content.

**Comment by lhj233** [comment]
I also can't see the refresh button popup when I set {updatePopup:true}

**Comment by wuyuehui** [comment]
I can't see the popup either,but the browser console prompt me Content was updated.
Unless I force the browser cache to clear, new content will appear.

**Comment by lhj233** [comment]
> I can't see the popup either,but the browser console prompt me Content was updated.
> Unless I force the browser cache to clear, new content will appear.

we got the same question

**Comment by kefranabg** [comment]
Indeed.

The bug was introduced by this commit https://github.com/vuejs/vuepress/commit/6f9e478

@meteorlxy could you take a look?

**Comment by meteorlxy** [comment]
Sure

**Comment by meteorlxy** [comment]
Figured out the reason.

The default options are set in `ready()` hook, which will have no effect in `globalUIComponents` option.

Fix and make further refactor in #2187

**Comment by meteorlxy** [comment]
For someone want a workaround: set `popupComponent: 'SWUpdatePopup'` option to make the popup component work in current version.

**Comment by kefranabg** [comment]
Awesome, thanks @meteorlxy 👍

**Comment by kefranabg** [comment]
Will be in the next minor release
