### ISSUE TITLE
Vuepress Public Folder Host

### ISSUE THREAD

**Issue by mgnfcnt** [vuejs/vuepress#2173]
I have an existing vuejs application and I want to add vuepress support to create documentation. So I have added it as in documentation.
To server output documents under site I just changed output directory as 

```
module.exports = {
    dest: './public/documentation' // desired path to VuePress output
}
```
Everything is Ok untill now:

```
wait Rendering static HTML...
success Generated static files in public\documentation.
```

But when I  go to http://localhost:8080/documentation/index.html , web server can't find css and js files:

```
Refused to apply style from 'http://localhost:8080/assets/css/0.styles.d4856bb8.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
7index.html:11 GET http://localhost:8080/assets/js/app.859a9a8e.js net::ERR_ABORTED 500 (Internal Server Error)
```

I have changed base directory as:

` base: './',`

It gives below error:
```

404
There's nothing here.
Take me home.
```
When I click 'Take me home' it is redirecting to  http://localhost:8080/ 
I can see documents.

I also tried 

`base: './documentation/',`

and

`base: 'http://localhost:8080/documentation/',`

this is redirecting : http://localhost:8080/http:/localhost:8080/documentation/ when click take me home

**Comment by ludanxer** [comment]
Try to change `base` according to the [documentation](https://vuepress.vuejs.org/config/#base).

> If you plan to deploy your site to https://foo.github.io/bar/, then you should set base to "/bar/". **It should always start and end with a slash**.

From your description, I think the correct `base` would be `'/documentation/'`

**Comment by mgnfcnt** [comment]
'/documentation/' is working thanks
