### ISSUE TITLE
[Bug report] markdown-it plugin cant load by using `config.markdown.plugins` config.

### ISSUE THREAD

**Issue by yibhou** [vuejs/vuepress#2175]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?

Using config below can correctly load markdown-it plugin like the [doc](https://vuepress.vuejs.org/config/#markdown-plugins).
```js
module.exports = {
  markdown: {
    plugins: [
      'markdown-it-sub'
      // or
      ['markdown-it-xxx', { /* options */ }]
    ]
  }
}
```
Actually it cant load any markdown-it plugins. But loading correctly in using `markdown.extendMarkdown` like:
```js
markdown: {
    extendMarkdown: md => {
      md.use(require('markdown-it-sub'))
    }
  }

```

#### What is actually happening?

Actually cant load any markdown-it plugins

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Binaries:
    Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
    Yarn: 1.22.0 - ~/Documents/Projects/oh-my-test/src/blog/node_modules/.bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.2/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 71.0
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.3.0 
    @vuepress/theme-default:  1.3.0 
    vuepress: ^1.3.0 => 1.3.0 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by kefranabg** [comment]
Please provide a reproduction repository so we can help you.

**Comment by yibhou** [comment]
Hi, @kefranabg. This is a [reproduction repository](https://github.com/yibhou/vuepress-reproduction).

**Comment by kefranabg** [comment]
`extendMarkdown` should be placed at the root of the config object. Not under `markdown`.

**Comment by yibhou** [comment]
See the [document](https://vuepress.vuejs.org/config/#markdown-extendmarkdown), that is under `markdown`. And its actually correct.

**Comment by kefranabg** [comment]
`markdown.plugins` looks deprecated. Can't find any reference to it in the VuePress code. We'll investigate. Thanks for the report !

**Comment by meteorlxy** [comment]
> `markdown.plugins` looks deprecated. Can't find any reference to it in the VuePress code. We'll investigate. Thanks for the report !

It's not deprecated. All the logic is placed in the `@vuepress/markdown` package.

**Comment by meteorlxy** [comment]
Confirmed. A bug of module resolver

**Comment by meteorlxy** [comment]
Ref #2286
