### ISSUE TITLE
Navigating to Static Files

### ISSUE THREAD

**Issue by mgnfcnt** [vuejs/vuepress#2176]
I have a static folder as Java Documentation generated with using Dokka at my services project. I am putting these outputs under following folder:

`docs\.vuepress\public\api\-my-service`

Then running npm command:

`npm run docs:build`

Everything works well untill now, and it is putting all documents into necessary place:

`public\documentation\api\-my-service`

I want to navigate user to this folder:

```
...
    base: '/documentation/',
    dest: './public/documentation',
...
        nav: [
            {
                text: 'Api Docs',
                ariaLabel: 'Service Api Documentation',
                items: [
                    { text: 'My Service', link: '/api/-my-service/index.html' }
                ]
            },
...
```

When I click my service menu it is being redirected to 404 page,

But when I directly enter frol url bar:

http://localhost:8080/documentation/api/-my-service/index.html

I can see the contents as desired

**Comment by rookieHcy** [comment]
+1

**Comment by ludanxer** [comment]
Hi @mgnfcnt @rookieHcy   Can you try to rename the `public` folder to something else and give it a go again? Because the `.vuepress/public` is used for [ static assets](https://vuepress.vuejs.org/guide/assets.html#public-files) in VuePress.

And if the problem is still there, can you help provide a minimal repo that reproduces the problem? Thanks.

**Comment by mgnfcnt** [comment]
Hello @ludanxer  First I tried with docs/.vuepress/api/my-service and docs/api/my-service folders. In this way vuepress does not create a folder under public/documentation

**Comment by kefranabg** [comment]
@mgnfcnt your link path is wrong, use this instead:

```
 items: [
   { text: 'My Service', link: '/api/-my-service/' }
]
```
