### ISSUE TITLE
vue.esm.js:4458 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method. TypeError: Cannot read property '$scopedSlots' of undefined

### ISSUE THREAD

**Issue by binnymaster** [vuejs/vuepress#2184]
I'm getting this error in my qa and Prod environment. This error is only seen in mobile not in desktop mode.
![Screen Shot 2020-02-13 at 2 52 15 PM](https://user-images.githubusercontent.com/14200541/74567933-e36a8200-4f44-11ea-915f-894ad28e51a5.png)

It would be create if someone is able to help me out.

**Comment by meteorlxy** [comment]
Please follow the template and provide more context
