### ISSUE TITLE
Errors in console about deeply nested sidebar

### ISSUE THREAD

**Issue by KieranHunt** [vuejs/vuepress#2190]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Have sidebar that is nested more than 3 items deep.

#### What is expected?

No errors in the console output.

#### What is actually happening?

Errors on first page load and on navigating between pages.

#### Other relevant information

Found the line here: https://github.com/vuejs/vuepress/blob/ca3679c3eb2b0406bcc7c3224fc54c6a48a48f9a/packages/%40vuepress/theme-default/util/index.js#L225-L229

Reading through that code, it seems that VuePress doesn't really have an issue with nesting deeper than three. It just errors into the console and then continues.

Is there some context that I'm missing? I see that the change happened here: https://github.com/vuejs/vuepress/commit/01dd45bc59e4117aafadbe3b3d91234fcee0b337
But 3 seems pretty arbitrary.

Actual error message:

```
07:58:13.598 [vuepress] detected a too deep nested sidebar group. 2 2.258cb917.js:1:3364
```

**Comment by KieranHunt** [comment]
Created a pull request for this here: https://github.com/vuejs/vuepress/pull/2191

**Comment by Mister-Hope** [comment]
It's designed by @ulivz , which warns people that his sidebar are to deep.

Just it, A too deep nested sidebar may have a bad apprence while rendering.

**Comment by KieranHunt** [comment]
PR was merged
