### ISSUE TITLE
Open index.html always location to 404 after build?

### ISSUE THREAD

**Issue by Rain120** [vuejs/vuepress#2197]
## Question Description

Location is ok, but open location build file index.html is 404

**Location**
![image](https://user-images.githubusercontent.com/20939839/75041224-1be6fe80-54f7-11ea-8239-6f37eca26bd3.png)

**line**
![image](https://user-images.githubusercontent.com/20939839/75041177-0671d480-54f7-11ea-977a-3d65664f03c8.png)

## Link

[Demo](https://rain120.github.io/vuepress-plugin-awesome-gitalk/dist/index.html)

[Config.js](https://github.com/Rain120/vuepress-plugin-awesome-gitalk/blob/master/example/.vuepress/config.js)

**Comment by ludanxer** [comment]
Check the document site about how to set [base](https://vuepress.vuejs.org/config/#base) correctly when [deploying to GitHub pages](https://vuepress.vuejs.org/guide/deploy.html#github-pages).

**Comment by Rain120** [comment]
@ludanxer It did not work, I had to try it

**Comment by ludanxer** [comment]
In your case, try `/vuepress-plugin-awesome-gitalk/dist/` or `/vuepress-plugin-awesome-gitalk/`.

**Comment by Rain120** [comment]
@ludanxer Both did not work

- [/vuepress-plugin-awesome-gitalk/ commit](https://github.com/Rain120/vuepress-plugin-awesome-gitalk/commit/698de05e74bf167d45a9c7999df970b7a1e0a383)

- [/vuepress-plugin-awesome-gitalk/dist/ commit](https://github.com/Rain120/vuepress-plugin-awesome-gitalk/commit/6f674a73e48a087f8448efbf0e0c28877ce5bb55)

**Comment by ludanxer** [comment]
`/vuepress-plugin-awesome-gitalk/dist/` is working in my case, check out my [fork](https://github.com/ludanxer/vuepress-plugin-awesome-gitalk) and [deploy](https://ludanxer.github.io/vuepress-plugin-awesome-gitalk/dist/index.html).

Close this issue if your problem is solved.

**Comment by Rain120** [comment]
@ludanxer It's work, thx
