### ISSUE TITLE
Automatic Reload?

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#220]
You can have an automatic reload to be on the development server, for every change I have to reload the page manually

**Comment by ycmjason** [comment]
How are you starting the server? New content should reflect on the dev site.

**Comment by yyx990803** [comment]
You definitely have something messed up with your installation... everything hot reloads on the dev server.

**Comment by luisDanielRoviraContreras** [comment]
To raise the development server I run `vuepress dev`

**Comment by yyx990803** [comment]
Either way please open a proper report with your exact environment, versions, directory setup etc.

**Comment by beetaa** [comment]
@yyx990803 @ycmjason After checking the source code of vuepress under `node_modules`, I found something maybe related in file `lib\dev.js`:

![2019-01-14_183130](https://user-images.githubusercontent.com/5688224/51107828-0353e180-182b-11e9-8163-d174d87286e8.png)

**Comment by beetaa** [comment]
Finally, the problem solved by following #123 , just set `host: localhost` in `.vuepress/config.js` and restart the dev server.
