### ISSUE TITLE
Importing SCSS mixins fail

### ISSUE THREAD

**Issue by henrikdahl** [vuejs/vuepress#2203]
I've created a component library and documented it using `VuePress`. Things worked smoothly until I wanted to also use the docs for debugging components. Instead of loading the built library, I'm importing the an index file that includes components and everything else. It works besides the fact that it fails on SCSS mixins. It appears it never loads the mixin at all.

In my `vue.config.js` I do:

```
loaderOptions: {
            scss: {
                prependData: `
                    @import "@/assets/scss/settings/_breakpoints.scss";
                    @import "@/assets/scss/settings/_layout.scss";
                    @import "@/assets/scss/settings/_typography.scss";
                    @import "@/assets/scss/utility/_functions.scss";
                    @import "@/assets/scss/utility/_mixins.scss";
                `
            }
        },
```

It's suggested that you can do the same in `config.js` inside `.vuepress`. However I don't want to duplicate the files and would like to reference the existing files that are already mentioned in the `vue.config.js`.

Any suggestions?

Doesn't seem to matter what I write within the `sass: {}`. It doesn't even throw an error at me for refereeing a file that doesn't exist.

Not sure how to proceed from here.

**Comment by henrikdahl** [comment]
Seems the fix was to have the `@` webpack alias before the sass data in the config.

**Comment by fredericpfisterer** [comment]
Can I see your config.js because I'n trying to achieve the same by importing globally include-media in my VuePress project but no luck so far.

Cheers

**Comment by henrikdahl** [comment]
@fredericpfisterer 

```
configureWebpack: {
        resolve: {
            alias: {
                '@': resolve(__dirname, '../../src')
            }
        }
    },
    scss: {
        prependData: `
            @import "@/assets/scss/settings/_breakpoints.scss";
            @import "@/assets/scss/settings/_layout.scss";
            @import "@/assets/scss/settings/_typography.scss";
            @import "@/assets/scss/utility/_functions.scss";
            @import "@/assets/scss/utility/_mixins.scss";
        `
    }
```

**Comment by JackieZhang-Coding** [comment]
> @fredericpfisterer
> 
> ```
> configureWebpack: {
>         resolve: {
>             alias: {
>                 '@': resolve(__dirname, '../../src')
>             }
>         }
>     },
>     scss: {
>         prependData: `
>             @import "@/assets/scss/settings/_breakpoints.scss";
>             @import "@/assets/scss/settings/_layout.scss";
>             @import "@/assets/scss/settings/_typography.scss";
>             @import "@/assets/scss/utility/_functions.scss";
>             @import "@/assets/scss/utility/_mixins.scss";
>         `
>     }
> ```
Why it doesn't work?
