### ISSUE TITLE
Why does VuePress configure externals failed?

### ISSUE THREAD

**Issue by zpfz** [vuejs/vuepress#2206]
- [x] I confirm that this is an issue rather than a question.

## Bug report
My project uses Antd of Vue components, and configures the following code in enhanceApp.js:
```js
import Antd from 'ant-design-vue';
export default ({
  Vue,
  options,
  router,
  siteData,
}) => {
  Vue.use(Antd)
}
```
Configure the following code under .vuepress / config.js:
```js
configureWebpack: {
 externals: {
  'ant-design-vue': 'Antd'
 }
}
```
The console then prompts the following message:
Cannot read property 'use' of undefined
Antd is not undefined
So I want to konw how to use externals correctly？（thank you for your reply first）
#### Steps to reproduce
1.Install dependencies Antd of Vue

npm i --save ant-design-vue

2.Add code snippet
// .vuepress/config.js
```js
configureWebpack: {
 externals: {
  'ant-design-vue': 'Antd'
 }
}
```

// .vuepress/enhanceApp.js
```js
import Antd from 'ant-design-vue';
export default ({
  Vue,
  options,
  router,
  siteData,
}) => {
  Vue.use(Antd)
}
```

// .vuepress/templates/dev.html
```
<script src="https://lib.baomitu.com/moment.js/2.24.0/moment.min.js" crossorigin="anonymous" type="text/javascript"></script>
<script src="https://unpkg.com/ant-design-vue@1.4.11/dist/antd.min.js" crossorigin="anonymous" type="text/javascript"></script>
```

#### What is expected?
Normal use of externals

#### What is actually happening?
The console then prompts the following message:
Cannot read property 'use' of undefined
Antd is not undefined

**Comment by meteorlxy** [comment]
`enhanceApp` will be called in [both server and client](https://vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements). 

```js
export default ({
  Vue,
  isServer // is this enhancement applied in server-rendering or client
}) => {
  if (!isServer ) {
    Vue.use(xxx)
  }
}
```

**Comment by zpfz** [comment]
Thanks~
