### ISSUE TITLE
Plugins don't register when running on a docker image

### ISSUE THREAD

**Issue by skafendre** [vuejs/vuepress#2207]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I encountered an issue when I tried to hook my repo with ci tools.
Registering plugins via Vue.use() does not seem to work on a docker image, as both vuepress dev and vuepress build will not register it.
The issue does not appear in my local dev environnement though.
I am writing a custom theme.

#### Steps to reproduce

I import buefy with the following code in EnhanceApp.js : 
```
import Buefy from 'buefy'
import 'buefy/dist/buefy.css'

export default ({
    Vue,
    options,
    router,
    siteData
}) => {
    Vue.use(Buefy)
}
```

I made a minimal repo to reproduce the issue, consisting of a newly generated vuepress project with buefy and a docker image.
https://github.com/skafendre/vuepress-docker-buefy-issue

#### What is expected?

Vuepress dev or vuepress build register and use the plugins when rendering files.

#### What is actually happening?

Plugins are not registered.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project (local dev environnement which work properly):
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found

- Output of `npx vuepress info` in the docker image :
 System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found

**Comment by meteorlxy** [comment]
EnhanceApp.js => enhanceApp.js
