### ISSUE TITLE
Automatic Reload not working?

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#221]
You can have an automatic reload to be on the development server, for every change I have to reload the page manually

> So you can compile the directory directly in  `C: \ vuepress-dev`

The command vuepress dev already works but when I make some change in the README.md it does not update automatically

- Your OS: **Window**
- Node.js version: **v8.4.0**
- VuePress version: **v0.7.0**
- Browser version: **Google Chrome Versión 65.0.3325.181 (Build oficial) (64 bits)**
- Is this a global or local install?: **Global**
- Which package manager did you use for the install?: **NPM**

**Comment by ulivz** [comment]
Can you open the console and see whether there is some error? such as `WebSocket connection to 'ws://0.0.0.0:8081/' failed`?

**Comment by yyx990803** [comment]
Also try `vuepress dev --host localhost`

**Comment by luisDanielRoviraContreras** [comment]
This is what it shows me when executing and what's below when making the changes but it does not automatically recharge anyway
   
     $ vuepress dev
     Extracting site metadata...[11:48:27] Compiling Client
     [11:48:30] Compiled Client in 3s

     VuePress dev server listening at http://localhost:8080/

     [11:49:09] Compiling Client
     [11:49:10] Compiled Client in 246ms
     [11:49:10] ✔ successfully compiled.
     [11:49:21] Compiling Client
     [11:49:22] Compiled Client in 204ms
     [11:49:22] ✔ successfully compiled.
     [11:49:22] Compiling Client
     [11:49:22] Compiled Client in 157ms
     [11:49:22] ✔ successfully compiled.
     [11:58:39] Compiling Client
     [11:58:39] Compiled Client in 203ms
     [11:58:39] ✔ successfully compiled.
     [11:58:39] Compiling Client
     [11:58:40] Compiled Client in 204ms
     [11:58:40] ✔ successfully compiled.
     [11:59:02] Compiling Client
     [11:59:02] Compiled Client in 174ms
     [11:59:02] ✔ successfully compiled.
     [11:59:02] Compiling Client
     [11:59:02] Compiled Client in 168ms
     [11:59:02] ✔ successfully compiled.
     [11:59:31] Compiling Client
     [11:59:31] Compiled Client in 218ms
     [11:59:31] ✔ successfully compiled.
     [11:59:31] Compiling Client
     [11:59:32] Compiled Client in 152ms
     [11:59:32] ✔ successfully compiled.
     [12:03:39] Compiling Client
     [12:03:40] Compiled Client in 192ms
     [12:03:40] ✔ successfully compiled.

**Comment by ulivz** [comment]
Have you tried `vuepress dev --host localhost` as Even said?

**Comment by ulivz** [comment]
Looked same to #123

**Comment by luisDanielRoviraContreras** [comment]
@yyx990803 Ready already worked when running vuepress dev --host localhost thank you very much and apologize for the inconvenience because running it that way if it works what is the difference

**Comment by yyx990803** [comment]
Looks like `wepback-serve` doesn't like `0.0.0.0` on Windows. We might need to default to `localhost` on Windows.

**Comment by CesarGA** [comment]
If you are on Windows, but you are running VuePress on a Linux Docker container, this problem still exists because process.platform is still 'linux'.

I think [this](https://github.com/webpack-contrib/webpack-serve/issues/56#issuecomment-377912611) would be a better solution.

**Comment by incrypt0** [comment]
I am having this issue. Vuepress does not hot reload when I make changes. I used yarn to install vuepress and also tries vupress dev --host localhost. But it did'nt help

**Comment by sabicalija** [comment]
> I am having this issue. Vuepress does not hot reload when I make changes. I used yarn to install vuepress and also tries vupress dev --host localhost. But it did'nt help

I fixed it by configuring what should be the default in `.vuepress/config.js` (cf. [`extraWatchFiles`](https://vuepress.vuejs.org/config/#extrawatchfiles)).

```js
module.exports = {
   ...,
   extraWatchFiles: ["**/*.md", "**/*.vue"],
   ...
}
```

**Comment by dcodeIO** [comment]
Same problem for me. With the `extraWatchFiles` above, the server does some building upon changing an `.md` file, but it doesn't update in the browser. Reloading the page also doesn't help and I have to restart the `vuepress dev` process. v1.5.0

**Comment by incrypt0** [comment]
I think this issue needs to be reopened
Is this a bug in Vue Press or is it in webpack?
Because when I look in the console I see an error message saying WDS disconnected.

**Comment by sabicalija** [comment]
I managed to get it working by reusing an older lockfile. Hope it helps.

**Comment by sktzofrenic** [comment]
I'm experiencing this issue as well.

**Comment by venimus** [comment]
Similar regression for me when updated from `1.4.1` to `1.5.0`

**Comment by acmoles** [comment]
I'm facing this issue after updating from `1.4.1` to `1.5.0`, but on MacOS

**Comment by fmonper1** [comment]
Can confirm hot reloading doesn't work after updating from 1.4.x to 1.5. It doens't work after rolling back either

**Comment by faroit** [comment]
does work here as well (OSX)

**Comment by thomrad** [comment]
same problem. (Windows 10) node, npm, yarn, vuepress fresh installs.

**Comment by ansky-pro** [comment]
I got it working by downgrading dependency `watchpack` to 1.6.1
Added resolutions section to package.json and ran yarn install

  "resolutions": {
    "watchpack": "1.6.1"
  }

Hope this helps to anyone struggling with the same problem
#2392

**Comment by incrypt0** [comment]
> I got it working by downgrading dependency `watchpack` to 1.6.1
> Added `resolutions` section to `package.json` and ran `yarn install`
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Hope this helps to anyone struggling with the same problem
> #2392

@ansky-pro  so is it an issue with webpack or vuepress its a bug right?
@yyx990803  whould this issue be reopened?

**Comment by paulvanbladel** [comment]
What worked, as a workaround, for me is adding additional nodemon script  in package.json
```
"start": "nodemon --ext md,vue --watch .vuepress --watch . --exec vuepress dev docs --host localhost"
´´´
First install nodemon globally (npm install -g nodemon).
Afterwards you can do: npm run start.

**Comment by tcrapts** [comment]
> I got it working by downgrading dependency `watchpack` to 1.6.1
> Added `resolutions` section to `package.json` and ran `yarn install`
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Hope this helps to anyone struggling with the same problem
> #2392

This works! For clarity, if you use npm, you must also [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions).

To summarize and clarify, you need to add two things to package.json.
```
"scripts": {
  "preinstall": "npx npm-force-resolutions"
}
```
and
```
  "resolutions": {
    "watchpack": "1.6.1"
  }
```
Followed by `npm install`.

Result: after updating a *.md file, you don't need to hit refresh in the browser or restart Vuepress to see the changes.

**Comment by sktzofrenic** [comment]
> > I got it working by downgrading dependency `watchpack` to 1.6.1
> > Added `resolutions` section to `package.json` and ran `yarn install`
> > ```
> >   "resolutions": {
> >     "watchpack": "1.6.1"
> >   }
> > ```
> > 
> > 
> > Hope this helps to anyone struggling with the same problem
> > #2392
> 
> This works! For clarity, if you use npm, you must also [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions).
> 
> To summarize and clarify, you need to add two things to package.json if you use npm.
> 
> ```
> "scripts": {
>   "preinstall": "npx npm-force-resolutions"
> }
> ```
> 
> and
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Followed by `npm install`.
> 
> Result: after updating a *.md file, you don't need to hit refresh in the browser or restart Vuepress to see the changes.

I attempted this, but it did not work in my case unfortunately.

**Comment by kevinpainchaud** [comment]
> > I got it working by downgrading dependency `watchpack` to 1.6.1
> > Added `resolutions` section to `package.json` and ran `yarn install`
> > ```
> >   "resolutions": {
> >     "watchpack": "1.6.1"
> >   }
> > ```
> > 
> > 
> > Hope this helps to anyone struggling with the same problem
> > #2392
> 
> This works! For clarity, if you use npm, you must also [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions).
> 
> To summarize and clarify, you need to add two things to package.json if you use npm.
> 
> ```
> "scripts": {
>   "preinstall": "npx npm-force-resolutions"
> }
> ```
> 
> and
> 
> ```
>   "resolutions": {
>     "watchpack": "1.6.1"
>   }
> ```
> 
> Followed by `npm install`.
> 
> Result: after updating a *.md file, you don't need to hit refresh in the browser or restart Vuepress to see the changes.

Works for me! Thx! 🎉

**Comment by ClintOxx** [comment]
Having this issue and the suggestions haven't fixed it for me, unfortunately. Didn't realize how annoying the lack of hot reload could be
