### ISSUE TITLE
关于主题开发的基础问题

### ISSUE THREAD

**Issue by jsliu-null** [vuejs/vuepress#2213]
你好，
我想自己开发一个主题，一直不知道怎么下手，
自己比较菜，文档看不太懂，
希望能有一个大牛帮助一下
如果可以希望能微信沟通一下
微信：13283394579
打扰了
  祝好

**Comment by ludanxer** [comment]
Hi @jsliu-null , I know that VuePress documentation may not be perfect, but there are also many useful resources on the [internet](https://www.google.com/search?q=how+to+develop+a+vuepress+theme), I believe they can at least get you started. And there is a list of [VuePress Themes](https://github.com/vuepressjs/awesome-vuepress#themes) for your reference.

And if you encounter some specific problems while developing a theme, I suggest you try to find the answers at [stackoverflow](https://stackoverflow.com/questions/tagged/vuepress) first.

However, if things still not going well for you, you can come back here and post an [issue](https://github.com/vuejs/vuepress/issues/new/choose) with details for your problem.

Also, please use English next time so everyone could understand and help you. Thanks!

**Comment by zpj80231** [comment]
Hi @jsliu-null, You can refer to my blog: [https://zpj80231.github.io/znote/](https://zpj80231.github.io/znote/), blog built with vuepress. 
And if you have questions, please contact me.

**Comment by jsliu-null** [comment]
非常感谢，@ludanxer  @zpj80231
我在努力看看文档和网上的资料
如果有不明白的还要麻烦您@zpj80231

**Comment by meteorlxy** [comment]
QQ群 686025154
