### ISSUE TITLE
Change the code block background and text

### ISSUE THREAD

**Issue by mspoulsen** [vuejs/vuepress#2223]
Any chance that you could change the dark code blocks so that they match the code blocks with light (#f8f8f8) background on https://vuejs.org/v2/guide/? 

It is so much nicer (and cheaper) when printing :slightly_smiling_face:

**Comment by ludanxer** [comment]
Hi @mspoulsen , not sure if they will decide to change it. But currently you can change the background color in [palette.styl](https://vuepress.vuejs.org/config/#palette-styl) 

```css
$codeBgColor = #f8f8f8
```

and change text color in [index.styl](https://vuepress.vuejs.org/config/#index-styl)

```css
@import '~prismjs/themes/prism.css'
```

May relate to #1401

**Comment by mspoulsen** [comment]
Thanks @ludanxer  :+1:
