### ISSUE TITLE
import sass file success, but compile failed

### ISSUE THREAD

**Issue by ChangerHe** [vuejs/vuepress#2224]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?

compile scss file successfully

#### What is actually happening?

I had import my component to custom component, but the sass variables and functions cannot compile.
![image](https://user-images.githubusercontent.com/26900876/76688234-f8325680-6665-11ea-8ad0-879dc7c98d8a.png)

that is what I had do:
![image](https://user-images.githubusercontent.com/26900876/76688252-29128b80-6666-11ea-8f9b-a15981168d10.png)
![image](https://user-images.githubusercontent.com/26900876/76688259-3465b700-6666-11ea-8ec2-3a43d73b7797.png)
the sass functions and variables is existed in `../styles/index.scss`

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
    Safari: 13.0.4
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found

**Comment by meteorlxy** [comment]
remove `url()`
