### ISSUE TITLE
Potential security vulnerability found in the minimist dependency?

### ISSUE THREAD

**Issue by jerryc127** [vuejs/vuepress#2228]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

the new version.
i built the Github page using vuepress,
but the GitHub notice me
Potential security vulnerability found in the minimist dependency?
![image](https://user-images.githubusercontent.com/16351105/76868128-6b73dc80-68a1-11ea-8aa4-d64faf983d3d.png)

how to solve?

**Comment by meteorlxy** [comment]
upgrade minimist
