### ISSUE TITLE
vuepress配置完alias打包报错

### ISSUE THREAD

**Issue by diy4869** [vuejs/vuepress#2236]
相关webpack配置
![image](https://user-images.githubusercontent.com/29079700/77153180-4d41f280-6ad4-11ea-95e3-d97e0e664816.png)

报错截图
![image](https://user-images.githubusercontent.com/29079700/77153110-271c5280-6ad4-11ea-976b-520e69357cda.png)

**Comment by tolking** [comment]
为什么你需要用 **if (!isServer)** ?

**Comment by diy4869** [comment]
> 为什么你需要用 **if (!isServer)** ?

如果不加的话，build的时候就会一直打印config的配置

**Comment by tolking** [comment]
i need a demo

or try
``` js
const path = require('path')

module.exports = {
chainWebpack: config => {
    config.resolve.alias.set('@docs', path.resolve(__dirname, '../docs'))
}
}
```

**Comment by meteorlxy** [comment]
Please follow the issue template
