### ISSUE TITLE
[Enhancement] use less memory while building.

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#2241]
- [x] I confirm that this is an issue rather than a question.

It's base on #2221。

The doc folder is less than 10M in size, and more than a half of it's size are images. So I think that vuepress should have the ability to build it with 2GB memory in use.

We should consider that some of the project which is using vuepress to build docs have the need to run on **vitual machines with 4GB memory**. But now vuepress often use more than 4GB memory itself while building.

Maybe some optimization is needed.

A demo here: https://github.com/Mister-Hope/vuepress-stress-test

It is falling on CI with the default command `vuepress build`

**Comment by jixuan1989** [comment]
I occur the same issue.
We have 158 markdown files. 
When using vuepress v0.x, it is fine.
But after upgrade to vuepress v1.x, JS out of memory occurs, even though I set ` --max_old_space_size=4096 `

**Comment by Mister-Hope** [comment]
I have 500+ markdown files hhh
