### ISSUE TITLE
Change search plugin regular expression to support non-latin characters

### ISSUE THREAD

**Issue by Alizadeh118** [vuejs/vuepress#2242]
#### What problem does this feature solve?
This add non-latin support for search plugin.
#### What does the proposed API look like?
It's not going to change API.
#### How should this be implemented in your opinion?
Now search plugin use this regex: `(?=.*\bWORD\b)` and it works for latin words but not for non-latin ones and this is about `\b` word boundaries.
We can use [this alternative way](https://stackoverflow.com/questions/14074308/regex-word-boundary-alternative) to support both latin and non-latin characters:
`(?=.*(?<=\s|^)WORD(?=\s|$))`
#### Are you willing to work on this yourself?
Yes.

**Comment by meteorlxy** [comment]
Contribution welcome

**Comment by ThaddeusJiang** [comment]
hi @meteorlxy @Alizadeh118 
I have made a PR for this Issue.

**Comment by meteorlxy** [comment]
@ThaddeusJiang 

Hey, I just reviewed your solution. That may break current logic for English words.

I just made an alternative PR #2283 for this.

**Comment by ThaddeusJiang** [comment]
Hi @meteorlxy 

As my test, nothing was broken.
Could you share your test case?

![CleanShot 2020-04-06 at 15 01 24](https://user-images.githubusercontent.com/17308201/78527332-8938bf80-7817-11ea-86d9-a6aed38f1c19.jpg)

**Comment by meteorlxy** [comment]
@ThaddeusJiang 

![image](https://user-images.githubusercontent.com/18205362/78529187-ab304300-7813-11ea-93e8-aa9103fd8f76.png)

**Comment by ThaddeusJiang** [comment]
@meteorlxy  Is it incorrect?

**Comment by meteorlxy** [comment]
Before your change, it won't match ready

**Comment by ThaddeusJiang** [comment]
Thank you, I understand that it didn't match `ready` before my change.

I read #1557, I view the improvement is 
> search can now take in multiple words separated by a space.

not relate fuzzy query.

--- 
BTW, Could we support `fuzzy query`?
