### ISSUE TITLE
自带搜索工具不能搜索到中文内容的md

### ISSUE THREAD

**Issue by taojunnan** [vuejs/vuepress#2243]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce
有两个md，一个是英文内容，一个是中文内容

#### What is expected?
md中有中文也能搜索
#### What is actually happening?
英文的能被搜索到，中文的不能被搜索到
#### Other relevant information
config.js
```
module.exports = {
  title: '标题',
  description: '测试项目',
  base: '/vuepress/',
  configureWebpack: {
    resolve: {
      alias: {
        '@alias': './assets/'
      }
    }
  },
  dest: './dist',
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Blog', link: '/blog/' },
      { text: 'About', link: '/about/' },
    ],
    sidebar: [
      {
        title: 'Blog',
        collapsable: false,
        children: [
          '/blog/',
          '/blog/first'
        ]
      }
    ],
    sidebarDepth: 3
  }
}
```

**Comment by meteorlxy** [comment]
May be duplicated of #2242

**Comment by jimwmg** [comment]
https://vuepress.vuejs.org/zh/theme/default-theme-config.html?#algolia-%E6%90%9C%E7%B4%A2
是不是只能用  algolia搜索了？

**Comment by taojunnan** [comment]
> https://vuepress.vuejs.org/zh/theme/default-theme-config.html?#algolia-%E6%90%9C%E7%B4%A2
> 是不是只能用 algolia搜索了？

@jimwmg 你可以去看下0.x版本的`searchBox`的代码，移植过来，以前版本是可以的

**Comment by Teacher-Li** [comment]
> > https://vuepress.vuejs.org/zh/theme/default-theme-config.html?#algolia-%E6%90%9C%E7%B4%A2
> > 是不是只能用 algolia搜索了？
> 
> @jimwmg 你可以去看下0.x版本的`searchBox`的代码，移植过来，以前版本是可以的

试过几个0.x版本呢，都不行

**Comment by liqingchang0365** [comment]
@taojunnan 我也是一样的问题。卡了两天了以为我自己的问题。但是我github上下载其他人的代码，在我电脑上运行，是没有问题的。

**Comment by taojunnan** [comment]
> > > https://vuepress.vuejs.org/zh/theme/default-theme-config.html?#algolia-%E6%90%9C%E7%B4%A2
> > > 是不是只能用 algolia搜索了？
> > 
> > 
> > @jimwmg 你可以去看下0.x版本的`searchBox`的代码，移植过来，以前版本是可以的
> 
> 试过几个0.x版本呢，都不行

@Teacher-Li 这是我GitHub上随便找的例子运行是可以的，版本`0.7.1`，[链接](https://github.com/newming/vuepress)

**Comment by taojunnan** [comment]
> @taojunnan 我也是一样的问题。卡了两天了以为我自己的问题。但是我github上下载其他人的代码，在我电脑上运行，是没有问题的。

@liqingchang0365 `vuepress`版本问题，我对比了下`1.x`和`0.x`的`searchBox`代码，`1.x`版本用的`\b`正则匹配单词边界，但不适用于中文，`0.x`版本直接用的`indexOf()`.  
`0.x`
```js
item.title &&  item.title.toLowerCase().indexOf(query) > -1
```
`1.x`
```js
`(?=.*\\b${escapeRegExp(word)})`
```

**Comment by zq99299** [comment]
我也发现了，最近 ＃1557 的被合并了，导致不能搜索到中文了

**Comment by Teacher-Li** [comment]
https://github.com/vuejs/vuepress/pull/2266/commits/b59288310a642497d4e954189922cc7393a3e1f0
有老哥提了Pr呢

**Comment by liqingchang0365** [comment]
> > @taojunnan 我也是一样的问题。卡了两天了以为我自己的问题。但是我github上下载其他人的代码，在我电脑上运行，是没有问题的。
> 
> @liqingchang0365 `vuepress`版本问题，我对比了下`1.x`和`0.x`的`searchBox`代码，`1.x`版本用的`\b`正则匹配单词边界，但不适用于中文，`0.x`版本直接用的`indexOf()`.
> `0.x`
> 
> ```js
> item.title &&  item.title.toLowerCase().indexOf(query) > -1
> ```
> 
> `1.x`
> 
> ```js
> `(?=.*\\b${escapeRegExp(word)})`
> ```

感谢！ 
`
yarn add @vuepress/plugin-search@1.3.1
`
重启项目，问题解决

**Comment by jimwmg** [comment]
我目前还是通过：https://community.algolia.com/docsearch/  解决的，本地启动的还是无法支持  全局 + 中文搜索

**Comment by taojunnan** [comment]
> 我目前还是通过：https://community.algolia.com/docsearch/ 解决的，本地启动的还是无法支持 全局 + 中文搜索

@jimwmg 申请不下来，有些主要还是公司内部查阅的文档，没有挂外网

**Comment by meteorlxy** [comment]
紧急的话可以考虑先用 1.3 版本。

Closing this as duplicated of #2242
