### ISSUE TITLE
vuepress打包报错

### ISSUE THREAD

**Issue by diy4869** [vuejs/vuepress#2246]
1. vuepress打包报错
这是我目前的配置
![image](https://user-images.githubusercontent.com/29079700/77404545-dadf5400-6dec-11ea-97be-568f4ee2edfc.png)
报错截图
![image](https://user-images.githubusercontent.com/29079700/77404717-1f6aef80-6ded-11ea-9025-f28e218ebb56.png)
build打包 client处理到92%的时候，就是terserWebpackPlugin这块，会一直输出{}, 然后报错

**Comment by ludanxer** [comment]
Hi, can you follow the issue template and provide a minimal reproduction? thanks!

And please use English so everyone could understand and help you.
