### ISSUE TITLE
Make it possible to set homepage title

### ISSUE THREAD

**Issue by Alizadeh118** [vuejs/vuepress#2247]
#### What problem does this feature solve?
It gives the ability to change home page title.
#### What does the proposed API look like?
It's not going to change API.
#### How should this be implemented in your opinion?
Imagine you want to use [homepage option](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage) so you set `home: true` then you search something that exist on homepage:
![Screen Shot 1399-01-05 at 16 12 41](https://user-images.githubusercontent.com/13087224/77421919-4f64c380-6dea-11ea-87a9-1fb4e8baa69c.png)
It is shown as `Home` and you can **not** change homepage title because when `home` is `true` it's hard coded and I don't know why:
https://github.com/vuejs/vuepress/blob/7977532d5a0d67509b25c1a788f236cd6e312ae5/packages/%40vuepress/shared-utils/src/inferTitle.ts#L12-L14
#### Are you willing to work on this yourself?
Yes.

**Comment by meteorlxy** [comment]
Contribtion welcome.

Tip: remember to consider the locales support

**Comment by Mister-Hope** [comment]
> ## Feature request
> #### What problem does this feature solve?
> It gives the ability to change home page title.
> 
> #### What does the proposed API look like?
> It's not going to change API.
> 
> #### How should this be implemented in your opinion?
> Imagine you want to use [homepage option](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage) so you set `home: true` then you search something that exist on homepage:
> ![Screen Shot 1399-01-05 at 16 12 41](https://user-images.githubusercontent.com/13087224/77421919-4f64c380-6dea-11ea-87a9-1fb4e8baa69c.png)
> It is shown as `Home` and you can **not** change homepage title because when `home` is `true` it's hard coded and I don't know why:
> https://github.com/vuejs/vuepress/blob/7977532d5a0d67509b25c1a788f236cd6e312ae5/packages/%40vuepress/shared-utils/src/inferTitle.ts#L12-L14
> 
> #### Are you willing to work on this yourself?
> Yes.

Are you working on it? I can help if you need @Alizadeh118

**Comment by Alizadeh118** [comment]
I made a PR and honestly I didn't a lot of changes but it fixes the problem.
Hope to work as my first PR on GitHub :)

**Comment by Mister-Hope** [comment]
> I made a PR and honestly I didn't change a lot but it fixes the problem.
> Hope to work as my first PR on GitHub :)

As meteorlxy suggest ed above, could you make the default word 'Home' changed with locales? Just a suggestion.

**Comment by Alizadeh118** [comment]
I'll work on it.

**Comment by Alizadeh118** [comment]
I have checked the code and I'm not sure about something and I need your help.

How should it exactly support locales for "Home" **default** title?

I can imagine three options:
1. We can use [`locales`](https://vuepress.vuejs.org/config/#locales) that user provide on `.vuepress/config.js` and look for some property like `homepageTitle` for each locale.

2. As we have homepage as a feature for default theme and some themes may not have homepage, we can implement this in default theme scope and use [default theme i18n config](https://vuepress.vuejs.org/guide/i18n.html#default-theme-i18n-config) and get some value from its `locales` property and for each locale, like that `homepageTitle`.

But the problem for both is that we already made it possible to set homepage title from [home frontmatter](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage) `title` property. And actually our challenge was about **default** title for homepage, means there is no a defined `title` by user anywhere.

3. So we can have a data list of translations for word of `Home` for all languages that are used as a default when user don't set `title` for homepage in [home frontmatter](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage).

But I'm not sure about having such a big list in core only for support default `Home` word for locales.

Thank you in advance for you suggestions.

**Comment by Mister-Hope** [comment]
i think 1 is not necessary, and 3 is what I want, any problem doing 2 such as cannot get the locale?

**Comment by Alizadeh118** [comment]
There is no problem for getting the locale from default theme config (2nd scenario), but I mean if we want to obtain homepage title from user explicitly, we don't have to get it from theme config because we can get it from homepage frontmatter.

So let's say we have a complete list of translations for `Home` for each language (3rd scenario),
_Although I'm not sure that how we should get this list but anyway:_
```json
{
  "en": "Home",
  "zh": "家"
}
```
How should we find out the page (homepage) locale in `inferTitle` function?
When `inferTitle` is called in `Page.js`:
https://github.com/vuejs/vuepress/blob/f54b389993dcb4e2fd57a82dee3dd4abd5d81dd6/packages/%40vuepress/core/lib/node/Page.js#L111
we have access to `siteConfig` and `themeConfig` and `path`:
```js
Page {
  _context: App {
    siteConfig: {
  	  locales: {
  	    '/': {
  	      lang: 'en-US',
  	      title: 'VuePress',
  	      description: 'Vue-powered Static Site Generator',
  	      homepageTitle: 'Home',
  	      path: '/'
  	    },
  	    '/zh/': {
  	      lang: 'zh-CN',
  	      title: 'VuePress',
  	      description: 'Vue 驱动的静态网站生成器',
  	      homepageTitle: '家',
  	      path: '/zh/'
  	    }
  	  },
  	  theme: '@vuepress/vue',
  	  themeConfig: {
  	    locales: {
  	      '/': {
  	        label: 'English',
  	        selectText: 'Languages',
  	        ariaLabel: 'Select language',
  	        editLinkText: 'Edit this page on GitHub',
  	        lastUpdated: 'Last Updated',
  	        nav: [Array],
  	        sidebar: [Object]
  	      },
  	      '/zh/': {
  	        label: '简体中文',
  	        selectText: '选择语言',
  	        ariaLabel: '选择语言',
  	        editLinkText: '在 GitHub 上编辑此页',
  	        lastUpdated: '上次更新',
  	        nav: [Array],
  	        sidebar: [Object]
  	      }
  	  },
    },
  regularPath: '/',
  relativePath: 'README.md',
  path: '/'
}
```
We can pass `siteConfig.locales` to `inferTitle` as third parameter then make a loop and map `lang` to `path`, for example `{ en: '/', zh: '/zh/ }` then detect  the page locale from the `path` and finally get the correct `Home` translations from our list.

But I don't think it's a good idea and also I have no another!
