### ISSUE TITLE
Module not found: Error: Can't resolve 'canvas' in ...

### ISSUE THREAD

**Issue by zhufuge** [vuejs/vuepress#2251]
I use module `Trianglify` in my blog theme. It works well in `vuepress dev`, but `vuepress build` is not.
In `vuepress build`, `Client Compiled successfully`, but `Server Compiled with some errors`.

Maybe in `Trianglify`, when node environment, it try `require('canvas')`. So I got:
```
(undefined) ./node_modules/jsdom/lib/jsdom/level2/html.js
Module not found: Error: Can't resolve 'canvas' in ...
...
```

How can i solve this ?

Should I add module `canvas` ?

Help!
Sorry for my poor English.

**Comment by andyhuai** [comment]
How to solve this?
