### ISSUE TITLE
page switch failed, when they use the same layout

### ISSUE THREAD

**Issue by xiayuxiaoyan** [vuejs/vuepress#2257]
## Bug report
in two pages, width default theme ,i custom my layout like:
```
---
layout: xxxlayout
---
```

#### What is expected?
page1 use router-link to page2

#### What is actually happening?
url change,but page content not change. page2's mounted life cycle has not been trigger

- Output of `npx vuepress info` in my VuePress project:
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.3.1 
    @vuepress/theme-default:  1.3.1 
    vuepress: ^1.3.1 => 1.3.1 
  npmGlobalPackages:
    vuepress: Not Found

**Comment by ludanxer** [comment]
Sorry, but I can't reproduce the issue. Can you provide a minimal reproduction? Thanks!

**Comment by xiayuxiaoyan** [comment]
@ludanxer here is my demo:https://github.com/xiayuxiaoyan/vuepress-theme-techface

**Comment by xiayuxiaoyan** [comment]
Does anyone kown why?

**Comment by xiayuxiaoyan** [comment]
After reading the source code i find it use dynamic component which will cause the problem。So i compute data in my custom layout component depend on this.$route.path.
