### ISSUE TITLE
如何在网站底部添加ICP备案号

### ISSUE THREAD

**Issue by sanrentai** [vuejs/vuepress#2263]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by koibi2** [comment]
莫得底部 slot 插槽。
JS 监听吧。

**Comment by QiuZi619** [comment]
> ```
> ---
> home: true
> # footer: 鲁ICP备XXXXXX号
> # ↑↑↑ 把 footer 注释掉 ↑↑↑
> ---
> 
> <div class="footer">
>     <span @click="open_beian">鲁ICP备XXXXXX号</span>
> </div>
> 
> <script>
>   export default{
>     methods:{
>         open_beian(){
>             window.open("http://beian.miit.gov.cn/")
>         }
>     }
>   }
> </script>
> ```
> 
> @sanrentai

帮助到我了，写成 <a> 标签可能会好一点啊
