### ISSUE TITLE
[bug report]] DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method

### ISSUE THREAD

**Issue by ijandc** [vuejs/vuepress#2271]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
使用`pwa`插件，然后`build`生产
起一个静态服务，直接跑刚才打包的产物，
页面就会报这个错误
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method
```

去掉pwa插件，重新build生产，起服务，则页面正常显示

```
"@vuepress/plugin-pwa": "^1.4.0"
```

#### What is expected?

页面正常显示，且可以离线阅读

#### What is actually happening?

页面报错
![image](https://user-images.githubusercontent.com/34884325/78218978-4615de00-74f1-11ea-889b-058a5a08da0b.png)
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

以下是`yarn vuepress info`的输出结果：

```bash
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 13.11.0 - /var/folders/m6/b1p0wr4n7lgg59cgz3klvrhw0000gn/T/yarn--1585810507738-0.7197932868771071/node
    Yarn: 1.22.4 - /var/folders/m6/b1p0wr4n7lgg59cgz3klvrhw0000gn/T/yarn--1585810507738-0.7197932868771071/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.4.0 
    @vuepress/theme-default:  1.4.0 
    vuepress: ^1.3.1 => 1.4.0 
  npmGlobalPackages:
    vuepress: Not Found

```

**Comment by ludanxer** [comment]
Hi @ijandc , can you provide a minimal reproduction or share your repo? thanks!

**Comment by JohnieXu** [comment]
I have tried a demo, everything works perfectly. If u used [vuepress-theme-reco](https://github.com/vuepress-reco/vuepress-theme-reco), maybe u can see this issue vuepress-reco/vuepress-theme-reco#136

**Comment by recoluan** [comment]
@ijandc 目前我个人使用过程中没有出现此问题，请使用主题最新版本 `1.4.2` 再尝试一下，如果还有问题，进Q群我们一起解决一下。

**Comment by meteorlxy** [comment]
Closing as it's theme scoped

**Comment by zhixinpeng** [comment]
我加完Pwa插件后也出现这个错误，我是自己写的主题。

**Comment by zzx-wj** [comment]
I had the same problem
