### ISSUE TITLE
内置搜索框无法搜索中文，但是搜索英文却可以(The built-in search box cannot search for Chinese, but it can search for English)

### ISSUE THREAD

**Issue by guestccc** [vuejs/vuepress#2279]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

我现在拉一个新的模版下来也是会的，`1.4.0` ,

1. 全局安装 `vuepress`，版本`1.4.0` 

2. 文件目录
```
 ├── .vuepress (可选的)
 │   └── config.js (可选的)
 ├── about.md
 └── README.md
```
config.js文件
```js
// config.js
module.exports = {
  themeConfig: {
    search: true,
    searchMaxSuggestions: 10
  }
}
```
about.md文件
```js
//about.md
# 关于我们1

# ABOUT

## 关于我们

## about
```

 README.md文件
```js
// README.md
---
home: true
heroImage: /hero.png
heroText: Hero 标题
tagline: Hero 副标题
actionText: 快速上手 →
actionLink: /zh/guide/
features:
- title: 简洁至上
  details: 以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。
- title: Vue驱动
  details: 享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。
- title: 高性能
  details: VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。
footer: MIT Licensed | Copyright © 2018-present Evan You
---
```

3. 执行`vuepress dev .`

项目成功跑在了localhost:8080

4. 浏览项目，点击搜索框，分别搜索 `about`和 `关于` 两个关键字

#### What is expected?

预期：应该是中英文都可以搜索才对

#### What is actually happening?

浏览项目，点击搜索框搜索 `about`,成功搜索出有关 `about` 关键字的文章，但是当，搜索 `关于` 关键字时 ，却什么都没有

#### Other relevant information

这里提供一下我的blog，也是用的 `vuepress 1.4.0` 版本，也有这种问题

> my blog --[JSChen](https://blog.jschen.cc)

- Output of `npx vuepress info` in my VuePress project:

vuepress v1.4.0

**Comment by ludanxer** [comment]
May relate to #2243 , #2242 . There is a PR #2266 may fix this.

**Comment by meteorlxy** [comment]
Duplicated to #2242

**Comment by guestccc** [comment]
Thank😍

**Comment by guestccc** [comment]
Thank😍 @meteorlxy @ludanxer
