### ISSUE TITLE
Use `themeEntry.globalLayout` filed custom `GlobalLayout` is not working

### ISSUE THREAD

**Issue by BryanAdamss** [vuejs/vuepress#2285]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- I want to use `themeEntry.globalLayout` filed to custom `GlobalLayout` ,but is not working
- Is there anoter way to custom `GlobalLayout` except use same name component to overwrite just like document mention it

- My config as follows 
```js

module.exports=(themeConfig,ctx)=>{

  const config = {
    plugins,
    define: {
      THEME_BLOG_PAGINATION_COMPONENT: themeConfig.paginationComponent
        ? themeConfig.paginationComponent
        : 'Pagination',
    },
    globalLayout: './layouts/GlobalLayoutCustom.vue', // try to use my own component
  }

  return config

}
```

#### What is expected?

- `GlobalLayoutCustom`  working

#### What is actually happening?

- still use `GlobalLayout`
- ![image](https://user-images.githubusercontent.com/7441504/78582482-e8bebb80-7867-11ea-89f2-45f8b81a6724.png)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```bash
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.4.0 => 1.4.0
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by meteorlxy** [comment]
`path.resolve(__dirname, 'path/to/component')`

**Comment by BryanAdamss** [comment]
> `path.resolve(__dirname, 'path/to/component')`

get it
