### ISSUE TITLE
Markdown plugin name only works in the short-hand form

### ISSUE THREAD

**Issue by vojtapol** [vuejs/vuepress#2286]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

When configuring Markdown and requesting a plugin to be used like this:
```js
markdown: {
  plugins: [
    'markdown-it-abbr'
  ]
}
```
The abbreviations are ignored.

However, this configuration works as desired:
```js
markdown: {
  plugins: [
    'abbr'
  ]
}
```

#### What is expected?
Both `markdown-it-abbr` and `abbr` in the plugin section should have the same effect as [according to the documentation](https://vuepress.vuejs.org/config/#markdown-plugins) omitting the `markdown-it-` portion of the plugin name is optional.

#### What is actually happening?
Only the shorthand form works.

#### Other relevant information

My `package.json`:
```json
{
  "name": "wiki",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.4.0",
    "markdown-it-abbr": "^1.0.4",
    "vuepress": "^1.4.0"
  }
}
```

**Comment by meteorlxy** [comment]
Thanks for report.

**Comment by meteorlxy** [comment]
Ref #2175
