### ISSUE TITLE
Images render in docs:dev but not deployment

### ISSUE THREAD

**Issue by pdimens** [vuejs/vuepress#2287]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Images are all in the `.vuepress/public/images` folder, and they load/render correctly when live-viewing the static site with `yarn docs:dev`, however, all of the images are broken links in the deployed website (via GitHub Pages). 

docs/.vuepress/
├── components
├── config.js
├── public
│   ├── favicon.ico
│   └── images
│       ├── logo_icon.png
│       ├── objectplot.png
│       ├── orcid.png
│       ├── PopData.png
│       ├── PopData.svg
│       ├── speedplot.png
│       ├── terminal_cactus.png
│       └── twitter.png
└── styles
    ├── index.styl
    ├── palette.styl
    └── style.styl

In the markdown, images are referenced as `![alt text](/images/speedplot.png)`. 

#### Steps to reproduce
The repo is pdimens/PopGen.jl

#### What is expected?
(from `yarn docs:dev`)
![image](https://user-images.githubusercontent.com/19176506/78692327-534f1600-78bf-11ea-8189-abe109c481cd.png)

#### What is actually happening?
(from https://pdimens.github.io/PopGen.jl/getting_started/comparison.html)
![image](https://user-images.githubusercontent.com/19176506/78692361-64982280-78bf-11ea-91bd-08e1334548a9.png)
Link to site: https://pdimens.github.io/PopGen.jl/getting_started/comparison.html#benchmarks

#### Other relevant information
The `config.js` includes this information (nav and side bars removed for clarity):
```js
module.exports = {
    base: '/PopGen.jl/',
    title: 'PopGen.jl',
    description: 'Population Genetics in Julia',
    plugins: [
        'flexsearch',
        'vuepress-plugin-element-tabs',
        'vuepress-plugin-smooth-scroll',
        '@vuepress/plugin-back-to-top',
        '@vuepress/active-header-links',
        '@vuepress/plugin-nprogress',
        '@vuepress/medium-zoom',
        '@vuepress/last-updated',
        [
         'vuepress-plugin-mathjax', {
            target: 'svg',
            macros: {
                '*': '\\times',
            },
        },
      ]
    ],
    themeConfig: {
        logo: '/images/logo_icon.png',
        flexSearchOptions: {
          },
        docsRepo: 'pdimens/popgen.jl',
        // if your docs are not at the root of the repo:
        //docsDir: '/docs/',
        // if your docs are in a specific branch (defaults to 'master'):
        docsBranch: 'gh-pages',
        // defaults to false, set to true to enable
        editLinks: true,
        // custom text for edit link. Defaults to "Edit this page"
        editLinkText: 'Help us improve this page!',
        searchPlaceholder: 'Search the docs...'
    }
}
```

- Output of `npx vuepress info` in my VuePress project:
Environment Info:

  System:
    OS: Linux 5.5 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 13.12.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.4.0 
    @vuepress/theme-default:  1.4.0 
    vuepress: ^1.4.0 => 1.4.0 
  npmGlobalPackages:
    vuepress: 1.4.0

**Comment by ludanxer** [comment]
You are deploying your site to a "non-root" URL, reference images like

```html
<img :src="$withBase('/foo.png')" alt="foo">
```

 check out the [document](https://vuepress.vuejs.org/guide/assets.html#base-url) for more detail.

**Comment by pdimens** [comment]
Thank you for the reply. Do the images always require this html, or is there a suitable markdown equivalent?

**Comment by ludanxer** [comment]
I think you can specify the path to your favicon

```html
<link rel="icon" href="favicon.ico" type="image/x-icon"/>
```

I never actually try it before, but I think you can try to wrap the path with `$withBase`, if it doesn't work, try changing href to `<base>\favicon.ico`

**Comment by newsbielt703** [comment]
It seems to be solved.
