### ISSUE TITLE
Redirecting unknown path to /

### ISSUE THREAD

**Issue by ycmjason** [vuejs/vuepress#229]
I think it make sense to rewrite the location to `/` if the path is not recognised? This way we could enable some sort of SPA functionality?

**Comment by yyx990803** [comment]
I personally think it's better to have a 404 page with a link back to home.

**Comment by ycmjason** [comment]
Perhaps there should be an option for that? What do you think?

**Comment by ycmjason** [comment]
A link back to home is nice as well.

**Comment by mdaffin** [comment]
You can always override the 404 file to redirect instead

**Comment by ulivz** [comment]
You can override the alias pointer of `@notFound` instead.
