### ISSUE TITLE
sidebar children title error display

### ISSUE THREAD

**Issue by SailVR** [vuejs/vuepress#2290]
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hello, in the 1.x version, the title of the children of the sidebar seems to require the first-level title of the md file to be at the forefront, but my markdown documents must have html tag comments at the beginning, so the title of the children cannot be parsed correctly, In version 0.x it is possible
#### What is expected?
display correctly
#### What is actually happening?
 error display
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by SailVR** [comment]
![image](https://user-images.githubusercontent.com/37333508/78789008-242fc600-79df-11ea-99ae-c9df7a9a2c9b.png)
![image](https://user-images.githubusercontent.com/37333508/78789142-504b4700-79df-11ea-8514-50c187ad3ad7.png)
Like this, if I add the html comment in front, the children title of the sidebar cannot be displayed normally, but the content of the article is displayed correctly. This problem is no problem in the 0.x version, but I need the new features of 1.x. My markdwon file must have a header declaration, so I hope you can help me solve this problem.

**Comment by ludanxer** [comment]
@SailVR Thanks for the report. I can reproduce the problem.

Currently, I suggest you explicitly specify the link text to walkaround

```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    sidebar: [
      '/page-a',
      ['/page-b', 'Explicit link text']
    ]
  }
}
```

Check out the [documentation](https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar) for more detail

**Comment by SailVR** [comment]
Ok ,this issue was solved.Thank you!
