### ISSUE TITLE
How to switch multiple versions?

### ISSUE THREAD

**Issue by juukee** [vuejs/vuepress#2299]
## Feature request

How to switch multiple versions?  i have two or more versions for update..such as 1.0, 2.0,3.0

**Comment by Mister-Hope** [comment]
Are you asking to switch been three different docs? You can deploy them with three project in three different path or sub-domains.

**Comment by newsbielt703** [comment]
Or you can simply create another folder, consider them as just different pages:
```
├── v1                     
│   ├── home        
│   ├── api       
├── v2                     
│   ├── home        
│   ├── api
