### ISSUE TITLE
Configuring overlay in chainwebapck does not work

### ISSUE THREAD

**Issue by diy4869** [vuejs/vuepress#2306]
在chainWebapck配置了overlay 并不生效，想把eslint语法警告输出到浏览器上
Configuring overlay in chainwebapck does not work. You want to output the eslint syntax warning to the browser
![image](https://user-images.githubusercontent.com/29079700/79190068-eb1ba980-7e55-11ea-803b-349dfae307b6.png)

**Comment by meteorlxy** [comment]
遵守 issue 模板这么难吗？你这样乱发 issue 被关了多少个了？
