### ISSUE TITLE
Remove the stale branches.

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vuepress#2312]
Since I am now trying to contributing to this repo, I have to switch between branchs, and I found that there are too many branches(24), which a lot of them are merged or solved. So can we just delete them?

![image](https://user-images.githubusercontent.com/33315834/79332620-be4bbd00-7f4f-11ea-8c62-5626392a170b.png)

**Comment by newsbielt703** [comment]
I've just delete some merged branches. Others will leave to its author.
