### ISSUE TITLE
只有一个插件生效

### ISSUE THREAD

**Issue by heny** [vuejs/vuepress#2322]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
![image](https://user-images.githubusercontent.com/45083899/79689927-751aa680-828a-11ea-9a3c-76df7c1dd03f.png)

像这样引入插件，只有copy插件生效了，是我语法错误了吗

**Comment by webSongNO1** [comment]
亲 需要把版本更新到最新版本，我也遇到了，我是把去哪句vuepress卸载后，在项目安装最新版本的vuepress就可以用了

**Comment by Hquestion** [comment]
本地插件要提供个name，不然后面的会把前面的覆盖掉
