### ISSUE TITLE
Typescript: optional chaining fails to parse

### ISSUE THREAD

**Issue by Etheryte** [vuejs/vuepress#2325]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Using optional chaining in components doesn't parse with Vuepress.  

For context, I'm adding `vuepress` to an existing project created with `vue-cli` that uses Typescript 3.8.3.

#### Steps to reproduce

[Minimal repro case repository](https://github.com/Etheryte/vuepress-demo)

Summary of steps:  

 - Initialize a Vue project with Typescript via `vue-cli`
 - Add Vuepress locally
 - Add [vuepress-plugin-typescript](https://vuepress.github.io/en/plugins/typescript/)
 - Add [required shims](https://vuepress.github.io/en/plugins/typescript/#enhanceapp-ts)

```ts
// docs/.vuepress/shims-vue.d.ts
declare module '*.vue' {
    import Vue from 'vue'
    export default Vue
}
```

 - [Configure the plugin](https://vuepress.github.io/en/plugins/typescript/#usage) + I've added an alias to resolve dependencies via `@`:

```ts
// docs/.vuepress/config.js
const path = require('path');

const projectRoot = process.cwd();
const alias = path.resolve(projectRoot, 'src');

module.exports = {
  configureWebpack(config) {
    config.resolve.alias['@'] = alias;
  },
  plugins: [
    [
      'vuepress-plugin-typescript',
      {
        tsLoaderOptions: {},
      },
    ],
  ],
}
```

 - Use [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) in a component:

```ts
import Vue from 'vue'
import { Component } from 'vue-property-decorator'

@Component
export default class HelloWorld extends Vue {
  nullableObject: { foo: unknown } | null = null

  get msg () {
    return this.nullableObject?.foo
  }
}
```

 - Import that component in a docs page:

```html
<script lang="ts">
// docs/README.md
import Vue from 'vue'
import Component from 'vue-class-component';

import HelloWorld from '@/components/HelloWorld.vue';

@Component({
  components: {
    HelloWorld,
  }
})
export default class extends Vue {}
</script> 

# Sample docs

<HelloWorld />

```

#### What is expected?

Successful compilation.

#### What is actually happening?

Optional chaining throws a parser error:

```
Uncaught (in promise) Error: Module parse failed: Unexpected token (10:35)
File was processed with these loaders:
 * ./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js
 * ./node_modules/ts-loader/index.js
 * ./node_modules/@vuepress/core/node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     }
|     get msg() {
>         return this.nullableObject?.foo;
|     }
| };
```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 70.0.1
    Safari: 11.1.2
  npmPackages:
    @vuepress/core:  1.4.1
    @vuepress/theme-default:  1.4.1
    vuepress: ^1.4.1 => 1.4.1
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by Mister-Hope** [comment]
Emm, vuepress is using alias like `@theme`, `@parent-theme`, `@internal` `@temp` and so on.

I am not sure about the bug, but I sugest you to change to a new alisa such as `#` and try again.

**Comment by Etheryte** [comment]
@Mister-Hope Thanks for taking the time to look at this. Given [module resolution](https://webpack.js.org/concepts/module-resolution/) is essentially a scanning process in Webpack, overlapping aliases are not a problem. The error message doesn't indicate that would be the case either. You can confirm that by removing the alias in the demo repro and seeing the issue persists.  

The alias is useful to demonstrate an architecture commonly used in [Vue CLI](https://cli.vuejs.org/) projects, but it's not the source of the problem.

**Comment by Mister-Hope** [comment]
So is the problem with the Vue-cli? My theme is build with typescript and I am not having issue when using `?.`

**Comment by Etheryte** [comment]
The Vue CLI based project works correctly with optional chaining on its own. This can be confirmed by running `yarn serve` in the demo repo — the code works as expected there. The problem appears, as described above, when importing that component in Vuepress (regardless of whether you use an alias or a relative import).

**Comment by Mister-Hope** [comment]
I built a vuepress theme https://github.com/mister-hope/vuepress-theme-hope

It do not have any issue using `?.`, so I bet there are some conflict in it.

**Comment by Mister-Hope** [comment]
I just saw the link you provided, I will help checking,

**Comment by Mister-Hope** [comment]
Hey, I am not sure about it, does Vuepress says or it do support writing `<script>` directly in the markdown files?

**Comment by Mister-Hope** [comment]
I think it's ok for you to write a `.vue` file and use it in your markdown files, but I don't think `ts-loader` can and should handle the markdown file you provide to it.

**Comment by Etheryte** [comment]
Using `<script>` tags in markdown files works as expected when optional chaining is removed, both with Typescript and Javascript.

**Comment by Mister-Hope** [comment]
I found this https://v1.vuepress.vuejs.org/guide/using-vue.html#script-style-hoisting, but I think it's for you to write some script which will be parsed after the markdown content is mounted to the dom. And I don't think it's a place for you to write component declare in it. Maybe you should try to write it in another vue files.

**Comment by Mister-Hope** [comment]
Also I don't think it's a bug for vuepress, you can move to https://github.com/vuepress/vuepress-community to open an issue there.

**Comment by Etheryte** [comment]
@Mister-Hope I appreciate your feedback, but everything you've pointed out already works completely fine. The whole example code works correctly when optional chaining is removed from the imported component.

**Comment by Mister-Hope** [comment]
@meteorlxy

**Comment by Mister-Hope** [comment]
I open an issue [here](https://github.com/vuepress/vuepress-community/issues/33) for you, you can follow this. It's not related to vue-cli.

Besides, I make a new [demo](https://github.com/Mister-Hope/vuepress-typescript-bug) with only 9 files.

**Comment by meteorlxy** [comment]
Optional chaining operator is part of ES2020, so do not set the target to `es2020` / `esnext`, or you have to use an extra babel plugin to handle those new features in es2020
