### ISSUE TITLE
TypeError: Cannot read property 'pages' of undefined

### ISSUE THREAD

**Issue by massimilianomarini** [vuejs/vuepress#2326]
- [ ] I confirm that this is an issue rather than a question.

## Bug report

I'm using the `@vuepress/plugin-blog` and running `npm run dev` and pagination works fine for both _posts_ and _tags_.

#### Steps to reproduce

But when I try to render the static HTML with `npm run build` I got this error

```
wait Rendering static HTML...
[Vue warn]: Error in render: "TypeError: Cannot read property 'pages' of undefined"

found in

---> <Layout>
       <GlobalLayout>
         <Root>
error Error rendering /tag/: false
undefined
TypeError: Cannot read property 'pages' of undefined
    at new Pagination (node_modules/@vuepress/plugin-blog/lib/client/pagination.js:8:16)
    at PaginationGateway.getPagination (node_modules/@vuepress/plugin-blog/lib/client/pagination.js:80:15)
    at VueComponent.$getPagination (node_modules/@vuepress/plugin-blog/lib/client/pagination.js:97:31)
    at Proxy.$pagination (node_modules/@vuepress/plugin-blog/lib/client/pagination.js:91:28)
```

#### What is expected?

No errors, because it works fine in `dev` mode. 🤷🏻‍♂️
`$pagination.pages` show always the right items for both posts and tags.

#### What is actually happening?

Seems like when building the static HTML, VuePress cant list posts returned by the tag selection?
I'm only guessing, as I said in `dev` mode it works fine.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

Environment Info:

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: Not Found
    Safari: 13.0.5
  npmPackages:
    @vuepress/core:  1.4.1 
    @vuepress/theme-default:  1.4.1 
    vuepress: ^1.4.1 => 1.4.1 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by massimilianomarini** [comment]
I find the issue, I was missing the `Tags.vue` and `Tag.vue` into `layouts` folder.

**Comment by vsetchinfc** [comment]
@massimilianomarini I am getting the same error when building the production version. What Tags.vue and Tag.vue files contain? Same as Layout.vue file? Thank you
