### ISSUE TITLE
Bad certificate on v0.vuepress.vuejs.org

### ISSUE THREAD

**Issue by 0az** [vuejs/vuepress#2327]
- [X] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Go to https://v0.vuepress.vuejs.org/

#### What is expected?

A certificate for `v0.vuepress.vuejs.org` is presented.

#### What is actually happening?

The default Netlify wildcard certificate is presented.

#### Other relevant information

N/A.

**Comment by newsbielt703** [comment]
Thanks for the report.

**Comment by bencodezen** [comment]
Thanks for reporting it @0az! Should be good to go now!
