### ISSUE TITLE
sidebar 配置有些复杂

### ISSUE THREAD

**Issue by vincent4j** [vuejs/vuepress#233]
刚看了下帮助文档，感觉 sidebar 配置有些复杂，是通过 json 格式来实现的，对不懂技术的同学可能有些困难。

当然如果 vuepress 想着用户群体就单单是技术人员那也就没问题。

我个人比较喜欢 gitbook 那种直接通过一个 md 文件来撰写 左侧目录，不懂技术的人也能 run 起来。

**Comment by vincent4j** [comment]
http://zitiao.org/deploy/
这是我自己用 gitbook 折腾的一个，就有一个毛病，对 移动端 支持的不好，移动端上看起来不舒服。
gitbook 的这套，特别是撰写起来非常方便。

**Comment by ulivz** [comment]
谢谢你的建议！只是VuePress的核心用户确实是针对（半）技术人员，不然很多有价值的拓展功能都用不到。

此外，配置也可以是 yml 格式，完全不懂技术的同学稍稍看下也能够快速配置，和你所说的写一个md也没多少区别。 单独开一个文件来写sidebar也只是配置的另一种表现形式而已（docsify是这么做的），但是目前我们没有打算将配置分离到不同文件中。
