### ISSUE TITLE
无法在移动端显示粗体样式

### ISSUE THREAD

**Issue by panxingcheng** [vuejs/vuepress#2336]
PC端：
![image](https://user-images.githubusercontent.com/31773900/80048985-55aea280-8544-11ea-94e1-a6c1694eb658.png)

移动端：
![image](https://user-images.githubusercontent.com/31773900/80049154-c1910b00-8544-11ea-8da8-d36c4155ec22.png)

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/80272876-fd240480-86ff-11ea-8642-6c43745df6ef.png)
What I found out , is that vuepress is giving the correct css style for strong, So, maybe you should open it somewhere else such as your phone browser feedback page?

![image](https://user-images.githubusercontent.com/33315834/80272929-6d328a80-8700-11ea-8e55-1c5a6247edc0.png)

It 's not Vuepress's problem.

**Comment by panxingcheng** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/80272876-fd240480-86ff-11ea-8642-6c43745df6ef.png)
> What I found out , is that vuepress is giving the correct css style for strong, So, maybe you should open it somewhere else such as your phone browser feedback page?
> 
> ![image](https://user-images.githubusercontent.com/33315834/80272929-6d328a80-8700-11ea-8e55-1c5a6247edc0.png)
> 
> It 's not Vuepress's problem.

You can try it on the Microsoft Edge in the Android.

**Comment by Mister-Hope** [comment]
So you can just open a issue on their repo, am I clear? It's not related to vuepress.
