### ISSUE TITLE
在vuepress中如何动态的加载一段md内容到layout.vue组件里

### ISSUE THREAD

**Issue by lucky-yang** [vuejs/vuepress#2354]
动态的md内容
```
::: slot aaa
# Here is slot aaa
:::
- A Paragraph
- Another Paragraph
::: slot bbb
Here is slot bbb
:::
```
layout vue的temaplate
```
<template>
  <div class="theme-container">
    <Content slot-key="aaa" />
   <br/>=============
    <Content />
   <br/>=============
    <Content slot-key="bbb" />
    <br />
  </div>
</template>
```

md内容动态从后台api获取，请问如何在vuepress里用js把他们动态的插入到template中

如果docs下的md文件是上面的md内容，页面在编译完第一次显示可以显示md文件的内容，但是如果我想动态显示的话，如何才可以做到

有没有方法可以直接像重新编译一下md内容然后加载一次vue的组件呢

谢谢了

**Comment by Mister-Hope** [comment]
Currently no, all the markdown is handled while compiling

**Comment by ulivz** [comment]
Duplicate of https://github.com/vuejs/vuepress/issues/2352
