### ISSUE TITLE
怎么实现复选框功能

### ISSUE THREAD

**Issue by fobgochod** [vuejs/vuepress#2364]
怎么实现复选框功能
我在md文件里面这样编辑，
```
- [X] 客户管理
    - [ ] 用户管理
    - [X] 用户管理
```
效果是这样：
![image](https://user-images.githubusercontent.com/13817644/80855485-2864a180-8c74-11ea-94a6-57f41bb4e30a.png)

希望类似这样：
![image](https://user-images.githubusercontent.com/13817644/80855409-8f358b00-8c73-11ea-8be1-dcae883140da.png)

**Comment by tolking** [comment]
You need [markdown-it-task-lists](https://www.npmjs.com/package/markdown-it-task-lists) to do this

npm install markdown-it-task-lists ( or yarn add markdown-it-task-lists )

``` js
// config.js
module.exports = {
  markdown: {
    plugins: ['task-lists']
  }
}
```
