### ISSUE TITLE
In Production Env , my components with v-if will throw error "DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method. "

### ISSUE THREAD

**Issue by wzdxy** [vuejs/vuepress#2368]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

repo: https://github.com/wzdxy/electron-qa
branch: master
commit id: 04880b0d59934d10a78db857d11deaac02d2d4f6
component path : theme-wzdxy\components\nav-single-img-ad.vue

```bash
npm i
npm run build
```
serve with http-server/nginx
open browser devtools , the error will appear in console

#### What is expected?

My components display in production environment

#### What is actually happening?

I used a custom theme extends default theme (includes a component) , and I used `v-if`  on my custom component root node.

It works fine in dev env , but after built , this error appeared in prod env.

![image](https://user-images.githubusercontent.com/12983764/80937738-fa649600-8e08-11ea-85f3-a14d18010088.png)

When I changed `v-if` to `v-show` , the error disappear. 

![image](https://user-images.githubusercontent.com/12983764/80935806-e6b53180-8e00-11ea-93f5-986eb8f81666.png)

But I didn't call `appendChild` in my component ,  and there is no DOM Actions.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core:  1.4.1
    @vuepress/theme-default:  1.4.1
    vuepress: ^1.4.1 => 1.4.1
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by meteorlxy** [comment]
A typical ssr mismatch issue. Make sure the value of `show` keep the same before `mounted` life cycle

**Comment by chryw** [comment]
@meteorlxy I'm running into this issue as well. I don't really understand. Could you help? Here are my newbie questions:
- How do I preview in production mode without actually deploying it?
- I can't tell which component has this issue.
	- I didn't change the nav component when this started to happen.
	- I added some `v-if` to the `Page.vue` to override the default theme. Could the problem be from there?
	- The Home page has custom components and some `v-if` attributes. I didn't make changes to that component as well. It worked fine before. But I'm only seeing this error in the root/Home page.
![playbook-router-issue](https://user-images.githubusercontent.com/7075677/86639005-1ad9d980-bf8d-11ea-812e-fd4d490e1e02.gif)




Any help would be appreciated. Thanks!

**Comment by meteorlxy** [comment]
> How do I preview in production mode without actually deploying it?

Try one of these:

- `vuepress build`, then serve the dist files using local http server. For example, `anywhere` or `http-server`
- use [vuepress-plugin-serve](https://vuepress.github.io/plugins/serve)

> I can't tell which component has this issue

I can't tell what's wrong with your site if you don't provide a reproduce repo.

FYI, see [this](https://vuepress.github.io/en/plugins/dehydrate/#why-we-need-this-plugin) for this kind of problems.

**Comment by chryw** [comment]
@meteorlxy Thanks for your quick response! Here's an update:
- I did try `http-server` but the error didn't show up locally. It only shows in the actually deployed site (Azure). I'll take a look at `vuepress-plugin-serve`. Thanks! 
- I found the problem in the home page component 🎉
	There was a `v-if` evaluation that could get invalid data depending on the actual markdown docs content. The value is date/time related so it may change. I didn't catch it before because I didn't have a markdown page of that edge case. I added data validation and the problem is resolved.

I'm not familiar with "ssr mismatch issue" but I think your hint led me to the right direction. Thanks again for your help!
