### ISSUE TITLE
请问能将入门文档写得详细一些吗？

### ISSUE THREAD

**Issue by xiaochunjimmy** [vuejs/vuepress#2376]
#### What problem does this feature solve?
让不懂 Vue.js 的用户也能快速上手 VuePress 且开发主题
#### How should this be implemented in your opinion?
经过阅读 VuePress 的文档，非常喜欢 Vuepress 的一些特性与强大的拓展性，想用来作为自己的静态博客框架，但是对于只懂 Html/CSS 和一点 JS 的用户而言，VuePress 的开发主题入门文档个人感觉还是有些曲线的，似乎需要了解很多 Vue.js 相关的知识才行：
> 到这里，就像开发一个普通的 Vue 应用一样。如何组织你的主题，这完全取决于你。

但对于以搭建博客并开发自定义主题为目的用户而言，“回去学好 Vue.js 再来” 似乎成为了一道壁垒。个人感觉 Gatsby 的入门文档写得还蛮不错的，对于不懂 React 的用户，通过阅读其文档也能快速上手入门，并了解一些 JSX 等 React 的特性，然后逐步通过 Doc 文档开发 Gatsby 自定义主题。期望 VuePress 也能加强一些对 Vue.js 小白的入门学习通道。这个链接是 Gatsby 的教程，仅供参考 https://www.gatsbyjs.org/tutorial/

目前个人仅是将 VuePress 的文档通读了一番，了解尚浅，若表达有失准确，还请见谅。

#### Are you willing to work on this yourself?
期望吧，但眼下能力还明显不足。

#### Why don't you just use Gatsby as your blog framework? BTW, it seems that Hexo is better for you.
1. 听很多人都说 Vue.js 的学习曲线比较适合初学者，业界对 Vue.js 的评价也很不错，也想借着 “个人博客” 这样的有目的性的实战项目逐步上手 Vue.js（个人博客有些自定义的特性默认博客模板是不支持的，想一边学一遍开发）。
2. 相比于 React，还是希望能学会 Vue.js，而且学 Hexo 的话确实应该会更容易，但这样似乎也仅仅是又学了一门偏静态的模板标记语法，并不会对自己的技能有太多提升。
3. 之前和朋友合作的开源项目 [RemixIcon](https://remixicon.com) 也是以 Vue.js 作为技术栈的，也想学会后能在开发层面帮朋友分担更多，加快版本迭代。 

最后感谢尤大和其他小伙伴的维护和付出，辛苦了，期待您的回复。

**Comment by Mister-Hope** [comment]
Personal idea: The docs does not fit new comers, that's true, but I think this project focus on docing projects, and is facing those who know front-end development.

To let vuepress work, you should install node, git. And that means  they should learn about it. It's not like vue, which can be imported through a script label.

> 只懂` Html/CSS 和一点 JS 的用户

I don't think placeing some related tutorial or adding a new get started for them is necessary.

If they do want to use, they should learn git, install node, getting a github account and use theme like vuepress-theme-reco and vuepress-theme-hope. And then using a workflow to deploy.

**Comment by xiaochunjimmy** [comment]
@Mister-Hope 

Thank you for your info and advice.

I think I've familiar with the front-end development, such as deploy a node.js based environment, git, run projects natively, etc.

Exactly, VuePress is designed for document projects, and [blog] is just a use-case of this project.

My point is that I think Vuepress is aimed at users who are already familiar with Vue.js, but it can be aimed at every developer with more detailed development documentation as **an independent product**.

The documentation for the installation, deployment, config, using section is fairly complete, but the develop-theme section seems to be less complete in my opinion:
> From there it’s the same as developing a normal Vue application. It’s entirely up to you how to organize your theme. (*quoted from [Writing a theme](https://vuepress.vuejs.org/theme/writing-a-theme.html))

Hmmm... maybe I just should have known some basic Vue.js knowledge before getting started with VuePress, but I wish there could be a theme development-driven learning route.

I really appreciate your reply and explanation, Hope.

**Comment by Mister-Hope** [comment]
To be honest, I don't think vuepress can be a product. Now no one is maintaining it. At least for me, I have 11 pending PR on this repo. I am rewriting it and improving it with typescript [See hopepress](https://github.com/hopepress/hopepress/) and I was working on it to develop [my theme](https://vuepress-theme.mrhope.site). The deeper I dig, the more weakness I find about vuepress.

It has much more issues than it looks like. Just an example, the building method of vuepress, the plugin system, is swallowing too much memory while building, [See #2241 ](https://github.com/vuejs/vuepress/issues/2241)

So I am totally disagree thinking it the same as Wordpress or HEXO. It's just a doc generator, with vue support.

**Comment by xiaochunjimmy** [comment]
(⊙o⊙)… Thank you...
So... There may be many problems or issues that I can not resolve if I continue to learn VuePress, considering my technological level.
