### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by LiuduZero** [vuejs/vuepress#2378]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
![image](https://user-images.githubusercontent.com/24452177/81251153-38ee9080-9055-11ea-9afb-72fdcae51bb6.png)
![image](https://user-images.githubusercontent.com/24452177/81251154-39872700-9055-11ea-98b9-f1e5cd4affb7.png)

#### What is expected?
build successful

#### What is actually happening?
build failed and what happend in terminal above

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
See: https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions
