### ISSUE TITLE
vuepress/plugin-pwa slow loading first time

### ISSUE THREAD

**Issue by juukee** [vuejs/vuepress#2385]
- [x] I confirm that this is an issue rather than a question.

## Bug report
my pwa config like this:
plugins: ['@vuepress/pwa', {
      serviceWorker: true,
      updatePopup: true
  }],
verry slow loading first time,need i add other pwa config option?

#### What is expected?
 I don't know how to set it can improve the loding speed first time.
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by Mister-Hope** [comment]
A service worker's job to cache all the files for you, so when you run for the first time, it started to download every css.js,html files after registing itself, so a lot of request will be queued,

If you navigate to a new page at that time, it definitely get stuck. It's something like feature or behavior.

**Comment by Mister-Hope** [comment]
If you do want some improvement, I do not have a good idea. Maybe forking this project, then make a own version of the pwa plugin by adding a delay with `setTimeout` before registing service worker will make a little help, by it will still stuck the page when navigating during the first registion..
