### ISSUE TITLE
Hot update failed and got error

### ISSUE THREAD

**Issue by JerryYuanJ** [vuejs/vuepress#2400]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Just follow the site guidance: create a folder, install vuepress, starting...

#### What is expected?

No errors when hot updated.

#### What is actually happening?

Hot update failed when I change a file and got errors.

#### Other relevant information

versions:

My OS is Mac OS v10.14.6, node version v12.16.3, vuepress version is ^1.5.0.

errors:

![image](https://user-images.githubusercontent.com/26586458/82724453-ef669c80-9d08-11ea-9716-8918394c2ec9.png)

- Output of `npx vuepress info` in my VuePress project:

**Comment by maxcareer** [comment]
me too

**Comment by JerryYuanJ** [comment]
Interesting is, I check the` @vuepress/code/.temp/` folder and those files are there, I don't know why it says `no such file or directory`

**Comment by kurotanshi** [comment]
I have the same problem

**Comment by bencodezen** [comment]
Thanks for filing this issue. It looks like there's a similar issue filed with #2392, so we'll close this one to track everything in that issue.
