### ISSUE TITLE
开发时.md文件内容的改变未触发热更新

### ISSUE THREAD

**Issue by knight084** [vuejs/vuepress#2414]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?
开发时修改/docs目录下的.md文件后触发热更新

#### What is actually happening?
开发时修改/docs目录下的.md文件未触发热更新，但修改/docs/.vuepress/config.js文件的内容会触发热更新

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

Environment Info:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Edge: Not Found
    Firefox: 70.0.1
    Safari: 12.1.2
  npmPackages:
    @vuepress/core:  1.5.0
    @vuepress/theme-default:  1.5.0
    vuepress: ^1.5.0 => 1.5.0
  npmGlobalPackages:
    vuepress: Not Found

**Comment by xwbxwb** [comment]
我也遇到了这个问题

**Comment by Wobugaosuni** [comment]
same problem i had met

**Comment by Wobugaosuni** [comment]
this work: https://github.com/vuejs/vuepress/issues/2392#issuecomment-633399465

**Comment by hopefuture** [comment]
确实有这个问题，是 bug 吗

**Comment by imLiukai** [comment]
我也遇到了同样的问题

**Comment by zsqzsq1993** [comment]
this works for me: 
```
npm i -D watchpack@1.6.1
```

**Comment by knight084** [comment]
> this work: [#2392 (comment)](https://github.com/vuejs/vuepress/issues/2392#issuecomment-633399465)
是的 安装开发依赖 watchpack
