### ISSUE TITLE
Accessing content of all pages

### ISSUE THREAD

**Issue by svenewers** [vuejs/vuepress#242]
I'm trying to use Vuepress as a simplified blogging system and was wondering how (if at all) I could get access to the `<Content/>` of every page of my site?    
I essentially want to just put the rendered markdown of every article I have on the index page and so far have not found a way to access that data in any convenient way.  
What I'm trying to accomplish would perhaps look something like this in a component's template:
  
```
<div class="page-wrapper">
    <div class="post" v-for="page in $site.pages">
        <Content/>
    </div>
</div>
```

Is there any way to get to this kind of data or am I just out of luck here?

**Comment by yyx990803** [comment]
With the latest version:

1. Add a `<!-- more -->` marker in each post to indicate the excerpt point.

2. Content above `<!-- more -->` will be available as `page.excerpt`.

Not including all content by default because that would bloat the size of the initial JavaScript bundle.

**Comment by tdurieux** [comment]
But page.excerpt is not rebdered,  how can I  render it to html?
