### ISSUE TITLE
如果在 md 里面写了vue 会导致路由 F5刷新失败

### ISSUE THREAD

**Issue by mayunhai** [vuejs/vuepress#2422]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?
[test link](https://mayunhai.github.io/mayunhai/blog/CSS.html#css-%E5%8D%81%E4%B8%AA%E7%81%B5%E6%B4%BB%E8%BF%90%E7%94%A8%E5%B0%8F%E6%8A%80%E5%B7%A7)
#### What is actually happening?
路由失败
#### Other relevant information
项目地址 https://github.com//mayunhai/mayunhai
- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
Please fill `Steps to reproduce`.
