### ISSUE TITLE
npm run dev is slow very much, when "additionalPages" option is large

### ISSUE THREAD

**Issue by wannamakeudance** [vuejs/vuepress#2440]
- [x] I confirm that this is an issue rather than a question.

## Bug report
if  the array of "additionalPages" is a large value(for example 1.5k),  npm run dev is slow very much.
#### Steps to reproduce
additionalPages is a array whose length is 1.5k.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1
  npmPackages:
    @vuepress/core:  1.5.0 
    @vuepress/theme-default:  1.5.0 
    vuepress: ^1.2.0 => 1.5.0 
  npmGlobalPackages:
    vuepress: Not Found

**Comment by ulivz** [comment]
> if the array of "additionalPages" is a large value(for example 1.5k)

You'd at least provide a minimal repro and related slow build time data to prove that this is an issue.
