### ISSUE TITLE
Feature Request: Highlight current region in sidebar

### ISSUE THREAD

**Issue by octref** [vuejs/vuepress#245]
This is a great feature I miss from gitbook. It's also on vuejs.org.

Example: try to scroll in this page: https://vue-loader.vuejs.org/guide/pre-processors.html. No updates on sidebar.

![image](https://user-images.githubusercontent.com/4033249/39215139-b2e2ceee-47cb-11e8-97e3-6c6e8a0e1941.png)

**Comment by ryanriv** [comment]
I'd love to grab this one 😄.

**Comment by ryanriv** [comment]
Do you have any suggestions for where this should live? I was thinking about using a scroll event in Layout.vue to change the active class. It would be similar to the approach that vuejs.org uses.

**Comment by yyx990803** [comment]
@ryanriv yeah, it can probably live in `Layout.vue`. Although don't use direct DOM manipulation - you just need to update the hash and the classes will update automatically.

**Comment by ulivz** [comment]
It would be better to add `throttle` control for the scroll event.

**Comment by ulivz** [comment]
@ryanriv Thanks for the great work again. code merged!
