### ISSUE TITLE
Missing examples for highlighting range of Lines in code blocks

### ISSUE THREAD

**Issue by billyyyyy3320** [vuejs/vuepress#2473]
## Feature request

[Line Highlighting in Code Blocks](http://localhost:8080/guide/markdown.html#line-highlighting-in-code-blocks)
<img width="964" alt="Screen Shot 2020-07-01 at 00 07 59" src="https://user-images.githubusercontent.com/38957202/86149824-15186a00-bb2f-11ea-8035-d812d8f35306.png">

There's only one example for this section.

However, it supports highlighting a range of lines, and even multiple ranges of lines!

In addition, import code highlighting works in the same way #2441

#### How should this be implemented in your opinion?

 Add more description for this feature. Provide examples for highlighting a range of lines and multiple ranges of lines.

#### Are you willing to work on this yourself?
Yep, but still it's Contribution Welcome!

**Comment by diogotcorreia** [comment]
I don't mind making a PR for this later this week 😃

**Comment by billyyyyy3320** [comment]
@diogotcorreia Great! Welcome!
