### ISSUE TITLE
Vuepress use the theme @vuepress/theme-default, click the drop-down title, then click elsewhere on the page, the drop-down list always show.

### ISSUE THREAD

**Issue by liulinboyi** [vuejs/vuepress#2492]
Vuepress use the theme [@vuepress/theme-default](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/theme-default), click the drop-down title, then click elsewhere on the page, the drop-down list always show.
I found this in [vuejs/docs-next](https://github.com/vuejs/docs-next), can't fix it on [vuejs/docs-next](https://github.com/vuejs/docs-next),
The issue is https://github.com/vuejs/docs-next/issues/244

**Comment by kefranabg** [comment]
This will be fixed with https://github.com/vuejs/vuepress/pull/2365
