### ISSUE TITLE
Add comments function?

### ISSUE THREAD

**Issue by zaiqiang-dong** [vuejs/vuepress#2518]
Will comments function be added in the near future？

**Comment by WowItsDoge** [comment]
There is already a component which offers the functionality to write comments.

[Vssue](https://vssue.js.org/)

**Comment by zaiqiang-dong** [comment]
Thanks, vuepress will perfect whth a comment function.

**Comment by billyyyyy3320** [comment]
With the plugin system, we want to leave such additional feature to plugin. In this case, we won't add it to the core of VuePress. 

There're many comment related vuepress plugin out there. e.g. [vuepress-plugin-disqus](https://github.com/lorisleiva/vuepress-plugin-disqus)
