### ISSUE TITLE
Docs without a server 

### ISSUE THREAD

**Issue by jrYeole** [vuejs/vuepress#255]
i have generated the dist, is it possible to run the files without a http server (nginx or apache). ?

**Comment by ulivz** [comment]
Unnecessary to be so complex, just use `python`:

```bash
cd [DIST_DIR]
python -m SimpleHTTPServer 4000
```

Then open `http://localhost:4000/`

**Comment by jrYeole** [comment]
without python also. just for normal users who can directly click on html file and its running.

Am talking about the dist

**Comment by jrYeole** [comment]
@ulivz

**Comment by yyx990803** [comment]
No.

**Comment by ulivz** [comment]
Duplicate of #575

See: https://github.com/vuejs/vuepress/issues/575#issuecomment-412420421
