### ISSUE TITLE
Internationalization/locales but for programming languages

### ISSUE THREAD

**Issue by pedr0-fr** [vuejs/vuepress#2552]
## Feature request

I am writing documentation for an API and I provide a lot of python code examples of how to integrate the API. In the future, I would like to create different versions of the same tutorials with the SAME English text but code blocks in a different programming language. The best solution right now would be to use internationalization (https://v1.vuepress.vuejs.org/guide/i18n.html#site-level-i18n-config) with a "locale" for each programming language. The problem with this approach is that the English text will be duplicated many times and will be much harder to change. I can divide my articles into English text components and then write the new article versions with these components and typing the new code blocks. This seems like a lot of work and therefore this feature request.

#### What problem does this feature solve?
It avoids having a lot of duplicate English text across different articles, each for a different programming language. 
#### What does the proposed API look like?
Similar to internationalization/locales but only the code blocks in the new language need to be specified.
#### How should this be implemented in your opinion?
A special type of locales.
#### Are you willing to work on this yourself?
No, I am not good at javascript/Vue.

**Comment by dtinth** [comment]
As Vuepress lets you use [create custom Vue components](https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions), you can create a widget that lets user select a preferred programming language.

Then you can create a widget that works like [how Google Cloud docs did it](https://cloud.google.com/storage/docs/downloading-objects#storage-download-object-ruby):

![image](https://user-images.githubusercontent.com/193136/89222736-bd729000-d5ff-11ea-81a2-2befd251489c.png)

Would this be a viable solution?

**Comment by pedr0-fr** [comment]
Yes, that would solve... but I think I would be reinventing the wheel... I will try to find an open-source version of this that is compatible with Vue.

**Comment by pedr0-fr** [comment]
fixed with https://superbiger.github.io/vuepress-plugin-tabs/
