### ISSUE TITLE
How to implement update tips

### ISSUE THREAD

**Issue by juzi214032** [vuejs/vuepress#2556]
## Feature request
![image](https://user-images.githubusercontent.com/38206169/89488345-552bd600-d7da-11ea-962f-910a8f5a041c.png)

**I've noticed that the vuepress website has a prompt when content is updated, and I'd like to know how to turn it on.**

**Comment by bencodezen** [comment]
Hi @juzi214032! You can learn more about it here: https://vuepress.vuejs.org/plugin/official/plugin-pwa.html#options

Hope this helps!

**Comment by juzi214032** [comment]
thanks!
