### ISSUE TITLE
Pages on basis of content type 

### ISSUE THREAD

**Issue by muke5hy** [vuejs/vuepress#2559]
Hi, 
I tried Vuepress by default I got blog section which shows on the home page. But I am not able to figure out how I can have content with different types
e.g.   
1. Blog -> This will have multiple pages and will reside on /blog URL.
2. Tutorial -> This will have multiple pages and subpages and can have /tutorial/python/intro-python 
3. Few other pages and they will have their own contents. 

Currently, I see _post in main directory and I add blog/_post or tutorial/_post VuePress doesn't work. 

Is this type of site possible in VuePress?

**Comment by billyyyyy3320** [comment]
Please read the [Theme](https://vuepress.vuejs.org/theme/) section.

The default theme is a documentation site, and [here](https://github.com/vuepressjs/vuepress-theme-blog) is the official blog theme.
