### ISSUE TITLE
Add an external code in markdown

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#256]
Since I can add an external code such as codepen or jsfiddle in the markdown look in the documentation but I did not find it very much thanks.

**Comment by ulivz** [comment]
Codepen support sharing as a embed iframe:

![image](https://user-images.githubusercontent.com/23133919/39252981-692b6950-48d9-11e8-8871-c0a950c74ec1.png)

I just tested for it. it works for now.

If you just want to demo Vue code with markdown, you can [using vue at markdown](https://vuepress.vuejs.org/guide/using-vue.html#using-components) instead.

**Comment by luisDanielRoviraContreras** [comment]
Sorry for the inconvenience you could show me the code to add the iframe in the markdown

**Comment by yyx990803** [comment]
Just... use an iframe? Look for it in Codepen's docs?

**Comment by ulivz** [comment]
no matter, I forget to give your the test iframe code:

```html
<iframe height='265' scrolling='no' title='OZXQWp' src='//codepen.io/ulivz/embed/OZXQWp/?height=265&theme-id=0&default-tab=html,result&embed-version=2' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'>See the Pen <a href='https://codepen.io/ulivz/pen/OZXQWp/'>OZXQWp</a> by ULIVZ (<a href='https://codepen.io/ulivz'>@ulivz</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
```

You can find the embed button at the right bottom side.
