### ISSUE TITLE
The built-in search box cannot search 内置搜索框无法搜索,  版本是 "vuepress": "^1.5.2"

### ISSUE THREAD

**Issue by web-ljy** [vuejs/vuepress#2563]
首次安装使用，默认内置的搜索框无法使用，搜索不到任何内容。

其次尝试着按照官网文档的搜索插件使用配置也不能搜索，没有反应。

主干:
https://github.com/web-ljy/vuepressBlog/tree/master

gh-pages:
https://github.com/web-ljy/vuepressBlog/tree/gh-pages

有时间的可以帮看看问题，谢谢!

**Comment by SigureMo** [comment]
请仔细[阅读文档](https://v1.vuepress.vuejs.org/zh/theme/default-theme-config.html#%E5%86%85%E7%BD%AE%E6%90%9C%E7%B4%A2)，内置搜索仅针对标题进行搜索，而你的文档里面没有任何标题

不建议在 Issue 里提 Problem，同时也不建议在这里使用中文提问，建议 Close
