### ISSUE TITLE
Rendering Markdown inside components

### ISSUE THREAD

**Issue by faustbrian** [vuejs/vuepress#257]
Just started using Vuepress and having a blast, much nicer to use then Jekyll but been wondering if it is possible to render markdown inside a vue component without any extra packages.

```html
<template>
    <div>
        ### Headline

        ```bash
        // some code
        ```
    </div>
</template>
```

**Comment by ulivz** [comment]
All markdown file will be first compiled into HTML, passed on as a Vue component to `vue-loader`,  so you can use write markdown at the vue component.

But the single Vue component will be only compiled by `vue-loader`. so you cannot directly write markdown at a Vue component at what you described above.

But, Here is a workaround by using `<slot>` 😅:

1. Create a component at `docs/.vuepress/components`, such as `MarkdownInVue.vue`:

```vue
<template>
  <div>
    <slot></slot>
  </div>
</template>
```

2. Using this component at your markdown:

```md
<MarkdownInVue>

  ### Headline

  ```bash
  // some code
  ```

</MarkdownInVue>
```

> Attention: **Please don't forget these two blank line**s, one is after open tag, and another one is before the close tag.

Refer to: #205

**Comment by faustbrian** [comment]
Thanks, will test that.

**Comment by f3l1x** [comment]
Hi, maybe quite similar question. I have markdown in my json file. Is there any way how to render it?

**Comment by avishnyakov** [comment]
Same here.

Tried `MarkdownInVue.vue` based solution, couldn't make it work. The use case is to render C#, JS, XML and PowerShell source code within a custom Vue component. The source code is not stored within markdown but dynamically loaded from other data sources.

**Comment by ulivz** [comment]
@avishnyakov You can create a new issue for that, otherwise it will be hard for us to see it.

**Comment by avishnyakov** [comment]
@ulivz it's nearly working, my bad. Markdown gets passed perfectly but here is a wonder:

Somewhere in /data/samples.json
```
{
    "samples": [
        {
            "title":"sample1",
            "description": "descriptoin 1",
            "code": "var i = 10;"
        },
         {
            "title":"sample2",
            "description": "descriptoin 2",
            "code": "var i = 1;"
        }
    ] 
}
```

Then your solution with custom Vue component. Passes markdown perfectly. However, not sure how to pass dynamic data in this case as the markdown content seems to be ignoring Vue expressions.
```
<div v-for="(item, index) in this.$site.themeConfig.samples">
  {{ item.title }}

<Markdown>

  """cs
  {{ item.code }}
  """

</Markdown>

</div>
```

Output:
```
sample1
{{ item.code }}

sample2
{{ item.code }}
```

**Comment by doostinharrell** [comment]
I just ran into this issue on a Vuepress 2 website I'm developing.  Because Vuepress 2 runs on Vue 3 the solutions noted in this issue didn't solve my problem.  Below is a simple component I wrote that solved the issue.  Hopefully it helps someone else!

```
<template>
  <div class="text-formatted" v-html="renderedMarkdown" />
</template>

<script>
import markdownIt from 'markdown-it';

export default {
  name: 'ui-markdown',

  props: {
    markdown: {
      type: String,
      required: true,
    },
  },

  setup(props) {
    let md = new markdownIt({ html: true }),
        renderedMarkdown = md.render(props.markdown)

    return {
      renderedMarkdown,
    }
  },
}
</script>
```

**Comment by mihaiconstantin** [comment]
I was looking for a way to reuse chunks of `markdown` throughout my documentation. I've settled for the time being the following.

I have a component `Markdown.vue` responsible for rendering `text` to `markdown` via `markdown-it`.

```vue
<script>
import { h } from "vue";
import markdownIt from "markdown-it";

export default {
    props: {
        text: {
            type: String,
            required: true
        }
    },

    render() {
        // Create markdown renderer engine.
        let renderer = new markdownIt({ html: true });

        // Render the component template.
        return h(
            "div",
            {
                // Add class for our own reference.
                class: "user-rendered-markdown",

                // Convert the text to markdown.
                innerHTML: renderer.render(this.text)
            }
        );
    }
}
</script>
```

Then in another component, say `Reusable.vue` I have:

```vue
<template>
    <Markdown text="

# Heading

|   a   |   b   |
| :---: | :---: |
|   1   |   2   |

Some paragraph.

A list:
- item one
- item two

    "/>
</template>
```

Throughout my documentation pages, I now call `<Reusable/>` in plain `markdown` whenever I want to render its contents, e.g.,

```html
<!-- Contents of `page.md`. -->

Before.

<Reusable/>

After.
```

which will result in:

<img width="422" src="https://user-images.githubusercontent.com/20051042/188412678-b5b6596a-2a26-4314-ad0c-369e5d21b28d.png">

Note that the ugly lack of indentation of the `markdown` text seems necessary. If anyone knows a better way, I'd greatly appreciate any input.
