### ISSUE TITLE
依赖的core-js不一致导致的冲突  @vue/cli-service

### ISSUE THREAD

**Issue by Javison666** [vuejs/vuepress#2578]
在和vue-cli + element2.13.2结合的环境中，core-js版本冲突导致不能结合
vuepress的1.5.2版本依赖2.6.5
@vue/cli-service 4.5.0版本依赖的core-js版本为最新的3.6.5

**Comment by showmethecode9527** [comment]
[https://github.com/vuejs/vuepress/issues/2275](https://github.com/vuejs/vuepress/issues/2275)
