### ISSUE TITLE
Any "<anything>" in markdown will make the content disapear.

### ISSUE THREAD

**Issue by bobyuancn** [vuejs/vuepress#2597]
- [x] I confirm that this is an issue rather than a question.

## Bug report
If markdown file has any tag like <anything> in it, the content will all go blank.

#### Steps to reproduce

1. Create a markdown file as below, run "vuepress dev" and open a browser to view the web page.
```markdown
# Hello VuePress!
```

2. Update the markdown file, add any tag like "<anything>" in the end, press F5 in browser to refresh.
```markdown
# Hello VuePress!
This tag below will make the content disappear! 
<anything>
```

#### What is expected?
I am expecting the web page can show "<anything>" correctly in text.

#### What is actually happening?
All web page will go blank.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by billyyyyy3320** [comment]
`<anything>` is transpiled as a Vue component. 

https://vuepress.vuejs.org/guide/using-vue.html#using-components

> The HTML wrapped by <code> will be displayed as-is; only the HTML that is not wrapped will be parsed by Vue.
