### ISSUE TITLE
Inform screen reader users if a link will open in a new tab

### ISSUE THREAD

**Issue by ktquez** [vuejs/vuepress#2601]
#### What problem does this feature solve?
Inform screen reader users in advance if the link will **open in a new tab**.

https://www.w3.org/WAI/WCAG21/Techniques/general/G201
https://webaim.org/techniques/hypertext/hypertext_links#new_window

#### How should this be implemented in your opinion?
Text customized by locales: `$themeLocaleConfig.openNewWindowText`

#### Are you willing to work on this yourself?
Yes

**Comment by d-pollard** [comment]
@ktquez - so since we already have the outbound link indicator, would you just want us to add the alt text of the users specification (via `$themeLocaleConfig.openNewWindowText`) ?

**Comment by d-pollard** [comment]
@ktquez - this PR should address this issue

https://github.com/vuejs/vuepress/pull/2603

**Comment by ktquez** [comment]
Awesome! @d-pollard 
I added a comment there.

**Comment by d-pollard** [comment]
@ktquez  - I don't see the comment, mind re-commenting on the PR for me?

**Comment by ktquez** [comment]
Sorry @d-pollard 
Done.
