### ISSUE TITLE
Tencent CloudBase 部署页面显示异常

### ISSUE THREAD

**Issue by JackyAndroid** [vuejs/vuepress#2609]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
在不同网站部署页面展示不同。
目前已知在github page展示无异常，但在其他提供类似服务，如 coding、腾讯cloudBase等都显示异常

#### What is actually happening?
CloudBase异常：https://interview-q-a-1gdnkgkla15afdbe-1258598664.tcloudbaseapp.com/
github page正常：https://jackyandroid.github.io/AndroidInterview-Q-A/

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: Not Found
    Safari: 13.1.1
  npmPackages:
    @vuepress/core:  1.5.4
    @vuepress/theme-default:  1.5.4
    vuepress: 1.5.4 => 1.5.4
  npmGlobalPackages:
    vuepress: 0.14.2

**Comment by JackyAndroid** [comment]
补充：本地server run 正常

**Comment by tolking** [comment]
你应该部署有问题。配置了网站的[子路径](https://vuepress.vuejs.org/config/#base) `AndroidInterview-Q-A`，正确链接应该是 [https://interview-q-a-1gdnkgkla15afdbe-1258598664.tcloudbaseapp.com/AndroidInterview-Q-A/](https://interview-q-a-1gdnkgkla15afdbe-1258598664.tcloudbaseapp.com/AndroidInterview-Q-A/)。或许你应该尝试将网页至于 AndroidInterview-Q-A 文件夹下访问上面地址。或者移除base配置后才能够部署到根目录
