### ISSUE TITLE
The search box is not working

### ISSUE THREAD

**Issue by zq99299** [vuejs/vuepress#2610]
- [ x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- repo link：https://github.com/zq99299/note-book
- static website：https://zq99299.github.io/note-book

and also

-  repo link：https://github.com/zq99299/dsalg-tutorial
-  static website：https://zq99299.github.io/dsalg-tutorial

1. yarn install
2. yarn docs:dev  or docs:build

#### What is expected?
Search box can display search results correctly

搜索框能正确显示搜索结果

#### What is actually happening?
There are no search results in the search box, whether the physical search is in Chinese or English, there is no

搜索框不能显示结果，中文或则英文都不显示搜索结果

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```
$ npx vuepress info

Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 14.10.1 - D:\ProgramFiles\node\nodejs\node.EXE
    Yarn: 1.9.4 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - D:\ProgramFiles\node\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)
  npmPackages:
    @vuepress/core:  1.5.4
    @vuepress/theme-default:  1.5.4
    vuepress: ^1.5.4 => 1.5.4
  npmGlobalPackages:
    vuepress: Not Found
```
Chrome unusual，Edge normal

vuepress Version 1.4.1 is normal, it should be abnormal from version 1.5.0

vuepress 版本 1.4.1 是正常的，应该问题从 1.5.0 开始就不正常了

**Comment by billyyyyy3320** [comment]
've Visited your website. It works.

**Comment by zq99299** [comment]
Thanks Reply.
I changed a computer for testing, and finally found the problem:
1. Removed node_modules and yarn.lock
2. Re-yarn install
3. yarn docs:dev
It is normal when found.

--------------------------

感谢回复。
我换了一台电脑进行了测试，最后找到了问题：
1. 删除了 node_modules 和 yarn.lock 
2. 重新 yarn install
3. yarn docs:dev
发现就正常了。对于 github.io 上的静态网站，可能由于是我本地缓存缘故，导致的。
