### ISSUE TITLE
Help formatting data being read from json

### ISSUE THREAD

**Issue by anthonypiccolo** [vuejs/vuepress#2625]
So this example of a numbermodifier component works fine;

```
Component:
<template>
  <div class="number-modifier">
    <button @click="increment()">+</button>
    <strong> {{value}} </strong>
    <button @click="decrement()">-</button>
  </div>
</template>

<script>
export default {
  props: ['start'],

  // We have to copy the value because we can't use v-model with
  // nothing to bind to.
  // (VuePress doesn't have support for reactive page variables at the moment.)
  data() {
    return {
      value: this.start
    }
  },

  methods: {
    increment() { this.value++ },
    decrement() { this.value-- }
  }
}
</script>
```

Calling on it in `md`:
`<numbermodifier :start="5"></numbermodifier>`

Doesn’t work for;
```
<div v-for="i in items">
    <h2>{{i.Home_Neutral}} - {{i.Visitor_Neutral}}</h2>
    <p>{{ i.Date }}</p>
</div>

<script>
import data from './data.json'
export default {
  data () {
      return {
          items: data.data
      }
  }
}
</script> 
```

Calling on it with;
`<nba_matches></nba_matches>`

The data in the `json` is simply;

```
[
  {
    "Home_Neutral": "Miami Heat",
    "Visitor_Neutral": "Boston Celtics",
    "Date": "2020-09-23 00:00:00 UTC",
    "ATS": "1.54"
  }
]
```

**Comment by d-pollard** [comment]
Hi @anthonypiccolo - I'm not sure I understand what's happening here, would you mind sharing a codepen or github project URL so I can see it first hand?

**Comment by anthonypiccolo** [comment]
It's all good, I was able to figure out what was wrong. It was because of where the `data.json` was sitting in the folder structure. Changing to the below fixed it;

`import data from '../../data.json'`

I'm interested to know about formatting though.

I'm trying to create a layout/grid system as per this; https://bootstrap-vue.org/docs/components/layout

I would have thought the below would work but it doesn't seem to work and lay the data out nicely;

```
<template>
<div>
    <div v-for="i in items">
    <b-container class="bv-example-row">
    <b-row>
    <b-col>Home</b-col>
    <b-col>Road</b-col>
    <b-col>Home ATS</b-col>
    <div class="w-500"></div>
    <b-col>{{i.Home_Neutral}}</b-col>
    <b-col>{{i.Visitor_Neutral}}</b-col>
    <b-col>{{i.ATS}}</b-col>
  </b-row>
</b-container>
    </div>
</div>
</template>
```

And this just shows up on the page like so;

![image](https://user-images.githubusercontent.com/3188611/95293497-3e2f6000-08bf-11eb-994e-96003f0c250c.png)
