### ISSUE TITLE
code-group components cannot render properly in some cases.

### ISSUE THREAD

**Issue by liyuj** [vuejs/vuepress#2641]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/9244802/95007852-ec7ca080-0646-11eb-81f1-b0d35f109332.png)

#### What is expected?

Normal rendering can be done

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by d-pollard** [comment]
Hello liyujue,

Looks like you're trying to render an unsupported format inside of the code block. Make sure to wrap the content in ```'s

**Comment by liyuj** [comment]
Hi Derek,

I think as a built-in component, if the component can only contain code 
blocks, it will seriously limit the scope of use of this component. I 
think any valid markdown statement should be legal.

 From the perspective of generality, the name of this component is more 
appropriate to be called tabs > tab, rather than code-group > code-block.

在 2020/10/13 上午5:28, Derek Pollard 写道:
