### ISSUE TITLE
Easy as 1， 2，2 ？？

### ISSUE THREAD

**Issue by angsheng** [vuejs/vuepress#265]
OK , i follow this

"As Easy as 1, 2, 3

# install
yarn global add vuepress # OR npm install -g vuepress

# create a markdown file
echo '# Hello VuePress' > README.md

# start writing
vuepress dev

# build to static files
vuepress build
"
(from  https://vuepress.vuejs.org/ )

and  before the CLI prinited  line words , i got a "README.md" file !   
it is really cool ! 
isn't it ?!!
what  the meaning is  i have done ??
would you  have some human language to write a user document ??

**Comment by yyx990803** [comment]
Maybe you can familiarize yourself with English, basic terminal commands and some developer common sense before trying to use a tool that is targeting developers?
