### ISSUE TITLE
$site.pages summary contains invalid markdown

### ISSUE THREAD

**Issue by maxigimenez** [vuejs/vuepress#2657]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

The summary provided on `this.$site.pages` can contain a broken markdown. 

We are facing this issue on https://theheadless.dev when the summary is trimmed based on the configured characters there could be scenarios where the markdow is not valid anymore (please check the image attached).

In our case, we are setting a max length of 120 characters (`summaryLength` config), and the text of the image above is:

```
The [HyperText Transfer Protocol (HTTP)](https://developer.mozilla.org/en-US/docs/Web/HTTP#:~:text=Hypertext%20Transfer%20Protocol%20(HTTP)%20is,be%20used%20for%20other%20purposes.) is stateless, but cookies allow it to keep context consistent over the course of a session. In other words, by having our browser automatically exchange small amounts of data, we get to have websites recognise us and remember our preferences, the contents of our shopping baskets or the fact that we had just logged in to our account.
```

BTW this is a public repo, so feel free to check the configuration here https://github.com/checkly/theheadless.dev

#### What is expected?

Option A) before trimming, remove the markdown from the summary
Option B) trim the text without counting markdown characters, so it ensures that is always valid.

#### What is actually happening?

As attached below, the markdown is invalid so it looks weird.

#### Other relevant information

<img width="434" alt="Screenshot 2020-10-12 at 12 21 10" src="https://user-images.githubusercontent.com/1178139/95738783-13138a80-0c8a-11eb-9a0d-af6a7ddc2289.png">

**Comment by d-pollard** [comment]
Hello @maxigimenez !

This seems to look like and API you guys have augmented your theme with here: https://github.com/checkly/theheadless.dev/blob/master/blog/.vuepress/theme/index.js#L6

I suspect the issue here might be with `remove-markdown`, but since I personally haven't implemented this, this is just an educated guess

**Comment by d-pollard** [comment]
<img width="888" alt="Screen Shot 2020-10-12 at 4 36 37 PM" src="https://user-images.githubusercontent.com/16292606/95792455-2550f100-0ca9-11eb-885c-5899ccf9bc3b.png">
 
Have confirmed, is an issue with `remove-markdown`

**Comment by maxigimenez** [comment]
Thank you @d-pollard! Wasn't aware of that file in our configuration.

**Comment by d-pollard** [comment]
No problem! Am interested in how you guys fix it, feel free to update and tag me here @maxigimenez
