### ISSUE TITLE
New `canonicalUrl` frontmatter property is incorrectly mapped in `ClientComputedMixin.js`

### ISSUE THREAD

**Issue by adamdehaven** [vuejs/vuepress#2665]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?

Canonical Url is grabbed from the `canonicalUrl` entry in the `frontmatter`

#### What is actually happening?

The canonical URL is not being injected into the SSR template because in PR #2658 the frontmatter entry was renamed (during development) **to** `canonicalUrl` **from** `canonical`. 

Line `69` in `packages/@vuepress/core/lib/node/ClientComputedMixin.js` is looking for a non-existent property called `canonical` and needs to be updated to the following:

``` js
const { canonicalUrl } = this.$page.frontmatter
```

Tagging @d-pollard

**Comment by d-pollard** [comment]
Would you want to submit a PR for this? @adamdehaven
