### ISSUE TITLE
 Cannot read property 'interval' of undefined

### ISSUE THREAD

**Issue by raisty** [vuejs/vuepress#2668]
- [ x ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

After building the website it appears, that it breaks with pagination.

Getting error:
```
wait Rendering static HTML...
[Vue warn]: Error in render: "TypeError: Cannot read property 'interval' of undefined"

found in

---> <BaseListLayout>
       <Anonymous>
         <GlobalLayout>
           <Anonymous>
             <Root>
error Error rendering /anime/1/: false
undefined
```
For the first article.

More here: https://uwaylu.github.io/blog/2020/02/24/hello-blog/

#### What is expected?

`yarn build` without issues

#### What is actually happening?

Project cannot be built.

#### Other relevant information

One workaround can be found here https://www.gitmemory.com/issue/ulivz/vuepress-plugin-blog/1/504744139
But unfortunately not solving the issue.

- Output of `npx vuepress info` in my VuePress project:

```
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v11.13.0/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 81.0
    Safari: Not Found
  npmPackages:
    @vuepress/core:  1.6.0 
    @vuepress/theme-default:  1.6.0 
    vuepress: ^1.6.0 => 1.6.0 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by d-pollard** [comment]
Looks like this is an issue with a plugin

**Comment by nford88** [comment]
Any update on which plugin? I have recently encountered this error, my last commit passed fine 10 weeks ago
