### ISSUE TITLE
Default-theme: Allow to use AlgoliaSearchBox with another theme

### ISSUE THREAD

**Issue by tinchox5** [vuejs/vuepress#267]
**What is it happening?**
Can't use AlgoliaSearchBox in a custom theme because the component is imported in NavBar using `@`:
``` Navbar.vue
import AlgoliaSearchBox from '@AlgoliaSearchBox'
````

**Solution proposed:**
``` Navbar.vue
import AlgoliaSearchBox from './AlgoliaSearchBox'
````
Edit: The problem was because I created a custom theme based on the default-theme. So, I only need to edit the Navbar.vue of my custom theme to solve the problem.

**Comment by yyx990803** [comment]
I don't think I'm understanding your problem.

**Comment by ulivz** [comment]
I don't think I'm understanding your problem too.

BTW, If you just want to use `AlgoliaSearchBox` at your custom theme, you just need:

```
import AlgoliaSearchBox from '@default-theme/AlgoliaSearchBox.vue'
```
