### ISSUE TITLE
when markdown h1~h6 is chinese,report error

### ISSUE THREAD

**Issue by xsmyqf** [vuejs/vuepress#2672]
DOMException: Failed to execute 'querySelector' on 'Document': '#%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%BE%E8%AE%A1%E8%8C%83%E5%BC%8F' is not a valid selector.

it will report error when h1~h6 is chinese,it seems id in html should not be chinese,could it add alphabet prefix when it detect the id is chinese?thank you!

**Comment by d-pollard** [comment]
This seems to be an issue with vue-router; going to need to huddle with them to figure this one out
