### ISSUE TITLE
`yaml` highlight causing error.

### ISSUE THREAD

**Issue by wxsms** [vuejs/vuepress#2680]
- [x] I confirm that this is an issue rather than a question.

## Bug report

code highlight with `yaml` causing an error:

```
app.73b8bd4d.js:8 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

**NOTE that this issue can only happen when a custom domain is given for Github Pages. In my case I was using Cloudflare as the custom domain provider of Github Pages.**

* dev mode locally, no bugs.
* built mode loccally, no bugs.
* github page without custom domain, no bugs.
* github page with custom domain, buglly.

I KNOW that this issue might not have many thing to do with vuepress. But I really hopes someone can help since I've try for lots of searching & trying and none of those can solve my issue.

#### Steps to reproduce

I have a reproduce project: https://github.com/wxsms/vuepress-bug-reproduce

which is dead simple, **no themes, no plugins, latest vuepress version**, with 2 pages in it, one of them is with `yaml` highlighter and causing issue, other one without.

when you visit [https://vuepress-bug-reproduce.wxsm.space/yaml-bug.html](https://vuepress-bug-reproduce.wxsm.space/yaml-bug.html) directly, you can see an error:

![image](https://user-images.githubusercontent.com/5960988/97097835-c465e780-16b0-11eb-8d93-ac2cee64895b.png)

which is causing all js functionality failed on that page, including navigations.

when you visit [https://vuepress-bug-reproduce.wxsm.space/yaml-bug-2.html](https://vuepress-bug-reproduce.wxsm.space/yaml-bug-2.html) directly, there's no error, every thing works fine.

#### What is expected?

both version of pages should thow no error.

#### What is actually happening?

[https://vuepress-bug-reproduce.wxsm.space/yaml-bug.html](https://vuepress-bug-reproduce.wxsm.space/yaml-bug.html) is thowing error.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 1600X Six-Core Processor
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.7.1
    @vuepress/theme-default:  1.7.1
    vuepress: 1.7.1 => 1.7.1
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by tangweikun** [comment]
@wxsms Hi, Did you fix that finally? I got the same issue on product environment

**Comment by wxsms** [comment]
@tangweikun Yes, I did solved it. It's cause by some domain provider settings. if you read chinese, you can visit my blog post for details: https://wxsm.space/posts/2020-10-25-a-difficult-debug-note.html
