### ISSUE TITLE
site lang not working

### ISSUE THREAD

**Issue by EloFran** [vuejs/vuepress#2683]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
vuepress does not change the language of the site

#### Steps to reproduce

```
module.exports = {
  locales: {
    "/": {
      lang: "es", // this will be set as the lang attribute on <html>
      title: "Mi Título",
      description: "Descripción",
    },
  },
```

#### What is expected?

that modifies the language of the html code to **Spanish**
#### What is actually happening?
![Captura](https://user-images.githubusercontent.com/37640520/97113483-014ed000-16eb-11eb-8037-996ed8bde911.PNG)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vuepress/core:  1.7.1 
    @vuepress/theme-default:  1.7.1 
    vuepress: ^1.5.3 => 1.7.1 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by d-pollard** [comment]
Hmmm, is this viewing source or viewing the inspector? During development, these values aren't added to the DOM via SSR; but bundled for production, they are.
