### ISSUE TITLE
CodeGroup rendering tabs and CodeBlock on hard reload

### ISSUE THREAD

**Issue by ThaNarie** [vuejs/vuepress#2711]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Visit a VuePress docs pages that renders multiple CodeBlocks in a CodeGroup, e.g. https://mubanjs.github.io/muban/guide/#installing

#### What is expected?

The tabs showing up, and the first tab showing highlighted code.

#### What is actually happening?

No tabs showing (although the space is there), and instead a highlighted message:
```js
// Make sure to add code blocks to your code group
```

#### Other relevant information

When navigating to another page and back, the CodeGroup displays correctly.

It seems like it's some kind of re-hydration issue when using the rendered HTML.

It also seems to not happen locally.

- Output of `npx vuepress info` in my VuePress project:
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Not Found
    Firefox: 81.0.2
    Safari: 13.1.2
  npmPackages:
    @vuepress/core:  1.7.1 
    @vuepress/theme-default:  1.7.1 
    vuepress: ^1.7.1 => 1.7.1 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by d-pollard** [comment]
I hope to get to this in the next few days

**Comment by qcyblm** [comment]
[#2686](https://github.com/vuejs/vuepress/issues/2686) to reproduce the problem and get no reply.  
I've solved this problem and need to manually add CodeGroup and CodeBlock to the global component:
```
// .vuepress/enhanceApp.js
import Vue from 'vue'
import CodeBlock from "@theme/global-components/CodeBlock.vue"
import CodeGroup from "@theme/global-components/CodeGroup.vue"
// Register the Vue global component
Vue.component(CodeBlock)
Vue.component(CodeGroup)
```

**Comment by d-pollard** [comment]
I believe I just need to move this component to only be rendered on the client

**Comment by thecoden** [comment]
Hi @d-pollard 
I am experiencing this issue as well, but am not familiar with the best way to move the component to client only. I tried doing something similar to @TimoBechtel fix on the docs, but that is not working for me so I believe the component needs to be modified.

I see the source of the ClientOnly component is:
```js
export default {
  functional: true,
  render (h, { parent, children }) {
    if (parent._isMounted) {
      return children
    } else {
      parent.$once('hook:mounted', () => {
        parent.$forceUpdate()
      })
    }
  }
}
```

I am thinking of editing the CodeGroup component to hook this same functionality in. If you confirm or let me know the best way to fix it, I'm happy to submit a pull request as well.

**Comment by d-pollard** [comment]
I'll take a look at this in the next few days, I appreciate all the feedback!

**Comment by thecoden** [comment]
> I'll take a look at this in the next few days, I appreciate all the feedback!

Thank you @d-pollard. Here to help as you need.

**Comment by d-pollard** [comment]
@thecoden - mind giving this PR a check to ensure it fixes your use-case? https://github.com/vuejs/vuepress/pull/2794

**Comment by d-pollard** [comment]
@qcyblm if you could make sure that PR fixes it for you too, I would greatly appreciate it! https://github.com/vuejs/vuepress/pull/2794

**Comment by d-pollard** [comment]
https://user-images.githubusercontent.com/16292606/107445844-3f8dc500-6b0b-11eb-94a9-60d7744a1eb6.mov

Example of the issue + the fix

**Comment by qcyblm** [comment]
> 
> 
> @qcyblm if you could make sure that PR fixes it for you too, I would greatly appreciate it! #2794

Hello @d-pollard ,Test the site [https://qcyblm.github.io/vuepress-CodeGroup/](https://qcyblm.github.io/vuepress-CodeGroup/), 
Local test, CodeBlock tab can not be displayed.

![VuePress-CodeGroup ](https://user-images.githubusercontent.com/64412486/107462419-0d29a980-6b97-11eb-97c0-893949776dc9.png)

**Comment by d-pollard** [comment]
@qcyblm it looks good for me, it renders the code block

**Comment by d-pollard** [comment]
https://user-images.githubusercontent.com/16292606/107463034-5f34e580-6b2b-11eb-96bf-3fda798d4d65.mp4

@qcyblm it shows this for me

**Comment by d-pollard** [comment]
<img width="1792" alt="Screen Shot 2021-02-09 at 11 12 51 PM" src="https://user-images.githubusercontent.com/16292606/107463571-64defb00-6b2c-11eb-9ccb-53143924d65a.png">
In chrome I get this too

**Comment by qcyblm** [comment]
> 
> 
> <img alt="Screen Shot 2021-02-09 at 11 12 51 PM" width="1792" src="https://user-images.githubusercontent.com/16292606/107463571-64defb00-6b2c-11eb-9ccb-53143924d65a.png">
> In chrome I get this too

CodeBlock can't be rendered locally, can you fix it?

Source： [https://github.com/qcyblm/vuepress-CodeGroup](https://github.com/qcyblm/vuepress-CodeGroup)

The procedure： yarn && yarn dev

Preview： [http://localhost:8080/vuepress-CodeGroup/](http://localhost:8080/vuepress-CodeGroup/)

**Comment by d-pollard** [comment]
@qcyblm - thanks for the clarification; I was able to debug and fix the issue you're seeing. Mind pulling down my recent changes and verifying that they work for you?

**Comment by qcyblm** [comment]
> - thanks for the clarification; I was able to debug and fix the issue you're seeing. Mind pulling down my recent changes and verifying that they work for you?

Yes, and verify that they work for me.

**Comment by thecoden** [comment]
For me, the code group renders, but the code blocks do not render correctly as I navigate pages. 

You'll see in this screen that initially the component does not render:
![image](https://user-images.githubusercontent.com/75643469/107467655-5a683580-6b1b-11eb-80f9-061b4ee726e6.png)

In this screen, I simply clicked in the address bar and hit enter to directly load the page:
![image](https://user-images.githubusercontent.com/75643469/107467754-8f748800-6b1b-11eb-8ce5-b38228bee488.png)

**Comment by qcyblm** [comment]
@d-pollard - You can clone the [vuepress-CodeGroup ](https://github.com/qcyblm/vuepress-CodeGroup/pulls)to make changes and pull requests to me, I do local testing.

**Comment by thecoden** [comment]
I had the same issues as @qcyblm, but saw your changes right after I commented, so I deleted my comment and checked again.

It works beautifully now, thank you!

**Comment by d-pollard** [comment]
Sweet; okay I'll work on getting this merged in the AM (it's 1:00AM here lol I'm tired)

Have a good day/night everyone!

**Comment by qcyblm** [comment]
My region is in China (it's 1:58 PM)

**Comment by d-pollard** [comment]
Should be fixed as of https://github.com/vuejs/vuepress/releases/tag/v1.8.1

**Comment by mohsen89z** [comment]
> Should be fixed as of https://github.com/vuejs/vuepress/releases/tag/v1.8.1

This link doesn't work anymore, use this link instead:
https://ecosystem.vuejs.press/themes/default/components.html#codegroupitem
