### ISSUE TITLE
Support google analytics 4

### ISSUE THREAD

**Issue by lz1998** [vuejs/vuepress#2713]
## Feature request

support google analytics 4

use gtag.js

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=XXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-xxxxx');
</script>
```

I applied a new media, and use `Google Analytics Plugin`, but it doesn't work.

The new ID is like 'G-xxxxx', not 'UA-00000000-0'

**Comment by eulier1** [comment]
In lack of response, i'm using right now this fork.
https://github.com/scopewu/vuepress
I'm waiting for the results.
I'll let you know if that works.

**Comment by Kerwood** [comment]
Yes, please fix this. It is not possible to create a `UA-XXXXXXX` number anymore.

**Comment by meteorlxy** [comment]
> Yes, please fix this. It is not possible to create a `UA-XXXXXXX` tag anymore.

Oh didn't notice that. I thought it's still optional to use version 3 or version 4.

---

As the GA4 is a breaking version, maybe we should create a new plugin called `@vuepress/plugin-google-analytics-4` ?

**Comment by Kerwood** [comment]
> 
> As the GA4 is a breaking version, maybe we should create a new plugin called `@vuepress/plugin-google-analytics-4` ?

Go for it :+1:

**Comment by javialcantaras** [comment]
Is there any new news on this?

**Comment by dvuckovic** [comment]
It seems that the GA4 support is now in beta and available via `@vuepress/plugin-google-analytics@next`, [the documentation](https://vuepress2.netlify.app/reference/plugin/google-analytics.html) also seems updated. However, I'm having some issues making it work with Vuepress 1.x, not sure why. Perhaps it hasn't been backported yet?

Anyway, just wanted to share a valid workaround for anyone who is not able to use the new version of the package, for whatever reason.

Via [the config file](https://vuepress.vuejs.org/guide/basic-config.html#config-file) and its [`head`](https://vuepress.vuejs.org/config/#head) array, you can inject additional tags to the page header. It's relatively trivial to add the proposed tracking code to the page, something along the following lines:

```js
module.exports = {
    head: [
        [
            'script',
            {
                async: true,
                src: 'https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX',
            },
        ],
        [
            'script',
            {},
            [
                "window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', 'G-XXXXXXXXXX');",
            ],
        ],
    ],
};
```

Just take care to replace the measurement ID in two places, and you'll be good to go.

**Comment by meteorlxy** [comment]
It has been supported in vuepress v2, which is not compatible with v1.

For v1 users, try the snippets that provided by [@dvuckovic](https://github.com/vuejs/vuepress/issues/2713#issuecomment-806621348)

**Comment by laphets** [comment]
In case anyone still need this, I've written a plugin specifically for google analytics 4 to work under vuepress v1, which is available here: https://github.com/laphets/vuepress-plugin-google-analytics-4.
