### ISSUE TITLE
vue-server-renderer@2.6.12 not match with vue3.x

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vuepress#2718]
- [x] I confirm that this is an issue rather than a question.

#### What is expected?
**when run `yarn doc:dev`** , there's a warning that tell version not match
#### What is actually happening?
![image](https://user-images.githubusercontent.com/49113249/100539785-b38e3000-3273-11eb-93ce-e559a54d6426.png)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by anisabboud** [comment]
VuePress uses Vue 2.6 not Vue 3. 
Try `npm install vue@2.6`

(_[vuepress-next](https://github.com/vuepress/vuepress-next) uses Vue 3, but it's still in development._)

**Comment by bencodezen** [comment]
@anisabboud is correct. The current stable version of VuePress is not able to support Vue 3 at this time.
