### ISSUE TITLE
VuePress website doesn't seem to resize to mobile view on Mobile Firefox

### ISSUE THREAD

**Issue by pbek** [vuejs/vuepress#2723]
- [x] I confirm that this is an issue rather than a question.

## Bug report

The VuePress website (and <https://www.qownnotes.org/changelog.html>, which was also built with the awesome VuePress) doesn't seem to resize to "mobile view" on Mobile Firefox.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1798101/100767798-77d1a280-33fa-11eb-8724-38ea9826e756.png">

#### Steps to reproduce

- open <https://vuepress.vuejs.org/config/> on Mobile Firefox (Android) or on the Desktop in the dev tools with "responsive device mode" switched to a Galaxy S9
- see that the website doesn't use the website's responsiveness

#### What is expected?

- rendered webpage uses responsiveness like in Mobile Chrome

#### What is actually happening?

- webpage looks like on a desktop screen

#### Other relevant information

- if you resize the virtual screen in Desktop Firefox in the dev tools the page switches to "mobile view", like expected

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1798101/100768270-f9c1cb80-33fa-11eb-806a-b770939a0cd0.png">

Reference:

- QOwnNotes Webpage issue: https://github.com/pbek/QOwnNotes/issues/1970

**Comment by Myuki** [comment]
Add viewport manually can workaround it

See also #2369 #2607

**Comment by pbek** [comment]
Thank you for the hint, @Myuki. The viewport was the first thing I thought of too, but a quick `curl https://vuepress.vuejs.org/config/ | grep "viewport"` showed me `<meta name="viewport" content="width=device-width,initial-scale=1">` and the issue still persisted. 😅

**Comment by pbek** [comment]
![image](https://user-images.githubusercontent.com/1798101/102017305-7a22ed80-3d66-11eb-913b-06a27f6dd408.png)

**Comment by pbek** [comment]
Or are we talking about the `1.0` instead of `1`?

**Comment by pbek** [comment]
Now I see, the `view-port` is removed by javascript, now that's tricky! 😆  I'll test the setting, thank you very much!

**Comment by pbek** [comment]
That did it! Thanks a lot for the workaround!
