### ISSUE TITLE
How to remove emoji plugin

### ISSUE THREAD

**Issue by Red-Asuka** [vuejs/vuepress#2728]
```
const { removePlugin, PLUGINS } = require('@vuepress/markdown')

markdown: {
    chainMarkdown(config) {
      removePlugin(config, PLUGINS.EMOJI)
    },
}
```

but it doesn't work，how to remove emoji plugin ?

**Comment by Red-Asuka** [comment]
I found it doesn't work on dev , but it work on build

**Comment by carlalexander** [comment]
@Red-Asuka could you let me know where you put this code. I'm trying to remove emojis and it's not working even in build.

**Comment by Red-Asuka** [comment]
@carlalexander 
put this code on `.vuepress/config.js` You can see how to use it [here](https://vuepress.vuejs.org/plugin/option-api.html#chainmarkdown)
