### ISSUE TITLE
Image in public folder not able to load

### ISSUE THREAD

**Issue by jamesyip** [vuejs/vuepress#2730]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. Create an empty repo using `npx create-vuepress-site`
2. put `logo.png` into `.vuepress\public\images`
3. Run `npm run dev`
4. Open `http://localhost:8080/images/logo.png` will return 404

#### What is expected?
Should load the image instead of 404 page

#### What is actually happening?

Vuepress's 404 page displayed

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```

Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.55)
  npmPackages:
    @vuepress/core:  1.7.1
    @vuepress/theme-default:  1.7.1
    vuepress: ^1.7.1 => 1.7.1
  npmGlobalPackages:
    vuepress: Not Found

```

**Comment by DracoPL** [comment]
I have the same issue.

**Comment by DracoPL** [comment]
I have no issue anymore. I missplaced public directory in src/public instead of src/.vuepress/public. It works for me now and i cannot reproduce your issue @jamesyip

**Comment by jamesyip** [comment]
Finally find the root cause is some config error. Closing the issue.
