### ISSUE TITLE
下拉框在手机端无法展开

### ISSUE THREAD

**Issue by pengshuangbao** [vuejs/vuepress#2749]
- [x] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

"devDependencies": {
    "@textlint-rule/textlint-rule-no-unmatched-pair": "^1.0.7",
    "@vuepress/plugin-back-to-top": "1.7.1",
    "@vuepress/plugin-google-analytics": "1.7.1",
    "@vuepress/plugin-medium-zoom": "1.7.1",
    "@vuepress/plugin-pwa": "1.7.1",
    "@vuepress/theme-vue": "1.7.1",
    "remark-cli": "^7.0.0",
    "remark-lint": "^6.0.5",
    "remark-preset-lint-consistent": "^2.0.3",
    "remark-preset-lint-recommended": "^3.0.3",
    "textlint": "^11.3.1",
    "textlint-filter-rule-comments": "^1.2.2",
    "textlint-rule-apostrophe": "^1.0.0",
    "textlint-rule-common-misspellings": "^1.0.1",
    "textlint-rule-diacritics": "^1.0.0",
    "textlint-rule-en-capitalization": "^2.0.2",
    "textlint-rule-stop-words": "^1.0.17",
    "textlint-rule-terminology": "^2.1.4",
    "textlint-rule-write-good": "^1.6.2",
    "vue-toasted": "^1.1.25",
    "vuepress": "1.7.1",
    "vuepress-plugin-flowchart": "^1.4.2"
  }

![51648F0F-CB97-4F8C-8294-827DCC2CE981_1_105_c](https://user-images.githubusercontent.com/16523697/103256411-2e0fb400-49c8-11eb-915d-128cbbd793fb.jpeg)
点击没有反应

**Comment by pengshuangbao** [comment]
自己的代码冲突

**Comment by zq99299** [comment]
怎么解决的？ 我 PC 端也打不开了
