### ISSUE TITLE
Build failed after updating webpack from 4.44.1 to 5.11.1

### ISSUE THREAD

**Issue by imaegoo** [vuejs/vuepress#2753]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Repo: https://github.com/imaegoo/twikoo

1. `git clone https://github.com/imaegoo/twikoo.git twikoo`
2. `cd twikoo`
3. `yarn install`
4. `yarn docs:build`

#### What is expected?

Build successfully (it was successfully before updating Webpack).

#### What is actually happening?

Get an exception: `Error: Rule can only have one resource source (provided resource and test + include + exclude) in {...`

Detail logs: https://github.com/imaegoo/twikoo/runs/1644442505?check_suite_focus=true

#### Other relevant information

- Docs build **SUCCESSFULLY** with below version of Webpack

``` json
"devDependencies": {
  "webpack": "^4.44.1",
  "webpack-cli": "^3.3.12",
  "webpack-dev-server": "^3.11.0"
}
```

- Docs build **FAILED** with below version of Webpack

``` json
"devDependencies": {
  "webpack": "^5.11.1",
  "webpack-cli": "^4.2.0",
  "webpack-dev-server": "^4.0.0-beta.0"
}
```

- I have tried Ubuntu 18.04.5, Windows 10, nodejs 12, nodejs 14, same exception.

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
  Binaries:
    Node: 14.15.3 - D:\Java\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - D:\Java\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
  npmPackages:
    @vuepress/core:  1.7.1
    @vuepress/theme-default:  1.7.1
    vuepress: ^1.7.1 => 1.7.1
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by imaegoo** [comment]
#### Workaround

Change build command from

```
yarn && yarn docs:build
```

to

```
yarn global add vuepress@1.8.0 && vuepress build docs
```

**Comment by meteorlxy** [comment]
Try [vuepress 2](https://github.com/vuepress/vuepress-next) if you want to use webpack 5 for now

**Comment by imaegoo** [comment]
@meteorlxy OK, thanks!

**Comment by nth-chile** [comment]
What if my company won't let me use a beta version?
