### ISSUE TITLE
[Docu-only] Update links

### ISSUE THREAD

**Issue by rowild** [vuejs/vuepress#2756]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Various links to repos that the default theme uses, point to the wrong location. In case this project is still supported - which it does not seem - it would be great to have proper links.

**Comment by charanshekar** [comment]
Hi I want to contribute but could you provide more details

**Comment by rowild** [comment]
I should have provided proper inks to the problem, now I don't know anymore, what I had problems with. Sorry, my bad!

The only thing I can find at the moment is this:
https://vuepress.vuejs.org/theme/blog-theme.html#sites

The listed links "Documentation", "Live Example" etc. go to nowhere. It seems the TLD does not exist anymore...

However, I close this issue. In case I find more problems, I'll reopen it.
