### ISSUE TITLE
实现基于文件夹的分类

### ISSUE THREAD

**Issue by Candane** [vuejs/vuepress#2757]
## Feature request
 1. 文章过多时，在docs下有web,server,team..各个文件夹，能否在nav的items中设置基于文件夹的路径名称，之后点击分类下的前端会根据web文件夹中各个a.md,b.md,c.md文件的categories实现2级分类。
 ```json
//项目目录结构
├── docs
│   ├── .vuepress (可选的)
│   ├── README.md
│   ├── web
│   │   └── a.md
│   │   └── b.md
│   │   └── c.md
│   ├── server
│   │   └── d.md
│   │   └── e.md
│   │   └── f.md
│   ├── team
│   │   └── g.md
│   │   └── h.md
└── package.json
//nav配置
nav = [
  { text: '首页', link: '/', icon: 'reco-home' },
  {
    text: '分类',
    icon: 'reco-category',
    items: [
      {
        text: 'Group1',
        items: [
          { text: '前端', link: '/web/ ' },
          { text: '后端', link: '/server/' },
          { text: '团队协作', link: '/team/' },
        ],
      },
    ],
  },
  { text: '标签', link: '/tag/', icon: 'reco-tag' }
]
//a.md中frontmatter内容
categories:
 - css
//b.md中frontmatter内容
categories:
 - javascript
 ```

#### What problem does this feature solve?
1. 实现基于文件夹下管理多个文章，便于后续管理
#### What does the proposed API look like?
1. 好像hexo有通过在frontmatter多设置一个type变量表示文件夹
#### How should this be implemented in your opinion?
1. categories页面上方的标签是根据frontmatter中的categories进行归档的，能否在编译阶段根据md文件所在的文件夹去生成router页面，或者多加一个type变量根据type在categories的基础上多一层分类

**Comment by Mister-Hope** [comment]
You may use `vuepress-plugin-blog` to achieve this feature while VuePress will focus on serving a static doc site.

**Comment by Mister-Hope** [comment]
You may use `vuepress-plugin-blog` to achieve this feature while VuePress will focus on serving a static doc site.
