### ISSUE TITLE
When import element-ui or any Component in enhanceApp.js have bug

### ISSUE THREAD

**Issue by moker-monkey** [vuejs/vuepress#2760]
- [x] I confirm that this is an issue rather than a question.

## Bug report

**When I import anything(just import) Vue Component, that elementui ant-design-vue and so on ，vuepress client doesn`t work and console  Error:**

_./node_modules/babel-runtime/core-js/array/from.js
Module not found: Error: Can't resolve 'core-js/library/fn/array/from' in '/Users/mac/Desktop/workPlan/伶鼬/perfect-vue/node_modules/babel-runtime/core-js/array_

_./node_modules/babel-runtime/core-js/get-iterator.js
Module not found: Error: Can't resolve 'core-js/library/fn/get-iterator' in '/Users/mac/Desktop/workPlan/伶鼬/perfect-vue/node_modules/babel-runtime/core-js_

...

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by moker-monkey** [comment]
I find lost import Vue,now vuepress can work.

**Comment by xgqfrms** [comment]
@moker-monkey Hi, I have the same question, could you show me your screenshots?

> import Vue, still not work

```js
/**
 * Client app enhancement file.
 *
 * https://v1.vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements
 */

import Vue from 'vue';
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';

export default ({
  Vue, // the version of Vue being used in the VuePress app
  options, // the options for the root Vue instance
  router, // the router instance for the app
  siteData // site metadata
}) => {
  // ...apply enhancements for the site.
  //   element-ui
  Vue.use(ElementUI);
}

```

![image](https://user-images.githubusercontent.com/7291672/104589330-a8b52080-56a4-11eb-9e83-c48722177536.png)

**Comment by xgqfrms** [comment]
# solution

```diff
  "dependencies": {
+   "async-validator": "1.11.5",
+   "core-js": "3.6.5",
    "element-ui": "2.14.1",
-   "vue": "2.6.11",
+   "vue": "2.6.12",
  },


```

**Comment by edgexie** [comment]
> # solution
> ```diff
>   "dependencies": {
> +   "async-validator": "1.11.5",
> +   "core-js": "3.6.5",
>     "element-ui": "2.14.1",
> -   "vue": "2.6.11",
> +   "vue": "2.6.12",
>   },
> ```

`async-validator` and `vue` are not necessary, the problem is miss core-js, it's version need 2.x

my dependencies
```json
  "dependencies": {
    "core-js": "2.x",
    "element-ui": "^2.15.9",
    "vuepress": "^1.9.7"
  }
```
