### ISSUE TITLE
navbar 高亮问题

### ISSUE THREAD

**Issue by sccassiel** [vuejs/vuepress#2765]
在用vuepress编写文档的时候，同一种分类的文档，第二篇文档就不会高亮
![image](https://user-images.githubusercontent.com/6365459/104583081-adc1a200-569b-11eb-97a9-e198a5b6c087.png)

**Comment by sccassiel** [comment]
点击左边sidebar的第二篇文档,那么这个高亮就会消失
![image](https://user-images.githubusercontent.com/6365459/104583292-ec575c80-569b-11eb-8701-35e5c1f06942.png)
都是同一个分类的文档

**Comment by billyyyyy3320** [comment]
Please follow issue template and provide more info about your project. Also, please translate to English if possible
