### ISSUE TITLE
build报错undefined is not a function

### ISSUE THREAD

**Issue by xiaofeng-bm** [vuejs/vuepress#2767]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
长时间没写的项目，打包报如下错误，代码回滚也不管用
![Snipaste_2021-01-15_15-39-50](https://user-images.githubusercontent.com/45890549/104695718-2120ed80-5748-11eb-91d4-ed3562046b5f.png)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by wangliang01** [comment]
我也遇到同样的问题了

**Comment by billyyyyy3320** [comment]
Please provide more info about your project. Also, please translate to English if possible

**Comment by radiorz** [comment]
TypeError: undefined is not a function
    at C:\...\node_modules\@vuepress\core\lib\node\build\index.js:82:15    
    at Array.filter (<anonymous>)
    at Build.render (C:\ ....\node_modules\@vuepress\core\lib\node\build\index.js:82:8)
    at async App.build (C:\....\node_modules\@vuepress\core\lib\node\App.js:499:5)
error Command failed with exit code 1.
