### ISSUE TITLE
Allow pages to be excluded from built-in search content

### ISSUE THREAD

**Issue by patroytall** [vuejs/vuepress#2768]
#### What problem does this feature solve?
I have a private section to my site. I would like to exclude its pages from the search.

#### What does the proposed API look like?
A new boolean frontmatter option `searchContent`  which excludes the page content when set to true.

#### How should this be implemented in your opinion?
There is already a `search` option to remove the presence of the search box for a page. The `searchContent` option will be in the same area of code. Documentation will need to be updated to document the new option.

#### Are you willing to work on this yourself?
Yes. I will try to submit a pull request for this. About me: https://patrickroy.me/about

**Comment by patroytall** [comment]
My understanding was that we are suppose wait for feedback on feature request before proceeding.

In this case, there are different designs to implement the exclusion; even non-backward compatible ones. It would be better, if someone with experience could confirm:
- it is a desirable feature
- the option name is correct

Thank you.

**Comment by giulioforesto** [comment]
Isn't this feature already implemented? See [the built-in search doc](https://vuepress.vuejs.org/theme/default-theme-config.html#built-in-search):

> You can also disable the built-in search box for individual pages by [setting `search` in frontmatter](https://vuepress.vuejs.org/guide/frontmatter.html#search):
> ```yaml
> ---
> search: false
> ---
> ```

**Comment by giulioforesto** [comment]
You can also [exclude entire paths from the search targets](https://vuepress.vuejs.org/plugin/official/plugin-search.html#test).

**Comment by patroytall** [comment]
Yes the "test" property is what I need to exclude some content from the searches. Thank you. Issue can be closed.

**Comment by patroytall** [comment]
"test" property is what I need to exclude some content from the searches

**Comment by timlonggr** [comment]
How was the "test" property defined? Can you give me an example?
