### ISSUE TITLE
build 时候报错 Cannot read property '_normalized' of undefined

### ISSUE THREAD

**Issue by GPPoseidon999** [vuejs/vuepress#2769]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by GPPoseidon999** [comment]
![image](https://user-images.githubusercontent.com/28697192/104870168-d343f980-5982-11eb-8422-a231ba709b6f.png)
目录结构
![Uploading image.png…]()

**Comment by GPPoseidon999** [comment]
![image](https://user-images.githubusercontent.com/28697192/104870168-d343f980-5982-11eb-8422-a231ba709b6f.png)
目录结构
![image](https://user-images.githubusercontent.com/28697192/104870194-e1921580-5982-11eb-8b73-a0cd343bbe1e.png)

**Comment by clone-git** [comment]
你要把所有的文件建好 other,relink 你有创建吗
