### ISSUE TITLE
ttf 字体文件怎么引入呢？谁知道如何配置可以引入当前目录的字体文件？

### ISSUE THREAD

**Issue by zq99299** [vuejs/vuepress#2779]
ttf 字体文件怎么引入呢？谁知道如何配置可以引入当前目录的字体文件？

**Comment by Mister-Hope** [comment]
Write something like this in your `.vuepress/styles/index.styl`. And please ask questions like this on Stackoverflow, The issue is used to track bugs and features.

```styl
@font-face
  font-family 'Font Awesome 5 Brands'
  font-style normal
  font-weight 400
  font-display block
  src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
```

**Comment by zq99299** [comment]
> Write something like this in your `.vuepress/styles/index.styl`. And please ask questions like this on Stackoverflow, The issue is used to track bugs and features.
> 
> ```stylus
> @font-face
>   font-family 'Font Awesome 5 Brands'
>   font-style normal
>   font-weight 400
>   font-display block
>   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> ```

感谢您的回复，不过我的问题是「离线字体，当前项目目录下的字体文件」，不是在线的字体文件
Thank you for your reply, but my question is "offline fonts, font files in the current project directory", not online font files

**Comment by mijaclan** [comment]
> > 在你的`.vuepress/styles/index.styl`。并请在Stackoverflow上提出这样的问题，该问题用于追踪错误和功能。
> > ```stylus
> > @font-face
> >   font-family 'Font Awesome 5 Brands'
> >   font-style normal
> >   font-weight 400
> >   font-display block
> >   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> > ```
> 
> 感谢您，不过我问题是是，当前是是是是是「是的的字体字体，不字体，不文件，不不，不是是在线在线在线在线在线的的的的的字体字体字体文件谢谢您谢谢您您您, 不是在线字体文件



> > Write something like this in your `.vuepress/styles/index.styl`. And please ask questions like this on Stackoverflow, The issue is used to track bugs and features.
> > ```stylus
> > @font-face
> >   font-family 'Font Awesome 5 Brands'
> >   font-style normal
> >   font-weight 400
> >   font-display block
> >   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> > ```
> 
> 感谢您的回复，不过我的问题是「离线字体，当前项目目录下的字体文件」，不是在线的字体文件 Thank you for your reply, but my question is "offline fonts, font files in the current project directory", not online font files

兄弟解决了吗？我也是下载到本地的ttf文件

**Comment by zq99299** [comment]
> > > 在你的`.vuepress/styles/index.styl`。并请在Stackoverflow上提出这样的问题，该问题用于追踪错误和功能。
> > > ```stylus
> > > @font-face
> > >   font-family 'Font Awesome 5 Brands'
> > >   font-style normal
> > >   font-weight 400
> > >   font-display block
> > >   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> > > ```
> > 
> > 
> > 感谢您，不过我问题是是，当前是是是是是「是的的字体字体，不字体，不文件，不不，不是是在线在线在线在线在线的的的的的字体字体字体文件谢谢您谢谢您您您, 不是在线字体文件
> 
> > > Write something like this in your `.vuepress/styles/index.styl`. And please ask questions like this on Stackoverflow, The issue is used to track bugs and features.
> > > ```stylus
> > > @font-face
> > >   font-family 'Font Awesome 5 Brands'
> > >   font-style normal
> > >   font-weight 400
> > >   font-display block
> > >   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> > > ```
> > 
> > 
> > 感谢您的回复，不过我的问题是「离线字体，当前项目目录下的字体文件」，不是在线的字体文件 Thank you for your reply, but my question is "offline fonts, font files in the current project directory", not online font files
> 
> 兄弟解决了吗？我也是下载到本地的ttf文件

解决了，ttf 好像不支持，换其他格式的字体文件，可以参考这个 https://github.com/zq99299/note-book/blob/master/docs/.vuepress/enhanceApp.js   就是写相对目录就行

**Comment by zq99299** [comment]
> > > > > 在你的`.vuepress/styles/index.styl`。并请在Stackoverflow上提出这样的问题，该问题用于追踪错误和功能。
> > > > > ```stylus
> > > > > @font-face
> > > > >   font-family 'Font Awesome 5 Brands'
> > > > >   font-style normal
> > > > >   font-weight 400
> > > > >   font-display block
> > > > >   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> > > > > ```
> > > > 
> > > > 
> > > > 感谢您，不过我问题是是，当前是是是是是「是的的字体字体，不字体，不文件，不不，不是是在线在线在线在线在线的的的的的字体字体字体文件谢谢您谢谢您您您, 不是在线字体文件
> > > 
> > > 
> > > > > Write something like this in your `.vuepress/styles/index.styl`. And please ask questions like this on Stackoverflow, The issue is used to track bugs and features.
> > > > > ```stylus
> > > > > @font-face
> > > > >   font-family 'Font Awesome 5 Brands'
> > > > >   font-style normal
> > > > >   font-weight 400
> > > > >   font-display block
> > > > >   src url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/webfonts/fa-brands-400.ttf') format('truetype'), 
> > > > > ```
> > > > 
> > > > 
> > > > 感谢您的回复，不过我的问题是「离线字体，当前项目目录下的字体文件」，不是在线的字体文件 Thank you for your reply, but my question is "offline fonts, font files in the current project directory", not online font files
> > > 
> > > 
> > > 兄弟解决了吗？我也是下载到本地的ttf文件
> > 
> > 
> > 解决了，ttf 好像不支持，换其他格式的字体文件，可以参考这个 https://github.com/zq99299/note-book/blob/master/docs/.vuepress/enhanceApp.js 就是写相对目录就行
> 
> 我按照你的方法在[enhanceApp.js](https://github.com/zq99299/note-book/blob/master/docs/.vuepress/enhanceApp.js)引入woff2的样式文件，为什么页面没有生效（F12 > Network > 有这个打包后的.woff2文件，页面字体却没有使用上）？

可以先复制我那个字体文件先调通，再尝试修改成自己的

**Comment by mijaclan** [comment]
> > 我按照你的方法在[enhanceApp.js](https://github.com/zq99299/note-book/blob/master/docs/.vuepress/enhanceApp.js)引入woff2的样式文件，为什么页面没有生效（F12 > Network > 有这个打包后的.woff2文件，页面字体却没有使用上）？
> 
> 可以先复制我那个字体文件先调通，再尝试修改成自己的

在docs/.vuepress/styles/index.styl 使用就可以了
解决了，感谢！ @zq99299
