### ISSUE TITLE
页面刷新后, 不能跳转到指定锚点

### ISSUE THREAD

**Issue by xuoutput** [vuejs/vuepress#2782]
https://vuepress.vuejs.org/zh/plugin/official/plugin-last-updated.html#%E9%80%89%E9%A1%B9
官网就不行

**Comment by nuochong** [comment]
你再试下，应该试可以的。

**Comment by billyyyyy3320** [comment]
Please submit the issue with issue templates.

By the way, I have visited the url and the functionality looks good
