### ISSUE TITLE
大写字母的锚点, id 变成全小写了, 同时不支持_ @等特殊字符

### ISSUE THREAD

**Issue by xuoutput** [vuejs/vuepress#2783]
标题自动生成的锚点, 不支持特殊字符, 且大写字母会变成小写字母插入到 id属性中

**Comment by nuochong** [comment]
貌似试因为老版本的ie浏览器不区分锚点大小写，所以就会全部转为小写，否则使用老版本浏览器会出现问题。

**Comment by Mister-Hope** [comment]
This is expected because `example.com/a/` and  `EXAMPLE.COM/A/` are exectly same to browser.

**Comment by meteorlxy** [comment]
https://vuepress.vuejs.org/config/#markdown-slugify
