### ISSUE TITLE
使用自定义布局后，导航栏没有保留

### ISSUE THREAD

**Issue by zhhbinn** [vuejs/vuepress#2793]
![image](https://user-images.githubusercontent.com/40169558/106996914-d16c9980-67bc-11eb-9c8b-2192b9c15057.png)
![image](https://user-images.githubusercontent.com/40169558/106996927-d7fb1100-67bc-11eb-8a9b-64ecab06e6d8.png)

新页面就只有组件内容，没有保留上方的导航栏

**Comment by antfu** [comment]
It's up to you to custom and that's why it called "custom".

**Comment by zhhbinn** [comment]
![image](https://user-images.githubusercontent.com/40169558/107009517-21089080-67d0-11eb-944b-b62d4c922e97.png)
这里不是写着保留导航栏么

**Comment by zhhbinn** [comment]
> It's up to you to custom and that's why it called "custom".

文档不是写着保留导航栏么，还是需要怎么打开？谢谢！
