### ISSUE TITLE
[Question] Any plan to add this to vue cli 3?

### ISSUE THREAD

**Issue by DrSensor** [vuejs/vuepress#28]
Thankyou :grin:

**Comment by yyx990803** [comment]
This is not related to vue-cli 3. It's meant to be a standalone tool.

**Comment by tinchox5** [comment]
It would be great to have the option to install when start a project with vue-cli 3

**Comment by yyx990803** [comment]
@tinchox5 it's literally just `npm install -D vuepress` in any project, not much point in adding anything special to vue-cli for that.

**Comment by tinchox5** [comment]
Yes, I understand what you mean. I insisted in @DrSensor suggestion because I thought it would be nice to have a powerful doc generator already installed in you project with a 'doc/' folder and a doc template mock ready to be edited.
