### ISSUE TITLE
Register global components in themes

### ISSUE THREAD

**Issue by Johnhhorton** [vuejs/vuepress#281]
Vue Press version: 0.8.4

In `.vuepress/` components are automatically registered when they're placed in `components/`. As a developer, my assumption was that the `theme/` folder would have a similar feature.

Components can be registered with a pattern like this:
```javascript
//.vuepress/theme/enhanceApp.js

import PostList from './components/PostList'
import PostSnippet from './components/PostSnippet'

export default ({
    Vue, // the version of Vue being used in the VuePress app
    options, // the options for the root Vue instance
    router, // the router instance for the app
    siteData // site metadata
  }) => {
    Vue.component('PostList', PostList)
    Vue.component('PostSnippet', PostSnippet)
  }
```

But it would be nice if the theme could mirror functionality of `.vuepress/` structures like `components/`

**Comment by meteorlxy** [comment]
`themeEnhanceApp` can help, which has not included in the docs yet.

**Comment by yliaho** [comment]
Theme's enhanceApp is documented [here](https://vuepress.vuejs.org/guide/custom-themes.html#app-level-enhancements)

**Comment by ulivz** [comment]
If you read her requirement carefully, you will find that she just want to leverage the structure " theme/ component/" that will be registered as global components.

**Comment by meteorlxy** [comment]
You are right, I misunderstood what he requests.

This feature may need some discussions.

**Comment by hmatalonga** [comment]
Hello everyone!

I have tried to come up with a simple solution for this scenario and I have drafted these changes on `vuepress/lib/prepare.js`:

```javascript
async function genComponentRegistrationFile ({ sourceDir }) {
  function genImport (file, componentPath) {
    const name = fileToComponentName(file)
    const baseDir = path.resolve(sourceDir, componentPath)
    const absolutePath = path.resolve(baseDir, file)
    const code = `Vue.component(${JSON.stringify(name)}, () => import(${JSON.stringify(absolutePath)}))`
    return code
  }
  const components = (await resolveComponents(sourceDir, '.vuepress/components')) || []
  const customThemeComponents = (await resolveComponents(sourceDir, '.vuepress/theme/components')) || []
  const componentsStr = components.map(f => genImport(f, '.vuepress/components')).join('\n')
  const customThemeComponentsStr = customThemeComponents.map(f => genImport(f, '.vuepress/theme/components')).join('\n')

  return `import Vue from 'vue'\n${componentsStr}\n${customThemeComponentsStr}`
}
```

Adding the component path as a second parameter to both `resolveComponents` and `genImport` could be used to generate the string for `.vuepress/theme/components` too.

I did some testing locally and I believe it achieves what is intended :+1:

What do you think of this approach could it be viable? If so I would be happy to open a PR :smile:

**Comment by hmatalonga** [comment]
@ulivz, @meteorlxy can you give some feedback on this idea? :wink:

**Comment by meteorlxy** [comment]
I suggest to use `options.themePath` instead of `'.vuepress/theme'`.

**Comment by hmatalonga** [comment]
Hello again!

Thanks for the tip @meteorlxy, I made some changes to make use of `options.themePath` and opened a PR for review :smile:
