### ISSUE TITLE
vuepress引入echarts-gl打包报错

### ISSUE THREAD

**Issue by Pentium286** [vuejs/vuepress#2827]
enhanceApp.js引入`import 'echarts-gl';`

![image](https://user-images.githubusercontent.com/1262247/114963577-a62eb680-9e9f-11eb-8e2b-96170cbf91e8.png)
![image](https://user-images.githubusercontent.com/1262247/114963626-bd6da400-9e9f-11eb-8d0b-a66141202ae0.png)

**Comment by qianzhangsheng** [comment]
`docs/.vuepress/enhanceApp.js`

```
export default ({
    Vue,
    options,
    router,
    siteData,
}) => {
// FIXME:解决加载 import 'echarts-gl' 报错的问题
    Vue.mixin({
        mounted() {
            let echartsGL = require('echarts-gl');
            Vue.use(echartsGL);
        },
    });
}
```

**Comment by yuanqingqingf** [comment]
Vue.mixin({
        mounted() {
          const { mockXHR } = require('./mock/index.js')
           mockXHR()
        },
    });
使用此方式引入mock后，运行项目之后，所有使用mock模拟接口的地方，都不生效了，谁有解决办法呀，急急急
