### ISSUE TITLE
"Vue packages version mismatch" after install @vuepress/plugin-pwa-popup

### ISSUE THREAD

**Issue by JialuGong** [vuejs/vuepress#2855]
- [x] I confirm that this is an issue rather than a question.

## Bug report
After adding `@vuepress/plugin-pwa-popup` plugins,  there will be an error as follows:
```shell
Vue packages version mismatch:

- vue@3.0.11
- vue-server-renderer@2.6.12
```

#### Steps to reproduce
- First , I install `@vuepress/plugin-pwa-popup`
```shell
yarn add -D @vuepress/plugin-pwa-popup
```
- Then, I run the following command to build
```shell
yarn docs:build    
```
but  it throws an error in `node_modules/vue-server-renderer/index.js:8`
```shell
throw new Error(
  ^

Error: 

Vue packages version mismatch:

- vue@3.0.11
- vue-server-renderer@2.6.12
```
To fix it, I run the following commands. However, they don't work on it
```shell
yarn upgrade
rm -rf yarn.lock
```
and 
```shell
rm -rf node_modules
yarn install
```

#### Other relevant information
my os version : macOS Big Sur 11.3.1
my node environment version: v14.16.1
And the `devDependencie`s of my project are
```json
{ "@vuepress/plugin-pwa": "^1.8.2",
    "@vuepress/plugin-pwa-popup": "^2.0.0-alpha.8",
    "vuepress": "^1.8.2"
}
```
- Output of `npx vuepress info` in my VuePress project:
```shell
Vue packages version mismatch:

- vue@3.0.11
- vue-server-renderer@2.6.12

This may cause things to work incorrectly. Make sure to use the same version for both.
```

**Comment by meteorlxy** [comment]
`@vuepress/plugin-pwa-popup` is for vuepress v2, not v1.
