### ISSUE TITLE
dev no problem,but build report an error: undefined is not a function

### ISSUE THREAD

**Issue by likesandy** [vuejs/vuepress#2859]
![Snipaste_2021-06-01_12-27-07](https://user-images.githubusercontent.com/68144742/120266700-086b3b80-c2d5-11eb-9904-1de4e11eb203.png)
![Snipaste_2021-06-01_12-28-48](https://user-images.githubusercontent.com/68144742/120266705-099c6880-c2d5-11eb-9ce2-f5fc0ea444d6.png)

**Comment by penguin0731** [comment]
I also have this problem. How can I solve it?
