### ISSUE TITLE
vuepress不支持<script lang="tsx">,怎么能让它支持

### ISSUE THREAD

**Issue by wocwin** [vuejs/vuepress#2893]
问题如图:
![image](https://user-images.githubusercontent.com/37534478/125021171-b32d0180-e0ac-11eb-86e5-473a4ef18726.png)

**Comment by CalmHarbin** [comment]
> 问题如图:
> ![image](https://user-images.githubusercontent.com/37534478/125021171-b32d0180-e0ac-11eb-86e5-473a4ef18726.png)

你的问题解决了吗

**Comment by CalmHarbin** [comment]
修改config.js文件，增加对tsx文件支持

```js
{
    configureWebpack: {
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    exclude: /node_modules/,
                    use: [
                        'cache-loader',
                        {
                            loader: 'babel-loader',
                            options: {
                                babelrc: false,
                                configFile: false,
                                presets: [
                                    '@babel/preset-env', // 可以识别es6语法
                                    '@vue/babel-preset-jsx' // 解析jsx语法
                                ]
                            }
                        },
                        {
                            loader: 'ts-loader',
                            options: {
                                appendTsxSuffixTo: [/\.vue$/, /\.md$/]
                            }
                        }
                    ]
                }
            ]
        }
    },
}

```

**Comment by wocwin** [comment]
是不是需要安装这三个依赖：babel-loader；cache-loader；ts-loader

**Comment by wocwin** [comment]
> 修改config.js文件，增加对tsx文件支持
> 
> ```js
> {
>     configureWebpack: {
>         module: {
>             rules: [
>                 {
>                     test: /\.tsx?$/,
>                     exclude: /node_modules/,
>                     use: [
>                         'cache-loader',
>                         {
>                             loader: 'babel-loader',
>                             options: {
>                                 babelrc: false,
>                                 configFile: false,
>                                 presets: [
>                                     '@babel/preset-env', // 可以识别es6语法
>                                     '@vue/babel-preset-jsx' // 解析jsx语法
>                                 ]
>                             }
>                         },
>                         {
>                             loader: 'ts-loader',
>                             options: {
>                                 appendTsxSuffixTo: [/\.vue$/, /\.md$/]
>                             }
>                         }
>                     ]
>                 }
>             ]
>         }
>     },
> }
> ```
是不是需要安装这三个依赖：babel-loader；cache-loader；ts-loader

**Comment by CalmHarbin** [comment]
> 是不是需要安装这三个依赖：babel-loader；cache-loader；ts-loader

babel-loader和cache-loader在vuepress已经有依赖了，如果你没有使用vuepress-plugin-typescript则需要安装ts-loader和typescript。ts-loader请安装8.x版本,因为vuepress内部使用的的webpack4.x

**Comment by wocwin** [comment]
> > 是不是需要安装这三个依赖：babel-loader；cache-loader；ts-loader
> 
> babel-loader和cache-loader在vuepress已经有依赖了，如果你没有使用vuepress-plugin-typescript则需要安装ts-loader和typescript。ts-loader请安装8.x版本,因为vuepress内部使用的的webpack4.x

之前有安装这个插件（vuepress-plugin-typescript），但是里面都没有配置；我删除node_modules重新安装后tsx能跑起来，但console会报很多ts的错后来在tsconfig文件加了"suppressImplicitAnyIndexErrors": true,就解决了
![image](https://user-images.githubusercontent.com/37534478/130742791-c2e61526-88da-44eb-b733-fc7abf8f2c83.png)

最终项目是跑起来了，总之谢谢啦！

**Comment by tlyau62** [comment]
I've finally written a [plugin](https://github.com/tlyau62/vuepress-plugin-ts-tsx) that support for both ts and tsx. Hope can help someone.
