### ISSUE TITLE
Newlines in markdown source file not correctly rendered

### ISSUE THREAD

**Issue by rolfchess** [vuejs/vuepress#2909]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Newlines within a paragraph in a markdown file are rendered as newlines in the output, breaking the layout of the rendered output. By convention, newlines in a markdown file paragraph should not end up in the rendered text.

#### Steps to reproduce

Create a markdown file which contains the following text:

```md
# This is a test markdown file

All
these
words
should
be
on
one
line.

These
words should be
on the second line.
```

run `vuepress dev`

Check the output in a browser.

#### What is expected?

When rendering above source file, the output should contain 2 paragraphs, like so:

> **This is a test markdown file**
> 
> All these words should be on one line.
> 
> These words should be on the second line.

#### What is actually happening?

The output is rendered as:

> **This is a test markdown file**
> 
> All
> these
> words
> should
> be
> on
> one
> line.
> 
> These
> words should be
> on the second line.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Not Found
    Firefox: 90.0
    Safari: 14.1
  npmPackages:
    @vuepress/core:  1.8.2
    @vuepress/theme-default:  1.8.2
    vuepress: ^1.8.2 => 1.8.2
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by mtoorop-ximedes** [comment]
OK it seems to behave as expected if you change the two softbreak lines.

Change these:
```js
state.push('softbreak', 'br', 0);
```
to
```js
state.pending = state.pending.replace(/ ?$/, ' ');
```

So the snippet becomes:
```js
  // '  \n' -> hardbreak
  // Lookup in pending chars is bad practice! Don't copy to other rules!
  // Pending string is stored in concat mode, indexed lookups will cause
  // convertion to flat mode.
  if (!silent) {
    if (pmax >= 0 && state.pending.charCodeAt(pmax) === 0x20) {
      if (pmax >= 1 && state.pending.charCodeAt(pmax - 1) === 0x20) {
        state.pending = state.pending.replace(/ +$/, '');
        state.push('hardbreak', 'br', 0);
      } else {
        state.pending = state.pending.slice(0, -1);
        state.pending = state.pending.replace(/ ?$/, ' ');
      }

    } else {
      state.pending = state.pending.replace(/ ?$/, ' ');
    }
  }
```

**Comment by rolfchess** [comment]
👍
