### ISSUE TITLE
Long autoscroll with auto chapter highlighting like Stripe.com

### ISSUE THREAD

**Issue by PabloC** [vuejs/vuepress#291]
It would be great if we can transform the full documentation in a navegational document like stripe.com docs.

See as an example:
https://stripe.com/guides/general-data-protection-regulation

- One page documentation
- Every big title is a chapter
- Once you scrolldown, the new chapter is highlighted at the left.

**Comment by yyx990803** [comment]
You can write your own theme for that. This by something we will consider in the default theme.
