### ISSUE TITLE
Migrating from GitBook

### ISSUE THREAD

**Issue by swapagarwal** [vuejs/vuepress#292]
I've been using GitBook for a while now, and would like to try this out owing to my recently-developed love for Vue.js! ❤️ 
Are there some instructions on how to migrate from GitBook to VuePress? If not, I'd love to contribute to this. 😇

**Comment by meteorlxy** [comment]
Not yet. Migration instructions may be an important part in docs.

**Comment by rogersachan** [comment]
definitely necessary, I've hit a ton of roadblocks in moving projects inside and out of vuejs that are using gitbooks for documentation.

**Comment by swapagarwal** [comment]
@rogersachan Let's compile the list of roadblocks; then we can work on addressing them one-by-one! 😄

**Comment by swapagarwal** [comment]
@ulivz I'm working on making a guide to migrate from GitBook to VuePress. From my understanding, I see that the parallel for GitBook plugins in VuePress is markdown-it plugins. Can you confirm?

**Comment by ulivz** [comment]
Not exactly, markdown-it plugins is only for markdown syntax extension, and we are still working for vuepress plugins (#240 ), which can help you to extend markdown / webpack / vue / vue-router and so on.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by Jeff-Tian** [comment]
@swapagarwal could you please share the guide link here? Thanks a lot!
