### ISSUE TITLE
Nav 包含中文无法匹配 active class

### ISSUE THREAD

**Issue by tomiaa12** [vuejs/vuepress#2930]
{ text: '预处理', items: [
  { text: 'Less', link:'/docs/CSS/预处理/Less'  },
  { text: 'Sass', link:'/docs/CSS/预处理/Sass'  },
]},
![image](https://user-images.githubusercontent.com/34568691/134523017-6c94fc16-7993-440f-9113-2cd314e3b5a6.png)

**Comment by ulivz** [comment]
Please don't delete issue template or we'll close your issue. (This sentence should be visible when you created the issue. )
