### ISSUE TITLE
Multi page support

### ISSUE THREAD

**Issue by dshvv** [vuejs/vuepress#2935]
默认情况下，只支持spa，也就是只生成一个html文件。
但是我提供了一种办法，可以根据markdown文件自动生成多个html。
侧边栏导航也会关联
https://www.cnblogs.com/dshvv/p/15386262.html

By default, only spa is supported, that is, only one HTML file is generated.
However, I provide a way to automatically generate multiple HTML based on the markdown file.
The sidebar navigation is also associated
https://www.cnblogs.com/dshvv/p/15386262.html

**Comment by ulivz** [comment]
Sorry but VuePress 1.x generated multiple html ... 

It looks like an issue of VuePress 2, please move on https://github.com/vuepress/vuepress-next to continue.
