### ISSUE TITLE
求助使用默认主题配置，怎么给文章添加作者？

### ISSUE THREAD

**Issue by labulatong** [vuejs/vuepress#2936]
求助，我使用的是默认的主题配置，没有继承任何主题，请问我怎么添加这个文章的作者信息呢？
![image](https://user-images.githubusercontent.com/75509582/136762368-74f04dbc-e7ae-461d-86ae-e8621d52c241.png)

**Comment by ulivz** [comment]
You can [writing a theme extending the default theme](https://vuepress.vuejs.org/theme/writing-a-theme.html) and [override the components of default theme](https://vuepress.vuejs.org/theme/inheritance.html#override-components).
