### ISSUE TITLE
vuepress is broken due to latest cac release

### ISSUE THREAD

**Issue by as-dg** [vuejs/vuepress#2937]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

* Install the latest version of vuepress via npm/yarn (fresh node_modules)

* Try to serve or build the docs

#### What is expected?

Successful serving / building of the docs

#### What is actually happening?

cac related error:

```
$ vuepress dev src
/my/username/docs/node_modules/vuepress/lib/util.js:21
  const cli = CAC()
              ^

TypeError: CAC is not a function
    at CLI (/my/username/docs/node_modules/vuepress/lib/util.js:21:15)
    at Object.<anonymous> (/my/username/node_modules/vuepress/cli.js:14:1)
```

#### Other relevant information

This started to happen with the currently latest version [cac@6.7.10](https://www.npmjs.com/package/cac/v/6.7.10). Not sure if this is a bug in their package, as I'm not familiar with it.

My workaround is currently to pin cac to v6.7.9 via resolutions:
```
  "resolutions": {
    "cac": "6.7.9"
  }
```

**Comment by ulivz** [comment]
Whether to lock the dependencies is a question.
