### ISSUE TITLE
Don't hide sidebar toggler at tablet resolutions!

### ISSUE THREAD

**Issue by alexsorinsky** [vuejs/vuepress#2938]
## So this is how doc looks like at **720px** breakpoint:

![pic](https://i.imgur.com/5M8w2C1.png)

## and here is at **700px**:

![pic](https://i.imgur.com/Gz2aTeb.png)

the letter much much better for reading with tablets, phones etc

a lot of people who read using mobile devices, so please dont hide the hamburger button toggler at least till 1200px !!!

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
