### ISSUE TITLE
plugin code in build output is not converted to es5

### ISSUE THREAD

**Issue by GalliumWang** [vuejs/vuepress#2954]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

I use vuepress-plugin-fulltext-search plugin, but the code of this plugin still exist as es6 version in build output, while all other code in build output is es5 version.

```js
  462: function (t, n, e) {
    'use strict';
    !(function (n, e, r) {
      let u;
      (u = r.define) && u.amd
        ? u([], function () {
            return e;
          })
        : (u = r.modules)
        ? (u['FlexSearch'.toLowerCase()] = e)
        : (t.exports = e);
    })(
      0,
      (function t(n) {
        function e(t, n) {
          const e = n ? n.id : t && t.id;
          (this.id = e || 0 === e ? e : B++),
            this.init(t, n),
            o(this, 'index', function () {
```

**Comment by ulivz** [comment]
I‘m sure that you should move on https://github.com/leo-buneev/vuepress-plugin-fulltext-search to submit this issue.
