### ISSUE TITLE
VuePress给的案例网站已经指向非法网站

### ISSUE THREAD

**Issue by sl514** [vuejs/vuepress#2955]
- [ ] I confirm that this is an issue rather than a question.

## Bug report
VuePress给的案例网站已经指向非法网站
#### Steps to reproduce

博客主题里给出的文档和案例网站，打开后是非法网站，请注意。
#### What is actually happening?
博客主题里给出的文档和案例网站，打开后是非法网站，请注意。
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
Sorry for this trouble, a quick fix created at #2956, thanks for the report!
