### ISSUE TITLE
怎么添加ICP备案号显示？

### ISSUE THREAD

**Issue by daenmax** [vuejs/vuepress#2958]
各位老师好，怎么给vuepress构建的网站添加ICP备案号显示呢？谢谢

**Comment by loa** [comment]
One option if you use the default theme is to put your ICP number in footer of the homepage layout.

https://vuepress.vuejs.org/theme/default-theme-config.html#homepage

**Comment by ulivz** [comment]
You can [writing a theme extending the default theme](https://vuepress.vuejs.org/theme/writing-a-theme.html) and [override the components of default theme](https://vuepress.vuejs.org/theme/inheritance.html#override-components).
