### ISSUE TITLE
怎么接入typedoc

### ISSUE THREAD

**Issue by wenyiweb** [vuejs/vuepress#2959]
- [ ] I confirm that this is an issue rather than a question.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by ulivz** [comment]
This is a question and should be asked in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress).
