### ISSUE TITLE
Update EditLinks to support a repo that uses main not master branch

### ISSUE THREAD

**Issue by n8-dev** [vuejs/vuepress#2965]
## Feature request

Update code to support edit links to repo that uses `main` over `master`.

I am talking about the following `edit link`
```
themeConfig: {
  editLinks: true
}
```

More information here:
https://github.com/github/renaming

#### What problem does this feature solve?

Currently any repo using main instead of master edit links will be broken and 404 when clicked

#### What does the proposed API look like?
N/A

#### How should this be implemented in your opinion?
Possible config option.
eg:
```
themeConfig: {
  mainRepoBranch: 'master'
}
```

This would prevent it being a breaking change, and people can change to `main` until a time vuepress wishes to change to `main`

#### Are you willing to work on this yourself?
Could do.

**Comment by ulivz** [comment]
You can use [themeConfig.docsBranch](https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links)

**Comment by n8-dev** [comment]
Thanks so much, sorry I missed that option
