### ISSUE TITLE
hello  我想知道vuepress有什么办法可以获取浏览器的域名

### ISSUE THREAD

**Issue by thompsonjiang** [vuejs/vuepress#2970]
在config.js里面需要根据当前环境访问不同的url，但是我现在拿不到浏览器的域名

**Comment by ulivz** [comment]
config.js 是构建期，你只能在运行时拿到：https://vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements

**Comment by thompsonjiang** [comment]
> config.js 是构建期，你只能在运行时拿到：https://vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements

谢谢   问题已解决
