### ISSUE TITLE
smoothScroll don't works

### ISSUE THREAD

**Issue by NatureK88** [vuejs/vuepress#2976]
When I use vuepress 1.8.2，I add ` smoothScroll: true`, it works well, but when I comes to vuepress 2.0.0-beta.31, it don't works. Both are default-theme.

config.js
```
module.exports = {
    // plugins: ['vuepress-plugin-smooth-scroll'],    
    themeConfig: {
        smoothScroll: true,
        ...
```

I have tried to install that plugin, but it still has no effect.

**Comment by ulivz** [comment]
It‘s an issue of VuePress 2, please move on https://github.com/vuepress/vuepress-next to continue.
