### ISSUE TITLE
Router scrollBehavior to.hash fail after #272

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#298]
I notice that because of #291. I find the sidebar link's default behavior fails.

Recent commit about that is #272, merged in https://github.com/vuejs/vuepress/commit/6b6d26870ff2b83918ce3356c7b3553feb26c9c7

**Comment by meteorlxy** [comment]
https://github.com/vuejs/vuepress/blob/6b6d26870ff2b83918ce3356c7b3553feb26c9c7/lib/default-theme/Layout.vue#L179-L181

`$router.replace` will trigger `scrollBehavior`, so he set the `to.hash` branch `false`, which disabled the default behavior of sidebar links.

https://github.com/vuejs/vuepress/blob/6b6d26870ff2b83918ce3356c7b3553feb26c9c7/lib/app/app.js#L56-L64

**Comment by ryanriv** [comment]
It would be nice to restore the `{ selector: to.hash }` scroll behavior, but prevent it when we're making the `$router.replace` call while scrolling through the page. With the normal `{ selector: to.hash }`, it will scroll to the anchor when we do the `$router.replace` while we're scrolling, which leads to some jerky page jumps (especially when scrolling up).

Is there a way to do this? I've looked into it, and I haven't found any obvious solutions.

**Comment by ulivz** [comment]
Fixed at 6081a3d75261e3c8dcef5655cd264a8e2d1d554f.
