### ISSUE TITLE
Uncaught TypeError: AllHtmlEntities is not a constructor

### ISSUE THREAD

**Issue by elf-mouse** [vuejs/vuepress#2996]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. yarn create vuepress-site [optionalDirectoryName]
2. cd docs && yarn
3. yarn add -D webpack-hot-middleware
4. yarn dev

#### What is expected?

Run dev without error

#### What is actually happening?

- with `webpack-hot-middleware@latest` is error
- with `webpack-hot-middleware <= 2.25.0` is ok

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
    - System:
        - OS: macOS 11.6.1
    - Binaries:
        - Node: 17.3.0
        - Yarn: 1.22.17
        - npm: 8.3.0
    - Browsers:
        - Chrome: 97.0.4692.71
    - npmPackages:
        - @vuepress/core:  1.9.7
        - @vuepress/theme-default:  1.9.7
        - vuepress: ^1.9.7 => 1.9.7

**Comment by vfreitas-** [comment]
Just in case someone ends up in the same issue:

In my case I fixed the issue using a version < 2 of the html-entities library.
```
"html-entities": "~1.4.0",
```

For some weird case the lib was at 2.3.x in my package-lock what made webpack-hot-widdleware <= 2.25.0 not work either.

Aparentely on the version [2.0.0 they did a breaking change](https://github.com/mdevils/html-entities/releases/tag/v2.0.0) going from the class sintax to function sintax, what broke the webpack-hot-middleware usage (class sintax) [of the versions <= 2.25.0](https://github.com/webpack-contrib/webpack-hot-middleware/blob/v2.25.0/client-overlay.js#L38). The webpack-hot-middleware devs changed it to use the new [function sintax on the 2.25.1](https://github.com/webpack-contrib/webpack-hot-middleware/blob/v2.25.1/client-overlay.js#L38).

Resuming:

You must make sure these versions are ok in your package-lock/node_modules:

html-entities < 2 && webpack-hot-middleware <= 2.25.0
or
html-entities == 2.1.0 && webpack-hot-middleware >= 2.25.1

**Comment by linussvahn** [comment]
> Resuming:
>
>You must make sure these versions are ok in your package-lock/node_modules:
>
>html-entities < 2 && webpack-hot-middleware <= 2.25.0
>or
>html-entities >= 2.1.0 && webpack-hot-middleware >= 2.25.1

Thank you @vfreitas- this was it for me. Apparently I was using an old version of `webpack-dev-server` that had a 
`html-entities: 1.X.X` dep while my webpack-hot-middleware was at `2.25.1`.

**Comment by MrPluto0** [comment]
I met this error, because `webpack-dev-server:4.x` has `html-entity > 2`, which I has installed.
but `vue-press:1.x` has still used `html-entity:1.x`.
when `run dev`, the `vue-press` will import the `html-entiy: 2.x` belong to `webpack-dev-server`, so will report the `AllHtmlEntities is not a constructor`.

You can  delete the package you install: `webpack-dev-server > 4`, which won't affect you to use it.

**Comment by pullingoff** [comment]
Yeah it's definitely breaking and I solved the error by uninstalling html-entities@^2.3.2 with this
```
npm uninstall html-entities@^2.3.2
```

Thank you all.

**Comment by elf-mouse** [comment]
Thanks all :)

Finally, I found the solution for package.json

```json
{
  "resolutions": {
    "webpack-hot-middleware": "2.25.0"
  }
}
```
