### ISSUE TITLE
Extra space after the outbound link indicator

### ISSUE THREAD

**Issue by yzhang-gh** [vuejs/vuepress#3006]
- [x] I confirm that this is an issue rather than a question.

### Steps to reproduce

Please see the official website https://vuepress.vuejs.org/guide/using-vue.html

### What is actually happening?

In the first paragraph, when you have an outbound link in the middle of a sentence

<img src="https://user-images.githubusercontent.com/7588612/154712015-839eca8a-2f56-434f-b0f0-1da049446c4d.png" width=703>

There is a strange space after the icon as whitespace in between words is treated as a single character.

### What is expected?

Scroll down and find a standalone outbound link

<img src="https://user-images.githubusercontent.com/7588612/154712242-c1cb5024-f043-4968-b8e4-1a5125b1415f.png" width=452>

It looks all right as whitespace at the start and end of elements is ignored.

### Other relevant information

~~This can be fixed by removing the line break here~~

https://github.com/vuejs/vuepress/blob/38e98634af117f83b6a32c8ff42488d91b66f663/packages/%40vuepress/core/lib/client/components/OutboundLink.vue#L22-L23

**Comment by deverka** [comment]
Hi there, I'm having issues with this extra space after links. I found this issue here, while researching potential solutions. This issue seems to still be occurring and I wonder why did you close it? @yzhang-gh Do you have any tip for fixing it on my end? 
I'd appreciate your help.
