### ISSUE TITLE
Cannot have three levels of document links like in GitBook

### ISSUE THREAD

**Issue by rogersachan** [vuejs/vuepress#301]
The current sidebar does not allow for linkable first-level, second-level, and third level documents to exist simultaneously. Many projects that use gitbook take advantage of this and are hard to port because of this dependence. (Yes, you could just combine all the documents but then it is harder to convince the current maintainer to move)

![image](https://user-images.githubusercontent.com/7173984/39415254-0e4a4c0c-4c0f-11e8-90ac-2263bded22cf.png)
![image](https://user-images.githubusercontent.com/7173984/39415256-123710fc-4c0f-11e8-8efd-833a0335dfde.png)
![image](https://user-images.githubusercontent.com/7173984/39415258-14f33bf4-4c0f-11e8-9890-9c99fa7371c7.png)
See: https://basarat.gitbooks.io/typescript/content/docs/project/project.html

**Comment by ulivz** [comment]
Hmmm,  you can use default sidebar (h1/h2/h3) instead of custom sidebar (title/h1/h2) ...
