### ISSUE TITLE
Issue with Webpack and exclamation mark in path

### ISSUE THREAD

**Issue by x8x** [vuejs/vuepress#309]
This PR https://github.com/webpack/webpack/commit/04d8188063e9d9dc68673416da5cabdbd1ab95ba was merged into Webpack 4.6, it returns better error message to the user, would be good to upgrade webpack version in dev dependency to 4.6 ( now it's 4.5 )

**Comment by ulivz** [comment]
Will release it at 0.9.0: #419. 🚀
