### ISSUE TITLE
escape text in code block when lang is 'text' or not specified

### ISSUE THREAD

**Issue by lazzzis** [vuejs/vuepress#31]
Content in my markdown file:

![](https://i.loli.net/2018/04/15/5ad2937bd9fa4.png)

Run `vuepress dev`, it throws an error:

![](https://i.loli.net/2018/04/15/5ad293bbd8cf5.png)

Run `vuepress build`, it doesn't throw an error. But the page is not rendered as expected:

![](https://i.loli.net/2018/04/15/5ad293bac820b.png)

---

I guess the cause is that `code`  isn't escaped, when lang is 'text' or not specified.
 https://github.com/vuejs/vuepress/blob/86d405562f88576379111ddb495c0ec37f8e952d/lib/markdown/highlight.js#L8-L10

Since prism would automatically escape `code`:

```
> prism.highlight('<scheme>', prism.languages['html'], 'html')
'<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>scheme</span><span class="token punctuation">></span></span>'
```

A quick solution might be:

```js
const escapeHtml = require('escape-html')

function wrap (code, lang) {
  if (lang === 'text') {
    code = escapeHtml(code)
  }
  return `<pre v-pre class="language-${lang}"><code>${code}</code></pre>`
}
```

This solution works well both on `vuepress dev` and `vuepress build`. But I don't know if this is a good solution

**Comment by ulivz** [comment]
PR welcome.
