### ISSUE TITLE
url-loader and assets with relative paths not starting with './' in MD files

### ISSUE THREAD

**Issue by x8x** [vuejs/vuepress#310]
Although it's probably better to use relative path starting with `./` (`./images/image.png` instead of `images/image.png` ) for assets, that is more a JS import requirement. In MD files it should be perfectly fine to use `images/image.png`, but in this case `url-loader` will not include `image.png` into assets.
Thinking about people switching to VuePress, could `url-loader` be made a little more flexible and allow both cases?

**Comment by ulivz** [comment]
I just checked current VuePress and cannot reproduced it.

---

We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by calin-darie-evo-sapio** [comment]
It's reproducible with Vuepress 1.5.3
