### ISSUE TITLE
Setting dest: './' in config deletes the whole project

### ISSUE THREAD

**Issue by shiya** [vuejs/vuepress#322]
- Your OS: Mac OSX 10.12.6
- Node.js version: v10.0.0
- VuePress version: v0.4.1
- Browser version: Chrome 65
- Is this a global or local install? Global
- Which package manager did you use for the install? yarn

Hi :) I was just trying this out and fiddling with the config. If I set `dest: './'` in `.vuepress/config.js` hoping that will build my file into the root directory, running `vuepress build` actually deletes my entire project.

**Comment by shaodahong** [comment]
Build time can delete `dest` directory, you should set a directory (is not root)

**Comment by shiya** [comment]
Yea, I think there should be a warning at least because some people will attempt that, and if there isn’t a remote git backup everything is gone. I was going to build it to root so it can be served over GitHub pages.

**Comment by shaodahong** [comment]
I submitted pr, it shouldn't be a warning but an error
