### ISSUE TITLE
Possible to extend markdown while using config.yml?

### ISSUE THREAD

**Issue by luminarious** [vuejs/vuepress#326]
```
title: Rules
description: Short references
markdown:
    config: md => { md.use(require('markdown-it-deflist')) }
```

When written like this, the markdown config is turned into a string and not evaluated as a function. Is this intentional?

**Comment by ulivz** [comment]
Hmmm... why not using `config.js`?

**Comment by luminarious** [comment]
Because the documentation said I can, because YAML format is easier to read and write and apart from Markdown configuration it does work exactly as intended.

**Comment by luminarious** [comment]
All right, thank you for clarifying.

**Comment by berot3** [comment]
Sorry, so to once more clarify (_for newbies like me_) how can I use markdown-it-config in a `config.yml`?

It also would be awesome if you (@luminarious maybe?) could share a full `config.yml`-example to kickstart the own yaml-config!
