### ISSUE TITLE
use VuePress without markdown sources?

### ISSUE THREAD

**Issue by dasdeck** [vuejs/vuepress#330]
Hi!

I'm trying to use VuePress with my own custom theme that renders from json sources, instead of markdown. All works fine, until I try to build/export.

It seems to me VuePress indexes the pages to iterate from the markdown sources. Is there a way for me to register other pages besides markdown?

I tried the 'pages' option in the config, but it does not seem to have any effect.

Cheers & Thanks!

**Comment by luisDanielRoviraContreras** [comment]
And, the best would be providing a reproduction repository. That takes guessing work out of the way and saves us time.

**Comment by dasdeck** [comment]
Nevermind!
I'll use .md files.
Cheers!
