### ISSUE TITLE
Algolia Theme Customization

### ISSUE THREAD

**Issue by bayssmekanique** [vuejs/vuepress#331]
The Algolia theme is not responding to the theme customizations.

Looking at the `Navbar.vue` file, it is importing the aliased `@AlgoliaSearchBox`.  Changing the import to `./AlgoliaSearchBox.vue` resolves the theming issues, but I'm not certain if there is a reason that it was using the alias that I'm not seeing?

I'm happy to make a PR for this if there is no objection to the change.

**Comment by bayssmekanique** [comment]
As I look further, it appears that the intentions behind using the alias to be able to bypass the theme inclusion based on the `isAlgoliaSearch` attribute. 

https://github.com/vuejs/vuepress/blob/4bf56d75659d80a5545bca4a49b10c0761a73619/lib/webpack/createBaseConfig.js#L44-L46

Replacing the reference in the import will cause the style to always be bundled.  I'm not certain how to work around this and I foresee this happening in the future with similar modules that are optional dependencies so I don't know if having the user modify the import is necessarily the correct approach.

**Comment by bayssmekanique** [comment]
Solution submitted in PR #334 .

**Comment by ulivz** [comment]
Not clearly know what do you want to do.

**Comment by bayssmekanique** [comment]
@ulivz, if you eject the theme and then customize the `AlgoliaSearchBox.vue` file, the changes are not picked up because the `@AligoliaSearchBox` alias was pointing to `default_theme` directory in the root of the application.  The PR #334 changes the alias to point to a relative path, so by default it will use the root `default_theme` location, but when ejected it will use the customized vue file instead.

**Comment by ulivz** [comment]
Hmmm, so why not describe it by using a issue template at first 😅

if you want maintainers to help you to solve a problem or merge a pr, you should take us to your context first. I won't understand what you want to do util you said you use `eject`.

**Comment by meteorlxy** [comment]
@bayssmekanique 
In my opinion, `eject` aims to help user build there custom theme. In your own theme, you can import AligoliaSearchBox by something like `@theme/AlgoliaSearchBox.vue` with the help of `@theme` alias.

**Comment by bayssmekanique** [comment]
@meteorlxy, I'm not entirely following your point regarding the `@theme/AlgoliaSearchBox.vue`, as this is more addressing the `eject` condition, not necessarily theme overriding, which I think might be what you are addressing?

You are correct that with this change, it will point to custom ejected `vue` file, rather than the default theme file when the files have been ejected.  If the files haven't been ejected, then it will still point to the default vue file.  This is more in keeping with the way all the other components work, so I would think this component should work the same way.  In all the other components, the dependent components are referenced relative to the requesting components location, so this is doing the same for the `AlgoliaSearchBox.vue` component.

https://github.com/vuejs/vuepress/blob/d9b290b39863c51f60468b7091d82f52a6c7335a/lib/default-theme/Navbar.vue#L23-L26

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/pull/334#issuecomment-388035981

**Comment by brandonkelly** [comment]
@ulivz Why was this issue closed? Even if you don’t like the proposed fix, the core issue definitely still exists: createBaseConfig.js will only set `@AlgoliaSearchBox` to the path to AlgoliaSearchBox.vue in the default theme directory, even if you’ve supplied a custom theme.

Is there a way around this that doesn’t involve hacking VuePress? E.g. is it possible to override t he `@AlgoliaSearchBox` alias from enhanceApp.js or something?
