### ISSUE TITLE
Proposal to add a label in the menu

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#335]
Good I have a proposal to add a label in the menu (sidebar) and add it in a custom theme but I do not know if we add it to the main one or if it already has support, I would love some contribution or change in the code.

## SidebarLink.vue
```js
function renderChildren (h, children, path, route, maxDepth, depth = 1, tag) {

  if (!children || depth > maxDepth) return null
  return h('ul', { class: 'sidebar-sub-headers' }, children.map(c => {
    const active = isActive(route, path + '#' + c.slug)

   //New code <---------
    const title = c.title.replace('<!-- #new -->','').replace('<!-- #update -->','')
    let tag = null
    if(c.title.search('<!-- #new -->')!=-1){
      tag = 'new'
    } else if (c.title.search('<!-- #update -->')!=-1) {
      tag = 'update'
    }
    return h('li', { class: 'sidebar-sub-header' }, [
      renderLink(h, '#' + c.slug, title, active),
      renderChildren(h, c.children, path, route, maxDepth, depth + 1),
      tag?h('span', {class: `span-etiqueta span-${tag}`}, tag):null
    ])
  }))
}
```

Now you can add a tag in the menu like this

```md
## Design concept <!-- #new  -->
```

 y se ve asi con un poco de css

![screenshot_31](https://user-images.githubusercontent.com/31676496/39544659-c222c8b2-4e1c-11e8-9987-f1743df3c73d.png)

The idea is that it is a comment so that they do not change any aspect of the template, but this is the solution I found, I am open to propose a change or if there is already support to clarify how it is done thank you very much.

**Comment by ulivz** [comment]
Looks good. PR welcome.

**Comment by luisDanielRoviraContreras** [comment]
Okay thanks! I'll make a formal proposal.

**Comment by ycmjason** [comment]
Is there a PR?

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
