### ISSUE TITLE
What's the best way to escape all tags inside markdown?

### ISSUE THREAD

**Issue by Messiahhh** [vuejs/vuepress#337]
vuepress won't escape tags inside markdown, what if the existing project document has lots of tags(some match end tag while some doesn't, especially the single tag like <origin> will cause error) , Is there a nice way to escape them?

**Comment by ulivz** [comment]
Do you know the mood when people ignore your issue's template?

**Comment by ycmjason** [comment]
@Messiahhh 

You addressed two problems
1. Bad HTML in md
2. Chinese paths

My opinion on them:
1. This is obviously the problem of the user if they write bad code. We couldn't really help with that.
2. This is an issue that I noticed too. Do you wanna open another issue to address this following the issue template?

**Comment by ulivz** [comment]
> "vuepress won't escape tags inside markdown"?

markdown support writing HTML originally, and vuepress support using Vue at makrdown.

> ... chinese path does't work ...

Please open a issue with issue template, thanks
