### ISSUE TITLE
"Last updated" feature is coupled to Git

### ISSUE THREAD

**Issue by inosik** [vuejs/vuepress#340]
The "Last updated" feature implemented in #282 is tightly coupled to Git.

- It assumes Git is installed.

- It assumes the project uses Git. The process will crash if the directory is not a Git repository. This is a serious issue if you're just starting out with documentation in a new directory or if you (have to) use something other than Git.

_Also see https://github.com/vuejs/vuepress/pull/282#issuecomment-386590298._

**Comment by ulivz** [comment]
Thanks for reporting for that.

And I also concerned for that. since I believed that most of users use git so I let it go, but it's truly a potential problem, I will disable it by default.

BTW, we will make this feature as a plugin in the future.

**Comment by ulivz** [comment]
BTW, You have been saying this question so early 😅 we even haven't released it yet. awesome !

**Comment by jackmu95** [comment]
@ulivz What about using `mtime` from `fs.stat()` by default (because its always available) and make using the Git last modified timestamp an option?

**Comment by ulivz** [comment]
@jackmu95 See: https://github.com/vuejs/vuepress/issues/258#issuecomment-385284682

**Comment by ulivz** [comment]
Fixed at 272df57421d20907b5a1edecabcaad649641e791
