### ISSUE TITLE
Unable to serve the site correctly after adding a base

### ISSUE THREAD

**Issue by HanchengZhao** [vuejs/vuepress#342]
- Your OS : macOS 10.13.2 
- Node.js version : v10.0.0
- VuePress version: 0.8.4
- Browser version: Version 66.0.3359.117
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

I added a base in config.js file, `base: '/docs/'`, then ran `vuepress build`, but could only see the site in a bare minimum html content without correct styles and redirections after running `serve -p 80 -s .vuepress/dist`

I checked `dist` folder, all the `href`s have `/docs/` before it, but the file structure is still
```
+-- assets
    +-- css
    +-- img
    +-- js
+-- index.html
```
I wonder if it is the issue with reference? However, `vuepress dev` works fine, is there any way to solve it or I should expect a different behavior?

**Comment by meteorlxy** [comment]
You misunderstand what the `base` is.

**Comment by HanchengZhao** [comment]
@meteorlxy From my understanding, `base` is used for hosting docs under a subdomain, since I need to serve the site in a docker container and this container will be accessed through `domainURL/docs/`, so I need a way to serve the static site locally on `locolhost:8080/docs/`

**Comment by meteorlxy** [comment]
OK, let's take nginx and your docker container for example.

Nginx server on `localhost:8080`, with a reverse proxy config like: 
```conf
server {
  listion 8080;
  server_name localhost;
  location /docs/ {
    proxy_pass http://your-docker-container;
  }
}
```
In your docker container, your serve files by set the root to your `dist` directory.

Then with the help of `base: "/docs/"`, everything works well.

**Comment by HanchengZhao** [comment]
@meteorlxy Thanks for explaining, I think I understand this part, but it still doesn't work for me. I think you can produce it by doing this:

* `git clone https://github.com/vuejs/vuepress.git`
*  add a base to `vuepress/docs/.vuepress/config.js`, such as `base: '/docs/'`
*  `yarn build`
* `serve -p 80 -s vuepress`
*  go to `localhost:80/docs/`

For me, I can only see the bare html elements on the page

**Comment by ulivz** [comment]
Hmmm, are you sure that you know how static server works?

**Comment by ulivz** [comment]
As @meteorlxy said, you might understand what the base is, but you don't know how to make it work at production.

FYI:

- In development, we are not using a static server!!! and we pass `base` to the `vue-router`'s initialized config so it works fine;

- In production, you will need a static server with correct config! and `base` option will be used as `publicPath`, there is the doc for you: https://webpack.js.org/guides/public-path

**Comment by ulivz** [comment]
If you want to make it work at local, you can try:

1. set `dest` to `vuepress/docs`, ;
2. create a empty `index.html` at `vuepress/`
3. serve -p 80 -s vuepress
4. go to localhost:80/docs/

Hmmm .... it's not production 🤔.

**Comment by yyx990803** [comment]
`base: '/docs/'` means your `dist` folder should be served at `localhost:80/docs/`.

**Comment by HanchengZhao** [comment]
Thank you all for such quick and informative responses, problem solved. For later users reference, remember to match `urls` with `folder path`

**Comment by pascalandy** [comment]
@HanchengZhao do you use docker container to build you Vuepress project as well?
I would be curious to start exploring with it :)

**Comment by HanchengZhao** [comment]
@pascalandy Yes, all you need to do is to `vuepress build` and `serve` the static files inside dockerfile
