### ISSUE TITLE
code on cellphone (small sreen) doesn't look good

### ISSUE THREAD

**Issue by yungsem** [vuejs/vuepress#350]
My pages on the computer are all OK, but when I read my pages on my cellphone, the style of code doesn't look good, like this:
 
![_20180506225158](https://user-images.githubusercontent.com/13379032/39674546-20d23224-5180-11e8-944b-cc348b558a10.jpg)

And I want it to look  like this:
![_ _20180506225347](https://user-images.githubusercontent.com/13379032/39674565-5d2ab5ac-5180-11e8-8d17-42e871209db1.png)

Are there any ways to solve this problem? Thanks very much!

**Comment by ycmjason** [comment]
Notice this issue as well. We probably want to make the code area scrollable on the x axis.

I will work on that tonight if I got time.

**Comment by ulivz** [comment]
The previous fix(6514c8f) will import another issue: the language tip at right top side will be scrollable too. reverted it at 546bded.
