### ISSUE TITLE
Cannot open multiple dev server with global vuepress

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#355]
Current **global** vuepress does not support multiple instances.

In other words, we cannot open multiple `dev` server using global installed vuepress.

The reason is we are now using a **fixed**/**single** temp directory, i.e. `lib/app/.temp`. Each project will overwrite the same temp directory, which will cause collision.

I created a PR #354 for this.

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/issues/956#issuecomment-436736055
