### ISSUE TITLE
Default Theme NavBar Links Not Displayed Correctly on Mobile View 

### ISSUE THREAD

**Issue by raytu** [vuejs/vuepress#359]
VuePress version: 0.8.4

Hi, 

I notice that the NavBar dropdown links get wrapped and overlayed with the following links in mobile/vertical view. Please have a look at the attached screenshots to see what I mean. Thanks!

Desktop Screenshot:  
![image](https://user-images.githubusercontent.com/6403100/39723213-20d28056-5213-11e8-8ff3-222eecd088ac.png)

Mobile Screenshot (Issue in the Teaching submenu):
![image](https://user-images.githubusercontent.com/6403100/39723154-e6f7b0e0-5212-11e8-8da6-16fcdb7c5935.png)

**Comment by ycmjason** [comment]
Could you please kindly include a reproduction link? This would really help investigating the issue.

**Comment by raytu** [comment]
Link: http://huahongtu.me

**Comment by ycmjason** [comment]
@raytu thank you. And the source❓

**Comment by raytu** [comment]
```
module.exports = {
  title: 'Raymond Tu',
  description: 'Raymond (Huahong) Tu Personal Website',
  head: [
    ['link', { rel: 'icon', href: `/favicon-32x32.png` }]
  ],
  ga: 'UA-80227374-1',
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { 
        text: 'Teaching',
        **items: [
          { text: 'FIRE171: Capital One Machine Learning', link: '/teaching/fire171-s18/' },
          { text: 'FIRE271: Capital One Machine Learning', link: '/teaching/fire271-f18/' }
        ]**
      },
      { text: 'Research', link: '/research/' },
      { text: 'Publications', link: '/publications/' },
      { text: 'Media', link: '/media/' },
      { text: 'CV', link: '/cv/' }
    ]
  }
}
```

**Comment by ycmjason** [comment]
@raytu 

Fixed at #360

**Comment by ycmjason** [comment]
@raytu you could make the changes in #360 to temporarily fix the issue.

**Comment by ycmjason** [comment]
@raytu No worries! 😄 
If this will be released in the next version depends if they approve my changes.
