### ISSUE TITLE
Sidebar does not appear when using locale

### ISSUE THREAD

**Issue by hanxue** [vuejs/vuepress#362]
The following is my `docs/.vuepress/config.js`

```js
module.exports = {
  title: 'Wujiquan',
  description: 'Traditional martial arts',
  head: [
    ['link', { rel: 'manifest', href: '/manifest.json' }],
    ['meta', { name: 'theme-color', content: '#3eaf7c' }],
  ],
  serviceWorker: true,
  // theme: 'vue',
  themeConfig: {
    repo: 'hanxue/wujiquan-vuepress',
    editLinks: true,
    docsDir: 'docs',
    locales: {
      '/': {
        label: 'English',
        selectText: 'Languages',
        editLinkText: 'Edit this page on GitHub',
        nav: [
          {
            text: 'About Us',
            link: '/about/',
          },
          {
            text: 'Beijing',
            link: '/beijing/'
          },
        ],
        sidebar: {
          '/articles/': [
            'class-video', 
            'short-term-course-for-health'  
          ],
        },
      },
    }
  }
}
```

The documents exist for the linked sidebar articles

```
$ ls docs/articles/
class-video.md			short-term-course-for-health.md
```
![image](https://user-images.githubusercontent.com/760008/39738666-fcfbaaf2-52be-11e8-8907-09939806982a.png)

From the screenshot above, the red rectangle should be the sidebar, but it does not appear. 

### Environment
OS: MacOS 10.10.5
Node: v9.11.1
VuePress: 0.8.4
Browser: Chrome  68.0.3422.0
Local install using yarn

Actual repository: https://github.com/hanxue/wujiquan-vuepress

**Comment by ulivz** [comment]
```md
sidebar: {
          '/articles/': [
            'class-video', 
            'short-term-course-for-health'  
          ],
        },
```
means that the sidebar will only show at `/articles/` and `/articles/*`, but your current url is `/beijing/`.

## FYI:

1. If you don't set `sidebar: auto`, and also don't config `themeConfig.sidebar` at `.vuepress/config.js`, the sidebar will not be shown.

2. If you set `sidebar: auto`, the sidebar should only leverage the active page's headers as the sidebar's links. **(h1/h2/h3)**

3. If you configured `themeConfig.sidebar`, the sidebar will automatically displays the page's links according to your settings. the default depth is `1`, which extracts the `h2` headers (**pageTitle/h1/h2**). Setting it to `0` disables the header links, and the max value is `2`(**pageTitle/h1/h2/h3**)

**Comment by hanxue** [comment]
@ulivz many thanks for your help!
