### ISSUE TITLE
External Navbar Links

### ISSUE THREAD

**Issue by citruspi** [vuejs/vuepress#37]
In the [Navbar Links](https://vuepress.vuejs.org/default-theme-config/#navbar-links) section of the Default Theme Config documentation, there's an example including an external link:

```
module.exports = {
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Guide', link: '/guide/' },
      { text: 'External', link: 'https://google.com' },
    ]
  }
}
```

The external link ends up being a link to `http://localhost:8080/https://google.com`.

**Comment by ulivz** [comment]
Thanks for reporting for that! this issue has been fixed at https://github.com/vuejs/vuepress/pull/30 and now it's in code review, just wait for some minutes.
