### ISSUE TITLE
back to top button

### ISSUE THREAD

**Issue by RonaldZhao** [vuejs/vuepress#372]
Hope for a "back to top"button in the article page.

**Comment by RonaldZhao** [comment]
great!
Here is another question:does VuePress quest any http resource?Because I
want to use https on my blog.Thanks!(Sorry for my bad english)

2018-05-10 0:24 GMT+08:00 ULIVZ <notifications@github.com>:

**Comment by meteorlxy** [comment]
@RonaldZhao https or not is not determined by Vuepress. You don't need to worry about that.

**Comment by daltondiaz** [comment]
@o15a3d4l11s2  I liked to much of the idea, but I think the have to be more identity of VuePress. 

For now your logo is my favorite =]

**Comment by djdeo** [comment]
Or we can just use the arrow code to show this

&#8682;  or &#8679;   or &#8673; 

then change font size to make it bigger
