### ISSUE TITLE
outside links

### ISSUE THREAD

**Issue by tk1** [vuejs/vuepress#373]
I tried to create a link like this: `[HTMLoutside](../../notes/index.html)` to refer to a file outside of the vuepress-Site (but on the same web server, i.e. the vuepress generated site will be in a subdirectory of the whole site).

But in the created link the part ../.. is omitted and results ins `http://localhost:8080/notes/index.html` How can I link to files outside?

**Comment by ycmjason** [comment]
I am not sure if I understand your question correctly. Are you trying to link to something outside of your project root?

**Comment by tk1** [comment]
Yes. My site is consisting of several subdirectories. I want to replace the content of one of these subdirectories by vuepress-generated content. From this content I want to refer to files in the sibling directories.

**Comment by ulivz** [comment]
Hmmm... why not thinking more about it?

Correctly resolving a relative link depends on correct `window.href`(base). But you are testing on `localhost`. 

BTW, All relative links would leverage `route-link` from `vue-router`, which has handled for relative links.
