### ISSUE TITLE
如何添加自己的html、css文件

### ISSUE THREAD

**Issue by RonaldZhao** [vuejs/vuepress#374]
我现在有几个以前博客的html和css文件，请问如何添加进入，直接放进文件夹里build的适合会忽略。希望指点以下，多谢。

**Comment by meteorlxy** [comment]
`.vuepress/public`

**Comment by RonaldZhao** [comment]
thanks!

**Comment by meteorlxy** [comment]
@RonaldZhao 多看看docs再开Issue，你这种问题被大佬们看到就一巴掌拍死了:sweat_smile:

**Comment by RonaldZhao** [comment]
好的

2018-05-09 18:01 GMT+08:00 ULIVZ <notifications@github.com>:
