### ISSUE TITLE
Adding a Vue component to Vuepress

### ISSUE THREAD

**Issue by zephyrous** [vuejs/vuepress#377]
Hi all,

Congratulations on the great work you've done! I've built my company's documentation on Vuepress and it works seamlessly so far. However, I want to add a toggle component which will be showing initially hidden gif files.

Therefore, I've built a child component (ToggleGif.vue) under .vuepress/components. The template is as follows:

```
<template>
    <div data-url="[here goes the AWS link to the gif]" class="lxq-gif-box">
        <div class="lxq-gif-view">
            <img src="" class="lxq-gif-thumb" />
            <div class="play"></div>
        </div>
        <iframe></iframe>
    </div>
</template>

```
This component will appear more than 30 times in the documentation, but the data-url attribute value will be different in every instance, as another gif will be shown, depending on the documentation's section. What is the best way to approach this in order for the code to remain DRY? I've tried with props, but it doesn't seem to work (maybe because I call them from this child component?). Many thanks in advance.

My setup is as follows:
MacOS High Sierra, version 10.13.4
Node v8.6.0
Vuepress version: clone of latest github repo
Version 66.0.3359.139 (Official Build) (64-bit)
Local install
NPM

**Comment by ycmjason** [comment]
can you show your actual vue component?

**Comment by ycmjason** [comment]
> I've tried with props, but it doesn't seem to work

Can you show us your code?

**Comment by zephyrous** [comment]
Hi Jason, thanks for the prompt reply. Which part of the code? The ToggleGif.vue component and the config.js file?

**Comment by meteorlxy** [comment]
@zephyrous How you use your component

**Comment by ycmjason** [comment]
@zephyrous 
Can you show the `ToggleGif.vue` and how you use it?

**Comment by zephyrous** [comment]
In the markdown files, I insert the component (no slots, just a plain one to see if it works) under the yaml frontmatter, : e.g. 

## Heading 1
lorem ipsum text

<toggleGif></toggleGif>

## Heading 2
lorem ipsum text

**Comment by meteorlxy** [comment]
> I've tried with props, but it doesn't seem to work (maybe because I call them from this child component?)

So which part failed? You have not explained clearly

**Comment by meteorlxy** [comment]
And...emmm... could your please make your comments more .... human-readable? 😅

**Comment by zephyrous** [comment]
I'm sorry, I'm new to Vue, I'll try to explain it more thoroughly.

I thought that I could use props to insert an array of all the data-url attribute values and then use in the markdown files the prop value I needed. 

E.g. I inserted `<toggleGif data-url="prop1"></toggleGif>`, `<toggleGif data-url="prop2"></toggleGif>`, etc. (prop1, prop2, etc. are the hosted URLs). This didn't work (maybe because I call the props from the child component? Should I try to use slots instead? If yes, would they work without any reference to the parent component?

(I will make my comments more readable, sure.)

**Comment by ycmjason** [comment]
Use tree backticks(\`) to include code blocks:

```
hello world
```

**Comment by meteorlxy** [comment]
```js
<template>
  <div :data-url="dataUrl" class="lxq-gif-box">
    <div class="lxq-gif-view">
      <img src="" class="lxq-gif-thumb" />
      <div class="play"></div>
    </div>
    <iframe></iframe>
  </div>
</template>

<script>
export default {
  name: 'toggleGif',
  props: {
    dataUrl: {
      type: String,
      required: true
    }
  },
  mounted () {
    console.log(this.$el);
  }
}
</script>
```

`<toggleGif data-url="https://.........."/>`

Anyway, this is not a Vuepress-related issue, suggest you to learn Vue first.

**Comment by zephyrous** [comment]
Many thanks, guys, it's becoming clear now. However, I think that many Vue.js newbies (like me) are currently checking Vuepress, so maybe it makes sense to include more examples/content of adding Vue components in the excellent Vuepress documentation. :)

**Comment by meteorlxy** [comment]
@zephyrous Wow, I thought only who are familiar with Vue would have interest in Vuepress

**Comment by zephyrous** [comment]
I understand, Jason, you're right. I just want people to start using Vuepress extensively, without being discouraged by the fact that they don't know Vue (which we can all learn relatively fast, as the learning curve is not steep). Many thanks again.

**Comment by ulivz** [comment]
@zephyrous Looks like you have been clear, thanks to @ycmjason and @meteorlxy .
