### ISSUE TITLE
Support Chinese filename

### ISSUE THREAD

**Issue by fjc0k** [vuejs/vuepress#380]
Directly open this url and you will get a 404 page:

https://fjc0k.github.io/blogs/tiny-wall/%E5%A6%82%E4%BD%95%E5%B0%86%E6%A0%87%E9%A2%98%E8%AE%BE%E7%BD%AE%E4%B8%BA%E4%B8%80%E5%BC%A0%E5%9B%BE%E7%89%87%E6%88%96%E4%B8%80%E4%B8%AA%E8%A1%A8%E6%83%85%EF%BC%9F.html

But, it's ok if open the home url and click `如何将标题设置为一张图片或一个表情？`:
https://fjc0k.github.io/blogs/tiny-wall

repo: https://github.com/fjc0k/blogs

**Comment by fjc0k** [comment]
Uh, the issue is related to https://github.com/vuejs/vuepress/issues/344 and https://github.com/vuejs/vuepress/issues/307.

**Comment by ulivz** [comment]
Fixed at #473
