### ISSUE TITLE
How to use <keep-alive> on Pages in Vuepress.

### ISSUE THREAD

**Issue by AleksejDix** [vuejs/vuepress#384]
Is there any chance to use `<keep-alive>` on Pages in Vuepress.

My app is  collection of recipes.

I have recipes where i can set egg-timers and when the user cooks something it should be possible to switch to another recipes without reseting the current timer? 

help needed.

**Comment by hmatalonga** [comment]
I think you can use, just keep in mind that, keeping the components in memory will lead you to lose some of the life cycle hooks like created, mounted, etc.

You could replace those hooks with those specific to `keep-alive` such as `activated` and `deactivated`.

You can find the Vue docs details here:
[https://vuejs.org/v2/api/#keep-alive](https://vuejs.org/v2/api/#keep-alive)

**Comment by ulivz** [comment]
Thanks to @hmatalonga.

Thus, before open an issue with API usage, you should check out the existing docs, or go stack-overflow first.

**Comment by AleksejDix** [comment]
I red the docs and i know how it works. There is no way to keep the pages alive. It rerenders because Vuepress is not using a dynamic components. `<Content>` component could receive keep alive prop to enable this feature like it was added to Nuxt here. https://github.com/nuxt/nuxt.js/tree/dev/examples/with-keep-alive
