### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by thomask77** [vuejs/vuepress#385]
For an internal project, I need a full-text search function that is not based on an external search provider. The built-in "headers only" search is not enough.

A lot of other static site generators (e.g. gitbook) use "lunrjs".

Can this feature be added to vuepress?

**Comment by hmatalonga** [comment]
I suppose this will eventually be implemented since it was request previously perhaps as a plugin. At the moment, the solution would be to create a custom theme to implement that like mentioned here #261

**Comment by ulivz** [comment]
Since all pages are loaded on demand, so full text search will make it meaningless.

So we won't plan to implement it at default theme,  but maybe it can be done by a plugin in the future (Maybe v1.0.0).

**Comment by meteorlxy** [comment]
Duplicated #261

**Comment by jrappen** [comment]
Duplicate of #68

**Comment by jrappen** [comment]
@ulivz just to clarify, would [@vuepress/plugin-pwa](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-pwa) mentioned in #815 enable full text search across the whole site or be limited to visited pages?

If so, maybe you could:

- re-open this issue
- extend the pull request description of #815 to make it close this issue when merged
- add info to the docs on next branch

**Comment by klarkc** [comment]
Any update on this?
