### ISSUE TITLE
Auto active the link on sidebar  

### ISSUE THREAD

**Issue by trongdong** [vuejs/vuepress#391]
First of all, thanks for a great tool!  
When visiting https://vuepress.vuejs.org/guide/#how-it-works  
I can see that when scroll down, it would active the sidebar on the left.  
Installed vuepress on my local machine and start writing but I couldn't figure out how to make it work.  
Is this builtin feature?  
![anchor_link](https://user-images.githubusercontent.com/6128372/39859979-dad6ab54-5465-11e8-86a1-2c0e35157fcf.png)

**Comment by ycmjason** [comment]
The feature is implemented in https://github.com/vuejs/vuepress/commit/6b6d26870ff2b83918ce3356c7b3553feb26c9c7, but not released yet. 

It will be available in the next release.

**Comment by meteorlxy** [comment]
No, is not a builtin feature yet. I has been only implemented in the default theme now

**Comment by meteorlxy** [comment]
@ycmjason LOL, we do not focus on the same point 😃

**Comment by trongdong** [comment]
@ycmjason @meteorlxy got it, thank you very much!
