### ISSUE TITLE
Global vuepress fail to resolve custom theme

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#392]
Here's the simplest way to repro it:

1. Add a custom theme (take `vuepress-theme-vue` for example) to a new repo:
```
mkdir testrepo
cd testrepo
yarn add vuepress-theme-vue
```

2. Create `src` and base files, then the directory will be like this:

```
+-- src/
|   +-- .vuepress/
|       +-- config.js
|   +-- README.md
+-- node_modules
|   +-- vuepress-theme-vue/
+-- package.json
+-- yarn.lock
```

3. Set theme to `vue` in `config.js`

```js
module.exports = {
  theme: 'vue'
}
```

4. Run global `vuepress`
```
vuepress dev src
```

5. Error
```
Error: [vuepress] Failed to load custom theme "vue". File vuepress-theme-vue/Layout.vue does not exist.
```

6. Possible solutions

- Install custom theme globally (i.e. `yarn global add vuepress-theme-vue`）
- (Or) Install `vuepress` locally (i.e. `yarn add vuepress`) and run it locally (i.e. `yarn vuepress dev src`)

The cause is that we are using `require.resolve()` to resolve custom theme:

https://github.com/vuejs/vuepress/blob/145cf4f244a9b2fff3ee9a3c59985dcda9642aa6/lib/prepare.js#L139-L140

Is there a better solution?

**Comment by meteorlxy** [comment]
@hmatalonga Come on!

Look at the **last line of the first step** to repro it:
> yarn add vuepress-theme-vue

**Comment by hmatalonga** [comment]
@meteorlxy my apologies, I don't known how I how missed the first steps... I removed my dumb comments from the previous message xD

Anyway for using it via global vuepress does the idea of somehow fetching the theme contents makes sense to you?

**Comment by meteorlxy** [comment]
@hmatalonga 
As a global `cli`, it should work, I think.

In my opinion, we must consider every possible & sensible scenario

**Comment by ulivz** [comment]
> In my opinion, we must consider every possible & sensible scenario

once again, I want to emphasize the intention of Evan: **VuePress is mainly for vuejs**. 

So we don't have to think about all possible scenarios.

**Comment by ulivz** [comment]
I don't think this feature is sensible. If you just want to play around with VuePress, you can install it globally. but since you have a custom theme installed at local, why not installing it at local too?

**Comment by meteorlxy** [comment]
"If you just want to play around with VuePress" - and try some different themes randomly - this is sensible. 

Just because that we don't have various themes now

**Comment by ulivz** [comment]
> If you just want to play around with VuePress, and try some different themes randomly 

 it makes sense.

**Comment by cfharyadi** [comment]
Hi @ulivz @meteorlxy ,
I update my vuepress global-cli to version 0.10.0 and follow folder structure from @meteorlxy above, then I run 'vuepress dev src' but still produce error, the same as point.5 above.

However if I modify ~/.config/yarn/global/node_modules/vuepress/lib/prepare.js and add 
`path.resolve('node_modules')` in the paths array 
as in
`          paths: [
            path.resolve(__dirname, '../node_modules'),
            path.resolve('node_modules'),
            path.resolve(sourceDir)
          ]
`

It fix the error, I guess it resolve the theme location within main project working directory node_modules folder, if that make sense? 
What do you think? or did I miss something?

Thanks!
