### ISSUE TITLE
Support different file extensions

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vuepress#394]
I'd like to use VuePress to generate an RSS feed (or a sitemap, but there is an open issue already on making that built in), but as VuePress always generates HTML files, I'd like to propose a way around that. Given a filename of something.ext.md, then VuePress should generate something.ext, not something.html. If something.md is used, then the default is HTML.

**Comment by ulivz** [comment]
since VuePress is ONLY a static site generator, we DON'T plan to support this. and for such functionality, you should finish it by your own build process.

**Comment by cfjedimaster** [comment]
How is an XML file not static though? Or JSON?
