### ISSUE TITLE
[Discussion] Scaffolding a new project

### ISSUE THREAD

**Issue by hmatalonga** [vuejs/vuepress#396]
I was wondering if there is already any idea/intention of creating a way to scaffold a new project, for instance going for templates to use with vue-cli or a vuepress init command of sorts...

Is there any plans on this matter?

**Comment by ulivz** [comment]
We don't plan for it, there is not much point in creating a scaffolding for that, since the usage is easy enough and also no extra files are needed.

**Comment by ulivz** [comment]
We don't plan for it, there is no much point in creating a scaffolding for that, since the usage is easy enough and also no extra files are needed.

**Comment by ulivz** [comment]
Just published a boilerplate: https://github.com/ulivz/template-vuepress
