### ISSUE TITLE
How to enable "compiler-included" build for components?

### ISSUE THREAD

**Issue by genedronek** [vuejs/vuepress#398]
In vuepress, how to access the template **compiler-included** build for components, e.g...
```
docs/.vuepress/components/hello.vue
<script>
export default {
	name:		"hello",
	mounted()	{ console.log("hello mounted") },
	template:	`<div> hello vue </div>`,
}
</script>
```

**Comment by meteorlxy** [comment]
Change to `hello.js` and remove the `<script>` tag

**Comment by ulivz** [comment]
Do you want to access the source? or the compiled code?

**Comment by ulivz** [comment]
For source, you can use `raw-loader`.

For compiled code ... it's not allowed.
