### ISSUE TITLE
Multiplatform support similar to multi language

### ISSUE THREAD

**Issue by sausin** [vuejs/vuepress#40]
First off - thanks for the good work :+1: 

I was looking at the vuejs docs and I assume that the multi-language support coming to vuepress will generate similar docs, i.e.:

- some.url/path (default, English)
- br.some.url/path (portugese)
- and so on.

Since documentation will often be developed for multiple platform (browser, android, iOS) I was wondering if there could be some way to do it such that the "url+path" combination only changes similar to how it works for languages?

I must admit that I don't have a solution in mind for this (other than that the current selection is tied to localstorage and that the path remains the same until user selects another platform) but it would be awesome if this were to be possible.

Thanks!
Saurabh

**Comment by yyx990803** [comment]
That kind of setup is totally a userland problem and we're probably not going to provide a built-in solution.

**Comment by sausin** [comment]
Fair enough. Thanks for responding!
