### ISSUE TITLE
[feat] Allow override.styl for all themes, not just the default

### ISSUE THREAD

**Issue by ghys** [vuejs/vuepress#404]
Following the discussion in https://github.com/vuejs/vuepress/issues/339#issuecomment-386712922:

I would simply like to suggest removing the `options.useDefaultTheme` check here: https://github.com/vuejs/vuepress/blob/d9b290b39863c51f60468b7091d82f52a6c7335a/lib/prepare.js#L64

The benefit would be to still be able to change Stylus variables like `$accentColor` when making small modifications to the default theme, for example adding a component to a slot of the default Layout:
```vue
<template>
  <Layout>
    <PageFooter slot="page-bottom" />
  </Layout>
</template>

<script>
import Layout from '@default-theme/Layout.vue'
import PageFooter from 'PageFooter.vue'

export default {
  components: {
    Layout,
    PageFooter
  }
}
</script>
```

Other custom themes could also allow local overrides by having `@import '~@temp/override.styl'` in their style. If not the file would still be copied in `app/.temp` but won't have any effect.

**Comment by lunaceee** [comment]
I added a `Layout.vue` component with the code example here to `theme/Layout` footer and getting the `[Vue warn]: Unknown custom element: <Layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.` error. Any suggestions? Thanks!
