### ISSUE TITLE
lastUpdated选项

### ISSUE THREAD

**Issue by RonaldZhao** [vuejs/vuepress#407]
这个参数是只要设置为true或者一个字符串就可以了还是还需要怎么样？我怎么弄都显示不出来更新时间。求助~我的[config.js](https://github.com/RonaldZhao/blog_source/blob/master/docs/.vuepress/config.js)

**Comment by meteorlxy** [comment]
这个要显示出来时间，需要：

1. 项目已经通过`git init`初始化为一个git repo
2. 想要显示时间的`.md`至少commit过一次

其实个lastUpdate选项就是显示当前页面的md文件最后一次在commit中修改的时间

**Comment by RonaldZhao** [comment]
我的文件结构是这样的：
然后我是在VuePressBlog目录下执行git init的，不是global vuepress，是通过在VuePressBlog目录中执行npm
install -D vuepress安装的。


2018-05-11 17:23 GMT+08:00 Liu Xinyu <notifications@github.com>:

**Comment by meteorlxy** [comment]
你直接npm安装的0.8.4版本，没有这个功能

**Comment by meteorlxy** [comment]
@RonaldZhao 你不要只用邮件回了，改了很多东西你都没看到

**Comment by RonaldZhao** [comment]
不好意思，我不知道邮件显示的有问题。。。
那请问要怎么安装最新版？

**Comment by ulivz** [comment]
Thank you for waiting, No accident, we will release 0.9.0 tomorrow !
谢谢你的等待，不出意外，我们明天会 release 0.9.0！

**Comment by RonaldZhao** [comment]
所以明天这个功能就官方支持了？期待~~~~~~

**Comment by ulivz** [comment]
Closing it since I have open a pre-release issue at #419

**Comment by xkcoding** [comment]
@ulivz @RonaldZhao @meteorlxy I have been update the  0.9.0, but it still doesn't work. it's my [config.js](https://github.com/xkcoding/note.xkcoding.com/blob/f41a6a12f9dbd850818d8d9d5c6ad3a7c5b49586/.vuepress/config.js#L51) and my [page](https://note.xkcoding.com/notes/Java/java-2-util-image.html)

**Comment by louistin** [comment]
> 这个参数是只要设置为true或者一个字符串就可以了还是还需要怎么样？我怎么弄都显示不出来更新时间。求助~我的[config.js](https://github.com/RonaldZhao/blog_source/blob/master/docs/.vuepress/config.js)

你好, 请问你的这个问题后来怎么解决的, 我现在也遇到了这个问题

**Comment by tangrenshushu** [comment]
显示是显示了，就是无论怎么commit，时间都不再更新了。很是奇怪。
