### ISSUE TITLE
how to fold article ？

### ISSUE THREAD

**Issue by a298003154** [vuejs/vuepress#408]
制作博客过程中
想使用类似 ``hexo`` 的方法，在 ``.md`` 里添加  使得文章得以折叠。
但是在 ``import md`` 文件的时候，依然会通过 ``render`` 函数 把整篇文章 转化为 vue 所识别的内容。
这个功能，我应该通过什么方法去实现呢

**Comment by meteorlxy** [comment]
不是很懂折叠文章是什么意思，给个例子？

**Comment by a298003154** [comment]
@meteorlxy 
hexo 的 readmore 功能

![image](https://user-images.githubusercontent.com/24939100/39914051-6d0bb016-5536-11e8-9531-28df71146794.png)

**Comment by meteorlxy** [comment]
你是在自己的主题中手动`import md`注册成组件，想要在同一页展示吗？

**Comment by meteorlxy** [comment]
然后这个read more是在当前页面就展开全文，还是跳到文章的页面？

如果是跳到文章的页面而不是直接在当前页展示的话，我建议你在`frontmatter`里面加一个`desc`之类的字段，然后把想要显示摘要手动填进去，在文章列表只显示摘要就行了。毕竟Vuepress目前并不直接支持提取md文件的部分内容。

**Comment by a298003154** [comment]
@meteorlxy 
哈，我就是想提取markdown文件的部分内容。
readmore 是当前展开 还是跳到对应文章页面都没问题啦。
弄了两天，醉了醉了

**Comment by meteorlxy** [comment]
@a298003154 

https://github.com/vuejs/vuepress/blob/e66a9ed15f1bac9a0609ec95706966905b722bde/lib/webpack/createBaseConfig.js#L113-L129

现在默认是通过Vuepress自己的`mardown-loader`，再过一下`vue-loader`加载`.md`文件。你要想提取部分内容可以通过`config.js`文件里面的`chainWebpack`自己加一个额外的解析规则试试。

**Comment by ulivz** [comment]
等插件机制 release 以后，你将会有权利在编译期向 $page 注入任意的字段，对于你说的这个feature，你可以在 $page 中注入你想要的概要内容。然后结合一个自定义的 Layout 组件，你将可以很方便地实现此功能。

 不过 1.0.0 还很远。

**Comment by meteorlxy** [comment]
@ulivz 😅 “还很远”真是充满了忧桑。。

**Comment by ulivz** [comment]
1.x is going to reach `beta` stage, so you can start to write a plugin for that.
