### ISSUE TITLE
[feature request] Allow themes to set default themeConfig

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#409]
A theme may need some basic config to make it run, or some default config that don't need to be set mannully by users.

So I propose to allow themes to set default `themeConfig`, which can be overridden in `siteConfig.themeConfig`.

I've put it together with another feature in PR #315 , which has not been approved yet. But I think theme default config could be an essential feature for a theme maker, so I decide to extract it to a single PR #410.

**Comment by ulivz** [comment]
A theme would be used for many users, `repo`、`editLinks` and most of other options would be different to different users. so there is no meaning to set the default theme config at a default theme.
 
BTW, this feature will take some noises when a theme set `locales` but a user doesn't want to use 
i18n.

**Comment by SebastianNiemann** [comment]
While this might be true for public shared themes, what about private themes, where one has fully control over all projects using them?

At the company I am working for, we are currently using vuepress for 24 different websites (with at least 6 more to be converted from wordpress in the following months). All sites are sharing the same theme and multiple, redundant options inside the config. It would be perfect for us if this could be refactored into a theme config, reducing the maintenance overhead.

I think such use-cases could greatly benefit from this, while I totally see your point that this is not best practice for public themes.

**Comment by meteorlxy** [comment]
A new issue comes #662
