### ISSUE TITLE
[Discussion] Multiple Language Support

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#41]
After exploration with current working flow and code details, and tried to implement i18n with different approach. finally I think that the idea from @egoist's docute would be minimalistic and useful enough for now.

Let me describe the story.

Since most users (Vue is also the same) will only consider supporting the main language support at the beginning, so I pass in an array that contains link items to nav: 

```js
module.exports = {
  themeConfig: {
    nav: [
      {
        text: 'Guide',
        link: '/guide/',
      },
      // rest pages ...
    ],
  }
}
```

Then one day, I find I want to add translations for my docs, taking adding Chinese translation as an example, I will need to do the following work to achieve i18n:

1. Create a directory in the name of language at `.vuepress`
2. Change the config to:

```js
const langs = [
  { text: 'English', link: '/' },
  { text: '简体中文', link: '/zh/' },
]

module.exports = {
  themeConfig: {
    nav: {
      default: [
        { text: 'Guide', link: '/guide/' },
        { title: 'Languages', type: 'dropdown', items: langs },
      ],
      zh: [
        { text: '指南', link: '/zh/guide/' },
        { title: '选择语言', type: 'dropdown', items: langs },
      ]
    }
  }
}
```

There is a WIP PR for this solution: https://github.com/ulivz/vuepress/pull/1 (i18n + Chinese Translations)

This solution also has some issues:

1. No consideration for i18n for Vue Component. (Using vue-i18n or making an another tiny lib?)
2. No consideration for the two field `title` and `description` at config. (Don't have a good idea now.)

Here I just said my thoughts, free free to share your thoughts, so that we can deliver multiple language support faster and better.

Thanks.

@yyx990803 @egoist 

## Updated

Finished Chinese translation and open a complete PR: https://github.com/vuejs/vuepress/pull/48

**Comment by yyx990803** [comment]
Closing in favor of the PR. Let's continue discussion there
