### ISSUE TITLE
sidebar sub header highlighting onscroll

### ISSUE THREAD

**Issue by cb-sumana** [vuejs/vuepress#412]
Found the code for highlighting the current region in the commit '6b6d26870ff2b83918ce3356c7b3553feb26c9c7'. When will this be published in the package?

**Comment by ulivz** [comment]
Thank you for waiting, No accident, we will release 0.9.0 tomorrow !

**Comment by ulivz** [comment]
Closing it since I have open a pre-release issue: #419
