### ISSUE TITLE
build/dev env - document this.$ssrContext

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#420]
Hey there.

I haven't found any documentation to what `this.$ssrContext` is.
Maybe this is already what I am looking for.
I want to know, whether or not I am in a dev or build env.

Thanks in advance

**Comment by ulivz** [comment]
This shouldn't be included and you should go: https://ssr.vuejs.org/en/head.html

**Comment by MartinMuzatko** [comment]
Thanks @ulivz I couldn't find that first in the docs of ssr.vuejs.org.
I think if I want  to know whether or not I am in a dev or prod env, I should use webpack end together with 
`ENV=DEV vuepress dev`
I just wondered if vuepress doesn't already come with an environment variable if I run `vuepress dev`.

I want to use a different api endpoint when testing my static site generated content along with lambda functions offline or online.

**Comment by igorkosta** [comment]
Hi @MartinMuzatko!

Have you figured out how to use `env` variables with `vuepress`?

**Comment by adamdehaven** [comment]
@ulivz real late to the convo here, but is there anything wrong with using `this.$ssrContext` in `created()` in order to do things only during the build process?

I'm currently using it to inject meta content into the `<head>` during the build process. 😬
