### ISSUE TITLE
[Roadmap]

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#421]
# ~0.9.1~

- Support filename that contains non-ASCII and unicode chars (#473)

# 0.11.0
- Back to top (#386)

# 1.0.0

- Plugin Support
- Attempt to enable inclusion of partial markdown  (#227)
- `TBD` - Builti-in deploy command (#237) 

# 1.1.0

- Asset handling via front matter (#79)

**Comment by yliaho** [comment]
Nice! Can't wait for plugin support! 😍

**Comment by trongdong** [comment]
@ulivz great to see this! Can't wait for including partial markdown

**Comment by marinintim** [comment]
Looking forward to plugin support 👍 

If there's anything I could do to support that / develop that, just let me know. I see that there's already PR which is for some reason marked as 'abandoned'.

**Comment by ulivz** [comment]
Let move to https://github.com/vuejs/vuepress/wiki/VuePress-Roadmap
