### ISSUE TITLE
The error message of port in use is not correct. Please check whether it is hard-coded.

### ISSUE THREAD

**Issue by hw712** [vuejs/vuepress#424]
In my laptop, port 8080 is in use, port 8081 is free. 

When I start `vuepress dev` command without any further configuration, it said port 8081 is in use. **I think it should be 8080, and perhaps this error message is hard-coded. Please check it.**

```
D:\JavaScript\DemoVuePress>vuepress dev
Extracting site metadata...
Compiling

* Client █████████████████████████ compiling (0%)


× ｢serve｣:  { Error: listen EADDRINUSE 127.0.0.1:8081
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)

  VuePress dev server listening at http://localhost:8081/
```
According to the vuepress documents, the default port is 8080, which is not free in my laptop, so I changed the default port to anther free port, everything is okay.

## Working Environment ##
- Windows 7
- Node.JS 8.9.3
- VuePress 0.8.4

**Comment by meteorlxy** [comment]
Reproduced.

It's not hard-coded for sure.

Maybe related to the `portfinder`

**Comment by meteorlxy** [comment]
It could be an issue of `webpack-serve` on Windows.

The simplest way to repro:
```
vuepress dev --port=8081
```

As `8081` is hard-coded in `webpack-server` ([Code link](https://github.com/webpack-contrib/webpack-serve/blob/c9235b5fc5135257809c15994b84b03088afd211/lib/server.js#L118))

**Comment by ulivz** [comment]
It's indeed a bug of `webpack-serve` and still unresolved. see: https://github.com/webpack-contrib/webpack-serve/issues/37#issuecomment-370144286.
