### ISSUE TITLE
light-box

### ISSUE THREAD

**Issue by RonaldZhao** [vuejs/vuepress#434]
希望能有一个图片点击放大查看的功能（比如知乎的），因为有时候需要放大图片观看。感谢

**Comment by LinFeng1997** [comment]
我的思路是：可以找一个这样的 vue 组件，然后写一个 markdown-it 的自定义插件，最后增加一个配置项来控制是否允许图片点击放大查看？

**Comment by egoist** [comment]
Maybe this could a feature for the default theme 😄using https://github.com/francoischalifour/medium-zoom

**Comment by ulivz** [comment]
@egoist Amazing!

**Comment by rajaraodv** [comment]
@egoist I'm new to vue but am mainly using this to generate docs. I love vuepress but the image zoom is a big pain point right now. Would love to see this capability in vuepress. Also wondering if we can use the medium-zoom in the mean time, if so how?

**Comment by egoist** [comment]
@rajaraodv create a Vue component using medium-zoom and use the component in your docs.

**Comment by ulivz** [comment]
See: [@vuepress/plugin-medium-zoom](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-medium-zoom)

**Comment by rowild** [comment]
I thought issues have to be written in English...
