### ISSUE TITLE
Url with params will redirect to a wrong place if the html file name contains UPPERCASE letter

### ISSUE THREAD

**Issue by xiaotianxia** [vuejs/vuepress#441]
- Mac OS
- Node.js version v8.11.1
- VuePress version v0.8.4
- Browser version chorme 66
- Is this a global or local install? global
- Which package manager did you use for the install? npm

Url with params will redirect to a wrong place if the html file name contains UPPERCASE letter
eg.
My file name is  'demo_Ademo', when I visit url as 'https://mydomain/js/demo_Ademo.html?a=1111' ,it will redirect to 'https://mydomain/js/demo_ademo?a=1111', and then returns a notFound page

**Comment by meteorlxy** [comment]
Time traveller

**Comment by xiaotianxia** [comment]
for demo try [this](https://epic-yonath-d41859.netlify.com/js/upload_using_fileReader_and_createObjectURL.html)
and then [this](https://epic-yonath-d41859.netlify.com/js/upload_using_fileReader_and_createObjectURL.html?t=123456)

**Comment by ulivz** [comment]
@xiaotianxia 

Please check with your static server config.

Why `**/upload_using_filereader_and_createobjecturl.html/?a=1` was redirected to `**/upload_using_filereader_and_createobjecturl/?a=1` which isn't caused by `vuepress` 😅

**Comment by xiaotianxia** [comment]
@ulivz ok... thx!

**Comment by xkcoding** [comment]
@xiaotianxia are your website deployed by Netlify?? I got the same error..but I don't know how to fix it. Can you help me?

**Comment by xiaotianxia** [comment]
@xkcoding make sure that all your file name is  lower case 😂 :

**Comment by xkcoding** [comment]
@xiaotianxia thx for your apply. I resolved my problem. #457
