### ISSUE TITLE
deploy production 404 when reloading or direct link

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#444]
- Your OS windows
- Node.js version 8.4.0
- VuePress version 0.8.4 
- Is this a global or local install? global
- Which package manager did you use for the install? npm

Repo https://github.com/lusaxweb/vuesax

I have the documentation created in vuepress and everything is excellent but in some documents I see 404 apparently does not compile the html

## Example Error

visitar https://lusaxweb.github.io/vuesax/documents/

Then click on `theme/colors` in the menu

being on that page reload and you will find a `404`

Same as going directly to the link https://lusaxweb.github.io/vuesax/documents/theme/colors.html

----

Check the documents on the page and just add some html but not all it's as if I did not compile some but others if

here the link of the docs before processing (**.md**) https://github.com/lusaxweb/vuesax/tree/master/docs

And the documents after doing deploy and passing them to **html** https://github.com/lusaxweb/vuesax/tree/gh-pages 

The documents do not match and they are not complete but what I do not understand is because if they work on the page but when I access them directly as
https://lusaxweb.github.io/vuesax/documents/theme/colors.html no ?

**Comment by ulivz** [comment]
Each sub folder should have at least  a `README.md`(`index.html` will be generated) so that the static server can work correctly.

**Comment by luisDanielRoviraContreras** [comment]
I have a directory with `README.md` but I still have the same problem

https://lusaxweb.github.io/vuesax/documents/layout/

**Comment by lloydjatkinson** [comment]
Same problem here.
