### ISSUE TITLE
Navbar Link highlighting issue with multilanguage configuration

### ISSUE THREAD

**Issue by iCarnagy** [vuejs/vuepress#445]
- Your OS: **Windows 7**
- Node.js version: **v9.7.0**
- VuePress version: **v0.8.4**
- Browser version: **Chrome 66** (Doesn't work in IE or Firefox either.)
- Is this a global or local install? **Global**
- Which package manager did you use for the install? **npm 6.0.1**

I recently internationalized my vuepress site and noticed that the Nav links where underlined incorrectly in the new added language (german). Not only the selected Page was underlined, but also the Start button (as seen in the screenshot below. This is the case in Chrome, Firefox and IE, I inspected the DOM and noticed that the `nav-link router-link-active` class simply was not removed from the link when clicking on another one. However, this is only the case in the German version of the page, the English version with the same file structure and configuration works just fine.

Screenshot of the german version:
![vuepress](https://user-images.githubusercontent.com/11553349/39998966-f76b69c4-5787-11e8-8e3c-2eea4309cadf.PNG)

Here a gist of my config file: https://gist.github.com/iCarnagy/4d0995c33a37d2ca845c2c3161f3978d

**Comment by ulivz** [comment]
Could you provide the reproduction repo instead of only config?

**Comment by iCarnagy** [comment]
@ulivz Sorry, I uploaded the files to this repo: https://github.com/iCarnagy/vuepress-multilang-issue

**Comment by ulivz** [comment]
This issue is because we only apply **[exact](https://router.vuejs.org/en/api/router-link.html) match mode** for the root path "/".

Fixed at 596014f01b5adbb47631fc4fe8995f14f3ef3496
