### ISSUE TITLE
How can I render the $page. excerpt to html

### ISSUE THREAD

**Issue by Bloss** [vuejs/vuepress#446]
I try to add `@md: require('path').resolve('node_modules/vuepress/markdown')` in webpack config, then I can use the vuepress md.render to render $page. excerpt, but I failed

**Comment by ulivz** [comment]
Could you provide reproduced repo?

**Comment by Bloss** [comment]
@ulivz 
repo: https://github.com/Bloss/vuepress-issue-446
At [config.js](https://github.com/Bloss/vuepress-issue-446/blob/master/docs/.vuepress/config.js#L24-L29), I try to add `@md` alias

Then, I try to import vuepress's `md.render` function at [ArticleCard](https://github.com/Bloss/vuepress-issue-446/blob/master/docs/.vuepress/theme/ArticleCard.vue#L15), but I failed

So how can I render the $page.excerpt to html : )

**Comment by ulivz** [comment]
I don't know why you need to import the `lib/markdown`. You cannot import it at client side since the internal markdown module depends on `chalk` which will check for `process` of node only.

If you want to render `$page.excerpt`, you can do:

In your markdown:

``` md
I am excerpt

<!-- more -->

I am content
```

In your custom component:

``` vue
<div v-html="$page.excerpt"></div>
```

**Comment by Bloss** [comment]
@ulivz `<div v-html="$page.excerpt"></div>` render `$page.excerpt` as raw text(markdown formatter), but what I need is to render it to html

**Comment by ulivz** [comment]
@Bloss why `$page.excerpt` within `v-html` will be rendered as raw text?  Did you really try?

**Comment by ulivz** [comment]
FYI:

The markdown text in  `excerpt ` range will also be compiled to HTML string.

**Comment by ulivz** [comment]
> Unfortunately it is not the case

So what's your case? 😅

**Comment by tdurieux** [comment]
I just told you: that the content of excerpt is not compiled to HTML.

**Comment by ulivz** [comment]
@Bloss Sorry, I just made a wrong judgment, it's truly not compiled to HTML...

**Comment by ulivz** [comment]
Let's continue at #458

**Comment by tdurieux** [comment]
Surprisingly...

**Comment by Bloss** [comment]
@ulivz It's ok, Let's continue
