### ISSUE TITLE
Need service worker update alert window.

### ISSUE THREAD

**Issue by EYHN** [vuejs/vuepress#453]
In the default theme, when the service worker is updated, the page will not have any prompts. I suggest adding a alert window to remind the user that the page has been updated.

![update-toast](https://user-images.githubusercontent.com/13579374/40092524-47eb7628-58f0-11e8-84d7-40c841466029.png)

**Comment by ulivz** [comment]
PR welcome. but the best to build a suitable vue-styled UI. ❤️
