### ISSUE TITLE
Sidebar links are not updated when changing language

### ISSUE THREAD

**Issue by george-silva** [vuejs/vuepress#454]
- Linux Mint 18
- Node.js 10
- VuePress 0.84
- Is this a global or local install? Global
- Which package manager did you use for the install? NPM

---

Hello!

Congratulations on the project! Marvelous!

Minor problem:

1. I have a simple website configured published in github pages (but I found this while testing locally)
2. I've created three simple pages and added to the sidebar, so far so good.
3. Created the same three pages in the i18n version (pt-br)
4. When I click the change language dropdown, it changes the language **only** for the page I'm looking at. It does not replace the links for the sidebar, for example.

* Page: https://george-silva.github.io/
* Repo: https://github.com/george-silva/george-silva.github.io.vuepress

**Comment by meteorlxy** [comment]
check the `config.js` of official docs to find how to set theme locale sidebar

https://github.com/vuejs/vuepress/blob/master/docs/.vuepress/config.js

**Comment by ulivz** [comment]
When using i18n, you need add `locales` as well as the `themeConfig.locales`:

``` js
module.exports = {
	locales: {
		'/': {
			// ...
		},
		'/pt-BR/': {
			// ...
		}
	},
	themeConfig: {
		locales: {
			'/': {
				sidebar: [
					// ...
				]
			},
			'/pt-BR/': {
				sidebar: [
					// ...
				]
			}
		}
	}
}
```

**Comment by george-silva** [comment]
Thanks. That was not clear on the docs and I did not tried on the
documentation (change locale).

Thanks

Em ter, 15 de mai de 2018 23:50, ULIVZ <notifications@github.com> escreveu:
