### ISSUE TITLE
[Netlify Deploy] refresh page got 404 error

### ISSUE THREAD

**Issue by xkcoding** [vuejs/vuepress#457]
OS: Mac high sierra
Node.js version: v8.5.0
VuePress version: 0.8.4
Browser: chrome 66.0.3359.139
local install
package manager: yarn

problem:
I enter a page by sidebar link like this
![image](https://user-images.githubusercontent.com/10429917/40094175-19b2e81e-588b-11e8-8ae9-a6e8a7b31c2d.png)
It's OK .

But when I use link like https://note.xkcoding.com/notes/Git/git-note.html
I got 404 error, and browser target link missing suffix `.html`
![image](https://user-images.githubusercontent.com/10429917/40094209-452ce4cc-588b-11e8-9807-d4959983881b.png)

It also appears 404 error when I refresh page

Is this a bug??

Sorry for my poor English..

**Comment by xkcoding** [comment]
emmmm...I deployed by Netlify... I don't know which web server on Netlify

**Comment by ulivz** [comment]
Sorry but I cannot reproduce it, would you please do more investigation by yourself? 

If you had any progress or could give any reproduction method, I will reopen it.

**Comment by xkcoding** [comment]
@ulivz I found may be caused by this https://www.netlify.com/docs/redirects/#basic-redirects

**Comment by xkcoding** [comment]
similar to https://github.com/developit/preact-boilerplate/issues/101

However I don't know how to fix it

**Comment by iampaul83** [comment]
@xkcoding this is cause by the **Pretty URLs** feature of Netlify, and can be turned of in the **Asset optimization** setting:

![Asset optimization setting](https://i.imgur.com/BHT6uwE.png)

https://determined-volhard-204fe8.netlify.com/notes/Git/git-note.html

**Comment by ulivz** [comment]
Thanks to @iampaul83. 

@xkcoding Is it helpful to you?

**Comment by xkcoding** [comment]
@iampaul83 It's very helpful, I am deeply grateful !

@ulivz thank you so much !

**Comment by siddhartharora02** [comment]
create a file in your vue root directory - `netlify.toml`
and put this code in the file
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

```
commit and push to your git repo

**Comment by WouterNigrini** [comment]
> create a file in your vue root directory - `netlify.toml`
> and put this code in the file
> 
> ```
> [[redirects]]
>   from = "/*"
>   to = "/index.html"
>   status = 200
> ```
> commit and push to your git repo

This fixed it for me. Thanks
