### ISSUE TITLE
如何应用UI库，例如iview、elementUI

### ISSUE THREAD

**Issue by kirazxyun** [vuejs/vuepress#459]
你好，我想要在主题中使用iview或者elementUI作为UI框架，便于实现效果，请问要怎么加，我试过在layout中加是ok的，但是文档描述是layout会对每一个md文件执行，这样的话ui框架就会被重复的注册。
请问在哪边加是比较好的呢？

**Comment by fjc0k** [comment]
[`enhanceApp.js`](https://vuepress.vuejs.org/zh/guide/basic-config.html#%E5%BA%94%E7%94%A8%E7%BA%A7%E5%88%AB%E7%9A%84%E9%85%8D%E7%BD%AE) 了解一下。

**Comment by ulivz** [comment]
https://vuepress.vuejs.org/zh/guide/basic-config.html#%E5%BA%94%E7%94%A8%E7%BA%A7%E5%88%AB%E7%9A%84%E9%85%8D%E7%BD%AE
