### ISSUE TITLE
[feat:build] control BundleRenderer shouldPrefetch option

### ISSUE THREAD

**Issue by ghys** [vuejs/vuepress#463]
VuePress leaves the BundleRenderer's _shouldPrefetch_ option unset - it used to be `() => false` but was disabled then removed by @yyx990803 here:

https://github.com/vuejs/vuepress/commit/9719bc3246afcf77f69eaf94a34f0d6b2fa9c95b#diff-26b681bd4dac10f25d5293c7595c435bL56

The VuePress documentation site I'm building has 400+ pages, prefetching everything is a bit overkill and a bandwidth/server hog. I'd like to suggest a _"prefetch"_ option in `options.siteConfig` to let the user control the prefetching in `config.js`. Could be either a boolean or the actual function expected in `createBundleRenderer`. If unset, the option will not be set and the current behavior will remain.

**Comment by ulivz** [comment]
PR welcome.
