### ISSUE TITLE
Request: render compiled html for markdown $page.title

### ISSUE THREAD

**Issue by mirisuzanne** [vuejs/vuepress#464]
Here is a reproduction repo: https://github.com/mirisuzanne/vuepress_markdown_demo

**Comment by ulivz** [comment]
This feature would have some conflict with a previous commit: https://github.com/vuejs/vuepress/commit/53c8489

PR welcome.

**Comment by SebastianNiemann** [comment]
Could you be more specific onto how it is thought to be working? An example would be helpful 🙂 

Would like to contribute to this.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
