### ISSUE TITLE
Page Level Encryption

### ISSUE THREAD

**Issue by toddpi314** [vuejs/vuepress#465]
Wanted to seed up a recipe:

1. Install [staticrypt](https://www.npmjs.com/package/staticrypt)
2. After `vuepress build`, run `find <<dist>> -type f -name "*.html" -exec staticrypt {} mypassword \;` on your dist folder

This creates stand-alone encrypted pages that require password on each refresh. This works well to lock down a Github Pages deployment.

This technique seems to be compatible with all of the various deployment environments supported and could potentially be an option on the config API down the road (relative to deployment types that support it).

Enjoy!

**Comment by ulivz** [comment]
LGTM, but we don't plan to add built-in support for it. it seems to be something that should be done by a plugin.

**Comment by Hambern** [comment]
If tried using Staticrypt to encrypt one of my folders. It works great. But if I access the page through the search box it doesn't require a password. I guess it's because the page is loaded from javascript. How can this be handled?

**Comment by syffs** [comment]
@ulivz could you please advise whether this is now supported (even with a plugin) ?

This could be a great feature to be able to lock a WIP vuepress...
