### ISSUE TITLE
Css scoped

### ISSUE THREAD

**Issue by cdmoro** [vuejs/vuepress#468]
Hello, I have a question, not an issue exactly... I'm developing the docs of a component library based on Bootstrap-vue and I wanna to show the components in the docs, I did it but there's a problem, the bootstrap-vue and bootstrap's css overwrite some vuepress css rules.
Is there a way to make bootstrap's css keep scoped only for my components?
Thanks!!

**Comment by ulivz** [comment]
I'm not sure if `bootstrap-vue` could support custom css prefix or namespace. for this, you should open a issue to `bootstrap-vue`.

We cannot make VuePress's css class name to scoped because it will limit the override from user.
