### ISSUE TITLE
feature request.  page name appear in DOM

### ISSUE THREAD

**Issue by genedronek** [vuejs/vuepress#471]
For purposes of triggering themed CSS rules, it is handy to have the page name appear in the DOM.
e.g. adding this code in vuepress source .../Page.vue
```
<div class= page  :name= pageBaseName />
pageBasename()	{ return this.$page.path.replace( /[.]html$|^.*[/]/g, '') }
```
would enable this rule, for example
```
.page[name="error"] { color: red; }
```
My vuepress experience is rather limited, though.

**Comment by ulivz** [comment]
You can use [Custom Page Class](https://vuepress.vuejs.org/default-theme-config/#custom-page-class).
