### ISSUE TITLE
有没有一种方案支持嵌入百度统计或者谷歌统计

### ISSUE THREAD

**Issue by onesez** [vuejs/vuepress#475]
#有没有一种方案支持嵌入百度统计或者谷歌统计

**Comment by ulivz** [comment]
Please follow issue reporting guidelines. Github issues are for bug reports and feature requests only. You can ask questions on the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vue.js). 🙂
