### ISSUE TITLE
[Feature Request] Expose `markdown.breaks`

### ISSUE THREAD

**Issue by octref** [vuejs/vuepress#476]
`markdown-it`'s `breaks` option should be exposed, so people don't have to type two spaces after each line to get a new line. This is also inline with GitHub's Markdown in issue/comments.

**Comment by ulivz** [comment]
You can custom `markdown-it`'s options via [md.set](https://markdown-it.github.io/markdown-it/#MarkdownIt.set):

``` js
module.exports = {
  markdown: {
    config: md => {
      md.set({ breaks: true })
  }
}
```

**Comment by octref** [comment]
I see, didn't realize it while reading doc. I have opened https://github.com/vuejs/vuepress/pull/477.
