### ISSUE TITLE
Unable to override default SVG loader

### ISSUE THREAD

**Issue by Tolmark12** [vuejs/vuepress#478]
I'm currently unable to use [vue-svg-loader](https://github.com/visualfanatic/vue-svg-loader) to load svgs in my `.vue` files.

I assume this is because vuepress uses `file-loader` to load svgs. (see : [createBaseConfig.js#L150](https://github.com/vuejs/vuepress/blob/master/lib/webpack/createBaseConfig.js#L150)). 

Is there a way to override the default vuepress svg loader?

I've tried:

**config.js:**
```javascript
chainWebpack: config => {
    config.module
      .rule('svg')
      .test(/\.svg$/)
      .use('vue-svg-loader')
        .loader('vue-svg-loader')
        .end()
}
```

**Comment by ulivz** [comment]
You need to remove the default rule first:

``` js
config.module.rules.delete('svg')
config.module
  .rule('svg')
    .test(/\.svg$/)
    .use('vue-svg-loader')
      .loader('vue-svg-loader')
      .end()
```

**Comment by Tolmark12** [comment]
Thank you worked perfectly!
