### ISSUE TITLE
Can provide an online editing function similar to vuep?

### ISSUE THREAD

**Issue by txs1992** [vuejs/vuepress#479]
Sometimes we want to be able to provide an online editing function when writing a document so that the user can immediately get the result he wants by modifying our example.

**Comment by LinFeng1997** [comment]
I think this is a great idea, but how to implement it?

**Comment by ulivz** [comment]
1.x is going to reach `beta` stage, so you can start to write a [plugin](https://vuepress.vuejs.org/plugin/) for it.

**Comment by xiguaxigua** [comment]
Maybe this plugin is right for you. 
http://daxigua.me/vuepress-plugin-demo-block
