### ISSUE TITLE
when using components in markdown file, how to pass variables ?

### ISSUE THREAD

**Issue by xiguaxigua** [vuejs/vuepress#483]
by this [doc](https://vuepress.vuejs.org/guide/using-vue.html) , i want to use a component that accept a custom string in markdown file such as:
```html
<comp attr="attr"></comp>

attr = `
	{
		"JSON": true
	}
`
```

with v0.8.4, i find a not good way to do it by use global variables:

```html
<comp attr="attr"></comp> // read window.attr in this component

<script>
attr = `
	{
		"JSON": true
	}
`
</script>
```

but in v0.9.0, it seems not useful, and what's the best way to deal with it?

**Comment by ulivz** [comment]
You can use frontmatter:

```
---
JSON: true
---

<comp :attr="$page.frontmatter.JSON"></comp>
```
