### ISSUE TITLE
Error: vue-loader was used without the corresponding plugin

### ISSUE THREAD

**Issue by bertdeterd** [vuejs/vuepress#485]
Hello,

In the most basic setup with just 1 .md file (just plain text), I get an error when **$ vuepress dev**

ERROR in ./Page-1.md?vue&type=template&id=4759a99c ..........
**vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.**

Node js version: v8.11.1
Windows 10
latest vuepress version, globally installed

used npm and yarn but both result in the same error.

How can i alter the webpack config?

**Comment by ulivz** [comment]
Could you provide the reproduction repository?

**Comment by bertdeterd** [comment]
Beginner mistake! Sorry for posting this issue guys!

**Comment by KirstyWright** [comment]
@bertdeterd what was the beginner mistake you made ? I suspect I have made a similar one as I get the same error.

**Comment by ulivz** [comment]
@KirstyWright Could you provide the production repo so that I can help you.

**Comment by KirstyWright** [comment]
Trying to find the minimum stuff to have to reproduce this.

**Comment by bertdeterd** [comment]
Well, I thought it was a beginner mistake because i did some fixes in my .md file. 
Later on I found out that when I get this error on **vuepress dev docs** I must restart my Visual Studio Code.   After that **vuepress dev docs** works fine. Don't know why but it works for me.

**Comment by seifip** [comment]
I have the same problem... Tried reverting to the github commit when everything worked still, but doesn't help. Tried removing and reinstalling from npm, same problem.
