### ISSUE TITLE
Make vuepress-theme-vue repository public

### ISSUE THREAD

**Issue by Yaty** [vuejs/vuepress#486]
Hi,

Thanks for Vuepress :+1: !!!

Is it possible to make `vuepress-theme-vue` GitHub repository public ? For now npm GitHub link redirect me to a 404 (https://www.npmjs.com/package/vuepress-theme-vue).

I currently ejected this theme for customization but I would like to still be able to see what has changed between my version and yours. The ideal would be for me to fork it but it's currently impossible.

Thanks,

**Comment by ulivz** [comment]
Thanks for your reporting, actually, `vuepress-theme-vue` is almost equal to built-in default theme, the unique difference is that `vuepress-theme-vue` add some advertisements.
