### ISSUE TITLE
Interrupted Build Process deleted all Data.

### ISSUE THREAD

**Issue by chrtz** [vuejs/vuepress#487]
#### Version
vuepress 0.9.0

#### Steps to reproduce
yarn docs:build

#### What is expected?
Build website for testing purpose as the heroimage wasn't shown on localhost (the file got an 404 itself).

#### What is actually happening?
The process was interrupted as the process itself seemed to delete all files including the project folder itself.
So all my work is gone.

#### Other relevant information

- Your OS:  macOS 10.12.6
- Node.js version: v8.9.4
- Browser version: Chrome v66
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

**Comment by chrtz** [comment]
I might maybe know what happend.
Appropriately, this could be my fault in the end.
I think the dest folder I set, had the same name as the project folder. So it was overwritten.

Could this be the issue?

**Comment by ulivz** [comment]
Please provide your reproduction repo.
