### ISSUE TITLE
markdown lineNumbers config option does not work

### ISSUE THREAD

**Issue by kevinmpowell** [vuejs/vuepress#488]
#### Version
0.8.4

#### Steps to reproduce
Follow getting started guide 
```
.
├── .vuepress
│   └── config.js
├── README.md
└── package.json
```

https://github.com/kevinmpowell/vp-linenumbers

#### What is expected?
When I run `vuepress dev` I expect to see line numbers in my block code snippet based on this config:
```
module.exports = {
  title: 'Testing Line Numbers',
  description: 'Just playing around',
  markdown: {
    lineNumbers: true
  }
}
```
And the documentation here: https://vuepress.vuejs.org/config/#markdown-linenumbers

#### What is actually happening?
I see a code block rendered with no line numbers:
![screen shot 2018-05-23 at 3 52 08 pm](https://user-images.githubusercontent.com/979463/40450423-44967eee-5ea1-11e8-993d-79cd6ee7e8ca.png)

#### Other relevant information

- Your OS: 
MacOS 10.13.4

- Node.js version: 
8.11.0

- Browser version: 
Safari 11.1
Chrome 67.0.3396.48
Firefox 59.0.2

- Is this a global or local install? 
global

- Which package manager did you use for the install?
NPM

**Comment by ulivz** [comment]
I don't know if you saw the following sentence in issue template:

> Before creating an issue please make sure you are using the latest version of VuePress.

`lineNumbers` feature is added in 0.9.0.

**Comment by EduardoRT** [comment]
Was this option removed? I can't see it in the docs and it's not working, VuePress 0.10.2

**Comment by ulivz** [comment]
@EduardoRT https://vuepress.vuejs.org/guide/markdown.html#line-numbers

**Comment by EduardoRT** [comment]
Thanks, it's working now I think it was a caching issue on my local machine, it started working without any change.
