### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null

### ISSUE THREAD

**Issue by kungfuboy** [vuejs/vuepress#49]
![1523812993425](https://user-images.githubusercontent.com/10394818/38781277-e82c1bea-4114-11e8-853f-639f5c605ead.jpg)

`##` will show error, then I try `#`. It is normal again. 

Looks wear.

![1523813437653](https://user-images.githubusercontent.com/10394818/38781389-516fddde-4116-11e8-87bd-a086a0c40874.jpg)

Am I wrong in somewhere ?

**Comment by yyx990803** [comment]
Should be fixed by 42f63a8 (release soon)
