### ISSUE TITLE
关于文档分类、归档的问题

### ISSUE THREAD

**Issue by quanzaiyu** [vuejs/vuepress#495]
#### What problem does this feature solve?

很多静态网站生成工具，例如Hexo、Jekyll都支持文章分类、标签及归档，目前VuePress必须手动维护配置文件，需要在 themeConfig.locales.sidebar 中手动添加侧边栏目录，希望之后的版本以一种自动添加指定 .md 文件 的 frontmatter 为目录的方式。

#### How should this be implemented in your opinion?

可以通过 frontmatter 添加 category 和 tags 的方式创建分类，通过相同的 category 和 tags 创建分类目录，可以在Vue的原型中添加 $category 和 $tags 的钩子，比如有一个叫 'frontend' 的分类，可以使用 $category['frontmatter'] 来访问。

#### Are you willing to work on this yourself?**

暂时没打算自己做，对 VuePress 源码还没研究透彻 !

**Comment by ulivz** [comment]
Thanks,

I'll appreciate if you take the time to translate the issue to English so anybody can answer, you will also benefit from this :)

**Comment by CatchLife** [comment]
I need this too. I want to build a blog theme myself with classification, tags, and archives included. But I want one supported by official developers of vuepress so that it may benefit more developers.

**Comment by meteorlxy** [comment]
Vuepress is originally designed for documents, in which cases categories/tags are not necessary.

As more people being interested in Vuepress, blog support (like categories, tags, etc.) has been requested for months.

@ulivz is working on plugin system to make Vuepress more customizable, and will be released in `v1.0.0`. After that, blog/theme/anything-you-want could be realized via plugins. You can take a look at the `next` branch for the progress of that.

So in version `0.x`, you may have to add some code to support this feature as @quanzaiyu did. FYI, I also make a simple workaround via `enhanceApp.js` in [my blog theme](https://github.com/meteorlxy/vuepress-theme-meteorlxy).

**Comment by Bloss** [comment]
I think what you want is this [theme](https://github.com/Bloss/vuepress-theme-yubisaki#tags)

**Comment by Bloss** [comment]
@meteorlxy Amazing

**Comment by cc189** [comment]
tags filter search, https://cc189.github.io/vuebook/tags/

**Comment by ulivz** [comment]
1.x is going to reach `beta` stage, so you can start to write a [plugin](https://vuepress.vuejs.org/plugin/) for it.

FYI: there has been an official plugin [@vuepress/plugin-blog](https://vuepress.vuejs.org/plugin/official/plugin-blog.html#install) and a [demonstration theme](https://github.com/ulivz/vuepress-theme-egoist).
