### ISSUE TITLE
markdown.lineNumbers option does not work on 0.9.0

### ISSUE THREAD

**Issue by kevinmpowell** [vuejs/vuepress#497]
I opened this issue yesterday and it was closed since I wasn't reporting it on the latest version. I have confirmed this _is_ broken in version 0.9.0.

#### Version
0.9.0

#### Steps to reproduce
Follow getting started guide 
```
.
├── .vuepress
│   └── config.js
├── README.md
└── package.json
```

Reproduction Repository
https://github.com/kevinmpowell/vp-linenumbers

#### What is expected?
When I run `npm run dev` I expect to see line numbers in my block code snippet based on this config:
```
module.exports = {
  title: 'Testing Line Numbers',
  description: 'Just playing around',
  markdown: {
    lineNumbers: true
  }
}
```
And the documentation here: https://vuepress.vuejs.org/config/#markdown-linenumbers

#### What is actually happening?
I see a code block rendered with no line numbers:
![screen shot 2018-05-23 at 3 52 08 pm](https://user-images.githubusercontent.com/979463/40450423-44967eee-5ea1-11e8-993d-79cd6ee7e8ca.png)

#### Other relevant information

- Your OS: 
MacOS 10.13.4

- Node.js version: 
8.11.0

- Browser version: 
Safari 11.1
Chrome 67.0.3396.48
Firefox 59.0.2

- Is this a global or local install? 
global

- Which package manager did you use for the install?
NPM

**Comment by xkcoding** [comment]
emmm... I update version to 0.9.0 and it works! 
you can see:  https://note.xkcoding.com/notes/Java/java-2-util-image.html

Your OS:
MacOS 10.13.4

Node.js version:
8.11.2

Browser version:
Chrome 67.0.3396.48

Is this a global or local install?
local

Which package manager did you use for the install?
yarn

**Comment by ulivz** [comment]
The [docs](https://vuepress.vuejs.org/guide/basic-config.html#config-file) has described detailedly:

> ... To customize your site, let's first create a `.vuepress` directory inside your `docs` directory ...

You just had a wrong directory structure, the correct structure should be:

``` js
cwd
└── docs
    ├── README.md
    └── .vuepress
        └── config.js
```

instead of:

```
cwd
├── .vuepress
│   └── config.js
└── docs
    └── README.md
```

**Comment by kevinmpowell** [comment]
@ulivz that was the issue. Thank you for pointing me in the right direction.
I think adding the correct directory tree to the docs would be helpful.
This:
```
cwd
└── docs
    ├── README.md
    └── .vuepress
        └── config.js
```
is much clearer and easier to see than this:
> ... To customize your site, let's first create a .vuepress directory inside your docs directory ...

Thanks again for the help!

**Comment by poolghost** [comment]
Good to know that it’s not working with an **index.md** file.

**Comment by poolghost** [comment]
My bad. Thought that you could make a **config.js** for each page. 

Would be nice btw.
