### ISSUE TITLE
build error using .vuepress/components with scripts

### ISSUE THREAD

**Issue by genedronek** [vuejs/vuepress#499]
#### Version
most current vuepress 0.9.0

#### Steps to reproduce
```
git  from https://github.com/genedronek/vuepress-bug.git
cd vuepress-bug
vuepress build docs
```

#### What is expected?
"vuepress build docs" should work

#### What is actually happening?
build blows up; bad default object, and other manifestations

#### Other relevant information
any .vuepress/component with script will cause failure

- Your OS: Mac Sierra
- Node.js version: v10.2
- Browser version: n.a.
- Is this a global or local install?
global, but either kind, local or global, vuepress build will fail.
- Which package manager did you use for the install?
npm install -g vuepress;  
I performed complete reload of node and npm.
Could not believe my eyes.   Perhaps I had made a newbie blunder.   Not likely.
This is my third day of  reducing this bug for reporting.   There are other vpress
bug reports regarding build problems.

I say it again.  You guys are doing bang up wonderful work on a wonderfully complex package.
It must be very hard.  But we love you for it.

**Comment by genedronek** [comment]
I am just now finding a case where .vuepress/components script is working.
sigh.  I will resubmit when I find out wtf.

**Comment by chrtz** [comment]
I think it could be possible this has to do with the new npm (6.10) and the audit function. As there are two vulnerabilities according to string.js.

(https://github.com/vuejs/vuepress/issues/493)
