### ISSUE TITLE
Remove navbar .site-name when logo is set in config.js

### ISSUE THREAD

**Issue by chrtz** [vuejs/vuepress#501]
#### What problem does this feature solve?
Currently, when you add a logo via **config.js**
```
module.exports = {
  themeConfig: {
    logo: '/your-logo.png'
    }
  }
```

The title (**.site-name**) is still shown beside it. This for your can make sense when you just add an icon, but if you set a wordmark this is kinda doubled.
Therefore, it would be nice to be able to disable or hide **.site-title** via **config.j**s if a logo is set.

#### How should this be implemented in your opinion?
Maybe with a boolean inside the config.js?

#### Are you willing to work on this yourself?**
for now I gave every page a custom CSS with `pageClass`via **YAML** and **override.styl** which hides .site-name and aligns the image.

**Comment by ulivz** [comment]
There are many ways to implement is and we DON'T plan to add this “rare” feature as the default theme is for Vue and its ecosphere.

1. override.styl
2. Custom layout
3. Eject
4. Write your theme.
