### ISSUE TITLE
build will fail when .vuepress/component has script tag

### ISSUE THREAD

**Issue by genedronek** [vuejs/vuepress#502]
#### Version
most current vuepress 0.9.0

#### Steps to reproduce
```
git  from https://github.com/genedronek/vuepress-bug.git
cd vuepress-bug
vuepress build docs
```

#### What is expected?
"vuepress build docs" should work

#### What is actually happening?
build blows up; bad default object, and other manifestations

#### Other relevant information
any .vuepress/component with script will cause failure

- Your OS: Mac Sierra
- Node.js version: v10.2
- Browser version: n.a.
- Is this a global or local install?
global, but either kind, local or global, vuepress build will fail.
- Which package manager did you use for the install?
npm install -g vuepress;  

I performed complete reload of node and npm just to make sure this is current bug.

**Comment by chrtz** [comment]
That seems to be the same issue I have to face since today.

but I created a repo (vuepress_repo) for showing the bug, and there it strangely doesn't occur.

**Comment by ulivz** [comment]
Just tested with latest version and all works for me:

![image](https://user-images.githubusercontent.com/23133919/40584782-bea96ee0-61d9-11e8-8e57-6b86c136f10c.png)

**Comment by ulivz** [comment]
Closing it since we cannot reproduce it, please feel free to continue discussion. we'll reopen this issue if a proper repro is posted.

**Comment by chrtz** [comment]
I think it could be possible this has to do with the new npm (6.10) and the audit function. As there are two vulnerabilities according to string.js.

(https://github.com/vuejs/vuepress/issues/493)
