### ISSUE TITLE
Navbar/Sidebar Link redirect not work

### ISSUE THREAD

**Issue by Higuoxing** [vuejs/vuepress#511]
#### Version
Vuepress 0.10.0

#### Key Words:  TypeError: (void 0) is not a function

repo link: [higuoxing.github.io](https://github.com/higuoxing/higuoxing.github.io)

#### What is expected?
Click the Navbar item and will jump to the link

#### What is actually happening?
Cannot jump to the link that item points to ...

#### Other relevant information

- Your OS:  `Mac OS 10.13.3`
- Node.js version:  `v8.11.1`
- Browser version: `Version 65.0.3325.181 (Official Build) (64-bit)`
- Is this a global or local install?  `npm install -g vuepress`
- Which package manager did you use for the install? `npm`

**Comment by ulivz** [comment]
Please provide a proper reproduction. (DON'T just give me the compiled code.)

BTW, I just saw you are using this custom layout or theme, so it should be resolved by yourself.

**Comment by Higuoxing** [comment]
Thanks, I will have a try. : )

**Comment by ulivz** [comment]
@Higuoxing congratulations!
