### ISSUE TITLE
Configure path to cache folder introduced in 0.9.0

### ISSUE THREAD

**Issue by Al-Rozhkov** [vuejs/vuepress#513]
#### What problem does this feature solve?

Vuepress + Netlify is amazing combination. Vuepress introduces caching mechanism in 0.9.0. But Netlify runs every deploy in a docker container without the possibility to reuse things from the previous deploy. Except one folder that persists across builds - `/opt/build/cache/`

Looks like it is possible to improve rebuild time on Netlify by moving cache from `node_modules` to `/opt/build/cache/`

#### How should this be implemented in your opinion?

Set variable for path to cache folder in config file and use it instead of hardcoded '../../node_modules/.cache/vuepress'.

I'm not sure is it even a good idea, since I don't understand Vuepress caching mechanism deeply. So it would be great to hear opinion from expirienced developers. Feel free to close this issue if this feels like bad idea.

#### Are you willing to work on this yourself?**

I'm not expirienced enough to implement it by myself yet.

**Comment by ekoeryanto** [comment]
I found it's easy to implement, editing this [line](https://github.com/vuejs/vuepress/blob/777c4f1551dba530cb88f35371980409088f5c7b/lib/webpack/createBaseConfig.js#L83) to
```js
  const cacheDirectory = siteConfig.cacheDir || path.resolve(__dirname, '../../node_modules/.cache/vuepress')
```
and add ` cacheDir: '.cache',` to `config.js`

**Comment by kumorig** [comment]
A bit verbose perhaps but you can currently tap the cache-loader options in your `config.js` :

    module.exports = {
      chainWebpack: (config, isServer) => {
        config.module
          .rule('vue')
          .use('cache-loader')
          .tap(options => merge(options, { cacheDirectory: path.resolve(__dirname, '.cache') }));
      },
    };

(Here using lodash.merge)
I also think a more direct config option would be nice!

**Comment by ulivz** [comment]
From 1.x, you will have a new flag `--cache` for dev/build.

```bash
$ vuepress dev --help
Usage: dev [options] [targetDir]

start development server

Options:
  -p, --port <port>    use specified port (default: 8080)
  -h, --host <host>    use specified host (default: 0.0.0.0)
  -t, --temp <temp>    set the directory of the temporary file
  -c, --cache <cache>  set the directory of cache
  --no-cache           clean the cache before build
  --debug              start development server in debug mode
  -h, --help           output usage information
```
