### ISSUE TITLE
Do not show the sidebar hamburger menu if there are no sidebar links

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#516]
#### Version

0.9.0

#### Steps to reproduce

If there is no sidebar defined, on mobile there is still a sidebar hamburger menu icon displayed. If you click on it, nothing happens.

Demo: https://happy-css.com/articles/how-do-you-connect-your-web-app-with-the-rest/
Resize to below 719px in width.

#### What is expected?

Hide sidebar menu button if there is no sidebar defined

#### What is actually happening?

Sidebar menu button gets displayed

#### Other relevant information

- Your OS: Windows 10
- Node.js version:  v8.9.1
- Browser version: Chrome 66
- Is this a global or local install? global
- Which package manager did you use for the install? npm

**Comment by MartinMuzatko** [comment]
I already removed it manually.. I'm sorry :P I'll look for another reproduction

**Comment by ulivz** [comment]
Hmmm, I guess you were not using the default theme. the `.sidebar` block shouldn't be missed at your  reproduction link.

![image](https://user-images.githubusercontent.com/23133919/40726767-016e4940-6459-11e8-97fd-78844618f739.png)

Please provide a valid repro when opening an issue. thanks.
