### ISSUE TITLE
using config.yml not auto reload changes

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#520]
#### Version
0.10.0
#### Steps to reproduce
create `config.yml` in `.vuepress/` updating the content of the config doesn't auto reload.

#### What is expected?
Reload with the change
#### What is actually happening?
need to stop and restart the `vuepress dev` command
#### Other relevant information

- Your OS: Window 10
- Node.js version: 8
- Browser version: 
- Is this a global or local install? 
both
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
Thanks for the reporting, fixed at 6048eb9.
