### ISSUE TITLE
Google Analytics tag missing?

### ISSUE THREAD

**Issue by bencodezen** [vuejs/vuepress#523]
#### Steps to reproduce

I've configured the GA attribute in the `config.js` file with the ID, but I'm not seeing any evidence of it in the dev or build files.

https://github.com/bencodezen/vue-meetups/blob/master/docs/.vuepress/config.js

#### What is expected?

I expected some evidence of the following to appear in a build file or something, but I don't see any evidence of it in the files.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123456"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123456');
</script>
```

#### What is actually happening?

It seems like the configuration to integrate Google Analytics isn't working? Based on diving into the source code, it is generated based on `(process.env.NODE_ENV === 'production' && GA_ID)`. 

Is it possible that when triggering `vuepress build docs` it doesn't set the `process.env.NODE_ENV` to production which is why it is missing?

#### Other relevant information

- Your OS: macOS High Sierra v10.13.4
- Node.js version: 8.11.1
- Browser version: Firefox Quantum v60.0.1
- Is this a global or local install? Local install
- Which package manager did you use for the install? yarn

**Comment by bencodezen** [comment]
I might have figured it out. I think it has to do with the node_env flag. Will report back shortly.

**Comment by bencodezen** [comment]
Just tried adding a NODE_ENV variable with "production" as a value to the Netlify build process and it didn't seem to change the output.

**Comment by LinFeng1997** [comment]
Can you provider your `themeConfig.algolia`?

**Comment by bencodezen** [comment]
@LinFeng1997 I'm currently waiting for Algolia to review the site.

**Comment by ulivz** [comment]
@bencodezen 

In dev, you cannot see it since the code won't be inclueded to the output bundle due to:

```js
if (process.env.NODE_ENV === 'production' && GA_ID) {
   // GA's code
}
```

See: https://webpack.js.org/guides/production/#specify-the-environment

so in build, it should be here when you provide the GA's id:

![image](https://user-images.githubusercontent.com/23133919/40668684-bd06aee4-6397-11e8-97f8-cdbbe4b2c5e8.png)

**Comment by bencodezen** [comment]
Can't believe I missed it in there. I assumed it was in one of the other build files. Thanks for clarifying @ulivz!
