### ISSUE TITLE
Merge into one html file

### ISSUE THREAD

**Issue by tumregels** [vuejs/vuepress#530]
## Feature request

When you generate the docs you get the following files

```
.
├── 404.html
├── assets
│   ├── css
│   │   └── 0.styles.a3badf68.css
│   ├── img
│   │   └── search.83621669.svg
│   └── js
│       ├── 1.64a2319a.js
│       ├── 10.69ac8bc8.js
│       ├── 11.15258892.js
│       ├── 12.fd1748f5.js
│       ├── 2.876db2b0.js
│       ├── 3.1efe1edf.js
│       ├── 4.f3fb7211.js
│       ├── 5.14f9cf23.js
│       ├── 6.7d156e8a.js
│       ├── 7.7c8f2536.js
│       ├── 8.fcd3f296.js
│       ├── 9.bd07bbad.js
│       └── app.d4950550.js
├── config
│   └── index.html
├── default-theme-config
│   └── index.html
├── guide
│   ├── assets.html
│   ├── custom-themes.html
│   ├── deploy.html
│   ├── getting-started.html
│   ├── index.html
│   ├── markdown.html
│   └── using-vue.html
├── hero.png
└── index.html
```

Will it be possible to add a feature which will allow to generate just one big `index.html` file which contains all of this.

#### What problem does this feature solve?

Just one file to deploy

**Comment by meteorlxy** [comment]
"all of this" means all `.css, .js, .svg, .html` ?

**Comment by tumregels** [comment]
Actually yes, "all of this" means all .css, .js, .svg, .html  into one big "index.html"

It will be a pretty cool feature for vuepress. 

And looks like its not difficult to merge all of this into one file via webpack.

**Comment by ulivz** [comment]
Don't think this feature has any meaning. also don‘t see where it's cool.

> And looks like its not difficult to merge all of this into one file via webpack.

So, why not doing it by yourself.

**Comment by futagoza** [comment]
@tumregels Sorry to bump, but how would one go about doing this?

**Comment by tumregels** [comment]
@futagoza I suppose its not that easy to implement this feature, but can be a good one.
