### ISSUE TITLE
Custom Containers with more options

### ISSUE THREAD

**Issue by PanJiaChen** [vuejs/vuepress#536]
### First
https://github.com/vuejs/vuepress/blob/cd8ee42fbe2db00ed964e54c60456ba30d9f6e8d/lib/markdown/containers.js#L22

Sometimes l just want `Custom Containers` without title.

### Second
And is it possible that I can customize its class? So I can simply create a custom container with custom css.

![image](https://user-images.githubusercontent.com/8121621/40829573-6ce1967e-65b6-11e8-9d2f-625e28379040.png)

**Comment by meteorlxy** [comment]
How about override the default style in `override.styl`?

**Comment by PanJiaChen** [comment]
I don't want to override the style, I also want to continue to use the default style.

**Comment by ulivz** [comment]
You can create your custom container by extending the `md` instance via [config/#markdown-config](https://vuepress.vuejs.org/config/#markdown-config).

Closing as this can be done in userland.

**Comment by GrayedFox** [comment]
This is nearly a direct copy paste of the [code used by Vuepress][1] to generate custom containers (minor changes to our internal linting rules and style):

```
const container = require('markdown-it-container')

function createContainer(type, defaultTitle) {
  return [container, type, {
    render(tokens, idx) {
      const token = tokens[idx]
      const info = token.info.trim().slice(type.length).trim()
      const title = info || defaultTitle
      if (token.nesting === 1) {
        return `<div class="${type} custom-block"><p class="custom-block-title">${title}</p>\n`
      } else {
        return `</div>\n`
      }
    }
  }]
}

// md needs to be an instance of markdown-it (in our case, the one used by mavonEditor)
module.exports = (md) => {
  md
    .use(...createContainer('tip', 'TIP') )
    .use(...createContainer('warning', 'WARNING') )
    .use(...createContainer('danger', 'WARNING') )
}
```

Update: just noticed Vue has updated custom containers to explicitly escape Vue syntax - follow the link and see if you also need that for your own custom containers.

 [1]: https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/markdown/lib/containers.js

**Comment by lunaceee** [comment]
@GrayedFox I can't seem to open the link you attached anymore, could you please explain a bit more about how you implemented this in your code? Where shall I add the function? I'm new to VuePress, thanks!

**Comment by Shigma** [comment]
@lunaceee For now you can try [@vuepress/plugin-container](https://v1.vuepress.vuejs.org/plugin/official/plugin-container.html).

**Comment by lunaceee** [comment]
Thanks @Shigma Didn't realize it's part of the 1.x feature. :)

**Comment by lunaceee** [comment]
@Shigma I installed the plugin, got the `type` working but the container doesn't seem to have any style. What's the expected behavior?

**Comment by Shigma** [comment]
@lunaceee 

Our default theme has provided styles for `tip`, `warnging` and `danger`. You can use them.

If you want to define your own custom blocks, you should provide styles by yourself.

See: https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/styles/custom-blocks.styl

**Comment by germanbobadilla** [comment]
I'm stuck here. I've installed the plugin, used it in config, but still. It doesn't work. I don't know what I'm doing wrong. Look:
`['@vuepress-plugin-container', {
          type: 'warning',          
          defaultTitle: 'WARNING',
        }],
        ['@vuepress-plugin-container', {
          type: 'tip',          
          defaultTitle: 'TIP',
        }],
        ['@vuepress-plugin-container', {
          type: 'theorem',
          before: tip => `<div class="theorem"><p class="title">${tip}</p>`,
          after: '</div>',
        }],`

**Comment by ludanxer** [comment]
Hi @germanbobadilla ,You don't need to manually install nor config `vuepress-plugin-container` if you are using the default theme. Can you share your repo or provide a minimal reproduction?
