### ISSUE TITLE
EPUB and/or PDF export for dev environment

### ISSUE THREAD

**Issue by sulmanweb** [vuejs/vuepress#546]
#### What problem does this feature solve?
For writers the best way to have online book in html and offline books to sell in epub and / or pdf.

#### What does the proposed API look like?
`vuepress export epub` should export epub book

#### How should this be implemented in your opinion?
Not sure how

#### Are you willing to work on this yourself?**
No I am not so good in it

**Comment by Yeeler** [comment]
this is an awesome feature.

**Comment by eyleron** [comment]
Not just selling books, but just publishing documentation as PDF is a common feature of help authoring software, so this is inline with the use cases of the mainline project.

We have several clients (state government agencies) that in contracts expect printed documentation (alongside online), and I was wondering how we'd single-source / multiple-publish target for PDF too.

**Comment by mlinschulte** [comment]
Export to PDF would be highly appreciated since we already evaluated vuepress as an alternative for our online user manual but are missing this option heavily

**Comment by eyleron** [comment]
### Pandoc?
Does that auto-generate +TOC+ from hierarchy of pages? Or would Vuepress have to use site map and pass as first pages? 

### Features, options, settings? 
Is the homepage theme what one would expect in first page of manual?

**Comment by gmoralesc** [comment]
I tried Pandoc to generate the PDF from the build, but the assets' urls generated with the build script are absolute to the server path ( / ), that's mean that only work with a http-server not for open locally.

**Comment by chbndrhnns** [comment]
I wrote a small Python script [1] that could help with exporting single vuepress pages. It uses a head-less Chrome instance to render and modify the page and exports it to PDF.

[1] https://github.com/chbndrhnns/vuepress2pdf

**Comment by SimeonRoss** [comment]
This would be a really handy feature to have. The old GitBook CLI did this and we've used that feature before.

**Comment by ulivz** [comment]
Try 1,x and https://github.com/ulivz/vuepress-plugin-export

**Comment by SimeonRoss** [comment]
From the VuePress home page, "for now we recommend that you use the 0.x in the production environment."

There no way to get this to work with 0.x?

**Comment by kiviaj** [comment]
[vuepress-plugin-export](https://github.com/ulivz/vuepress-plugin-export) looks great for pdf export indeed, but what about the epub format? Is there any plan to evolve vuepress-plugin-export to support epub as well, unless the feature should rather be developed in a distinct plugin, what's your view on this?

**Comment by WhileLoop** [comment]
@ulivz I am not able to to get vuepress-plugin-export to run.

```$ vuepress --version
vuepress/1.5.0 darwin-x64 node-v10.15.1
$ vuepress export docs

Unknown command: export docs
```

`docs/.vuepress/config.js `
```
module.exports = {
  plugins: ['vuepress-plugin-export'],
...
```

**Comment by condorheroblog** [comment]
This is a screenshot of a generated outline PDF case.

![PDF-demo](https://github.com/vuejs/vuepress/assets/47056890/f1662da3-04ff-435a-afcb-f7b214bd1aac)

- If you are using VuePress major version is 1.x, please use [@condorhero/vuepress-plugin-export-pdf-v1](https://github.com/condorheroblog/vuepress-plugin-export-pdf/blob/main/packages/vuepress-plugin-export-pdf-v1/README.md)
- If you are using VuePress major version is 2.x, please use [@condorhero/vuepress-plugin-export-pdf-v2](https://github.com/condorheroblog/vuepress-plugin-export-pdf/blob/main/packages/vuepress-plugin-export-pdf-v2/README.md)
- If you are using VitePress, please use [vitepress-export-pdf](https://github.com/condorheroblog/vitepress-export-pdf)
