### ISSUE TITLE
Documentation advice.

### ISSUE THREAD

**Issue by arkceajin** [vuejs/vuepress#548]
https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project

Please mention, this code is for the global install

```
{
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  }
}
```
And add the following to explain how to do it in the local install case
```
{
  "scripts": {
    "docs:dev": "npx vuepress dev docs",
    "docs:build": "npx vuepress build docs"
  }
}
```

And also mention `npx ` require ` npm 5.2.0` shall be better.

**Comment by ulivz** [comment]
Thanks for the reporting, for now we recommend `yarn` instead of `npm`:

![image](https://user-images.githubusercontent.com/23133919/41016950-1abb3ddc-6985-11e8-919f-5fdfa014f7c6.png)

**Comment by yyx990803** [comment]
... npm scripts is able to find locally installed binaries. You don't need `npx` in npm scripts.

**Comment by arkceajin** [comment]
@yyx990803 I found the problem,  the `vuepress` did not installed correctly.

Got error when `yarn add -D vuepress`
```
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
error koa@2.5.1: The engine "node" is incompatible with this module. Expected version "^4.8.4 || ^6.10.1 || ^7.10.1 || >= 8.1.4".
error Found incompatible module
```
