### ISSUE TITLE
Ability to read/compile .MD file from installed npm module

### ISSUE THREAD

**Issue by randyhoulahan** [vuejs/vuepress#549]
## Feature request

Ability to read/compile .MD file from installed npm module so that the docs with respect to a component being showcased can live in a different repo.

#### What problem does this feature solve?
So components docs can be in the same repo/package as the component it describes.

#### What does the proposed API look like?
Perhaps:
import CompDoc from 'installed-npm-package/README.md'
At which point the file is imported as the main template.

#### How should this be implemented in your opinion?
<script>
import CompDoc from 'installed-npm-package/README.md'
export default{
template:CompDoc
}
</script>
#### Are you willing to work on this yourself?**
Yes but would like affirmation on suggested implimentation.

**Comment by yyx990803** [comment]
This is actually a useful feature that can be included in core. Essentially we can use a markdown file to "redirect" to another markdown file.

But this may also overlap with / can be solved by what @ycmjason has been working on in #227

**Comment by ycmjason** [comment]
@yyx990803 ya, I think I could assume non-relative path to be rooted at `node_modules`. Then you could probably do something like

```
<!-- include installed-npm-package/README.md -->
```

**Comment by ulivz** [comment]
This could also be solved by the plugin's option `additionalPages` (TBD with @yyx990803 )

``` js
  additionalPages () {
    return [
      {
        // This will override the default `/guide/`
        route: '/guide/',
        path: path.resolve(__dirname, '../../node_modules/guide.md')
      }
    ]
  }
```
