### ISSUE TITLE
local preview via file protocol

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#55]
Hello!

The Base path is set to "/" by default I guess. 
When I want to preview the built website without being deployed, I open the file in my browser by double clicking the file in my file explorer.

There the path is `file://...../vuepress/dist/index.html`

Is there something I could do to make this also possible?

Thanks in advance.

**Comment by yyx990803** [comment]
You need a simple HTTP server to preview the site, something like `serve` or `http-server` on npm.
