### ISSUE TITLE
Question: raw text + Let's encrypt

### ISSUE THREAD

**Issue by k33g** [vuejs/vuepress#550]
Hi, I deploy a VuePress site on GitLab pages and I would like to use Let's Encrypt. 
It seems I need to render raw (plain/text)  to send informations to check the certificate : https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/

But I can't find how to proceed (even with a redirection in `enhanceApp.js`) to render raw text.

If somebody here already use Let's Encrypt with VuePress, I'm very interested

**Comment by yyx990803** [comment]
You can just have a script that adds a raw text file to the dist folder after VuePress build.

Or you can use Netlify which provides support for automated Lets Encrypt certs (highly recommended).
