### ISSUE TITLE
set `sidebar: auto` as default configure of pages

### ISSUE THREAD

**Issue by tyrion-yu** [vuejs/vuepress#552]
#### What problem does this feature solve?

If someone use VuePress to build a blog of himself, he may have tons of files in his docs directory.
He may want all his contents have a sidebar of the content.
It's crazy to append FrontMatter Config to all the files.

#### What does the proposed API look like?

In the `.vuepress/config.js`, we can set `sidebar` property to `auto`. Then all the pages have this value for default. FrontMatter on single page still have higher priority to rewrite the default value.

#### How should this be implemented in your opinion?

``` js

// resolveSidebarItems
const { themeConfig } = site
const pageSidebarConfig = page.frontmatter.sidebar || themeConfig.sidebar
if (pageSidebarConfig === 'auto') {
    return resolveHeaders(page)
}
```

#### Are you willing to work on this yourself?**

I'm not sure. At least Not Recently.

**Comment by ulivz** [comment]
Thanks, it's truly a useful feature. finalize it at 56cbb5f
