### ISSUE TITLE
Why name "README.MD" for the homepage file?

### ISSUE THREAD

**Issue by arkceajin** [vuejs/vuepress#554]
I understand this might be a very boring question, but it really confused me when learning Vuepress. Why naming "README.MD" for the homepage file? Why not "index.MD" or "home.MD"?

**Comment by ycmjason** [comment]
`README.md` is standard naming convention for the default markdown file. The convention probably come from git repos? Most git repos has a README.md as the default landing markdown to show. This convention is used in most git hosting services like Github, Gitlab...

If you go to (here)[https://github.com/vuejs/vuepress], the content you are reading at the bottom is essentially `README.md` at the root of the repo.

**Comment by ulivz** [comment]
As @ycmjason said, `README.md` is a convention from `git` repos. and VuePress also supports `index.md` as the entry.

**Comment by arkceajin** [comment]
Thanks for answering!
