### ISSUE TITLE
Multiple values for "base" configuration

### ISSUE THREAD

**Issue by hanxue** [vuejs/vuepress#560]
## Feature request

I need to have the ability to set different values of [base](https://vuepress.vuejs.org/config/#base) for deployment to multiple sites. My default deployment for the site is OK with the default, unspecified value for `base` because the content is deployed to https://www.wujiquan.net

I also want to have a development deployment to https://hanxue.github.io/wujiquan-vuepress/ , to the `gh-pages` branch. Without setting `base` to `wujiquan-vuepress`, the Github Pages site will not work

#### What problem does this feature solve?

Allowing multiple deployments with differing settings of base. 

Is there any option to set configuration values via environment variables, or to specify a different configuration file other than the default `config.js`?

**Comment by yyx990803** [comment]
You can just set the base value depending on an environment variable.

**Comment by AyAmeng** [comment]
> I have met a question.
in config.js i set 
```js
base: process.env.NODE_ENV === 'development' ? '/magic-wpress/' : '/',  
```
why it don't work ? 

> 
@yyx990803

**Comment by Krutie** [comment]
@RVya Did you ever figure out how to set multiple values in `config.js` for VuePress `base`?

**Comment by ulivz** [comment]
@RVya @kru

The environment variable `NODE_ENV` was not injected when `config.js` was read, so you need to set the environment variable in your `package.json`.

**Comment by Mister-Hope** [comment]
Excuse me, my question is that I want to use the same code to automatically deploy on `/XXX/` and `/`.
So what can I do?

I searched how to set environment variable in package.json, but how to dynamic set it?

**Comment by nielsnuebel** [comment]
You can use npm i -D cross-env

in your package.json
`"docs:build": "cross-env NODE_ENV=production vuepress build docs"`

in config.js
`module.exports = {
  base: process.env.NODE_ENV === 'production'? '/github_repo/': '/'
}`
