### ISSUE TITLE
Collapsable navigation doesn't work

### ISSUE THREAD

**Issue by ahmmu18** [vuejs/vuepress#562]
#### Version
`0.10.0`

#### What is expected?
Collapsable navigation should work. 

#### What is actually happening?
Collapsable navigation doesn't work in `built` version

#### Other relevant information

- Your OS: `Mac 10.13.4`
- Node.js version: `v8.11.1`
- Browser version: `Chrome v67`
- Is this a global or local install? `global`
- Which package manager did you use for the install? `yarn`

**Comment by ulivz** [comment]
> Collapsable navigation doesn't work

Could you provide at least a reproduction link?

**Comment by ahmmu18** [comment]
@ulivz The issue has been solved! :)

All I had to do is remove `node_modules` folder and run `npm i`

Thank you
