### ISSUE TITLE
Add edit link on GitHub

### ISSUE THREAD

**Issue by lex111** [vuejs/vuepress#572]
At the bottom of the page, as now in the official Vue documentation

![image](https://user-images.githubusercontent.com/4408379/41224213-9c474d6c-6d74-11e8-83a3-624b5e5ce267.png)

**Comment by ulivz** [comment]
Thanks, and I also noticed this, it's truly meaningful to let edit link supports more complex format.

**Comment by lex111** [comment]
Closing, as done in https://github.com/vuejs/vuepress/commit/5479d6ef07519ebaede2f4d21e57f5e4ee8ce1e1
