### ISSUE TITLE
[Feature request] Last Update should be support to change date format pattern

### ISSUE THREAD

**Issue by xkcoding** [vuejs/vuepress#573]
#### What problem does this feature solve?
this feature can make last update more comfortable if it could support to change date format like `'YYYY-MM-DD hh:mm:ss'`

#### What does the proposed API look like?
API will be based on https://vuepress.vuejs.org/default-theme-config/#last-updated
look like this:
```js
module.exports = {
  themeConfig: {
    lastUpdated: {
        label: 'Last Updated', // string
        format: 'YYYY年MM月DD日 hh:mm:ss' // pattern can refer to moment.js
    }
  }
}
```

#### How should this be implemented in your opinion?
emmm... I think may be use moment.js or others...

#### Are you willing to work on this yourself?
emmm...  I'm not good at javascript... but i will do some research... if I resolved by myself. I will push a PR~

sorry for my poor English...
thank you for your reading~

**Comment by ulivz** [comment]
Good idea, and it has also been listed in my TODOs list.

But I have extracted it as a standalone plugin, so please hold it and waiting us to finalize the plugin API.

**Comment by xkcoding** [comment]
huh. expect your plugin

**Comment by meteorlxy** [comment]
Suggest using `date-fns/format`

**Comment by daltondiaz** [comment]
Yo @ulivz I don't understood what do you saying about standalone plugin and plugin API, can you explain only for me understand better? Thank you!

**Comment by willin** [comment]
@ulivz 

```
---
date:  2018-09-19 15:19:29
---
```

when i use: 

```js
dayjs(this.$page.frontmatter.date).format('YYYY-MM-DD HH:mm:ss')
```

it comes to: 

```
2018-09-19 23:19:29
```

**Comment by willin** [comment]
it maybe related with package `gray-matter`

https://github.com/jonschlinkert/gray-matter/issues/78

**Comment by ulivz** [comment]
@willin There is no any dark magic in VuePress, so can't you think by yourself before about a question?  please stop use issue to ask question.

**Comment by willin** [comment]
It's my duty to help you, not to help you to look into your codes.

**Comment by ulivz** [comment]
lol, are you sure that you're helping me? are you sure that you're not creating noises here?
