### ISSUE TITLE
random port for websocket on dev - HMR

### ISSUE THREAD

**Issue by r3stm4n** [vuejs/vuepress#577]
running command `vuepress dev --port 23300 --host myhost.com docs`
should:
- listen on 23300 - http 
- listen on 23301 - HMR (according to https://github.com/vuejs/vuepress/blob/master/lib/dev.js#L105)

but HMR port is random (every run)

**Comment by ulivz** [comment]
Please follow the issue reporting guidelines and don't delete our template. I even cannot know if we are in the same environment. 

---

> but HMR port is random ...

I cannot reproduced that (OSX 10.12.6 / Version 66.0.3359.181 (Official Build) (64-bit) )
