### ISSUE TITLE
Imagesize in Markdown

### ISSUE THREAD

**Issue by TheWhiteLlama** [vuejs/vuepress#578]
Hey there!

I looked up the page on:
https://vuepress.vuejs.org/guide/assets.html
for referencing images. It works properly, but I cannot find any way to resize the image in markdown.

Non of these seem to work:
```
[Image](./img.png =100x)
[Image](./img.png =100x100)
```
https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown/41169162

Google does also not provide any information. How does it come that noone wants to resize images via markdown in vuepress?

Thanks for help!

**Comment by ulivz** [comment]
Markdown syntax doesn't support different set for different pictures.

If you want to do such fine-grained control, you can just write pure HTML:

``` html
<img src="./img.png" width="100" height="100">
```

**Comment by TheWhiteLlama** [comment]
Oh I see, thank you very much!

**Comment by exKAZUu** [comment]
@TheWhiteLlama You may use https://github.com/tatsy/markdown-it-imsize via https://v1.vuepress.vuejs.org/config/#markdown-extendmarkdown

**Comment by oupala** [comment]
I tried the solution proposed by @exKAZUu but it does not seem to work.

I install the package locally, I declare it in the VuePress config file, and I add some code in the markdown:

> ![image](image.svg =100x200)

And in the generated html file, I can read:

> <p>![qrcode](qrcode.svg =100x200)</p>

In fact, the markdown is not interpreted at all...

**Comment by oupala** [comment]
I tried the solution proposed by @exKAZUu but it does not seem to work.

I install the package locally, I declare it in the VuePress config file, and I add some code in the markdown:

> ![image](image.svg =100x200)

And in the generated html file, I can read:

> <p>![image](image.svg =100x200)</p>

In fact, the markdown is not interpreted at all...

**Comment by exKAZUu** [comment]
@oupala I'm now using my solution and it works well. I list up possible things to fix your problem.

- You should use a relative path, e.g., `![Screenshot](./set-language.png =600x600)` (<- this is actual code fragment from my markdown)
- You should tweak settings by modifying `.vuepress/config.js` like

```
module.exports = {
  ...
  markdown: {
    linkify: true,
    extendMarkdown: md => {
      md.use(require('markdown-it-imsize'));
    },
  },
  ...
};
```

**Comment by oupala** [comment]
I've seen where I've made an error. I enabled the plugin this way:

```yaml
  markdown: {
    config: md => {
      md.use(require('markdown-it-deflist'))
      md.use(require('markdown-it-imsize'))
    }
  },
```
Where I should have enabled it this way:

```yaml
  markdown: {
    config: md => {
      md.use(require('markdown-it-deflist'))
    },
    extendMarkdown: md => {
      md.use(require('markdown-it-imsize'))
    }
  },
```

Thanks for your help, your were helpful.

**Comment by zuzhaoye** [comment]
> 
> 
> Markdown syntax doesn't support different set for different pictures.
> 
> If you want to do such fine-grained control, you can just write pure HTML:
> 
> ```
> <img src="./img.png" width="100" height="100">
> ```

Works for me. Thx!

**Comment by gounthar** [comment]
> I've seen where I've made an error. I enabled the plugin this way:
> 
> ```yaml
>   markdown: {
>     config: md => {
>       md.use(require('markdown-it-deflist'))
>       md.use(require('markdown-it-imsize'))
>     }
>   },
> ```
> 
> Where I should have enabled it this way:
> 
> ```yaml
>   markdown: {
>     config: md => {
>       md.use(require('markdown-it-deflist'))
>     },
>     extendMarkdown: md => {
>       md.use(require('markdown-it-imsize'))
>     }
>   },
> ```
> 
> Thanks for your help @exKAZUu, your were helpful.

Thanks.
What would be the syntax for a `config.ts` file?
