### ISSUE TITLE
Error loading the upstream vuepress documentation

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vuepress#583]
#### Version

N/A

#### Steps to reproduce

Go to https://vuepress.vuejs.org

#### What is expected?

See the Vuepress docs

#### What is actually happening?

A large amount of white space interspersed with black sections. There is also no styling applied, and multiple console logs:

```
Loading failed for the <script> with source “https://vuepress.vuejs.org/assets/js/app.230e632e.js”.
using-vue.html:78
Loading failed for the <script> with source “https://vuepress.vuejs.org/assets/js/13.3af902e0.js”.
using-vue.html:78
Loading failed for the <script> with source “https://vuepress.vuejs.org/assets/js/25.5a49aea7.js”.
using-vue.html:78
Loading failed for the <script> with source “https://vuepress.vuejs.org/assets/js/26.76559100.js”.
using-vue.html:78
Loading failed for the <script> with source “https://vuepress.vuejs.org/assets/js/27.45d150b0.js”.
using-vue.html:78
```

#### Other relevant information

- Your OS: MacOS High Sierra 10.13.5
- Node.js version: N/A
- Browser version: Firefox 60.0.2
- Is this a global or local install? N/A
- Which package manager did you use for the install? N/A

**Comment by GustavoMarcante** [comment]
Isn't it the same as https://github.com/vuejs/vuepress/issues/575?

**Comment by robcresswell** [comment]
@gustavomarcante well, this is upstream, your bug says it's during the build process.

**Comment by GustavoMarcante** [comment]
Yes, you're right, but also mentions that "sometimes" (and I don't know why) also https://vuepress.vuejs.org shows the same theme error, looking as shown in https://github.com/vuejs/vuepress/files/2095917/VuePress.pdf.
Is it this way it looks for you?

**Comment by robcresswell** [comment]
Yes, same display bug for me

**Comment by GustavoMarcante** [comment]
So I updated https://github.com/vuejs/vuepress/issues/575 to link with this one.

**Comment by ulivz** [comment]
Could you uninstall the service worker and try again?

**Comment by robcresswell** [comment]
@ulivz It seems to have cleared up of its own accord; not sure what was going on there then.

**Comment by ulivz** [comment]
@robcresswell It should be caused by a outdated sw which causes you missed the assets.

**Comment by robcresswell** [comment]
Good to know, I'll close the issue

**Comment by ulivz** [comment]
There is a WIP PR #533 which helps us to get the latest sw update of docs, please stay tuned.
