### ISSUE TITLE
Tighter integration with existing projects

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vuepress#584]
## Feature request

This is a bit of a grander high level request; a direction I'd love to see vuepress take. At the moment, it seems very much designed to sit alongside a Vue app, potentially even in a separate repo, so that people can use their existing Vue knowledge to quickly create documentation. This is a good start, but I'd love to see it be able to do things like share webpack config and components from a base app. 

For example, my app currently has a fairly standard structure like so:

```
$ tree src -FLa 1
src
├── .vuepress
├── README.md
├── components/
├── docs/
├── index.html
├── main.js
└── views/
```

There are two issues that stand out to me here, and may be due to my misunderstanding:

- I can't easily render the components from my application in the Vuepress docs site. Ideally, I'd love to be able to live render the components alongside their relevant documentation, but currently this involves recreating half the application in `.vuepress/components/`. I could probably get clever with symlinks, but that feels a bit overengineered.
- Ideally, `.vuepress` should be in `docs/`, but then it doesn't seem to be aware of the components
  directory, where each component has it's own README (for ease of use in GitHub, and sharing the   content with Vuepress. This isn't a huge deal though, just feels a little clunky.

#### Are you willing to work on this yourself?

Yes, if it fits with the direction envisioned by the Vuepress maintenance team

**Comment by ulivz** [comment]
Great expression 👍

> share webpack config and components from a base app

It can be done by a plugin so please wait for us to release the plugin API.

**Comment by robcresswell** [comment]
@ulivz That's awesome; would you like me to close this issue, or keep it open as a reference? I'll be following along keenly. I think this is great so far.

**Comment by ulivz** [comment]
Just keep it open, I'll close it and inform you of the releasing.

**Comment by ulivz** [comment]
Just keep it open, I'll close it then and inform you of the releasing.

**Comment by chan4est** [comment]
Has this been released yet?

**Comment by ulivz** [comment]
Try: https://vuepress.vuejs.org/plugin/option-api.html#chainwebpack

**Comment by robcresswell** [comment]
@ulivz Can you elaborate?

**Comment by robcresswell** [comment]
https://vuepress.vuejs.org/plugin/official/plugin-register-components.html

I think this is what I was looking for, if it helps anyone else

**Comment by nickforddesign** [comment]
@robcresswell That link appears to be dead, and the docs say plugin support is still TODO, any idea what happened?

**Comment by robcresswell** [comment]
@nickforddesign I believe it's now at https://v1.vuepress.vuejs.org/plugin/official/plugin-register-components.html
