### ISSUE TITLE
allow simple markdown plugin loading

### ISSUE THREAD

**Issue by neumayr** [vuejs/vuepress#585]
#### What problem does this feature solve?
`markdown.config` currently requires a javascript [function argument](https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets). This is only manageable with a `config.js` setup. I would like to allow markdown plugin loading also from a `config.yml` file.
Similar requests, see #326 & #579

#### What does the proposed API look like?
I would propose a `markdown.plugins` endpoint that requires an Array. See implementation example.

#### How should this be implemented in your opinion?

```yml
# .vuepress/config.yml
markdown:
  lineNumbers: true
  plugins:
    - ins
    - markdown-it-mark
```

```js
// .vuepress/config.js
module.exports = {
  markdown: {
    lineNumbers: true,
    plugins: ['ins', 'markdown-it-mark']
  }
}
```

```js
// vuepress/lib/markdown/index.js:58

  // apply user plugins
  if (markdown.plugins) {
    markdown.plugins.forEach(function (plugin) {
      plugin = plugin.replace('markdown-it-', '')
      md.use(require(`markdown-it-${plugin}`))
    })
  }
```

#### Are you willing to work on this yourself?
Yes 🎉 wip [branch](https://github.com/neumayr/vuepress/tree/markdown-plugins) is alive

**Comment by ulivz** [comment]
Thanks, It would be better to also support shortcuts without `markdown-it-`:

``` js
module.exports = {
  markdown: {
    lineNumbers: true,
    plugins: ['ins', 'mark']
  }
}
```

**Comment by neumayr** [comment]
@ulivz Do all `markdown-it` plugins have this convention about naming? If yes, I could add a fixed prefix to the `require` statement. No problem. If you want to support both versions (with and w/o prefix) I'll have to do some sting search & replace. Is this ok?

**Comment by ulivz** [comment]
We should support both versions since VuePress's plugin API (In branch) has supported it.

Feel free to open a pull request,

**Comment by neumayr** [comment]
@ulivz Because a lot has changed with the new `v1.0.0-alpha` progress. 
Is the initial idea still ok, or is there a better integration concept (automatically fetching missing markdown-plugins) like it's done with `vuepress` plugins…
