### ISSUE TITLE
missing information about host and port on `vuepress dev`

### ISSUE THREAD

**Issue by r3stm4n** [vuejs/vuepress#591]
#### Version
0.10.1

#### Steps to reproduce
```bash
vuepress dev
```

1. Linux Mint 18 (nice information with host and port) -> two core cpu

  ```bash
  DONE  [20:55:36] Build 51a13d finished in 8671 ms!
  
  > VuePress dev server listening at http://localhost:8080/
  ```

2. Linux Centos7 (missing information about host and port) -> 8 core cpu

  ```bash
  DONE  [20:54:23] Build 314a34e finished in 8422 ms!
  ```

  After commenting clearing screen in `node_modules/vuepress/lib/webpack/DevLogPlugin.js`
   
  ```bash
  WAIT  Extracting site metadata...

  DONE  [21:00:21] Build dead0a finished in 4274 ms!

  > VuePress dev server listening at http://localhost:8080/

  DONE  [21:00:22] Build 7450bc finished in 120 ms!

  > VuePress dev server listening at http://localhost:8080/
  ```

#### What is expected?
information about host and port

#### What is actually happening?
missing information about host and port - maybe related to number of cpu cores

#### Other relevant information

- Your OS: Linut Mint 18 and Linux Centos 7
- Node.js version: v10.4.1
- Is this a global or local install? local 
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Sorry but I cannot give you any useful suggestion, since I didn't ever use it in a linux(**with 8 core cpu**), 

In my MAC(with 4 core cpus) the `clearScreen`  will only scroll the terminal's bottom to the top.

**Comment by dkebler** [comment]
Same OS and versions as OP.  Same here no info on host port being displayed on dev server start.    I do not see any "rebuild" happening either after adding a readme.md.  Sadly this bug is a non-starter for me.  On to another project (docsify etc) that worked fine out of the box.

```
 DONE  [11:15:01] Build f7c838 finished in 222 ms!
```
that's all my terminal shows
