### ISSUE TITLE
Force adding of `index.html` to router links

### ISSUE THREAD

**Issue by alex-exerve** [vuejs/vuepress#592]
Is there an option to have vuepress add `index.html` to router links instead of using `/`?

We are creating some documentation that will be available to developers. However, it will be served in a manner that doesn't allow automatically picking up on index.html. Due to the way the router currently is created, the `home-link` in default-theme will always be equal to `config.js::modules.export.base` and thus the site logo/title will not link to an index.html

I was looking through the documentation and couldn't find a way to make this happen without ejecting the theme and doing it myself manually.

I can also redo this as a feature request and/or implement it if someone points me in the right direction of where the router creation is.

**Comment by meteorlxy** [comment]
From my understanding, adding `index.html` is the default behavior.

https://github.com/vuejs/vuepress/blob/64bb80d91a854ec02725d4dbcdaeb99a9bfa8a77/lib/prepare/codegen.js#L34-L40

**Comment by alex-exerve** [comment]
I think my main issue is in this line, now that i'm looking at it:

https://github.com/vuejs/vuepress/blob/64bb80d91a854ec02725d4dbcdaeb99a9bfa8a77/lib/default-theme/Navbar.vue#L4

since it's using the $localePath (which is currently set to `/`) it will not link to `index.html`.  

Let me try setting my locale and see if that fixes it.

**Comment by alex-exerve** [comment]
Okay so yeah, it looks like the issue is that it is using the base/localePath, and won't use the root 'index.html' as the link to the home page in the navbar.

**Comment by meteorlxy** [comment]
Oh I catch your point. Currently we redirect '/index.html' to '/'. Maybe we should redirect '/' to '/index.html' instead?

**Comment by alex-exerve** [comment]
> Oh I catch your point. Currently we redirect '/index.html' to '/'. Maybe we should redirect '/' to '/index.html' instead?

Or at least give an option in the themeConfig maybe?

**Comment by ycmjason** [comment]
If @alex-exerve 's environment do not support `/`, I don't think redirecting `/` to `/index.html` could help because the redirection we are doing is on the client side (?)

**Comment by alex-exerve** [comment]
True, but it's more about being able to right click a link and copy the url and give it to someone else. At that point it is a redirection issue since new person hasn't been to said thing yet.

This is really not that big of a deal, and was more of an odd thing I ran into in my specific environment. It might be something where it is outside the scope of this project as a whole and I just need to create my own theme to handle this specific issue since it appears to be that one specific link in the navbar.

**Comment by ulivz** [comment]
@alex-exerve 

Don't know  if the `public/_redirects` file could help you. refs: [vue-router > _redirects](https://github.com/vuejs/vue-router/blob/dev/docs/.vuepress/public/_redirects)

---

Before adding any new feature to the core, we will consider the complexity brought about by the feature and the actual meaning it produces. for a very rare requirement that can also be done on the user-land, our principle is not to add it to core. sorry but this is our principle.
