### ISSUE TITLE
image for base64 code in md file

### ISSUE THREAD

**Issue by xubowenjx** [vuejs/vuepress#596]
## Bug report
我将一个图片转化为base64格式后在md文件中这样插入
I got a base64 code from a image and insert into the md file as this:
```js
![](data:image/*;base64,【the base64code】)
```
部署后无法正常显示图片，但是如果我将`data:image/*`修改为`data:image/png`后，则显示出正常图片
But it can't show the original image，if I change `data:image/*` to `data:image/png`，it works。
#### Version
V0.10.1
#### Other relevant information

- Your OS: win7
- Node.js version: V9.1.0
- Browser version: Chrome V66
- Is this a global or local install?  Yes
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
Refer to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), the correct syntax is:

```
data:[<mediatype>][;base64],<data>
```
