### ISSUE TITLE
event not found

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [vuejs/vuepress#6]
bash-3.2# echo "# Hello VuePress!" > test.md
bash: !": event not found

maybe it caused by npm? : 
bash-3.2# npm config get registry
https://registry.npm.taobao.org/

**Comment by egoist** [comment]
Try StackOverflow it before creating an issue, `!` is a special char to bash.

**Comment by mqhe2007** [comment]
This step is a demonstration. It is not a necessary operation. You can skip it.

**Comment by webtaculars** [comment]
As specified by @mqhe2007, you can skip it. But if you want to use `!` then use it as `\!`.
