### ISSUE TITLE
[Feature request] custom `themeLayoutPath`

### ISSUE THREAD

**Issue by tyrion-yu** [vuejs/vuepress#600]
#### What problem does this feature solve?

VuePress resolves theme by using path as `vuepress-theme-${siteConfig.theme}/Layout.vue`.
But for some security reason, some companies have their own `npm registry`. And the VuePress themes using in the company should only publish in the `private npm registry`. For no conflict with the public npm registry, the private npm packages published in the company should with a scope like `@cip/vuepress-theme-security`.

#### What does the proposed API look like?

in `.vuepress/config.js`

``` js
module.exports = {
  themeConfig:{
    layoutPath: `@cip/vuepress-theme-security`
  }
}
```

#### How should this be implemented in your opinion?

``` js

// resolve theme
const useDefaultTheme = (
  !siteConfig.theme &&
  !siteConfig.layoutPath &&
  !fs.existsSync(path.resolve(vuepressDir, 'theme'))
)

// prepare.js
try {
  const layoutPath = siteConfig.layoutPath? `${siteConfig.layoutPath}/Layout.vue`
    : `vuepress-theme-${siteConfig.theme}/Layout.vue`
  themeLayoutPath = require.resolve(layoutPath, {
    paths: [
      path.resolve(__dirname, '../node_modules'),
      path.resolve(sourceDir)
    ]
  })
  themePath = path.dirname(themeLayoutPath)
}
```

#### Are you willing to work on this yourself?**

I'm not sure.

**Comment by andreasvirkus** [comment]
We should be able to copy this logic from vue-cli plugin lookup. I can look into it over the coming weekend, if there's no takers beforehand
