### ISSUE TITLE
[Feature request] possiblity to easily include Matomo

### ISSUE THREAD

**Issue by chrtz** [vuejs/vuepress#604]
## Feature request
I'd like to see a possibility to include Matomo (ex. piwik) instead of Google Analytics.

Maybe this could be implement as an upcoming PlugIn.
I don't know if this would be hard to build in.

#### What problem does this feature solve?
Tracking on serverside with Matomo instead of Google Analytics.
#### How should this be implemented in your opinion?
Maybe by default or PlugIn
#### Are you willing to work on this yourself?**
Sure if there would be a way I can help

**Comment by ulivz** [comment]
Thanks for your reporting, sure, it can be done by a plugin.

**Comment by chrtz** [comment]
For now, I would have to include the Matomo/piwik script in every single file, if I got it right.
So the plug-in should maybe just autoimplement the Matomo script in every rendered HTML.

Thanks for recognizing

**Comment by ulivz** [comment]
I just forgot that you can accomplish this by [enhanceApp](https://vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements) for now. instead of including the `Matomo/piwik` script in every single file.
