### ISSUE TITLE
iPhone's Safari Auto-zoom after Search use

### ISSUE THREAD

**Issue by Paulcoops** [vuejs/vuepress#606]
#### Version
0.10.2

#### Steps to reproduce
Tap search field on iPhone/Safari, type and click a search result. The result page now stays zoomed-in. 

#### What is expected?
Zoom back to scale: 1 on new page or disable auto-zoom.

#### What is actually happening?
All pages navigated after using the search field stay zoomed-in unless user zooms-out manually.

#### Other relevant information

- Your OS: 10.13.5 Beta (17F70a) 
- Node.js version: v8.11.3
- Browser version: Safari iOS 11.3.1
- Is this a global or local install? global
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
Thanks for your reporting but it isn't a bug, see: [HTML5 History Mode](https://router.vuejs.org/guide/essentials/history-mode.html).

When you click the search result, the page doesn't really reload. so the page will stay zoomed-in.

**Comment by andreruffert** [comment]
I've opened a PR #2841 to disable the auto-zoom for the search on iOS devices.
