### ISSUE TITLE
Change collapsable to collapsible in sidebar groups config

### ISSUE THREAD

**Issue by mattixittam** [vuejs/vuepress#607]
#### What problem does this feature solve?

Sidebar groups config in the default theme contains the collapsable prop. My instinctual reaction was that this should be collapsible. While both versions of the word are correct, collapsible is by far the most used (source: google search, ratio is about 10:1). I think changing it may save some people having to go to the docs to find the correct spelling.

#### What does the proposed API look like?

```md
module.exports = {
  themeConfig: {
    sidebar: [
      {
        title: 'Group 1',
        collapsible: false,
        children: [
          '/'
        ]
      }
    ]
  }
}
```

#### How should this be implemented in your opinion?
Well, I realise this is a breaking change and a bit of a pet peeve, so perhaps not at all. But I did want to bring it up, since we are pre-1.0 and there might still be a window.

#### Are you willing to work on this yourself?
Sure, I'll do a PR if this is deemed a good suggestion.

**Comment by ulivz** [comment]
Thanks for your suggestion, but since `collapsable` has been able to get the result what user want:

![image](https://user-images.githubusercontent.com/23133919/41782463-e146202c-766c-11e8-9d67-9f606a19420c.png)

It also has no side effects, so it isn't worth taking breaking change for that.

**Comment by mattixittam** [comment]
Sure, I find your reasoning a bit off (my issue wasn't about a google search working, but intuitively misspelling in the config file), but I can accept that this may not be worth a breaking change.

**Comment by ulivz** [comment]
We have set alias `collapsible` for `collapsable` at #706.
