### ISSUE TITLE
Option to disable svg in external links

### ISSUE THREAD

**Issue by octref** [vuejs/vuepress#610]
`<OutboundLink>` generates an icon like this:

![image](https://user-images.githubusercontent.com/4033249/41814347-2bd0d3d0-76fe-11e8-9230-70e63e3fef18.png)

There should be an option to turn this off.

**Comment by octref** [comment]
It make sense to include it in the theme, however including it in the default markdown renderer and not offering anyway to turn it off is forcing this icon to everyone, even those who's not using the default theme.

**Comment by dcastil** [comment]
What is the status of this feature? I would like to be able to disable the OutboundLink component and think it should be rather opt-in with a plugin.

**Comment by xinconan** [comment]
How to disable svg in external links? The web site has  removed svg, https://vuepress.vuejs.org/config/, but I can't find config option.

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/pull/614#issuecomment-472482023

**Comment by morphatic** [comment]
If you only want to hide the outbound link icon only in certain cases you can hide it with CSS. For example, in my site I sometimes wrap images in external links, e.g.

```markdown
[![some img](/assets/images/some.png)](http://someothersite.com)
```

The HTML rendered by this looks something like:

```html
<a href="http://someothersite.com" target="_blank" rel="noopener noreferrer">
  <img src="/assets/images/some.png" alt="some img">
  <svg class="icon outbound">... this is the external link icon ...</svg>
</a>
```

And results in an image with the external link icon after it like this:

![some img](https://imgur.com/gL4xXvU)

In my CSS, I can use a sibling selector to hide the icon like this:

```css
img + .icon.outbound {
  display: none;
}
```

This is pretty flexible and wouldn't require you to disable all of `markdown-it`. HTH!

**Comment by deancn** [comment]
```
  markdown: {
    externalLinkSymbol: false,
  },
```

![image](https://user-images.githubusercontent.com/1617384/76280663-8bb60100-62cd-11ea-826e-67a853969aed.png)


do not work yet.  Any thing wrong?
