### ISSUE TITLE
extend functionality of Code Snippets Import

### ISSUE THREAD

**Issue by tk1** [vuejs/vuepress#612]
## Feature request

It would be very convenient
1.  to import only a few lines of a file
2.  to specify the begin and end of the region to be imported by regular expressions
3. to specify the lines to be highlighted by a regular expression

#### What problem does this feature solve?

If a file is big and only a few lines are interesting to demonstrate an idea, you could extract those lines easily.

When using regular expressions, you don't need to count line numbers and change them when inserting lines into the file. You could write regular expressions which match certain code lines or comments, e.g. `/* start-snip */`.

#### What does the proposed API look like?

`<<< @/filepath{from=reFrom, to=reTo, inclusive=[yes|no], highlight=reHighlight}`

where `reXXX` are regular expressions. Then the region to be extracted would start at the first match of `reFrom` and end at the first following match  of `reTo`. If `inclusive=yes` then the matching lines are included, otherwise excluded. All the lines in the region which match `reHighlight` will be highlighted.

All properties should be optional:
* If `from` and `to` are missing the whole file will be included
* If `from` is given and `to` is missing `to` will be the end of the file regardless of `inclusive`
* If `from` is missing and `to` is given, `from` will be the start of the file regardless of `inclusive`
* The default value for `inclusive` is `yes`.
* If `highlight` is missing, nothing is highlighted.

#### How should this be implemented in your opinion?

By extending the current `Import Code Snippet` Markdown functionality.

#### Are you willing to work on this yourself?**

I'm not proficient in Markdown extensions.

**Comment by ulivz** [comment]
Thanks for your interest in vuepress, but we'll refine the code snippet's API later, see: 

- https://github.com/vuejs/vuepress/pull/538#issuecomment-394572010
- https://github.com/vuejs/vuepress/pull/538#issuecomment-394579033

And I don't think we should support Regular Expressions at this feature. If you want to demonstrate some of those lines, why not write them directly?

cc @znck

**Comment by tk1** [comment]
I like it more to get my example lines automatically from working code files instead of using copy & paste. If something is changed in the example code the change will carry over to the documentation automatically.

**Comment by daggerok** [comment]
Hi @ulivz,

I wasn't able to found in documentation example, how to include only part of source code from a real project file, which can contains a lot of noice, useless for demonstration...

Please, let me know if you have plans to support partial code snippet in a future. Similarly like we have in asciidoctor, where in real source code file in comments we can mark from-to lines will be included in a snippet:

```java
// some App.java file
package com.verylong.packagename;
import ...;
// other code, useless for snippet
// tag::my-subject[]
  publis static void main(...) {
    // ...
  }
// end::my-subject[]
```

```adoc
// somewhere in docs/README.adoc file
include::../src/main/java/com/verylong/packagename/App.java[tags=my-subject]
```

which id different from full file inclusion:

```adoc
include::../src/main/java/com/verylong/packagename/App.java[]
```

With that I can point only to important thinks when showing code snippets and do not need remember update also documentation if that code will be changed, it will be done automatically on next build...

It's really useful feature and can help avoid code snippet reusability and documentation update right during development...
