### ISSUE TITLE
Consider extracting default theme into its own repository

### ISSUE THREAD

**Issue by Loilo** [vuejs/vuepress#617]
## Feature request
It may be worth considering to put the default theme into its own repository.

#### What problem does this feature solve?
Userland themes could be a great deal for VuePress. Most theme authors though will probably start with modifications to the default theme. That's easy thanks to `vuepress eject`.

However, it would be even nicer if theme authors would be able to just GitHub-fork a `vuepress-default-theme` repository — mainly because it would allow pulling updates from the default theme's *logic* (sidebar, nav, ...) which many theme authors probably wouldn't touch anyway.

#### What does the proposed API look like?
—

#### How should this be implemented in your opinion?
There may be a new repository with a `lib` folder containing all the current theme files. The theme could be ported back into the `vuepress` repo as a git submodule or via git subtree.

#### Are you willing to work on this yourself?
Yes.

**Comment by ulivz** [comment]
Thanks for your suggestion, but this is a long way to go, especially we haven't released the plugin API and the additional theme API. 

This is probably what 2.x is going to think about.

**Comment by faroit** [comment]
@ulivz is this still 2.x land considering the current progress on 1.0? If not, I would propose to reopen this.

**Comment by ulivz** [comment]
@faroit See: https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/theme-default

**Comment by faroit** [comment]
@ulivz Excellent. Keep up the great work. Is there a official roadmap for 1.0?
