### ISSUE TITLE
[Feature request] Lazy loading routes

### ISSUE THREAD

**Issue by AWulkan** [vuejs/vuepress#618]
## Feature request
Ability to lazy load pages.

#### What problem does this feature solve?
Increase initial load times. When doing SEO it is important that your site loads fast when a user goes to it from search engines, otherwise your bounce rate might increase. Google also measures your page load speed as a ranking factor, they don't like slow sites. It is also generally a good thing to have for UX if people are on slow connections or if you got a *huge* site with hundreds of pages (blogs for example).

#### What does the proposed API look like?
I don't know, but the Vue router supports lazy loading, right?
https://router.vuejs.org/guide/advanced/lazy-loading.html

#### How should this be implemented in your opinion?
I don't know. It would be good to make it optional though.

#### Are you willing to work on this yourself?**
I don't think I'll be able to solve this since I don't know enough about Vuepress and I've never used lazy loading in Vue before.

**Comment by ulivz** [comment]
Hmmm, we are using lazy load now.

**Comment by AWulkan** [comment]
@ulivz Ok, maybe I misinterpreted what it does. What are all of these JS files that loads on the first page visit then?
![](https://i.imgur.com/5cdBagL.png)

**Comment by ulivz** [comment]
See: 

- [vue ssr > shouldprefetch](https://ssr.vuejs.org/api/#shouldprefetch)
- [vuepress > shouldprefetch](https://vuepress.vuejs.org/config/#shouldprefetch)
