### ISSUE TITLE
Mixing HTML and Markdown in single block does not work

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vuepress#619]
## Bug report

Using markdown syntax inside of HTML blocks results in raw output of markdown code instead of parsed result.

#### Version
`v0.10.2`

#### Steps to reproduce

Create page with such content:
```
<dl class="dl-horizontal">
	<dt>Content <small>[Editor](/ponteus/editor)</small></dt>
</dl>
```

#### What is expected?
Markdown link should be parsed along with the surrounding HTML block content, resulting in outputting HTML `<a/>` tag in this case.

#### What is actually happening?
Markdown content is not parsed at all, outputting plain `[Editor](/ponteus/editor)` as is.

**Comment by ulivz** [comment]
You cannot mix the markdown and HTML syntax at the same line.

Only when you put them into different lines so [markdown-it](https://github.com/markdown-it/markdown-it) can know whether it was HTML or md tokens.

This is a workaround:

``` md
<dl class="dl-horizontal">
	<dt>Content<small>

[Editor](/ponteus/editor)

  </small>
  </dt>
</dl>
```

But why not using the `<a>` tag directly.

> FYI: Please don't mix inline syntax. For the multi-line syntax, make sure there is a blank line between HTML and markdown token.
