### ISSUE TITLE
Create a plugin system and a guide on how to create plugins

### ISSUE THREAD

**Issue by FadySamirSadek** [vuejs/vuepress#62]
I think Plugins are one of the most essential things in static site generators as they do a lot of functionalities that can not be implemented otherwise so I think there should be a guide explaining how to create a plugin and future plans on the plugin system

**Comment by yyx990803** [comment]
Unlike other static site generators, almost everything can be done either in a custom theme (which is a full Vue app) or tweaking the postcss/webpack config via the [build pipeline options](https://vuepress.vuejs.org/config/#build-pipeline).

Do you have any specific use case that cannot be solved with these?

**Comment by MartinMuzatko** [comment]
It would be nice to have documented how e.g. custom containers can be added.
Right now, they are hardcoded here: https://github.com/vuejs/vuepress/tree/master/lib/markdown

I can't find documentation how to these kind of functionality can be added to e.g. markdown.

**Comment by mdaffin** [comment]
One problem I have had is the inability to generate flat files based on site data (redirect links, sitemap, rss feeds, other hosting provider configs). I have attempted to solve this problem in #196 which gives themes and the site a possibility to hook into the `options` value just before the `prepare.js` ends. It is not a general purpose plugin system, just gives themes and sites the ability to add a low-level hook that runs on the server side rather then client side.

**Comment by ulivz** [comment]
Let's continue discussion at the roadmap "channel" (#198).
