### ISSUE TITLE
Giving relative urls for prev/next yields unexpected results

### ISSUE THREAD

**Issue by Uriziel01** [vuejs/vuepress#623]
## Bug report

When plain relative (omitting dot dash notation) urls are given inside of frontmatter prev/next blocks the resulting links are targeting some random pages not the pages user expects
#### Version
`v10.2`
#### Steps to reproduce

Crete page with frontmatter prev/next values like (Im using json syntax):
```
"prev": "author-info-box",
"next": "breadcrumb"
```

#### What is expected?

Resulting prev/next links should point to 'mydomain.com/shortcodes/author-info-box' and 'mydomain.com/shortcodes/breadcrumb' pages.

#### What is actually happening?

Resulting prev link is some random page ("mydomain.com/shortcodes/author" in my case) and next points to the exact page Im currently on now (which is quite nonsense on its own and certainly not correct).

Modifying the values to:
```
"prev": "./author-info-box",
"next": "./breadcrumb"
```
fixes everything and generates correct links and points to `mydomain.com/shortcodes/author-info-box` and `mydomain.com/shortcodes/breadcrumb`

**Comment by ulivz** [comment]
My file structure:

```
├── README.md
├── assets.md
└── deploy.md
```

and I just tested:

```md
---json
{
  "prev": "./deploy",
  "next": "deploy"
}
---
```

Both of them get the correct links for me.

So if it truly turns out to be a bug, please provide a reproduction link.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
