### ISSUE TITLE
Vuepress attempts to parse files ending in JPG

### ISSUE THREAD

**Issue by MichaelJPDX** [vuejs/vuepress#625]
#### Version

0.10.1

#### Steps to reproduce

I have images in folders with the extension JPG (uppercase) instead of lowercase jpg. Vuepress in dev mode will throw errors if these are referenced in a file. Errors go away if you rename the file with a lowercase extension.

#### What is expected?

Vuepress should treat .JPG and .jpg the same.

#### What is actually happening?

Attempts to parse the files and throws errors.

#### Other relevant information

- Your OS: MacOSx High Sierra
- Node.js version: 8.10.0
- Browser version: Chrome 67.0.3396.87 
- Is this a global or local install? local (dev)
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Thanks for your reporting, but after looking for some specifications, I think we shouldn't support this.

See:

1. Recommended config from [url-loader](https://github.com/webpack-contrib/url-loader):

``` js
        test: /\.(png|jpg|gif)$/,
```

Note that it's case sensitive.

2. [Naming conventions (file formats)](https://en.wikipedia.org/wiki/Wikipedia_talk:Naming_conventions_(file_formats)):

> ... many people advocate writing file extensions in lowercase ...

3. [Why should one prefer lower case file extensions like .jpg over uppercase ones like .JPG?](https://superuser.com/questions/914914/why-should-one-prefer-lower-case-file-extensions-like-jpg-over-uppercase-ones-l):

> All file names should be in lower case.
