### ISSUE TITLE
Object Spread Operator

### ISSUE THREAD

**Issue by galvez** [vuejs/vuepress#626]
@yyx990803 Pardon my ignorance, but is there a reason why the object spread operator isn't used? I see several occurrences of `Object.assign()` in the code, but `...` has been natively supported by Node for a while now?

**Comment by ulivz** [comment]
See [object spread properties](https://node.green/#ES2018-features-object-rest-spread-properties-object-spread-properties), node supported it since node@8.6.0, but VuePress should work at any version of greater than 8.

**Comment by galvez** [comment]
Thanks for clarifying @ulivz
