### ISSUE TITLE
Customize the default theme

### ISSUE THREAD

**Issue by mittalyashu** [vuejs/vuepress#627]
#### What problem does this feature solve?
I didn't find any option to add logo/icon to the navbar, so customizing on a new theme is not a good idea, where we have to only add a div.

#### What does the proposed API look like?
Not sure

#### How should this be implemented in your opinion?
By adding the option of customizing the default theme.

#### Are you willing to work on this yourself?
I will try.

**Comment by ulivz** [comment]
See: [eject](https://vuepress.vuejs.org/default-theme-config/#ejecting)

> You can copy the default theme source code into `.vuepress/theme` to fully customize the theme using the `vuepress eject [targetDir]` command

**Comment by mittalyashu** [comment]
I get that

> Note, however, once you eject, you are on your own and won't be receiving future updates or bug fixes to the default theme even if you upgrade VuePress.

But if that's the case, then how can I update the changes that Vuepress will make in the default theme.

**Comment by faroit** [comment]
@ulivz did you consider having the default theme as a separate plugin for 1.0 so that ejecting is not necessary anymore but rather allow people to fork the default theme?
