### ISSUE TITLE
Support three level sidebar

### ISSUE THREAD

**Issue by jeely919** [vuejs/vuepress#630]
## Feature request
Support three level sidebar

#### What problem does this feature solve?
Common nedds

#### What does the proposed API look like?
```
[
  {
    title: '概述',
    children: ['introduce',  'quick-start']
  },
  {
    title: '组件',
    sub: [
      {
        title: '基础组件',
        children: ['button',  'tab']
      },
      {
        title: '滚动组件',
        children: ['scroll',  'list']
      }
    ]
  }
]
```

#### How should this be implemented in your opinion?
Add level

#### Are you willing to work on this yourself?**
No, no plan to see the vuepress source code

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, but for now we don't plan to support more deep-level sidebar.

**Comment by jeely919** [comment]
I hope will support in the future
