### ISSUE TITLE
Unable to active nav

### ISSUE THREAD

**Issue by jeely919** [vuejs/vuepress#631]
## Bug report
If I specify nav default link to a markdown file, the nav will not activate when I choose other.
My goal is to link a sidebar item with nav.

#### Version
Newest

#### Steps to reproduce
As abo

#### What is expected?
Specify nav default link to a markdown file, Active nav when I choose other sidebar. 

#### What is actually happening?
Unable to active nav

#### Other relevant information

- Your OS: mac
- Node.js version: 8 
- Browser version:  chrome
- Is this a global or local install?  local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Sorry but I cannot get what you want.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
