### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by danielmlc** [vuejs/vuepress#632]
#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
It's emitted by **server-plugin** in [vue-server-renderer](https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer).

Of course, it has been fixed at https://github.com/vuejs/vue/pull/7839, and you will not see this warning from `vue-server-renderer@2.6`. (now: we are `2.5.17-beta.0`), so let wait for the next release of Vue.
