### ISSUE TITLE
Disable base64 representation

### ISSUE THREAD

**Issue by mittalyashu** [vuejs/vuepress#633]
#### What problem does this feature solve?

We can use a direct image URL instead of base64 representation.

![carbon](https://user-images.githubusercontent.com/29014463/42345333-9a036c24-80bc-11e8-8a31-1220816525aa.png)

#### How should this be implemented in your opinion?

By writing [custom webpack configuration](https://vuepress.vuejs.org/config/#configurewebpack)

#### Are you willing to work on this yourself?**
I will try.

#### Links
* [How to add logo in vuepress?](https://spectrum.chat/thread/45c105a9-6227-406e-872c-4ec55b1fccb7)

**Comment by ulivz** [comment]
I am sure that we can use image URL directly. or maybe I misunderstand what you want, so could you provide a reproduction link or usage? that will be more direct.

**Comment by mittalyashu** [comment]
I have used the image URL directly, but it converted into base64 representation.

Here's the [repo link](https://gitlab.com/mittalyashu/vuepress-demo).

**Comment by ulivz** [comment]
@mittalyashu 

If you don't want it to be converted, you should move the `assets` to `.vuepress/public`

Then, change:

``` html
<img :src="./assets/img/stylechip-icon.png" alt="Stylechip logo icon">
```

to:

``` html
<img :src="./assets/img/stylechip-icon.png" alt="Stylechip logo icon">
```

**See: **

- [Public Files](https://vuepress.vuejs.org/guide/assets.html#public-files)

**Comment by mittalyashu** [comment]
Okay, but apart from that if you can custom webpack configuration that would also be great.

**Comment by ulivz** [comment]
Okay, you need to remove the default rule first:

``` js
  config.module.rules.delete('svg')
  config.module
    .rule('fonts')
      .test(/\.(woff2?|eot|ttf|otf)(\?.*)?$/i)
      .use('url-loader')
        .loader('url-loader')
        .options({
          // Your options here, default options:
          // limit: 10000,
          // name: `assets/fonts/[name].[hash:8].[ext]`
        })
```
