### ISSUE TITLE
[Feature request] Config option to disable prefetch links, or only prefetch certain pages

### ISSUE THREAD

**Issue by jakeg** [vuejs/vuepress#636]
#### What problem does this feature solve?

Sites with many pages don't want to prefetch all pages. For example, a site with 1,000+ pages may want to prefetch no pages, or a small selection of main pages.

#### What does the proposed API look like?

In `.vuepress/config.js` add an option `prefetch` which defaults to `true` but can be changed to `false` to not prefetch any pages, or an array of pages.

```js
module.exports = {
  // To not do any prefetching of pages
  prefetch: false,
  // Or to prefetch a selection of main pages
  prefetch: [
    '/about',
    '/faq',
    '/contact'  
  ]
}
```

**Comment by ulivz** [comment]
For request 1, we have supported, see: [shouldPrefetch](https://vuepress.vuejs.org/config/#shouldprefetch).

For request 2, Since VuePress's `prefetch` is based on `vue-server-renderer`, and only when Vue SSR supports so fine-grained control can we implement it. so please create this feature request for `vue-server-renderer`.

**Comment by jakeg** [comment]
Thanks. Really weird caching issue or something on the page you linked to there... at first the `shouldPrefetch` block didn't appear at all, had to refresh several times to see it.

**Comment by ulivz** [comment]
That's the issue of service worker, make sure you have closed all the previous vuepress website tabs before opening this link.

BTW, we'll have a update popup UI in the future: https://github.com/vuejs/vuepress/pull/533

**Comment by robmuh** [comment]
Just a note that the documentation on `shouldPrefetch` has an example with a `preload` link in it. It through me for a bit having just read about the difference between `shouldPreload` in the main Vue docs.

![screen shot 2018-11-20 at 1 11 35 pm](https://user-images.githubusercontent.com/3749067/48793837-3d3eb680-ecc6-11e8-9c77-6262434a7b33.png)

**Comment by adarshmadrecha** [comment]
Now in `v2.5.0 +` of `vue-server-renderer` has support for defining function and can customize which paths should be prefetched.

https://ssr.vuejs.org/api/#shouldprefetch

```js
  shouldPrefetch: (file, type) => {
    // type is inferred based on the file extension.
    // https://fetch.spec.whatwg.org/#concept-request-destination
    if (type === 'script' || type === 'style') {
      return true
    }
    if (type === 'font') {
      // only preload woff2 fonts
      return /\.woff2$/.test(file)
    }
    if (type === 'image') {
      // only preload important images
      return file === 'hero.jpg'
    }
```
