### ISSUE TITLE
Adapting vuepress to genaral purpose single-file publishing / Jupyter notebooks as PDF, MS Word and others killer

### ISSUE THREAD

**Issue by kiwi0fruit** [vuejs/vuepress#646]
## Feature request

Not long ago the [Idea to enhance nbviewer with js/css plugins to make nbviewer+ipynb secure, dynamic and mobile friendly](https://github.com/kiwi0fruit/misc/blob/master/pdf_and_word_killer.md) visited me. The proposed idea would create a new HTML-based online publishing experience. New in a sense that we are still to get a free secure one click solution convenient both for the content publishers (that want Word-like simplicity) and for content readers on desktop and mobile (sic!).

#### What problem does this feature solve?
Adapting vuepress to genaral purpose single-file publishing: user creates a single file document (like [Lecture-1-Jaynes-Cumming-model.ipynb](https://github.com/jrjohansson/qutip-lectures/blob/master/Lecture-1-Jaynes-Cumming-model.ipynb)), uploads it or IM sends, then the other people can view it online via on-demand preprocess (like on [nbviewer.jupyter.org](https://nbviewer.jupyter.org/github/jrjohansson/qutip-lectures/blob/master/Lecture-1-Jaynes-Cumming-model.ipynb)) by link or upload.

I mostly thought about sciense articles/reports publishing this way but it seems to be suitable for any Word like documents.

Actually this workflow assumes that the conversion would happen on demand on the web-server side (presumably without caching - for privacy concerns). I'm not sure if it can fast enough using vuepress. So this is the question to start with.

#### Are you willing to work on this yourself?
Not in the near future. But I like the idea too much to drop it.

**Comment by ulivz** [comment]
I am sorry I cannot get what you want. could you speak more easily?

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
