### ISSUE TITLE
Support for opengraph 

### ISSUE THREAD

**Issue by besrabasant** [vuejs/vuepress#647]
How do I add **opengraph** namespace to the `html` tag?
```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml">
```

**Comment by ulivz** [comment]
See: [head](https://vuepress.vuejs.org/config/#head).

**Comment by besrabasant** [comment]
I tried using it... but no tags are added to the head and I want to add those attributes to `html` tag

**Comment by besrabasant** [comment]
No @codeofsumit. I switched to nuxt.js.

**Comment by ulivz** [comment]
I guess it's related to https://github.com/vuejs/vuepress/issues/733.

You can move here to get the workaround.
