### ISSUE TITLE
Base setting is added to url two times

### ISSUE THREAD

**Issue by gintsgints** [vuejs/vuepress#649]
#### Version
0.12.0
#### Steps to reproduce

Basic site is made at - https://gitlab.com/gintsgints/myblog
Configuration of base is set to myblog.

#### What is expected?
Site to show up at - https://gintsgints.gitlab.io/myblog/

#### What is actually happening?
Scripts are not loading because myblog is added for sources two times.
https://gintsgints.gitlab.io/myblog/myblog/assets/css/0.styles.5ea31811.css

#### Other relevant information

- Your OS: Linux
- Node.js version: 9.11.1
- Browser version: n/a
- Is this a global or local install? global
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
See [docs](https://vuepress.vuejs.org/config/#base):

> then base should be set to "/bar/". **It should always start and end with a slash.**

**Comment by gintsgints** [comment]
OMG... sry... do not know how I could miss that.
