### ISSUE TITLE
Make custom containers' default labels configurable by locale config

### ISSUE THREAD

**Issue by Loilo** [vuejs/vuepress#659]
#### What problem does this feature solve?
The default labels `TIP` and `WARNING` of custom containers are not configurable. However, they *should* be, for localization purposes.

#### What does the proposed API look like? / How should this be implemented in your opinion?
The default labels stay unchanged, but the

* `$themeLocaleConfig.customContainer.tip`
* `$themeLocaleConfig.customContainer.warning` and
* `$themeLocaleConfig.customContainer.danger`

values take precedence over them.

#### Are you willing to work on this yourself?
I think this should be a rather simple implementation, and therefore I think it's better suited for someone who's already proficient in the VuePress codebase. However, should nobody be willing to work on this, I'd give it a shot.

**Comment by Shigma** [comment]
Let's move to https://github.com/vuepress-contrib/vuepress-plugin-container/issues/1.
