### ISSUE TITLE
Markdown italics immediately after bold removes space

### ISSUE THREAD

**Issue by FistMeNaruto** [vuejs/vuepress#661]
#### Version
v0.12.0
#### Steps to reproduce

Write `**testing** _testing_` in any page

#### What is expected?
Space between italics and bold e.g. **testing** _testing_

#### What is actually happening?
Space gets removed

![screenshot from 2018-07-21 11-58-29](https://user-images.githubusercontent.com/13431677/43034053-6b326738-8cdd-11e8-8040-c3e0af89a85e.png)

```html
<p>testing <strong>testing</strong><em>testing</em><strong>testing</strong></p>
```

#### Other relevant information

Markdown-it online parser seems to handle this correctly

```html
<p class="line" data-line="0">testing <strong>testing</strong> <em>testing</em> <strong>testing</strong></p>
```

[Link here](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22testing%20%2A%2Atesting%2A%2A%20_testing_%20%2A%2Atesting%2A%2A%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

- Your OS: Arch Linux
- Node.js version: 6.2.0
- Browser version: Chromium 67.0.3396.87
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
Thanks for the reporting, fixed it at 7730ee1.
