### ISSUE TITLE
files after built can not be opened directly in browser

### ISSUE THREAD

**Issue by gardenzjd** [vuejs/vuepress#667]
files after built can not be opened directly in browser, and can not be used in electron.  we made some vuepress documents and hope to can be opened directly in browser or electron. but not deployed on a web server. how should we do?

**Comment by ulivz** [comment]
Of course you cannot do that, you can only serve vuepress dist files under a static server.  e.g. [express.static](http://expressjs.com/en/starter/static-files.html) or [koa-static](https://github.com/koajs/static).

BTW, please follow the issue reporting guidelines.

**Comment by cihanzengin** [comment]
@ulivz you sure ? because it was doing in vue projects with some configuration like 

build: {
    ...
    assetsPublicPath: '',
    ...
  }

and then was possible to use project directly in browser or in some standart ftp.

**Comment by ulivz** [comment]
@cihanzengin 

Hmmm, but not all the sites will be deployed to to root domain. so setting default `PublicPath` to `''` is not so meaningful.

See: https://github.com/vuejs/vuepress/issues/575#issuecomment-412420421

**Comment by ulivz** [comment]
Duplicate of #575

**Comment by cihanzengin** [comment]
@ulivz  what is the static server mean ?  
I'm using standard linux hosting. So may i need to some extra configuration on my hosting? 
Because using vuepress project just on heroku, digital ocean etc some specific hosting providers too not logical.

**Comment by cihanzengin** [comment]
@ulivz i understand now the point :) sorry. Yes when i upload content of dist folder to root of my ftp everything works well. 

now question is: where and with which configuration i can upload my builded vuepress projects to subfolder. not the root folder ?

**Comment by atilkan** [comment]
@cihanzengin You should check out **base** config.
