### ISSUE TITLE
Build Dist Caching

### ISSUE THREAD

**Issue by achendrick** [vuejs/vuepress#668]
## Feature request

I think it would be worth exploring having the dist work as a cache and somehow only build new pages since the last build.

#### What problem does this feature solve?
I have a fairly large site (>1000 pages), so I understand this is an edge case.
Each time I do a build, VuePress rebuilds each one of these pages.
This causes more than 2GB of RAM to be utilized, and sadly, most free CI tiers don't allow this much utilization.

#### How should this be implemented in your opinion?
Maybe have a new CLI param `vuepress build --use-dist`

#### Are you willing to work on this yourself?**
Possibly, but I'd need some guidance for where to get started and what to utilize.

**Comment by ulivz** [comment]
That's a great point, I need some time to do a research for current build performance.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by z3by** [comment]
This is a very important feature! we have about 1000 files and there is much more to come, and the build time is going beyond 30 minutes, this feature could make the build time less than one minute.
