### ISSUE TITLE
How to edit the docs?

### ISSUE THREAD

**Issue by nilswindisch** [vuejs/vuepress#67]
If I wanted to add some information about the [EU General Data Protection Regulation](https://www.eugdpr.org) (context: Google Analytics feature), where would I start?
Any help on how to make a pull request to appreciated.

**Comment by ulivz** [comment]
- Tool: Any editor
- Location: https://github.com/vuejs/vuepress/blob/master/docs/config/README.md#ga
- Step: fork => clone => add your code => open a PR

**Comment by yyx990803** [comment]
You can also directly edit on GitHub... Every page in the docs has an edit link at the bottom.

**Comment by nilswindisch** [comment]
Thank you @ulivz and @yyx990803

**Comment by nilswindisch** [comment]
Thanks again, I opened a related PR https://github.com/vuejs/vuepress/pull/515 with very minor changes to the docs (readme.md).
