### ISSUE TITLE
public image linked in md

### ISSUE THREAD

**Issue by xubowenjx** [vuejs/vuepress#670]
#### Version 
0.12
#### Steps to reproduce
1. one picture in .vuepree/public like 'logo.png'
2. set the base in .vuepree/config.js as "demo"
3. touch a file >docs/guide/myFile.md，and edit it
```md
![image](/logo.png)
```
Yes,It will get the path in page ```localhost:8080/logo.png```,because I lose the base path

```md
![image](/demo/logo.png)
```
It will work.
But how can I resolve  all images like this ? if I change the base path.
There is "$withBase" in docs, and How to use is 
```md
![image]($withBase('/logo.png'))
```
Tip: the heroImage is ok.
It will lose the base path .
#### What is expected?
Automatically supplement the base path
#### Other relevant information

- Your OS: Win7
- Node.js version: 9.1 
- Browser version: Google V66
- Is this a global or local install? local install
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by yuanlove521** [comment]
Have you solved it yet

**Comment by topwood** [comment]
same question
 ![image]($withBase('/logo.png')) does not work
while the doc says

> Note you can use the above syntax not only in theme components, but in your markdown files as well.

**Comment by FrankFan** [comment]
Have you solved it yet ? 

the same question to me.

**Comment by PeppeL-G** [comment]
> 
> 
> same question
> 
> ```
>  ![image]($withBase('/logo.png')) does not work
> ```
> 
> while the doc says
> 
> > Note you can use the above syntax not only in theme components, but in your markdown files as well.
> > [docs here](https://v1.vuepress.vuejs.org/guide/assets.html#public-files)

I think "the above syntax" refer to all the HTML code, i.e. `<img :src="$withBase('/foo.png')" alt="foo">`.
