### ISSUE TITLE
[Feature request] Localized pages routes

### ISSUE THREAD

**Issue by petzerhub** [vuejs/vuepress#673]
## Feature request

Define relations between localized pages, to allow different/translated routes and correct routes to the localized paths wen using a language switcher.

#### What problem does this feature solve?

Allow related localized routes for localized pages, instead of working only with identical slugs based on a primary language.

Instead of : 

```
/plugins/editing
/fr/plugins/editing
/de/plugins/editing
```

Having : 

```
/plugins/editing
/fr/extensions/edition
/de/plugins/redaktion
```

Ideally the current non-localized routes would be redirected to the localized ones, to allow editing the locale part in the url directly, like with the exemple above `/fr/plugins/editing` would redirect to `/fr/extensions/edition`.

#### What does the proposed API look like?

Defining routes relations in config or using some keys in pages metadata, and the localized versions would be listed in `this.$site.pages` & `this.$page` data for themes/language switching ?

#### How should this be implemented in your opinion?

Maybe related to https://github.com/vuejs/vuepress/issues/363#issuecomment-390719783 ?

#### Are you willing to work on this yourself?

Not sure I can help.

**Comment by ulivz** [comment]
Sorry but we don't plan to change the implementation of `i18n`. 

You can write `_redirects` in public dir to get what you want.

Ref: https://github.com/vuejs/vue-router/tree/dev/docs/.vuepress/public
