### ISSUE TITLE
themeConfig.serviceWorker.updatePopup only shows up on first page reload

### ISSUE THREAD

**Issue by jordonbaade** [vuejs/vuepress#677]
## Bug report

When pushing new content to a VuePress site with the themeConfig.serviceWorker.updatePopup enabled the popup only shows up the first page reload - if you don't click the refresh button the popup no longer appears for subsequent page reloads.

#### Version

VuePress 0.13.0

#### Steps to reproduce

1. Create a new commit 
2. Refresh the page to see the new content popup
3. Refresh the page again and the new content popup doesn't appear

#### What is expected?

The service worker update popup should appear as long as there is a new service worker available.

#### What is actually happening?

The service worker update popup appears on refresh with new content but doesn't appear again if you refresh without clicking the update button.

#### Other relevant information

Your OS: macOS High Sierra v10.13.6
Node.js version: v9.1.0
Browser version: Version 68.0.3440.75 (Official Build) (64-bit)
Is this a global or local install? Global
Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
https://github.com/yyx990803/register-service-worker/pull/8
