### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jrappen** [vuejs/vuepress#68]
Maybe it would be possible to **not** use Algolia document search, but a custom search built-in?

Compare:

<https://github.com/QingWei-Li/docsify>

Otherwise search wouldn’t work for a company Intranet.

**Comment by egoist** [comment]
> VuePress comes with built-in headers-based search - it automatically builds a simple search index from the title, h2 and h3 headers from all the pages.

https://vuepress.vuejs.org/guide/basic-config.html#config-file

**Comment by sinaa** [comment]
While I appreciate that vuepress has both options of "header-search" and "Algolia search for fulltext", I agree with the issue author that having also a built-in fulltext search would be an excellent addition (for example, MKDocs and Gitbook have this feature).

Internal/private documents would enormously benefit from this (and this would make Vuepress an excellent choice for such cases).

**Comment by jrappen** [comment]
@yyx990803 Would you consider re-opening this?

**Comment by jrappen** [comment]
> @ulivz wrote an explanation why it's currently not implemented here: https://github.com/vuejs/vuepress/issues/385#issuecomment-387929249
>
> Since all pages are loaded on demand, so full text search will make it meaningless.
>
> So we won't plan to implement it at default theme, but maybe it can be done by a plugin in the future (Maybe v1.0.0).

**Comment by ynnelson** [comment]
https://github.com/vuejs/vuepress/pull/1557 I added tags support and multi-word search, not the whole nine yard but a small improvement!
