### ISSUE TITLE
[Question] Using third party UI frameworks to develop custom vuepress theme

### ISSUE THREAD

**Issue by Sparkenstein** [vuejs/vuepress#681]
Hi, Thanks for the awesome project you guy created. I am developing a custom theme and I want to use UI frameworks like vuetify/element-ui to develop the theme. But I could not get the theme to load into my Layout. The official documentation provides info about how to use an existing `vuepress-theme-xxx` theme from your docs. but it does not say anything about how to use components from these third-party frameworks. Here is my directory structure:
* .vuepress
  * theme
    * Layout.vue
  * config.js
* node_modules
  * vuetify
* first
  * README.md
* second
  * README.md
* README.md
* package.json

And then I am trying to write some vuetify code in `Layout.vue` like:
```html
<v-card>
</v-card>
```
Thank you for your help.

**Comment by ulivz** [comment]
See: https://vuepress.vuejs.org/guide/custom-themes.html#content-outlet

**Comment by matjaeck** [comment]
To integrate `Vuetify`:

``` js
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
export default ({
  Vue, // the version of Vue being used in the VuePress app
  options, // the options for the root Vue instance
  router, // the router instance for the app
  siteData // site metadata
}) => {
  Vue.use(Vuetify);
}
```

See https://vuetifyjs.com/en/getting-started/quick-start#existing-applications

**Comment by NeroBlackstone** [comment]
> To integrate `Vuetify`:
> 
> ```js
> import Vuetify from 'vuetify'
> import 'vuetify/dist/vuetify.min.css'
> import 'material-design-icons-iconfont/dist/material-design-icons.css'
> export default ({
>   Vue, // the version of Vue being used in the VuePress app
>   options, // the options for the root Vue instance
>   router, // the router instance for the app
>   siteData // site metadata
> }) => {
>   Vue.use(Vuetify);
> }
> ```
> 
> See https://vuetifyjs.com/en/getting-started/quick-start#existing-applications

Hi, I want to insert Vuetify component to my Vuepress page.
Some components work as expected. Like **Card**.
But some component not. Like **time picker**.
[Here is what time picker look like in vuepress page](https://neroblackstone.asia/black-ops-zombies-story-discovery/zh/guide/bo4/voyage_of_despair/voyage_of_despair.html#%E6%8E%92%E6%B0%B4%E9%98%80)
[Here is time picker component .vue file](https://github.com/NeroBlackstone/black-ops-zombies-story-discovery/blob/master/docs/.vuepress/components/demo.vue)
[Here is enhanceApp.js file](https://github.com/NeroBlackstone/black-ops-zombies-story-discovery/blob/master/docs/.vuepress/enhanceApp.js)
Could you please help me? Thx!

**Comment by NeroBlackstone** [comment]
OK, I make it!
enhanceApp.js
`import Vuetify from "vuetify";
import 'vuetify/dist/vuetify.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'

export default ({
    Vue, // VuePress 正在使用的 Vue 构造函数
    options, // 附加到根实例的一些选项
    router, // 当前应用的路由实例
    siteData, // 站点元数据
})=>{
    Vue.use(Vuetify);
    options.vuetify=new Vuetify({})
}`

**Comment by leandro-costa** [comment]
@astronautchen 

try
```
<div class="v-application"> 
    <v-btn color="red"> test </v-btn>  
    <v-btn color="info"> test </v-btn>  
</div>
```
