### ISSUE TITLE
Base set - wont start vuepress dev

### ISSUE THREAD

**Issue by alexbainbridge** [vuejs/vuepress#685]
#### Version

13 (and checked 12, also the same problem)

#### Steps to reproduce

1) Have base set in config.js such as base: 'docs',

2) vuepress dev

3) Terminal remains stuck at "WAIT  Extracting site metadata..." 

#### What is expected?

Development version of vuepress starts

#### What is actually happening?

It does not start
Terminal remains stuck at "WAIT  Extracting site metadata..." 

#### Other relevant information

Yarn installed
Node 10.6.0

I can fix by
- Commenting out base entry (in config.js)
- Running vuepress dev
- Uncommenting base (in config.js)
- Vuepress notices the change, reruns, and all is OK from then on.

**Comment by ulivz** [comment]
You cannot set `base` to `'docs'`. ref: https://vuepress.vuejs.org/config/#base

> then base should be set to "/bar/". It should always start and end with a slash.

**Comment by alexbainbridge** [comment]
Thank you!
