### ISSUE TITLE
Vuepress & DocSearch

### ISSUE THREAD

**Issue by s-pace** [vuejs/vuepress#686]
👋 team,

I am [working on DocSearch ](https://community.algolia.com/docsearch/)that helps open source project with a good search experience for documentation website.

We used to feature vuepress since we are integrated in several vuepress users like:
- [vuejs](https://vuejs.org/)
- [craftcms](https://docs.craftcms.com/v3/)
...

We love vue and especially vuepress. We want to help you again by creating a dedicated integration for vuepress since we receive plenty of request about it.

We have made a quick showcase of how it would looks like:
https://docsearch-vuepress.netlify.com/
![preview](https://cl.ly/300y2D3H0r3r/download/Screen%20Recording%202018-07-30%20at%2003.46%20PM.gif)

Why DocSearch?

- Provide a learn as you type experience
- Powered [by algolia](https://www.algolia.com/doc/): Super fast. Results every keystroke. Typo tolerant ...
- We provide the full Algolia analytics so that you can inject user's usage in your documentation design (most queries done, most unsuccessful queries...) @FadySamirSadek has been granted since he was the first one to request DocSearch.

## Feature request

You will only need to inject a javascript snippet. I can do the PR for you since we want to **enhance the vuepress integration** by:
- Using meta tags from your page in order to handle version and language filtering
- Define the best DocSearch config for vuepress's users.
- Consider doing new feature like using a sitemap

#### What problem does this feature solve?

- Search within your documentation website

#### How should this be implemented in your opinion?
Ask us to do it for you.

#### Are you willing to work on this yourself?**

If you provide me a green light. I can work on enhancing the integration by generating meta tags for filtering on version & languages

**Comment by dagilleland** [comment]
As a VuePress user with a few open-source sites/projects that I would use VuePress and **Algolia** on, I would be willing to participate in testing.

**Comment by ulivz** [comment]
Thank you very much for your interest in VuePress, we strongly support you to enhance the docsearch experience. Let's go!

Refs: 

1. Current implementation: https://github.com/vuejs/vuepress/pull/201
2. Docs: https://vuepress.vuejs.org/default-theme-config/#algolia-search

**Comment by zipme** [comment]
It would be great if we can do more customizations, now it seems not possible to pass in functions like 

```js
themeConfig: {
  algolia: {
    handleSelected: function (input, event, suggestion) {
    }    
  }
}
``` 

https://community.algolia.com/docsearch/documentation/docsearch-autocomplete/configuring-the-search/

**Comment by s-pace** [comment]
Hi thank you for the help.

We will do it within this quarter.

So happy to receive these feedback.

**Comment by ulivz** [comment]
@s-pace 

Thanks for the official support, now VuePress's [documentation](https://vuepress.vuejs.org/) has enabled docsearch. You can see that we have handled language at our default theme: https://github.com/vuejs/vuepress/commit/e8a6ab1b09d6cb0e85333c9db39619a7e132865a because this filter `facetFilters: ['lang:$lang']` is generic for all docs built by VuePress.

And user will only need to config for `apiKey` and `indexName` as  before. https://github.com/vuejs/vuepress/commit/cba490461b40ff4f493215f733513920a4d965c2
