### ISSUE TITLE
Badge Component HTML displays in Page Title when used in H1

### ISSUE THREAD

**Issue by roberthamel** [vuejs/vuepress#688]
#### Version
0.13.0

#### Steps to reproduce
1. clone [this repository](https://github.com/roberthamel/vuepress-badge-issue)
2. run `vuepress dev`

#### What is expected?

Ideally, I would think that the following would occur: 
- the text `SAMPLE: Sample Page Title` would be parsed into the head title
- the text `SAMPLE: Sample Page Title` would be parsed into the sidebar

At the very least, the HTML should not display.

#### What is actually happening?

- The head title displays `<Badge text="SAMPLE"/> Sample Page Title`.
- The sidebar displays `<Badge text="SAMPLE"/> Sample Page Title`.

<img width="693" alt="screen shot 2018-07-31 at 11 06 44 am" src="https://user-images.githubusercontent.com/6254584/43469113-7724891c-94b3-11e8-877b-0b0ea7986651.png">

#### Other relevant information

I am aware that I can override the header using the following front matter:

```yml
---
title: Sample Page Title
---
```

But, I have a situation where I want to use the badge component to differentiate the page from others.

I am able to use regex to override the theme in order to fix the sidebar, but from what I can tell, the page head title is generated by the vuepress cli.

- Your OS: **MacOS**
- Node.js version: **10.7.0**
- Browser version: **Chrome 67**
- Is this a global or local install? **global** 
- Which package manager did you use for the install? **yarn**

**Comment by ulivz** [comment]
`<Badge/>` component can ONLY be used at the tail of the headers.

**Comment by roberthamel** [comment]
So this framework, which is meant to be customizable, can only be customized as long as you explicitly don't place a tag in a certain place? I don't appreciate the tone of your response, or your rush to close this issue. 

Even if I were to place the badge at the end of the header, [as per your documentation](https://vuepress.vuejs.org/guide/using-vue.html#badge), it would still display in the sidebar and in the title of the page if I used it in an h1 tag. 

It can be fixed so easily. You're basically putting me in a position to fork vuepress and make the change myself. Why?

**Comment by ulivz** [comment]
By default, the HTML in the header should be preserved, so for now we only remove the trailing HTML as the status identifier.

And for `" It can't be used on h1 "`, it's really a bug we didn't cover in development. We will fix it later.

In addition, since you said `It can be fixed so easily`, why not just giving a PR?

**Please also pay attention to your tone, I am not what you think, can the programmer be simpler?**

**Comment by ulivz** [comment]
I just checked:

```
# Introduction <Badge text="beta" type="warn"/>
```

![image](https://user-images.githubusercontent.com/23133919/43474802-6e796b02-9526-11e8-9065-15f248f4778e.png)

I hope you can create a valid repro instead.

**Comment by roberthamel** [comment]
Because this is a beta feature, I wanted to open an issue to make the maintainers aware of it. I was a little bit surprised that the issue was closed and dismissed so quickly. If the tone of my response was unpleasant, I apologize. I appreciate the work that you do, and any of the other maintainers involved in this project. All I ask is that you don't be so quick to dismiss in the future.

As to your point about me complaining, I have submitted a pull request to fix the problem with the meta title.

**Comment by ulivz** [comment]
@roberthamel 

See: https://github.com/vuejs/vuepress/pull/689#issuecomment-409662106

Could you close this issue and open a new feature request to support `support strip HTML from the left` ?


``` js
    expect(deeplyParseHeaders('# <Comp/> *H1* ')).toBe('# H1')
    expect(deeplyParseHeaders('# `<Comp/>` `H1`')).toBe('# <code><Comp></code> H1')
```

Thanks.
