### ISSUE TITLE
No custom css possible for homepage description color

### ISSUE THREAD

**Issue by bertdeterd** [vuejs/vuepress#691]
#### Version
0.13

#### Steps to reproduce
in styles.styl:
`.home.hero.description {
  color: green;
}`

or
`.description {
  color: green;
}`

#### What is expected?
Description text is green

#### What is actually happening?
Nothing

It seems something specific to the text color. 

`
.description {
  color: green;   <== not working
  background-color: red; <== works
}
`

#### Other relevant information

- Your OS: Windows
- Node.js version: latest
- Browser version: latest
- Is this a global or local install? global
- Which package manager did you use for the install? npm

**Comment by alexbainbridge** [comment]
```
.home .hero .description {
  color: green;
}
```
Note the spaces 

or with important...

`.description { color: green !important}`

Works?

I have been struggling with CSS also - but I think what you are doing should work, with a few adjustments https://github.com/vuejs/vuepress/issues/687

**Comment by bertdeterd** [comment]
Works perfect. Thx!!
