### ISSUE TITLE
Failed to resolve async component

### ISSUE THREAD

**Issue by u3u** [vuejs/vuepress#695]
#### Version

0.13.0

#### Steps to reproduce

1. Create symlinks with `npm link` or `yarn link`
2. Import modules in `.vuepress/components/example.vue`

#### What is expected?

Import modules correctly

#### What is actually happening?

[Vue warn]: Failed to resolve async component

#### Other relevant information

- Your OS: macOS High Sierra Version 10.13.6
- Node.js version: v9.11.1
- Browser version: Chrome/67.0.3396.99
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Could you provide a reproduction repo? That takes guessing work out of the way and saves us time.

**Comment by u3u** [comment]
Thank you for your reply, I solved it with `config.resolve.set('symlinks', false);`
