### ISSUE TITLE
Error with nuxt

### ISSUE THREAD

**Issue by iliyaZelenko** [vuejs/vuepress#704]
Hi, i'm using nuxt and getting [this error](https://stackoverflow.com/questions/51716353/nuxt-error-in-nuxt-client-js-this-setdynamic-is-not-a-function)
**vuepress v0.13.1**(latest), **nuxt v1.4.2**(latest)
You can check this error here: https://github.com/iliyaZelenko/laravel-nuxt(after installation add vuepress)

**Comment by ulivz** [comment]
Please follow issue reporting guidelines and provide a valid repro when opening an issue.
Note you can ask questions in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress) 🙂
