### ISSUE TITLE
build error when i use window object

### ISSUE THREAD

**Issue by webfansplz** [vuejs/vuepress#708]
components    a.vue 

```js 
const a = window;
```

Error: render function or template not defined   when i build

**Comment by ulivz** [comment]
See: https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions

---

Please follow issue reporting guidelines and provide a valid repro when opening an issue.
Note you can ask questions in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress) 🙂
