### ISSUE TITLE
w3.org now use https

### ISSUE THREAD

**Issue by djdeo** [vuejs/vuepress#709]
## Feature request

Change `http://www.w3.org/2000/svg` to `https://www.w3.org/2000/svg` in the root index.html page after build

#### What problem does this feature solve?
Google console Audits improvements

#### What does the proposed API look like?
`<svg xmlns="https://www.w3.org/2000/svg"...`

#### How should this be implemented in your opinion?
replace `http` with `https`

#### Are you willing to work on this yourself?**
I can replace them after build, but I don't know how to do it before run build

**Comment by ulivz** [comment]
Sorry but could you provide more context about why we must use `https` here?

**Comment by DiiLord** [comment]
Https is only needed for resources and links to prevent mixed-origin errors, but the svg namespace can stay at http without any issues. In fact https://w3.org/... is actually considered a wrong namespace by many, including es-lint.

So this feature is not necessary and could be harmful.

**Comment by ulivz** [comment]
Thanks, but it would be better to provide a spec as a reference to support what we said.

**Comment by djdeo** [comment]
Thanks @DiiLord,  for pointing this out, and @ulivz,  I just audit my https site in google console, the result says it's not secure to link to site with `http`, after I manually modified it to `https` on w3.org, I passed the audit, don't know if that make any sense on namespace, should I close this?

**Comment by ulivz** [comment]
Closing it since I cannot find any evidence to support us in making change. feel free to continue discussion if you have any new discoveries.
