### ISSUE TITLE
Expose a Vue constructor in entry potint

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vuepress#71]
Hope to expose a Vue constructor in entry point, so I can use it by `Vue.use('XXX')` to install third-party Vue plugin.

**Comment by egoist** [comment]
Here's a PR already https://github.com/vuejs/vuepress/pull/61

**Comment by wangyi7099** [comment]
oh!  Thanks!

**Comment by fjc0k** [comment]
#80
