### ISSUE TITLE
The web site displays overlapping problems in Apple Mobile Devices

### ISSUE THREAD

**Issue by swdwiki** [vuejs/vuepress#712]
#### What is expected?
This is my desired result.
![desired result](http://gonglue.swdwiki.com/1.jpg)
#### What is actually happening?
But after opening the website on Apple mobile devices, there is a problem of overlapping words.
![desired result](http://gonglue.swdwiki.com/2.jpg)
#### Other relevant information

- Your OS: 
- Node.js version: IOS
- Browser version: safari，chorme
- Is this a global or local install?  global
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Could you provide the IOS/Safari version?

**Comment by swdwiki** [comment]
IOS 9 and IOS10

**Comment by meteorlxy** [comment]
@swdwiki 

It will be better if you provide a reproduce repository.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
