### ISSUE TITLE
Can define  custom theme name or path at will?

### ISSUE THREAD

**Issue by axolo** [vuejs/vuepress#713]
## Feature request
theme in config.js

#### What problem does this feature solve?
theme files break away from node_modules!

#### What does the proposed API look like?
all ok

#### How should this be implemented in your opinion?
theme's value may be a path for import

#### Are you willing to work on this yourself?**
Evan, I need you :)

**Comment by ulivz** [comment]
Please provide a reproduction repo.

**Comment by axolo** [comment]
### theme
- Type: string
- Default: undefined
Specify this to use a custom theme. With the value of `"foo"`, VuePress will attempt to load the theme component at `node_modules/vuepress-theme-foo/Layout.vue`.

```vue
// .vuepress/config.js
module.exports = {
  theme: 'foo'    // Can point fullname file by user defined ?
}
```

e.g. `{ theme: foo }`  => `.vuepress\components\vuepress-theme-foo/Layout.vue`

`node_modules` is in `.gitignore` usually, it's out of control by git.

Sould I exce following command after theme updated every time?

```bash
cp -r .vuepress\components\vuepress-theme-foo node_modules
```

**Comment by meteorlxy** [comment]
@axolo 

Put your custom theme in `.vuepress/theme` if you don't need to extract the theme as an individual repository.

https://vuepress.vuejs.org/guide/custom-themes.html
