### ISSUE TITLE
文件夹是中文，导致生成侧边栏失败

### ISSUE THREAD

**Issue by MeetInInc** [vuejs/vuepress#717]
#### Version
v0.14.0 

#### Steps to reproduce
![snip20180809_7](https://user-images.githubusercontent.com/19743218/43908457-9c64e888-9c2a-11e8-8579-adf12c1627da.png)

![snip20180809_6](https://user-images.githubusercontent.com/19743218/43908282-23decaa0-9c2a-11e8-9bac-d9f2ce2f8be4.png)

下方是修复之后的 `resolveMatchingConfig` 方法
```javascript
export function resolveMatchingConfig (route, config) {
  if (Array.isArray(config)) {
    return {
      base: '/',
      config: config
    }
  }
  for (const base in config) {
    const encodeBase = encodeURI(base)
    if (ensureEndingSlash(route.path).indexOf(encodeBase) === 0) {
      return {
        base,
        config: config[base]
      }
    }
  }
  return {}
}
```

`route` 中的 `path` 是经过编码的
`config` 中的 `base` 没有编码
所以匹配不上，返回了空数组，也就是侧边栏为空了
加了一个 `encodeURI` 编码的逻辑就正常显示侧边栏了

**Comment by ulivz** [comment]
Thanks and contribution welcome!

**Comment by smile921** [comment]
'/docs/wiki/blog.wiki/vim配置',
if the page file name has some Chinese ，then the side render will fail 
 
![image](https://user-images.githubusercontent.com/1404755/44249875-81806d80-a224-11e8-9fad-409e72b6f624.png)
