### ISSUE TITLE
Access to markdown-it instance from theme

### ISSUE THREAD

**Issue by nkoehring** [vuejs/vuepress#721]
#### What problem does this feature solve?
To give theme developers more possibilities, it would be good to have access to the markdown-it instance before it rendered anything. This way lots of extensions would become possible like interactive code samples with live preview.

#### What does the proposed API look like?
The function exported by `enhanceApp.js` could be called with some object that gives direct access to the VuePress instance or at least the markdown-it one.

#### How should this be implemented in your opinion?
Unfortunately as far as I can tell the current way VuePress is written is that the theme initialization is happening after mardown-it initialization. This might have to be changed.

#### Are you willing to work on this yourself?**
I would have a look into this but I might just not find enough time at the moment.

**Comment by ulivz** [comment]
Now you can use [chainMarkdown](https://vuepress.vuejs.org/plugin/option-api.html#chainmarkdown).

Or, if you want to remove all built-in markdown-it plugins, you can use the Node.js API of [@vuepress/markdown](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/markdown)
