### ISSUE TITLE
Change temp directory

### ISSUE THREAD

**Issue by Johnhhorton** [vuejs/vuepress#723]
## Feature request
Enable users to change the location of the .temp directory for the build process. 

#### What problem does this feature solve?
I'm attempting to run VuePress within Google Cloud functions where the node_modules folder is readonly. Based on the errors I'm getting, it looks like VuePress is attempting to make use of a temp directory within node_modules, rather than in the src or dist locations.

#### What does the proposed API look like?
For the cli `vuepress build --dist .vuepress/dist --temp /tmp/vuepresstemp /tmp/client/`

Though an extra configuration option would be helpful as well.

#### Are you willing to work on this yourself?**
With some general direction, I'd be happy to make a PR.

**Comment by meteorlxy** [comment]
If this feature is approved, we can make some modification based on #354 to achieve it

**Comment by ycmjason** [comment]
I am just curious. Why not just use firebase hosting?

https://vuepress.vuejs.org/guide/deploy.html#google-firebase

**Comment by ycmjason** [comment]
👍 

I think it makes perfect sense to use an OS temp directory. Is there any reason why we haven't been using it?

Instead of `/tmp`, perhaps we can use [`os.tmpdir()`](https://nodejs.org/dist/latest-v8.x/docs/api/os.html#os_os_tmpdir).

**Comment by Johnhhorton** [comment]
To be clear about my intentions, I'm attempting to build in cloud functions pulling .md content from firestore as a weird sort of compiled CMS experiement. The compiled files can then either be pushed to hosting, or to storage with hosting rules to points to the files.

I was able to get it to work by: 

- copying `/srv/node_modules/vuepress` to `/tmp/alt_modules/vuepress`.
- Creating a symlink for `/tmp/node_modules` to `/srv/node_modules` //the real one
- Running build from `node /tmp/alt_modules/vuepress/bin/vuepress.js build /tmp/client`

This allowed me to use vuepress in a writable directory while still using the installed node packages (node will walk up directories until it finds a node_modules folder and use packages from there).

None of that would be necessary if we could explicitly control the temp directory for VuePress.
