### ISSUE TITLE
can't find parent node on reloading a page

### ISSUE THREAD

**Issue by dcsan** [vuejs/vuepress#725]
#### Version
^0.14.1

#### Steps to reproduce
I created a page that uses a component.
On first time viewing the page, the component works fine
but on ctrl-R reload the page the component is duplicated with this error:

![image](https://user-images.githubusercontent.com/514002/43992557-95491126-9db2-11e8-9336-c895c15eaeee.png)

![image](https://user-images.githubusercontent.com/514002/43992555-90ae8312-9db2-11e8-9866-3cb5d3fd60bc.png)

the public document is here:
https://crowdlingo.github.io/course/speaking/movies.html

source is also public

calling page
https://github.com/crowdlingo/course/blame/master/src/speaking/movies.md#L18
uses the component like this:
```
<banner imgPath='../images/movies.jpg'></banner>
```

and the component itself is here:
https://github.com/crowdlingo/course/blob/master/src/.vuepress/components/banner.vue

I had a heck of a time getting a component to get a dynamic path to an image, so ended up passing in the path from the parent to work.

anyway the component really doesn't do anything, just displays a nice box with an image and title.

#### What is expected?
The site should not crash if someone reloads a page.

#### What is actually happening?
Crash on reload the same URL

#### Other relevant information
For some reason a separate page that uses the **exact** same method to embed the same component, seems to work well without reload problems.
https://crowdlingo.github.io/course/speaking/free-time.html
maybe its cos they have different components on the page and something is cross-interfering?

Also the error doesn't happen in development mode, only against final published version.

- Your OS:  osx 10.13.6 (17G65)
- Node.js version: V10.1.0
- Browser version: latest chrome
- Is this a global or local install? global, deployed to github
- Which package manager did you use for the install? yarn and npm

**Comment by meteorlxy** [comment]
Get a lot of 404's in your public document. Seems like the `base` is wrong.

![image](https://user-images.githubusercontent.com/18205362/43993765-343269a6-9dc5-11e8-894a-e03b16593f62.png)

**Comment by ulivz** [comment]
@meteorlxy is right.

404: https://crowdlingo.github.io/static/course/assets/js/app.2d2a3838.js
200: https://crowdlingo.github.io/course/assets/js/app.2d2a3838.js

You [base](https://vuepress.vuejs.org/config/#base) are set to `/static/course/`, just change it to`/course/`.

Ref: [Deploy > Github Pages](https://vuepress.vuejs.org/guide/deploy.html#github-pages)

**BTW, If you want to be more professional, please read documentation before using any product.**
