### ISSUE TITLE
Define custom component directory and import custom components

### ISSUE THREAD

**Issue by olavoasantos** [vuejs/vuepress#729]
## Feature request

Allow developers to use the `config.js` file to customize the components folder and to import components with custom names.

#### What problem does this feature solve?
Currently, VuePress looks for a `components` folder inside the `.vuepress` folder. If we are aiming to integrate VuePress into an existing project (or use it to document a custom component package), this would drive us to move or copy existing components to this folder. This results in either verbosity (as we would have to import from `./path/to/.vuepress/components`) or duplication.

Moreover, the current implementation does not allow us to import custom components with a custom name tag, relying solely on the folder structure of the component (e.g. `<Path-To-Custom-Component></Path-To-Custom-Component>`.

#### What does the proposed API look like?

- Custom component directory:

![carbon 25](https://user-images.githubusercontent.com/10423749/43995416-d4282226-9d83-11e8-9943-ffcd5cd585e6.png)

- Custom component import:

![carbon 24](https://user-images.githubusercontent.com/10423749/43995421-dda64792-9d83-11e8-9dc2-5d17e4b87d52.png)

#### How should this be implemented in your opinion?
First, modifying the `resolveOptions.js` to accept two new options (`components` and `componentsDir`). Then, modifying the `genImport` function in the `codegen.js ` to accept these options and generate the imports based on their values.

#### Are you willing to work on this yourself?**
Yes. [#730](https://github.com/vuejs/vuepress/pull/730)

**Comment by ulivz** [comment]
https://github.com/vuejs/vuepress/pull/730#issuecomment-412297364

**Comment by ulivz** [comment]
docs of WIP plugin [@vuepress/plugin-register-components](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-register-components).
