### ISSUE TITLE
Config the dev and build html template.

### ISSUE THREAD

**Issue by Akimyou** [vuejs/vuepress#733]
#### What problem does this feature solve?

Use a customized dev and build html template（inline some scripts, meta ...）.
It will be more freedom.

#### What does the proposed API look like?

none

#### How should this be implemented in your opinion?

It is a simple way to use customized build html template, but have to change the vuepress source code.

```js
template: process.env.SERVER_RENDER_TPL || await fs.readFile(path.resolve(__dirname, 'app/index.ssr.html'), 'utf-8')
```
In this way can use customized dev html template, just change config but not well.

```js
  configureWebpack (config, isServer) {
    for (let i = 0; i < config.plugins.length; i++) {
      const plugin = config.plugins[i]
      if (plugin instanceof HtmlWebpackPlugin) {
        plugin.options.template = devIndexTplPath
      }
    }
  }
```

May be need a normal config option like this.

```js
config.devTemplate = devTemplatePath
config.buildTemplate = buildTemplatePath
```

Thanks.

#### Are you willing to work on this yourself?**

none

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, but we don't plan to add extra config for this feature because most of users almost don't need this feature, and we need to keep the simplicity of the core.

**Comment by timberkeley** [comment]
This would be very useful to me as I am attempting to use vuepress to generate golang templates to integrate static content into a larger web application. I am sure there are many other scenarios where the wrapping html would need to be altered.
