### ISSUE TITLE
Deploy to Azure Storage Static Website Hosting

### ISSUE THREAD

**Issue by sirfarmalot** [vuejs/vuepress#734]
Can vuepress be deployed to Azure Storage's new Static Website hosting?

**Comment by ulivz** [comment]
The built files can be deployed to any static file server, and all static hosting services work basically the same way. I don't use `Azure Storage's new Static Website hosting`, and I recommend you to read the docs first. 🙂 

--- 

Please follow issue reporting guidelines. this is a question and should be asked in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress).
