### ISSUE TITLE
Is it possible to programatically render the same markdown as `<<<` from a Vue component?

### ISSUE THREAD

**Issue by davestewart** [vuejs/vuepress#735]
I ask as I'm loading in a file raw from a component in a theme...

```js
const data = require('!raw-loader!./' + this.file + '.vue')
return md.renderInline('```vue\n\n' +data+ '\n```')
```

...but I want to just use the VuePress Markdown setup, which looks great.

Unfortunately, my attempt looks like the top half below.

How do I make it look like the result of `<<< path/to/file.vue` (the bottom half, below)?

![image](https://user-images.githubusercontent.com/132681/44125075-8ceb8a36-a028-11e8-96d1-26ad2bbefd82.png)

**Comment by f3ltron** [comment]
i trying to find the solution too here... 

i do the same here with look at bot for code. i call it as component in the readme.md

When i am not importing prism it doesnt do his compilation normal so i have something like just reproduce my initial html code.

But when i import the prism it work but it work in one line no more multiple lines.....

And other old markdown are not anymore compile too...

I am so miss for now

```
<template>
    <div class="blockCode code-toolbar">
    <div class="hideMe">
        <slot></slot>
    </div>
        <div class="extra-class" :class="`language-${lang}`">
            <button @click="code = !code" class="w3-btn w3-primary w3-text-white">
                <span v-if="code"> preview</span>
                <span v-else> code</span>
            </button>
            <pre v-if="!code" v-html="content" class="w3-text-white"></pre>
            <pre v-else class="line-numbers" :class="`language-${lang}`">
                <code v-html="contentPreview">
                </code>
            </pre>
        </div>
    </div>
</template>


<style lang="scss">
    @import '../../../src/scss/main';
    // pre {
    //     white-space: pre-line !important;
    // }
    code {
        text-shadow: none !important;
    }
    .hideMe {
        display: none;
    }
</style>


<script>

import prism from "prismjs";

export default {
    props: {
        lang: {
            default: "",
            type: String
        }
    },
    data:() => ({
        content: "",
        contentPreview: "",
        code: false
    }),
    mounted() {
        this.$nextTick(() => {
            this.content = this.$el.querySelector(".hideMe").innerHTML;
            this.code = this.$el.querySelector(".codeMe");
            if (this.lang == 'html') {
                this.contentPreview = prism.highlight(this.content, prism.languages.html, 'html');
            } else if (this.lang == 'scss') {
                this.contentPreview = prism.highlight(this.content, prism.languages.scss, 'scss');
            }
        })
    }
}
</script>

```

**Comment by f3ltron** [comment]
@davestewart your bug is normal because u trying to use a process.env that is node relevant and no client side so yeah not possible

**Comment by ulivz** [comment]
It seems that you want to highlight the code generated by your raw-loader query. but it's a good idea in VuePress - since our direction is to build everything at build time as much as possible.

I suggest that you write a VuePress for your request of highlight code at runtime as #676, or waiting for our new code snippet API (#1336)
