### ISSUE TITLE
[Feature Request] Progressive-image-loading

### ISSUE THREAD

**Issue by DanteZii** [vuejs/vuepress#737]
[Feature Request] Progressive-image

How  does progressive image loading? 

like Medium and zhihu

**Comment by ekoeryanto** [comment]
Progressive and responsive image

**Comment by Sorix** [comment]
Something like [Gridsome](https://gridsome.org/docs/images) and 
[gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/?=#gatsby-image) do.

**Comment by ulivz** [comment]
Try 1.x and [@vuepress/plugin-medium-zoom](https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html).

**Comment by Sorix** [comment]
> Try 1.x and [@vuepress/plugin-medium-zoom](https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html).

That plugin doesn't support progressive image loading what was asked in that thread (as far as I understood). Progressive image loading = load image only when it is displayed to user + (optional) load light blurred version while full image is loading.

**Comment by ekoeryanto** [comment]
@Sorix You can create a little hack like this
https://github.com/apekarawang/apek/blob/production/docs/.vuepress/markdown/v-img.js

**Comment by ngocbnv-0940** [comment]
@ulivz please make vuepress support this feature :+1:

**Comment by ulivz** [comment]
@ngocbnv-0940 You can create a plugin 🙂
