### ISSUE TITLE
Algolia search results limit

### ISSUE THREAD

**Issue by grayfella** [vuejs/vuepress#738]
Is it possible to make the limit for the Algolia search dropdown to be bigger than 5?
I've searched API docs and the code and can't find how to alter this.
Thanks.

**Comment by ulivz** [comment]
This shouldn't be handled by VuePress, and you should go to [docsearch](https://github.com/algolia/docsearch) to investigate.

I have helped your to do the investigation but cannot find what you want.

---

BTW, Can't you see this?

## Please don't delete this template or we'll close your issue.

Besides, I hope I am the last to emphasize, please don't use issue to ask question! A question should be asked in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress)
