### ISSUE TITLE
Vuepress project can't run correctly

### ISSUE THREAD

**Issue by sky790312** [vuejs/vuepress#739]
Some of my team member can't run the vuepress project correctly. When they run vuepress dev they face the following warning:

WARNING in ./.vuepress/theme/Layout.vue?vue&type=script&lang=js (/Users/kevin.hu/.config/yarn/global/node_modules/cache-loader/dist/cjs.js??ref--3-0!/Users/kevin.hu/.config/yarn/global/node_modules/babel-loader/lib??ref--3-1!/Users/kevin.hu/.config/yarn/global/node_modules/vue-loader/lib??vue-loader-options!./.vuepress/theme/Layout.vue?vue&type=script&lang=js) 103:50-69
"export 'pathToComponentName' was not found in '@app/util'
 @ ./.vuepress/theme/Layout.vue?vue&type=script&lang=js
 @ ./.vuepress/theme/Layout.vue
 @ /Users/kevin.hu/.config/yarn/global/node_modules/vuepress/lib/app/.temp/routes.js
 @ /Users/kevin.hu/.config/yarn/global/node_modules/vuepress/lib/app/app.js
 @ /Users/kevin.hu/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js
 @ multi /Users/kevin.hu/.config/yarn/global/node_modules/vuepress/lib/app/clientEntry.js

It can run but can't change the route. No matter using npm or yarn to reinstall, it still facing the same problem. Any idea?

"export 'pathToComponentName' was not found in '@app/util'

nodejs version: v8.11.3

yarn version: v1.7.0

npm version: 5.6.0

vuepress version: 0.10.1

**Comment by ulivz** [comment]
Let me repeat the words from issue template:

> If you are reporting a bug that can ONLY be reproduced on your repository, PLEASE provide this repo link. That takes guessing work out of the way and saves us time. 

> If your repo isn't public, you can use this boilerplate to create a proper reproduction repo quickly: https://github.com/ulivz/template-vuepress

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
