### ISSUE TITLE
a vuepress forum for community support

### ISSUE THREAD

**Issue by dkebler** [vuejs/vuepress#745]
I'd hate to pollute your github issue tracker with usage questions etc.   Given the popularity of this project and the fact it's actively maintained I'd suggest you either add a category to the [vue forum](https://forum.vuejs.org/) given that vuepress appears to be part of the vuejs project or start a separate forum.  At the least in the readme and guide link folks to the vuejs forum for getting help if that is ok.   I have several questions and need some input but using the issue tracker for that seems wrong.

Side benefit is that you can vet bugs, issues and other requests in the forum before having someone make an issue here that you want to really pursue.  63 open issues looks bad in an otherwise really promising project.   Given that when you read this feel free to close it :-).

**Comment by apekarawang** [comment]
quick suggestion https://cmty.app

**Comment by ulivz** [comment]
Let me clarify something here.

> 63 open issues looks bad in an otherwise really promising project.

Our principle is to fix bug first, at the same time, we will not arbitrarily accumulate code.

The current open issues are almost all feature requests, or feature requests that should be completed by plugins. and for now we are working for next big version. so once the next version is released, most of the issues will be closed.

---

The forum category isn't set separately for each project, feel free to ask questions and I can find it out. 🙂 

- https://forum.vuejs.org/search?q=vuepress
- https://stackoverflow.com/tags/vuepress

**Comment by ulivz** [comment]
I am currently stationed in VueLand's #vuepress channel, please feel free to ask questions.

![image](https://user-images.githubusercontent.com/23133919/44396146-a2232d00-a56e-11e8-8e11-be9bc3eba5bd.png)
