### ISSUE TITLE
Dev mode doesn't detect changes on Virtualbox (Win7x64)

### ISSUE THREAD

**Issue by Danita** [vuejs/vuepress#747]
## Bug report

With vuepress installed on a Virtualbox machine, the dev server doesn't detect changed files on the fly. My VirtualBox machine (provided by a Vagrant file) is set up as follows:

* Ubuntu Xenial
* ip: 192.168.10.10
* ports forwarded: 8080, 8081
* vuepress installed in shared folder

Host machine: 

* Windows 7 x64
* ip: 192.168.1.106
* accessing vuepress dev using chrome at http://192.168.10.10:8080/

My vuepress config:

```js
module.exports = {
	host: '192.168.10.10',
	title: 'Hello VuePress',
	description: 'Just playing around',
	configureWebpack: {
		devServer: {
			watchOptions: {
				poll: 1000
			}
		}
	}
};
```

Vuepress runs perfectly, compiles and I can see the generated site. The socket seems to connect just fine. But changes on the host local files (which are shared with the vm) don't get detected by vuepress dev server. As you can see I tried to modify the Webpack config as I did with other non-vuepress projects with the same problem, but it doesn't work.

I was looking at the vuepress source and trying to find the string `devServer` but it seems you use a customary solution.

I'm aware that I probably could try not to use a VirtualBox shared folder and instead set up a host -> guest file syncronization via the IDE, but I wanted to keep things simple.

Any ideas?

#### Version

0.14.2

#### Steps to reproduce

1. Create a virtualbox VM as described and set up a shared directory.
2. Set up vuepress [as per the docs](https://vuepress.vuejs.org/guide/getting-started.html#inside-an-existing-project) on the VM in the shared directory, using the provided config.
3. On the VM execute `yarn run docs:dev`
4. Access the devserver on `http://192.168.10.10:8080/`
5. Modify some `.md` files or custom components

#### What is expected?

That the changes are detected and rerendered.

#### What is actually happening?

That the changes don't get detected and there is no rerender.

#### Other relevant information

- Your OS: Windows 7x64
- Node.js version: 8.11.4
- Browser version: Chrome 68.0
- Is this a global or local install? Local install
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
VuePress is based on [webpack-serve](https://github.com/webpack-contrib/webpack-serve) and [chokidar](https://github.com/paulmillr/chokidar).

- webpack-serve: Create a webpack dev server.
- chokidar: detect the change of config file.

I don't use VuePress on Virtualbox or on win7, excuse me but I cannot help you. I think you can go these two repos to find more information.

**Comment by Danita** [comment]
So the answer is basically, "Works on my machine, figure out yourself"?

**Comment by PeppeL-G** [comment]
This is probably relevant:

https://stackoverflow.com/a/39239884/2104665

The same problem exists for [nodemon](https://github.com/remy/nodemon), and the problem seems to be that although VirtualBox syncs the files, it does not emit the correct file changed events the applications are listening for (I don't know the details, but I imagine that's how it works). The workaround nodemon uses (their "legacy" mode) is to read the files with a small intervall and see if they have changed, and if so restart.
