### ISSUE TITLE
Failed to build with unexpected token @import

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#753]
#### Version
__0.14.2__
#### Steps to reproduce
running `dev` works but not with build
repo: https://github.com/ekoeryanto/vuepressify

#### What is expected?
built
#### What is actually happening?
error
`
Error rendering /:
D:\Repository\vuepressify\node_modules\vuetify\src\stylus\components\_app.styl:1
(function (exports, require, module, __filename, __dirname) { @import '../bootstrap'
`
#### Other relevant information
Set up with ala carte method of vuetify
- Your OS: 
Windows 10
- Node.js version: 
v8.11.3
- Browser version: 
- Is this a global or local install? 
tried both
- Which package manager did you use for the install?
npm

**Comment by ekoeryanto** [comment]
this is weird, I fix this by changing path to vuetify with absolute path.
looks like  `enhanceApp.js` does not resolve `node_modules`

**Comment by ekoeryanto** [comment]
after read deep the source, and vue-style-loader only loaded on NODE_ENV=production
I fixed this with set the NODE_ENV to production.

Feel free to close.

**Comment by Deraw-** [comment]
@ekoeryanto Hi! I'm facing the same issue, I'm not sure how you finally resolved it :thinking:

**Comment by Deraw-** [comment]
Okay so importing the files in the Layout.vue solves this:
```html
<style lang="stylus">
	@require '~vuetify/src/stylus/main'

	@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons')
</style>
```
Maybe you can close this issue now? :slightly_smiling_face:
