### ISSUE TITLE
Help with Postcss

### ISSUE THREAD

**Issue by nil** [vuejs/vuepress#757]
I don't know how to setup Postcss with Vuepress. The docs are extremely vague in this aspect and nothing seems to work.

I included this in the config.js:

```
postcss: {
  plugins: [
    require("postcss-color-mix")
  ]
}
```

but the none of the CSS files are parsed.

Creating a postcss.config.js file, equal to the one that appears in the postcss-loader documentation, doesn't work either.

**Comment by ulivz** [comment]
Please follow issue reporting guidelines. You can ask questions on the [Discord server](https://vue-land.js.org/), the [forum](https://forum.vuejs.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress). If it turns out to be a bug, come back and open an issue with a proper repro. 🙂
