### ISSUE TITLE
Add webpackServer config.

### ISSUE THREAD

**Issue by LinFeng1997** [vuejs/vuepress#758]
#### What problem does this feature solve?
custom dev server koa config.

#### What does the proposed API look like?
In .vuepress/config.js:
```
module.exports = {
  webpackServer: (app, middleware, options) => {
    app.use(xxx)
  }
}
```
#### How should this be implemented in your opinion?
In lib/dev.js,add code:

```
// ... other code
app.use(convert(history({
        rewrites: [
          { from: /\.html$/, to: '/' }
        ]
})))

if (options.siteConfig.webpackServer) {
    options.siteConfig.webpackServer(app, middleware, options)
}
```

#### Are you willing to work on this yourself?**
Yes!

**Comment by ulivz** [comment]
Thanks, but it has been included in the [next](https://github.com/vuejs/vuepress/tree/next) version.

**Comment by LinFeng1997** [comment]
@ulivz Thanks，I am very much looking forward to the release of the next version.
