### ISSUE TITLE
Repo not deploying despite seemingly correct config

### ISSUE THREAD

**Issue by raybesiga** [vuejs/vuepress#760]
## Bug report

Hey guys,

I have setup Vuepress for a documentation site and it runs fine locally. Repo can be seen here:

https://github.com/sparkplug/mtn-momo-api-documentation

However, my deploy script does not run as expected. Is there something I am doing wrong in the config or deploy?

Appreciate all the help 

#### Steps to reproduce

Repo:
https://github.com/sparkplug/mtn-momo-api-documentation

#### What is expected?

It is expected that the repo would be deployed and viewed on https://sparkplug.github.io/mtn-momo-api-documentation/

#### What is actually happening?

Gives a `404` page

#### Other relevant information

- Your OS: Mac OS
- Node.js version: v8.9.1
- Browser version: Google Chrome
- Is this a global or local install? Vuepress installed locally but also globally
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
Resume you `baes` to `/mtn-momo-api-documentation/`.
