### ISSUE TITLE
build will fail if double curly braces are present in single back tick code block

### ISSUE THREAD

**Issue by jbibla** [vuejs/vuepress#767]
#### Version
0.14.2

#### Steps to reproduce

1. Put double curly's inside of a single back tick codeblock in a markdown file
```
`i am going to {{ break the build }} process`
```
2. Run `vuepress build docs`

#### What is expected?

The build should succeed.

#### What is actually happening?

The build fails.

```
Error: Failed to compile with errors.
```

#### Other relevant information

- Your OS: high sierra 10.13.6
- Node.js version: v9.11.0
- Browser version: n/a
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by greg-szabo** [comment]
Did anyone check this out? This makes it hard to talk about Jinja or Go templates in a markdown file without breaking docs builds.

**Comment by zramsay** [comment]
this bug can sneak into docs without failing a build and has this error message:
`SyntaxError: Unexpected token` without telling us where this unepxected token is

**Comment by ulivz** [comment]
https://vuepress.vuejs.org/guide/using-vue.html#escaping
