### ISSUE TITLE
`vuepress dev` -h option conflict

### ISSUE THREAD

**Issue by ZYSzys** [vuejs/vuepress#770]
## Bug report
Not a bug seriously ?
When `vuepress dev -h`, it seems the `-h`(host) option has little conflict with the `-h`(help)

#### Version
0.14.2
#### Steps to reproduce
![screen shot 2018-08-26 at 8 34 22 pm](https://user-images.githubusercontent.com/23313266/44628904-45af7b80-a97b-11e8-8ac2-08b97e7ea7c6.png)

#### What is expected?
The `-h` option when running `vuepress dev -h` has a specific meaning.
#### What is actually happening?
`-h` option vague in help page
#### Other relevant information

- Your OS: macOS X 10.13.3
- Node.js version: v10.8.0
- Browser version: Safari Version 11.0.3 
- Is this a global or local install? global
- Which package manager did you use for the install? npm

**Comment by gumpcha** [comment]
Looks like it is `commander` issue and not merged yet.

https://github.com/tj/commander.js/pull/658

**Comment by ZYSzys** [comment]
Yeah, think you are right @gumpcha 👍

**Comment by ulivz** [comment]
We have migrated to [CAC](https://github.com/cacjs/cac) and this issue have been fixed.
