### ISSUE TITLE
external script support

### ISSUE THREAD

**Issue by apekarawang** [vuejs/vuepress#774]
#### What problem does this feature solve?
easy integration of google adsense, recaptcha, etc.

#### What does the proposed API look like?
```js
// global scripts
// currently only available on `head`
{
scripts: [
    {
      src: 'https://www.google.com/recaptcha/api.js?render=...',
      defer: true,
      async: true,
      pos: 'before'
    }
  ]
},
// per page scripts
nav: [
  {
    text: "Home",
    link: "/", 
    scripts: [
      {
        src: 'https://www.google.com/recaptcha/api.js?render=...',
        defer: true,
        async: true,
        pos: 'before'
      }
    ]
  },
]
```
#### Are you willing to work on this yourself?**
yes

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, but:

1. For `global scripts`, we can use `enhanceApp.js` and some script loading lib (e.g [loadjs](https://github.com/muicss/loadjs)) to implement it at userland. you can even inject it at the dev or prod template when we support https://github.com/vuejs/vuepress/issues/733

2. For `per page scripts`, the API you recommended is such complicated, why coupling it with nav config? The simplest way should be monitoring `$route` changes, and then loading the scripts that you want.
