### ISSUE TITLE
meta data is doubled/tripled at runtime

### ISSUE THREAD

**Issue by codeofsumit** [vuejs/vuepress#777]
Might be related to the closed issue https://github.com/vuejs/vuepress/issues/665.

It was fixed for the `description` tag - the issue seems to persist for other meta tags:

```js
// config.js
  head: [
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:site', content: '@TweetsOfSumit' }],
    ['meta', { name: 'twitter:creator', content: '@TweetsOfSumit' }],
    ['meta', { property: 'og:type', content: 'article' }],
    ['meta', { property: 'og:title', content: 'Raum.sh' }],
    ['meta', { property: 'og:site_name', content: 'Raum.sh' }],
    ['meta', { property: 'og:url', content: 'https://raum.sh' }],
    [
      'meta',
      {
        property: 'og:image',
        content: 'https://raumsh-idpjzzfqhw.now.sh/images/speaking.jpg',
      },
    ],
  ],
```

``` md
---
# Markdown Front Matter
layout: Post
published: 2018-08-07
title: Blog is online 🙋‍♂️
meta:
  - property: og:title
    content: Blog is online 🙋‍♂️
  - name: description
    content: I finally decided to use VuePress as a blog engine.
  - name: keywords
    content: Web Developer Developer Relations Development Blog
---
```
(yup, social meta tags are a bit of a chaos but that's a different issue)

Output:
```html
  <title>Blog is online 🙋‍♂️ | Raum.sh</title>
  <meta name="description" content="I finally decided to use VuePress as a blog engine.">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@TweetsOfSumit">
  <meta name="twitter:creator" content="@TweetsOfSumit">
  <meta property="og:type" content="article">
  <meta property="og:title" content="Raum.sh">
  <meta property="og:site_name" content="Raum.sh">
  <meta property="og:url" content="https://raum.sh">
  <meta property="og:image" content="https://raumsh-idpjzzfqhw.now.sh/images/speaking.jpg">
  <meta name="title" content="Blog is online 🙋‍♂️">
  <meta property="og:title" content="Blog is online 🙋‍♂️">
  <meta name="keywords" content="Web Developer Developer Relations Development Blog">
```

Demo:
https://raum.sh/blog/BlogLaunch.html

Here, the meta tag `og:title` is present three times.

**Comment by lorisleiva** [comment]
👋 Same problem here. I've created [an issue on my vuepress seo plugin](https://github.com/lorisleiva/vuepress-plugin-seo/issues/1) that demonstrates this duplication.

<img width="559" alt="screenshot 2019-02-02 at 11 21 42" src="https://user-images.githubusercontent.com/3642397/52163660-0250fa00-26dd-11e9-8ea7-a3d1a3706cef.png">

In production, the bottom batch of meta tags are updated when we switch pages but the top batch stays static and matches the page that we originally loaded.

I am using `vuepress@1.0.0-alpha.32`. I hope this helps.

**Comment by samanthaming** [comment]
I'm having the same problem too @lorisleiva 😣. I'm setting the metadata in my own custom plugin, programmatically setting the frontmatter object. Hope this get resolved 🤞
