### ISSUE TITLE
un-user-friendly PWA notification push automatically on Android phone (not sure on Apple device)

### ISSUE THREAD

**Issue by meRyanWu** [vuejs/vuepress#781]
## Bug report

The site built with Service Worker always showing the meaningless notification **everytime you open the PWA directly from your Android desktop**. And you cannot swipe it off, that's a bit of annoying.

I'm not sure the situation above is same on the Apple device because I only have one Android device.

This is the VuePress official doc site

![image](https://user-images.githubusercontent.com/17338101/44776805-84c41380-abab-11e8-980c-ef79b6845c2f.png)

Same as my blog

![image](https://user-images.githubusercontent.com/17338101/44777454-429bd180-abad-11e8-8c6c-786afc33d915.png)

#### Version
VuePress 0.14.2
#### Steps to reproduce
add VuePress PWA on your Android device desktop, and open it

#### What is expected?
don't show this meaningless notification

#### What is actually happening?
always showing everytime you opened it directly from your Android desktop

#### Other relevant information

- Your OS: Android 8.0.0 with MIUI 10
- Node.js version: 9.5.0
- Browser version: Chrome 68 Android
- Is this a global or local install? local
- Which package manager did you use for the install? NPM

**Comment by ulivz** [comment]
Oh, I also have a MIUI device but I cannot repro that, could anyone else encounter that?

**Comment by LinusBorg** [comment]
I get that on my Samsung S8 as well, but I think it's a feature. I get it for different PWA apps, not just Vuepress.

**Comment by ulivz** [comment]
Thanks @LinusBorg for the explanation, let's close it.
