### ISSUE TITLE
Sidebar should update in sub-folders

### ISSUE THREAD

**Issue by tristan957** [vuejs/vuepress#785]
## Feature request

Say I have a structure like this:
![image](https://user-images.githubusercontent.com/11936772/44881012-d506a880-ac73-11e8-923f-5498859f6837.png)

and my `config.js` file looks like:
```js
module.exports = {
    themeConfig: {
        nav: [
            { text: "Home", link: "/"},
            { text: "Projects", link: "/"},
            { text: "Wiki", link: "/wiki/"}
        ],
        sidebar: {
            "/wiki/": [
                "",
                "vscode/",
            ],
            "/wiki/vscode/": [
                "",
                "extensions/",
                "go/"
            ],
            "/wiki/vscode/extensions/": [
                "",
                "python",
                "c-cpp"
            ],
            "/wiki/vscode/go/": [
                "",
                "debugging"
            ]
        }
    }
}
```

I only get to see the sidebar of the `/wiki/` directory. When I am in the `/vscode/` directory, I want to see the sidebar I defined. Unfortunately all the sidebars under `/wiki/` are the same `/wiki/` sidebar. The sidebar should be updated on every sub-folder

#### What problem does this feature solve?

Allows for sub-folders to have unique sidebars

#### What does the proposed API look like?

Nothing would have to change about `config.js`, although it might help to allow for nesting like

```js
sidebar: {
    '/wiki/': [
        '',
        'vscode/': [
            '',
            'go/' //,
            // ...
        }
    }
}
```

#### How should this be implemented in your opinion?

Similarly to how it is already implemented

#### Are you willing to work on this yourself?**

I would be willing if I knew where to look.

**Comment by hello-sunbaixin** [comment]
https://github.com/vuejs/vuepress/pull/669 ，you can see see

**Comment by aaroncaito** [comment]
try this
```
module.exports = {
    themeConfig: {
        nav: [
            { text: "Home", link: "/"},
            { text: "Projects", link: "/"},
            { text: "Wiki", link: "/wiki/"}
        ],
        sidebar: {
            "/wiki/vscode/": [
                "",
                "extensions/",
                "go/"
            ],
            "/wiki/vscode/extensions/": [
                "",
                "python",
                "c-cpp"
            ],
            "/wiki/vscode/go/": [
                "",
                "debugging"
            ],
            "/wiki/": [
                "",
                "vscode/",
            ]
        }
    }
}
```

**Comment by kaidesu** [comment]
☝️ @aaroncaito's solution will work. It's dependent on the order in which you register your navigation items. Reverse it so your global items come last so they're not picked up first.

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
