### ISSUE TITLE
valine comment system    comments data dosen't update

### ISSUE THREAD

**Issue by GongJS** [vuejs/vuepress#793]
#### Other relevant information

- Your OS: mac
- Node.js version: 8.0.0
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?
i clone the code from the `https://github.com/vuejs/vuepress`, and then i 
use the valine comment system in my Vuepress, i package it as a component and add it into the Layout.vue. Now, i have a problem, when i jump to the `/guide/deploy.html` page, the comments'data is not updated, it is still like the `/guide/` page's comments data , unless i refresh the page; so i check the network, i  find when the comments make a request its url params is not updated everytime,such like:

`where: {"$or":[{"rid":{"$exists":false}},{"rid":""}],"url":"/guide/"}
order: -createdAt,-insertedAt
limit: 0
count: 1`
the `/'guide'/` is the same as the introduction page's link, so how can i update it when i jump to the different page?

my repro is [test_vuepress](https://github.com/GongJS/test_vuepress)

**Comment by ulivz** [comment]
I truly read your description carefully but I cannot get what it is. and we DON'T leave time to see the feature of a fork, because it's your issue.

If you want to get `comment` support, I think you can open a feature request instead.

**Comment by GongJS** [comment]
ok,thank you
