### ISSUE TITLE
Is there a way to configure the sidebar path concisely, rather than enumerating them all？？

### ISSUE THREAD

**Issue by hello-sunbaixin** [vuejs/vuepress#795]
<img width="887" alt="11" src="https://user-images.githubusercontent.com/18138020/45030523-b1ca6780-b07e-11e8-96a1-25314276eba2.png">
How to write less code and be more concise？？

**Comment by ulivz** [comment]
I guess you didn't read the document carefully, you can leave out the '/posts/design' for each child.
