### ISSUE TITLE
`vuepress dev` failed with babel error `programPath.hub.addHelper is not a function`

### ISSUE THREAD

**Issue by Mactaivsh** [vuejs/vuepress#797]
## Bug report

I got a local repo, using `webpack 4` and latest `babel 7` for develoment

And I want to use `vuepress` for documentation

Then I run ` vuepress dev docs`, failed with build errors

``` sh
ERROR in ./node_modules/vuepress/lib/app/clientEntry.js
Module build failed (from ./node_modules/vuepress/node_modules/babel-loader/lib/index.js):
TypeError: programPath.hub.addHelper is not a function
```

#### Version

Latest version: 0.14.2

#### Steps to reproduce

check this [repo](https://github.com/Mactaivsh/vuepress-bug-reproduction) for reproduction

#### What is expected?

fix this weird behaviour

#### What is actually happening?

I found that if I remove my `babel.config.js` in the root dir, the build will go green again

#### Other relevant information

https://github.com/babel/babel/issues/8508

- Your OS:  Mac OS High Sierra (10.13.6)
- Node.js version:  **v8.11.4**
- Browser version: **latest chrome**
- Is this a global or local install?  **local**
- Which package manager did you use for the install? **yarn**

**Comment by zealot09** [comment]
http://babeljs.io/docs/en/config-files

createBaseConfig.js

```
configFile: false,
```

**Comment by ulivz** [comment]
Release at 0.14.3
