### ISSUE TITLE
Self hosted search

### ISSUE THREAD

**Issue by trajano** [vuejs/vuepress#799]
## Feature request

According to https://vuepress.vuejs.org/default-theme-config/#search-box there are only two ways of searching one is the built-in one but does not have a full text search and another is Algolia which is hosted.

I am looking for a self hosted one.  Free ideally.

#### What problem does this feature solve?

$$$ for private documents.

#### What does the proposed API look like?

I am thinking along the lines of using either ElasticSearch or MongoDB (probably MongoDB) because it is smaller and fits into Docker ecosystem easier.  Which will provide some sort of indexer.

Perhaps something like the following in the CLI

    vuepress index --format=mongodb

Which will generate a file that is suitable executing in the MongoDB CLI which can be used to generate JS files that do database inserts that would be suitable for the [MongoDB Docker image](https://hub.docker.com/_/mongo/)

#### How should this be implemented in your opinion?

The easy part would likely be to write the mongo JS insert statements.

The hard parts would be:

a) modifying the default template to allow that as a new search using [mongo-rest](https://hub.docker.com/r/linuxenko/mongo-rest/) API.  [mongo-rest](https://hub.docker.com/r/linuxenko/mongo-rest/) would be used to wrap Mongo in a readonly mode so we do not need to deal with administration
b) figuring out what to store into the mongodb.

#### Are you willing to work on this yourself?**

No.

**Comment by trajano** [comment]
[mongo-rest](https://hub.docker.com/r/linuxenko/mongo-rest/) can be used to wrap the MongoDB so it can be used by VueJS.

**Comment by ulivz** [comment]
Cool, I think it's a useful feature, we'll plan to do more for that at [next](https://github.com/vuejs/vuepress/tree/next) branch.

**Comment by l0nax** [comment]
Was this Feature Included in VuePress?

**Comment by iofu728** [comment]
Expect to next version

**Comment by l0nax** [comment]
So if I use the "Develop Version" (installing from this Repo) I can use this Feature?

**Comment by RickCogley** [comment]
Lunr (https://lunrjs.com/) is a good option, provided you can make a json file with your contents as input. It works for me on some static Japanese sites I build (not on vuepress), and I have heard others say it's fine with the other "CJK" languages.

**Comment by ulivz** [comment]
For now VuePress doesn't plan to support dynamic data source in the core, but you can implement it by writing a plugin. 

FYI, you can just fork [@vuepress/plugin-search](https://vuepress.vuejs.org/plugin/official/plugin-search.html#vuepress-plugin-search).
