### ISSUE TITLE
Comment data is not automatically updated

### ISSUE THREAD

**Issue by GongJS** [vuejs/vuepress#810]
Version
Latest version: 0.14.2

Steps to reproduce
check this repo for reproduction

What is expected?
fix this weird behaviour

What is actually happening?
Comment data is not automatically updated

Your OS: Mac OS High Sierra (10.13.6)
Node.js version: v8.11.4
Browser version: latest chrome
Is this a global or local install? local
Which package manager did you use for the install? yarn

I got a local repo, using webpack 4 and latest babel 7 for develoment
And I want to use vuepress for documentation
Then I add `valine` as comment system in the vuepress,
but  I have problems during the process of using `valin` in the vuepress:

![bug](https://user-images.githubusercontent.com/25744301/45217731-bfc6f500-b2d7-11e8-8350-a54fba81939a.gif)

as you can see , when i jump to the  `Deploying` page, the comment data is not automatically updated ,need me to manually refresh the  `Deploying` page.

this is my code:
```
\\Comments.vue
<template>
    <div class="vcomment" v-if="data.comments === true">
      <div id="vcomments"></div>
    </div>
</template>

<script>
export default {
  computed: {
    data () {
      return this.$page.frontmatter
    }
  },

  mounted: function () {
    const Valine = require('valine')

    this.window = window
    window.AV = require('leancloud-storage')

    new Valine({
      el: '#vcomments',
      appId: 'dw2tx8d6vMPTvWUnipnDu6lA-gzGzoHsz',
      appKey: 'yqr27CxNs4sIAXDjWY3zAn7A',
      notify: true,
      verify: false,
      avatar: 'monsterid',
      placeholder: '欢迎留言与我分享您的想法...'
    })
}
</script>
  // Page.vue
  <slot name="bottom"/>
    <comments v-if="hackReset"></comments>
  </div>
</template>

<script>
import { resolvePage, normalize, outboundRE, endingSlashRE } from './util'
import Comments from './Comments.vue'
export default {
  props: ['sidebarItems'],
  components: { Comments },
 .....
```

![bug-1](https://user-images.githubusercontent.com/25744301/45218401-0fa6bb80-b2da-11e8-8204-988397d81260.gif)

i check the network, and i find the comment data's request  parameter has not changed....
i do not know how to solve it ...
this is my [repo](https://github.com/GongJS/test_vuepress)

**Comment by ulivz** [comment]
This is because VuePress using [history-mode](https://router.vuejs.org/guide/essentials/history-mode.html), which leverages the `history.pushState` API to achieve URL navigation without a page reload(Very user friendly). so the `mounted` hook won't trigger again when you switch the route.

So you watch the change of route to solve it:

```js
{
  // Your comment component
  watch: {
    '$route' () {
      // Re-call comment
    }
  },
}
```

**Comment by GongJS** [comment]
oh,I  know.... but by this way, the page  can't  be cached, so the experience will not be good..
No matter what， thank  you !

**Comment by ulivz** [comment]
Why cannot the page be cached?

**Comment by GongJS** [comment]
i  change the code like this:
```
watch: {
     '$route' (to, from) {
        if(to.path !==  from.path){
          this.$router.go(0)
        }else{
           // nothing
       }
     }
   }, 
```
and it worked,   sorry ,  the previous code is wrong, thank you .

**Comment by ulivz** [comment]
Why adding this:

```js
if(to.path !==  from.path){
          this.$router.go(0)
        }else{
           // nothing
       }
```
