### ISSUE TITLE
Change GitHub to Source in default template.

### ISSUE THREAD

**Issue by robmuh** [vuejs/vuepress#811]
## Feature request

Change *GitHub* to *Source* in the default template.

#### What problem does this feature solve?

Removes vendor-specific reference to GitHub (by default)

#### Are you willing to work on this yourself?**

Sure.

**Comment by ulivz** [comment]
You can check out our implementation:

https://github.com/vuejs/vuepress/blob/master/lib/default-theme/NavLinks.vue#L97

We have made it default to `Source`, but when you provide the repo link (github, gitlab or Bitbucket), we'll infer it. If you want to change the label text, you can [change the `repoLabel`](https://vuepress.vuejs.org/default-theme-config/#git-repo-and-edit-links).

**Comment by robmuh** [comment]
Absolutely brilliant solutions! Something so small, but it really shows just how far ahead the thinking of these team is. I hope to be able to help more in whatever way I can. (Hey did I mention I created the TOML logo?) Seriously, thank you for all of it. I can't rave enough and can't wait to show off working examples of "rich text books" at ISTE and NCTIES eventually evangelizing this great tool. I've definitely crossed into fan-boy status.
