### ISSUE TITLE
Is it possible to write some markdown and reuse it in other markdown files?

### ISSUE THREAD

**Issue by rajaraodv** [vuejs/vuepress#812]
Sorry, I didn't know where else to ask. I have a piece of markdown with some pictures, code and text. I need to reuse it in multiple other markdown files. How to do that?

**Comment by FistMeNaruto** [comment]
Markdown inclusion is not possible right now, but it is planned for 1.0.0. See #222.

**Comment by ulivz** [comment]
Closing it since it's duplicate, let's move #222 to continue.
