### ISSUE TITLE
如何在head嵌入百度统计啊

### ISSUE THREAD

**Issue by onesez** [vuejs/vuepress#813]

**Comment by wangyi7099** [comment]
我用的 netlify。。 在持续集成的  post building里向head里插入一个标签就行了。。。

**Comment by onesez** [comment]
具体怎么操作

发自我的 iPhoneX

**Comment by ulivz** [comment]
This is a question and should be asked in the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress)
