### ISSUE TITLE
Scroll overflow triggered by long words

### ISSUE THREAD

**Issue by FistMeNaruto** [vuejs/vuepress#823]
#### Version
0.14.2
#### Steps to reproduce

1. Open any VuePress project (https://vuepress.vuejs.org/guide/)
2. Open devtools and edit in a long word inside the content (a URL like `https://github.com/vuejs/vuepress/issues/vuepress/issues/vuepress/issues/`, for example)

#### What is expected?

Long word breaking and scrolling working properly:

![screenshot from 2018-09-11 23-35-46](https://user-images.githubusercontent.com/13431677/45386272-9aa9ed80-b61b-11e8-985b-78e12f8309e7.png)

#### What is actually happening?

Long word introduces a scroll overflow, which allows the navbar to be scrolled out of the viewport:

![screenshot from 2018-09-11 23-36-17](https://user-images.githubusercontent.com/13431677/45386316-bf9e6080-b61b-11e8-8b43-3b49ad189c85.png)

The same issue happens when long words are inside the nav menu:

![screenshot from 2018-09-11 23-11-17](https://user-images.githubusercontent.com/13431677/45386563-510dd280-b61c-11e8-9406-fd8b60bf3577.png)

Or section headers:

![screenshot from 2018-09-11 23-42-47](https://user-images.githubusercontent.com/13431677/45386607-6d117400-b61c-11e8-9f37-8d5b472a9789.png)

#### Other relevant information

- Your OS: Arch linux
- Node.js version: v10.10.0
- Browser version: Chromium 68.0.3440.106
- Is this a global or local install? Local
- Which package manager did you use for the install? Yarn

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/pull/824#pullrequestreview-155719501
