### ISSUE TITLE
markdown img link

### ISSUE THREAD

**Issue by Kyoloro** [vuejs/vuepress#826]
Hi, thanks so much for this tool, very useful...

but I have some question, maybe it's my mistake.

**version**
vuepress@0.14.2 

**Example**:
`![](./path_image.png)`
tip: this is fine, `./path_image.png` will be changed to `{base}/assets/img/path_image.{hash}.png`

**Something wrong**:
`[![](./path_image.png)](./path_image.png)` 
tip: the last link won't go to `{base}/assets/img/path_image.{hash}.png`, but go to `./path_image.png`, and it get 404

watch for help... thanks so much..

**Comment by Kyoloro** [comment]
I find some way to solve it.

at markdown doc, vuepress can use html element.

**Solve:**

- move `path_image.png` to `.vuepress/public/` folder

- edit `a.md`

```markdown
---
some header code
---

# A page

<a :href="$withBase('/path_image.png')">
  <img :src="$withBase('/path_image.png')" alt="">
</a>
```

It work .

**Comment by tristanlins** [comment]
I'm not sure if that's right.
But after I reverse engineered the code, I found out that you can change the `transformAssetUrls`.

```js
module.exports = {
  chainWebpack: (config, isServer) => {
    config.module.rule('vue').uses.store.get('vue-loader').store.get('options').transformAssetUrls = {
      video: ['src', 'poster'],
      source: 'src',
      img: 'src',
      image: ['xlink:href', 'href'],
      a: 'href'
    };
  }
};
```

Actually, I was looking for a way to support vuetify's `v-img`.
I just added `v-img: 'src'` =>

```js
module.exports = {
  chainWebpack: (config, isServer) => {
    config.module.rule('vue').uses.store.get('vue-loader').store.get('options').transformAssetUrls = {
      ...,
      'v-img': 'src'
    };
  }
};
```
