### ISSUE TITLE
Serif Font Toggle

### ISSUE THREAD

**Issue by robmuh** [vuejs/vuepress#827]
## Feature request

Nothing Earth shattering, but I wonder if having  a config setting in the default template to enable a serif font would be worth considering. Medium uses a mixture of san (headers) and serif (body). I realize I can do this myself in the style overrides and will continue to do so. Just putting out there the possibility that others would appreciate this as a configurable option.

My feelings will not be hurt if you instantly close this.  😁

#### What problem does this feature solve?

It improves readability dramatically on modern screens.

#### What does the proposed API look like?

```toml
[themeConfig]
serif = true
```

#### How should this be implemented in your opinion?

See above.

#### Are you willing to work on this yourself?**

Absolutely.

**Comment by ulivz** [comment]
Thanks for your suggestion, but it's so simple to implement at user-land so we don't plan to open a new config for it.
