### ISSUE TITLE
TOML Front Matter Support

### ISSUE THREAD

**Issue by robmuh** [vuejs/vuepress#828]
## Feature request

TOML front matter support.

#### What problem does this feature solve?

Carries the support of `config.toml` through into all front matter possibilities.

#### What does the proposed API look like?

```
+++
toml = 'here'
+++
```

https://gohugo.io/content-management/front-matter/

#### How should this be implemented in your opinion?

Additional check for front-matter type.

#### Are you willing to work on this yourself?**
 
Yes.

**Comment by ulivz** [comment]
Of course we've supported for it: https://github.com/vuejs/vuepress/pull/164
