### ISSUE TITLE
Provide a way to call custom JS when a new page is loaded

### ISSUE THREAD

**Issue by rajaraodv** [vuejs/vuepress#829]
## Feature request
I am using [medium-zoom](https://github.com/francoischalifour/medium-zoom) library that scans for all the "img" tags and adds callback. This allows us to Zoom all the images in the page. So I have added the following in the config. But it needs to be called from each page. Ciurrently I have another js file `mediumZoom.js` that simply calls the `  mediumZoom('img')` so that the library can add its features. But this doesn't work when I go from the main page to another page because my hacky solution `mediumZoom.js` is not reloaded. I'm wondering if there is any callback that I can listen to know if the new page is loaded and then call my function. If not, please add it. 

BTW, I am really enjoying Vuepress although I don't know Vue! (I'm mainly a React guy). Thank you for such an amazing product!

```
//config.js
  head: [
    [
      "script",
      { src: "https://unpkg.com/medium-zoom@1.0.2/dist/medium-zoom.min.js" }
    ],
    [
      "script",
      { src: "/mediumZoom.js" }
    ]
  ]
```

```
//mediumZoom.js

setTimeout(function() {
  mediumZoom('img')
}, 1000);

``

<!-- Please ask questions on StackOverflow. -->
<!-- https://stackoverflow.com/questions/ask?tags=vuepress -->
<!-- Issues which contain questions or support requests will be closed. -->

#### What problem does this feature solve?
Helps us run custom JS upon page load
#### What does the proposed API look like?
onPageLoad(myFunctipnToCall)
#### How should this be implemented in your opinion?
It should be similar to event listeners in the DOM. It should allow multiple functions to listen to the onPageOpen, onPageClose etc.
#### Are you willing to work on this yourself?**
No.

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, let's go https://github.com/vuejs/vuepress/issues/434 to continue.

**Comment by howar31** [comment]
Hello,

I have similar question about how to call a custom Javascript on each page loaded. 
I'm hosting VuePress as a blog.  And I want to add a comment section at the bottom of every pages (site-wide), such as Disqus.  
I want to stick with the default layout.  So currently all I can do is to add a custom component, which contains Disqus code, and add the component to every pages manually.  This is hard to maintain.

Is there any way to load a custom Javascript function on every page in VuePress 0.14.10?
Or should I upgrade to 1.x for plugin support? (but it's in alpha now)

Thank you
