### ISSUE TITLE
关于部署问题

### ISSUE THREAD

**Issue by Salvador23** [vuejs/vuepress#833]
不好意思，打扰您大神前来问下部署问题，在腾讯云linux系统可以部署VuePress项目不会出现问题吗？还有在首页可以自行弄成全屏背景图里面只有自我介绍或者链接地址比如说blog，github,微博等等按钮，也不需要搜索栏，导航栏留下，点击链接地址跳到后至少有搜索栏，导航栏等等可以实现吗？

**Comment by ulivz** [comment]
1. Please read the docs first.
2. Please don't use issue to ask questions.
