### ISSUE TITLE
feat: allow showing a dropdown on site title

### ISSUE THREAD

**Issue by rigor789** [vuejs/vuepress#835]
#### What problem does this feature solve?

I was browsing the vue-router docs, and wanted to jump to the vuex docs. Currently there is no "easy" way to do this, and what I would consider a convenient solution is if the current site title was a dropdown with a list of related sites.

#### What does the proposed API look like?

```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    sites: [
      { text: 'Vue Router', link: 'https://router.vuejs.org' },
      { text: 'Vuex', link: 'https://vuex.vuejs.org' },
    ]
  }
}
```

#### How should this be implemented in your opinion?

I believe we can easily implement this by reusing the existing [`DropdownLink` component](https://github.com/vuejs/vuepress/blob/master/lib/default-theme/DropdownLink.vue)

And a new branch in the [`Navbar` component](https://github.com/vuejs/vuepress/blob/master/lib/default-theme/Navbar.vue)
https://github.com/vuejs/vuepress/blob/a7d9a1a6ee570574d3113c9028a0df068ab80445/lib/default-theme/Navbar.vue#L15-L20

```xml
      <!-- sitesLinks would be a computed property so that it can automatically add $siteTitle as the root elements text -->
      <DropdownLink v-if="sites" :item="sitesLinks" />
      <span
        ref="siteName"
        class="site-name"
        v-else-if="$siteTitle"
        :class="{ 'can-hide': $site.themeConfig.logo }"
       >{{ $siteTitle }}</span>
```

#### Are you willing to work on this yourself?**

If this is something useful for anyone, sure!

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/issues/683#issuecomment-408924448
