### ISSUE TITLE
Rename `.vuepress` as `config`

### ISSUE THREAD

**Issue by colwilson** [vuejs/vuepress#836]
## Feature request

Rename `.vuepress` as `config` or similar. `.vuepress/config.js` should become `config/meta.js`

#### What problem does this feature solve?
Developers will already know this is a vuepress project. wouldn't the more conventional config make more sense?

#### How should this be implemented in your opinion?
I'm hoping there's no magic here. Just s straight rename?

#### Are you willing to work on this yourself?**
Yes, with guidance.

**Comment by ulivz** [comment]
Sorry but **no**, some other projects would also use the `config` as config directory, and it's very common to see VuePress installed at an existing project.
