### ISSUE TITLE
HTTP2 Server Push

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#837]
## Feature request
Halo, will be great if we support officially HTTP/2 Server Push (generate file for assets)

#### What problem does this feature solve?
Increase performance

#### What does the proposed API look like?
It better implemented as plugin for the next v1.0 version

#### How should this be implemented in your opinion?
Listen to a hook for generated `preload` or `prefetch` assets then write it to a file (firebase.json, _headers, etc).

#### Are you willing to work on this yourself?**
Ya.

I implemented this by running a script that crawls all generated `html` files using `cheerio` but I don't think that's a best practice.

**Comment by ulivz** [comment]
So please create a plugin for it after the 1.0.0 release.

**Comment by skurlow** [comment]
@ekoeryanto do you know if there is any progress on support for HTTP/2 with Vue to improve loading performance of pages?

**Comment by ekoeryanto** [comment]
I made a plugin for this https://github.com/ekoeryanto/vuepress-plugin-server-push
