### ISSUE TITLE
自定义主题如何创建侧边栏

### ISSUE THREAD

**Issue by yqxf** [vuejs/vuepress#839]
版本：0.14.3

问题描述：
设置自定义主题的时候，即建了.vuepress -> theme -> Layout.vue，之后如何在设置侧边栏呢？
默认主题是在config.js里面配置sidebar，设置了自定义主题后这个就无效了，请问应该怎么做呢？
谢谢！

**Comment by ulivz** [comment]
侧边栏由你自己实现。

---

再一次强调，不要用 issue 问问题。

**Comment by yqxf** [comment]
我用vuepress主要是想用这个侧边栏自动生成的，但是又不想要那个头部以及首页等其他内容，所以用的自定义主题，但是自定义主题没法自动生成侧边栏的么？？？
