### ISSUE TITLE
Hero Image Fails to Resize

### ISSUE THREAD

**Issue by robmuh** [vuejs/vuepress#849]
## Bug report

Nothing a `max-width: 100%` won't fix:

```css
.hero img {
  max-width: 100%;
}
```
Before:
![screen shot 2018-09-17 at 3 15 33 pm](https://user-images.githubusercontent.com/3749067/45645075-65732480-ba8d-11e8-8e60-29f60077ad05.png)
After:
![screen shot 2018-09-17 at 3 15 59 pm](https://user-images.githubusercontent.com/3749067/45645109-7a4fb800-ba8d-11e8-97bb-b5274920af36.png)

#### Version

0.14.2

#### Steps to reproduce

Just create any image the is relatively wide and set as hero image.

#### What is expected?

Responsive resizing.

#### What is actually happening?

Not resizing.

#### Other relevant information

That should be enough. Can provide more if needed.

Thank you.

**Comment by ulivz** [comment]
Welcome to create a PR for that, thanks!

**Comment by sh7dm** [comment]
Looks like it's already been fixed: https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Home.vue#L82

**Comment by Deraw-** [comment]
Yes, fixed by https://github.com/vuejs/vuepress/pull/980 🙂
