### ISSUE TITLE
Version Docs - limiting search context

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuepress#857]
## Feature request

Some projects offer documentation for different versions of their software.
In order to meaningfully navigate these, it would be nice to have something like a version context.

Versions are commonly organized as folders like so:
`docs/1.2`, `docs/2.0`

#### What problem does this feature solve?

Cover documentation for multiple versions without having multiple Vuepress installations.

#### What does the proposed API look like?

This feature involves a few smaller features:

- Limit search to a certain parent folder (only search in `docs/2.0`)
- Add a version picker based on folders to switch contexts
- Redirect to most recent version on index

#### How should this be implemented in your opinion?

It could work similar to the sidebar. Limiting the search could make use of the site metadata api so we can see how based on the folders, to only include relevant items.

versions could work as dropdown. Similar to how this software company does documentation: https://help.k15t.com/scroll-versions/latest/scroll-versions-documentation-110528202.html (right upper corner)

#### Are you willing to work on this yourself?

I'm extending my own theme and will see how I can go from there.  It is not that easy maybe, because I have to see how flexible the settings have to be. Is it ok to assume versions are only located in the topmost parent folder?

**Comment by ulivz** [comment]
Good feature request 👍

**Comment by robsontenorio** [comment]
@MartinMuzatko What mechanism do you use to versioning docs automatically?

**Comment by robsontenorio** [comment]
See #1032

**Comment by ulivz** [comment]
For docs please see [here](https://v1.vuepress.vuejs.org/plugin/official/plugin-search.html#options).
