### ISSUE TITLE
Support devServer.proxy in configureWebpack

### ISSUE THREAD

**Issue by ad-m** [vuejs/vuepress#858]
## Feature request

Allow to use ```devServer.proxy``` from webpack & make work.

#### What problem does this feature solve?

CORS request to API in development envrionemtn.

#### What does the proposed API look like?

It doesn't require new API, but it should be something like that:

```javascript
module.exports = config = {
    configureWebpack: {
        devServer: {
            proxy: {
                "/api": {
                    target: "http://localhost:8090/",
                    secure: false
                }
            }
        },
    }
}; 
```

#### How should this be implemented in your opinion?

Replace deprecated (see https://github.com/webpack-contrib/webpack-serve ) webpack-serve there https://github.com/vuejs/vuepress/blob/master/lib/dev.js#L97 and use webpack-dev-server instead (  https://github.com/webpack/webpack-dev-server ).

#### Are you willing to work on this yourself?**

I don't know webpack enought.

**Comment by ulivz** [comment]
Thanks for the report, and it has been addressed at #1195.
