### ISSUE TITLE
Allow Links in Footer

### ISSUE THREAD

**Issue by gevera** [vuejs/vuepress#859]
#### What problem does this feature solve?
Right now there is no straightforward way to add a link to footer via frontmatter or in config.js
A workaround will be a custom component.
However, it is a common thing and it is used often. I believe that lot's of people will find this feature useful.

#### What does the proposed API look like?
N/A

#### How should this be implemented in your opinion?

*In config.js*
using regular html
footer: 'Link to external <a href="https://www.somepage.com">page</a>'
or markdown
footer: 'Link to external [page](https://www.somepage.com)'

*In YAML frontmatter*
footer: Link to external [page]
footerLink: https://www.somepage.com

#### Are you willing to work on this yourself?**
I am not sure how to do that

**Comment by ccleve** [comment]
Related: allow links in the "features" elements on the home page. Would be nice to have them in both the title and the details. The benefit is that a user could click on a feature and go straight to the docs that describe the feature.

**Comment by nicholasglazer** [comment]
I've got response in my website from a user : - "For some reason links under the button are not working". So I totally agree with @ccleve that it's nice to have both features.

**Comment by ulivz** [comment]
Maybe we should open up a way for user to custom the footer via a Vue component.

**Comment by yonkov** [comment]
I also need this feature, i asked for help in the vue forum but still could not get it to work.. [Link](https://forum.vuejs.org/t/vuepress-add-link-to-footer-in-front-matter/52598)

**Comment by Shigma** [comment]
And now we have markdown slots, which may solve your problem.

**Comment by ulivz** [comment]
Since we have supported [Theme Inheritance](https://v1.vuepress.vuejs.org/theme/inheritance.html), you can create a custom theme to extend the default theme to get it.
