### ISSUE TITLE
docs: there is no publicPath

### ISSUE THREAD

**Issue by michael-brade** [vuejs/vuepress#876]
## Bug report

See the example here: https://vuepress.vuejs.org/plugin/#enhancedevserver
It doesn't work because the `AppContext` doesn't have such a property: `ctx.publicPath`
I think what was meant is just `ctx.base`.

#### Version

1.0.0-alpha.1

#### Steps to reproduce

Add the example plugin, run VuePress in dev mode: `vuepress dev docs`.

#### What is expected?

vuepress starts in dev mode.

#### What is actually happening?

It crashes:
```
FAIL  anonymous-9 apply enhanceDevServer failed.
(node:26906) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at enhanceDevServer (./docs/.vuepress/assets.js:18:28)
```

#### Other relevant information

- Your OS: Debian unstable
- Node.js version: 10.10.0
- Browser version: n/a
- Is this a global or local install? local
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Thanks, it's truly `base` and we forgot to update after we unify the `base` and `publicPath`.
