### ISSUE TITLE
Markdown syntax rendering is broken for CommonMark

### ISSUE THREAD

**Issue by robmuh** [vuejs/vuepress#880]
## Bug report

Has trouble with images as links. It shouldn't. These are basic and common.

![screen shot 2018-09-27 at 5 51 46 pm](https://user-images.githubusercontent.com/3749067/46176603-05932f80-c27e-11e8-9543-389af46f7c88.png)

#### Version

0.14.4

#### Steps to reproduce

Simply include any CommonMark `md` fence with a linked image.

#### What is expected?

Accurate syntax hilighting.

#### What is actually happening?

Not that.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
