### ISSUE TITLE
Blog plugin: category, tag page don't work

### ISSUE THREAD

**Issue by mAKEkr** [vuejs/vuepress#881]
#### Version
v1.0.0-alpha.1

#### Steps to reproduce

1. install ulivz/vuepress-blog-example-egoist repository
2. run development mode(``vuepress dev source``)
3. access to tag, category page

#### What is expected?
displaying category, tags page.

#### What is actually happening?
404 page displaying.

#### Other relevant information
testing on ulivz/vuepress-blog-example-egoist repository.

- Your OS: Windows 10
- Node.js version: v10.4.1
- Browser version: Firefox
- Is this a global or local install? local install
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
Cann't reproduce it. did you execute the latest repo?

**Comment by mAKEkr** [comment]
@ulivz yes, I clone latest repo, and try to up to date nodejs, but same problem on my environment.
![vuepress](https://user-images.githubusercontent.com/2796198/46190013-a4766500-c32c-11e8-9515-0e0d3fb429ff.PNG)

https://github.com/mAKEkr/vuepress-blog-akekr
this is my vuepress repository, maybe this help for solve this issue.

**Comment by mAKEkr** [comment]
current check build command, all render complete without error.
category and tag page render complete and don't displaying 404.
this problem still an error occurs on dev command.

**Comment by ulivz** [comment]
@mAKEkr Could you check if `v1.0.0-alpha.2` works?

**Comment by mAKEkr** [comment]
@ulivz I checked v1.0.0-alpha.2 on my repository, these problem not solved yet, and new error on dev/build script.

![windows problem](https://user-images.githubusercontent.com/2796198/46243298-bbd94f00-c40d-11e8-9d91-524f73a83bf5.PNG)
this error has only displaying on Windows OS environment(Ubuntu 18.08 windows subsystem don't display this error). maybe ``19e73d7`` this commit effect on my environment.

**Comment by ekoeryanto** [comment]
I have the same issue, 
and fixed with #886

**Comment by mAKEkr** [comment]
category and tag page don't register on page-components.js. maybe this is key of solve this issue.

**Comment by zvinless** [comment]
this occurs for me on macOS as well, both with the vuepress-blog-example-egoist (alpha.8) repository and with a simple theme on alpha.13.

**Comment by mAKEkr** [comment]
@zvinless can you try on applied #909 PR? this PR solved my issue.

**Comment by zvinless** [comment]
@mAKEkr yeah, the pages get generated properly with that change applied 👍

**Comment by amorist** [comment]
same issue

Your OS: MacOS 10.14
Node.js version: v11.0.0
Browser version: Chrome
Is this a global or local install? local install
Which package manager did you use for the install? npm & yarn

**Comment by tkzwhr** [comment]
It might work according to Node.js version.
My OS is Ubuntu 18.04 on Windows Subsystem for Linux.

#### Node.js versions

- v8.14.0 => 200 OK
- v9.11.2 => 200 OK
- v10.14.2 => **404 Not Found**
- v11.4.0 => **404 Not Found**

#### Applied #909 ( @mAKEkr 👍  )

- v8.14.0 => 200 OK
- v9.11.2 => 200 OK
- v10.14.2 => 200 OK
- v11.4.0 => 200 OK

**Comment by ulivz** [comment]
This issue should be fixed at the latest version (1.0.0-alpha.30).
