### ISSUE TITLE
Custom HTML template in siteconfig

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#882]
## Feature request
seen [here ](https://github.com/vuejs/vuepress/blob/20e520dd904340d03500841313c61299d09f1c5a/packages/%40vuepress/core/lib/prepare/AppContext.js#L160) I think the better one is in `themeConfig`

**Comment by ulivz** [comment]
Supported in 7437005

 Now the resolving priority (devTemplate as example) is as follows:

1. siteConfig.devTemplate
2. `dev.html` located at `.vuepress/templates`
3. themeIndexFile.devTemplate
4. default devTemplate

---

FYI.

`themeIndexFile` refers to the entry file `index.js` of the theme. while `themeConfig`  is a field of `siteConfig`. —— Consider creating a glossary later to avoid confusion.

---

BTW.

Improving documentation are welcome. When the document was stable, I will officially announce the release of next version.

**Comment by ekoeryanto** [comment]
I see it still using `siteConfig` not `themeConfig`
```js
   const { siteSsrTemplate, siteDevTemplate } = this.siteConfig
```

also, `palette` should be in `themeConfig` not in `siteConfig`

**Comment by ulivz** [comment]
I don't think it should be in `themeConfig`. detail of `themeConfig` should be controlled by theme itself instead of core.

**Comment by meteorlxy** [comment]
@ekoeryanto Themes can set devTemplate by `themeIndexFile.devTemplate`, which will be overrided by `siteConfig`

**Comment by ekoeryanto** [comment]
ha, thanks I think I need to read the source again carefully
