### ISSUE TITLE
markdown.config not work anymore

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#885]
#### Version
1.0

#### Steps to reproduce
migrating to next version and found [markdown.config](https://vuepress.vuejs.org/config/#markdown-config) does not work any more, but it works when the code moved to a plugin with extendMarkdown.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
Yes, this API has been renamed to `markdown.extendMarkdown` to keep consistent to plugin API.

**Comment by ulivz** [comment]
Updated document at 89d8a7aa7151e7f76bf3a09b78a35e1d7b6f07bc

**Comment by ulivz** [comment]
We'll write a migration when we reach rc.

**Comment by ekoeryanto** [comment]
@ulivz, maybe you forgot `BREAKING CHANGE` keyword in the commit 😃

**Comment by jenreiher** [comment]
FYI looks like this didn't get updated in the documentation! @ulivz https://vuepress.vuejs.org/config/#markdown-config

**Comment by ycjcl868** [comment]
BreakChange + 1
