### ISSUE TITLE
How should I use the back-to-top plugin in vuepress?

### ISSUE THREAD

**Issue by chenweigao** [vuejs/vuepress#888]
hi, when I am reading official tutorials, I find that a small button 'back to top' in the site, so I read the code of `vuejs/vuepress/docs.vuepress/' and update my site's code as follows:
`in docs/.vuepress/configs' I add:
```
plugins: {
      '@vuepress/plugin-back-to-top': true,
    }
```
and in `package,json`, add:

```
 "devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.2",
    "@vuepress/plugin-i18n-ui": "^1.0.0-alpha.2",
    "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.2",
    "@vuepress/plugin-pwa": "^1.0.0-alpha.2",
    "vuepress": "^1.0.0-alpha.2"
  }
```

but unlucky, there is no effect on my site, for I want the button 'back to top' as an official site, what should I do?

**Comment by ulivz** [comment]
You'd better create a reproduction repo for that. thanks

**Comment by ekoeryanto** [comment]
@ulivz I think we need an official place for discussion or support, something like discord or gitter

**Comment by ulivz** [comment]
See issue template.

**Comment by Eterion** [comment]
@chenweigao this works for me
```
plugins: ['@vuepress/back-to-top']
```

**Comment by chenweigao** [comment]
> You'd better create a reproduction repo for that. thanks

This is my repo's link: https://github.com/chenweigao/vueblog.git
thank you very much for your help.

**Comment by chenweigao** [comment]
> @chenweigao this works for me
> 
> ```
> plugins: ['@vuepress/back-to-top']
> ```
it still does not work, I don't know why...Orz

**Comment by x8x** [comment]
@chenweigao From [here](https://github.com/chenweigao/vueblog/blob/master/package.json) it looks like you are running release version `0.14.4`, while plugin support is added to the `1.x` version that you have to install with `yarn add vuepress@next -D` documented [here](https://github.com/vuejs/vuepress). Be warned that it is still alpha ;-)

**Comment by chenweigao** [comment]
> @chenweigao From [here](https://github.com/chenweigao/vueblog/blob/master/package.json) it looks like you are running release version `0.14.4`, while plugin support is added to the `1.x` version that you have to install with `yarn add vuepress@next -D` documented [here](https://github.com/vuejs/vuepress). Be warned that it is still alpha ;-)

Thank you very much, I updated then vuepress via 'yarn add vuepress@next -D`, but when I run 'npm run docs:build`, there is an error that `[vuepress] cannot resolve plugin "@vuepress/back-to-top"`, what's wrong with me? could you please help me?

**Comment by ulivz** [comment]
@chenweigao 

You should install a plugin before using it.

```
yarn add @vuepress/plugin-back-to-top -D
```

**Comment by chenweigao** [comment]
> @chenweigao
> 
> You should install a plugin before using it.
> 
> ```
> yarn add @vuepress/plugin-back-to-top -D
> ```

It is ok for this code, thanks for your kind help!

**Comment by songStar0904** [comment]
> > @chenweigao From [here](https://github.com/chenweigao/vueblog/blob/master/package.json) it looks like you are running release version `0.14.4`, while plugin support is added to the `1.x` version that you have to install with `yarn add vuepress@next -D` documented [here](https://github.com/vuejs/vuepress). Be warned that it is still alpha ;-)
> 
> Thank you very much, I updated then vuepress via `yarn add vuepress@next -D`, but when I run `npm run docs:build`, there is an error that `[vuepress] cannot resolve plugin "@vuepress/back-to-top"`, what's wrong with me? could you please help me?

hi, i used `npm install -d vuepress@next`, but not change
```md
"devDependencies": {
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.0",
    "gh-pages": "^1.1.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vuepress": "^0.14.5"
  },
  "dependencies": {
    "element-ui": "^2.3.6",
    "html2canvas": "^1.0.0-alpha.12",
    "nprogress": "^0.2.0",
    "prismjs": "^1.14.0",
    "vue": "^2.5.16"
  },
```

**Comment by OtabekSadiridinov** [comment]
yarn add vuepress@next -D worked for me with the latest version
