### ISSUE TITLE
Why components are inside .vuepress?

### ISSUE THREAD

**Issue by brsanthu** [vuejs/vuepress#89]
I would like to understand the reasoning behind using .vuepress subfolder to store components etc.,

When we vuepress, the whole project would be considered vuepress based. So won't it makes sense to just store all components under src instead of .vuepress?

**Comment by yyx990803** [comment]
This is simply for keeping the raw content and VuePress specific assets separate. In a lot of cases we use VuePress for a sub directory e.g. `docs` inside another project. In this case the `docs` directory should be content-first.
