### ISSUE TITLE
Allow lang="coffee" for components or allow disabling of eslint

### ISSUE THREAD

**Issue by Youdaman** [vuejs/vuepress#896]
Currently CoffeeScript in components chokes due to eslint -- is there a way to disable eslint? i.e. where would I put an .eslintignore file? Tried it in components and then in each parent directory but no luck.

**Comment by Youdaman** [comment]
Looked at docs re webpack:

https://vuepress.vuejs.org/config/#configurewebpack

https://vuepress.vuejs.org/config/#chainwebpack

But not sure how/where to get script tags with lang="coffee" being not linted. 

Did a dump of config param of each of the above functions but couldn't see details re linting so guess it's under the hood like in the vue dep itself? 

Couldn't override/reset or ignore with the usual eslint conf/ignore files, might be though I didn't set them up right or they require extra config/modules in order to be processed. 

Thought about using the method used by nuxt in its coffee example but that's only for straight CoffeeScript files not .vue components that also contain templates and styles and script tags. 

Tried adding type="text/coffeescript" in addition to lang="coffee" as I'd heard that makes eslint skip the script tag but no luck.

**Comment by Youdaman** [comment]
I can see here that maybe this is how the linting is setup for VuePress but I'm not sure:

https://github.com/vuejs/vuepress/blob/master/.eslintrc.js

So I tried the following in my config.js:
```
module.exports = {
  title: 'Hello VuePress',
  description: 'Just playing around',
  chainWebpack: (config, isServer) => {
    config.plugins.delete('plugin:vue-libs/recommended')
    config.plugins.delete('plugin:jest/recommended')
  }
}
```

And also tried the above with just 'vue-libs/recommended' and then just 'vue-libs' (and same for jest) but no luck there either. I based these guesses on the `delete` function available with webpack-chain:

https://github.com/neutrinojs/webpack-chain/blob/master/README.md#config-plugins-removing

**Comment by ulivz** [comment]
I cannot understand why there is an eslint issue. Please provide a reproduction repo instead.

**Comment by Youdaman** [comment]
To reproduce, create a component like so:
```
<template>
  <p>Hello {{ name }}!</p>
</template>

<script lang="coffee">
export default data: ->
  { name: 'World' }
</script>
```

When I run `vuepress dev` with the above I get:
```
Module parse failed: Unexpected token (6:19)
You may need an appropriate loader to handle this file type.
|
|
> export default data: ->
|   { name: 'World' }
```

However as per the instructions here https://nuxtjs.org/faq/pre-processors/ I have installed `coffeescript` and `coffee-loader` so it _should_ work.

The reason I believe eslint is the issue is that @yyx990803 said it was the issue with `vue-loader` here:

https://github.com/vuejs/vue-loader/issues/162#issuecomment-187927018

I could be wrong, and it might be nothing to do with eslint, but I can't use CoffeeScript in VuePress as per the docs about pre-processors.

**Comment by Youdaman** [comment]
I can see in the VuePress docs https://vuepress.vuejs.org/guide/using-vue.html#using-pre-processors it says:

> For pre-processors that do not have built-in webpack config support, you will need to extend the internal webpack config in addition to installing the necessary dependencies.

Which links to this in the docs: https://vuepress.vuejs.org/config/#configurewebpack

So I'm not sure whether I have to (or how to) extend VuePress to support CoffeeScript.

Any hints would be appreciated!

**Comment by Youdaman** [comment]
So I searched for "pug" in node_modules/lib/webpack and found the following in createBaseConfig.js:
```
  config.module
    .rule('pug')
    .test(/\.pug$/)
    .use('pug-plain-loader')
      .loader('pug-plain-loader')
      .end()
```

And then I guessed that I could just copy/paste this into my VuePress config.js inside the `chainWebpack` function and replace "pug" with "coffee" and "pug-plain-loader" with "coffee-loader" and bam, it worked! My `.vuepress/config.js`:

```
module.exports = {
  title: 'Hello VuePress',
  description: 'Just playing around',
  chainWebpack: (config, isServer) => {
    config.module
    .rule('coffee')
    .test(/\.coffee$/)
    .use('coffee-loader')
      .loader('coffee-loader')
      .end()
  }
}
```

Hopefully this is helpful to anyone else wondering how to get CoffeeScript working in VuePress!

**Comment by Youdaman** [comment]
Another way to enable CoffeeScript is just extending the build/webpack section of nuxt.config.js like so:
```
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
      config.module.rules.push({
        test: /\.coffee$/,
        loader: 'coffee-loader'
      })
    }
  }
```

I've seen other issues about lang="coffee" not working out of the box and it seems you can use other pre-processors like pug and stylus by just installing their npm modules and respective loaders, however CoffeeScript requires adding the above to the webpack config manually -- perhaps it should be included like the others are so that the code example in the docs works: https://nuxtjs.org/faq/pre-processors#how-to-use-pre-processors-
