### ISSUE TITLE
vuepress eject not copying default theme files

### ISSUE THREAD

**Issue by baumannzone** [vuejs/vuepress#901]
#### Version
v1.0.0-alpha.3

#### Steps to reproduce
Run `vuepress eject`

#### What is expected?
Copy default theme into `.vuepress/theme` folder

#### What is actually happening?
Just creating a file in `.vuepress` folder called `theme` with some text (`module.exports...`) inside

#### Other relevant information

- Your OS: MacOS
- Node.js version: v9.11.1
- Is this a global or local install? Both
- Which package manager did you use for the install? Both, yarn & npm

**Comment by dcastil** [comment]
The problem is that VuePress is copying the contets of the `index.js` file within the default theme directory instead of the whole directory. I fixed that in the PR referenced above.

**Comment by baumannzone** [comment]
Yep, that was the content of the file.
