### ISSUE TITLE
permalink setting doesn't work

### ISSUE THREAD

**Issue by Youdaman** [vuejs/vuepress#903]
### Repro steps:

- create `hello.md` as per docs (https://vuepress.vuejs.org/guide/permalinks.html#permalinks-2) with:
```
---
title: Hello World
permalink: /hello-world
---

Hello!
```
- run `vuepress dev` and visit http://localhost:8080/hello-world or http://localhost:8080/hello-world.html

### Expected:

- see that page above at the permalink specified

### Actual:

- see the 404 page
- the page is still at http://localhost:8080/hello.html

Also happens when trying the `permalink` setting in .vuepress/config.js

Also `vuepress build` generates `hello.html` still.

Also a link on the permalinks docs page (see ":regular" definition) is 404:
> Permalink generated by VuePress by default, for implementation see here

(links to https://github.com/vuejs/vuepress/blob/next/packages/%40vuepress/shared-utils/lib/fileToPath.js)

**Comment by ulivz** [comment]
What you read is the documentation of VuePress 1.x, and VuePress starts to support permalinks from 1.x, but you're using 0.x.x

And we have mentioned it at two different position:

## 1

![image](https://user-images.githubusercontent.com/23133919/46572646-3846d180-c9bc-11e8-9b38-596e4b29b21e.png)

## 2

![image](https://user-images.githubusercontent.com/23133919/46572649-4268d000-c9bc-11e8-8291-dbf129e13f85.png)

To conclude, you should install VuePress via `yarn install vuepress@next`

**Comment by Youdaman** [comment]
You need to update the docs then!

When you press the big green "Get Started" button on the home page, it takes you to the Introduction page of the docs, and then the next page is Getting Started:

https://vuepress.vuejs.org/guide/getting-started.html#global-installation

It does _not_ specify `vuepress@next` -- and the instructions on the home page are below the fold, and many users would click the big green call to action and find the incorrect instructions like I did.

**Comment by ulivz** [comment]
Thanks for the feedback, I just added some compatibility notification at the 1.x website. you can refresh the SW to see it soon.

**Comment by Assassyn** [comment]
I amn running on 1.0.0.24 and Permalinks does not work for me as well.

**Comment by ulivz** [comment]
@Assassyn Please create an reproduction repo instead of mentioning here.

**Comment by hyvyys** [comment]
It still doesn't work for me at version 1.3.0.  This should be straightforward and not black magic! Please create a working example demo instead of claiming it works...

**Comment by hyvyys** [comment]
For anyone having this issue: in my case, it seems I need to restart the dev server anytime I change a single permalink... As I do whenever I create a new scoped style. Talk about hot-reloading.
