### ISSUE TITLE
Unclear how to add _redirect file for Netlify

### ISSUE THREAD

**Issue by tyrw** [vuejs/vuepress#912]
Evan suggested using Netlify to do CDN-level redirects.  

_Originally posted by @yyx990803 in https://github.com/vuejs/vuepress/issues/239#issuecomment-384276251_

Their docs (https://www.netlify.com/docs/redirects) suggest a `_redirects` file placed in the root of the project.

The only way I can find to get a custom file into the root of the deploy folder (docs/.vuepress/dist) is to run the build steps locally, then manually add the file, then commit `dist` and push it to Netlify.

Can we get this file into the `dist` folder during the build automatically?

**Comment by tyrw** [comment]
I found the answer in a more general form here: https://vuepress.vuejs.org/2018/08/15/assets/#relative-urls

> Sometimes you may need to provide static assets that are not directly referenced in any of your markdown or theme components - for example, favicons and PWA icons. In such cases you can put them inside .vuepress/public and they will be copied to the root of the generated directory.

**Comment by pallas-als** [comment]
Thanks!

**Comment by jamesrhea** [comment]
Ironically, that's now a broken link with no redirect. Here's the latest correct URL: https://vuepress.vuejs.org/guide/assets.html#public-files
