### ISSUE TITLE
windows user issue collection (VuePress 1.x Alpha)

### ISSUE THREAD

**Issue by ulivz** [vuejs/vuepress#913]
This issue was for windows users who are using VuePress 1.x Alpha. since I don't use win and even don't have one, so specially create this issue, concentrate all the issues, and hope to solve it with the help of everyone.

For now the urgent issues was `path` handling at windows:

- #908
- https://github.com/vuejs/vuepress/issues/881#issuecomment-425627683
- #886

/cc @mAKEkr @ekoeryanto

**Comment by ulivz** [comment]
About this issue:

![image](https://user-images.githubusercontent.com/23133919/46583058-5b888400-ca83-11e8-84d2-45a8eb6b6c14.png)

After some investigation, I find that we don't need to sunset `upath`, it's mainly caused by this compressed style which would take unexpected result at windows:

```js
path.resolve(outDir)
```

I try to fix it at https://github.com/vuejs/vuepress/commit/f62cd7302475e1436a85bf21182bc250a6924c89 and publish it at `vuepress@1.0.0-alpha.5`, @mAKEkr @ekoeryanto could you help check if the new version fix it?

**Comment by meteorlxy** [comment]
@ulivz 

Same error as you posted above. 

(sorry I just tried and left my lab, so couldn't paste at this moment  :sweat_smile:)

**Comment by ulivz** [comment]
@meteorlxy Cool, your log is so clear, and I can basically confirm that this is an edge case issue of webpack. (webpack/webpack#66), 

Fixed at https://github.com/vuejs/vuepress/commit/d89f766be1649fa3388d51f0a76440ccfb85095e and released at `vuepress@1.0.0-alpha.6`, could you confirm again? Thanks.

**Comment by ulivz** [comment]
@ekoeryanto Why do we fix a small issue by introducing `appveyor`?

**Comment by ekoeryanto** [comment]
@ulivz, I don't understand with `a small issue` you said, except **multi platform** is not a goal of vuepress.
with `appveyor` doing build in windows platform we can prevent merging future PRs that's incompatible  with windows.

**Comment by ulivz** [comment]
@ekoeryanto Why do you want to imagine in advance?

**Comment by chenweigao** [comment]
there is a problem in config the plugin 'last-updated' :
```
 WARN  [@vuepress/last-updated] Invalid value for "pluginOptions" @vuepress/plugin-last-updated: expected a Object or Boolean but got String.
```
and in the 1.x version, I have used
```
 plugins: {
    '@vuepress/last-updated': true
  },
 ```
but failed to show the message, I am the newer of this, so if this a change or a bug... :

**Comment by mAKEkr** [comment]
@chenweigao can you had try an clean installation using an yarn? this issue don't reproduce on my environment.

**Comment by chenweigao** [comment]
@mAKEkr I use both yarn and npm in my project, and when I build it I use npm run, when I install the dependence, I use the yarn add ... is that causes a problem? I cannot understand what ‘an clean installation’ means? could please give me a direction?

**Comment by mAKEkr** [comment]
@chenweigao I mean remove all file in `node_modules` directory, and try running install. my environment somtimes npm crashed installation without error message.

**Comment by ulivz** [comment]
@chenweigao  This issue of `last-update has been fixed at 
 https://github.com/vuejs/vuepress/commit/b8ce22c3a9ae7e6e069040dc0662ea1059baa0f4.

**Comment by chenweigao** [comment]
@ulivz thank you very much. it is a good job! 
best wishes

**Comment by ltstriker** [comment]
> > the base seems must be that, or the js file cannot be found?
> 
> Are you sure? Hmmm... don't know what to say.

Yes.I use the default base at first.But it will find the js file in the path E:/assets/.....
It is a wrong path,so that it make load fail.(It seems a bug too, I think)
 I just try to change the base  to  (/retryvpress/docs/.vuepress/dist/) to fix it to find in the path E://retryvpress/docs/.vuepress/dist/assets/.......
Then the js files were found but just jump 404 soon.
Is it lead to the 404?

**Comment by meteorlxy** [comment]
Close as it's stale
