### ISSUE TITLE
Internationalization doesn't work with sidebar

### ISSUE THREAD

**Issue by gigioSouza** [vuejs/vuepress#914]
#### Version
0.14.4
#### Steps to reproduce
`npm run docs:dev`
open `http://localhost:8080`
switch language

https://github.com/gigioSouza/v-stylish

#### What is expected?
Sidebar update as the language is switched

#### What is actually happening?
Sidebar doesn't update as the language is switched

#### Other relevant information

- Your OS: macOS High Sierra
- Node.js version: v9.9.0
- Browser version: Chrome 69.0.3497.100
- Is this a global or local install? 
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
You want to [get the headers of current page](https://v0.vuepress.vuejs.org/default-theme-config/#auto-sidebar-for-single-pages). but you used [Multiple Sidebars](https://v0.vuepress.vuejs.org/default-theme-config/#multiple-sidebars).

Remove:

```diff
    locales: {
      '/': {
        selectText: 'Languages',
        label: 'English',
-       sidebar: {
-         '/': [
-           {
-             collapsable: false,
-             children: ['']
-           }
-         ]
-       }
      },
      '/pt-br/': {
        selectText: 'Languages',
        label: 'Português brasileiro',
-       sidebar: {
-         '/pt-br/': [
-           {
-             collapsable: false,
-             children: [
-               ''
-             ]
-           }
-         ]
-       }
      }
    }
```

And set `sidebar` via frontmatter:

```
---
home: false
sidebarDepth: 3
sidebar: auto
---
```

**Comment by gigioSouza** [comment]
Thank you!
