### ISSUE TITLE
Badge component stopped working

### ISSUE THREAD

**Issue by Eterion** [vuejs/vuepress#916]
#### Version
1.0.0-alpha.8

#### Steps to reproduce

https://github.com/Eterion/issue-vuepress-badge

#### What is expected?

Badge component should be displayed.

#### What is actually happening?

Badge component is not displayed, throws error in console.

![image](https://user-images.githubusercontent.com/7584981/46600230-d4222b80-cae9-11e8-80cd-5166d020fb82.png)

The component works just fine on vuepress 0.14.4

#### Other relevant information

- Your OS: Windows 10
- Node.js version:  8.12.0
- Browser version: Firefox 62.0.3
- Is this a global or local install? local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Fixed at 04588cc and released at `1.0.0-alpha.9`. ✨
