### ISSUE TITLE
How to select .styl "styles"?

### ISSUE THREAD

**Issue by SeaDude** [vuejs/vuepress#917]
Hello, 

Thank you for the great tool. I'd like to customize things a bit, but I can't locate the .styl equivalents of the .css values on the screen. 

Example: 
- When I inspect a link in the sidebar, there is a div class of `sidebar`, a `ul` class of `sidebar-links`
- When I look at the override.styl file, the selectors are in camelCase. 

How do I translate css selectors to syle selectors?

Thank you!

![image](https://user-images.githubusercontent.com/8636973/46641311-d904d080-cb25-11e8-88e7-50a97a400d87.png)

**Comment by ulivz** [comment]
You should at least provide the version that you use.

**Comment by SeaDude** [comment]
Hello, 

```
user5@system5:~$ vuepress -V
0.14.2
```

The issue templates are labeled "Bug" and "Feature Request". Since my issue was neither, I decided to click "Regular Issue".

**Comment by SeaDude** [comment]
Ok. Do you have any insights on the OP?

**Comment by ulivz** [comment]
> When I look at the override.styl file, the selectors are in camelCase.

These aren't selectors, they are stylus variables.

**Comment by SeaDude** [comment]
For all the other awesome people out there looking for this info, look here: https://stackoverflow.com/a/52384198/5976033
