### ISSUE TITLE
how can i use ' ``` ' to render the code in the slot?

### ISSUE THREAD

**Issue by GongJS** [vuejs/vuepress#920]
hi , i have a problem when i use the slot, i find the ````` doesn't work...

the code and the render result like this:
![1539180492279](https://user-images.githubusercontent.com/25744301/46742212-21182480-ccd9-11e8-9de8-4273eeb36ab8.jpg)
![1539180534788](https://user-images.githubusercontent.com/25744301/46742231-2a08f600-ccd9-11e8-8d71-7e01bafeec05.jpg)
![1539180699540](https://user-images.githubusercontent.com/25744301/46742376-7d7b4400-ccd9-11e8-9b30-8e213646781f.jpg)

**Comment by GongJS** [comment]
> Three "`"(Shift-Enter) Then another`
> 
> EDIT: I don't know how to escape MD from the comment. after the 3 "`" press shift-enter.
> can I recommend to you on Markdown Lint?

oh,of course, thank you very much.

**Comment by billcolumbia** [comment]
@GongJS Did this work for you?

**Comment by GongJS** [comment]
> @GongJS Did this work for you?

i just switch to newline,and it worked, like this:
![888](https://user-images.githubusercontent.com/25744301/46900172-a1ed4100-ced0-11e8-8883-e5f19a4a00b5.jpg)
