### ISSUE TITLE
Please provide a way to have a right-column for sub, sub-sub, sub-sub-sub headers

### ISSUE THREAD

**Issue by rajaraodv** [vuejs/vuepress#921]
Please provide a way to have a right-column for sub, sub-sub, sub-sub-sub headers. This helps us when we have a lot of items in the left pane and we want to show sub-headers, and sub-sub-sub-headers. If we two panes, we can keep the left pane for the main headers and when a user selects one of them, we can show the sub, sub-sub and sub-sub-sub headers in the right hand panel.

![screen shot 2018-10-10 at 9 38 55 pm](https://user-images.githubusercontent.com/626337/46781222-69cdde80-ccd5-11e8-9351-e6ff8f9781db.png)

**Comment by rwam** [comment]
+1

**Comment by ulivz** [comment]
You can create a plugin for that by using [Plugin Options > globalUIComponents](http://localhost:8082/plugin/#globaluicomponents)

Other Refs:

- [Global Computed > $page](http://localhost:8082/miscellaneous/global-computed.html#page)
