### ISSUE TITLE
Custom theme and Default Theme working together?

### ISSUE THREAD

**Issue by milotindragos** [vuejs/vuepress#922]
### Custom theme working together with the basic theme. Is it possible?

💯 VuePress 💯

Is it possible to have a custom theme setup to work only on certain pages (like the `Home`, or `Category Pages` such as _vuepress.vuejs.org_`/guide/` and _vuepress.vuejs.org_`/config/`) and keep the default theme with sidebar and all the default functionality for everything else?

### Example 

I want to change the page vuepress.vuejs.org`/config/` using `layout: AnotherLayout`

![v1](https://user-images.githubusercontent.com/30367360/46784805-72e79b80-cd27-11e8-9c53-dc8ec6cb9489.png)

But keet the page vuepress.vuejs.org`/config/OTHER-PAGE` using something like `layout: Default`. This way I can change all of the `README.md` pages in folders but keep the `default theme` for all files in subfolders. 

![v3](https://user-images.githubusercontent.com/30367360/46784903-d5d93280-cd27-11e8-8db7-221c82f31d38.png)

### If it is not possible then...

If the above is not possible then is it possible to access the `Sidebar` functionality inside a `Custom Theme`?

**Comment by ulivz** [comment]
See: [Custom Layout for Specific Pages](http://localhost:8082/theme/default-theme-config.html#custom-layout-for-specific-pages).
