### ISSUE TITLE
dir attribute for html element

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vuepress#929]
## Feature request

My vue ui library uses the `dir` attribute in the `html` tag for positioning and text direction.

In addition, my ui library uses a class that's set in the container, e.g. `<body class="ms-Fabric">`. The only way to come by this right now is using:

```
---
pageClass: ms-Fabric
---
```

This is tedious though, cause there are a lot of `.md` files that need to have this set.

#### What problem does this feature solve?

There seems to be no way of adding custom tags to the `html` without editing the built docs `index.html` file.

#### What does the proposed API look like?

An entry in `config.js` would help, or an easy way to provide a public `index.html` (similar to vue-cli3).

#### How should this be implemented in your opinion?

See *What does the proposed API look like*.

#### Are you willing to work on this yourself?**

No

**Comment by ulivz** [comment]
You can custom the dev and ssr HTML template to do that.

- `docs/.vuepress/templates/dev.html`: HTML template file for development environment.
- `docs/.vuepress/templates/ssr.html`: Vue SSR based HTML template file in the built time.

See: https://vuepress.vuejs.org/guide/directory-structure.html#directory-structure

> Note that this feature are ONLY supported in `vuepress@1.x`.
