### ISSUE TITLE
How to add mailto links for the actionLink

### ISSUE THREAD

**Issue by ItsPugle** [vuejs/vuepress#93]
I'm setting up a dummy website using VuePress, and I don't know how to get the `actionLink` in the Front Matter for the Homepage to link to `mailto:tim@itspugle.ga`. At the moment, it's looking like this:
![VuePress Dummy Button](https://rpl.cat/uploads/2-yzUg84yyjQ0L8zE_weJYhAKhnepwUJbOPBM4tj0e0/public.png)

and the Front Matter is:
```
---
home: true
heroImage: /assets/header.jpg
actionText: Get in touch 📩
actionLink: mailto:tim@itspugle.ga
(features & footer down here)
---
```

When I click the button, it takes me to http://localhost:8080/mailto:tim@itspugle.ga.html

(Just to clarify, that email isn't working just yet 🙂)

**Comment by ItsPugle** [comment]
Sorry @yyx990803, but I don't know why you've closed this issue with that commit? I'm just asking a question about the functionality of VuePress locally, not reporting an issue.

**Comment by yyx990803** [comment]
Well that commit fixed the problem so it should handle mailto links properly now.

**Comment by ItsPugle** [comment]
Ah, awesome! Thanks 😄 Any idea on when this will go live?
