### ISSUE TITLE
[FR] displayAllHeaders until h2 → but until h3 when page is open.

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/vuepress#930]
## Feature request

`displayAllHeaders` can now be `true` or `false`. What I would love is to have all headers displayed but only if that relevant page is opened:

```
sidebarDepth: 2, // show headers in sidebar until h3
displayAllHeaders: 1 // to display all headers until level h2 (and h3 only when page is opened)
```

#### What problem does this feature solve?

I want to see nested headers until h3, but not for chapters that are not opened.

#### What does the proposed API look like?

```
sidebarDepth: 2, // currently already available
displayAllHeaders: 1 // choose until which depth it should displayAllHeaders
```

#### How should this be implemented in your opinion?

see above

#### Are you willing to work on this yourself?**

sure, but I'm not sure I'm good enough to do so...

**Comment by ulivz** [comment]
You can refer to the official guide column: https://vuepress.vuejs.org/guide.

That's what you want.

Ref: https://v0.vuepress.vuejs.org/default-theme-config/#multiple-sidebars
