### ISSUE TITLE
These two plugins work together incorrectly

### ISSUE THREAD

**Issue by iliyaZelenko** [vuejs/vuepress#933]
#### Version

v1.0.0-alpha.10

#### Steps to reproduce
These two plugins work together incorrectly:

- @vuepress/plugin-back-to-top
- @vuepress/plugin-pwa

![](https://i.imgur.com/VfWbhxh.png)

**Comment by ulivz** [comment]
This bug has been fixed at https://github.com/vuejs/vuepress/commit/4cc317f2f22c412b41a636b534ec61fe4f13974f#diff-1cefe56ea102fbc4a1a0e74446ac6c31.
