### ISSUE TITLE
Getting custom plugins to work

### ISSUE THREAD

**Issue by fen89** [vuejs/vuepress#934]
## Bug report

I tried to test writing a custom plugin with the newest vuepress version, but I didn't get it to work like explained on [Vuepress Docs](https://vuepress.vuejs.org/plugin/#writing-a-plugin).

I checked the source code for [@vuepress/last-updated](https://github.com/vuejs/vuepress/tree/master/packages/@vuepress/plugin-last-updated) and tried to adapt it to my test, without any effort.

#### Version
1.0.0-alpha.10

#### Steps to reproduce
Create the following structure:
```
.
├───docs/
│   ├───.vuepress/
│   │   ├───components/
│   │   │   └───PageSize.vue
│   │   ├───plugins/
│   │   │   └───page-size/
│   │   │       └───index.js
│   │   └───config.js
│   └───README.md
├───package.json
```
`docs/.vuepress/config.js`:
```js
module.exports = {
    plugins: [
        require('./plugins/page-size'),
    ]
}
```

`docs/.vuepress/plugins/page-size/index.js`:
```js
module.exports = (options, ctx) => ({
    name: 'my-page-time',
    extendPageData ({ _content }) {
        return {
            size: (_content.length / 1024).toFixed(2) + 'kb',
        };
    }
})
```

`docs/.vuepress/components/PageSize.vue`
```js
<template>
    <p>Page Size: {{ pageSize }}</p>
</template>

<script>
export default {
    name: 'PageSize',
    computed: {
        pageSize() { return this.$page.size || 'no value' },
    },
}
</script>
```

`docs/README.md`
```
# Hello Vuepress

<PageSize />
```

`package.json`
```
{
  "scripts": {
    "dev": "vuepress dev docs"
  },
  "dependencies": {
    "vuepress": "1.0.0-alpha.10"
  }
}
```

#### What is expected?

As the documentation says: Then you can use this value via `this.$page.size` in any Vue component.

#### What is actually happening?

`this.$page.size`remains empty.

- Plugin loads correctly:

![grafik](https://user-images.githubusercontent.com/4036376/46940360-dac01e00-d068-11e8-8f0e-2378502fc581.png)

- extendPageData gets called as well and returns correctly `size: "0.03kb"`

![grafik](https://user-images.githubusercontent.com/4036376/46940495-22df4080-d069-11e8-88c4-3d9a98f22bee.png)

![grafik](https://user-images.githubusercontent.com/4036376/46940929-33dc8180-d06a-11e8-9522-6e36feb7e51d.png)

But page renders without a value:

![grafik](https://user-images.githubusercontent.com/4036376/46940605-66d24580-d069-11e8-8125-6ae51d11fc30.png)

![grafik](https://user-images.githubusercontent.com/4036376/46940822-ea8c3200-d069-11e8-9d98-ff6e78fe461b.png)

Am I doing something wrong? Please let me know, any help would be appreciated!

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v8.12.0
- Is this a global or local install? Global and local, both same results
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Thanks for reporting this issue, and this issue was caused by the internal api change but we haven't updated the docs in time (sorry to waste your time in that, I mainly have my own job and I've been too busy lately.). 

I just updated the [documentation](https://vuepress.vuejs.org/plugin/#extendpagedata), hope it can help you.

**Comment by fen89** [comment]
Thanks @ulivz , got it working! There was no waste of time at all! Absolutely lovely project, I'm having super fun working with and diving into it! 👍
