### ISSUE TITLE
Plugin @vuepress/last-updated usage

### ISSUE THREAD

**Issue by chenweigao** [vuejs/vuepress#936]
Hi, there is a problem for me when using the plugin `last-updated`, my config is:
```
// in config.js
 themeConfig: {
    lastUpdated: "Last Updated: ",
    // ...
}
```
but when I build it, the information shows:
```
Invalid value for "pluginOptions" @vuepress/plugin-last-updated: expected a Object or Boolean
but got String.
```
what is the warning means?
this is my [repo](https://github.com/chenweigao/vueblog)

**Comment by ulivz** [comment]
Could you update your plugins' version to the latest version (`1.0.0-alpha.11`) and see if the warning exists?

```js
    "@vuepress/plugin-back-to-top": "^1.0.0-alpha.11",
    "@vuepress/plugin-i18n-ui": "^1.0.0-alpha.11",
    "@vuepress/plugin-medium-zoom": "^1.0.0-alpha.11",
    "@vuepress/plugin-notification": "^1.0.0-alpha.11",
    "@vuepress/plugin-pwa": "^1.0.0-alpha.11",
```

**Comment by chenweigao** [comment]
@ulivz thank you very much, according to what you said, I upgraded the plugin via
```
yarn add @vuepress/last-updated@next
```
then it works.

Thanks for your kind help, happy coding!
