### ISSUE TITLE
Allow both index.md for VuePress root and README.md for Git info

### ISSUE THREAD

**Issue by benhaynes** [vuejs/vuepress#944]
#### What problem does this feature solve?

Allows for a VuePress index page (`/index.md` -> `/index.html`) in addition to the common `/README.md` for the repository's info file. This would allow you to have a custom/informational README file displayed on git services such as GitHub instead of the VuePress homepage with YAML front-matter.

#### What does the proposed API look like?

I don't know if the API would change based on this feature.

#### How should this be implemented in your opinion?

The `/index.md` should take priority over the `/README.md` in the root when generating the `/index.html` file (the opposite is true now, with README taking priority). If this is too much of a breaking change, then an option or flag could be added to the VuePress config.js to manually set the default index file to build.

#### Are you willing to work on this yourself?**

I am willing to offer my time, but wouldn't know how to implement the change itself.

**Comment by ulivz** [comment]
This feature has been supported by https://github.com/vuejs/vuepress/pull/23
