### ISSUE TITLE
Add images to features on the home page template of the default theme

### ISSUE THREAD

**Issue by sergeyfilimonov** [vuejs/vuepress#946]
## Feature request

It would be great for the default theme to have images (like icons) in features on the home page template of the default theme.

#### What problem does this feature solve?

A home page would like nicer :) 

#### What does the proposed API look like?

No idea.

#### How should this be implemented in your opinion?

Images should be added in a YAML section of a home page. 

#### Are you willing to work on this yourself?**

Yes.

**Comment by ulivz** [comment]
See: https://github.com/vuejs/vuepress/issues/683#issuecomment-408924448
