### ISSUE TITLE
The button "Get Started ->" on https://vuepress.vuejs.org, is pointing to wrong page!

### ISSUE THREAD

**Issue by ememumoh** [vuejs/vuepress#95]
The button "**Get Started ->**" on https://vuepress.vuejs.org, is pointing to the wrong GitHub page!
![2018-04-17](https://user-images.githubusercontent.com/8033614/38848394-74993cac-41f6-11e8-97d8-b3bfc9048717.png) it should point to "https://github.com/vuejs/vuepress" not just "https://github.com" as it is now.

**Comment by yyx990803** [comment]
That was an accident... fixed
