### ISSUE TITLE
Deploying a Subgroup Project to GitLab Pages

### ISSUE THREAD

**Issue by seevee** [vuejs/vuepress#952]
#### Version
v0.14.4

#### Steps to reproduce

I've created a repo [here](https://gitlab.com/1-group-test/2-group-test/vuepress) to demonstrate. It should be a representative copy of the situation I encountered within a private project.

1. Create a GitLab group (https://gitlab.com/1-group-test)
2. Create a subgroup under the first group (https://gitlab.com/1-group-test/2-group-test)
3. Create a VuePress project under the subgroup (https://gitlab.com/1-group-test/2-group-test/vuepress)
4. Add GitLab Pages support as per VuePress documentation (.gitlab-ci.yml, base/dest in config.js)

#### What is expected?

A static site should be hosted at a known URL.

#### What is actually happening?

The documentation does not seem to cover this case.

No static site is hosted at any of the following URL patterns:

https://1-group-test.gitlab.io/vuepress
https://2-group-test.gitlab.io/vuepress
https://1-group-test.2-group-test.gitlab.io/vuepress
https://2-group-test.1-group-test.gitlab.io/vuepress
https://1-group-test.gitlab.io/2-group-test/vuepress
https://2-group-test.gitlab.io/1-group-test/vuepress

#### Other relevant information

- Your OS: Linux
- Node.js version: 10.12.0
- Browser version: Firefox 62.0.3
- Is this a global or local install? Global
- Which package manager did you use for the install? Problem presents with both Yarn and NPM installs. Demo project uses Yarn.

**Comment by Seven4X** [comment]
this gitlab 's bug 

https://docs.gitlab.com/ee/user/group/subgroups/#limitations

**Comment by shaheer-rahman** [comment]
Have you found a solution to this problem
