### ISSUE TITLE
希望能兼容多个命令启动不同项目

### ISSUE THREAD

**Issue by swordYWQ** [vuejs/vuepress#956]
问题： 不能正常用启动两个或多个命令来启动开发服务器环境
版本： vuepress@0.14.4
描述：目前通过**vuepress dev ./project1**单独运行是没有问题的，但是启动**vuepress dev ./project1**和**vuepress dev ./project2** 各自指定不同端口，命令能成功运行，但是项目2会把项目1覆盖（也即是访问项目1端口显示的是项目2的内容），希望能修复这个问题,谢谢。

**Comment by meteorlxy** [comment]
Duplicate of #355

**Comment by ulivz** [comment]
You can try the latest 1.x alpha version (we're going to release it). and set npm scripts as follows:

```
    "dev": "vuepress dev docs --temp .temp1",
    "build": "vuepress build docs --temp .temp2"
```
