### ISSUE TITLE
Is there a way to include variables from front-matter in a Markdown link

### ISSUE THREAD

**Issue by johnrengelman** [vuejs/vuepress#965]
Sorry if this is not the correct place to get this info. I'm very new Vue and Vuepress.
I'm trying to write documentation for a software project and I'm using Vuepress with markdown files.
I have lots of links that point out to an external site and I was wondering if there was a way for me including the base path in the front matter and then use that in the markdown link.

```
---
api: http://domain.com/api
---

This is the [link]({{ $page.api }}/path/to/a/file.html)
```

**Comment by fen89** [comment]
@johnrengelman you could write a custom component and embed it in your markdown, e.g. something like this: 

```
---
api: http://domain.com/api
---

This is the <ApiLink :to="/path/to/a/file.html"/>
```

Please see https://vuepress.vuejs.org/guide/using-vue.html#using-components for details

**Comment by ulivz** [comment]
`$page.api` is Vue runtime syntax but all markdown links are resovled at build time. so what you tried 
above doesn't work.

Just using HTML:

```
---
api: http://domain.com/api
---

This is the <a :href=" $page.frontmatter.actionLink + '/path/to/a/file.html' ">App</a>
```

**Comment by shongololo** [comment]
Just to clarify, I assume `actionLink` is a typo and should refer to `api`?

**Comment by ulivz** [comment]
@shongololo Updated. thanks

**Comment by rafi** [comment]
Using `<a href=""></a>` will cause a full refresh, I found that `<router-link to=""></router-link>` doesn't.

**Comment by f-w** [comment]
\<a\> doesn't show outbound icon for outbound link.
