### ISSUE TITLE
GraphQL support to work with data sources and headless CMS

### ISSUE THREAD

**Issue by sergeyfilimonov** [vuejs/vuepress#968]
## Feature request

To be a complete replacement for Gatsby, VuePress has to work with data sources via GraphQL.

#### What problem does this feature solve?

No headache to work with static markdown files.

#### What does the proposed API look like?

No idea :(

#### How should this be implemented in your opinion?

Just like in Gatsby.

#### Are you willing to work on this yourself?**

No, I don't have skills enough for this task.

**Comment by ekoeryanto** [comment]
maybe you should try https://npm.im/gridsome

**Comment by sergeyfilimonov** [comment]
> maybe you should try https://npm.im/gridsome

wow! thanks! this is what I was looking for! Gatsby is great but making static website with React is too much unnecessary code.

**Comment by ulivz** [comment]
To report an issue that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. [vuepress-issue-example](https://github.com/ocavue/vuepress-issue-example)), otherwise I don't know where you are going wrong.

**Comment by rufuspollock** [comment]
I'd like to suggest re-opening this. Gridsome is great but with page generation support now in the plugins i think it would be nice at least to have a recipe for how one could set this up with pure vuepress - I ❤️ the simplicity of vuepress and being able to pull wordpress content would be super useful.
