### ISSUE TITLE
How i can add .babelrc file use plugin babel-plugin-import lazyload ui-component

### ISSUE THREAD

**Issue by youxfans** [vuejs/vuepress#969]

**Comment by ulivz** [comment]
```js
  config.module
    .rule('js') // Find the rule.
      .use('babel-loader') // Find the loader
      .tap(options => Object.assign(options, { // Modifying options
        plugins: ['babel-plugin-import']
      }))
```

Ref: [webpack-chain > Config module rules uses> modifying options](https://github.com/neutrinojs/webpack-chain#config-module-rules-uses-loaders-modifying-options)

**Comment by youxfans** [comment]
```
// config.js

  chainWebpack: (config, isServer) => {
    config.module
    .rule('js') // Find the rule.
      .use('babel-loader') // Find the loader
      .tap(options => Object.assign(options, { // Modifying options
        plugins: ['babel-plugin-import']
      }))
  }

```

Error: 
ERROR in ./node_modules/_@vuepress_core@1.0.0-alpha.15@@vuepress/core/lib/app/clientEntry.js
Module build failed (from ./node_modules/_babel-loader@8.0.0-beta.3@babel-loader/lib/index.js):

**Comment by youxfans** [comment]
where ask question ;)

**Comment by ulivz** [comment]
[Discord server](https://vue-land.js.org/) (Recommended), [forum](https://forum.vuejs.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress) 🙂

**Comment by youxfans** [comment]
Response timeout  WTF GFW~

**Comment by ulivz** [comment]
If you can't even get over the wall... I can't help you nothing.

**Comment by youxfans** [comment]
Thinks. u are nice and Helpful man.
I have solved the problem

```js
  chainWebpack: (config, isServer) => {
    config.module
      .rule('js') // Find the rule.
      .use('babel-loader') // Find the loader
      .tap(options => Object.assign(options, { // Modifying options
        plugins: [
          ["import", {
            "libraryName": "ant-design-vue",
            "libraryDirectory": "es",
            "style": "css"
          }]
        ]
      }))
  }
js

**Comment by ulivz** [comment]
Cool, so we just forgot options for this plugin (I don't know and don’t use it). but you should know this is not very safe if the internal babel options has occupied the `plugins` option.

**Comment by cugb-xieyu** [comment]
Thank you for your research on the configuration, this problem troubles me a lot.
