### ISSUE TITLE
About Multiple Sidebars fallback of redirect

### ISSUE THREAD

**Issue by my9074** [vuejs/vuepress#970]
## Bug report

In  Multiple Sidebars mode, I can't config sidebar to redirect ```/components/``` with ```/``` root path

directory structure:
```shell
├── components
│   ├── README.md
│   ├── i18n.md
│   ├── quickstart.md
│   └── text.md
└── guide
    └── FAQ.md
```
config.js
```js
sidebar: {
   '/components/': [
     '',
     ['quickstart', 'Quick Start'],
     ['i18n', 'Internationalization'],
     {
       title: 'components',
       collapsable: false,
       children: [['text', 'Text']]
      }
   ],
   '/guide/': ['FAQ'],
   '/': ['']   // how to config to redirect '/components/' ???
}
```

#### Version
0.14.4
#### What is expected?
Sidebar provides a property that supports redirect to other route
#### Other relevant information
-
- Your OS: MacOS 10.13
- Node.js version:  8.11.*
- Browser version:  Chrome 70+
- Is this a global or local install?  local
- Which package manager did you use for the install? npm

**Comment by ronggang** [comment]
sidebar: {
   '/components/': [
     '',
     ['quickstart', 'Quick Start'],
     ['i18n', 'Internationalization'],
     {
       title: 'components',
       collapsable: false,
       children: [['text', 'Text']]
      }
   ],
   '/guide/': ['FAQ'],
   '/': ['', '/components/']   // Is this what you mean?
}

**Comment by my9074** [comment]
@ronggang  Such a configuration cannot be achieved by jumping from the root directory to the specified url. I expect to automatically jump to the `http://xxxx/vue-components-webpack4/components` URL when entering the `http://xxxx/vue-components-webpack4/` URL

**Comment by my9074** [comment]
@ronggang  It's work.  thx for  your help
