### ISSUE TITLE
[Feature] Offical Vuepress docker container

### ISSUE THREAD

**Issue by heyheni** [vuejs/vuepress#974]
#### What problem does this feature solve?
Hassle free quick deployment of Vuepress for Cloud and **Intranet** usage.
Ready made documentation system for your company. Usable even by non techy office clercs.
#### What does the proposed API look like?
docker install vuepress
#### How should this be implemented in your opinion?
The container should have: Vuepress, Git, NetliflyCMS, NGNIX
#### Are you willing to work on this yourself?**
No, my docker-fu is only consumer level.

**Comment by meteorlxy** [comment]
> ### What does the proposed API look like?
> docker install vuepress

I didn't know there is a `docker install` command 😅

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, but this repo shouldn't be responsible for this feature, and this feature looks like a very special need, (Vuepress, Git, NetliflyCMS, NGNIX ? Sorry but most of users don't need it.)

You can create and publish it by yourself.

**Comment by avimehenwal** [comment]
I still wonder if there is any official vuepress docker container anywhere?
I am unable to make it work on `Linux parrot 5.4.0-4parrot1-amd64` and hence for looking for a quick container to test it out. 
Kindly point me to right direction
