### ISSUE TITLE
.vuepress/style.styl does not take effect in the production environment

### ISSUE THREAD

**Issue by xnng** [vuejs/vuepress#977]
- [x] I confirm that this is a issue rather than a question.

## Bug report

.vuepress/style.styl can not use in production enviroment，but in development enviroment is available

when I `vuepress`

#### Version

0.14.4

#### Steps to reproduce

I want to override some of the styles. I created .vuepress/style.styl and it took effect after I `vuepress dev` it, but it didn't take effect after I `vuepress build` it.

I tried both on windows and CentOS, and they all had the same effect.

Do I need additional configuration to add this file? I didn't see it in the document.

#### What is expected?

I hope than `.vuepress/style.styl` can use in dev and prod enviroment。

This is my css：

![image](https://user-images.githubusercontent.com/38936252/47961285-3c115680-e043-11e8-97c7-c936e7d27d32.png)

This is dev：

![image](https://user-images.githubusercontent.com/38936252/47961690-c3ae9380-e04a-11e8-949c-91323f61c8a0.png)

This is prod：

![image](https://user-images.githubusercontent.com/38936252/47961697-e345bc00-e04a-11e8-84ac-3dd71b06e5dd.png)

I found a way to solve my problem，add `!important` like this ：

![image](https://user-images.githubusercontent.com/38936252/47961972-248c9a80-e050-11e8-8a41-a328fd15dd39.png)

#### What is actually happening?

After I build it, `.vuepress/style.styl` didn't work.

#### Other relevant information

- Your OS: Win 10 1803 and CentOS7
- Node.js version: 10.13.0
- Browser version: 70.0.3538.77
- Is this a global or local install?  I've tried all of it
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Could you provide the reproduction repo?

**Comment by xnng** [comment]
> Could you provide the reproduction repo?

Thank you for the reply，the repo is [https://github.com/xnng/vuepress-test](https://github.com/xnng/vuepress-test)

**Comment by ulivz** [comment]
Hey, thanks for your repro, this is an issue caused by this [commit](https://github.com/webpack-contrib/mini-css-extract-plugin/commit/dd141f2aacddbb30d9129a14425085b11f3cba8d) of [webpack-contrib/mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin).

`mini-css-extract-plugin > 0.4.2` is not compatible in VuePress. in 0.14.x you can lock the version via `resolutions` and re-install by yarn.

```
  "resolutions": {
    "mini-css-extract-plugin": "0.4.1"
  }
```
