### ISSUE TITLE
Badge does not work

### ISSUE THREAD

**Issue by quanzaiyu** [vuejs/vuepress#979]
- [x] I confirm that this is a issue rather than a question.

## Bug report

Component `Badge`  does not work :

![image](https://user-images.githubusercontent.com/13745132/47963117-47c04580-e062-11e8-9c9f-67e697303ccf.png)

#### Version

1.0.0-alpha.17

#### What is expected?

Component `Badge`  works well.

#### Other relevant information

- Your OS: Win10 Edu 1803
- Node.js version:  v10.11.0
- Browser version:  Chrome 70
- Is this a global or local install?  local
- Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Badge was included in the default theme.
