### ISSUE TITLE
some problem of use gitalk in vuepress 

### ISSUE THREAD

**Issue by Viking1726** [vuejs/vuepress#982]
```
<common-gitalk></common-gitalk>

```

```
<template>
    <div id="gitalk-container"></div>
</template>

```

```
 mounted() {
            this.gitalk.render("gitalk-container");
        }
```

```
Rendering page: / FAIL  Error rendering /:
Error: render function or template not defined in component: common-gitalk
    at normalizeRender (/Users/viking/Documents/v-press/node_modules/vue-server-renderer/build.js:7407:13)
    at renderComponentInner (/Users/viking/Documents/v-press/node_modules/vue-server-renderer/build.js:7531:3)
    at renderComponent (/Users/viking/Documents/v-press/node_modules/vue-server-renderer/build.js:7502:5)
    at resolve (/Users/viking/Documents/v-press/node_modules/vue-server-renderer/build.js:7563:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ docs:build: `vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Viking1726** [comment]
this happened when i wasing run build prepare to deploy

**Comment by ulivz** [comment]
1. Issue wasn't created to ask questions, it should be issue or pull request.
2. Removing the issue template isn't very friendly.
2. According to the error message, this should be the issue of your component `<common-gitalk>`

> Closing this since it's a question, you can create an issue if it's truly turned out to be a bug.

**Comment by Viking1726** [comment]
Thanks for your reply. I'm not sure that's a bug or not , the component was good with run dev , when I run build the error show up.

在 2018-11-06 21:09:50，ULIVZ <notifications@github.com> 写道：

Issue wasn't created to ask questions, it should be issue or pull request.
Removing the issue template isn't very friendly.
According to the error message, this should be the issue of your component <common-gitalk>

Closing this since it's a question, you can create an issue if it's truly turned out to be a bug.

**Comment by ulivz** [comment]
So at least you should provide the component/reproduction repo.

**Comment by Viking1726** [comment]
<template>
<div id="gitalk-container"></div>
</template>

<script>
import Gitalk from 'gitalk'

export default {
name: "gitalk",
data() {
return {
myGitComment: new Gitalk({
clientID: '....',
clientSecret: '.....',
repo: '....',
owner: '....',
admin: ['....'],
//id: location.pathname, // Ensure uniqueness and length less than 50
id: window.location.hash, // Ensure uniqueness and length less than 50
distractionFreeMode: false, // Facebook-like distraction free mode
language: 'zh-CN',
})
}
},
mounted() {
this.myGitComment.render("gitalk-container");
}
}
</script>

<style scoped>

</style>






At 2018-11-07 10:43:41, "ULIVZ" <notifications@github.com> wrote:


So at least you should provide the component/reproduction repo.

**Comment by ulivz** [comment]
Hmmmm, you should provide a valid reproduction repo.

**Comment by Viking1726** [comment]
At 2018-11-08 11:35:38, "ULIVZ" <notifications@github.com> wrote:


Hmmmm, you should provide a valid reproduction repo.

**Comment by Viking1726** [comment]
Do you need my configuration parameters?

clientID: '9b600a5cc026d65c9bb2',
clientSecret: '6978d7f1f640b38b7e52fb0df795878fa3c1fc85',
repo: 'Viking1726.github.io',
owner: 'Viking1726',
admin: ['Viking1726'],

At 2018-11-08 11:35:38, "ULIVZ" <notifications@github.com> wrote:


Hmmmm, you should provide a valid reproduction repo.
