### ISSUE TITLE
404 not found:cache-loader@1.2.2

### ISSUE THREAD

**Issue by dbs2009hdu** [vuejs/vuepress#983]
- [ ] I confirm that this is a issue rather than a question.

#### Version
lastest
#### Steps to reproduce
when i install in cmd:npm install -g vuepress
npm error! code E404
npm error:404 Not Found:cache-loader1.2.2

#### Other relevant information

- Your OS: windows 7
- Node.js version: v8.9.4
- Browser version: 
- Is this a global or local install? gobal install
- Which package manager did you use for the install?
npm

**Comment by ulivz** [comment]
Try: `npm view cache-loader@1.2.2`.
