### ISSUE TITLE
Add Ability to specify how deep page headers should go

### ISSUE THREAD

**Issue by bretterer** [vuejs/vuepress#984]
## Feature request
It would be nice to have the ability to specify how deep the `extractHeaders` method goes.
Currently, it has a hard coded value of `['h2', 'h3']`
Our current markdown files use `h4` as well in order to handle some table of contents for the page in sidebar form.

#### What problem does this feature solve?
When doing a table of contents in the sidebar, this feature would allow you to specify how deep the TOC should go based on headers.

#### What does the proposed API look like?
config.js
```
module.exports = {
    themeConfig: {
        parseHeaders: ['h2','h3','h4']
    }
}
```

#### How should this be implemented in your opinion?
The above would be a themeConfig option and will replace the default hard coded value located at 
https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/prepare/Page.js#L92

#### Are you willing to work on this yourself?**
Yes

**Comment by Leedehai** [comment]
This is a much needed feature.
Additionally, I wish the sidebar is able to handle "skipped" headings, i.e. a `h3`-level heading directly under `h1` without `h2` in between, and a `h4`-level heading directly under `h2` without `h3` in between. Like so:
```
h1
|-- h3
|-- h2
      |-- h4
      |-- h3
             |-- h4
```

**Comment by bretterer** [comment]
Looking into how to code this, Once issue is it seems that currently, the Page.js does not have access to the config file.  I have been looking for samples of the `prepare` files requiring the config file and and falling short.  It may require some re-structure/re-work of how that is set

**Comment by youxfans** [comment]
Welcome to pull requests, This is a much needed feature.

**Comment by Leedehai** [comment]
Heck, even Vuepress's own [README](https://github.com/vuejs/vuepress/blob/master/README.md) contains skipped headings: a `h2` heading ("Status") is above the `h1` heading ("Vuepress"). :)

**Comment by bretterer** [comment]
Picking this up this week.  Targeting to have a PR by the end of week

**Comment by pianoboysai** [comment]
this is obviously necessary.

**Comment by bretterer** [comment]
@pianoboysai I believe this was merged in through another PR https://github.com/vuejs/vuepress/pull/1945 after being told to "[avoid wasting your time](https://github.com/vuejs/vuepress/pull/1004#issuecomment-472504377)" and let the "[feature be implemented by official collaborators](https://github.com/vuejs/vuepress/pull/1004#issuecomment-472504377)"
