### ISSUE TITLE
doesn't support checkbox in markdown

### ISSUE THREAD

**Issue by ch957869975** [vuejs/vuepress#986]
- [ ] I confirm that this is a issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by youxfans** [comment]
https://github.com/revin/markdown-it-task-lists

**Comment by youxfans** [comment]
```
module.exports = {
  markdown: {
    config: md => {
      md.use(require('markdown-it-task-lists'))
    }
  }
}
```

**Comment by meision** [comment]
This is not exactly same with https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/
add follow css in override.styl to remove leading dots.

.contains-task-list LI
{
    list-style-type:none;
}

**Comment by maartenvanderhoef** [comment]
As per 1.0, extendMarkdown
```javascript
module.exports = {
  markdown: {
    extendMarkdown: md => {
      md.use(require('markdown-it-task-lists'))
    }
  }
}
```
.vuepress/styles/index.styl
```css
.contains-task-list LI
{
list-style-type:none;
}
```

**Comment by iszmxw** [comment]
> As per 1.0, extendMarkdown
> 
> ```js
> module.exports = {
>   markdown: {
>     extendMarkdown: md => {
>       md.use(require('markdown-it-task-lists'))
>     }
>   }
> }
> ```
> 
> .vuepress/styles/index.styl
> 
> ```css
> .contains-task-list LI
> {
> list-style-type:none;
> }
> ```

感谢，成功解决问题

**Comment by justforuse** [comment]
For your information, if you are using vuepress-next, the config file should be:

```
module.exports = {
	// ...
	extendsMarkdown: md => {
	  md.use(require('markdown-it-task-lists'))
	}
}
```

**Comment by sweihub** [comment]
Thanks for the answer by @maartenvanderhoef, to clarify for newbie, the complete steps for VuePress 1.x + tasklists

1. Install markdown-it-task-lists
```
npm install markdown-it-task-lists
```
2. Edit ```src/.vuepress/config.js```, add the `markdown` node
```js
module.exports = {
  markdown: {
    extendMarkdown: md => {
      md.use(require('markdown-it-task-lists'))
    }
  }
}
```
3. Remove the dot before tasks, edit file `.vuepress/styles/index.styl`
```css
.contains-task-list LI {
list-style-type:none;
}
```

4. Restart the VuePress
