### ISSUE TITLE
Change content path

### ISSUE THREAD

**Issue by simonwjackson** [vuejs/vuepress#988]
#### What problem does this feature solve?
Isolate content to a specific subdirectory.

A subdirectory as the content entrypoint, would make it trivial to sync the content elsewhere (dropbox, google drive, etc) and then be edited by non-techies.

#### What does the proposed API look like?
`config.js`

```js
module.exports = {
  content: "./myContentDir" // sets the directory entry point for site content
}
```

#### Are you willing to work on this yourself?**

Yes, just need some advice on what files / variables to look out for

**Comment by ulivz** [comment]
Try `vuepress dev [targetDir]`.

**Comment by simonwjackson** [comment]
Thanks for the input, but i'm not sure this solves the problem.

This solution still requires the `.vuepress` directory to be included inside `[targetDir]`

`folder structure`
```
- package.json
- .vuepress
- node_modules
- myContentDir
  |
  - README.md
  - About.md
  - subFolder
    |
    - README.md
    - AnotherPage.md
```
