### ISSUE TITLE
Let user specify Markdown preprocessor before compiling

### ISSUE THREAD

**Issue by Leedehai** [vuejs/vuepress#989]
## Feature request
I wish in `config.js` I'm able to specify a preprocessor script that will be invoked before feeding the each markdown into markdown-it for Markdown-to-HTML conversion.

For example, I have a script called `preprocess.py`, then instead of compiling `myfile.md` directly into `myfile.html`, I hope Vuepress would invoke `preprocess.py` to process `myfile.md` and generate a temporary markdown file, and feed that temporary file to markdown-it.

Current:
```
`myfile.md` --> markdown-it --> `myfile.html`
```
Proprosed:
```
`myfile.md` --> preprocessor script (if provided by user) --> `myfile.temporary.md` --> markdown-it --> `myfile.html`
```

#### What problem does this feature solve?
Users may want their markdown files rendered beautifully on GitHub while leveraging Vuepress's ability to build website.

However, a markdown file understood by Vuepress may be rendered poorly on GitHub, e.g. the YAML front matter will be displayed on GitHub ([example](https://github.com/vuejs/vue-cli/blob/dev/docs/README.md)). Another example is GitHub doesn't understand footnotes, while Vuepress's markdown-it supports footnotes extension. A third example is Vuepress's custom container `::: tip` will be rendered literally on GitHub ([example](https://github.com/vuejs/vue-cli/blob/dev/docs/guide/README.md))

Therefore, a user may want to write their own preprocessor script for the markdown files that were originally intended for GitHub. This preprocessor script will add Vuepress-specific stuff or replace some strings in that file to the temporary markdown file, and Vuepress will compile that temporary file to HTML.

This way, user's documentation will look nice on **both** venue: the GitHub and the Vuepress-generated website.

**By the way, [this is my preprocessor script](https://gist.github.com/Leedehai/28107137868fc8c847a7e4c681eaf2dd) with a unit test (on Mac, Python2.7)** 
#### What does the proposed API look like?
In `config.js` add a new attribute:
```
module.export = {
...
markdownPreprocessor: "user-custom-preprocessor.py" // or "xxx.sh", "xxx.rb", ...
...
}
```
Its default value is `""`, i.e. do not invoke preprocessor, and directly feed markdown files to markdown-it, like the current implementation.
#### How should this be implemented in your opinion?
Sorry I don't know.. but it seems it shouldn't be very hard? (I may be wrong)
#### Are you willing to work on this yourself?**
Sorry I know very little about JS..

**Comment by youxfans** [comment]
add extra scripts in your ```package.json```
like
```
  "scripts": {
    "dev:vuepress": "yarn workspace blog build",
    // dev/build for github format
    "dev:github": "python user-custom-preprocessor.py && yarn workspace blog dev"
  },
```

**Comment by Leedehai** [comment]
@youxfans ha that works!
It further proves that I'm not familiar with node.js... :( learning

Please close this FR.
