### ISSUE TITLE
Ability to disable built-in markdown extensions

### ISSUE THREAD

**Issue by Ambyjkl** [vuejs/vuepress#991]
## Feature request

Imo would be nice to be able to disable things like syntax highlighting with prismjs when they are never going to be used, so that they don't end up in the bundle.

#### What problem does this feature solve?
Help chop a few kilobytes off the bundle when possible.

#### What does the proposed API look like?
Probably some keys under `markdown` in the config.

#### How should this be implemented in your opinion?
Same as above

#### Are you willing to work on this yourself?**
Sure. I don't know if this is already in the works, but if that's not the case I can try and implement this myself.

**Comment by ulivz** [comment]
✨Support it at `1.0.0-alpha.21`, for document see [here](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/markdown#removeallbuiltinpluginsconfig-chainmarkdown).

**Comment by Ambyjkl** [comment]
Well, it seems to remove almost all unnecessary plugins, but the syntax highlighting plugin is still left included.
